### ISSUE TITLE
Implement Default stride Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#100]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, stride() should return a tuple. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by Ujjwal-9** [comment]
I will do it.

**Comment by Ujjwal-9** [comment]
@iamtrask according to pytorch docs stride() returns a tuple not a tensor.
you can check [here](http://pytorch.org/docs/master/tensors.html#torch.Tensor.stride)

**Comment by iamtrask** [comment]
ahhh yes!

**Comment by iamtrask** [comment]
let's follow that convention :)

**Comment by Ujjwal-9** [comment]
@iamtrask then could you edit the issue :smile:

**Comment by iamtrask** [comment]
done ;)

**Comment by vbankov** [comment]
i would like to pick this one up. @Ujjwal-9 do you have any update?

**Comment by Ujjwal-9** [comment]
@vbankov its done. PR is in review process

**Comment by vbankov** [comment]
@Ujjwal-9 no worries :), feel free to copy any of my tests if you'd like
