### ISSUE TITLE
Implement Default tolist(), topk(), and trace() Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#104]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, tolist(), topk(), and trace() should return new tensors. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by aqibsaeed** [comment]
Please review PR #201 for implementation.

**Comment by aneesh-joshi** [comment]
Hey @aqibsaeed , @kevinahuber 
I am trying to implement tolist() for IntTensor and this PR seems to have already done some of that work.

However, after seeing the PR and it's changed files, I don't see the same changes reflected in the current master.

Could you help me out?

**Comment by bharathgs** [comment]
@aneesh-joshi  this was done for the older version of pysyft, which has been deprecated. 

The issues related for the new ones, both float and int are still open and they can be found [here](https://github.com/OpenMined/PySyft/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+tolist)
and the resources that you might need to implement can also be found in the issue description.

**Comment by aneesh-joshi** [comment]
Thanks for the info.

Is the deprecation present because openmined moved to unity?
