### ISSUE TITLE
__mul__ not correctly implemented

### ISSUE THREAD

**Issue by erfannoury** [OpenMined/PySyft#118]
In the `PaillierFloat` implementation, multiplication with another `PaillierFloat` is also implemented, whereas in the `python-paillier` library, it is not possible to multiply two `EncodedNumber`s ([ref.](https://github.com/n1analytics/python-paillier/blob/master/phe/paillier.py#L746-L748)).

https://github.com/OpenMined/PySyft/blob/16dae46b154dd755c18e941409b4ec771f5e2ca5/syft/he/Paillier.py#L97

**Comment by iamtrask** [comment]
Great catch! Fixed. :)
