### ISSUE TITLE
Set up CI for automated testing and style checks

### ISSUE THREAD

**Issue by samsontmr** [OpenMined/PySyft#119]
Now that our codebase is growing (hooray!), we should set up CI for automated testing and style checks (PEP8, PEP257). 

Choices include [CircleCI](https://circleci.com) and [TravisCI](https://travis-ci.org). These can be integrated into our repo such that every pull request will be checked before review.

**Comment by dmonn** [comment]
I have used Travis before and could set it up to run tests and check for any style guide violations tomorrow. Assign it to me if nobody else is already working on it.

Quick question: Should the build fail if something violates PEP8/PEP257?

**Comment by samsontmr** [comment]
> Quick question: Should the build fail if something violates PEP8/PEP257?

Yes!

**Comment by swaroopch** [comment]
I would recommend using https://pypi.python.org/pypi/flake8
