### ISSUE TITLE
Failed to install Syft on MacOs

### ISSUE THREAD

**Issue by kidinamoto01** [OpenMined/PySyft#125]
Hello,
I followed the instructions to install PySyft.
But I failed to get all the dependencies after running 
`pip install -r requirements.txt`

the Error messages are the following:
`Collecting singledispatch (from tornado>=4->notebook->jupyter->-r requirements.txt (line 5))
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Requirement already satisfied: certifi in /Library/Python/2.7/site-packages (from tornado>=4->notebook->jupyter->-r requirements.txt (line 5))
Collecting backports_abc>=0.4 (from tornado>=4->notebook->jupyter->-r requirements.txt (line 5))
  Downloading backports_abc-0.5-py2.py3-none-any.whl
Requirement already satisfied: functools32; python_version == "2.7" in /Library/Python/2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->nbconvert->jupyter->-r requirements.txt (line 5))
Collecting webencodings (from html5lib>=0.99999999->bleach->nbconvert->jupyter->-r requirements.txt (line 5))
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: gmpy2, phe, decorator, ipython-genutils, traitlets, scandir, pathlib2, wcwidth, prompt-toolkit, pickleshare, appnope, IPython, line-profiler, mistune, jupyter-core, nbformat, configparser, entrypoints, pandocfilters, testpath, webencodings, html5lib, bleach, nbconvert, singledispatch, backports-abc, tornado, python-dateutil, pyzmq, jupyter-client, ipykernel, terminado, notebook, jupyter-console, widgetsnbextension, ipywidgets, qtconsole, jupyter, args, clint
  Running setup.py install for gmpy2 ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-rPx3Nd/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RaN8cm-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'gmpy2' extension
    creating build
    creating build/temp.macosx-10.11-intel-2.7
    creating build/temp.macosx-10.11-intel-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DWITHMPFR -DWITHMPC -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/gmpy2.c -o build/temp.macosx-10.11-intel-2.7/src/gmpy2.o
    In file included from src/gmpy2.c:426:
    src/gmpy.h:252:12: fatal error: 'mpfr.h' file not found
    #  include "mpfr.h"
               ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-rPx3Nd/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RaN8cm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-rPx3Nd/gmpy2/`

**Comment by erfannoury** [comment]
I recommend installing the tricky packages using `conda`. You can install the rest (which are not on the anaconda cloud) using `pip`.

**Comment by cypherai** [comment]
This is maybe because you need specific OS depencies to install Syft. I resolved this issue in ubuntu by installing:

``ˋ
libgmp-dev
libmpfr-dev
libmpc-dev
ˋ`ˋ

You could probably install these with the brew macOS package manager and retry Syft installation.

**Comment by swaroopch** [comment]
Try installing https://github.com/OpenMined/PySonar/blob/master/README.md#base-libraries before pip install

**Comment by filangel** [comment]
@swaroopch's solution worked on MacOS

**Comment by iamtrask** [comment]
@swaroopch should we add this to the PySyft readme under just MacOs or others more generally?

**Comment by swaroopch** [comment]
@iamtrask Added https://github.com/OpenMined/PySyft/pull/203
