### ISSUE TITLE
Support extended slicing of TensorBase objects

### ISSUE THREAD

**Issue by samsontmr** [OpenMined/PySyft#129]
Extended slicing in Python is an extremely useful operation supported by major libraries like Numpy and Pandas. Therefore, we would like our TensorBase objects to support this operation as well. This [StackOverflow answer](https://stackoverflow.com/a/509295) contains a good explanation of how it works.

Since we are wrapping `numpy`'s `ndarray` in our TensorBase classes, a way of implementing it would be to pipe the operations through to `numpy`'s implementation.

**Acceptance criteria**
* Contains unit tests demonstrating indexing, slicing, and step behavior.

**Comment by aqibsaeed** [comment]
Would you be more specific or provide a bit more detail of this ticket? I mean, do you want a slicing function to be implemented?

**Comment by siarez** [comment]
This seems to be working already. Should we close this? Or am I missing something?

```
>>> from syft import TensorBase
>>> import numpy as np
>>> t1 = TensorBase(np.array([[1, 2, 3], [4, 5, 6]]))
>>> t1
array([[1, 2, 3],
       [4, 5, 6]])

>>> t1[:]
array([[1, 2, 3],
       [4, 5, 6]])

>>> t1[1:2]
array([[4, 5, 6]])

>>> t1[1:2, 0]
array([4])

>>> t1[1:2, 1:3]
array([[5, 6]])

>>> t1[:,::2]
array([[1, 3],
       [4, 6]])
```
