### ISSUE TITLE
Caching in Travis build

### ISSUE THREAD

**Issue by jvmancuso** [OpenMined/PySyft#1330]
Currently, we're using Travis for CI.  At the moment, it's doing a fresh install of all dependencies.  We should be caching static, bulky dependencies like PyTorch, so as to improve the build time.  More information at this link: https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)

**Comment by iamtrask** [comment]
I think you're right! Great find Rohan!

**Comment by Nivek92** [comment]
@iamtrask @jvmancuso could someone close this issue as it seems to be resolved already?
