### ISSUE TITLE
Profiling Tensor Registration and Message Passing

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1354]
see @jvmancuso 's comment elow

**Comment by jvmancuso** [comment]
I think this is part of a larger issue where we should profile operations and tensor sending/receiving to definitively understand where the bottlenecks are.  Then we can prioritize optimization efforts analytically/rigorously.

**Comment by lucaslopes** [comment]
Knows which function is calling `register_object` might be helpful?
```
>>> import inspect
>>> def f1(): f2()
>>> def f2():
        curframe = inspect.currentframe()
        calframe = inspect.getouterframes(curframe, 2)
        print 'caller name:', calframe[1][3]
>>> f1()
caller name: f1
```
[Source](https://stackoverflow.com/questions/2654113/python-how-to-get-the-callers-method-name-in-the-called-method)
