### ISSUE TITLE
Mnist Example Not Working For GPU

### ISSUE THREAD

**Issue by santanu-2018** [OpenMined/PySyft#1381]
## Context

The new experimental example on training MNIST dataset works fine without GPU. But, throws error messages when GPU is used.

For Working CPU version, see this : https://colab.research.google.com/drive/1cpTIxtebCMRsHEmJreI7ycyzS42OjXM8 
(Run without enabling GPU)

### Test Configuration

Colab Python 3
PyTorch - 0.3.0

### Expected Behavior

The Code should work fine with GPU as it worked with CPU.

### Current Behavior

Throws Error Messages

### Steps to Reproduce

Run the GPU colab notebook link with GPU activated.
 

For GPU version, see this: https://colab.research.google.com/drive/1U6B3mp2dK0gDW1UwlBSVWS0iKF6DNplU

**Comment by iamadarshk** [comment]
Hey, can I take up the issue if not already taken?

**Comment by kamathhrishi** [comment]
We still haven't Inherited the methods required for it to work on GPU.
