### ISSUE TITLE
N-ary methods/iterable methods do not work remotely

### ISSUE THREAD

**Issue by alhparsa** [OpenMined/PySyft#1396]
# Issue Template
### User Story:
When iterable methods are called on remote objects, the get() method returns an empty tensor. See expected and current behavior for more info.

`torch.stack` and `torch.cat` are great examples of such methods.
[torch.stack](https://pytorch.org/docs/0.3.1/torch.html#torch.stack)
[torch.cat](https://pytorch.org/docs/0.3.1/torch.html#torch.cat)

## Expected Behavior
```
>>> x = torch.FloatTensor([1,2,3,4]).send(remote)
>>> y = torch.FloatTensor([3,4,1,2]).send(remote)
>>> z = torch.FloatTensor([5,2,1,4]).send(remote)
>>> torch.stack([x,y,z]).get()

 1  2  3  4
 3  4  1  2
 5  2  1  4
[torch.FloatTensor of size 3x4]
```

## Current Behavior
What is the current behavior?
```
>>> x = torch.FloatTensor([1,2,3,4]).send(remote)
>>> y = torch.FloatTensor([3,4,1,2]).send(remote)
>>> z = torch.FloatTensor([5,2,1,4]).send(remote)
>>> torch.stack([x,y,z]).get()
[torch.FloatTensor with no dimension]
```
## Failure Information (for bugs)
When iterable methods are called on remote objects, the get() method returns an empty tensor. 
### Steps to Reproduce (for bugs)

Please provide detailed steps for reproducing the issue. (for bugs)

```
>>> x = torch.FloatTensor([1,2,3,4]).send(remote)
>>> y = torch.FloatTensor([3,4,1,2]).send(remote)
>>> z = torch.FloatTensor([5,2,1,4]).send(remote)
>>> torch.stack([x,y,z]).get()
```

**Comment by alhparsa** [comment]
For such methods, arrays are not supported as an argument and a tensor of tensors should be only used.

**Comment by jvmancuso** [comment]
Hey @alhparsa, I'm reopening this.  Maintaining the original semantics of PyTorch is very important, and I think this should be covered when #1395 lands.  We'll close when that happens.

**Comment by LaRiffle** [comment]
Yes, my PR fix this, I will add a unit test

**Comment by bartimaeus12** [comment]
doing this works for stack and cat
torch.stack([x.get(),y.get(),z.get()])

 1  2  3
 2  3  4
 5  6  7
[torch.FloatTensor of size 3x3]

I added the unittests based on this.

**Comment by alhparsa** [comment]
This also works!

```
t = torch.FloatTensor([x,y,z]).get()
torch.stack(t)
```
