### ISSUE TITLE
Missing docstrings in TorchHook

### ISSUE THREAD

**Issue by jvmancuso** [OpenMined/PySyft#1412]
Some methods in TorchHook need docstrings.  In particular, some of the original hooking methods (for example [here](https://github.com/OpenMined/PySyft/blob/47f2044d187480150a5a1d253466935dff92db6e/syft/core/hooks/torch/hook.py#L1069) and [here](https://github.com/OpenMined/PySyft/blob/47f2044d187480150a5a1d253466935dff92db6e/syft/core/hooks/torch/hook.py#L1027) and [here](https://github.com/OpenMined/PySyft/blob/47f2044d187480150a5a1d253466935dff92db6e/syft/core/hooks/torch/hook.py#L1042)) are missing them, as well as all the fixed precision ones (mainly [all of the ones in this guy here](https://github.com/OpenMined/PySyft/blob/47f2044d187480150a5a1d253466935dff92db6e/syft/core/hooks/torch/hook.py#L236)).

**Comment by jvmancuso** [comment]
This is a great issue for people who want to understand more of TorchHook, since this will require clearly understanding and explaining the purpose of each of these methods and functions.

**Comment by kamathhrishi** [comment]
I will take on this issue

**Comment by alexandregranzerguay** [comment]
Are we still missing some docstrings?

**Comment by jeamick** [comment]
@kamathhrishi  Any Update ?

I can check  with you if you want too ;)

**Comment by g0lemXIV** [comment]
If it's still open I will try to tackle this issue. First, I will try to create docstring for   ``` _hook_module ```.

**Comment by souravsingh** [comment]
I am interested in taking a stab at the issue.
