### ISSUE TITLE
API Change -- Imperatively set TorchHooks

### ISSUE THREAD

**Issue by jvmancuso** [OpenMined/PySyft#1414]
## User Story:
As of #1413, the new version of TorchHook allows it to be used as a context manager, and improves it's interface for doing so.  In particular, instead of automatically reimporting the original torch module and breaking our hooks on `__exit__`, it resumes the previous version of torch that was being used (regardless of how much it's been hooked).  This can be useful if we eventually develop other hooks that act on the torch module, or if the user is only using the context manager to change how much they're batching commands up.  The problem is that TorchHook currently hooks into torch on instantiation, so the user has less control over this sort of functionality.

Previous behavior (before #1413):
```
hook = TorchHook(...)
worker = VirtualWorker(hooks=hook)
...some pysyft code under the original TorchHook settings...
with TorchHook(...) as ctx_hook:
    ...some pysyft code with a slightly different TorchHook settings...
# torch is no longer hooked, have to reinstantiate everything
x = torch.zeros(2,2)
x.send(worker) # errors out, because exiting the context
               # manager means torch is no longer hooked
```

Current behavior (as of #1413):
```
hook = TorchHook(...)
worker = VirtualWorker(hooks=hook)
# I want to do normal torch code, but it's slower
# because torch is hooked when TorchHook is instantiated above
with TorchHook(...) as ctx_hook:
    ... # some pysyft code with a slightly different torch hook
... # some pysyft code using the original TorchHook
```

Proposed change:
```
hook = TorchHook(...)
worker = VirtualWorker(hooks=hook)
... # I can do normal torch code here!
hook.set_hooks(...)
... # I can do pysyft code here!
hook.lift_hooks(...)
... # I can go back to doing normal torch code here!
```
Also useful for context managers:
```
hook = TorchHook(...)
worker = VirtualWorker(hooks=hook)
with TorchHook(...) as ctx_hook:
    ... # some pysyft code with torch hooked
... # some normal torch code
hook.set_hooks(...) # set up TorchHook how you would've initialized it before
with TorchHook(...) as ctx_hook:
    ... # some pysyft code with a slightly different torch hook
... # some pysyft code using the previous setting of TorchHook
```

**Comment by iamtrask** [comment]
@jvmancuso still interested in this?
