### ISSUE TITLE
Add Logo and Color Scheme to Documentation

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1418]
PySyft's documentation is currently hosted using Sphinx and Github at (https://openmined.github.io/PySyft/_build/html/index.html)

However, the documentation isn't remotely attractive yet, and doesn't have any of OpenMined's pretty logos, colors, and branding. This issue is about sprucing things up a bit and making them more attractive.

Firstly - it would be amazing if OpenMine's logo could be in the top left (much like [PyTorch's](https://pytorch.org/docs/stable/index.html). Secondly, if we could change the color spectrum to be a bit more OpenMinedy... that'd be amazing!!!

**Comment by cereallarceny** [comment]
Got it

**Comment by kamathhrishi** [comment]
I would be interested in working on this issue.

**Comment by iamtrask** [comment]
Finished via https://github.com/OpenMined/PySyft/pull/1427 Well done @kamathhrishi !!
