### ISSUE TITLE
Installation Script

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1419]
So one interesting complication is that some of our dependencies install fine with pip (all the ones in requirements.txt) but PyTorch doesn't install well with pip... and instead prefers conda. Thus, we have a 3 step installation process (pip install requirements.txt; conda install pytorch; python setup.py install).

This issue is about making that a 1 step process using a script.... "install.sh" to be located in the PySyft/scripts folder.

**Comment by m3rc3n4ry** [comment]
Hey @iamtrask ! I would like to take this issue.

**Comment by iamtrask** [comment]
Fixed with https://github.com/OpenMined/PySyft/pull/1420

**Comment by iamtrask** [comment]
Sorry about that @m3rc3n4ry . I'd be happy to help you find another project though!

**Comment by m3rc3n4ry** [comment]
@iamtrask I don't mind. I'm a beginner in open source, just trying to figure out how this works. I'd be glad if you did :)
