### ISSUE TITLE
Create New Worker for gRPC Base Communication

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1421]
In PySyft, a worker object extends BaseWorker, which represents a global list of tensors and various functions on those tensors (such as adding them, removing them, sending them, receiving them, and receiving commands which involve them). 

All other workers except BaseWorker merely extend BaseWorker's capability over different communication protocols. VirtualWorker does so locally. SocketWorker uses sockets... WebSocketWorker uses Web Sockets (slightly different from sockets). Each of these extensions implements send_msg and receive_msg using this new protocol.

In this issue, we'd like to implement a new extension of BaseWorker allowing for communication over [gRPC](https://grpc.io/). Two workers should be able to perform remote tensor execution over this connection type.

**Comment by ddhaval04** [comment]
I'd be working on this issue, if anyone else is interested, please reach out to me on slack @Dhaval

**Comment by iamtrask** [comment]
Hey @ddhaval04 are you still interested in this?

**Comment by robert-wagner** [comment]
closed due to changing priorities
