### ISSUE TITLE
Unable to use nn.RNN module on remote workers. No .shape parameter

### ISSUE THREAD

**Issue by OzzyKampha** [OpenMined/PySyft#1442]
## Context
I was experimenting with PySyft and RNN's when i got errors. I was unable to use the sent model with data on a remote worker. I did some testing with a very simple RNN. It worked on the local machine, but when it was sent over to a worker it had same error as before. The error i was getting was when the RNN was trying to get the batch size from the input tensor.

**Test Configuration**:

* PySyft Version: 3.1

## Current Behavior

Throws Error Messages

### Steps to Reproduce 

1. creating a float tensor as data
2. reshaping it for rnn input (batch_size,step,seq)
3. Creating the RNN using (torch.nn.RNN)
4. sending data to worker (data.send(worker1))
5. sending model to worker (model.send(worker1))
6. Computing with the data and model (model(data)) ERROR

[Google Colab](https://colab.research.google.com/drive/1K9N74jjsWVwOzlXe97m2_57UrEwA-mOq)
### Failure Logs
[https://gist.github.com/haruza/5a5b021fda1ed5a966ad969c59b00409](https://gist.github.com/haruza/5a5b021fda1ed5a966ad969c59b00409)

**Comment by iamtrask** [comment]
Any chance you could copy paste some code to reproduce (or even better... attach a colab?)

**Comment by OzzyKampha** [comment]
[Here is the colab](https://colab.research.google.com/drive/1K9N74jjsWVwOzlXe97m2_57UrEwA-mOq)

**Comment by OzzyKampha** [comment]
It is a work around by using nn.RNNCell instead of the nn.RNN

**Comment by OzzyKampha** [comment]
No problem at all :D

**Comment by srijang97** [comment]
Hi guys. I have been receiving the same error. My error occurs when the remote tensor is passed through the Embeddings variable. Is it because PySyft does not support embeddings as of now?

**Comment by iamtrask** [comment]
Hmmm - honestly not sure yet. We don't support GPU yet though so that could be the problem. Are you running on the CPU or GPU?

**Comment by iamtrask** [comment]
i believe .shape has been fixed
