### ISSUE TITLE
Refactor: Docstrings -> Autodoc Upgrades 

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1445]
We are currently in the midst of a significant refactoring of PySyft in the *pointers_are_tensors* branch. As the refactor is feature-complete (sans bugs), it is now a top priority to write good docstrings for all classes, methods, and functions in the refactor. In particular, we would like to have full code coverage for the entire library, especially files in the "syft/core/frameworks" folder and in "syft/core/utils.py", "syft/core/frameworks/torch/utils.py", which has had lots of code changes.

**Step 0:** Fork PySyft and then checkout the pointers_are_tensors branch.
```
# On the https://github.com/OpenMined/Pysyft page click on the button fork
git clone https://github.com/{your repo}/PySyft.git
cd Pysyft
git checkout tensors_are_pointers
git checkout -b tensors_are_pointers_your_name
# do stuff and commit
git push
# New pull request : https://github.com/OpenMined/Pysyft/compare, click on 'compare across forks'
```
To keep your fork branch up-to-date:
```
git remote add upstream https://github.com/OpenMined/PySyft
git pull upstream pointers_are_tensors  --rebase
```

**Step 1:** get automatic documentation building locally (you may need to install sphinx if you don't already have it). You can find a script for building the documentation locally [here.](https://github.com/OpenMined/PySyft/blob/master/scripts/build.sh).

**Step 2:** Find an undocumented method, function, or class and learn how it works. Ask questions on on slack in #team_pysft, reverse engineer the code yourself, and play with it in a Jupyter Notebook.

**Step 3:** For _all public methods and classes_ (which do NOT start with an underscore), create an example of how to use the functionality from an end user's perspective (Please speak up if you think a method/class/function has the incorrect privacy setting!)

**Step 4:** Write the autodoc. The autodoc should include a general high-level description of functionality, a bulleted list with a description (and type) of each input parameter as well as any output results. If the method/function/class is public, the autodoc should include an example of how to use it.

For an example of correct documentation, see the following:

**A Class:**
[The Docstring Code](https://github.com/OpenMined/PySyft/blob/master/syft/core/hooks/torch/hook.py#L15)

[The Documentation The Code Produces](https://openmined.github.io/PySyft/_build/html/_modules/syft.core.hooks.html#syft.core.hooks.TorchHook)

**A Method:**

[The Docstring Code](https://github.com/OpenMined/PySyft/blob/master/syft/core/workers/base.py#L256)

[The Documentation The Code Produces](https://openmined.github.io/PySyft/_build/html/_modules/syft.core.workers.html#syft.core.workers.BaseWorker.add_worker)

**Step 5:** Compile the documentation and check that everything looks as it should (and has consistent styling with the other documentation).
```
./script/build.sh
(open) ./docs/index.html
```

**Step 6:** Rinse and Repeat from Step 2.

**Comment by iamtrask** [comment]
**BONUS POINTS:** for finding code that is improperly documented and fixing it :)

**Comment by mukul-rathi** [comment]
Hey, if no one has claimed this, I'll give it a go!

**Comment by bksahu** [comment]
Hi @iamtrask :smile: . I think there's a little typo in the **Step 0** commands. In place of `git checkout tensors_are_pointers` it should be `git checkout pointers_are_tensors` and `git checkout -b tensors_are_pointers_your_name` should be `git checkout -b pointers_are_tensors_your_name`.

**Comment by bksahu** [comment]
@iamtrask Hi. I think there's a small type in the **Step 0** commands.  The branch to be checkout should be `pointers_are_tensors` in place of `tensors_are_pointers`. :thinking:
