### ISSUE TITLE
[Pointers are Tensors] Custom made tensors' attributes disappear after conversion

### ISSUE THREAD

**Issue by alhparsa** [OpenMined/PySyft#1451]
# Issue Template
### User Story:
Custom made tensors are now easier than ever to make with [pointers are tensors](https://github.com/OpenMined/PySyft/pull/1394). In `_PlusIsMinusTensor` everything works since, we're only overriding the existing methods (in this case torch.add) but if a tensor requires a custom made method if we want to add an attribute to it, they disappear during the conversion from the custom made tensor to torch supported tensor. 

## Expected Behavior

```
import syft as sy
import torch
hook = sy.TorchHook()

x = torch.FloatTensor([2, 4, 2])
x = sy._PlusIsMinusTensor().on(x)
print(hasattr(x.abs(), 'is_plusisminustensor'))

True
```

## Current Behavior

What is the current behavior?

```
import syft as sy
import torch
hook = sy.TorchHook()

x = torch.FloatTensor([2, 4, 2])
x = sy._PlusIsMinusTensor().on(x)
print(hasattr(x.abs(), 'is_plusisminustensor'))

True
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce (for bugs)
Simply add `self.is_plusisminustensor` to [this line](https://github.com/OpenMined/PySyft/blob/75402439cfc78238c4bf2bad16dc1b88810c746a/syft/core/frameworks/torch/tensor.py#L496).

### Relevant Literature or Examples (for features)
https://github.com/OpenMined/PySyft/pull/1394

**Comment by iamtrask** [comment]
The current behavior seems to be the same as the expected behavior. Perhaps another description?

**Comment by robert-wagner** [comment]
This is an issue on a deprecated branch
