### ISSUE TITLE
Minimizing the project's Docker-Image size

### ISSUE THREAD

**Issue by abdulrahmanmazhar** [OpenMined/PySyft#1463]
### User Story:
As a Data Scientist using PySyft's... <br>
I want to be able to build/push and pull the project's Docker-Image quickly so it's recommended if it has the minimal size possible.

## Expected Behavior

Image size: Will be less than 769.4MB by far hopefully.

## Current Behavior

Image size: is equal to 769.4MB

**Comment by abdulrahmanmazhar** [comment]
Hello, So is this something helpful so maybe I can start working on as my first contribution? 😊

**Comment by iamtrask** [comment]
This would be a fantastic contribution! Thank you so much!

**Comment by abdulrahmanmazhar** [comment]
Thank you so much it's really my pleasure to be able to contribute, So will be pushing my PR soon to be reviewed 😊.

**Comment by iamtrask** [comment]
Well done!
