### ISSUE TITLE
[mpc_tensor] Handle nested args in `split_to_pointer_commands`

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1480]
### User Story:
`GeneralizedPointerTensors` forward the command they receive by creating a special command for each of their pointers, using `split_to_pointer_commands`
However, we only handle very simple arguments so far.

## Expected Behavior

Should support args = [(gpt1, gpt2), 2, {'e': gpt3}]

**Comment by amit-rastogi** [comment]
Hi @LaRiffle, 
I created the following sample code to get some insights into the "GeneralizedPointerTensors"  and the "split_to_pointer_commands" -

```
hook = sy.TorchHook()
me = hook.local_worker
bob = VirtualWorker(id="bob",hook=hook)
me.add_worker(bob)
x = torch.LongTensor([1, 2, 3, 4, 5])
x.send(bob)
x_pointer_tensor_dict = {bob: x.child}
x_gp = _GeneralizedPointerTensor(x_pointer_tensor_dict, torch_type='syft.LongTensor').wrap(True)
y = x_gp + x_gp
```

Using the above code I could see that the syft_command looks like the following -
syft_command = {'args': ([_GeneralizedPointer...1 owner:0],), 'command': '__add__', 'has_self': True, 'kwargs': {}, 'self': [_GeneralizedPointer...1 owner:0]} 

Could you please give more inputs on what is the expected format of the syft_command if it needs to support complex args in the context of the above example.
