### ISSUE TITLE
Key-Rotation Support for Additive HE 

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#15]
**Background:** [It has been alleged](https://pdfs.semanticscholar.org/73f0/aa4e1b47b55f0f3d8464f61750e559067c56.pdf) that vanilla Learning with Errors can be extremely performant for additive homomorphic encryption. In this work, we seek to verify that this is indeed true and achieve similar performance gains.

Acceptance Criteria:
- the LWE approach in the above paper is constructed and shown to work for homomorphic addition and scalar multiplication (with unit tests)
- key switching interfaces are added 
- the homomorphic encryption algorithm is in a new repository called PyFastLWE

**Comment by ivenzor** [comment]
This is an interesting issue. I will start reading the paper.

**Comment by piyush2896** [comment]
@ivenzor this interested me as well. Will be reading the paper this weekend. It looks nice.

**Comment by iamtrask** [comment]
Excellent!
