### ISSUE TITLE
MPC Addition With Arbitrarily Large Numbers of Parties

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1501]
In this issue, I will be extending our current MPCTensor implementation to support sharing to an arbitrarily large number of parties. A limited number of operations will also work in this configuration including.

- __add__
- sum()
- __getitem__
-... other default Torch functionality that currently gets inherited

Things that won't work (but will be addressed by a later issue).
- __mul__
- mm
- prod()

**Comment by LaRiffle** [comment]
I updated share() already
