### ISSUE TITLE
Numpy Remote Execution Bug

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1503]
In the process of creating the Numpy Federated Learning Demo (https://github.com/OpenMined/PySyft/blob/master/examples/numpy/Federated%20Learning.ipynb), I discovered that np.dot(a,b) doesn't work for remote numpy arrays while a.dot(b) does. Similarly, I also discovered that a.T does not work with remote tensors but a.transpose() does. Closing this Issue is about getting these functions to work.

To reproduce the error, just run the Federated Learning demo above with the function np.dot() instead of the method x.dot(y) (or similarly for transpose).

**Comment by iantimmis** [comment]
Ill take it 👍

**Comment by iamtrask** [comment]
Hey Ian - how's this PR going? @amit-rastogi is interested in picking it up if you've moved on from the project.

**Comment by iamtrask** [comment]
Hey @amit-rastogi - Ian messaged me offline that this project is all yours! :)
