### ISSUE TITLE
Logging tensor

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1505]
We want a tensor which rather than doing any operations simply writes the operation to a file

**Comment by stephenjfox** [comment]
I'd love to give this one a shot. I've been silently keeping up with the community since its inception and I think I can do this.

@all okay with this?

**Comment by robert-wagner** [comment]
Go for it! If you have any questions I'll be happy to help!

**Comment by stephenjfox** [comment]
Seeing as @robert-wagner has taken off with #1632, I'm going to make those tests pass instead.
