### ISSUE TITLE
Create a Polynomial Tensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1506]
Create an abstraction such that any other tensor can leverage polynomial approximations of various non-linear functions by either extending this tensor (or by putting it in the chain hierarchy) or both. This initial functionality should include approximations for sigmoid, tanh, relu, exp, and log.

**Comment by kamathhrishi** [comment]
Do we really need a separate tensor for this or shall we just make it a part of SPDZ?

**Comment by jvmancuso** [comment]
I'd defer to @iamtrask, but I imagine this could be done in SPDZ

**Comment by kamathhrishi** [comment]
This should be closed ?
