### ISSUE TITLE
Rename MPCTensor -> SPDZTesnor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1508]
Change all code references to MPCTensor (including notebooks, demos, and documentation) to SPDZTensor

**Comment by llealgt** [comment]
i'll take this one as my first project,but any guidance for starters welcome since it's my starting point.

**Comment by iamtrask** [comment]
Excellent! Just make sure you find all the references and run python setup.py test at the end (all the tests should pass)
