### ISSUE TITLE
Bugfix in Matrix Multiplication for MPC

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1511]
import random
import syft as sy
from syft.core import utils
from syft.core.frameworks.torch import utils as torch_utils
from syft.core.frameworks import encode

from syft.core.frameworks.torch.tensor import _GeneralizedPointerTensor
from syft.mpc import spdz
from syft.core.frameworks.torch.tensor import _MPCTensor
import torch
import torch.nn.functional as F
from torch.autograd import Variable as Var
import json

hook = sy.TorchHook(verbose=True)

me = hook.local_worker
me.is_client_worker = False

bob = sy.VirtualWorker(id="bob", hook=hook, is_client_worker=False)
alice = sy.VirtualWorker(id="alice", hook=hook, is_client_worker=False)
james = sy.VirtualWorker(id="james", hook=hook, is_client_worker=False)

x = torch.LongTensor([[1,2],[3,4]])
y = torch.LongTensor([[5,6],[7,8]])
xptr = x.share(bob, alice)
yptr = y.share(bob, alice)
z = x.mm(y)

z.child isn't an MPCTensor..., it's just a GeneralizedPointerTensor. Working on a fix.

**Comment by iamtrask** [comment]
oh wait... i'm an idiot...


i should have put down xptr.mm(yptr)

**Comment by LaRiffle** [comment]
Ahahah

**Comment by iamtrask** [comment]
There was a small bug to fix but now it's done - although i noticed that x and y are getting inline modified to become GeneralizedPointerTensors when they probably shouldn't be.

**Comment by LaRiffle** [comment]
Hum yes you're right this should be avoided!
