### ISSUE TITLE
Add Subtraction, Negation, and Power function to MPCTensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1513]
In this project, I'll be adding several basic operators to MPCTensor.

**Comment by iamtrask** [comment]
got sub working 

    def __sub__(self, other):
        gp_response = spdz.spdz_add(self.shares, spdz.spdz_neg(other.shares))
        response = _MPCTensor(gp_response).wrap(True)
        return response

**Comment by LaRiffle** [comment]
Maybe the question of negative values is related as well:
trt this:
```
x = torch.LongTensor([3])
y = torch.LongTensor([-5])

mpc_x = x.share(alice, bob)
mpc_y = y.share(alice, bob)

mpc_z = mpc_x + mpc_y
mpc_z.get()```
You get a negative value -2 because I did a hacky fix, but without it because of the modulo you would have <field_value> - 2

**Comment by iamtrask** [comment]
I might skip pow since torch.LongTensor doesn't seem to have it either.

**Comment by iamtrask** [comment]
Hit a speedbump - this seems to fail

x = torch.LongTensor([[1, 2], [-3, -4]])

x = x.share(bob, alice)

z = -x
assert (z.get() == torch.LongTensor([[-1, -2], [3, 4]])).all()

**Comment by iamtrask** [comment]
z.get() returns

 2.1475e+09  2.1475e+09
 3.0000e+00  4.0000e+00
[syft.core.frameworks.torch.tensor.LongTensor of size 2x2]

**Comment by iamtrask** [comment]
Curiously these work fine

x = torch.LongTensor([[1, 2], [3, 4]])

x = x.share(bob, alice)

z = -x
# assert (z.get() == torch.LongTensor([[-1, -2], [3, 4]])).all()

z.get()



AND




x = torch.LongTensor([[-1, -2], [-3, -4]])

x = x.share(bob, alice)

z = -x
# assert (z.get() == torch.LongTensor([[-1, -2], [3, 4]])).all()

z.get()

**Comment by iamtrask** [comment]
@robert-wagner had some good things to say in Slack

yo - there seems to be an issue with the negation logic in spdz.py

https://github.com/OpenMined/PySyft/issues/1513

bobby [9:08 PM]
Are you decoding the value before checking what it is or just summing the result
Because if you're summing the result it will definitely be wrong for negative numbers

trask [9:10 PM]
i have no idea
lo
def __neg__(self):
       gp_response = spdz.spdz_neg(self.shares)
       response = _MPCTensor(gp_response).wrap(True)
       return response
that's what i did

bobby [9:13 PM]
How is get sum defined? Or I'll be back on laptop in 5

trask [9:13 PM]
sum?
where is sum?

bobby [9:13 PM]
Get_sum
It's on mpc tensor

trask [9:13 PM]
oh - it's defined how you defined it

bobby [9:13 PM]
Theo wrote it

trask [9:13 PM]
def get(self, deregister_ptr=False):
       # TODO: have deregister_ptr do something
       value = self.shares.child.sum_get() % spdz.field
       if (value > spdz.torch_max_value).all(): # TODO: value per value
           return value - spdz.torch_field
       else:
           return value

bobby [9:14 PM]
The comment needs to be fixed
We need to have it do that subtraction on every entry greater than the max value
I'll write up a fix in a few

trask [9:15 PM]
oh - so mask and subtract
ok i'm going to copy paste this into the github issue for reference

**Comment by iamtrask** [comment]
Merged in some improvements from Bobby - but they aren't finished yet https://github.com/OpenMined/PySyft/pull/1518

Now whenever i call .get() on an MPC tensor I get an error 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-f01fae6ab1b3> in <module>()
----> 1 z.get()

/Users/atrask/anaconda/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/core/frameworks/torch/tensor.py in get(self, deregister_ptr, update_ptr_wrapper)
   1182                     and tensor is not None \
   1183                     and tensor.dim() > 0:
-> 1184                 self.native_set_(tensor)
   1185             torch_utils.fix_chain_ends(self)
   1186             torch_utils.assert_is_chain_well_formed(self)

```
TypeError: set_ received an invalid combination of arguments - got (torch.FloatTensor), but expected one of:
 * no arguments
 * (torch.LongTensor source)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (torch.LongStorage storage)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (torch.LongStorage sourceStorage, int storage_offset, torch.Size size)
 * (torch.LongStorage sourceStorage, int storage_offset, torch.Size size, tuple stride)
```

**Comment by iamtrask** [comment]
Traced the issue to

```
def decode(field_element, precision_fractional=PRECISION_FRACTIONAL, mod=field):
    neg_values = field_element.gt(mod)
    # pos_values = field_element.le(field)
    # upscaled = field_element*(neg_valuese+pos_values)
    field_element[neg_values] = mod - field_element[neg_values]
    rational = field_element.float() / BASE ** precision_fractional
    return rational
```

the .float() casting seems to be the issue. Changing it to 

```
def decode(field_element, precision_fractional=PRECISION_FRACTIONAL, mod=field):
    neg_values = field_element.gt(mod)
    # pos_values = field_element.le(field)
    # upscaled = field_element*(neg_valuese+pos_values)
    field_element[neg_values] = mod - field_element[neg_values]
    rational = field_element / BASE ** precision_fractional
    return rational
```

gets rid of the error but then negative numbers stop working again.

```
x = torch.LongTensor([[-1,2],[3,4]])
x = x.share(bob, alice)
x.get()
```

 ```
2.1475e+09  2.0000e+00
 3.0000e+00  4.0000e+00
[syft.core.frameworks.torch.tensor.LongTensor of size 2x2]
```

**Comment by iamtrask** [comment]
Ok, made some progress by looking back at what it was before (https://github.com/OpenMined/PySyft/blob/trask2/syft/core/frameworks/torch/tensor.py)

   ```
 def get(self, deregister_ptr=False):
        # TODO: have deregister_ptr do something
        value = self.shares.child.sum_get() % spdz.field
        if (value > spdz.torch_max_value).all(): # TODO: value per value
            return value - spdz.torch_field
        else:
            return value
```

and then just focusing on implementing that TODO there... using some basic masking.

  ```
  def get(self, deregister_ptr=False):
        # TODO: have deregister_ptr do something
        value = self.shares.child.sum_get() % spdz.field

        gate = (value > spdz.torch_max_value).long()

        neg_nums = (value - spdz.torch_field) * gate
        pos_nums = value * (1 - gate)
        result = neg_nums + pos_nums

        return result
```

Seems to be working so far.

```
x = torch.LongTensor([[1,-2],[-3,-4]])
x = x.share(bob, alice)
x.get()

 1 -2
-3 -4
[syft.core.frameworks.torch.tensor.LongTensor of size 2x2]
```

**Comment by iamtrask** [comment]
going to try testing it with the other functions now

**Comment by iamtrask** [comment]
No dice yet - doesn't work with matrix multiplication

```
x = torch.LongTensor([[1, 2], [3, 4]])
y = torch.LongTensor([[5, 6], [7, 8]])

x = x.share(bob, alice)
y = y.share(bob, alice)

x.mm(y).get()
```

```
-8.4013e+08  3.0743e+08
 9.2008e+08 -5.7132e+08
[syft.core.frameworks.torch.tensor.LongTensor of size 2x2]
```

**Comment by iamtrask** [comment]
Ok - this piece is kindof annoying - looks like the old version of .get() doesn't work with matrix multiplication anymore either..., something else must have changed

```
x = torch.LongTensor([[1, 2], [3, 4]])
y = torch.LongTensor([[5, 6], [7, 8]])

x = x.share(bob, alice)
y = y.share(bob, alice)

z = x.mm(y)


value = z.child.shares.child.sum_get() % spdz.field

if (value > spdz.torch_max_value).all(): # TODO: value per value
    out = value - spdz.torch_field
else:
    out = value
out
```

```
2.4780e+08  1.2492e+09
 1.0811e+09  5.7968e+08
[syft.core.frameworks.torch.tensor.LongTensor of size 2x2]
```

**Comment by iamtrask** [comment]
Ok... good news is that the implementation on branch trask2 still works for matrix multiplication... so going to compare the two branches (trask and trask2) to figure out where matrix multiplication differs.

**Comment by iamtrask** [comment]
Ok, i'm almost completely sure that some other PR has messed up matrix multiplication, so i'm going to check that subtraction and negation work properly and then merge this
