### ISSUE TITLE
Federated Learning with Tensorflow Demo

### ISSUE THREAD

**Issue by ceballosiker** [OpenMined/PySyft#1522]
### User Story:
Add a TensorFlow demo using PySyft's virtual workers and the custom federated optimizer.

## Expected Behavior

Have a demo showing usage of the custom federated optimizer and the PySyft's workers together.

### Relevant Literature or Examples (for features)
Something similar to [this](https://github.com/coMindOrg/federated-averaging-tutorials/blob/master/advanced_federated_classifier.py) example.

**Comment by iamtrask** [comment]
Will revisit
