### ISSUE TITLE
Add Functionality to FixedPrecisionTensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1532]
In https://github.com/OpenMined/PySyft/pull/1530 and https://github.com/OpenMined/PySyft/pull/1531, we created a new class called FixedPrecisionTensor which is able to take any pytorch tensor and compute over it using a limited range of precision. For example (https://github.com/OpenMined/PySyft/blob/master/examples/torch/Fixed%20Precision%20Tensor%20Testing.ipynb)

However, only addition has been implemented. In this work, we'd like to add the following functions.

- \_\_mult__ - multiplication by another fixed precision tensor
- \_\_mult__ - multiplication by another non-fixed precision tensor
- prod() - multiplication across a dimension
- cumprod() - cumulative multiplication across a dimension
- \_\_add__ - addition by a non-fixed precision tensor
- sum() - addition across a dimension
- cumsum() - cumulative addition across a dimension
- inheritance - all undefined methods should inherit from the tensor underlying FixedPrecisionTensor (self.child). Test that this works using __getitem__

**Comment by jjmachan** [comment]
I would like to work on this. I'm just getting started with this project though.

**Comment by iamtrask** [comment]
Please reach out if you get stuck on anything - I'm here to help :)

**Comment by alhparsa** [comment]
I got this 😁
