### ISSUE TITLE
FixPrecisionTensor is eager, make it graphic!

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1540]
## Context about chains
If you don't know why we keep talking about chains, here is a brief recap [Quick review of PySyft chains](https://drive.google.com/file/d/1Ydd3YPwJRE_77t5RiK9IGmktNuFAZTlx/view?usp=sharing).
Having understand chains, here is an interpretation: the chain is like a simple graph of the operations you want to perform before doing the real computation. If we take the example of the PlusIsMinusTensor, it is stated that every __add__ op will be substituted with a __sub__ one, before the computation take place. 

## The issue itself:
Here is an example:
```
x = torch.FloatTensor([3.1])
z = x.fix_precision()
chain_print(z) # function to show the syft chain
```
Displays:
```
FloatTensor > _FixedPrecisionTensor > _LongTensor > _LocalTensor
```

It works perfectly fine but having `> _LongTensor` in the chain is not really appriopriate since it doesn't corresponds to a transformation, whereas `_FixedPrecisionTensor` does.
Of course there would be no point to replace the head FloatTensor with this LongTensor, as we want to keep the initial typing. So the question would be, where should we put it if we want to remove it from the chain?
Well, the real question is: why is it here? This is actually computation already available, already done. This corresponds to an **eager** mode.

So what would be the dual **graph** mode?
As the chain or graph chain is mainly a descriptor of the operations we do on the data before executing usual computation, it is only a description. For FixedPrecision this would be: when you would want to do an operation, (x.abs_() for instance), the FloatTensor would be converted into a LongTensor by the handle_call method of FixedPrecision, and transmitted downward the chain, so there would be no need to store the LongTensor.
We are inclined to think both modes could be useful, so we need to implement this **graph** mode.

If you have any question, please drop them here.

**Comment by iamtrask** [comment]
Graph mode is the tensorflow way - which would be strange to do in pytorch
