### ISSUE TITLE
Turn PySyft into graph mode.

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1541]
## Context
I would strongly recommend reading #1540 to have a context on:
- PySyft chain
- Eager and Graph mode, how PySyft chain can implement a graph mode

## The issue 
This is not exactly an issue but more a reflexion about eager and graph mode.
PyTorch is known to be eager and this is great, TF is also turning eager by default. This means that when you require an operation it is performed immediately.

By contrast, when you add a node syft_tensor in the syft chain of the tensor (eg PlusIsMinusTensor), you often declare a transformation to be performed only when a "real" command is issued, which is mainly a torch command. (Note that this is not the case for Pointers, but well... it could be too)

So basically I can add in the chain (or graph) any operation I want, provided that I have created the appropriate SyftTensor (eg MultiplyByTwoTensor, AddOneTensor, etc.), and all these will be applied to the tensor when I ask for a torch command, jute before the command is executed.

Now, what if we did a `TorchOperatorTensor`, which would store an arbitrary Torch command given at ` __init__` ? And in addition, we add a special method/function that actually run the graph, say `run()`. Example:
```
x = sy.FloatTensor([-2.3])
# 1. Usual Eager way
y = x.abs()
# 2. New Graph mode
y = sy._TorchOperatorTensor('abs').on(x)
y.run()
```
This would allow us to perform complete PyTorch in graph mode!

**Observations:**
1. The syntax is terrible, but I'm sure we can make something nicer
2. What is the point of getting back to graph mode? First, to benefit of optimisation in computation which are not available in eager mode. Second, in the context of federated learning, having a better control of the remote variables. Here again an example:
```
x = sy.FloatTensor([-2.3])
x.send(bob) # pointer to bob@addr1
x = x**2 # new pointer to bob@addr2
```
In this very short code, we already lost the reference to the tensor located at bob@addr1, so it will never be removed, until we build a special manager. This manager would greatly benefit from having a graph of computation.

**Comment by jopasserat** [comment]
Not sure this is the right issue to discuss this (depends to which extent you guys want to push this graph mode), but I've had a chat with @LaRiffle about migrating to an existing representation of chains of operation.

For the record, we were wondering if we could build something on top of [Dask](http://conference.scipy.org/proceedings/scipy2015/pdfs/matthew_rocklin.pdf) but haven't really looked into it yet.

**Comment by iamtrask** [comment]
We've got a good plan for this in torch 1.0 - see the torch 1.0 refactor
