### ISSUE TITLE
Tensors shouldn't store information about commands

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1542]
## Context
The _PlusIsMinusTensor has been created as a canonical example of what can be done by extending the SyftTensor.However, it does not make sense that we modify the behaviour of commands from an argument.

This underlines that the architecture is very much argument oriented, which is excellent when we send tensor or transform them in MPCTensor, but rather unefficient and complicated when we want to execute command on them.

Idea: using contexts defining workers involved and mpc. PR #1543 https://github.com/OpenMined/PySyft/pull/1543 gives extended explanation of a possible solution.

A typical example would be:
```
x = sy.FloatTensor([1.2])

#x.send(bob) #<- This is what you don't need to do

with sy.session(bob):
    # Here all the commands and ensors are sent to bob
    z = torch.add(x, x)

#z.get() or x.get() #<- This is what you don't need to do

print(z) # This is FloatTensor
```

**Comment by LaRiffle** [comment]
^^^^ I just added an example of what I meant by context.

**Comment by iamtrask** [comment]
I assume we'll be leaving in .send() and .get() as backups? There are some cases when it will be very challenging to use the indented case (such as when you're working with tensors in multiple places at once or pointers to pointers.

**Comment by LaRiffle** [comment]
Exactly, .send() and .get() will be kept. Sending a tensor to bob before opening a context session with bob for example means that when the session ends, that tensor still is at bob (example: the data when doing training over epochs).
If you have two remote datasets at bob and alice as it is the case in most of our examples, you would probably iterate on each batch, and depending of whom stores it, you would open the appropriate remote session.
