### ISSUE TITLE
Implement PATE with PySyft

### ISSUE THREAD

**Issue by yanndupis** [OpenMined/PySyft#1547]
We would like to implement the Private Aggregation of Teacher Ensembles (PATE) framework with PySyft by following the example [here](https://github.com/tensorflow/models/tree/master/research/differential_privacy/multiple_teachers).
- [x] Implement PATE in PyTorch - #1552
- [ ] Integrate PATE with PySyft

**Comment by iamtrask** [comment]
Super excited about this PR!

**Comment by yanndupis** [comment]
Great, thank you @jopasserat! I will definitely check this out. I have just pushed this initial implementation with PyTorch #1552. Thanks

**Comment by mari-linhares** [comment]
@kamathhrishi  can we close this based on #1967 ?

**Comment by kamathhrishi** [comment]
@mari-linhares I have ported the analysis implementation in Pytorch. I am working on implementing an PATE model.
