### ISSUE TITLE
Combine Differential Privacy Demos with Federated Learning with Secure Aggregation Demo

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1556]
We currently have two demos for differential privacy and one with secure aggregation. In a real world setting, we would want to be able to train these at the same time. In this issue, we would like to create TWO new demos.

1) by combining [this Differential Privacy demo](https://colab.research.google.com/drive/1k2TtOJSKSfuvcVLPILAtnh34lFhuUs45) with [this Federated Learning with Secure Aggregation demo](https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training%20with%20Secure%20Aggregation.ipynb)

2) by combining [this Differential Privacy demo](https://github.com/OpenMined/PySyft/blob/master/syft/differential_privacy/PATE_example_with_pytorch.ipynb) with [this Federated Learning with Secure Aggregation demo](https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training%20with%20Secure%20Aggregation.ipynb)

**Comment by mukul-rathi** [comment]
Could I give this a go as a first issue?

**Comment by iamtrask** [comment]
Certainly! @mukul-rathi - go ahead and submit a PR when you get started which I will label "work-in-progress". This will make it easier for us to have conversation as you go (you can see several examples of this in the Pull Requests for this project now)

**Comment by iamtrask** [comment]
@mukul-rathi - are you in our slack? (slack.openmined.org). If so, what is your handle?

**Comment by mukul-rathi** [comment]
Yes, my handle is Mukul Rathi.

**Comment by mukul-rathi** [comment]
@iamtrask the 2nd Federated Learning with Secure Aggregation demo links to the same one as the previous one. Should it be linking to 
https://github.com/OpenMined/PySyft/blob/master/examples/other/experimental/MNIST%20Example.ipynb instead?

**Comment by iamtrask** [comment]
Nope - the secure aggregation part of it is identical! Great question though. I should have specified.
