### ISSUE TITLE
missing "workers" parameter when calling share on new spdz demo.ipynb

### ISSUE THREAD

**Issue by llealgt** [OpenMined/PySyft#1557]
In notebook :
PySyft/examples/other/experimental/new spdz demo.ipynb

There's a calls to _SPDZTensor.share which are missing "workers" parameter

**Comment by llealgt** [comment]
I'll fix this .

**Comment by iamtrask** [comment]
That demo might actually be out of date in general - would be great if it used the new API

**Comment by llealgt** [comment]
It seems as the notebook is missing in master branch, maybe it was renamed?

**Comment by iamtrask** [comment]
It was moved to experimental -  but we really should create _new_ demos

**Comment by iamtrask** [comment]
(because that one is out of date)
