### ISSUE TITLE
Documentation link not found

### ISSUE THREAD

**Issue by TheShadow29** [OpenMined/PySyft#1562]
I am not sure why but the documentation link on the readme page is not working. It links to https://openmined.github.io/PySyft/_build/html/index.html which gives 404 file not found error on github page. 
![image](https://user-images.githubusercontent.com/10602903/46029145-7f24f500-c0a7-11e8-8315-2e2dba131b1c.png)

**Comment by iamtrask** [comment]
Yeah - we're having general link issues - if you pull the docs down and build them locally it works - @jeremyjordan is currently working on this

**Comment by iamtrask** [comment]
i'll pull the docs page down from the readme for now - thanks for the heads up!
