### ISSUE TITLE
Adapt to README template

### ISSUE THREAD

**Issue by anoff** [OpenMined/PySyft#158]
Update the `README` to follow the new [README template](https://github.com/OpenMined/Docs/blob/develop/contributing/readme_template.md)

Currently missing
* Usage
* License
* TOC

**Comment by lucaslopesf** [comment]
This applies to all repositories or only PySyft?

**Comment by anoff** [comment]
There's a similar issue for each repository. They should each be 5 minute fixes though :)

**Comment by swaroopch** [comment]
Issue can be closed after @lucaslopesf commit - https://github.com/OpenMined/PySyft/commit/065a3a2e59ca3ece6acbbea3407cc3ef19584abf ?
