### ISSUE TITLE
Coordinate FixPrecision and SPDZ Tensor on multiplication

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1582]
# Issue

Let's say we have 6.0 and 8.0 to multiply,
field is 2**31 and bit precision is 3.

When I get into fix precision I'll have 6000 and 8000. Then I share them with spdz
When I do the multiplication I get back a spdz tensor whose shares sum up to 48.10**6, so what I do is I divide by n = 10**3 to have a proper encoding of fixp.
But if I divided the shares by n, _I also need to divide the field, otherwise the shares won't sum up correctly_
So after my multiplication my field is only 2**28.
Which means I can only perform ~10 consecutive ops before I have lost all information.

Am I doing something incorrectly here?

**Comment by iamtrask** [comment]
i don't think this is an issue in torch_1 which is moving to master today
