### ISSUE TITLE
URGENT: remove all % operators and replace with torch.fmod()

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1592]
@channel - BUG IN PYTORCH 0.3.1

The modulus operator doesn't always work.
https://github.com/pytorch/pytorch/issues/1164

torch.fmod() works correctly
torch.remainder() and the % sign do NOT work.

We need to swap out all uses of % for torch.fmod() pronto

**Comment by ionlights** [comment]
I think I can take this. @iamtrask

**Comment by iamtrask** [comment]
Thank you @ionlights !!

**Comment by iamtrask** [comment]
Note that % work fine if it's just between two python ints... it's only when it's computing on one or more torch tensors that it's an issue

**Comment by iamtrask** [comment]
Hey @ionlights - how's it goin?

**Comment by ionlights** [comment]
:wave: Sorry, got caught up finishing up some assignments due an hour ago. :joy:

I should be able to finish this up towards late afternoon today (Oct 08) in EST.
