### ISSUE TITLE
Travis Errors

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1604]
Since travis was broken for a while - we now have some style guide issues

https://travis-ci.org/OpenMined/PySyft

Anyone interested in helping to sort these out? Would be a great first project if you're looking for one.

**Comment by iamtrask** [comment]
Comment on the issue here if you're interested in picking it up - first come first serve!

**Comment by dnuka** [comment]
Hi @iamtrask ! Can I work on this :)

**Comment by souravsingh** [comment]
@iamtrask I am interested in taking a stab at the issue.

**Comment by iamtrask** [comment]
Excellent! There are several problems indeed so feel free to tackle it togther @dnuka and @souravsingh !!
