### ISSUE TITLE
WebSocketWorker example code doesn't work

### ISSUE THREAD

**Issue by replomancer** [OpenMined/PySyft#1642]
The example code from WebSocketWorker docstring breaks. The first line imports TorchHook from a no longer existing module:
```>>> from syft.core.hooks import TorchHook```
The hook is available in syft now. When this is fixed, after a few steps a nonexistent function utils.PythonJSONDecoder is called on the server side. I don't know what else needs to be updated.

There are no tests for this Worker.

**Comment by replomancer** [comment]
I'd like to fix this Worker and add a test or two.

**Comment by Ogofo** [comment]
Are you making any progress on this issue and do you need help?

**Comment by replomancer** [comment]
I see a lot of broken code in workers, fixing this is not a "fun issue" and may take a little more time.

If you're interested, take a look at [workers_test.py](https://github.com/OpenMined/PySyft/blob/4036adcac0ea20d702d5f9eee314a188b2e297d2/test/core/workers_test.py). There's only one test. Try executing example code from [VirtualWorker's docstring](https://github.com/OpenMined/PySyft/blob/4036adcac0ea20d702d5f9eee314a188b2e297d2/syft/core/workers/virtual.py#L45-L72). It brakes. Adding any worker tests or fixing VirtualWorker would be nice. If you still want to help with workers, maybe try there, so we don't get in each other's way or spend time both doing exactly the same thing.

Or you can take a look at "good first issues" here: https://github.com/OpenMined/PySyft/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by Ogofo** [comment]
Do you have a branch that you are actively working on or a list of broken things that need to be repaired? That would help us do not get in each other's way. 

A potential issue I found is if the WebSocketWorker is initialized with `is_client_worker=True` which is the default, he will not register any received objects in either `_objects` or `_tmp_objects`. This is because  `set_obj(self, remote_key, value, force=False, tmp=False)`of BaseWorker only allows client worker to register temporary objects, but the `tmp` variable is not set to `True`.

**Comment by replomancer** [comment]
Yes, I got a little stuck in this issue. We're talking with Ogofo and Nivek92 on Slack. I think this weekend I'll create a pull request with what I have: a correctly failing test and some small incomplete fixes. Or maybe it will be in my repo only, because I think I have no permissions to create a PR to a new branch here and I don't want this to be a pull request to master.

**Comment by mari-linhares** [comment]
Should this issue be closed?

**Comment by replomancer** [comment]
Hello!
I think this issue still needs discussion and bigger rewrite. I've been a little out of touch lately and I'm not sure what's the plan exactly. Please don't close it yet.

**Comment by Ogofo** [comment]
I suggest creating a ticket to implement the WebSocket worker in torch_1 branch. I don't think we should put more work than necessary into an outdated version of the repository :)
