### ISSUE TITLE
Pytorch 1.0 Garbage Collection

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1658]
This is an Epic which is a sub-project under the project Torch 1.0 - the specs for which you can find here (#1587) - and the KanBan board for which you can find [here](https://github.com/orgs/OpenMined/projects/8?add_cards_query=is%3Aopen).

All work is happening in the [torch_1](https://github.com/OpenMined/PySyft/tree/torch_1) branch.

# Description

We should have a Pool of wrappers which we can re-use.

**Comment by iamtrask** [comment]
I _think_ we're good to go based on https://github.com/OpenMined/PySyft/pull/1805 - @LaRiffle ?

**Comment by LaRiffle** [comment]
I think this isn't too bad however I'd like some more tests to be performed or questions to be answered:
- have a GC test file
- How new tensors types like the LoggingTensor (will) implement __del__ and GC ?

**Comment by LaRiffle** [comment]
Ok I think #1829 Solves this.
