### ISSUE TITLE
PyTorch 1.0 Automatic Command Batching / Async

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1659]
This is an Epic which is a sub-project under the project Torch 1.0 - the specs for which you can find here (#1587) - and the KanBan board for which you can find [here](https://github.com/orgs/OpenMined/projects/8?add_cards_query=is%3Aopen).

All work is happening in the [torch_1](https://github.com/OpenMined/PySyft/tree/torch_1) branch.

# Description:

Let's say we have a series of commands to remote tensors:
```
c = a + b
y = a + c
```
We want all of the JSON for this command to be sent (in order) asynchronously to the worker. The only way this is possible is by having the id of method results be identified by the client. In other words, when running "c = a + b" the client specifies the correct id of "c" so that it can correctly specify the following command "y = a + c" using the correct id for "c".

The way we would like to implement this so that it occurs efficiently is a try/except method. In this case, when y = a + c is sent to be executed, it will error out with a "key not found" error because c will likely not (yet) exist. At this point, we want to save the command into a key-value "command queue" where the key is the id of "c" (the one that doesn't exist yet) and the value is the serialized command instructions. This queue would be checked whenever a new tensor is registered into worker._objects. If the tensor being registered is blocking a command, then after registration that command would be released for execution.

# Sub Tickets

- [ ] #1809 
- [ ] #1810 
- [ ] #1811

**Comment by iamtrask** [comment]
irrelevant given new async strategy
