### ISSUE TITLE
Add serde logic for float

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1665]
Part of Epic: https://github.com/OpenMined/PySyft/issues/1656

This issue should extend the current logic in syft/deser.py to include support for serializing/deserializing floats. 

- [ ] add logic (if necessary) for float serde
- [ ] add unit test demonstrating proper serde of floats
- [ ] add docstrings for all methods describing their functionality including an example of how to serialize it.

**Comment by Ogofo** [comment]
@robert-wagner is this one still open?

**Comment by kamathhrishi** [comment]
I don't think so. It was decided we don't need to handle float datatype explicitly. But , a unit test ensuring it works for float helps
