### ISSUE TITLE
Add serde logic for torch.Tensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1666]
This issue should extend the current logic in syft/deser.py to include support for serializing/deserializing torch.Tensor objects. 

- [ ] add logic (if necessary) for torch.Tensor serialization and deserialization
- [ ] add unit test demonstrating proper serde of torch.Tensor objects
- [ ] add docstrings for all methods describing their functionality including an example of how to serialize/deserialize it.

**Comment by Ogofo** [comment]
I'll be working on this one.

**Comment by Ogofo** [comment]
Review the merged PR. 

 [x] add logic (if necessary) for torch.Tensor serialization and deserialization
 [x] add unit test demonstrating proper serde of torch.Tensor objects
 [x] add docstrings for all methods describing their functionality including an example of how to serialize/deserialize it.

**Comment by iamtrask** [comment]
Excellent work!
