### ISSUE TITLE
Add serde logic for tuples

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1668]
This issue should extend the current logic in syft/deser.py to include support for serializing/deserializing tuple. 

- [x] add logic (if necessary) for tuple serde
- [x] add unit test demonstrating proper serde of tuples
- [ ] add docstrings for all methods describing their functionality including an example of how to serialize it.

**Comment by Ogofo** [comment]
`msgpack` is encoding a tuple as a list. Once you decode the binary you don't get a tuple back, but a list. I think this can easily be handled with the first parameter that is passed and has to be handled in the `_detail_collection` method.
