### ISSUE TITLE
Add serde logic for python ellipsis

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1669]
Part of Epic: https://github.com/OpenMined/PySyft/issues/1656

This issue should extend the current logic in syft/deser.py to include support for serializing/deserializing ellipsis objects. 

- [ ] add logic (if necessary) for ... serialization and deserialization
- [ ] add unit test demonstrating proper serde of ... objects
- [ ] add docstrings for all methods describing their functionality including an example of how to serialize/deserialize it.

**Comment by Nivek92** [comment]
Hey could you give an example on when one would need to serialize an ellipsis object?
