### ISSUE TITLE
Add serde logic for np.ndarray

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1670]
Part of Epic: https://github.com/OpenMined/PySyft/issues/1656

This issue should extend the current logic in syft/deser.py to include support for serializing/deserializing np.ndarray objects. 

- [ ] add logic (if necessary) for np.ndarray serialization and deserialization
- [ ] add unit test demonstrating proper serde of np.ndarray objects
- [ ] add docstrings for all methods describing their functionality including an example of how to serialize/deserialize it.

**Comment by robert-wagner** [comment]
Great work on this issue!
