### ISSUE TITLE
Add serde logic for slice

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1673]
Part of Epic: https://github.com/OpenMined/PySyft/issues/1656

This issue should extend the current logic in syft/deser.py to include support for serializing/deserializing slice objects. 

- [ ] add logic (if necessary) for slice serialization and deserialization
- [ ] add unit test demonstrating proper serde of slice objects
- [ ] add docstrings for all methods describing their functionality including an example of how to serialize/deserialize it.

**Comment by Nivek92** [comment]
@iamtrask Like ellipsis I don't actually understand why would we want to serde a slice object?

Would you not just send the slice itself instead of the slice object?

**Comment by Ogofo** [comment]
@iamtrask can you close this, please? :) Thanks
