### ISSUE TITLE
Fix travis ci build process

### ISSUE THREAD

**Issue by Nivek92** [OpenMined/PySyft#1685]
The is an error in the paths for the exclude command

**Comment by Ogofo** [comment]
There is another issue within the Travis CI run, I would suggest to use this ticket to resolve the issues and get the Travis build running. 

Current issue is: 

```
$ coverage run python setup.py test
No file to run: 'python'
The command "coverage run python setup.py test" exited with 1.
```

**Comment by Ogofo** [comment]
The previous can be resolved by changing the line to `coverage run setup.py test`.

Currently the build would still faile because:

1. The test coverage is not 100% yet. 
2. The `bash scripts/execute_notebooks.sh` will fail, because the script does not yet exist on the `torch_1` branch

**Comment by Nivek92** [comment]
Associated 

Get 100% test coverage #1703
Make tests pass #1705

**Comment by iamtrask** [comment]
Woot woot!!!
