### ISSUE TITLE
Investigate if pickle for numpy arrays is secure

### ISSUE THREAD

**Issue by Nivek92** [OpenMined/PySyft#1689]
@iamtrask is wondering whether pickle is a secure way to serialize numpy arrays.
By default pickle allows for arbitrary code injection so we don't want to use it for normal python objects. We have to investigate further as to whether this concern applies to numpy.

**Comment by Nivek92** [comment]
@iamtrask I looked into it and found

https://intoli.com/blog/dangerous-pickles/ & https://checkoway.net/musings/pickle/ which describe the problem. 

So from my understanding the whole code injection is only a problem if we unpickle user generated data which isn't the case (except they manipulate the message that is send between client and server)

Aside from that I found that pickle.dumps is slower than using .tobytes on the array so I will change it anyway so we are safe on that side either way.

**Comment by iamtrask** [comment]
This sounds solved!
