### ISSUE TITLE
Add serde logic for PointerTensor

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1694]
Sub issue of #1695 

This issue should extend the current logic in syft/serde.py to include support for serializing/deserializing PointerTensor objects. 

- [x] add logic (if necessary) for PointerTensor serde
- [x] add unit test demonstrating proper range of ints
- [x] add docstrings for all methods describing their functionality including an example of how to serialize it.
- [x] add convenience function for PointerTensor .serialize()

**Comment by mari-linhares** [comment]
Looking at [`serde.py`](https://github.com/OpenMined/PySyft/blob/torch_1/syft/serde.py) and [`test_serde.py`](https://github.com/OpenMined/PySyft/blob/torch_1/test/test_serde.py) apparently this is done.

**Comment by iamtrask** [comment]
The only piece we're lacking here is the actual .serialize() method on the PointerTensor itself.

**Comment by LaRiffle** [comment]
It was done in 8c479141511a6f4adf84599cdb95472d5eae3bce
