### ISSUE TITLE
Create_pointer for torch tensors

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1696]
This is a child issue of https://github.com/OpenMined/PySyft/issues/1695. Please check this issue to see if you have anything you need.

Initialize a pointer to this tensor with .create_pointer().
- [x] Instanciate a pointer tensor that inherits from an Abstract / Syft Tensor
- [x] Define appropriate attr (torch_type, location, id_at_location, owner, skip_register)

**Comment by Nivek92** [comment]
This is finished isn't it?

**Comment by LaRiffle** [comment]
Yes it is, the PR #1706 does only need a better coverage in tests
I'll do this when I find some time, any contrib welcome :)
