### ISSUE TITLE
Adding .send() to torch.Tensor()

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1697]
This is a child Issue of https://github.com/OpenMined/PySyft/issues/1695. Be sure to check the parent issue to ensure this issue has all dependencies required to finish it.

In this issue, you should add the method .send() to torch.Tensor. This tensor should call .create_pointer() (to create a pointer), then serialize the tensor, and send the message to a remote worker. Thus, this method will accept two parameters: self and location. It will return the pointer object.

This issue relies on two Sub Issues to be accomplished first (in order):

- [ ] register_obj() added to BaseWorker  #1699
- [ ] receive_obj() added to BaseWorker

Final Acceptance Criteria:
- [ ] ensure .send() works as described above
- [ ] .send() has correct docstrings (and any other functions created while creating .send() )
- [ ] .send() has several unit tests. In particular it should test sending tensors of ALL types (Float, Int, etc.)

Known Dependencies: torch.Tensor must already have .create_pointer() and .serialize() implemented.

**Comment by LaRiffle** [comment]
One point I remember discussing is whether we should rather ask the remote worker the storage address, instead of forcing him to use a given one, which could be already be in use.
Any thoughts?

**Comment by Ogofo** [comment]
I think this is a good idea. I think it would make the most sense, to send the object to the `storage_worker` and let him respond with a `storage_id`. That way we can create a PointerTensor with `id_at_location=storage_id`.

**Comment by LaRiffle** [comment]
Yes I agree, but one drawback is that the operation needs to be synchronous and wait for the response.

**Comment by Ogofo** [comment]
True. That could slow down the process. 

Another approach could be to just store an internal reference to the remote Tensor within the PointerTensor. The Remote Worker would register the Tensor with his own chosen ID and create a mapping between the PointerTensor ID and his own remote ID.

To clarify the example: 

```
# local worker
ptr_on_local_worker = tensor.send()

# remote worker
remote_worker.receive(tensor, ptr_id)

def receive(self, tensor, ptr_id):
    id_on_remote_worker = self.register(tensor)
    mapping.add(ptr_id, id_on_remote_worker)
```

**Comment by LaRiffle** [comment]
Yes, basically have an internal storage id which is a function `f` : `id_on_remote_worker = f(<worker>, <ptr_id>)`  should be fine !
