### ISSUE TITLE
Add register_obj() to worker

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1699]
This is a sub issue of #1697 

Objects given as args should be registered by the worker, meaning they should be included in the worker registry `self._objects`

**Comment by Nivek92** [comment]
That's already solved by `bob.send_obj(obj, alice)`

**Comment by Nivek92** [comment]
Whats missing from the original register_object method is the creation of a pointer and changing the owner of the obj. 

Other than that it will add the object to the _object dictionary using the id of the obj.

But do we need a seperate method than or wouldn't it be better to adjust one of the existing methods? e.g. the set_obj or recv_msg

**Comment by LaRiffle** [comment]
Sometimes you want to register tensors that are included in a rather complex response, like tuples, dictionary which include tensors.
In this case I think a separate  method is useful to handle registration gracefully
But it could also be included in the deserialize logic since we already iterate in the response
