### ISSUE TITLE
Initial Garbage Collection Support for PointerTensor 

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1701]
This is a child Issue of https://github.com/OpenMined/PySyft/issues/1695. Be sure to check the parent issue to ensure this issue has all dependencies required to finish it.

In this issue, we want to make it so that when a PointerTensor goes out of scope, the tensor that it is pointing to also gets deallocated. In particular, we want to VERY robustly test this functionality (with all tensor types) so that any later code doesn't break this (i.e., by accidentally creating circular dependentices, etc.)

- [x] add .del() command which a worker can receive and correctly use to deallocate/deregister a tensor
- [x] override \__del__ for PointerTensor objects so that they send the delete command
- [x] extensively test this functionality to ensure it works in a variety of ways (both for explicit "del x" and for automatic garbage collection)

Other Acceptance Criteria
- [x] all methods have robust doc strings
- [x] EXTENSIVE tests demonstrating both automatic and explicit garbage collection working correctly for ALL tensor types (Float, Int, etc.) 

Known Dependencies: torch.Tensor must already have .send() and PointerTensor must have .serialize() implemented.

**Comment by mari-linhares** [comment]
I'm planning to have a look at this.

**Comment by iamtrask** [comment]
Me too - with the PR I just merged a few minutes ago we should be more or less ready.
