### ISSUE TITLE
train() function in 'Intro to Federated Learning.ipynb' example code

### ISSUE THREAD

**Issue by miranthajayatilake** [OpenMined/PySyft#1725]
Hi,
First of all, great work Trask! Loving your work. 
I'm following the tutorials and in the Federated Learning notebook example, when passing each worker's dataset to the sent model, shouldn't we pass `data_bob` as a parameter to the function?

I'm talking about the function here :-

```
def train():
    # Training Logic
    opt = optim.SGD(params=model.parameters(),lr=0.1)
    for iter in range(20):
        
        # NEW) iterate through each worker's dataset
        for data,target in datasets:
            
            # NEW) send model to correct worker
            model.send(data.location)

            # 1) erase previous gradients (if they exist)
            opt.zero_grad()

            # 2) make a prediction
            pred = model(data)
```

I think that the function should have a parameter input as `def train(dataset)` in order to pass each worker's data. Am I wrong? Would love to clarify.

Thanks!

**Comment by iamtrask** [comment]
Hi @miranthajayatilake!!! This function would be greatly improved if the "model" and "datasets" variables were passed in as a parameter! PR Welcome!

**Comment by miranthajayatilake** [comment]
Thank you very much for the response! I will look into it.
