### ISSUE TITLE
[Discussion] Running pytorch tests as part of the CI to ensure hook stability

### ISSUE THREAD

**Issue by Ogofo** [OpenMined/PySyft#1735]
As part of #1587 we are still hooking pytorch. I would suggest to hook pytorch and run the pytorch tests, to ensure that the hook is stable and the pytorch functionality is ensured. 

Potential Challenges:
- CI time would increase
- CI with GPU support seems to be an issue - potentially requires a custom (community funded) CI server

Pros:
- PySyft would ensure that the complete pytorch functionality is preserved and the security + federal learning feature is added on top!

Thougts?

**Comment by robert-wagner** [comment]
I like this idea in theory. However I think it is most likely something that we should address if it starts being a serious issue in practice
