### ISSUE TITLE
Working Documentation

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#1743]
In order to have more people have an understanding of the project beyond the tutorials the documentation (https://pysyft.readthedocs.io/en/latest/) needs to be working.

**Comment by Ogofo** [comment]
Definitely! This is already part of the Torch 1.0 refactor #1587 but more as a constraint.

**Comment by kamathhrishi** [comment]
@robert-wagner Shall I close this issue?

**Comment by mari-linhares** [comment]
closing it :), feel free to re-open this if needed @robert-wagner
