### ISSUE TITLE
Tests not Working 

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#1756]
Tests were working all fine  until recently when I ran `make test` locally. 

I get these errors. Any idea on how I could resolve it?

```
test -e venv/bin/activate || python -m venv venv
Error: Command '['/Users/hrishikesh/Hrishikesh/Projects/PySyft/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
make: *** [venv/bin/activate] Error 1
```

**Comment by iamtrask** [comment]
Hmm - I'm really not sure. Maybe try rebuilding your virtual environment?

**Comment by kamathhrishi** [comment]
@iamtrask  That did the trick!
