### ISSUE TITLE
Torch1: Format for send_obj

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1763]
I observed the actual recommended format for sending an object is `{'id': obj_id, 'data':obj}` (see send_obj, set_obj)
I would be tempted to use (obj_id, obj) like the tuple format which is used in ser/deser
Does smthg go agains this?

**Comment by Ogofo** [comment]
This is with respect to our conversation in #1697, correct? I approve the format as it makes the most sense to me.

**Comment by robert-wagner** [comment]
I don't see any issues with this. Let's change it!

**Comment by LaRiffle** [comment]
Ok it's changed!
