### ISSUE TITLE
Ser / deser attributes id and owner of tensors

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1772]
The attributes id and owner are not kept in the builtin methods on torch tensor used to serialize / deser.

Can we:
1. Overload theses methods to handle this
2. transfer them aside and add them together as attributes
3. Do we really need them?

**Comment by Ogofo** [comment]
I'm addressing your questions from bot to top. 

Regarding point 3. I'm not entirely sure. I think it will depend on the workflow:

1. Sending a Tensor to a remote worker
Regarding the discussion in #1697 I don't think we need either variable as they are newly set by the remote worker anyways. 

2. Saving a Tensor to disk
This depends if we want to be able to save a complete syft-instance to disk with all the workers and tensors staying connected. If we don't care about the worker <-> Tensor relation we could simply save the tensors and assign them a new worker once we loaded them. This probably depends on whether the syft worker will hold a state at a later point, but one could build a workaround to save a worker and assign the loaded worker to all tensors.

3. Future/other syft-variables
I'm not sure what else we are going to add in the future and If this might be a necessity so send syft variables attached to a tensor to the remote worker. 

---
Regarding your second point: this is totally possible. I'm not sure how "big" the variables might get that we want to transfer, but we should be able to build a deserialization for this. 

--- 
Regarding your first point: Currently, a Tensor is saved via `torch.save()`. We would have to hook into https://github.com/pytorch/pytorch/blob/master/torch/serialization.py which I would not like to do if possible.

**Comment by LaRiffle** [comment]
I do agree with you, I think we could avoid these tensors attribute because:
1. owner is trivial
2. id is not: we expect a ptr = x.send()  then x2 = ptr.get() to return an x2 with the same id than x. But if the id is transmitted to the PointerTensor and given back this would work.

**Comment by iamtrask** [comment]
I *think* this issue was addressed in https://github.com/OpenMined/PySyft/pull/1791

**Comment by LaRiffle** [comment]
Ok this is the behavior with currently have in serde.py
