### ISSUE TITLE
Refactor all docstrings in the torch_1 branch to Google style

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1784]
As we are now able to compile google style docstrings into sphinx docs, we should switch all the docs over to google style for consistency and readability.

Part of #1783

**Comment by Ogofo** [comment]
Reference: 
https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

**Comment by iamtrask** [comment]
It seems like we're really close on this one - only a couple places where we lack! I spotted missing docstrings in VirtualWorker (virtual.py)

**Comment by LaRiffle** [comment]
Should we close this issue for now? I think we're quite good.
