### ISSUE TITLE
MNIST Example 

### ISSUE THREAD

**Issue by suhelsayyad2006** [OpenMined/PySyft#1804]
In notebook available in Experimental section for MNIST Training it is seen that worker are created.
Does the code mentioned in 2 takes cares of privacy preserving of data elements. 
Why share methods to data on MNIST are not used ?

**Comment by LaRiffle** [comment]
Nicely spotted, the code in https://github.com/OpenMined/PySyft/blob/master/examples/other/experimental/MNIST%20Example.ipynb does not perform  privacy preserving training or anything federated. I suspect it was a demo which wasn't finished, that's why it's in `experimental` :)
