### ISSUE TITLE
Turning off async

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1810]
This issue is a subissue of #1659 
We want to be able to turn of async in order to have debugging purposes. If there is not a clean way to do this, this issue may not be implemented.

Successful completion of this issue includes

- [ ] a function or context manager which turns off async commands after it
- [ ] tests which ensure that the functionality inside and outside the context manager is the same (minus the async part)

**Comment by iamtrask** [comment]
Irrelevant given new Async Design schema
