### ISSUE TITLE
Boston Housing server-client demo under /examples/torch

### ISSUE THREAD

**Issue by lovicwhite** [OpenMined/PySyft#1813]
Hi, I mat some problems when trying these two demos:

https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training%20with%20Diff%20Privacy%20SERVER.ipynb

https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training%20with%20Diff%20Privacy%20CLIENT.ipynb

On client side, when coming to this line, error shows like this:
![client-side1](https://user-images.githubusercontent.com/33448800/50941363-91446b00-14bf-11e9-90e8-bae686205247.png)

Then when re-running this line, error changes into this:
![client-side2](https://user-images.githubusercontent.com/33448800/50941385-ac16df80-14bf-11e9-8aaa-b68ca71b334f.png)

When re-runing this line again( the 3rd time), error will disappear:
![client-side3](https://user-images.githubusercontent.com/33448800/50941447-e3858c00-14bf-11e9-9354-18f5b29f7f54.png)

Now, on server side, an error appears:
![server-side](https://user-images.githubusercontent.com/33448800/50941489-09ab2c00-14c0-11e9-9c6e-552d04d44819.JPG)

I run server side and client side on two different machines.

**Comment by jlebensold** [comment]
This notebook has been deprecated on the master branch.
