### ISSUE TITLE
cannot import name '_set_worker_signal_handlers'

### ISSUE THREAD

**Issue by jidroid404** [OpenMined/PySyft#1815]
Unable to get a Hook in Remote PyTorch using Virtual Worker.ipynb(colab notebook)

![screenshot 96](https://user-images.githubusercontent.com/43285614/51068968-ef9e5480-164b-11e9-8eed-251c781788d9.png)
![screenshot 97](https://user-images.githubusercontent.com/43285614/51068969-ef9e5480-164b-11e9-985d-18fa36b37c34.png)

**Comment by param087** [comment]
It seems problem related to the torch GPU torch version 0.3.0 vs  0.3.1 just comment the following lines in first shell of colab notebook.

```
#accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'
#!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.3.0.post4-{platform}linux_x86_64.whl torchvision
#import torch
```

It will work just fine or you can check for torch GPU v0.3.1
here the working colab notebook of me : 
https://colab.research.google.com/drive/1OWl-iud3gSM7ZYyEkK2EVr0q8zNIe0C9
