### ISSUE TITLE
Issues about Tutorial Part-7

### ISSUE THREAD

**Issue by lovicwhite** [OpenMined/PySyft#1816]
When trying to follow the tutorial part 7--Encrypting / Decentralizing the ledger, I found tensors after operation('+' or '-') will lose their dimension, is it the expected behavior, or a bug?
![ledge1](https://user-images.githubusercontent.com/33448800/51094287-974f8a00-17e6-11e9-9a97-19c334472b52.png)
![ledge2](https://user-images.githubusercontent.com/33448800/51094311-b6e6b280-17e6-11e9-9282-b60f9ff5e380.png)

**Comment by jlebensold** [comment]
This example is now part of a deprecated branch.
