### ISSUE TITLE
Constructor of torch.Tensor is broken in the torch_1 branch

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1817]
Currently in the torch_1 branch we are unable to construct tensors which require gradients (formerly known as variables). The proper way to do this is ` torch.Tensor(<list>, requires_grad=True)` On the current version this returns the error of
```
TypeError                                 Traceback (most recent call last)
<ipython-input-28-35439c5a0d54> in <module>
----> 1 x = torch.Tensor([1,2,3,4,5], requires_grad=True).send(bob)
      2 y = torch.Tensor([1,1,1,1,1], requires_grad=True).send(bob)

TypeError: new() received an invalid combination of arguments - got (list, requires_grad=bool), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
```

**Comment by robert-wagner** [comment]
@LaRiffle @iamtrask if you had any insight on this issue that would be appreciated

**Comment by iamtrask** [comment]
trask [3:30 PM]
x = torch.tensor([1.,2,3,45], requires_grad=True)

Théo Ryffel [3:30 PM]
`x = torch.tensor([1.,2,3,4,5], requires_grad=True)``

trask [3:30 PM]
:point_up: that works
x = torch.Tensor([1.,2,3,45], requires_grad=True)

**Comment by robert-wagner** [comment]
I am reopening this because we are unable to call send on torch.tensor which means either we need to hook torch.tensor or get pytorch to fix this issue upstream (ideally both) cc @iamtrask

**Comment by LaRiffle** [comment]
Note that hooking `torch.tensor` is not trivial since you can't add any attributes, if you try you get:
`AttributeError: 'builtin_function_or_method' object has no attribute 'my_attr'`

**Comment by LaRiffle** [comment]
One work around for `owners` could be adding owner as a property:

```
@property
        def owner(self):
            if not hasattr(self, "_owner"):
                self._owner = hook_self.local_worker
            return self._owner

        @owner.setter
        def owner(self, new_owner):
            self._owner = new_owner
            return self

        tensor_type.owner = owner
```

**Comment by robert-wagner** [comment]
Got this to work by just doing initialization normally then adding the attributes after
