### ISSUE TITLE
Organize tensors -> Decorators and Interpreters

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1819]

**Comment by param087** [comment]
Hi Andrew,
I want to work on this issue. Any example or sample regarding Organize tensors -> Decorators and Interpreters will be very helpful.

**Comment by param087** [comment]
@iamtrask - I have started to work on this issue, If I get stuck somewhere I will let you know.

**Comment by param087** [comment]
hello @iamtrask -  I have started to work on this issue, If I get stuck somewhere I will let you know.

**Comment by param087** [comment]
hey @iamtrask , I have moved  
1. log.py file from syft/frameworks/torch/tensors/ into syft/frameworks/torch/tensors/decorator folder
2. Other files from syft/frameworks/torch/tensors/  into  syft/frameworks/torch/tensors/interpreters folder. 
3. added and updated all required import statements from the syft/ , test/ folder.

Please tell me, if there any additional suggestions and corrections.
[https://github.com/param087/PySyft/tree/torch_1](Organized tensors -> Decorators and Interpreters)
