### ISSUE TITLE
Test hook.py should be modified to not use class structure

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1835]
We do not need to use the class structure required by unittest with pytest. Doing things in the pytest style of not having tests inside a testing class makes cleaner code and avoids side effects of tests interacting. As such the test_hook.py file should be refactored to the pytest style (see other tests for examples)

**Comment by alexis-thual** [comment]
I could try and do this one if you want to assign me :)

**Comment by alexis-thual** [comment]
Sorry akki, there seem to be some overlap in our works...
I basically refactored all test files, except from `./test/workers/test_worker.py` and `./test/test_serde.py`.

@robert-wagner it seems that I can't add you to the reviewers of the PR I just opened. I left a couple of comments in the PR if you want to read them first!

**Comment by robert-wagner** [comment]
As this work has been done twice, I'm closing this now
