### ISSUE TITLE
Federated Learning - Implement MNIST / ConvNet Example

### ISSUE THREAD

**Issue by jlebensold** [OpenMined/PySyft#1869]
This example should use FederatedDataset

**Comment by LaRiffle** [comment]
I'm doing good progress in having the CNN layers + Pool + backward working in a full FL setting.
Ping me if you open a PR on this, I'll add my work to have the complete example with the FederatedDataset :)

**Comment by LaRiffle** [comment]
I've open one on this topic: #1894
