### ISSUE TITLE
Spelling mistake in the README

### ISSUE THREAD

**Issue by pranav-ap** [OpenMined/PySyft#1884]
Hi,
I was going through the README and found a minor spelling error in Siraj Raval's name. It says Rav**e**l, but should be Rav**a**l. 

Honestly, I think this is probably the single biggest contribution anyone has ever anyone made in Github history.  
: )

Cheers,
Pranav

**Comment by param087** [comment]
Hi @pranav-ap,  Just make a PR with corrected spelling.

**Comment by pranav-ap** [comment]
Yeah, its done.
