### ISSUE TITLE
Implement Base Tensor Object

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#19]
In this ticket, we want to create a new basic type called a "Tensor". A Tensor is a nested list of numbers with an arbitrary number of dimensions. With one dimension, it's a list of numbers known as a "vector". With two dimensions, it's a list of lists of numbers known as a "matrix". In this ticket, we want to build our implementation of Tensor with inspiration from PyTorch's  [Tensor](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py) object ([Tensor Docs](http://pytorch.org/docs/master/tensors.html)). 

So, in this ticket, you should build a basic tensor class. You should be able to pass in as an argument an arbitrary shape (number of rows, columns, etc.) when you create it. Furthermore, we want this basic class to support elementwise addition, subtraction, multiplication, and division.

Acceptance Criteria:
- __init__ supports initializing a tensor with an arbitrary number of dimensions and arbitrary scalar type (test with float and int)
- elementwise operators for +-/* and their inline operators should be overridden
- elementwise operations should check to make sure both tensors are of identical dimension
- elementwise operators should also support (and automatically detect!) the input of a single number, which should be applied to the entire tensor (aka... multiply every number by "5").

**Comment by TheOriginalAlex** [comment]
Does this depend on #10?  Do we wanna extend this Tensor class off of the generic Tensor that will be created?

**Comment by iamtrask** [comment]
Ah1 I need to put this in the Contributor Quickstart Guide. Install the ZenHub plugin. zenhub.com That will show you that this ticket is a subset of #10 and in fact the first stepping stone to achieving #10
