### ISSUE TITLE
rename functions in hook_args.py to better say what they do

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1903]
Currently a lot of the functions in hook_args.py have very similar/confusing names which make it difficult to see at a glance what they do. These should be renamed to more vebosely state their purpose

**Comment by sashank06** [comment]
is this issue still open?

**Comment by mari-linhares** [comment]
@robert-wagner can we close this?

**Comment by robert-wagner** [comment]
@sashank06 is on this

**Comment by ajnovice** [comment]
I hope to work on this issue. Is this still open?
