### ISSUE TITLE
Where should I hook? Choosing the right level.

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1906]
I'm currently working with fixed precision tensors (see PR #1897).
In this PR, I had to unhook nn.Linear because it contains the operation `a*x + b`. Indeed, multiplication should be controlled at the fixed precision level (for truncation after multiplication) which you can't do if you hook Linear. Because if you do, then `a*x + b` happens on the LongTensors which are below the precision tensor and the aggregation result is unusable.

Example:
 a = 2.0, x = 3.0, b = 1.0, precision_fractional = 3
 - without hook on Linear:
    a*x + b = [(2000 * 3000) / 10e3 + 1000 ] / 10e3 = 7.0
 - with hook on Linear
    a*x + b = [(2000 * 3000)  + 1000 ] / 10e3 = 6001.0

So there are some tensors like MPC or precision which can't handle "high level" functions, but they can deal with the native implementation of these functions (typically nn.Linear). So I'm incline to think that we could have a double level of hooking: a high level hook (typically you want pointer to handle nn.Linear and not to send the details operations of it; so hook every thing you can) and low-level hook (typically you want the precision tensor to understand what is the recipe for doing nn.Linear with low-level operations [and you definitely don't want to rewrite the recipe which is already in torch.nn.functional]; so hook nothing but low-level ops that you can handle specifically).

**Comment by iamtrask** [comment]
TODO: make this string comparison more efficient

https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/tensors/interpreters/precision.py#L190

**Comment by LaRiffle** [comment]
solved by #2005
