### ISSUE TITLE
Optimizer and momentum for remote tensors

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#1909]
As you know, optim with momentum keeps old gradients in a buffer.
However, when gradients are pointers, it becomes really tricky if you move the parameters from a worker to another, which is exactly what we do in tutorial Part 8. Let's say you move from bob to alice, then you will try to update parameters at alice using a buffer containing pointers to bob, and you get in real trouble.

So, how should we handle this? Drop the buffer by hand? Having different optimizers and different models? Or another solution?

**Comment by manu-sk** [comment]
Any updates for this?

**Comment by dcato98** [comment]
I think this was solved by #3179, where each worker now maintains it's own optimizer. However I'm pretty new here so I may be missing something.

**Comment by karlhigley** [comment]
I'm not sure that #3179 was intended to add full support for momentum-based optimizers. It certainly seems like a step in the right direction, but it's not clear that momentum-based optimizers are fully compatible with the rest of PySyft.
