### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by Alpslee** [OpenMined/PySyft#192]
wuweilindeMacBook-Pro:~ Rand$ cd pysyft
wuweilindeMacBook-Pro:pysyft Rand$ make test
pytest
make: pytest: No such file or directory
make: *** [test] Error 1

**Comment by iamtrask** [comment]
this seems to work ok for me... can you confirm it still doesnt work for you (on master)? 

Also, does running "pip install -r requirements.txt" help?

**Comment by Alpslee** [comment]
pip install -r requirements.txt works fine.cd pysyft
is that below normal?
wuweilindeMacBook-Pro:pysyft Rand$ make run
docker run --rm -it -v /Users/Rand/pysyft/notebooks:/notebooks -w /notebooks -p 8888:8888 openmined/pysyft jupyter notebook --ip=0.0.0.0 --allow-root
[I 21:20:35.654 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 21:20:35.703 NotebookApp] Serving notebooks from local directory: /notebooks
[I 21:20:35.703 NotebookApp] 0 active kernels 
[I 21:20:35.703 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/?token=2d5354b98f57aa22745080e7dd63c7fa6da59bcef526d4d6
[I 21:20:35.704 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 21:20:35.705 NotebookApp] No web browser found: could not locate runnable browser.
[C 21:20:35.705 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://0.0.0.0:8888/?token=2d5354b98f57aa22745080e7dd63c7fa6da59bcef526d4d6

**Comment by iamtrask** [comment]
do you have a browser installed?

**Comment by Alpslee** [comment]
yes,of course

**Comment by iamtrask** [comment]
(just checking... you could have been running it on AWS or some other headless node)

**Comment by Alpslee** [comment]
no,I just turned  docker on.btw,what is headless node?

**Comment by iamtrask** [comment]
a headless node is one without a monitor... like when you rent a server on Amazon EC2 :)

**Comment by iamtrask** [comment]
ah... pytest is a local dependency

**Comment by iamtrask** [comment]
you can install it conda install -c anaconda pytest

**Comment by iamtrask** [comment]
or with pip: pip install pytest

**Comment by iamtrask** [comment]
i'll add it to requirements.txt and close this out.
