### ISSUE TITLE
Sampling in SPDZ Tensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1927]
In order to do differential privacy on an encrypted tensor, we need to be able to sample from a Laplace and/or Gaussian distribution. In theory this can be done based on the exponential sampling mechanisms described here (https://link.springer.com/content/pdf/10.1007/11761679_29.pdf).

**Comment by robert-wagner** [comment]
With this in mind, gaussian sampling is very easy to do in an additivly shared setting (the sum of two gaussians is a gaussian)

**Comment by kamathhrishi** [comment]
This could be implemented in the Polynomial tensor ?
