### ISSUE TITLE
Unit Tests for Sensitivity Tensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1929]
This ticket is a sub-ticket of the #1824 Epic.

So in order to be able to track privacy leakage - we need to track sensitivity. We're making a tensor to do this in the examples/experimental folder. We are currently on version 3.

And to make sure it works correctly - we want to use the examples from this book where sensitivity has been correctly calculated and use them as unit tests. (other resources/papers also welcome) https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf

These test can be implemented in a new version of the notebook in experimetnals folder. Eventually these tests will be moved to PySyft directly.

**Comment by mari-linhares** [comment]
Currently not I'm working on this, but I would like to help in the future.
