### ISSUE TITLE
Create FL Demo with DP-SGD Optimizer

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1933]
This is a sub-issue of the #1824 Epic. 

Similar to the [previous demo](https://github.com/OpenMined/PySyft/blob/torch_031/examples/torch/Boston_Housing_Federated_Training%20with%20Diff%20Privacy%20CLIENT.ipynb) in the 0.3.1 version of the stack, we want to use the DP-SGD optimizer to train a differentially private federated learning model. This should use our SensitivityTensor, MomentsAccountant, and DP mechanisms previously implemented into PySyft for the budget calculation.

**Comment by dionman** [comment]
is there any progress in this ?

**Comment by Kritikalcoder** [comment]
Is anyone working on this?

**Comment by karlhigley** [comment]
@Prtfw is probably the most knowledgeable about where we are with demos. Thoughts on whether/how to tackle this @Prtfw?

**Comment by Prtfw** [comment]
@karlhigley @Kritikalcoder looks like this issue isn't ready to be worked on yet. see https://github.com/OpenMined/PySyft/issues/1824 and in particular issue https://github.com/OpenMined/PySyft/issues/1932

**Comment by karlhigley** [comment]
@trask What's the status on those issues? Are they still accurate/relevant?
