### ISSUE TITLE
Import error in “Paillier Homomorphic Encryption Example”

### ISSUE THREAD

**Issue by siarez** [OpenMined/PySyft#194]
The very first line in the file notebook is
`from syft.he.Paillier import KeyPair`
I get an import error. Changing “Paillier” to “paillier” solved the problem. 
Python import has some quirks around case sensitivity on OSX which should be considered. In general “Modules should have short, all-lowercase names. ... ”
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by siarez** [comment]
Can this be my first PR to get my feet wet?

**Comment by iamtrask** [comment]
certainly! however, i may have accidentally just pushed the fix

**Comment by minujawahar** [comment]
from syft.he.paillier import KeyPair

my error is No module named 'syft.he'.
how to solve these error?
