### ISSUE TITLE
Build a Named Tensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1943]
There was a really cool post on NamedTensors not too long ago - and I thought that since we're one of the only projects which makes it easy to create custom Torch tensor types - it might be worth having a go if anyone was interested.

Full details on how such a project would be done can be found here - http://nlp.seas.harvard.edu/NamedTensor

**Comment by mcleonard** [comment]
Yeah! NamedTensors look awesome. This would definitely be a fun project at some point.
