### ISSUE TITLE
Looking for a runnable demo

### ISSUE THREAD

**Issue by hu6360567** [OpenMined/PySyft#1945]
The tutorial is almost broken, and unfinished.
I'd like to find pieces of example code on federated learning with SMC and DP.
Is there any of them?

**Comment by kamathhrishi** [comment]
The tutorials on Federated Learning are very much working :) 

https://github.com/OpenMined/PySyft/tree/dev/examples/tutorials for Torch1 version of PySyft. Currently, Torch 1 supports only federated learning and DP is under experimental which you could review if you would like to. 

 We did have SMPC on our previous version supported for torch 0.3.1 version only.

https://github.com/OpenMined/PySyft/tree/torch_031/examples/tutorials

**Comment by hu6360567** [comment]
Thanks a lot.
I'll try on torch_031 branch.
