### ISSUE TITLE
Laplace Mechanism with proper Floating Point Snapping Mechanism 

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1953]
We need a Laplace Mechanism for Differential Privacy which is fitted with the proper [Snapping Mechanism](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.366.5957&rep=rep1&type=pdf) so that it can be used with FloatingPoint operations. It should be usable with the SensitivityTensor out of the box.

**Comment by iamtrask** [comment]
Related: https://arxiv.org/pdf/1306.2691.pdf

**Comment by Kritikalcoder** [comment]
I want to take this up. Is this still valid?
