### ISSUE TITLE
Automatically add workers to known workers

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1958]
Since each worker has access to the hook, we are able to get the workers that the local workers has knowledge of at creation. This allows us to automatically add the new worker on spinup to all workers known workers

**Comment by alaaboudib** [comment]
I am interested in this issue. However, I am new to PySyft, I just followed the 8 tutorials. Can you please explain this issue a bit more? maybe give a concrete example of what you are willing to have as a result?

**Comment by robert-wagner** [comment]
Hey @alaaboudib I didn't see that you were interested in doing this issue before completing it myself this morning. Sorry about that :slightly_smiling_face:

**Comment by alaaboudib** [comment]
No problem @robert-wagner , can you refer me to your PR to learn more about how you did it?

**Comment by robert-wagner** [comment]
Hey @alaaboudib I tagged you in the pr (it is linked above this message)

**Comment by alaaboudib** [comment]
Thank you @robert-wagner
