### ISSUE TITLE
Get .max() working on PointerTensor; multiple ptrs in response

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1975]
We can't return tuples of tensors when calling remote executions. This means that functions like .max() fail on PointerTensor objects.

**Comment by bhushan23** [comment]
```
import torch 
import syft as sy
hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id="bob")
x = torch.tensor([1,2,3,4,5])
x_ptr = x.send(bob)
print(x_ptr.max())
```

Currently, `x_ptr_max()` returns  `(Wrapper)>[PointerTensor | me:73509977871 -> bob:73509977871]`
and should return `5` right?

**Comment by bhushan23** [comment]
@iamtrask I was wondering, if we should build an interface to directly enable all torch tensor functionalities to pointer tensor? Is that something useful? Do we require all torch functionality for pointer tensor? Why do we specifically need max?

**Comment by LaRiffle** [comment]
max is one between others (torch.split, etc.), basically all functions that can return more than one tensors with fail if they are run remotely as we explicitely always make the assumption the response is a unique tensor.
