### ISSUE TITLE
bug in Federated learning on MNIST using CNN while loading federated dataset !

### ISSUE THREAD

**Issue by Adarshsng** [OpenMined/PySyft#1981]
Hi,
In the FederatedDataLoader function
on the execution of this  statement
federated_train_loader = sy.FederatedDataLoader( datasets.MNIST('../data', train=True, download=True, transform=transforms.Compose([ transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,)) ])) .federate((bob, alice)), batch_size=args.batch_size, shuffle=True, **kwargs)

It gives this as an ERROR :-

'MNIST' object has no attribute 'federate'

 any suggestion or procedure can help!
Thank you.

**Comment by LaRiffle** [comment]
Would you mind sharing the complete snippet of code you used?
Thanks!

**Comment by Adarshsng** [comment]
*THIS IS  THE CODE SNIPPET :- *
federated_train_loader = sy.FederatedDataLoader( # <-- this is now a FederatedDataLoader 
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))
    .federate((bob, alice)), # <-- NEW: we distribute the dataset across all the workers, it's now a FederatedDataset
    batch_size=args.batch_size, shuffle=True, **kwargs)

test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=args.test_batch_size, shuffle=True, **kwargs)

*THIS IS THE ERROR :- *

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-4085cd6569bc> in <module>
      3                    transform=transforms.Compose([
      4                        transforms.ToTensor(),
----> 5                        transforms.Normalize((0.1307,), (0.3081,))
      6                    ]))
      7     .federate((bob, alice)), # <-- NEW: we distribute the dataset across all the workers, it's now a FederatedDataset

AttributeError: 'MNIST' object has no attribute 'federate'

**Comment by Adarshsng** [comment]
> Would you mind sharing the complete snippet of code you used?
> Thanks!

https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Part%208%20-%20Federated%20Learning%20on%20MNIST%20using%20a%20CNN.ipynb

 I tried to run exact code from this link but it showed that error.

**Comment by LaRiffle** [comment]
Oh this is strange, and you didn't make any changes in the code or imports ?

**Comment by geochri** [comment]
> > Would you mind sharing the complete snippet of code you used?
> > Thanks!
> 
> https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Part%208%20-%20Federated%20Learning%20on%20MNIST%20using%20a%20CNN.ipynb
> 
> I tried to run exact code from this link but it showed that error.

I have the same error!

**Comment by mari-linhares** [comment]
Hey @Adarshsng, are you still getting errors with the most updated version of syft and torch?

**Comment by fdoherty13** [comment]
Would be cool to see applications of CNN's in the field of construction and project management, nothing to do with bug fixes in code - but a life-saving idea nonetheless. I know most devs focus on merchandise and e-commerce when applying a convolutional, yet there exists a vast library of architecture and blueprints from companies in mech engineerin' (Caterpillar, John Deere, Toyota) that remain in the dark  Hopefully if you manage to debug the FederatedDataLoader you could find time to explore new datasets

Gears Churnin'

**Comment by kicKORhIT-16384-needSYDney** [comment]
> > Would you mind sharing the complete snippet of code you used?
> > Thanks!
> 
> https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Part%208%20-%20Federated%20Learning%20on%20MNIST%20using%20a%20CNN.ipynb
> 
> I tried to run exact code from this link but it showed that error.

link broken.

**Comment by edgarinvillegas** [comment]
This error appears when you haven't hooked PySyft:
`hook = sy.TorchHook(torch) `
`bob = sy.VirtualWorker(hook, id="bob") `

Can you review you did that?
