### ISSUE TITLE
Increase test coverage to 100%

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#1989]
Currently we have 95% coverage. Ideal that coverage would be 100%

**Comment by Ankk98** [comment]
I would like to start my contribution to OpenMined with this issue.

**Comment by Ankk98** [comment]
This issue is assigned or I can work on it?

**Comment by robert-wagner** [comment]
@Ankk98 Feel free to work on it! I will be iterating on it over time but would love any help.

**Comment by Ankit-Dhankhar** [comment]
@robert-wagner can we integrate https://codecov.io/ for coverage test during the pull request integrated in travis.ci? 
Most of organisation use this for check coverage of pull request.
