### ISSUE TITLE
Urgent: fail gracefully when initializing two VirtualWorker objects with the same id/name

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1992]
When people are introduced to PySyft, they often fall into the mistake (particularly in Jupyter Notebbooks) of initializing a VirtualWorker with the same ID twice. This causes really strange errors because both workers end up co-existing together. We need to modify the VirtualWorker (or perhaps the BaseWorker) API to make it so that this fails gracefully (aka... that the new worker actually becomes the old worker or all intensive purposes)

Aka - we want this code to function normally

bob = sy.VirtualWorker(hook, "bob")

x = th.tensor([1,2,3,4,5]).send(bob)

bob = sy.VirtualWorker(hook, "bob")

y = th.tensor([1,2,3,4,5]).send(bob)

z = x + y

z.get() # returns [2,4,6,8,10]

We should accomplish this by having both the new "bob" and the old "bob" point to the same underlying _objects dictionary.

**Comment by LaRiffle** [comment]
At any moment, you can check all the virtual workers present on your process by retrieving syft.hook.local_worker.(known_workers) as they get automatically added to this list on __init__. Just making a search and returning the already existing one if any should fix the pb

**Comment by robert-wagner** [comment]
@LaRiffle Tried this out. Trying to naively return the known worker with the same id, causes over half of the tests to fail. I am of the impression it might be best to make this simply throw a verbose error for the moment. #2000 for reference to my changes

**Comment by mari-linhares** [comment]
@robert-wagner just tried your solution (#2000) with a small modification and it seems to work, can you check if it makes sense just made the PR #2022. Thanks!
