### ISSUE TITLE
Add status for Plan

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2003]
Add a status attribute which gives a bit of information about the plan task: is the plan built / sent / run / failed / etc.

Inspiration can be found on the celery project syntax -> http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html

**Comment by mari-linhares** [comment]
Hey @LaRiffle, can you point me to where in celery project syntax it mentions task? Should the status be a string indicating the last operation performed with the plan?

**Comment by jcezarms** [comment]
@mari-linhares it mentions it by the name "state". If you `CTRL+F state` on the given link, you can see for example [how they manage `PENDING` states](http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#result-backend-doesn-t-work-or-tasks-are-always-in-pending-state), and in their docs there's also a [list of all built-in states](http://docs.celeryproject.org/en/latest/userguide/tasks.html#built-in-states).

**Comment by jcezarms** [comment]
Just to point out, they also [support custom states](http://docs.celeryproject.org/en/latest/userguide/tasks.html#custom-states), which in my opinion would be a nice feature to support here as wel.
