### ISSUE TITLE
Configuration of the system

### ISSUE THREAD

**Issue by mccorby** [OpenMined/PySyft#2009]
While working on `seder` I found out that more and more having a configuration would help when adding workers.
In the case of external workers (Android, web sockets) they do not have direct access to the configuration used when starting the federated setup. Though part of this information can be inserted in the stream sent and received by the workers other is only part of a set of assumptions

Having a configuration when a worker starts would have some benefits as:
* Knowing which serialisation is in use
* Homogenisation of the compression schemes. If a worker cannot use the compression scheme used by other, it could discard itself from the federation
* Check compatibility of backends

The configuration could be sent to a worker when it's first instantiated or when it first connects to a socket server or aggregation server

**Comment by mari-linhares** [comment]
@mccorby is this still open (in discussion)?

**Comment by mccorby** [comment]
There has not been much of a discussion about it. I still think it will be necessary if we intend to expand PySyft to other systems but we can reopen this if we need to
Or maybe I can come back with a plan :)
