### ISSUE TITLE
which line is doing the FederatedAverage in tutorial 8 

### ISSUE THREAD

**Issue by XinDongol** [OpenMined/PySyft#2012]
I am following the tutorial 'Part 8 - Federated Learning on MNIST using a CNN.ipynb'.

```Python
def train(args, model, device, federated_train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(federated_train_loader): # <-- now it is a distributed dataset
        model.send(data.location) # <-- NEW: send the model to the right location
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        model.get() # <-- NEW: get the model back
        if batch_idx % args.log_interval == 0:
            loss = loss.get() # <-- NEW: get the loss back
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * args.batch_size, len(federated_train_loader) * args.batch_size,
                100. * batch_idx / len(federated_train_loader), loss.item()))
```

**I am wondering which line is doing the `FederatedAverage`?**

---------------------------------------------
In tutorial 4 'Federated Learning via Trusted Aggregator.ipynb'.
`FederatedAverage` is quite clear.
```Python
iterations = 10
worker_iters = 5
for a_iter in range(iterations):
    bobs_model = model.copy().send(bob)
    alices_model = model.copy().send(alice)
    bobs_opt = optim.SGD(params=bobs_model.parameters(),lr=0.1)
    alices_opt = optim.SGD(params=alices_model.parameters(),lr=0.1)
    for wi in range(worker_iters):
        ...
    
    alices_model.move(secure_worker)
    bobs_model.move(secure_worker)
    
    model.weight.data.set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())
    model.bias.data.set_(((alices_model.bias.data + bobs_model.bias.data) / 2).get())
    
    print("Bob:" + str(bobs_loss) + " Alice:" + str(alices_loss))
```

**Comment by kamathhrishi** [comment]
Hello @XinDongol We aren't doing Federated Averaging with this tutorial. The tutorial was just to demonstrate how we could train an image classifier using federated learning. Sure , you could perform federated averaging if you would like :)

**Comment by XinDongol** [comment]
@kamathhrishi 
Thanks for your reply. 

So if we have two clients.
```Python
bob = sy.VirtualWorker(hook, id="bob")  # <-- NEW: define remote worker bob
alice = sy.VirtualWorker(hook, id="alice")  # <-- NEW: and alice
```
This tutorial is actually training two independent models. One is bob's model on bob's data and the other one is alice's model on alice's data.

**Is it correct?**

**Comment by midokura-silvia** [comment]
@XinDongol 
No, only one model is trained in Tutorial 8, in a completely sequential way. The federated_train_loader will provide in each step a remote batch of data and the model in trained on this batch. 
With the current implementation of the FederatedDataLoader, first all batches of bob are provided then the batches of alice are returned.
In the end it is the same as training the model one epoch on bob's data and then continue to train the model one epoch on alice's data.
So no federated averaging is used in this setting.

**Comment by XinDongol** [comment]
Thanks a lot!
@midokura-silvia @kamathhrishi
