### ISSUE TITLE
Hooking __ eq __

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2030]
I tried to hook the == sign by hooking __ eq __ just like I did with > and __ gt __ but this didn't work, when comparing pointers for example I get "NotImplemented"
So far I fixed the pb by replacing __eq __ by torch.eq but any help on this is welcome!

**Comment by mari-linhares** [comment]
@LaRiffle should we close this issue?

**Comment by LaRiffle** [comment]
I don't remember anything about this issue
