### ISSUE TITLE
Remove checks for binary strings all over the code base

### ISSUE THREAD

**Issue by jlebensold** [OpenMined/PySyft#2034]
We need a consistent way of doing serialization / deserialization that takes into account our serialization strategy (e.g. `msgpack`).

**Comment by mari-linhares** [comment]
I think this was partially covered by serializing/deserializing strings explicitly, is this right @iamtrask ?

**Comment by Ankit-Dhankhar** [comment]
I was looking in issue #2357 and found this one. Can someone please explain about this issue in more detail. 
Thanks

**Comment by karlhigley** [comment]
@Ankit-Dhankhar I think [this try/except that decodes bytes to a string](https://github.com/OpenMined/PySyft/blob/ff080c1aff7ef99f5a0411b97ca1e3ac924b9ae4/syft/workers/base.py#L428-L435) is an example of the sort of check this issue is referring to.
