### ISSUE TITLE
Custom Federated Data Loader Tutorial 

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#2036]
Create a tutorial explaining how the users could create custom Federated Data Loaders to load their data. Ideally an example of image and text dataset. Example of how this was done with text dataset is given in the <a href="https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Advanced/Federated%20Word%20Vectors.ipynb">Federated Word Vectors Tutorial</a> .

**Comment by mari-linhares** [comment]
Is there any major difference in the creation of a federated data loader to a regular pytorch data loader?

**Comment by kamathhrishi** [comment]
@mari-linhares There are some minor differences which is why it helps to have a separate tutorial on it :)
For, instance unlike Torch data loader you can't load text inside the training loop and then convert them to torch tensors, you need to convert them beforehand so that they could be sent to the desired workers and there are some attributes that need to be created such as data and target.

**Comment by mari-linhares** [comment]
Cool, makes sense. Thanks for the great explanation!

**Comment by sina-nabavi** [comment]
This tutorial is not available anymore.
