### ISSUE TITLE
Hook Torch zeros and rand

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#2046]
While they might seem like a minor issue. It is necessary for the end users to have torch.zeros , torch.rand and torch.linspace to  initialize hidden layers or create custom datasets.

**Comment by LaRiffle** [comment]
Can you give an example of what you would like and you error you get at the moment ?

**Comment by kamathhrishi** [comment]
@LaRiffle check this out https://github.com/OpenMined/PySyft/issues/2047#issuecomment-480867982

**Comment by Ankit-Dhankhar** [comment]
@kamathhrishi  I think torch.rand, torch.zeros and torch.linspace are hooked. So, we can close this issue ;)

**Comment by kamathhrishi** [comment]
Oh is it ? I will check once and confirm and then close it :)

**Comment by kamathhrishi** [comment]
Yep They are hooked :)
