### ISSUE TITLE
Custom Neural Network in Federated Learning

### ISSUE THREAD

**Issue by flo257** [OpenMined/PySyft#2049]
Hi,
I've experienced a problem while replacing the simple Neural Network of the "Federated CIFAR 10 Example" with more complex ones - eg. those untrained models in torchvision.models. 

I've replaced `model = Net().to(device)` by 
`import torchvision.models as models; model = models.resnet18()` and left everything else untouched, but at `output = model(data)` I'm always receiving a "RuntimeError: bool value of Tensor with no values is ambiguous". 

It seems that the model tries to make a prediction on an empy tensor - however, the tensor should be there, as it's working with the simple model in the tutorial.

Do you have any suggestions? 
Thank you

**Comment by kamathhrishi** [comment]
@flo257 Thank you for raising this issue, I will have a look at it and get back to you. True, we haven't particularly thought of developing support for pretrained models from torch vision , but in the near future we will ensure the support for it is taken care of :)

**Comment by iamtrask** [comment]
Hi @flo257 - it sounds like there's an issue with the way the model is deserialized. In particular, we have to wrap all of our custom tensor types (wrapped by empty tensors). There's no reason why your operation shouldn't work - but it's hard for me to debug without seeing the code. Can you upload what you've got here? How can I reproduce?

**Comment by flo257** [comment]
Sure - I've used the "Federated CIFAR 10 Example" here on GitHub from `/examples/tutorials/advanced/`and only changed the line `model = Net().to(device)` into `import torchvision.models as models; model = models.resnet18().to(device)` while leaving everything else untouched. 

You can reproduce this by simply changing this line on the tutorial in the jupyter notebook and start the training process.

**Comment by mari-linhares** [comment]
I think this is related to #2175, I'm closing this for now. Feel free to re-open if after #2175 is fixed this is still a problem.
