### ISSUE TITLE
Add Jupyter Notebooks to Unit Tests (Travis)

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2061]
It would be great if we could add the notebooks to Travis so that they are automatically run (at least the notebooks we want to test). This would help us know when changes to the codebase break demos.

**Comment by replomancer** [comment]
I think I even wrote about this on Slack a few months ago. I'd like to get involved in development again. Can I take this one?

**Comment by kamathhrishi** [comment]
I don't t remember what @replomancer wrote , but one way of doing this is to have a bash script run first that find all jupyter notebooks and runs jupyter convert ... The command to convert jupyter notebooks to Python script and run the Python scripts as unit tests.

**Comment by kamathhrishi** [comment]
@replomancer you may go ahead. it's a much required feature right now and it would be great to have your help :)

**Comment by replomancer** [comment]
Allright! I'm on it.

**Comment by mari-linhares** [comment]
@replomancer any updates :)?

**Comment by gmuraru** [comment]
@replomancer are you still working on it?

**Comment by lc0** [comment]
@iamtrask would you mind to assign me to this one. I am back and happy to bring it to reality :)

**Comment by iamtrask** [comment]
I think we're about to merge it https://github.com/OpenMined/PySyft/pull/2755

**Comment by iamtrask** [comment]
But welcome back @lc0 !!! Great to see you!

**Comment by lc0** [comment]
> I think we're about to merge it #2755

This is great. In this case, I would rather allocate my effort reviewing / improving existing one. Thanks for quick reply!

**Comment by karlhigley** [comment]
Added in #2755.
