### ISSUE TITLE
int(10e10 * random.random()) all over syft

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2063]
int(10e10 * random.random()) is used in multiple files to generate Ids, could we create a module to deal with id generation? Or maybe a utility file that could be accessible from every module?

**Comment by iamtrask** [comment]
+1 to this - and in fact we should probably start switching to a much larger hash instead of an int. We will eventually get to a scale where collisions (accidential or malicious) are a bigger deal.

**Comment by LiviaCavalcanti** [comment]
Hey, is this problem free, in the way that I can  work on it?

**Comment by kamathhrishi** [comment]
> Hey, is this problem free, in the way that I can work on it?

Yes , go ahead! It would great to have your help on this :)

**Comment by jcezarms** [comment]
@iamtrask what about something along the lines of `random.SystemRandom().getrandombits(n)`? In this case, `n` would be up to discussion, I'd say 128 fits the purpose. A higher `n` contributes ~an extra bit~ in terms of security on hashing, which I suppose is a priority for PySyft.

**Comment by mari-linhares** [comment]
@LiviaCavalcanti @jcezarms FYI: there is already an id generator entity abstraction at [base.py](https://github.com/OpenMined/PySyft/blob/dev/syft/workers/abstract.py)
