### ISSUE TITLE
Search remote data will cause the data being deleted

### ISSUE THREAD

**Issue by feigaoxyz** [OpenMined/PySyft#2076]
I've experimented on getting PySyft to work with remote worker with its own dataset.
During these, I found out the `search` from local will cause the data deleted on the remote.

Relevant files in [this gist](https://gist.github.com/feigaoxyz/99dffd2f4336417f83f0cf4e1c80d8fd).

To trigger the error, 
1. First run `python remote.py` in one terminal window
2. Then run `python local.py` from another terminal window

You will see the results:

```sh
$ python remote.py
Objects: {94139650912: tensor([-1.,  2.])
	Tags: x
	Shape: torch.Size([2])}
worker <WebsocketServerWorker id:0 #tensors:1> received SEARCH (b'x',)
worker <WebsocketServerWorker id:0 #tensors:1> received OBJ_DEL 94139650912
Objects: {}
```

```sh
$ python local.py
Local objects before search {}
Search result: [(Wrapper)>[PointerTensor | me:68744693343 -> 0:13527568418]]
Local objects after search {}
```

As the first one showed: the remote worker actually received two actions `SEARCH` and `OBJ_DEL` in correspondence with the search command on Line 20 of local.py.

---

This error can also be reproduced by slightly modifying the `test/test_websocket_woker.py` by searching same term twice, see [L57 of updated test](https://gist.github.com/feigaoxyz/99dffd2f4336417f83f0cf4e1c80d8fd#file-test_websocket_woker-py).

**Comment by iamtrask** [comment]
This is usually because a function (in this case search()) is returning pointers with self.garbage_collect_data==True. This means that when the pointers are deleted (garbage collected) that it sends a delete command to the remote machine.

**Comment by iamtrask** [comment]
Have you gotten https://github.com/OpenMined/PySyft/tree/dev/examples/experimental/Federated%20Learning%20Experiment to work on your local setup?

**Comment by feigaoxyz** [comment]
Yes, I can get this example working. 

(A side note, perhaps it would be better to have some detail instructions in files to help others running.)

**Comment by mari-linhares** [comment]
@feigaoxyz can you open a new issue (or issues) pointing to parts of the documentation that are not clear? 

Thank you!

**Comment by feigaoxyz** [comment]
Hi @iamtrask 

Are you able to reproduce this error from your side?
The simplest way is to replicate the search and asserts again after the first round in [this standard test file for websocket worker](https://github.com/OpenMined/PySyft/blob/4251f728bdff186328b7c24603dedf09e3037230/test/workers/test_websocket_worker.py#L51-L55).

**Comment by feigaoxyz** [comment]
Hi @mari-linhares 

Some of my thoughts on the "FL experiment" example as its current state:
1. add a readme to guide user to run the server with either
  - `FLASK_APP=server.py flask run`; or
  - add `app.run()` in `server.py` and run `python server.py`
2. a clean-up on `ipynb`.

I might put a PR when I got some time.

**Comment by racinger** [comment]
Hi everyone,

I have been experiencing the same issue as @feigaoxyz .
So after updated pysyft. It is no longer deleting the tensor as intended.

But now there is an error only when I use a real remote IP as WebsocketServerWorker ( I am using an AWS instance).
```
    913     # TODO: fix comment for this and simplifier
--> 914     obj_id, id_at_location, worker_id, point_to_attr, shape, garbage_collect_data = tensor_tuple
    915 
    916     if isinstance(worker_id, bytes):

ValueError: not enough values to unpack (expected 6, got 5)
```
```
$ python local.py
kwargs_websocket_2 = {"host": "*.*.*.*", "hook": hook, "verbose": True}
hospital_2 = WebsocketClientWorker(id="hospital_2", port=8083, **kwargs_websocket_1)
hospital_2.search('train_features')'''
```
Any suggestions, I would like to help (but I guess I ll star with beginning issue).
Thanks,
