### ISSUE TITLE
Net has no attribute 'share'

### ISSUE THREAD

**Issue by 2fasc** [OpenMined/PySyft#2080]
I faced the same error pointed out in the comment section of your blog post Encrypted Deep Learning Classification with PyTorch & PySyft in my project  https://github.com/2fasc/Distributed_Malaria/blob/master/src/federated_training.py.

AttributeError: 'Simple_CNN' object has no attribute 'share'

https://blog.openmined.org/encrypted-deep-learning-classification-with-pysyft/

**Comment by mari-linhares** [comment]
+1

**Comment by LaRiffle** [comment]
It is defined here: https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/hook.py#L981

Can you share a code sample failing please?

**Comment by 2fasc** [comment]
`import torch
import torch.nn as nn
import torch.nn.functional as F
import syft as sy


class Simple_CNN(nn.Module):
    def __init__(self):
        super(Simple_CNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 20, 3, 3)
        self.conv2 = nn.Conv2d(20, 50, 3, 3)

        self.fc1 = nn.Linear(50, 500)
        self.fc2 = nn.Linear(500, 2)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(x.shape[0], -1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)


def reproduce_error():
    model = Simple_CNN()

    hook = sy.TorchHook(torch)
    client = sy.VirtualWorker(hook, id="client")
    bob = sy.VirtualWorker(hook, id="bob")
    alice = sy.VirtualWorker(hook, id="alice")
    crypto_provider = sy.VirtualWorker(hook, id="crypto_provider")

    model.fix_precision().share(alice, bob, crypto_provider=crypto_provider)


if __name__ == "__main__":
    reproduce_error()`

**Comment by mari-linhares** [comment]
@2fasc just tried this code snippet with the most current version (dev branch) and it seems to run. Can you try again?

**Comment by 2fasc** [comment]
@mari-linhares thank you! It works :+1:  

`pip install https://github.com/OpenMined/PySyft/archive/dev.zip`

**Comment by mari-linhares** [comment]
@2fasc (or @LaRiffle) can you close this issue?
