### ISSUE TITLE
Add Secure layer at socket communication  between Websocket workers

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PySyft#2082]
Communication among remote workers seems to be in plain text (serialized only). This would allow a **man-in-the-middle attack**
I thought about adding a layer of security by adding symmetric encryption between components.

For this, I thought of the following sequence of steps:
1. Add the Diffie-Hellman protocol when opening a socket with a component, to generate a shared key between workers.
2. Use this shared key throughout the process to encrypt communication between workers.

Is it a viable task?

**Comment by mari-linhares** [comment]
Closed by #2087.
