### ISSUE TITLE
Error Creating Tensor of Tensors

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#2083]
You get an error stating TypeError: Not a Sequence when you create a tensor of tensors. This does not occur when test functions are called manually locally but occurs when Travis is run. I am guessing we haven't hooked the function that is used to create a tensor using tensors. 

`torch.tensor([torch.tensor(1),torch.tensor(2),torch.tensor(3)])`

**Comment by Lou1s** [comment]
I get this error too, when creating a tensor of tensors in a custom class. Does anyone have a work around for the moment?

**Comment by kamathhrishi** [comment]
I did this 

`def tensors_to_literals(tensor_list):
    """Converts list of torch tensors to list of integers/floats. Fix for not having the functionality which converts list of tensors to tensors
       Args:
           tensor_list[List]: List of torch tensors
        
       Returns:
           literal_list[List]: List of floats/integers
    """

    literal_list = []

    for tensor in tensor_list:
        literal_list.append(tensor.item())

    return literal_list`

Also try using torch.cat to convert list of tensors into a single tensor.

**Comment by Lou1s** [comment]
Thanks!
