### ISSUE TITLE
Move simplifier and detailer from serde to specific objects

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2110]
How serde [simplifiers](https://github.com/OpenMined/PySyft/blob/dev/syft/serde.py#L1290) and [detailers](https://github.com/OpenMined/PySyft/blob/dev/syft/serde.py#L1340) are related is not very intuitive.

Every time a new simplifier is created the index needs to be updated and the index created needs to match the index of the detail function at the detailers list. Especially because there is `simplifiers` and [forced_full_simplifiers](https://github.com/OpenMined/PySyft/blob/dev/syft/serde.py#L1312) which makes things even less obvious.

 I think that if `detailers` were a dictionary the relation would be more obvious.

**Comment by robert-wagner** [comment]
I think it may be a better idea to move each simplifier and detailer to the file which defines the object. In that case serde would only need to keep the higher level logic and the simplifiers for built in python types making everything easier

**Comment by mari-linhares** [comment]
Agree, I think a detailers dict/list would still be needed right?

**Comment by racinger** [comment]
Hello @mari-linhares,

I am working on this issue.
Thanks,

**Comment by midokura-silvia** [comment]
What was the conclusion of the discussion to move the serde functionality to the classes? It will not work for all cases, but for many it will work and make the maintenance easier.

**Comment by mari-linhares** [comment]
Fixed #2230
