### ISSUE TITLE
Rename WebsocketClientWorker and WebsocketServerWorker

### ISSUE THREAD

**Issue by midokura-silvia** [OpenMined/PySyft#2120]
I would propose to rename the two classes as follows:

WebsocketClientWorker => WebsocketRemoteProxy or WebsocketRemoteInterface or WSRemote...  
WebsocketServerWorker => WebsocketRemoteWorker

"Remote" could also be replaced by the word client, e.g. WebsocketClientProxy and WebsocketClientWorker

The idea is to avoid the words client and server. Currently they are used as given by their roles in the websocket connection. However, when talking about federated learning, we often also talk about client/server but with another meaning. In the federated learning setting, the two classes WebsocketClientWorker and WebsocketServerWorker form together a client that can participate in a training.

**Comment by jacorbachosky** [comment]
I agree with the name of `Proxy`. I thought of using it for the `SocketIO` object too as that's its function in the setup

**Comment by mccorby** [comment]
(I used my other username in the previous comment :) )

**Comment by mari-linhares** [comment]
+1 to Proxy.

**Comment by midokura-silvia** [comment]
Any preference for Remote vs Client?
WebsocketRemoteProxy + WebsocketRemoteWorker
or
WebsocketClientProxy + WebsocketClientWorker

**Comment by mari-linhares** [comment]
No strong opinions, but I would say client is more informative than remote.

**Comment by midokura-silvia** [comment]
Any more opinions out there? 
@robert-wagner wrote:

> Traditionally the client is the one who calls commands. I would prefer if we moved away from the terms client and server regardless as they seem to add confusion. 

As a new option, we could also remove the word client and name the classes:
WebsocketProxy + WebsocketWorker

In my opinion the original naming WebsocketServerWorker and WebsocketClientWorker is confusing, as you think of setting up a federated training where client and server have different meanings.

**Comment by gmuraru** [comment]
@karlhigley should this still be open? (might be a good idea to rename)

**Comment by karlhigley** [comment]
Yeah, I agree they should renamed. I like the suggestion of `WebsocketProxy` and `WebsocketWorker`. Seems clean and clear, and would disambiguate the usages of client/server.
