### ISSUE TITLE
python3 setup.py test  fails with "test_plan_built_on_method Illegal instruction"

### ISSUE THREAD

**Issue by pkc-harry** [OpenMined/PySyft#2130]
I've followed https://github.com/OpenMined/PySyft/blob/dev/INSTALLATION.md and https://pytorch.org/get-started/locally/ to install torch-1.0.1.post2.

The install goes fine, but the test errors out with theses last two lines of output...
.....
test/federated/test_plan.py::test_plan_built_remotely PASSED                                                                                                                                                                           [ 28%]
test/federated/test_plan.py::test_plan_built_on_method Illegal instruction

There are no conflicted packages in my pip3 environment : 
...
torch                    1.0.1.post2  
torchvision           0.2.2.post3
syft                      0.1.14a1 

platform linux -- Python 3.6.7, pytest-4.4.1, py-1.8.0, pluggy-0.11.0 -- /usr/bin/python3

_I'm quite happy to check this out if someone gives me some pointers as to where to look._

**Comment by pkc-harry** [comment]
======================================================================
I've tried a local install and I'm getting ..
ERROR: syft 0.1.14a1 has requirement torch==1.0.1, but you'll have torch 1.0.1.post2 which is incompatible.
torch               1.0.1.post2


Then I did the torchvision install and got...
torch                1.1.0      
torchvision         0.2.2.post3

no syft !

**Comment by mari-linhares** [comment]
@pkc-harry can you install torch 1.0.1 instead of torch 1.0.1.post2 and try it out?

**Comment by pkc-harry** [comment]
Sure.
I cleared out all other installs and tried it with

torch (1.0.1)
torchvision (0.2.2.post3)
syft (0.1.13a1)

same error resulting. [test/federated/test_plan.py::test_plan_built_on_method Illegal instruction]

**Comment by mari-linhares** [comment]
Thanks, I'll try to reproduce it.

**Comment by pkc-harry** [comment]
I've done a near identical build from scratch.

test/workers/test_worker.py::test_get_unknown_worker PASSED                                                                                                     [ 99%]
test/workers/test_worker.py::test_search PASSED                                                                                                                   [100%]
=============================================================== 236 passed, 12 warnings in 59.35 seconds ================================================================
Well it gets me moving, but doesn't identify the original  problem.  On a web search, I've noticed a few  'illegal instruction' errors logged with python modules. 
@mari-linhares : I'll carry on checking this out, but I don't expect a solution soon. Ta !

**Comment by mari-linhares** [comment]
Thanks for trying @pkc-harry!

Probably it was syft version... don't think it was numpy.
