### ISSUE TITLE
Seriealize/Deserialize grad_fn

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2137]
Currently, `grads` is serialized but `grad_fn` is not.

I believe without this change is not possible to send a model and train it remotely.

**Comment by iamtrask** [comment]
With AutogradTensor from @mcleonard , this should be possible.

**Comment by mari-linhares** [comment]
#1902

**Comment by karlhigley** [comment]
Captured again in #2797 and work in progress in #2871.
