### ISSUE TITLE
local_worker.is_client_worker = True and Garbage collection

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2150]
I observed that the `hook.local_worker.is_client_worker = False` in conftest.py had an influence on the reference count of pointers, which increases from 2 to 3. As a consequence, pointers of pointers don't get deleted with garbage collection (GC).

I'm not sure where this additional reference happens, but this is something we want to avoid, as GC is **very** important for FL.

**Comment by mari-linhares** [comment]
Hey @LaRiffle,

the description is not clear to me, is there a problem with conftest.py or is it an issue inside syft?

**Comment by LaRiffle** [comment]
I don't actually know, I suspect pytest does extra stuff which leads to over reference some objects like pointers. It's annoying because then the behaviour differs between test and real world execution
However I'm not sure that the statement  `pointers of pointers don't get deleted with garbage collection (GC)` is still false

I would suggest closing this as we experience normal behaviour in out pointers of pointers GC tests
