### ISSUE TITLE
RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by songchuangyuan** [OpenMined/PySyft#2156]
In the Part 2: Intro to Federated Learning，have a code running error：RuntimeError: set_storage is not allowed on Tensor created from .data or .detach().
![image](https://user-images.githubusercontent.com/46445562/58070014-03456300-7bca-11e9-9830-bdb9edff42f4.png)

**Comment by mari-linhares** [comment]
Hey @songchuangyuan,

I've just executed the notebook using PySyft most current version (dev branch) and it works.

Can you check if you're using an updated version of PySyft and re-run the notebook? Thanks!

**Comment by acyrl** [comment]
In tutorial 4:
I get the same error on the cell:
```
model.weight.data.set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())
model.bias.data.set_(((alices_model.bias.data + bobs_model.bias.data) / 2).get())
```
If I downgrade from `torch 1.1.0` the error goes away.

**Comment by acyrl** [comment]
I did a bit more digging -- see [this](https://discuss.pytorch.org/t/api-change-for-tensor-data-set-in-torch-nightly/33310) discussion. 

Following the solution provided in the link above, If I change: 
`model.weight.data.set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())`
to
```
with torch.no_grad():
    model.weight.data.set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())
```
