### ISSUE TITLE
Hooking process, torch.jit / PySyft compatibility

### ISSUE THREAD

**Issue by midokura-silvia** [OpenMined/PySyft#2161]
I noticed an issue when using torch.jit after hooking torch from PySyft. 
The following code instantiates an instance of Net() twice. Once before hooking and once after. 
Before the hooking it is instantiated without problem, but afterwards I get a NameError. 
Any ideas what in the hooking process could provoke this?

```
import torch
import syft as sy

class Net(torch.jit.ScriptModule):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(2, 3)

model = Net()
hook = sy.TorchHook(torch)
model = Net()
```
                                                                                                                                        
---------------------------------------------------------------------------

> NameError                                 Traceback (most recent call last)
<ipython-input-2-ec1f395a60b2> in <module>
      1 hook = sy.TorchHook(torch)
----> 2 model = Net()

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/__init__.py in init_then_register(self, *args, **kwargs)
    949             if cls is type(self):
    950                 torch._C.ScriptModule.__init__(self)
--> 951             original_init(self, *args, **kwargs)
    952             _create_methods_from_stubs(self, methods)
    953 

><ipython-input-1-922892c7d0f3> in __init__(self)
      5     def __init__(self):
      6         super(Net, self).__init__()
----> 7         self.fc1 = torch.nn.Linear(2, 3)
      8 
      9 model = Net()

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/__init__.py in __setattr__(self, attr, value)
   1106                 if isinstance(value, Module) and _is_weak_type(type(value)):
   1107                     # Compile weak script module
-> 1108                     value = _make_strong(value)
   1109                 if attr == 'training':
   1110                     if self._has_buffer('training'):

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/__init__.py in _make_strong(mod)
   1252 
   1253     # Create proxy with stubs
-> 1254     proxy = WeakScriptModuleProxy(mod, stubs)
   1255 
   1256     _weak_modules[mod] = proxy

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/__init__.py in init_then_register(self, *args, **kwargs)
    949             if cls is type(self):
    950                 torch._C.ScriptModule.__init__(self)
--> 951             original_init(self, *args, **kwargs)
    952             _create_methods_from_stubs(self, methods)
    953 

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/__init__.py in __init__(self, original, stubs)
   1189 
   1190             self.__dict__["_initialized"] = True
-> 1191             _create_methods_from_stubs(self, stubs)
   1192 
   1193         def __getattr__(self, attr):

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/__init__.py in _create_methods_from_stubs(self, stubs)
    911     rcbs = [m.resolution_callback for m in stubs]
    912     defaults = [get_default_args(m.original_method) for m in stubs]
--> 913     self._create_methods(defs, rcbs, defaults)
    914 
    915 # For each user-defined class that subclasses ScriptModule this meta-class,

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/annotations.py in get_signature(fn)
     50         return None
     51 
---> 52     return parse_type_line(type_line)
     53 
     54 

>~/python/envs/openmined/lib/python3.6/site-packages/torch/jit/annotations.py in parse_type_line(type_line)
     88 
     89     try:
---> 90         arg_ann = eval(arg_ann_str, _eval_env)
     91     except SyntaxError:
     92         raise RuntimeError("Failed to parse the argument list of a type annotation")

><string> in <module>

>NameError: name 'Optional' is not defined

**Comment by midokura-silvia** [comment]
For this small example it is sufficient to exclude torch.nn.linear from the hooking process.
in the function syft.frameworks.torch.hook.hook.TorchHook._hook_torch_module :
```
# ignore linear
if func == "linear":
  continue
```
However, we should understand what happens during the hooking process that is incompatible with jit.

**Comment by mari-linhares** [comment]
@midokura-silvia do you have a scenario where we want to use jit.ScriptModule instead of jit.trace?

**Comment by midokura-silvia** [comment]
An instance of a jit.ScriptModule provides you directly with a serializable respresentation. You don't need to provide data to trace the model.

**Comment by midokura-silvia** [comment]
For completeness: In order to create more complex neural networks containing relus etc. even more functions need to be excluded from the hooking. 

In file syft/frameworks/torch/hook/torch_attributes.py, line 33-, uncomment torch and torch.nn.functional.
```
# List modules that we will hook
        self.torch_modules = {
            # "torch": torch,
            "torch.functional": torch.functional,
            # "torch.nn.functional": torch.nn.functional,
        }
```

**Comment by AdnanMunir294** [comment]
I am getting this error please help me thanks " module syft has no attribute 'TorchHook'.
I am creating virtual environment with conda and then install this but again error. Please help me
