### ISSUE TITLE
Error: matmul operation with websocket workers

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PySyft#2168]
I'm trying to run a [simple code snippet](https://hastebin.com/uhafamejey.py) that applies the matmul method on two SMPC tensors.

But I'm having problems when applying spdz multiplication (more precisely when trying to **reconstruct** the delta and epsilon tensors). 
https://github.com/OpenMined/PySyft/blob/734742554358f5fc8ef6942a4aca042746aafc89/syft/frameworks/torch/crypto/spdz.py#L31-L32

When creating a pp tensor by **sending** the SMPC tensor to the **first worker**.
https://github.com/OpenMined/PySyft/blob/734742554358f5fc8ef6942a4aca042746aafc89/syft/frameworks/torch/tensors/interpreters/additive_shared.py#L178

 I get the following warnings on server side:
`
WARNING:root:Worker remote_worker0 couldn't recognize worker (crypto_provider)
` 
`
WARNING:root:Worker me couldn't recognize worker (remote_worker2)
`
`WARNING:root:Worker me couldn't recognize worker (remote_worker3)`
 

After that, when calling the function **remote_get ()** to get the value of pointer stored on previous worker, my websocket servers throw exceptions. 
https://github.com/OpenMined/PySyft/blob/734742554358f5fc8ef6942a4aca042746aafc89/syft/frameworks/torch/tensors/interpreters/additive_shared.py#L179

If it is a bug, I would like to work on it. But I need someone to help me understand the behavior behind the tensors and workers.

**syft version: 0.1.14a1**

**Comment by mari-linhares** [comment]
I'm on it.

**Comment by iamtrask** [comment]
Solving this might be moree of a Grid project than a PySyft one - primarily because it will require two people to be able to connect to the same worker and interact with the same tensors on that worker. This requires things like user roles and permission and managing multiple connections.

**Comment by mari-linhares** [comment]
I agree with @iamtrask, I'll close this issue for now and re-open it at [Grid](https://github.com/OpenMined/Grid/)
