### ISSUE TITLE
Error in Tutorial Part 4 Step 6

### ISSUE THREAD

**Issue by RunshanHu** [OpenMined/PySyft#2179]
Hi, 

I am runing the sample code in the tutorial Part 4 Federated Learning with Model Averaging. The code is in Step 6 Rinse and Repeat  and the error message is as following. Any idea on the reason behind this? thanks!

---------------------------------------------------------------------------
PureTorchTensorFoundError                 Traceback (most recent call last)
~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\tensors\interpreters\native.py in handle_func_command(cls, command)
    195             new_args, new_kwargs, new_type, args_type = syft.frameworks.torch.hook_args.hook_function_args(
--> 196                 cmd, args, kwargs, return_args_type=True
    197             )

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook_args.py in hook_function_args(attr, args, kwargs, return_args_type)
    146         # Try running it
--> 147         new_args = hook_args(args)
    148 

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook_args.py in <lambda>(x)
    340 
--> 341     return lambda x: f(lambdas, x)
    342 

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook_args.py in three_fold(lambdas, args, **kwargs)
    504     return (
--> 505         lambdas[0](args[0], **kwargs),
    506         lambdas[1](args[1], **kwargs),

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook_args.py in <lambda>(i)
    318         # Last if not, rule is probably == 1 so use type to return the right transformation.
--> 319         else lambda i: forward_func[type(i)](i)
    320         for a, r in zip(args, rules)  # And do this for all the args / rules provided

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook_args.py in <lambda>(i)
     53     if hasattr(i, "child")
---> 54     else (_ for _ in ()).throw(PureTorchTensorFoundError),
     55     LoggingTensor: lambda i: i.child,

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook_args.py in <genexpr>(.0)
     53     if hasattr(i, "child")
---> 54     else (_ for _ in ()).throw(PureTorchTensorFoundError),
     55     LoggingTensor: lambda i: i.child,

PureTorchTensorFoundError: 

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-9-3b113eb239f0> in <module>
     14         # Train Bob's Model
     15         bobs_opt.zero_grad()
---> 16         bobs_pred = bobs_model(bobs_data)
     17         bobs_loss = ((bobs_pred - bobs_target)**2).sum()
     18         bobs_loss.backward()

c:\users\rs\documents\projectworkspace\pysyft\.venv\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

c:\users\rs\documents\projectworkspace\pysyft\.venv\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
     90     @weak_script_method
     91     def forward(self, input):
---> 92         return F.linear(input, self.weight, self.bias)
     93 
     94     def extra_repr(self):

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook.py in overloaded_func(*args, **kwargs)
    705             cmd_name = f"{attr.__module__}.{attr.__name__}"
    706             command = (cmd_name, None, args, kwargs)
--> 707             response = TorchTensor.handle_func_command(command)
    708             return response
    709 

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\tensors\interpreters\native.py in handle_func_command(cls, command)
    204             new_command = (cmd, None, new_args, new_kwargs)
    205             # Send it to the appropriate class and get the response
--> 206             response = new_type.handle_func_command(new_command)
    207             # Put back the wrappers where needed
    208             response = syft.frameworks.torch.hook_args.hook_response(

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\tensors\interpreters\pointer.py in handle_func_command(cls, command)
    102 
    103         # Send the command
--> 104         response = owner.send_command(location, command)
    105 
    106         return response

~\Documents\ProjectWorkspace\PySyft\syft\workers\base.py in send_command(self, recipient, message, return_ids)
    416 
    417         try:
--> 418             _ = self.send_msg(MSGTYPE.CMD, message, location=recipient)
    419         except ResponseSignatureError as e:
    420             return_ids = e.ids_generated

~\Documents\ProjectWorkspace\PySyft\syft\workers\base.py in send_msg(self, msg_type, message, location)
    216 
    217         # Step 2: send the message and wait for a response
--> 218         bin_response = self._send_msg(bin_message, location)
    219 
    220         # Step 3: deserialize the response

~\Documents\ProjectWorkspace\PySyft\syft\workers\virtual.py in _send_msg(self, message, location)
      4 class VirtualWorker(BaseWorker):
      5     def _send_msg(self, message: bin, location: BaseWorker) -> bin:
----> 6         return location._recv_msg(message)
      7 
      8     def _recv_msg(self, message: bin) -> bin:

~\Documents\ProjectWorkspace\PySyft\syft\workers\virtual.py in _recv_msg(self, message)
      7 
      8     def _recv_msg(self, message: bin) -> bin:
----> 9         return self.recv_msg(message)

~\Documents\ProjectWorkspace\PySyft\syft\workers\base.py in recv_msg(self, bin_message)
    247             print(f"worker {self} received {sy.codes.code2MSGTYPE[msg_type]} {contents}")
    248         # Step 1: route message to appropriate function
--> 249         response = self._message_router[msg_type](contents)
    250 
    251         # Step 2: Serialize the message to simple python objects

~\Documents\ProjectWorkspace\PySyft\syft\workers\base.py in execute_command(self, message)
    374                 command = getattr(command, path)
    375 
--> 376             response = command(*args, **kwargs)
    377 
    378         # some functions don't return anything (such as .backward())

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook.py in overloaded_func(*args, **kwargs)
    705             cmd_name = f"{attr.__module__}.{attr.__name__}"
    706             command = (cmd_name, None, args, kwargs)
--> 707             response = TorchTensor.handle_func_command(command)
    708             return response
    709 

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\tensors\interpreters\native.py in handle_func_command(cls, command)
    221             # in the execute_command function
    222             if isinstance(args, tuple):
--> 223                 response = eval(cmd)(*args, **kwargs)
    224             else:
    225                 response = eval(cmd)(args, **kwargs)

c:\users\rs\documents\projectworkspace\pysyft\.venv\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
   1404     if input.dim() == 2 and bias is not None:
   1405         # fused op is marginally faster
-> 1406         ret = torch.addmm(bias, input, weight.t())
   1407     else:
   1408         output = input.matmul(weight.t())

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\hook\hook.py in overloaded_func(*args, **kwargs)
    705             cmd_name = f"{attr.__module__}.{attr.__name__}"
    706             command = (cmd_name, None, args, kwargs)
--> 707             response = TorchTensor.handle_func_command(command)
    708             return response
    709 

~\Documents\ProjectWorkspace\PySyft\syft\frameworks\torch\tensors\interpreters\native.py in handle_func_command(cls, command)
    221             # in the execute_command function
    222             if isinstance(args, tuple):
--> 223                 response = eval(cmd)(*args, **kwargs)
    224             else:
    225                 response = eval(cmd)(args, **kwargs)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by mari-linhares** [comment]
Hey @RunshanHu ,

I've just executed it with pysyft most updated version (dev branch) and pytorch 1.1 and 1.0.1 with no errors.

Can you check if you have all the correct/updated dependencies installed?

Feel free to ping me on slack if you continue to have problems, closing it for now since it doesn't seem to have a problem.
