### ISSUE TITLE
Unable to run unit tests.

### ISSUE THREAD

**Issue by jidroid404** [OpenMined/PySyft#2198]
Unable to run unit tests even after installing everything properly ( tried both pip install and the installation guide for Linux )
* Installation is proper
![Screenshot from 2019-05-31 06-38-28](https://user-images.githubusercontent.com/43285614/58674758-de41b480-836e-11e9-86c8-1c7620649978.png) 

*Breaks after cd-ing into test dir
![Screenshot from 2019-05-31 06-39-17](https://user-images.githubusercontent.com/43285614/58674760-deda4b00-836e-11e9-8852-084b7d36d3cc.png)
What am I missing?

**Comment by amit-rastogi** [comment]
@jidroid404  Inside test folder you can run tests using pytest e.g pytest test_serde.py

**Comment by mari-linhares** [comment]
@jidroid404  as @amit-rastogi pointed you should run the file using pytest. Also if you want to run all the unit tests you can cd to the PySyft folder and run: `pytest test/*`

**Comment by jidroid404** [comment]
Then throwing off this import error, while running all of the unit tests
![Screenshot from 2019-06-02 18-16-19](https://user-images.githubusercontent.com/43285614/58761590-b6677200-8563-11e9-8ea3-7b4d86c01684.png)

**Comment by mari-linhares** [comment]
@jidroid404 try to run as I described on my previous comment. conftest.py is not a valid unit test, so probably that's why you see the error.

Go to Desktop/PysSyft/ and run pytest test/*

This should execute without errors.

**Comment by jidroid404** [comment]
Nope,it doesn't.
![issue](https://user-images.githubusercontent.com/43285614/58761906-c92f7600-8566-11e9-960d-e1c9a5534ff6.png)

**Comment by mari-linhares** [comment]
right... weird...  can you check if you have all the dependencies installed?

run:

```
pip install -r requirements.txt
pip install -r requirements_dev.txt
```

**Comment by jidroid404** [comment]
All the dependencies are intact.

**Comment by amit-rastogi** [comment]
From the error details your python version appears to be 2.7. Could you check with python 3.x?

**Comment by jidroid404** [comment]
Had the same suspicion, it's Python 3.6 only.

**Comment by mari-linhares** [comment]
Oh indeed @amit-rastogi, nice catch!

**Comment by mari-linhares** [comment]
Not really @jidroid404 from the previous print-screen error you sent your pytest is running python2.7

**Comment by jidroid404** [comment]
![ss](https://user-images.githubusercontent.com/43285614/58762094-a2bf0a00-8569-11e9-966c-9e66e0e5310e.png)

**Comment by jidroid404** [comment]
Okay lesson learned. :) Thanks peeps.
python3 -m pytest test/test_serde.py
