### ISSUE TITLE
Separate Folders/Sections for tutorials

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#2200]
With growing features and possibilities in PySyft, it's best we have separate folders/sections for tutorials such as Homomorphic Encryption (when pailier tensor is merged), Differential Privacy, Federated Learning, MPC, etc.

**Comment by gmuraru** [comment]
@karlhigley this is already done, right?

**Comment by karlhigley** [comment]
We have the `advanced` directory which has a bunch of tutorials in separate folders, but I don't think they're organized by topic yet.
