### ISSUE TITLE
Test share for keras does not work on macos in a virtual env

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2211]
**Describe the bug**
Due to firewall issues, it is not possible to run test share on macos in a venv. This can be remedied by replacing network calls with mock.
**To Reproduce**
run make_test on a fresh macos install

**Additional context**
contact @robert-wagner to replicate as it is still broken on his system

**Comment by mortendahl** [comment]
Mind taking a look at the linked PR @robert-wagner?
