### ISSUE TITLE
Debug messages not visible with socketworkers

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2212]
**Describe the bug**
The debug messages are not visible on FL examples with socketworkers

**To Reproduce**
Run https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/advanced/websockets-example-MNIST/Federated%20learning%20with%20websockets%20and%20federated%20averaging.ipynb

**Expected behavior**
You should see the debug message, I don't

**Desktop (please complete the following information):**
 - OS: macOS Mojave

**Comment by DanyEle** [comment]
I agree. Debug messages just appear at the server and not on the workers themselves when using websockets. It would nice to have them also on the workers.

Replicated on:

**Desktop:**
OS: Ubuntu 18.04 LTS, Raspbian 4.14
