### ISSUE TITLE
Exception forwarding across workers

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2214]
**Is your feature request related to a problem? Please describe.**
When a remote workers fails, the client doesn't has access directly to the error (and traceback). In particular, the error needs to be caught for response of operations with several pointers where a ResponseSignatureError is raised by a worker and caught by another

**Describe the solution you'd like**
I'd like remote socket workers to catch all (or some high-level) errors and serialize them so that the client can get and catch them, or error with a full message

**Describe alternatives you've considered**
we can use `pip install tblib`
example: 
```
import tblib.pickling_support
tblib.pickling_support.install()
import pickle, sys 

def inner_0():
    raise Exception('fail')

def inner_1():
    inner_0()

def inner_2():
    inner_1()

try:
    inner_2()
except:
    s1 = pickle.dumps(sys.exc_info())

# deserialize and raise again error
from six import reraise
reraise(*pickle.loads(s1))
```

**Comment by robert-wagner** [comment]
@LaRiffle Is this done?

**Comment by LaRiffle** [comment]
Yes!
