### ISSUE TITLE
Could not find a version that satisfies the requirement torch>=1.0.1 (from syft) (from versions: 0.1.2, 0.1.2.p

### ISSUE THREAD

**Issue by hr21** [OpenMined/PySyft#2221]
I am using a windows machine, with anaconda navigator I installed as per the instructions given in the readme.md 
1. created an enviornment named pysyft and activated it
2. initialized pip install syft
3. The error mentioned above is displayed

I am  Udacity Student for Secure and Private AI

![image](https://user-images.githubusercontent.com/39687652/58757245-8e0d5280-8526-11e9-962f-7d231cec825e.png)

**Comment by kamathhrishi** [comment]
Looks you haven't installed the appropriate version of torch or don't have torch installed in your conda environment. So activate your conda environment and install pytorch. Conda environments are a good way to keep separate dependencies. So if you have had a different version of torch in your system which you usually use. You can use a specific version of torch separate using virtual environments such as conda.

**Comment by amit-rastogi** [comment]
Did you execute the following command in your pysyft environment? If not, then please run this command and check.

conda install pytorch torchvision -c pytorch

**Comment by iamtrask** [comment]
You should update conda and pip. If it doesn't have torch 1.x it's likely very old.

**Comment by hr21** [comment]
I have already tried all the mentioned commands I even tried using it within the enviornment in which I had pytorch Installed and I got back the same error my current conda version is 4.5x and the torch version is 1.x @iamtrask

**Comment by colin-byrneireland** [comment]
I've the exact same issue seems to me that torch 1.2 (latest) isn't compatible with syft ?.
Any suggestions
