### ISSUE TITLE
Raise Error When We Call .item() on a PointerTensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2227]
**Is your feature request related to a problem? Please describe.**
.item() returns a plain python object (like an int or float), but we don't have the ability to point to a remote python object in this way. 

**Describe the solution you'd like**
We should raise an error when .item() is called on a PointerTensor, with an informative message describing how the user should call .get() in order to call .item() safely.

**Describe alternatives you've considered**
We could also have a pointer to python objects - but this seems like more work than is necessary and could open up it's own issues.

**Comment by abmazhr** [comment]
@iamtrask so basically any instance of "syft.frameworks.torch.pointers.PointerTensor" which have a call to ".item" function should be raising an error with a message as described above? or there is something I misunderstood? :smile: , if it's right so it's as easy as implementing a ".item" function inside "syft.frameworks.torch.pointers.PointerTensor" and raising the error there. I'm willing to make a quick PR if that's fine, Thank you :smile:

**Comment by abmazhr** [comment]
I guess we could close this issue since it got fixed and merged already in dev? #2239 :smile:

**Comment by mari-linhares** [comment]
Fixed #2239
