### ISSUE TITLE
Add support for operations on pointer tensors and multipointer tensors

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2233]
**Describe the solution you'd like**
Operations on pointer tensors and multipointer tensors should return a pointer tensor if the pointer tensor points to one of the workers that the multipointer tensor pointer points to. Currently this throws an error

**Comment by amit-rastogi** [comment]
@robert-wagner can i take this up?

**Comment by amit-rastogi** [comment]
I replicated this using the code below-

hook = sy.TorchHook(torch)
x = torch.tensor([1.,2])
y = torch.tensor([2,3.])
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
x_ptr = x.send(bob, alice)
y_ptr = y.send(bob)
z = x_ptr+y_ptr        #####Got syft.exceptions.RemoteObjectFoundError here

**Comment by gmuraru** [comment]
Tested the code from @amit-rastogi and the error still exists. @robert-wagner are you looking into the issue?

**Comment by LaRiffle** [comment]
I don't think so! beware this might be a tricky issue to solve :)
