### ISSUE TITLE
AttributeError: 'FixedPrecisionTensor' object has no attribute 'attr'

### ISSUE THREAD

**Issue by AndyClouder** [OpenMined/PySyft#2234]
**Describe the bug**

When I run the demo of Part 11 - Secure Deep Learning Classification from the example.
In cell [12]  `model.fix_precision().share(alice, bob, crypto_provider=crypto_provider)`
I met an error as below:

![ERROR](https://user-images.githubusercontent.com/16660974/58936093-86a5ad80-87a1-11e9-85fe-f0d134bfd777.PNG)

Is that a bug ?

My env details:
python 3.6.8
pytorch 1.0.1
syft 1.12.a1
os WIN10

**Comment by iamtrask** [comment]
Let's start by updating PySyft. The latest version is 0.1.17.a1 which is 5 versions after the one you have.

**Comment by robert-wagner** [comment]
@AndyClouder did updating PySyft fix your issue?

**Comment by keenlykeenly** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-7-5b486064ddb2> in <module>()
----> 1 model.share(alice, bob, carol)

D:\ProgramData\Anaconda3\lib\site-packages\syft-0.1.15a1-py3.6.egg\syft\frameworks\keras\model\sequential.py in share(model, target_graph, *workers)
     38 
     39     with target_graph.as_default():
---> 40         tfe_model, batch_input_shape = _rebuild_tfe_model(model, stored_keras_weights)
     41 
     42         # Set up a new tfe.serving.QueueServer for the shared TFE model

D:\ProgramData\Anaconda3\lib\site-packages\syft-0.1.15a1-py3.6.egg\syft\frameworks\keras\model\sequential.py in _rebuild_tfe_model(keras_model, stored_keras_weights)
    112     """
    113 
--> 114     tfe_model = tfe.keras.Sequential()
    115 
    116     for keras_layer in keras_model.layers:

D:\ProgramData\Anaconda3\lib\site-packages\tf_encrypted-0.5.4-py3.6.egg\tf_encrypted\keras\engine\sequential.py in __init__(self, layers, name)
     10   """
     11   def __init__(self, layers=None, name=None):
---> 12     super(Sequential, self).__init__(name=name)
     13 
     14     self._layers = []

D:\ProgramData\Anaconda3\lib\site-packages\tf_encrypted-0.5.4-py3.6.egg\tf_encrypted\keras\engine\base_layer.py in __init__(self, trainable, name, **kwargs)
     51 
     52     self.trainable = trainable
---> 53     self._init_set_name(name)
     54     self.built = False
     55 

D:\ProgramData\Anaconda3\lib\site-packages\tf_encrypted-0.5.4-py3.6.egg\tf_encrypted\keras\engine\base_layer.py in _init_set_name(self, name, zero_based)
    108   def _init_set_name(self, name, zero_based=True):
    109     if not name:
--> 110       self._name = base_layer_utils.unique_layer_name(
    111           generic_utils.to_snake_case(self.__class__.__name__),
    112           zero_based=zero_based)

AttributeError: module 'tensorflow.python.keras.engine.base_layer_utils' has no attribute 'unique_layer_name'

How can I solve this problem? Thanks.

**Comment by LaRiffle** [comment]
Hi, this error is now related to #2255 
I will therefore close this one, and add you in the other one.
