### ISSUE TITLE
Federated Learning on always available data

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2240]
We want to be able to perform federated learning on data which is always available. In practice this means we need to be able to

- Aggregate workers into a dataset to load pointer to data
- Send models to a set of workers
- Perform federated averaging automatically across optimizers

This epic will continue to be updated as progress is made.

**Comment by midokura-silvia** [comment]
What do you mean by constant uptime?

**Comment by DanyEle** [comment]
> What do you mean by constant uptime?

I believe it means at a regular time interval, like every X minutes?

**Comment by robert-wagner** [comment]
Hey @midokura-silvia @DanyEle I will fix the phrasing of this. What I mean by constant uptime is that they data is always available. This is contrasted with data that goes in and out of availability
