### ISSUE TITLE
Support more basic operations for AdditiveSharedTensor

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2245]
This is part of #2235 

**Describe the solution you'd like**
Support for torch.sum and torch.mean on AdditiveSharedTensor

Also related is the #2246 optimization

**Comment by Jasopaum** [comment]
I can do this!

**Comment by Jasopaum** [comment]
My PR is here #2248
I am not really sure about what it means to compute a mean for int, I did a sum and an int div

**Comment by LaRiffle** [comment]
Thanks! I just reviewed
