### ISSUE TITLE
Faster torch.max for AdditiveSharedTensors

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2246]
Our implementation can be made faster using this idea: max(x, y) = y + sgn(x − y) · (x − y).
While we currently do beta =(x > y) ;  max(x, y) = beta * x + (1-beta) * y 
Which requires 2 multiplications

See current implementation in additive_shared.py

**Comment by Jasopaum** [comment]
Is #2249 what you meant?

**Comment by LaRiffle** [comment]
Perfect!
