### ISSUE TITLE
Part 6 and Part 11 Tutorial - List index out of range

### ISSUE THREAD

**Issue by DanyEle** [OpenMined/PySyft#2260]
**Describe the bug**
Part 11 Tutorial breaks when running cell n. 5
See also related issue #2243 
**Edit** Error for torchvision >0.2.2

**To Reproduce**
1. Launch the Jupyter Notebook containing Part 11 - Secure Deep Learning tutorial
2. Run all cells up to the following one:

```
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=args.test_batch_size, shuffle=True)

private_test_loader = []
for data, target in test_loader:
    private_test_loader.append((
        data.fix_precision().share(alice, bob, crypto_provider=crypto_provider),
        target.fix_precision().share(alice, bob, crypto_provider=crypto_provider)
    ))
```

3. Run that cell
4. See the error generated:

https://pastebin.com/cYfEMJ2H

**Expected behavior**
That the cell does indeed run
**Screenshots**
![image](https://user-images.githubusercontent.com/4907418/59180043-27aab480-8b64-11e9-957b-f0a0a79bae17.png)
![image](https://user-images.githubusercontent.com/4907418/59180067-3beeb180-8b64-11e9-83a3-bcfb50586b4c.png)

**Desktop (please complete the following information):**
Ubuntu 18.04 LTS
PySyft 0.1.17

**Comment by Polarbeargo** [comment]
@DanyEle you can see the discussion here:
https://openmined.slack.com/archives/C6EEFN3A8/p1559737323042400?thread_ts=1559737323.042400
relate to [issue 1893](https://github.com/OpenMined/PySyft/issues/1893) I encounter the same problem as you do :).

**Comment by DanyEle** [comment]
> Hello @DanyEle,
> you can see the discussion here:
> https://openmined.slack.com/archives/C6EEFN3A8/p1559737323042400?thread_ts=1559737323.042400
> relate to [issue 1893](https://github.com/OpenMined/PySyft/issues/1893) here.
> I encounter the same problem as you do :).

I confirm that issue also happens to me in Tutorial Part 6.

**Comment by DanyEle** [comment]
This code seems to be fix Tutorial 6.

```
train = datasets.MNIST('data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))

train_base = sy.BaseDataset(data=train.data, targets=train.targets)
train_base_federated = train_base.federate((bob, alice))
federated_train_loader = sy.FederatedDataLoader(train_base_federated, 
                                                batch_size=args.batch_size, 
                                                shuffle=True,
                                                **kwargs)
```

**Comment by jtagliaf** [comment]
And i was wondering if i am just to dump to get everything right... got the same Problem on any Tutorial which uses the MNIST Dataset.

**Comment by LaRiffle** [comment]
Hey, can you confirm you don't have a gpu or cuda?

**Comment by Polarbeargo** [comment]
I use Google Colab.

**Comment by LaRiffle** [comment]
Indeed I experience the same on colab. I'm looking at it

**Comment by DanyEle** [comment]
> Hey, can you confirm you don't have a gpu or cuda?

I have a GPU and CUDA installed, but even when disabling CUDA, this still happens.

**Comment by jtagliaf** [comment]
> Hey, can you confirm you don't have a gpu or cuda?
I do not have an external GPU

Specs:
Memory: 15,4 GiB
Processor: Intel Core i7-7500U CPU @ 2.70GHz x 4
Graphics: Intel HD Graphics 620 (Kaby Lake GT2)
OS: Ubuntu 18.10 64 Bit

Completly fresh installation with Anaconda and pip.

**Comment by LaRiffle** [comment]
The error is related to the torchvision `0.3.0` version.
Will edit a fix for it
