### ISSUE TITLE
AttributeError: 'Conv2D' object has no attribute '_batch_input_shape'

### ISSUE THREAD

**Issue by keenlykeenly** [OpenMined/PySyft#2265]
**Describe the bug**
AttributeError: 'Conv2D' object has no attribute '_batch_input_shape'

**To Reproduce**
In Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving, I encounter the next problem when execeute "model.share(alice, bob, carol)":

**Screenshots**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-5b486064ddb2> in <module>
----> 1 model.share(alice, bob, carol)

D:\ProgramData\Anaconda3\lib\site-packages\syft-0.1.15a1-py3.6.egg\syft\frameworks\keras\model\sequential.py in share(model, target_graph, *workers)
     38 
     39     with target_graph.as_default():
---> 40         tfe_model, batch_input_shape = _rebuild_tfe_model(model, stored_keras_weights)
     41 
     42         # Set up a new tfe.serving.QueueServer for the shared TFE model

D:\ProgramData\Anaconda3\lib\site-packages\syft-0.1.15a1-py3.6.egg\syft\frameworks\keras\model\sequential.py in _rebuild_tfe_model(keras_model, stored_keras_weights)
    116     for keras_layer in keras_model.layers:
    117         tfe_layer = _instantiate_tfe_layer(keras_layer, stored_keras_weights)
--> 118         tfe_model.add(tfe_layer)
    119 
    120         if hasattr(tfe_layer, "_batch_input_shape"):

d:\programdata\anaconda3\tf-encrypted\tf_encrypted\keras\models\sequential.py in add(self, layer)
     42                          "tfe.keras.Sequential model.")
     43 
---> 44       batch_shape = layer._batch_input_shape  # pylint: disable=protected-access
     45 
     46       # Instantiate an input layer.

AttributeError: 'Conv2D' object has no attribute '_batch_input_shape'

**Desktop (please complete the following information):**
 - OS: [Windows 7 64 bits]
In anaconda3, python 3.6.4
 - Version [In anaconda3, python 3.6.4]

**Additional context**
I have updated the tf-encrypted to version 0.5.5 from source and reinstalled pysyft from pip.

**Comment by jvmancuso** [comment]
Hi @keenlykeenly, unfortunately I was unable to reproduce your bug with the information provided -- when I try the notebook it works smoothly on both the pip package and the dev branch.  Did you change any code in the notebook?

It looks like your version of PySyft is slightly out of date though, you're using syft-0.1.15a1, while the current version from pip should be syft-0.1.17.  I recommend reinstalling with `pip install -U syft` in your environment and retrying this notebook.  Hope that helps!

**Comment by keenlykeenly** [comment]
I update the syft as you suggest using pip install -U syft==0.1.17. 
And the version information is as follows .

Requirement already up-to-date: syft==0.1.17 in d:\programdata\anaconda3\lib\site-packages (0.1.17)
Requirement already satisfied, skipping upgrade: torchvision in d:\programdata\anaconda3\lib\site-packages (from syft==0.1.17) (0.2.2)
Requirement already satisfied, skipping upgrade: sklearn in d:\programdata\anaconda3\lib\site-packages\sklearn-0.0-py3.6.egg (from syft==0.1.17) (0.0)
Requirement already satisfied, skipping upgrade: zstd in d:\programdata\anaconda3\lib\site-packages\zstd-1.4.0.0-py3.6-win-amd64.egg (from syft==0.1.17) (1.4.0.0)
Requirement already satisfied, skipping upgrade: lz4 in d:\programdata\anaconda3\lib\site-packages\lz4-2.1.6-py3.6-win-amd64.egg (from syft==0.1.17) (2.1.6)
Requirement already satisfied, skipping upgrade: tf-encrypted>=0.5.4 in d:\programdata\anaconda3\tf-encrypted (from syft==0.1.17) (0.5.5)
Requirement already satisfied, skipping upgrade: websockets>=7.0 in d:\programdata\anaconda3\lib\site-packages\websockets-7.0-py3.6-win-amd64.egg (from syft==0.1.17) (7.0)
Requirement already satisfied, skipping upgrade: torch>=1.0.1 in d:\programdata\anaconda3\lib\site-packages (from syft==0.1.17) (1.0.1)
Requirement already satisfied, skipping upgrade: flask-socketio in d:\programdata\anaconda3\lib\site-packages\flask_socketio-4.0.0-py3.6.egg (from syft==0.1.17) (4.0.0)
Requirement already satisfied, skipping upgrade: tblib in d:\programdata\anaconda3\lib\site-packages (from syft==0.1.17) (1.4.0)
Requirement already satisfied, skipping upgrade: msgpack in d:\programdata\anaconda3\lib\site-packages (from syft==0.1.17) (0.6.1)
Requirement already satisfied, skipping upgrade: websocket-client in d:\programdata\anaconda3\lib\site-packages\websocket_client-0.56.0-py3.6.egg (from syft==0.1.17) (0.56.0)
Requirement already satisfied, skipping upgrade: Flask in d:\programdata\anaconda3\lib\site-packages (from syft==0.1.17) (1.0.3)
Requirement already satisfied, skipping upgrade: numpy in d:\programdata\anaconda3\lib\site-packages (from torchvision->syft==0.1.17) (1.16.4)
Requirement already satisfied, skipping upgrade: six in c:\users\administrator\appdata\roaming\python\python36\site-packages (from torchvision->syft==0.1.17) (1.11.0)
Requirement already satisfied, skipping upgrade: pillow>=4.1.1 in d:\programdata\anaconda3\lib\site-packages (from torchvision->syft==0.1.17) (6.0.0)
Requirement already satisfied, skipping upgrade: scikit-learn in d:\programdata\anaconda3\lib\site-packages (from sklearn->syft==0.1.17) (0.19.1)
Requirement already satisfied, skipping upgrade: tensorflow<2,>=1.12.0 in d:\programdata\anaconda3\lib\site-packages\tensorflow-1.14.0rc0-py3.6-win-amd64.egg (from tf-encrypted>=0.5.4->syft==0.1.17) (1.14.0rc0)
Requirement already satisfied, skipping upgrade: pyyaml>=5.1 in d:\programdata\anaconda3\lib\site-packages (from tf-encrypted>=0.5.4->syft==0.1.17) (5.1)
Requirement already satisfied, skipping upgrade: python-socketio>=2.1.0 in d:\programdata\anaconda3\lib\site-packages\python_socketio-4.0.3-py3.6.egg (from flask-socketio->syft==0.1.17) (4.0.3)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in d:\programdata\anaconda3\lib\site-packages (from Flask->syft==0.1.17) (1.1.0)
Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in d:\programdata\anaconda3\lib\site-packages (from Flask->syft==0.1.17) (0.15.4)
Requirement already satisfied, skipping upgrade: click>=5.1 in d:\programdata\anaconda3\lib\site-packages (from Flask->syft==0.1.17) (7.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10 in d:\programdata\anaconda3\lib\site-packages (from Flask->syft==0.1.17) (2.10.1)
Requirement already satisfied, skipping upgrade: absl-py>=0.7.0 in d:\programdata\anaconda3\lib\site-packages\absl_py-0.7.1-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (0.7.1)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in d:\programdata\anaconda3\lib\site-packages\astor-0.8.0-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (0.8.0)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in d:\programdata\anaconda3\lib\site-packages\gast-0.2.2-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (0.2.2)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.6 in d:\programdata\anaconda3\lib\site-packages\google_pasta-0.1.7-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (0.1.7)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in d:\programdata\anaconda3\lib\site-packages\grpcio-1.21.1-py3.6-win-amd64.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.21.1)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in d:\programdata\anaconda3\lib\site-packages\keras_applications-1.0.8-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.0.8)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in d:\programdata\anaconda3\lib\site-packages\keras_preprocessing-1.0.9-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.0.9)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.1 in d:\programdata\anaconda3\lib\site-packages\protobuf-3.8.0-py3.6-win-amd64.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (3.8.0)
Requirement already satisfied, skipping upgrade: tensorboard<1.14.0,>=1.13.0 in d:\programdata\anaconda3\lib\site-packages\tensorboard-1.13.1-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.13.1)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in d:\programdata\anaconda3\lib\site-packages\termcolor-1.1.0-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.1.0)
Requirement already satisfied, skipping upgrade: tf-estimator-nightly<1.14.0.dev2019042302,>=1.14.0.dev2019042301 in d:\programdata\anaconda3\lib\site-packages\tf_estimator_nightly-1.14.0.dev2019042301-py3.6.egg (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.14.0.dev2019042301)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in d:\programdata\anaconda3\lib\site-packages (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (0.33.4)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in d:\programdata\anaconda3\lib\site-packages (from tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (1.11.1)
Requirement already satisfied, skipping upgrade: python-engineio>=3.2.0 in d:\programdata\anaconda3\lib\site-packages\python_engineio-3.7.0-py3.6.egg (from python-socketio>=2.1.0->flask-socketio->syft==0.1.17) (3.7.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in d:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.10->Flask->syft==0.1.17) (1.1.1)
Requirement already satisfied, skipping upgrade: h5py in d:\programdata\anaconda3\lib\site-packages (from keras-applications>=1.0.6->tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (2.9.0)
Requirement already satisfied, skipping upgrade: setuptools in d:\programdata\anaconda3\lib\site-packages (from protobuf>=3.6.1->tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (41.0.1)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in d:\programdata\anaconda3\lib\site-packages\markdown-3.1.1-py3.6.egg (from tensorboard<1.14.0,>=1.13.0->tensorflow<2,>=1.12.0->tf-encrypted>=0.5.4->syft==0.1.17) (3.1.1)


But I still get the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-8-5b486064ddb2> in <module>
----> 1 model.share(alice, bob, carol)

D:\ProgramData\Anaconda3\lib\site-packages\syft\frameworks\keras\model\sequential.py in share(model, target_graph, *workers)
     38 
     39     with target_graph.as_default():
---> 40         tfe_model, batch_input_shape = _rebuild_tfe_model(model, stored_keras_weights)
     41 
     42         # Set up a new tfe.serving.QueueServer for the shared TFE model

D:\ProgramData\Anaconda3\lib\site-packages\syft\frameworks\keras\model\sequential.py in _rebuild_tfe_model(keras_model, stored_keras_weights)
    115     for keras_layer in keras_model.layers:
    116         tfe_layer = _instantiate_tfe_layer(keras_layer, stored_keras_weights)
--> 117         tfe_model.add(tfe_layer)
    118 
    119         if hasattr(tfe_layer, "_batch_input_shape"):

d:\programdata\anaconda3\tf-encrypted\tf_encrypted\keras\models\sequential.py in add(self, layer)
     42                          "tfe.keras.Sequential model.")
     43 
---> 44       batch_shape = layer._batch_input_shape  # pylint: disable=protected-access
     45 
     46       # Instantiate an input layer.

AttributeError: 'Conv2D' object has no attribute '_batch_input_shape'

The only change I made is: 
config_filename = "/tmp/tfe.config"
 in C:\Users\Administrator\Desktop\covert security\codes\PySyft-dev\PySyft-dev\syft\workers\tfe.py 
to 
config_filename = "D:\ProgramData\Anaconda3\lib\site-packages\syft\workers\tfe.config",
because in the windows OS the directory /tmp does not exist.

I am sorry to confuse you, maybe there are some version probloms in my notebook environment. I will check it carefully. And thank you very much for your help.

**Comment by keenlykeenly** [comment]
Hi. I download the Pysyft you released yesterday from github and that error disappear!
But it seems abnormal:
![image](https://user-images.githubusercontent.com/11493656/59321150-7cd0fc80-8d03-11e9-95c8-809b86cf8b11.png)

![notebook](https://user-images.githubusercontent.com/11493656/59321100-50b57b80-8d03-11e9-822f-1789241c0db8.PNG)
