### ISSUE TITLE
Automatically have every fixed precision operation call wrap to field

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2271]
**Describe the solution you'd like**
Currently for every method in fixed precision tensor we need to call response%=self.field at the end of the call to ensure that the output is in within the size of the field

We should automatically make this call

**Comment by Yugandhartripathi** [comment]
Once #2982 is merged. These explicit modulo calls are removed and wrapping of values in field size(moving forward we will only support 32 bit or 64bit) will be handled using native torch tensors with dtype torch.int32 and torch.int64 respectively.
