### ISSUE TITLE
AttributeError: 'int' object has no attribute 'is_wrapper'

### ISSUE THREAD

**Issue by Polarbeargo** [OpenMined/PySyft#2273]
**Describe the bug**
Execute Part 11 - Secure Deep Learning Classification.ipynb ecounter "AttributeError: 'int' object has no attribute 'is_wrapper'"

**To Reproduce**
1. Go to 'examples/tutorials/Part 11 - Secure Deep Learning Classification.ipynb'
2. Click on 'run all'
3. Scroll down to 'cell 17 test(args, model, private_test_loader)'

**Expected behavior**
No error here:).
**Screenshots**
![1](https://user-images.githubusercontent.com/8589224/59334626-7fe0e280-8d2d-11e9-9c9b-e556e3c1d099.png)
**Desktop (please complete the following information):**
 On Google colaboratory

**Comment by LaRiffle** [comment]
Hey, indeed there is a bug in our last release 0.1.18 when operating with constant values, I'm working on a fix right now.

**Comment by Polarbeargo** [comment]
@LaRiffle Thank you:)!

**Comment by LaRiffle** [comment]
#2274 should solve
It will be merged very soon so if you can build the code from source in your colab you should benefit from it quickly, otherwise the 1.19 release will arrive in a few days. :)

**Comment by Polarbeargo** [comment]
Thank you @LaRiffle!

**Comment by LaRiffle** [comment]
For information, this is my config to build and run the latest code from PySyft on Colab:
```
!pip install tf-encrypted

! URL="https://github.com/openmined/PySyft.git" && FOLDER="PySyft" && if [ ! -d $FOLDER ]; then git clone -b dev --single-branch $URL; else (cd $FOLDER && git pull $URL && cd ..); fi;

!cd PySyft; python setup.py install  > /dev/null

import os
import sys
module_path = os.path.abspath(os.path.join('./PySyft'))
if module_path not in sys.path:
    sys.path.append(module_path)

!pip install --upgrade --force-reinstall lz4
!pip install --upgrade --force-reinstall websocket
!pip install --upgrade --force-reinstall websockets
!pip install --upgrade --force-reinstall zstd
```

I'm sure this is sub optimal, but it works ;)
