### ISSUE TITLE
3 Tests fail when local worker is verbose

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2279]
**Describe the bug**
When hook.local_worker is set to verbose the following errors occur

```
FAILED test/torch/test_hook.py::test_RNN_grad_set_backpropagation - RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 57 and 128 in dimension 1 at ../aten/src/TH/generic/THTensor.cpp:711
FAILED test/torch/tensors/test_additive_shared.py::test_max - RuntimeError: Error, Please consider calling ".get" method instead of ".item" method, so you can be safely getting the item you need.
FAILED test/torch/tensors/test_additive_shared.py::test_argmax - RuntimeError: Error, Please consider calling ".get" method instead of ".item" method, so you can be safely getting the item you need.
```

**To Reproduce**
In test/conftest.py 
put the line `hook.local_worker.verbose=True` in the hook function

**Expected behavior**
Tests should pass regardless of if they are printing output

**Comment by mari-linhares** [comment]
@robert-wagner I've had a discussion about this with @IonesioJunior some time ago, we think this is due to the fact that garbage collector "gets stuck" since every time you're printing something you're creating a new reference to it, that tries to be deleted but then is printed again, ... and so on

**Comment by mari-linhares** [comment]
Having said that, if our intuition is true I'm not sure how easy is to get this fixed

**Comment by refactormyself** [comment]
Hello, please is anyone working on this. 
I will like to give it a try. Thanks

**Comment by LaRiffle** [comment]
I don't think so, you're very much welcome!

**Comment by imskr** [comment]
@LaRiffle Is anyone working on this?

**Comment by Kritikalcoder** [comment]
Can I start working on this?
