### ISSUE TITLE
All tests calling start_proc fail on windows

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2281]
**Describe the bug**
Start proc does not succeed on windows causing 9 tests to fail
**To Reproduce**
Call make test on windows

**Expected behavior**
Tests should work on all operating systems
**Desktop (please complete the following information):**
 - OS: windows
 - Version: all

**Additional context**

[-.txt](https://github.com/OpenMined/PySyft/files/3286916/-.txt)

**Comment by amit-rastogi** [comment]
I would like to take this up if this is still available.

**Comment by amit-rastogi** [comment]
On Windows the web socket client also fails to connect giving the error below. 

OverflowError: timeout doesn't fit into C timeval

Appears to be due to the timeout interval (TIMEOUT_INTERVAL = 9_999_999) specified in websocket_client.py.

**Comment by amit-rastogi** [comment]
I saw the PR "[WIP] Implement start_remote_worker #2345" where its mentioned that start_proc would get replaced with start_remote_worker. Hence, wanted to check if this issue is still valid and needs to be worked upon?

**Comment by mari-linhares** [comment]
Hey @amit-rastogi,

The new function actually uses `start_proc`, so yes, this issue is still valid.

**Comment by amit-rastogi** [comment]
The web socket client overflow error on windows has been addressed by https://github.com/OpenMined/PySyft/pull/2395
