### ISSUE TITLE
Import syft on Azure databricks for secure model serving with Syft Keras

### ISSUE THREAD

**Issue by Polarbeargo** [OpenMined/PySyft#2282]
**Describe the bug**
Dear all,
I'm working on Azure Databricks want to try out install syft and encounter error log like bellow
`Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.1.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting syft
  Downloading https://files.pythonhosted.org/packages/56/ba/12753b3ef01a4b4cd6bba6326001b1ac9d372155828f935c198dbb092c1a/syft-0.1.18.tar.gz (136kB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b0P0kB/syft/setup.py", line 15, in <module>
        requirements = read("requirements.txt").split()
      File "/tmp/pip-install-b0P0kB/syft/setup.py", line 12, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-b0P0kB/syft/requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-b0P0kB/syft/`
**Expected behavior**
Hope I can import syft and secure model serving with Syft Keras
successfully on Azure Databricks

**Screenshots**
![87](https://user-images.githubusercontent.com/8589224/59495146-493bd100-8ec1-11e9-9430-8c2a976211c3.png)

**Azure Databricks (please complete the following information):**
![2](https://user-images.githubusercontent.com/8589224/59495195-5e186480-8ec1-11e9-950e-fad11894e071.png)
PYSPARK_PYTHON=/databricks/python3/bin/python3

**Comment by robert-wagner** [comment]
@Polarbeargo You are trying to install syft on python 2. Syft only supports python 3

**Comment by Polarbeargo** [comment]
Thank you @robert-wagner 👍 !
