### ISSUE TITLE
Docker image for Raspberry PI

### ISSUE THREAD

**Issue by youben11** [OpenMined/PySyft#2292]
**Problem**
It's really frustrating to setup a Raspberry PI to run PySyft as shown in [this blog post](https://blog.openmined.org/federated-learning-of-a-rnn-on-raspberry-pis/) by @DanyEle 

**Suggested Solution**
Make a ready to use Docker image of PySyft for Raspberry PIs.

**Comment by gmuraru** [comment]
@youben11 do you have any idea if this is working?

**Comment by youben11** [comment]
I was working on it and had many issues that would have been resolved over time, so I postponed the work for later but couldn't get back till now. Nothing that works, only a dirty branch [here](https://github.com/youben11/PySyft/tree/pysyft-worker-docker)
