### ISSUE TITLE
TrainConfig parameter "epochs"

### ISSUE THREAD

**Issue by racinger** [OpenMined/PySyft#2306]
**TrainConfig parameter "epochs" doesn't have effect.**
After changing the number of epochs=1 to epochs=100. The worker still do only 1 epoch.

```
train_config = sy.TrainConfig(
        model=traced_model,
        loss_fn=loss_fn,
        batch_size=batch_size,
        shuffle=True,
        #max_nr_batches=max_nr_batches,
        epochs=100,
        lr=lr,
    )
```

**Comment by mari-linhares** [comment]
Hey @racinger,

Thanks for creating the issue!

I think this used to work but due to multiple new PRs this behavior may have been compromised. I'll fix it later today, and it should work on the next syft release :).

**Comment by racinger** [comment]
Great to hear. Thanks for your great work @mari-linhares !
