### ISSUE TITLE
Travis build error: setuptools>=41.0.0 is required by {'tensorboard'}

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2310]
There is a very frequent error while building Travis. We need to restart the build, which is time consuming and also impossible when not granted the appropriate rights.

```
...
$ python setup.py install >> build.log
zip_safe flag not set; analyzing archive contents...
error: setuptools 38.2.4 is installed but setuptools>=41.0.0 is required by {'tensorboard'}
The command "python setup.py install >> build.log" failed and exited with 1 during .
Your build has been stopped.
```

We need to relaunch the build several times to have it working, how can we fix this issue related to tensorboard?

**Comment by midokura-silvia** [comment]
I fixed it putting a requirement setuptool>=41.0.0 in requirements_dev.txt
Code contained in PR on tf_encrypted dependency removal

**Comment by LaRiffle** [comment]
Awesome!

**Comment by midokura-silvia** [comment]
Code merged into dev
