### ISSUE TITLE
Transform ToTensor() on BaseDataset automatically executes get()

### ISSUE THREAD

**Issue by aristizabal95** [OpenMined/PySyft#2313]
**Describe the bug**
Iterating with `FederatedDataLoader` on a federated dataset with `transforms.ToTensor()` will return the raw data tensor instead of a pointer to the tensor.

**To Reproduce**

This is a working script that demonstrates the issue.
```python
import torch as th
import syft as sy
import torchvision
from torchvision import transforms

hook = sy.TorchHook(th)

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")

# DECLARE A TOY DATASET AS IMAGE DATA
data = th.tensor([[[1,1],[0,1],[1,0],[0,0]],[[1,1],[0,1],[1,0],[0,0]],[[1,1],[0,1],[1,0],[0,0]],[[1,1],[0,1],[1,0],[0,0]]]).type(th.uint8)
target = th.tensor([[1],[1], [0], [0]])

# DECLARE TRANSFORM WITH TOTENSOR
transform = transforms.ToTensor()

# SPLIT THE DATASET AND SEND TO WORKERS
bob_dataset = sy.BaseDataset(data[:2], target[:2], transform=transform).send(bob)
alice_dataset = sy.BaseDataset(data[2:], target[2:], transform=transform).send(alice)

# DECLARE THE FEDERATED DATASET AND DATALOADER
f_dataset = sy.FederatedDataset([bob_dataset, alice_dataset])
f_dataloader = sy.FederatedDataLoader(f_dataset, shuffle=True, batch_size=2)

# GET A BATCH FORM THE DATALOADER
data, label = next(iter(f_dataloader))  # This batch should be returned as pointers to the tensors


print(data) # UNEXPECTED: returns the raw data without using get()
print(label) # EXPECTED: returns the pointer to the tensor

```

**Expected behavior**
transforms should be run remotely and `FederatedDataLoader` should return the pointer to the remote data.

Specifically:
`data` should be a pointer tensor and not the data tensor itself.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.1
 - Version `syft==0.1.19a1`

**Comment by ajnovice** [comment]
I think as of now, Transforms cannot be applied to Pointer, Fixed Precision or Float Precision tensors. @mari-linhares, If you guys are planning to extend the Transforms to Pointer, Fixed Precision or Float Precision, I would like to get involved.
