### ISSUE TITLE
Backward function not called for torch.autograd.function

### ISSUE THREAD

**Issue by DanyEle** [OpenMined/PySyft#2318]
**Describe the bug**
The `backward` function of a custom class in PySyft inherited from the `torch.autograd.function` is not invoked when running the `backward()` method on remote tensors. This feature is essential for my current research work based on PySyft. 

**To Reproduce**
Just run this code:

```
import torch
import torch.autograd as autograd
import torch.nn as nn
import syft as sy

class MyFun(torch.autograd.Function):
    def forward(self, inp):
        return inp

    def backward(self, grad_out):
        grad_input = grad_out.clone()
        print('Custom backward called!')
        return grad_input

class MyMod(nn.Module):
    def forward(self, x):
        return MyFun()(x)

#local version - the backward method is indeed invoked. 
mod = MyMod()
y = autograd.Variable(torch.randn(1), requires_grad=True)
z = mod(y)
z.backward()

#remote version - the backward method is not invoked.
hook = sy.TorchHook(torch)
worker = sy.VirtualWorker(hook, id="alice")
y_remote = y.send(worker)
z_remote = z.send(worker)
z_remote.backward()
```

**Expected behavior**
I would expect the backward() method from the custom class to be actually called. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Additional context**
I believe the problem lies in the fact that the `torch.autograd.function` is not implemented in PySyft, and hence the `backward` method of a custom class is not invoked.

**Comment by LaRiffle** [comment]
As discussed with @DanyEle one reason for this can be:
Regarding nn.Modules operated on remote data, the forward pass method is run by the client (ie the local instance) and then all ops inside (like nn.relu or nn.Linear) are hooked and a message is sent for each of them to the workers which holds the data. Therefore, the remote worker doesn't have the big picture of your nn.module model.
However, when you call backward, the cmd `backward()` is sent directly to the remote worker. In this case, as it doesn't have the big picture of your nn.module model, it doesn't see the custom backward of yours and just performs the default backward.

**Comment by DanyEle** [comment]
Thank you for the response @LaRiffle . Any idea on how to possibly fix this issue and introduce support for torch.autograd.function in PySyft over remote tensors?

**Comment by robert-wagner** [comment]
hey @DanyEle On another note, how does this behave if you call y.send() before you call the mod on it?

**Comment by DanyEle** [comment]
> hey @DanyEle On another note, how does this behave if you call y.send() before you call the mod on it?

Just tried it and did not notice any difference. The backward method from the MyMod class is still not invoked.

**Comment by iamtrask** [comment]
This seems like a good fit for AutogradTensor, no? (CC: @LaRiffle)

**Comment by iamtrask** [comment]
The core issue is that when we serialize objects we don't serialize their graph as well. In other words, when you call .send() on a tensor, we don't send the whole graph, we only send that tensor.

However, the fix should be easy. If you send everything BEFORE the forward pass it should work.

TODO: we should add support for someone to send a dynamic graph

**Comment by iamtrask** [comment]
@LaRiffle - shouldn't it be possible to do what he's trying to do using AutogradTensor? Is there a way to call .send() on a graph and keep the graph local but just send the tensor to a remote machine so that when you call .backward() it does backprop locally but executes it remotely?

Aka - how does he create a custom op for AutogradTensor?

**Comment by DanyEle** [comment]
As suggested by @iamtrask , I currently trying to use "AutogradTensor" from Pull Request #2293 , however I have not yet managed to get it working with a custom class.

Any ideas on how to combine custom classes in combination with an AutogradTensor?

**Comment by LaRiffle** [comment]
Hey! 
So there are many things here,
- Currently with AutogradTensor, you need to specify the gradient for all operations that you use, and in particular you need to explain how the backward is supposed to be computed, so you cant' just add a print statement to some multiplication function, you also need to re-state how to differentiate it. Of course this is not a pb for a function which doesn't modify the data. One awesome thing would be to be able to call the native backward for a function, which might not be always available especially if you don't have access to the graph of computation grad_fn.
- To specify a custom function with a forward and backward, which are understood by Autograd, you currently need to add this function in gradient.py, would be good to offer a way for user to add more functions directly in the code just like @DanyEle tries to do

**Comment by LaRiffle** [comment]
The easiest way to do would be to work in the second direction, and the piece of code that we'd like to work would be:
```python
import torch
import torch.autograd as autograd
import torch.nn as nn

import syft as sy
hook = sy.TorchHook(torch)
worker = sy.VirtualWorker(hook, id="alice")

class MyFunction(torch.autograd.Function):
    def forward(self, x):
        print("Custom forward called")
        return x
    
    def backward(self, grad_out):
        grad_input = grad_out.clone()
        print('Custom backward called!')
        return grad_input


x = torch.tensor([1.5], requires_grad=True)
x = x.send(worker, local_autograd=True)

y = MyFunction(x)

y.backward()
```
Would this address your usecase?

**Comment by DanyEle** [comment]
Thank you for the example @LaRiffle . I tried running your code, but got the following error:

```
y.backward()

TypeError: backward() missing 1 required positional argument: 'grad_out'
```

Instead, when running

`y.backward(x)`

This does seem to be working as expected and the backward method is indeed invoked from the custom class. I have yet to verify whether this would work for my particular case though.

**Comment by LaRiffle** [comment]
So I would say the sample of code I suggetsed is not supposed to work right now, but we should do the appropriate imprvements in autograd to have it working. It's more a target to achieve :)

**Comment by DanyEle** [comment]
I'm currently trying to run a slightly more complicated example:

```python
#Perform forward pass
 output, hidden = remote_model_cpu_train(data_remote, hidden_repackaged, worker)
#Resize the output
output_viewed = output.view(-1, ntokens)
#Compute the loss
loss = criterion(output_viewed, targets_remote)
#Let's backpropagate over here!
loss.backward(hidden) 
```
However, I get the following error in the loss.backward(hidden) step:

![image](https://user-images.githubusercontent.com/4907418/61128878-65786100-a4b3-11e9-8b61-eb205a3d7ab3.png)

**Comment by DanyEle** [comment]
Perhaps no serialization mechanism are implemented for AutogradTensor objects? Not super sure.. I'm trying to look into it.

**Comment by DanyEle** [comment]
The current implementation for these methods I came up with is the following, however it's not working yet:


from a`utograd.py`


```python
 @staticmethod
    def simplify(tensor: "AutogradTensor") -> tuple:
        """Takes the attributes of an AutogradTensor and saves them in a tuple.

        Args:
            tensor: an AutogradTensor.

        Returns:
            tuple: a tuple holding the unique attributes of the AutogradTensor.
        """
        print("Simplify AutogradTensor")
        chain = None
        if hasattr(tensor, "child"):
            chain = syft.serde._simplify(tensor.child)
            
        return (
            syft.serde._simplify(tensor.id),
            tensor.grad,
            tensor.owner,
            tensor.grad_fn,
            tensor.preinitialize_grad,
            tensor.requires_grad,
            tensor.data,
            syft.serde._simplify(tensor.tags),
            syft.serde._simplify(tensor.description),
            chain,
        )
        

    @staticmethod
    def detail(worker: AbstractTensor, tensor_tuple: tuple) -> "AutogradTensor":
        """
            This function reconstructs an AutogradTensors given its attributes in form of a tuple.
            Args:
                worker: the worker doing the deserialization
                tensor_tuple: a tuple holding the attributes of the AutogradTensor
            Returns:
                AutogradTensor: an AutogradTensor
            Examples:
                shared_tensor = detail(data)
            """
            
        print("Detail AutogradTensor")

        tensor_id, grad, owner_worker, grad_fn, preinit_grad, requires_grad, data, tags, description, chain = tensor_tuple

        tensor = AutogradTensor(
            data=data,
            requires_grad=requires_grad,
            owner=owner_worker,
            id=syft.serde._detail(worker, tensor_id),
            preinitialize_grad=preinit_grad,
            grad_fn=grad_fn, #not needed?
            grad=grad, #not needed?
            tags=syft.serde._detail(worker, tags), #not needed?
            description=syft.serde._detail(worker, description), #not needed?
        )

        if chain is not None:
            chain = syft.serde._detail(worker, chain)
            tensor.child = chain

        return tensor
```

**Comment by DanyEle** [comment]
I successfully managed to implement the serialization and deserialization procedures. Nevertheless, my issue with remote backpropagation using a custom class still persists, and a [0,0,0,..0] gradient is produced in all model's parameters.

**Comment by DanyEle** [comment]
Issue finally solved thanks to the help provided by @iamtrask !! To get the actual gradient following backpropagation, it was sufficient to do:

`for param in model.parameters():
     param.grad.data.location._objects[param.grad.data.id_at_location]`

Instead  of:

`for param in model.parameters():
   param.grad.data`

Closing the Issue as it got resolved!

**Comment by DanyEle** [comment]
Moved issue to #2361
