### ISSUE TITLE
Few typing errors in tutorials

### ISSUE THREAD

**Issue by ProfXGiter** [OpenMined/PySyft#2322]
Thank you the contributors, the tutorials is great, but I found few typing errors so far.

Fisrt:
In PySyft/examples/tutorials/Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving.ipynb,
in section Cleanup!,
in last it say "Congratulations on finishing **Part 12**: Secure Classification with Syft Keras and TFE!"
It should be "Congratulations on finishing **Part 13b**: Secure Classification with Syft Keras and TFE!".
Not Part12, it is Part13b.

Second:
In PySyft/examples/tutorials/Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb,
section Connect to model,
line 3, "server set up by model.serve() in **Part 11b**.",
it should be ""server set up by model.serve() in **Part 13b**."".
Not Part11b, it is Part13b.

Third:
In PySyft/examples/tutorials/Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb,
section Query model,
line 2, "and submit the shares to the model server in Part 11b",
it should be "and submit the shares to the model server in Part 13b".
Not Part11b, it is Part13b.

Forth:
In PySyft/examples/tutorials/Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb,
section Query model,
in last it say "Before we rush off to apply this in our own apps, let's quickly go back to **Part 11b** to clean up our served model!",
it should be "Before we rush off to apply this in our own apps, let's quickly go back to **Part 13b** to clean up our served model!".
Not Part11b, it is Part13b.

These are typing errors if I am understand correct.
Thanks again the contributors, hope this projects better and better.

**Comment by mari-linhares** [comment]
Thanks for the contribution @ProfXGiter, feel free to make a PR to fix these typos!
