### ISSUE TITLE
Have the option to turn off plans execution

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2324]
**Is your feature request related to a problem? Please describe.**

Currently, plans are executed as readable plans all the time except for building the plan.

In other words, when a user calls a plan there's not a way to run execute the original blueprint aka the actual function wrapped by the plan decorator.

This could be useful for: training a model locally with regular pytorch but then serve it in an encrypted fashion using plans.

**Describe the solution you'd like**

I would like to have a way to control if a plan should be run using a blueprint or not. A few options are:

1. Adding an argument to `__call__` in plans.py called "use_blueprint". If this is True then the blueprint is executed.
2. Use a global variable like syft.PLAN_USE_BLUEPRINT.
3. By default executing the blueprint if available. Otherwise executing the readable plan. This will require the user to explicitly build a plan.

The third is by far the best option in my opinion since it will be transparent to the user (they do not need to know how a plan works at all you just run and it works) and just work out of the box.

**Comment by mari-linhares** [comment]
@LaRiffle @robert-wagner @midokura-silvia do you have any thoughts about this?

**Comment by robert-wagner** [comment]
How does this affect performance/ the ability to send plans? If it has a dominance relationship with the current implementation for those two categories, I'm all for it. I personally am opposed to having global variables if all possible (they break in multiprocessing situations). Furthermore, I think adding the argument to call, means it will not be used.

**Comment by mari-linhares** [comment]
> How does this affect performance/ the ability to send plans? 

It should affect neither. 

There are mainly two cases:
* If a plan is local (worker has the blueprint), it will execute the plan using the blueprint.
* If a plan was sent, it will execute plans in the "traditional way".

**Comment by mari-linhares** [comment]
The main pro is that: locally a plan will behave exactly like the original function/method to users.
The main con is that: remotely this may not be true (for example: a plan for a Model will not be able to train remotely without using autograd tensors).

**Comment by midokura-silvia** [comment]
I don't see it as a problem to have different behavior locally and remotely. However we should make sure that all relevant cases are tested and cannot get different results.

**Comment by mari-linhares** [comment]
Another important change that option 3 would require is that users will need to call `plan.build` explicitly since the default behaviour will not build the plan.

How do you feel about this? @LaRiffle 

I don't see this as a major problem, and I still think the third option is more intuitive than others.
