### ISSUE TITLE
Add div support of autograd Tensor

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2336]
We have add sub mul but not div yet implemented for autogradtensor

**Comment by pynchmeister** [comment]
I'd like to give this a shot if that's ok. Where can I find this in the directory?

**Comment by LaRiffle** [comment]
@wagnernegrao  has started on this issue I think, but you can also give a try of course

have a look at syft/frameworks/torch/tensors/interpreters/
- autograd.py
- gradients.py

**Comment by LaRiffle** [comment]
Has been done actually
