### ISSUE TITLE
When sharing a model where bias equals true, not all parameters get shared

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/PySyft#2365]
**To Reproduce**
Run attached notebook until you get an error. When you look at the args of the call to addmm, one of the args is a torch tensor when all should be ast. This implies that either the weights or the bias is not being shared (Im pretty sure)

**Comment by robert-wagner** [comment]
[reproduce_error.ipynb.zip](https://github.com/OpenMined/PySyft/files/3403467/reproduce_error.ipynb.zip)

**Comment by robert-wagner** [comment]
@shivramsrs

**Comment by LaRiffle** [comment]
The pb is that the data is not shared correctly here:

The model can be shared in-place but data can't be:
```python
model.share(...) # Is OK
model = model.share(...) # Is OK

data.share(...) # IS *NOT* OK
data = data.share(...) # Is OK
```
Additionally, all the parameters of the model get shared by default: we loop on model.parameters()
