### ISSUE TITLE
error in websockets-example-MNIST tutorials

### ISSUE THREAD

**Issue by 1000ping** [OpenMined/PySyft#2370]
To Reproduce error:
1. In terminal Activate pytorch Environment 
2. cd to PySyft-dev\examples\tutorials\advanced\websockets-example-MNIST
3. run command `python run_websocket_server.py --port 8887 --id alice`

WARNING: Logging before flag parsing goes to stderr.
W0720 07:04:28.831149  5416 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was 'H:\Softwares\anaconda\envs\dlpytorch\lib\s
ite-packages\tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0720 07:04:28.846143  5416 deprecation_wrapper.py:119] From H:\Softwares\anaconda\envs\dlpytorch\lib\site-packages\tf_encrypted\session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Traceback (most recent call last):
  File "run_websocket_server.py", line 53, in <module>
    server = start_proc(WebsocketServerWorker, kwargs)
  File "run_websocket_server.py", line 23, in start_proc
    p.start()
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'start_proc.<locals>.target'

(dlpytorch) C:\Users\wajah\PycharmProjects\pytorch_help\PySyft-dev\examples\tutorials\advanced\websockets-example-MNIST>WARNING: Logging before flag parsing goes to stderr.
W0720 07:04:31.624255 15556 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was 'H:\Softwares\anaconda\envs\dlpytorch\lib\s
ite-packages\tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0720 07:04:31.639249 15556 deprecation_wrapper.py:119] From H:\Softwares\anaconda\envs\dlpytorch\lib\site-packages\tf_encrypted\session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wajah\PycharmProjects\pytorch_help\PySyft-dev\examples\tutorials\advanced\websockets-example-MNIST\run_websocket_server.py", line 53, in <module>
    server = start_proc(WebsocketServerWorker, kwargs)
  File "C:\Users\wajah\PycharmProjects\pytorch_help\PySyft-dev\examples\tutorials\advanced\websockets-example-MNIST\run_websocket_server.py", line 23, in start_proc
    p.start()
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

4. After replacing 
`server = start_proc(WebsocketServerWorker, kwargs)`

in run_websocket_server.py with 

```
if __name__ == '__main__':
    freeze_support()
    server = start_proc(WebsocketServerWorker, kwargs)
```

and running command
 
`python run_websocket_server.py --port 8887 --id alice`

 again

Traceback (most recent call last):
  File "run_websocket_server.py", line 53, in <module>
    server = start_proc(WebsocketServerWorker, kwargs)
  File "run_websocket_server.py", line 23, in start_proc
    p.start()
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'start_proc.<locals>.target'

(dlpytorch) C:\Users\wajah\PycharmProjects\pytorch_help\PySyft-dev\examples\tutorials\advanced\websockets-example-MNIST>WARNING: Logging before flag parsing goes to stderr.
W0721 19:48:18.066954 13356 secure_random.py:22] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow (1.14.0). Fix this by compi
ling custom ops.
W0721 19:48:18.099944 13356 deprecation_wrapper.py:119] From H:\Softwares\anaconda\envs\dlpytorch\lib\site-packages\tf_encrypted\session.py:28: The name tf.Session is deprecated. Please use tf.compat.
v1.Session instead.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "H:\Softwares\anaconda\envs\dlpytorch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Expected behavior
I expected them to launch WebSocket servers on my machine 

I am getting same errors when running `python websocket_servers.py`
OS version windows 10 64bit
python version 3.6.8
Cuda 10

Installed python libraries

absl-py                   0.7.1                     <pip>
astor                     0.8.0                     <pip>
attrs                     19.1.0                    <pip>
backcall                  0.1.0                     <pip>
bleach                    3.1.0                     <pip>
certifi                   2019.3.9                 py36_0
cffi                      1.12.3                    <pip>
Click                     7.0                       <pip>
colorama                  0.4.1                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.4.0                     <pip>
defusedxml                0.6.0                     <pip>
dill                      0.3.0                     <pip>
entrypoints               0.3                       <pip>
enum34                    1.1.6                     <pip>
Flask                     1.1.1                     <pip>
Flask-SocketIO            4.1.0                     <pip>
gast                      0.2.2                     <pip>
gevent                    1.4.0                     <pip>
google-pasta              0.1.7                     <pip>
greenlet                  0.4.15                    <pip>
grpcio                    1.22.0                    <pip>
h5py                      2.9.0                     <pip>
ipykernel                 5.1.1                     <pip>
ipython                   7.6.1                     <pip>
ipython-genutils          0.2.0                     <pip>
itsdangerous              1.1.0                     <pip>
jedi                      0.14.1                    <pip>
Jinja2                    2.10.1                    <pip>
joblib                    0.13.2                    <pip>
json5                     0.8.5                     <pip>
jsonschema                3.0.1                     <pip>
jupyter-client            5.3.1                     <pip>
jupyter-core              4.5.0                     <pip>
jupyter-http-over-ws      0.0.6                     <pip>
jupyterlab                1.0.2                     <pip>
jupyterlab-server         1.0.0                     <pip>
Keras-Applications        1.0.8                     <pip>
Keras-Preprocessing       1.1.0                     <pip>
kiwisolver                1.1.0                     <pip>
lz4                       2.1.10                    <pip>
Markdown                  3.1.1                     <pip>
MarkupSafe                1.1.1                     <pip>
matplotlib                3.1.1                     <pip>
mistune                   0.8.4                     <pip>
msgpack                   0.6.1                     <pip>
nbconvert                 5.5.0                     <pip>
nbformat                  4.4.0                     <pip>
notebook                  5.7.8                     <pip>
numpy                     1.16.4                    <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.5.1                     <pip>
pickleshare               0.7.5                     <pip>
Pillow                    6.1.0                     <pip>
Pillow                    6.0.0                     <pip>
pip                       19.1.1                   py36_0
prometheus-client         0.7.1                     <pip>
prompt-toolkit            2.0.9                     <pip>
protobuf                  3.8.0                     <pip>
pycparser                 2.19                      <pip>
Pygments                  2.4.2                     <pip>
pyparsing                 2.4.0                     <pip>
pyrsistent                0.15.3                    <pip>
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.0                     <pip>
python-engineio           3.8.2.post1               <pip>
python-socketio           4.2.0                     <pip>
pywinpty                  0.5.5                     <pip>
PyYAML                    5.1.1                     <pip>
pyzmq                     18.0.2                    <pip>
scikit-learn              0.21.2                    <pip>
scipy                     1.3.0                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                41.0.1                   py36_0
six                       1.12.0                    <pip>
sqlite                    3.28.0               he774522_0
syft                      0.1.21a1                  <pip>
tblib                     1.4.0                     <pip>
tensorboard               1.14.0                    <pip>
tensorflow                1.14.0                    <pip>
tensorflow-estimator      1.14.0                    <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.2                     <pip>
testpath                  0.4.2                     <pip>
tf-encrypted              0.5.4                     <pip>
torch                     1.1.0                     <pip>
torchvision               0.3.0                     <pip>
tornado                   6.0.3                     <pip>
traitlets                 4.3.2                     <pip>
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
websocket                 0.2.1                     <pip>
websocket-client          0.56.0                    <pip>
websockets                8.0.1                     <pip>
Werkzeug                  0.15.4                    <pip>
wheel                     0.33.4                   py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.11.2                    <pip>
zstd                      1.4.1.0                   <pip>

**Comment by DanyEle** [comment]
Hi, could you please follow the template for writing an Issue, so that more people can help solve your problem? Having a reproducible code snippet, along with details about your systems would surely help.

**Comment by 1000ping** [comment]
@DanyEle Thank you for pointing that out I have edited it now.

**Comment by amit-rastogi** [comment]
@1000ping instead of spawning a separate process on Windows during which pickling error is encountered you can create the WebSocketServer within the current process context itself. I have created a PR with this change. https://github.com/OpenMined/PySyft/pull/2389
