### ISSUE TITLE
about error in websocket mnist example 

### ISSUE THREAD

**Issue by ProfXGiter** [OpenMined/PySyft#2378]
**Describe the bug**
KeyError: (wrapper)>[PointerTensor | me:some series of numbers -> alice:some series of number]

**To Reproduce**
Add the code in run_websocket_client.py:
```
kwargs_websocket_alice = {"host": "127.0.0.1", "hook": hook}
alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket_alice)
workers = [alice]
```
I run the lines:
python3 run_websocket_server.py --host 127.0.0.1 --port 8777 --id alice
python3 run_websocket_client.py

It shows the bug.

**Desktop (please complete the following information):**
RedHat Linux 7.2, python3.6.8, pysyft==0.1.13a1, torch==1.0.1, torchvision==0.2.2
nvidia-driver==410.48, cuda==10.0, cudnn==7.5

**Additional context**
I change to: pysyft==0.1.19a1, torch==1.1.0, torchvision==0.3.0
or I use the VirtualHook.
The bug still have.

**Comment by Jiarong000** [comment]
I also see this error! But when i use 2 workers it works fine.
