### ISSUE TITLE
new dataset  

### ISSUE THREAD

**Issue by Liepill** [OpenMined/PySyft#2380]
Hi, I want to know how can I load a dataset that doesn't exit in torch datasets in federated style.

**Comment by kamathhrishi** [comment]
Hello @Liepill , do check out examples->tutorials->advanced , we have a tutorial on how to do that.

**Comment by kamathhrishi** [comment]
https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/advanced/Federated%20Dataset.ipynb

**Comment by kamathhrishi** [comment]
Close this issue ?
