### ISSUE TITLE
"Via" Worker

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2383]
**Is your feature request related to a problem? Please describe.**
In some cases we do not want to support the ability for two workers to communicate directly with each other (perhaps both are behind separate firewalls), and instead we want them to communicate via a 3rd worker. Thus, we would like to have a new extension of BaseWorker which can generically leverage ANY other worker type as a proxy to forward messages to a final worker.

**Describe the solution you'd like**

We do NOT want to have to implement a new Via worker type for every existing worker type. I *think* that we can implement this functionality generically using a new BaseWorker extension I will call "ViaWorker". This wraps any message sent to the final worker inside of a wrapper with routing information (which will require a new msgtype to be added to BaseWorker).

Instatiating a ViaWorker should work like this.

bob = VirtualWorker()
alice = VirtualWorker()
sue = VirtualWorker()

Let's say that Bob wants to send a message to Alice but cannot do so directly. So, instead Bob is going to send it via Sue. First, Bob needs to ask Sue what workers she knows about.

workers = sue.get_known_workers()

This should return a dict of ViaWorkers by default, which can be used to send messages to those workers via Sue. Note that each ViaWorker should also support an attempt to convert the ViaWorker to another kind of worker (such as SocketWorker) if the worker is available via a public endpoint. Let's say that alice is the first worker returned by sue.

alice_via_bob = workers['alice']

x = th.tensor([1,2,3,4,5])

x_ptr = x.send(alice_via_bob)

Note that when Sue sends Bob the ViaWorkers, they should automatically come down with the public keys necessary to send encrypted communication to each respective worker.

**Describe alternatives you've considered**
We need to be able to verify that the public key which Bob receives is actually the correct one. We should have some sort of central registry for keys (or just have one worker which is very popular and run by OpenMined), which means we should have the ability to check that the public keys match. Aka.

bob = VirtualWorker()
alice = VirtualWorker()
sue = VirtualWorker()
john = VirtualWorker()

assert sue.get_known_workers()['alice'].pub_key == john.get_known_workers()['alice'].pub_key

We should be able to run this kind of check just to make sure that everyone agrees on which key Alice is using.

**Additional context**
We will need this to work with syft.js - as getting two browsers to be able to communicate with each other is probably the main use case for ViaWorkers

**Comment by kamathhrishi** [comment]
I will work on this 👍
