### ISSUE TITLE
Openmined `client` tutorial is broken and needs fixing

### ISSUE THREAD

**Issue by kakirastern** [OpenMined/PySyft#2396]
**Describe the bug**
The Colab version of the `Client` notebook needs fixing, as the code version it was based on is now deprecated. 

**To Reproduce**
1. Go to [https://colab.research.google.com/drive/1Je1rk7olA9uTWWaqvvt4_gXf7yX1rTBm](https://colab.research.google.com/drive/1Je1rk7olA9uTWWaqvvt4_gXf7yX1rTBm), or follow the web link on [https://www.openmined.org/](https://www.openmined.org/)
2. Check the outputs of the cells in that notebook
3. See error

**Expected behavior**
A good notebook should be as a bare minimum functional yet informative, especially in this context. 

**Desktop (please complete the following information):**
 - Google Colaboratory

**Additional context**
The code base of the websocket* workers might need to be modified to achieve the desired effect.

**Comment by kakirastern** [comment]
I would really like to work on this issue though... which is not to be confused with #1905, which deals with the accompanying `Server` tutorial notebook hosted on Colab.

**Comment by kakirastern** [comment]
I am guessing to make the tutorial run perfectly on Colab this is what we need to do: https://research.google.com/colaboratory/local-runtimes.html

**Comment by kakirastern** [comment]
Am actively working on this issue, and will open a PR to follow up soon.

**Comment by midokura-silvia** [comment]
@kakirastern Is this done? Can we close this issue?

**Comment by kakirastern** [comment]
Yup, I have modified the file on Google Colab so it should be fine now. At least it was the last time I checked.
