### ISSUE TITLE
Docs request: Web-based tutorials

### ISSUE THREAD

**Issue by kakirastern** [OpenMined/PySyft#2397]
**Is your feature request related to a problem? Please describe.**
Yes... I have been a member of "Learn Astropy", which is a subsidiary of the Astropy community for some time now. From what I could observe on PySyft, including the GitHub repo, Slack, and website, I am thinking it might be worth considering for the PySyft community to perfect the way tutorials are presented for the package. Currently notebooks are stored in the repo for people to download for themselves and experiment with. But in my mind at least, some kind of a web version with more comprehensive info and interactive features would definitely draw more new comers in who are not experienced with Git at first. 

**Describe the solution you'd like**
A web-based version hosting all the tutorials for PySyft. 

**Describe alternatives you've considered**
Staying the course, keeping the tutorials in the repo only. 

**Additional context**
Example: http://learn.astropy.org/ (But what I have in mind is on a much smaller and manageable scale.)

**Comment by kakirastern** [comment]
As per Slack discussion earlier, perhaps rendering the tutorials into Google Colab versions would be a good way forward too.

**Comment by TTitcombe** [comment]
what about [binder](https://mybinder.org/)?

**Comment by ucalyptus** [comment]
Look at this https://medium.com/jovianml/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e
