### ISSUE TITLE
Docs update: Improvements to CONTRIBUTING.md

### ISSUE THREAD

**Issue by kakirastern** [OpenMined/PySyft#2399]
**Is your feature request related to a problem? Please describe.**
The request is not related to a problem, but instead related to some desired improvements to make the documentation more complete. For example, it appears to be a given as to how to install the development version of `syft` as a simple command, but in fact there can be variations and not every one knows about this basic command unless an example of it is provided. 

**Describe the solution you'd like**
I would like to see more relevant info be included in CONTRIBUTING.md to make the documentation more detailed or at least complete so that the novice can follow the instructions will no issues. 

**Describe alternatives you've considered**
Or the documentation can stay as is the current state. 

**Additional context**
Would love to be assigned this task.

**Comment by kamathhrishi** [comment]
We could just add a link to INSTALLATION.md for reference?

**Comment by kakirastern** [comment]
True, that would do to some extent... Maybe will need to add some descriptions about what can be found and expected at `INSTALLATION.md` too. 

And how about adding some material regarding the **workflow**, or just polish up the existing material and expand on this where necessary?
