### ISSUE TITLE
Serde: Map with simplifiers and detailers should use constant values

### ISSUE THREAD

**Issue by mccorby** [OpenMined/PySyft#2409]
**Is your feature request related to a problem? Please describe.**
`Serde` makes use of two dictionaries to know the type of the object. As it is right now, it does so by checking the position. This however fast it's a problem when other systems are added as JS or the JVM.
A change in the position of any of the elements or addition or removal can create a cascade of issues on the other side.

**Describe the solution you'd like**
Assign a constant value to each of these entries in the dictionary so that they do not change (unless strictly necessary)

**Describe alternatives you've considered**
A constant to represent each type

**Additional context**

**Comment by LaRiffle** [comment]
Fixed by #2654
