### ISSUE TITLE
Close the issues that have been already implemented and merged

### ISSUE THREAD

**Issue by sajalsubodh22** [OpenMined/PySyft#241]
@iamtrask sir there are still many issues opened which have been solved and merged. This is thus causing a problem in finding non-implemented issues to fix.

**Comment by siarez** [comment]
@sajalsubodh22 Can you let me which issues your are talking about? I'll check them out.

**Comment by iamtrask** [comment]
Sorry about that @sajalsubodh22 !

**Comment by iamtrask** [comment]
dammit... keep accidentally hitting "Close and comment"... ironic... since this ticket is about my reluctance to close the right Issues

**Comment by aiorla** [comment]
I don't know if this has been talked outside GH but these are some currently implemented-but-not-closed issues:

* Abs (#20) fixed by #124
* Cumsum (#35) fixed by #136 
* Equal (#40) fixed by #126 
* View (#108) fixed by #193 
* Rsqrt (#90) fixed by #179

ping: @iamtrask & @siarez

**Comment by siarez** [comment]
Right now we are discussing whether we want to conform to PyTorch's conventions. And if not come up with conventions of our own. In either case some of these functions will most likely have to be moved around. 
Maybe we can defer closing them untill then, or we can close them now open another issue which addresses the convention issue.

**Comment by iamtrask** [comment]
Closed. We should address the convention thoughts under the new ticket.
That way we keep the conversation focused in one spot (easier to follow)
