### ISSUE TITLE
Tutorial for differential privacy

### ISSUE THREAD

**Issue by harora** [OpenMined/PySyft#2416]
Hi 

Is there any standalone demo/tutorial for Differential privacy on a mnist/cifar dataset? The only one I see has both federated learning and differential privacy. I'm new to the platform.

**Comment by kamathhrishi** [comment]
@harora Its in progress https://github.com/OpenMined/PySyft/pull/2183 , there is a bug in computing privacy loss which I have to yet resolve. Apart from that, it's a good enough PATE example.

**Comment by kamathhrishi** [comment]
I am not sure if I have made some mistake or not, the problem is I am getting very high epsilon values than it should be.
