### ISSUE TITLE
Local worker *me* not recognized by other workers when explicitly declared as crypto provider

### ISSUE THREAD

**Issue by aristizabal95** [OpenMined/PySyft#2426]
**Describe the bug**
Sharing a sent tensor between workers, and explicitly declaring the crypto provider as `sy.local_worker` causes the warning `Worker [worker_id] couldn't recognize worker me`. This warning causes problems when trying to execute get() on the sent, shared tensor, throwing an exception `AttributeError: 'str' object has no attribute 'id'`. Strange enough, this doesn't happen if `sy.local_worker` is implicitly assigned as crypto provider by not providing any crypto provider while sharing the tensor.

**To Reproduce**
Working script to demonstrate the problem.
```python
import torch as th
import syft as sy

hook = sy.TorchHook(th)

# Declare workers
alice = sy.VirtualWorker(id="alice", hook=hook)
bob = sy.VirtualWorker(id="bob", hook=hook)
jack = sy.VirtualWorker(id="jack", hook=hook)

# create a tensor
a = th.zeros(1).long()

# send the tensor
a = a.send(alice)

# share the tensor with me as an implicit crypto provider
a = a.share(bob, jack) # No warning is shown here

# get the shared tensor
a = a.get() # AdditiveSharingTensor returned, *crypto provider: me*

# Redeclare tensor
a = th.zeros(1).long()

# send the tensor
a = a.send(alice)

# share the tensor with me as an explicit crypto provider
a = a.share(bob, jack, crypto_provider=sy.local_worker) 
# W0801 11:56:01.096644 4346246592 base.py:577] Worker alice couldn't recognize worker me

# get the shared tensor
a = a.get() # AttributeError: 'str' object has no attribute 'id'
```

**Expected behavior**
There should be no difference between implicit and explicit declaration of the local worker as crypto provider.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - Version `syft==0.1.19a1`

**Additional context**
A similar script can be seen inside `syft/frameworks/torch/crypto/securenn.py`, for example in `_shares_of_zero()` declaration:
```python
def _shares_of_zero(size, field, crypto_provider, *workers):
    """
    Return n in [0, max_value-1] chosen by a worker and sent to all workers,
    in the form of a MultiPointerTensor
    """
    u = (
        torch.zeros(size)
        .long()
        .send(workers[0])
        .share(*workers, field=field, crypto_provider=crypto_provider, **no_wrap)
        .get()
        .child
    )

    return u
```
and causes errors when trying to run functions inside `securenn.py` while using tensors without explicit declaration of a crypto provider. This assigns `crypto_provider` to the local worker, and gets explicitly assigned as crypto provider in the line `.share(*workers, field=field, crypto_provider=crypto_provider, **no_wrap)`.

**Comment by iamtrask** [comment]
Very interesting bug - I do wonder how deep this bug goes. Is the local worker listed in bob._known_workers?

**Comment by aristizabal95** [comment]
@iamtrask the local worker is not recognized by any of the virtual workers.
```python
print(alice._known_workers)
# => {'alice': <VirtualWorker id:alice #objects:10>, 'bob': <VirtualWorker id:bob #objects:14>, 'jack': <VirtualWorker id:jack #objects:12>}
# The results are the same for bob and jack
```

**Comment by aristizabal95** [comment]
@iamtrask I'm seeing two problems here:
1. VirtualWorkers are not recognizing the local worker.
2. letting the class `AdditiveSharingTensor` assign the default crypto_provider to local_worker behaves differently as explicitly assigning it to local_worker.

As of 1:
when declaring a new worker, the `_known_workers` dict is populated by copying `sy.hook.local_worker._known_workers`. If we run this script
```python
import torch as th
import syft as sy

hook = sy.TorchHook(th)
hook.local_worker._known_workers
# => {}
```
returns an empty dictionary, which means that `hook.local_worker` is not aware of itself, which explains why any other worker won't recognize it. I'm guessing this should be another issue by itself?

As of 2.
I still don't get it, if I don't assign a crypto_provider, then it gets automatically assigned as `sy.hook.local_worker`, which should behave the same as explicitly assigning it to the same value. Any ideas?

**Comment by aristizabal95** [comment]
PR #2431 fixes this problem. So I'm going to close this issue.
