### ISSUE TITLE
The WebSocketServer could be prone to a DoS attack

### ISSUE THREAD

**Issue by amit-rastogi** [OpenMined/PySyft#2428]
**Describe the bug**
The WebSocketServer could be prone to a DoS attack from a malicious script

**To Reproduce**
1. Start a websocketserver using run_websocket_server.py --port 8777 --id alice 
2. Create a client script which calls WebsocketClientWorker to connect to the websocketserver created above in a loop say 100000 times
3. Now start another client script which tries to connect to the above server using WebsocketClientWorker and tries sending a tensor to the remote worker
4. This client script in step 3 cannot perform any operations since it appears to hang due to DoS.

**Expected behavior**
This client script in step 3 should be able to perform its operations.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by iamtrask** [comment]
Does it work after 1 time? I *think* WebSocketServer only allows one client to connect.

**Comment by amit-rastogi** [comment]
Yes it works after 1 time. So i think it shouldn't be an issue then.
One question though, cannot see the objects of a remote socket worker using for e.g. "bob._objects". Is this for security reason?
