### ISSUE TITLE
Tensors remain in server memory if websocketclient connection closes abruptly  

### ISSUE THREAD

**Issue by amit-rastogi** [OpenMined/PySyft#2442]
**Describe the bug**
Tensors remain in websocket server memory if websocket client connection closes abruptly 

**To Reproduce**
1. Start the websocket server "run_websocket_server.py --port 8777 --id alice"
2. Start a websocketclient and connect on port 8777 using id="alice".
3. Send a tensor to alice on the socket created in step 2. 
4. Close the client abruptly.
5. Check on the websocketserver console. The "WebSocket connection created in step 2 gets closed"
4. Connect another websocketclient to port 8777 and use any random id say "some_random_id"
5. Now call "some_random_id.list_objects_remote()" on the websocket created in step 4
6. Tensors sent to alice on the websocket in step 3 are clearly visible to this client with "some_random_id". 

**Expected behavior**
When socket connection gets closed all the tensors in server memory sent on that connection should be removed if any. This would ensure that if a websocket client closes abruptly due to network issues, etc its private tensors should not remain on the server which could be retrieved by any other client which connects to the server on the same port later. 

 - OS: Windows 10

**Comment by iamtrask** [comment]
This is an important feature - but it requires user auth to know the difference between the same user re-connecting and another user re-connecting, which means this is more a feature for https://github.com/OpenMined/Grid

@IonesioJunior - I believe you'll be working on a user, based system. This is an important characteristic!
