### ISSUE TITLE
Add "disable_garbage_collection" and "enable_garbage_collection" flags to native.py

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2444]
**Is your feature request related to a problem? Please describe.**
By default, when we delete a pointer to a tensor, it sends a command to the remote worker telling it to delete the thing being pointed to automatically.

This is a GREAT default, BUT, sometimes we want to turn it off. Currently it's quite cumbersome. Let's say we have a tesnor.

x = th.tensor([1,2,3,4,5])

...and we send it to someone

x_pointer = x.send(bob)

...if we want Bob to KEEP that tensor even when we delete our pointer, we have to do this....

x_pointer.child.garbage_collect_data = False

This is cumbersome... it would be better if we could just do

x_pointer.disable_garbage_collection

In fact, it would be even BETTER if this flag returned ```self``` allowing us to do

x_pointer = x.send(bob).disable_garbage_collection

It would also be convenient to have a shorthand version

x_pointer = x.send(bob).disable_gc

AND to also have a specific parameter we can update

x_pointer = x.send(bob)
x_pointer.gc = False
x_pointer.garbage_collection = False

**Comment by iamtrask** [comment]
For reference on how this is implemented, the implementation of a "description" feature was very similar, which you can see here.

https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/tensors/interpreters/native.py#L93

The whole project should be doable by only changing native.py (see the link above)

**Comment by Shashankjain12** [comment]
Hey @iamtrask can you assign me this issue.!?

**Comment by hanare** [comment]
@iamtrask I have created a PR can you please review it ?
https://github.com/OpenMined/PySyft/pull/2445

**Comment by hanare** [comment]
@iamtrask  This issue can be closed.

**Comment by iamtrask** [comment]
Thank you!
