### ISSUE TITLE
Move create_sandbox function

### ISSUE THREAD

**Issue by jvmancuso** [OpenMined/PySyft#2446]
There's currently a `create_sandbox` function in the main syft namespace that automates some boilerplate and sets up an environment for experimentation.

While this is a nice feature to have, it certainly should not live in the `syft/__init__.py` file.  I propose moving this to a `sandbox.py` file (or similar) and importing it from there.

**Comment by Ankit-Dhankhar** [comment]
@jvmancuso  I would like to take on this issue :)

**Comment by jvmancuso** [comment]
Go for it! Please link the PR to this issue when you've submitted it :)

**Comment by Ankit-Dhankhar** [comment]
@jvmancuso  we can close this issue :)

**Comment by jvmancuso** [comment]
Nice work!

In the future, you can include "Closes <issue number>" or "Fixes <issue number>" in the description of a PR to automatically close linked issues, which is a good practice :)
