### ISSUE TITLE
Unexpected behavior with AutogradTensors in remote workers

### ISSUE THREAD

**Issue by andrelmfarias** [OpenMined/PySyft#2447]
**Describe the bug**
Transforming a remote tensor into an `AutogradTensor` with `.share(*workers, requires_grad=True)` creates an `AutogradTensor` that points to a `Wrapper` instead of the opposite, as it should be expected. We want this to behave correctly as our objective is to work with data in remote servers (i.e. remote tensors) and do encrypted training using MPC with this data.

**To Reproduce**
The code below:
```
t = torch.Tensor([3]).send(bob) # t is a remote tensor located at the remote worker Bob
t = t.fix_precision().share(alice, jon, crypto_provider=crypto_provider, requires_grad=True)
t.get()
```

Gives this output:
```
AutogradTensor>(Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
    -> [PointerTensor | me:48986511531 -> alice:2051851770]
    -> [PointerTensor | me:48878799575 -> jon:38113753813]
    *crypto provider: crypto_provider*
```

**Expected behavior**
When working with local tensors and sharing them for MPC with autograd we have a `Wrapper` at the top
```
t = t.fix_precision().share(alice, jon, crypto_provider=crypto_provider, requires_grad=True)
t
```
```
(Wrapper)>AutogradTensor>FixedPrecisionTensor>[AdditiveSharingTensor]
    -> [PointerTensor | me:78465969403 -> alice:24923297626]
    -> [PointerTensor | me:39395163768 -> jon:22928149946]
    *crypto provider: crypto_provider*
```

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.4
 - Version `syft==0.1.22a1`

**Comment by meandmymind** [comment]
Actually I can still see the issue. I'm on the latest version of `dev` branch.
![Uploading image.png…]()
