### ISSUE TITLE
Add "force_delete()" method to Object Pointers (including TensorPointer)

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2448]
In some environments the garbage collector doesn't actually collect your objects, even when you call "del my_obj". This can be annoying when trying to tell a remote worker to delete an object. Thus, it would be very nice to have a couple of overrides, one on the object itself... which should work something like this.

Let's say I have a pointer
```
x_ptr = th.tensor([1,2,3,4,5]).send(bob)
```
I want to be able to force Bob to delete it by going.
```
x_ptr.force_delete()
```

This will require adding a new function to https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/pointers/object_pointer.py and to native.py.

It would also be nice to have the same function on the worker, so we could altenratively do.

```bob.force_delete(x_ptr)```

or equivalently

```bob.force_delete(x_ptr.id)```

**Comment by shashigharti** [comment]
I would like to take this issue

**Comment by murarugeorgec** [comment]
Is the issue and the description still up to date?

**Comment by Av01** [comment]
If this issue has not been assigned to anyone, can I work on it?

**Comment by agarwalmanvi** [comment]
Is this still open?

**Comment by sachin-101** [comment]
@iamtrask I would like to take up this issue.

**Comment by sachin-101** [comment]
I went through the code and found a method similar to the one mentioned by you. 
Link: https://github.com/OpenMined/PySyft/blob/0561a5d21c1787afeeb9753a0487f0c91d38a07d/syft/generic/object_storage.py#L93
I also noticed that this issue occurs while working in jupyter notebook. So, if you need any more functionalities to be implemented, let me know.

**Comment by iamtrask** [comment]
Anyone can work on this issue. @sachin-101 it looks like no-one has begun work. Feel free to jump in.

In the future it's better to simply say "I'm working on it" and then immediately create a 'work in progress" PR so we can see your current status. This also allows people to collaborate with you.

**Comment by iamtrask** [comment]
That method is similar but it's on the worker. We need am method on a
PointerTensor :)

**Comment by Kritikalcoder** [comment]
I'm working on it
