### ISSUE TITLE
Fix import issues

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2461]
Fix TODO https://github.com/OpenMined/PySyft/blob/06ce023225dd613d8fb14ab2046135b93ab22376/syft/frameworks/torch/hook/hook.py#L617

Fix TODO https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/tensors/interpreters/autograd.py#L242

Fix TODO
https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/tensors/interpreters/additive_shared.py#L912

Fix TODO
https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/tensors/interpreters/abstract.py#L158

Fix TODO
https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/tensors/interpreters/multi_pointer.py#L195

Fix TODO https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/tensors/interpreters/precision.py#L613

**Comment by LaRiffle** [comment]
This has been fixed
