### ISSUE TITLE
Add get_copy parameter to object_pointer get method

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2474]
Fix TODO https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/pointers/object_pointer.py#L125

**Comment by bhadreshpsavani** [comment]
May i work on this issue?

**Comment by karlhigley** [comment]
[Current location](https://github.com/OpenMined/PySyft/blob/1f05bd9babd552f4fc40545c71303dc624c0c132/syft/frameworks/torch/pointers/object_pointer.py#L125) of the comment above.

**Comment by karlhigley** [comment]
@bhadreshpsavani, it looks to me like the `deregister_ptr` param is doing basically this, as you pointed out. `get_copy` would probably be a clearer name for the param though, so might still be worth changing.
