### ISSUE TITLE
generate_triple in base.py

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2475]
**Describe the bug**
Cryptography logic is inside of the generic worker class, which is not a proper decoupling of messaging infrastructure from cryptography protocols.

**To Reproduce**
Visit... https://github.com/OpenMined/PySyft/blob/dev/syft/workers/base.py#L825

**Expected behavior**
This method should instead live in a new file syft/frameworks/torch/crypto/beaver.py as a method called "request_triple" where you also pass in the worker you'd like to request the triple from.

**Comment by Yugandhartripathi** [comment]
I would like to work on it.

**Comment by Yugandhartripathi** [comment]
@iamtrask please review
