### ISSUE TITLE
Clean up operation at native.py#L297

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2487]
Fix TODO https://github.com/OpenMined/PySyft/blob/6c3f9303eeeebae42f575e47e77907e4f747395d/syft/frameworks/torch/tensors/interpreters/native.py#L297

**Comment by bhadreshpsavani** [comment]
I want to work on it but could not understand what exactly we need to clean up, Can you help me?

**Comment by gmuraru** [comment]
@LaRiffle do you want to create the ```cmd``` in a simple way?

**Comment by karlhigley** [comment]
Ah, sorry, I think I addressed the issue that this comment highlighted in #2951, which addressed a security issue in this code.
