### ISSUE TITLE
Can't  create TFEwokers and  predict

### ISSUE THREAD

**Issue by baishanca** [OpenMined/PySyft#2493]
Describe the bug
I followed the tutorial step by step but I couldn't get the results，and my tf-encrypted is already meet the requirement

Expected behavior
As the tutorials13c

Screenshots
![bug](https://user-images.githubusercontent.com/50005467/62834165-36ecd200-bc7b-11e9-9b48-accd265a7cd3.png)

Desktop 
 - OS: windows10
 - 1903

![bug](https://user-images.githubusercontent.com/50005467/62834165-36ecd200-bc7b-11e9-9b48-accd265a7cd3.png)

**Comment by jvmancuso** [comment]
Hi @baishanca can you explain a bit more what you're experiencing?  I'm not sure I see the problem based on what you've written here.  What exactly is different from the expected behavior?

**Comment by baishanca** [comment]
Sorry, maybe the screenshot I uploaded doesn't display correctly. I will
write down follow the issue.
Attached is the screenshot of the program running results☺

jvmancuso <notifications@github.com> 于2019年8月14日周三 上午2:45写道：

**Comment by baishanca** [comment]
WARNING: Logging before flag parsing goes to stderr.
W0814 10:20:17.627083 10880 secure_random.py:22] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow (1.14.0). Fix this by compiling custom ops.

W0814 10:20:18.362116 10880 deprecation_wrapper.py:119] From D:\Anaconda\envs\pytorch\lib\site-packages\tf_encrypted\session.py:28: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0814 10:20:34.427498 10880 deprecation_wrapper.py:119] From D:\Anaconda\envs\pytorch\lib\site-packages\tf_encrypted\tensor\native.py:403: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0814 10:20:34.518264 10880 deprecation_wrapper.py:119] From D:\Anaconda\envs\pytorch\lib\site-packages\tf_encrypted\config.py:300: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0814 10:20:34.519479 10880 deprecation_wrapper.py:119] From D:\Anaconda\envs\pytorch\lib\site-packages\tf_encrypted\config.py:87: The name tf.GraphOptions is deprecated. Please use tf.compat.v1.GraphOptions instead.

I0814 10:20:34.520223 10880 session.py:57] Starting session on target 'grpc://localhost:4000' using config graph_options {
}

**Comment by jvmancuso** [comment]
These messages are expected when running the TFEWorkers in a terminal. The
predictions and results happen in the notebooks. If you can follow the
notebook instructions carefully and report any deviations from expected
behavior, please post them here, otherwise I will be closing this issue.

**Comment by baishanca** [comment]
Well, thank you all very much. I'll try notebook
