### ISSUE TITLE
Optimize Message Detailing and Simplification

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2512]
**Is your feature request related to a problem? Please describe.**
At present, most of our Message types use a simple/default simplification/detailing process. It's very likely that this is calling simplify() and detail() on objects which are already simple enough (which is not very efficient).

**Describe the solution you'd like**
For each TODO marked with this issue inside of syft/messaging/message.py, see if you can find the optimal detail and simplify method for each message type.

**Describe alternatives you've considered**
It's possible they're already optimal./

**Additional context**
You should run a benchmark on performance to double check your improvements actually translate into a speed increase.

**Comment by kakirastern** [comment]
Has anyone started working on this issue? If not, can I take this on?

**Comment by kakirastern** [comment]
I will work on it anyways then... Hopefully no doubly duplicated efforts.

**Comment by suhacker1** [comment]
@kakirastern Hi. Are you still working on this?

**Comment by kakirastern** [comment]
@suhacker1 No, not anymore.

**Comment by karlhigley** [comment]
@suhacker1 We're in the process of migrating from msgpack to Protobuf in part to improve performance, so optimizing msgpack might not make sense any more. Happy to help you get started working on Protobuf if you want though.

**Comment by duynht** [comment]
@karlhigley Have we had an open issue for that? I would love to try.

**Comment by karlhigley** [comment]
See OpenMined/syft-proto#35 for details on the Protobuf effort.
