### ISSUE TITLE
Move ObjectPointer, ObjectWrapper, and CallablePointer

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2517]
**Is your feature request related to a problem? Please describe.**
There are three files/classes inside of torch/pointers which are not specific to PyTorch and should be instead moved outside of the torch framework folder. 

- https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/pointers/callable_pointer.py
- https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/pointers/object_wrapper.py
- https://github.com/OpenMined/PySyft/blob/dev/syft/frameworks/torch/pointers/object_pointer.py

One good home for this could be syft/generic but I'll leave that up to you.

**Comment by jvmancuso** [comment]
@yanndupis is already working on this one in relation to #2502

**Comment by jvmancuso** [comment]
oh wait, this should actually be closed by #2502
