### ISSUE TITLE
Inline Documentation Consistency

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#252]
User Story: As a regular Contributor to OpenMined's PySyft repository, I want documentation to follow a consistent format to ease my use of the platform. Presently, this is not the case.

Acceptance Criteria:
• a defined template for inline documentation
• modifying PySyft repositories to conform to this template (particularly math.py and tensor.py which are highly irregular)

**Comment by CT83** [comment]
Assuming Documentation like that of equal(TensorBase,TensorBase) in tensor.py is expected. I am on  it !

**Comment by drewvolpe** [comment]
@CT83 I would recommend we use an existing style for docstrings. The two most popular ones are Google style and Numpy style. Both are well-supported by Sphinx and tools like PyLint and Jedi. Given we're using Numpy in various parts of the code, I would vote for NumPy style.

http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

**Comment by iamtrask** [comment]
@CT83 very excited about this!!!!

**Comment by CT83** [comment]
I don't know if you guys know, but you guys were featured here! https://youtu.be/HAC6sqq7_-U?t=7m13s 
I was interested, excited and wanted to help.

**Comment by CT83** [comment]
I don't really know how this works but I worked on one of the two files and I am done; 
https://github.com/OpenMined/PySyft/pull/273 Let me know if what I did was, what was expected and I will do the math.py File too. If not I am open to Advice  :)

**Comment by momonala** [comment]
Hey! I'm new to Openmined and this seems like an issue I can tackle. How can I help?

**Comment by CT83** [comment]
@iamtrask @drewvolpe https://github.com/OpenMined/PySyft/pull/273 I have completed tensor.py should I start with math.py? in the same way?

**Comment by bharathgs** [comment]
@CT83 *tensor.py* looks great, I think you can start off with *math.py*.
