### ISSUE TITLE
Update Automatically the Docker Hub using GitHub Actions

### ISSUE THREAD

**Issue by meandmymind** [OpenMined/PySyft#2528]
**Original issue** 
Docker container https://hub.docker.com/r/openmined/pysyft-notebook is 2 months old. Some parts of the project has changed a lot (e.g. Plan), so tutorials don't work as expected.

**Updated**
Same error found in #2939

We should update the container automatically when we merge to master using github actions

Example of this is done here:
https://github.com/arkhn/fhir-pipe/blob/master/.github/workflows/main.yml

**Comment by linamnt** [comment]
Hi I would like to work on this if no one else has started.
