### ISSUE TITLE
Test send operation inside a plan

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2539]
Make tests for using send inside a plan, the test will be something like:

```python
@sy.func2plan([th.Size((2,3))])
def plan_double_abs(x):
    x = x.send(bob)
    x = x + x
    x = th.abs(x)
    return x

ptr_result = plan_double_abs(th.zeros(3))
assert type(ptr_result, sy.PointerTensor)
result = ptr_result.get()
assert torch.equal(result, th.tensor([2., 2., 2.]))
```

**Comment by LaRiffle** [comment]
This has been discussed today @iamtrask @cereallarceny 
With the version of master of today I can run:
```python
@sy.func2plan([th.Size((3,))])
def plan_double_abs(x):
    x = x.send(bob)
    x = x + x
    x = th.abs(x)
    return x

ptr_result = plan_double_abs(th.ones(3))
assert isinstance(ptr_result.child, sy.PointerTensor)
result = ptr_result.get()
print(result)
assert torch.equal(result, th.tensor([2., 2., 2.]))
```
What could be not working as expected?

**Comment by cereallarceny** [comment]
@LaRiffle to the best of my memory, this doesn't simplify in Serde to include the send command.  Because of that, syft.js will have no idea to send the tensor.  I remember you, me, and @iamtrask had an issue simplifying the send command a while back.

Is this no longer the case?

**Comment by LaRiffle** [comment]
You're right it must be more tricky, i think the code I gave is not appropriate to observe the error which indeed is still there

**Comment by iamtrask** [comment]
This is because we need to add msg.OBJ to the messages tracked by the plan trace. Right now it’s only msg.CMD

**Comment by cereallarceny** [comment]
@LaRiffle Do we have any timeline for this in PySyft?

**Comment by LaRiffle** [comment]
We don't have anyone working on this currently unfortunately at the moment, but as soon as someone picks it we'll be good!

**Comment by PlamenHristov** [comment]
Maybe I can take a look at this?

**Comment by cereallarceny** [comment]
🙏🙏🙏

**Comment by karlhigley** [comment]
This will likely be addressed by current @OpenMined/syft-core-team work to refactor the remote execution primitives. Currently looks like `send()` operations will only be allowed in `Protocols`.
