### ISSUE TITLE
Federated Learning in two different machine 

### ISSUE THREAD

**Issue by hubuwx** [OpenMined/PySyft#2544]
as above，I can not find doc about this 
if i want to train model between two different machine by using pysyft , what should i check the configuration. Could you Please give  me some suggestions? Thanks a lot!

**Comment by LaRiffle** [comment]
Could you detail how your usecase differ from the tutorials please? Thanks!
https://github.com/OpenMined/PySyft/tree/dev/examples/tutorials

**Comment by DanyEle** [comment]
It should be sufficient to use two web sockets running on two separate machines.

**Comment by LaRiffle** [comment]
Agreed, I'm closing this because it has not been active for 1 month
