### ISSUE TITLE
Memory leakage in FederatedDataLoader

### ISSUE THREAD

**Issue by wentaiwu92** [OpenMined/PySyft#2553]
**Describe the bug**
Memory consumption by Syft keeps increasing when loading data in each epoch after another, causing an enormous memory usage in case of a large number of training epochs.

**To Reproduce**
Simply iterating through a FederatedDataLoader without doing any training can reproduce. Code example
```
# begin an epoch of training
for batch_id, (inputs, labels) in enumerate(fedDataLoader):
    # inputs, labels = inputs.to(dev), labels.to(dev)  # data to device
    # do nothing
    pass
# for MNIST, memory usage goes up by roughly 100MB after each and every epoch (even though no loss compute/propagation conducted).
```

**Expected behavior**
1. Memory keeps being increasingly consumed until the program stops. It reaches 30+GB usage in my case where I set many rounds of epochs.
2. Manual memory release (e.g., **gc.collect()** or **del**) is to no avail.

**Screenshots**
 Of course u will get a MemoryError finally after a long-enough run.
![image](https://user-images.githubusercontent.com/46561082/63648494-6b0acd00-c728-11e9-81a5-c1741ff96540.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python 3.7
 - PyTorch 1.1.0
 - PySyft 0.1.24a1

**Additional context**
I guess the reason behind may relate to the **multiple references** to each batch of data - observed by using sys.getrefcount() that shows a count >= 3, meaning that there is at least one ref to this batch data remaining even after the end of an iteration. Perhaps the problem is with the sy.VirtualWorker or the FederatedDataLoader because they could hold references to data.

**Comment by Y-Xu** [comment]
Hi, @wentaiwu92, I also encountered the same problem, and I have tried to clear_objects() all the data distributed to different virtual worker every time after each epoch and then reload the data, but it didn't work. The memory still increased along with the training iterations. Did you get any solution?

**Comment by wentaiwu92** [comment]
Hi, @Y-Xu. Unluckily no solution yet, _clear_objects()_ doesn't work probably means that there is one or more references (to the batch data) remained somewhere we don't know even though you attempt to release one from the virtual workers.

Only thing that I can do is to avoid too many epochs in one run.

I hope the leak problem could be noticed by the developers of this repo.

**Comment by Y-Xu** [comment]
@wentaiwu92 ，this bug also got in the way of using much more data residing on each virtual machine to train the local model. Now I convinced myself to treat this as a forced computing constraint in practice.

**Comment by Thobo5** [comment]
Hi there, has anyone found a fix for this issue yet? 

Syft 0.2.9 still has this issue and it's causing me to use huge amounts of RAM. Using tracemalloc I've found that the id's referring to Syft objects generated while iterating over a federated data loader are stored indefinitely. It can only be removed from memory by resetting the kernel.

Tracemalloc report:
`\syft\generic\id_provider.py:41: size=32.0 MiB (+28.0 MiB), count=1 (+0), average=32.0 MiB`
`\syft\generic\id_provider.py:7: size=20.4 MiB (+16.3 MiB), count=669505 (+535602), average=32 B`
