### ISSUE TITLE
.federate() does not work with torchvision's ImageFolder dataset

### ISSUE THREAD

**Issue by edgarinvillegas** [OpenMined/PySyft#2554]
**Describe the bug**
When you try to federate a `torchvision.datasets.ImageFolder`, you get the custom exception AttributeError("Could not find inputs in dataset")

**To Reproduce**

1) Have the following file structure locally:
```
+-- dataset
|   +-- class1
|   |   +-- whatever1.jpg
|   |   +-- whatever2.jpg
```
Those jpgs can be any image of at least 256x256 size.

2) Run: 
```
import torch
from torchvision import datasets, transforms
import syft as sy  

hook = sy.TorchHook(torch)  
bob = sy.VirtualWorker(hook, id="bob")  
alice = sy.VirtualWorker(hook, id="alice")

imagefolder_dataset = datasets.ImageFolder(root='./dataset/', transform = transforms.Compose([
        transforms.Resize(size=256),
        transforms.CenterCrop(size=224),
        transforms.ToTensor()
    ]))


fed_dataset = imagefolder_dataset.federate((bob, alice)) # Raises exception
```

**Expected behavior**
`fed_dataset` should be created without raising any exception

**Actual behavior**
An exception "Could not find inputs in dataset" is raised:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-21c009d642db> in <module>
      7 
----> 8 fed_dataset = imagefolder_dataset.federate((bob, alice))
      9 

c:\...\syft\frameworks\torch\federated\dataset.py in dataset_federate(dataset, workers)
    148             dataset.data = dataset.test_data
    149         else:
--> 150             raise AttributeError("Could not find inputs in dataset")
    151     if not hasattr(dataset, "targets"):
    152         if hasattr(dataset, "train_labels"):

AttributeError: Could not find inputs in dataset
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
 - torchvision: 0.3.0
 - pytorch: 1.1.0
 - pysyft: 0.1.22a1

**Workaround**
Before calling `.federate()` you can create the following dummy fields to prevent the exception:
`imagefolder_dataset.data = imagefolder_dataset.targets = True`

**Comment by edgarinvillegas** [comment]
Created PR to fix this: https://github.com/OpenMined/PySyft/pull/2555

There is harmful defensive code (that I removed) on `dataset_federate` function. It was checking for the data/train_data/test_data/targets/train_labels/test_labels fields in the dataset in a mandatory way. Which is not needed, and it's causing an exception that shouldn't exist.
What matters is that on each iteration of the dataset, it has to return a tuple in the form (data, target), which ImageFolder complies.
With the fix, `ImageFolder` and other datasets with the same problem now can be federated with `.federate()`

@iamtrask can you please review?

**Comment by gmuraru** [comment]
@edgarinvillegas are you still working on the PR?

**Comment by aditya-malte** [comment]
Hi,
Is this issue sorted because I'm facing the same on the PyPi version
Thanks

**Comment by ChedidJM** [comment]
Hello,
I have a class that inherits the Dataset class, but I can't apply the .federate() method on an instance of this class. Can someone explain why?
Thank you.

class UCI_HAR(Dataset):
    def __init__(self, samples, labels):
        self.samples = samples
        self.labels = labels
        
    def __getitem__(self, index):
        sample, target = self.samples[index], self.labels[index]
        return sample, target

    def __len__(self):
        return len(self.samples)

**Comment by tudorcebere** [comment]
Hello @ChedidJM , thank you for reporting this bug,

Could you please provide:
1. full script to reproduce the bug.
2. stack tracke/logging if you have any.
3. OS and syft version.

Thank you!
