### ISSUE TITLE
Argmax on encrypted  data fails

### ISSUE THREAD

**Issue by mzenk** [OpenMined/PySyft#2556]
The argmax-call on an encrypted tensor throws an exception. Minimal code example for reproduction:
```
import torch
import syft as sy
hook = sy.TorchHook(torch)

alice = sy.VirtualWorker(hook, 'alice')
bob = sy.VirtualWorker(hook, 'bob')

a = torch.arange(6)
enc_a = a.share(alice, bob)
print(enc_a.argmax())
```
Executing this script results in a `KeyError: 'Object "44504679185" not found on worker!!!You just tried to interact with an object ID:44504679185 on <VirtualWorker id:alice #objects:36> which does not exist!!!`

My python environment (Ubuntu 18.04):
torch 1.1.0
syft 0.1.24a1

**Comment by LaRiffle** [comment]
This should work :)
Add a crypto_provider and call fix_precision() 

```python
import torch
import syft as sy
hook = sy.TorchHook(torch)

alice = sy.VirtualWorker(hook, 'alice')
bob = sy.VirtualWorker(hook, 'bob')
crypto_provider = sy.VirtualWorker(hook, 'crypto_provider')

a = torch.arange(6).fix_precision()
enc_a = a.share(alice, bob, crypto_provider=crypto_provider)
print(enc_a.argmax())
```

**Comment by mzenk** [comment]
Thank you! I checked that both modifications are necessary to fix the problem.

**Comment by mzenk** [comment]
I assumed that I did not need fix precision encoding on an integer tensor. The need for an explicit crypto provider wasn't clear to me either. Could you explain on both?

**Comment by LaRiffle** [comment]
So actually you should have to do it, even if it doesn't raise an error: even if you work with integers, fix precision elements are in a field while integers are not, so it is a  best practice. And actually for some reason it doesn't work if you don't do it (argmax does smthg strange)
Same for crypto provider, it should be possible to not explicitoit,  but it doesn't work for some reason :/
