### ISSUE TITLE
resnet50 not supported when torch 1.0.1 / 1.1 is hooked 

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2562]
```
import torch
import syft
hook = syft.TorchHook(torch)
import torchvision.models as models

def make_model(num_out_classes: int):
    """Load a resnet50 and add a new head to it."""
    model = models.resnet50(pretrained=True) 
    num_ftrs = model.fc.in_features
    model.fc = torch.nn.Linear(num_ftrs, num_out_classes)
    return model

model = make_model(7)
model(torch.zeros(torch.Size([1, 3, 224, 224])))
```

Error:

```
...
~/PySyft/syft/frameworks/torch/hook/hook.py in overloaded_func(*args, **kwargs)
    745                 handle_func_command = TorchTensor.handle_func_command
    746 
--> 747             response = handle_func_command(command)
    748 
    749             return response

~/PySyft/syft/frameworks/torch/tensors/interpreters/native.py in handle_func_command(cls, command)
    336             # in the execute_command function
    337             if isinstance(args, tuple):
--> 338                 response = eval(cmd)(*args, **kwargs)
    339             else:
    340                 response = eval(cmd)(args, **kwargs)

~/PySyft/syft/frameworks/torch/tensors/interpreters/native.py in <module>

AttributeError: module 'torch._C._nn' has no attribute 'native_avg_pool2d'
```
---
torch version 1.0.1 and 1.1
syft dev version

**Comment by andrelmfarias** [comment]
Weird... I don't think there is a `native_avg_pool2d` in Pytorch, only `avg_pool2d`. Did you try to load the model without hooking torch?

Maybe the hook changes the name of the method...

**Comment by marcusvlc** [comment]
@mari-linhares  For some reason, the command created by the native.py file for the avg_pool2d layer looks like this:

syft.local_worker.hook.torch._C._nn.native_avg_pool2d

While the max_pool2d looks like this:

syft.local_worker.hook.torch.nn.functional.native_max_pool2d

I am still trying to understand why this particular layer is being called from torch._C and not torch.nn, but for practical testing purposes, I just created an if to change avg_pool2d's command to conform to that of max_pool2d, and it worked normally. I was able to load networks like ResNet and MobileNet.

To fix it, simply open the native.py file and change the construction of the cmd variable to the following:

if (cmd.split (".") [- 1] == 'avg_pool2d'):
                cmd = 'syft.local_worker.hook.torch.nn.functional.native_avg_pool2d'
            else:
                cmd = (
                    "syft.local_worker.hook."
                    + ".". join (cmd.split (".") [: - 1])
                    + ".native_"
                    + cmd.split (".") [- 1]
                )

Then just run python setup.py install again to overwrite the library with your change. I will try to propose a solution that is not unique to avg_pool, but for now this will work.

**Comment by robert-wagner** [comment]
To me this looks like we are hooking _C._nn after we are hooking torch.nn.functional. In my opinion we should not be hooking _C._nn at all which might solve this problem

**Comment by gmuraru** [comment]
@mari-linhares should we close this issue since currently we are on torch 1.4
