### ISSUE TITLE
PyTorch -> Tensorflow Eager and Tensorflow Eager -> PyTorch Wrapper Tensor Types

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2563]
**Is your feature request related to a problem? Please describe.**
Often we will have algorithms implemented in one framework which are not implemented in another. 

**Describe the solution you'd like**
Build a bridge tensor type between pytorch and tensorflow which allows us to automatically leverage each other's algorithms. 

The bulk of the work here is creating a tensor type which overloads tensor methods in such a way that a high level API in one framework correctly executes in the other framework.

One way this API could work is...

```
x = torch.Tensor([1,2,3,4,5.0]).fix_precision().tensorflow()

y = x + x

# y is now a tensorflow tensor wrapping a fixed precision pytorch tensor.
```

**Comment by kamathhrishi** [comment]
I could give it a try :)

**Comment by kamathhrishi** [comment]
A good starting point would be to create a torch tensor, call .TensorFlow() and show arithmetic and logical operations?

**Comment by kamathhrishi** [comment]
Arlight then, I might task quite sometime before begin to do this so if anybody else is interested they can work on this.
