### ISSUE TITLE
Could not find a version that satisfies the requirement torch>=1.0.1 (from syft) (from versions: 0.1.2, 0.1.2.p

### ISSUE THREAD

**Issue by colin-byrneireland** [OpenMined/PySyft#2574]
**Describe the bug**
A clear and concise description of whI am using a windows machine, with anaconda navigator I installed as per the instructions given in the readme.md

created an enviornment named pysyft and activated it
initialized pip install syft
The error mentioned above is displayed
I am Udacity Student for Secure and Private AI

![syfterror](https://user-images.githubusercontent.com/44531236/63923638-c7c6fa00-ca3e-11e9-93f1-49671b3dc71f.png)

The issue seems to me that torch 1.2 (latest) isn't compatible with syft ?, & You can't get torch 1.1 for windows.

Current Versions:
Windows 10
Base Env: torch                  1.2.0+cpu
torchvision                        0.4.0+cpu

Second Env:
torch        1.0.1

Both giving the same dependency error from syft torch 1.1.

Even if I follow https://pytorch.org/get-started/locally/ and install particular versions of torch on windows I still get the same error. 

ie conda install pytorch-cpu torchvision-cpu -c pytorch or 
# Python 3.7
pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl
pip3 install torchvision

Any ideas welcome. 
Does pysyft work with windows and if so how do I rectify the torch 1.1 error ?

**Comment by MarterLee** [comment]
I meet the same error, I think “torch==1.1” in requirements.txt case this bug, however there is no version 1.1, it mast be 1.1.0  for the mark "==". I change the  requirements.txt and install it. it's running well.

**Comment by LaRiffle** [comment]
Closing this as we now support torch>=1.3

**Comment by colin-byrneireland** [comment]
Thanks, much appreciated.

**Comment by hadisyekta** [comment]
Hi 
I am struggling with torch, cuda and syft!

for using cuda I need torch> 1.11, but syft is noy=t compatible with that!

pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Requirement already satisfied: torch in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (1.10.0)
Requirement already satisfied: torchvision in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (0.12.0+cu113)
Requirement already satisfied: torchaudio in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (0.11.0+cu113)
Requirement already satisfied: typing-extensions in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from torch) (4.0.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from torchvision) (9.0.1)
Requirement already satisfied: numpy in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from torchvision) (1.21.4)
Collecting torch
  Using cached https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp38-cp38-win_amd64.whl (2186.1 MB)
Requirement already satisfied: requests in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from torchvision) (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from requests->torchvision) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from requests->torchvision) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from requests->torchvision) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hizadi\fl\fl_avg_cae\env\lib\site-packages (from requests->torchvision) (2021.10.8)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 1.10.0
    Uninstalling torch-1.10.0:
      Successfully uninstalled torch-1.10.0
_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
syft 0.6.0 requires torch<=1.10.0,>=1.8.1, but you have torch 1.11.0+cu113 which is incompatible._
Successfully installed torch-1.11.0+cu113
