### ISSUE TITLE
OS and version details in ISSUE TEMPLATE- bug report

### ISSUE THREAD

**Issue by Ankit-Dhankhar** [OpenMined/PySyft#2592]
**Is your feature request related to a problem? Please describe.**
In issue template, it is asked to provide information about OS and version. It is a manual process and sometimes user may miss include important/conflicting libraries or add redundant information about version of other libraries on which PySyft doesn't depends.
 
**Describe the solution you'd like**
There should be a function like syft.show_versions() that output the OS information and only versions of those library on which PySyft depends. Similar to what is currently being done in [Pandas](https://github.com/pandas-dev/pandas/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by robert-wagner** [comment]
Hey @Ankit-Dhankhar This functionality is accomplished by either pip list or conda env list.

**Comment by Ankit-Dhankhar** [comment]
Yes but that also include other libraries that are not important for the given bug.
