### ISSUE TITLE
Tensor type error of SMS spam prediction with a GRU model

### ISSUE THREAD

**Issue by baishanca** [OpenMined/PySyft#2595]
Describe the bug
When I run the Federated SMS Spam prediction.py in advanced tutorials, it will go to handcrafted.py and show the tensor type error about :

''Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)''

Expected behavior
Which in tutorials actually

Screenshots
![image](https://user-images.githubusercontent.com/50005467/64407202-57f7e580-d0b6-11e9-9447-45d69426c17c.png)
![image](https://user-images.githubusercontent.com/50005467/64407234-6cd47900-d0b6-11e9-9789-13092a985289.png)

Desktop
windows 10

**Comment by niklausliu** [comment]
Me too, but I have no idea about this bug...

**Comment by DanyEle** [comment]
Running the code on Ubuntu 18.04 LTS, but not getting any error. It's training just fine.

**Comment by andrelmfarias** [comment]
I am running the tutorial on my macOS Mojave 10.14.4 and it's running without errors too.
