### ISSUE TITLE
Should tensors be part of the public API?

### ISSUE THREAD

**Issue by jvmncs** [OpenMined/PySyft#2600]
Right now, most tensors are exposed as `syft.TensorType`. This has the effect of speeding up development in that people developing new tensor types don't need to worry about circularity of tensor implementations as much (since they have access to other tensor types in the `syft` namespace). However, the hooking of syft-specific methods and the tensor chain abstraction together mean that these tensor types are essentially never used outside of the library internals.  This seems to be in the spirit of the original PySyft paper as well -- abstract away the complexity behind the scenes so that data scientists can focus on building layers/models.

We need to decide if these tensors should be a part of the main `syft` public API.  Note that excluding them here does not mean they can't inhabit their own self-contained submodule with a public API, similar to `syft.serde` -- it just means that they shouldn't be exposed as `syft.TensorType`.

P.S. We might want the result of this discussion to become an RFC.

**Comment by jvmancuso** [comment]
We need to clarify who the users of this tensor system are in order to make any decision about how public their API should be. Are data scientists/machine learning engineers expected to use these tensors? Are they PySyft contributors? Are they developers of other OpenMined projects and/or developers of ecosystem projects?

**Comment by LaRiffle** [comment]
That's an interesting point, but maybe we are a bit ahead of schedule. These tensors are currently all in the torch module `syft/frameworks/torch`, and there is still a bit of work in ordeer to make careful choices about which can live outside of it, as many of them are very unrelated to using pytorch. As soon as we have made these choices, I believe it would be good to remove them of the public API and have instead `sy.tensor.SyftTensor` or smthg like this.
We must keep in mind that there will be many developers for quite a bit of time here, so it's important to keep short and comprehensive paths.

**Comment by jvmancuso** [comment]
I agree we have quite some work to do, and I did not intend to suggest a timeline for this work.  But better to make the issue public now so people know this is an open question.

Also, *most* of the tensors are in `syft/frameworks/torch`. `PointerTensor` and `MultiPointerTensor` have already been moved into `syft/generic/pointers`.

**Comment by iamtrask** [comment]
Is anyone actually using the syft.<tensor type> ones? If it's only being used sparingly could we just move them to "torch.<tensor type>" instead?

**Comment by andrelmfarias** [comment]
Personally, I think will need to remove them from the public API in the future and have a unique public syft.tensor abstraction. TBH, and speaking from my experience, it's a bit of pain to get used to these kinds of tensors and understand their behavior. It can be an entry barrier for new users.
