### ISSUE TITLE
get_obj should raise a syft exception

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#2608]
Currently `worker.get_obj` raises a KeyError exception we should raise a syft specific exception like "ObjectNotFoundException".

This helps to avoid mistaking a regular/native python KeyError exception with exceptions raised by get_obj.

https://github.com/OpenMined/PySyft/blob/750bd2c3987a570ef1dc8554b933696d416724c7/syft/generic/object_storage.py#L84

**Comment by bhadreshpsavani** [comment]
I will work on this issue
