### ISSUE TITLE
method2plan is not supported anymore error in Introduction to plan part 08

### ISSUE THREAD

**Issue by OrhunKar** [OpenMined/PySyft#2615]
in Introduction to plan part 08 there is method2plan but it is not supported anymore

**To Reproduce**
Run 14th code cell in the tutorial

I was working on google colab

**Comment by LaRiffle** [comment]
Hey,
The tutorial has been updated, you should update your repo :)
https://github.com/OpenMined/PySyft/pull/2569/commits/36330ab3a7df7c874819b320071e3dc2a7252b4d
