### ISSUE TITLE
federated dataset with lazy loading

### ISSUE THREAD

**Issue by sunilsu** [OpenMined/PySyft#2616]
I have a large dataset and want to load only a batch of data at a time, for  training on each client. How can I create a federated dataset with this behavior? Could you point me to an example if one is available?

Thanks!

**Comment by sunilsu** [comment]
I was able to do that using train config (add_dataset to worker).

**Comment by NeuZhangQiang** [comment]
@sunilsu how do you implement the lazy loading by add_dataset? Could you please provide an example?
