### ISSUE TITLE
.squeeze(1) transforms autograd gradient to None

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2621]
**Describe the bug**
This bug is reported in #2618, where in the sample of code adding or remove .squeeze(1) make the gradient None or not.
Support should be added for this function in autograd.

**Comment by murarugeorgec** [comment]
@LaRiffle I think I can take this one, if you do not have another issue more urgent :)

**Comment by tudorcebere** [comment]
Is this still open?

**Comment by Kritikalcoder** [comment]
Is this issue still open? Can I take it up?
