### ISSUE TITLE
Microsoft Visual Studio 14.0 required error pops up while installing PySyft and VS 14.0 is already installed in system

### ISSUE THREAD

**Issue by dashitoishi23** [OpenMined/PySyft#2623]
**Installation bug**
I was trying to install PySyft from the Anaconda Command Prompt and an error popped up saying "Microsoft Visual Studio 14.0 required". The latest version is already installed in my system

**To Reproduce**
1. Create an environment in conda
2. try "pip install syft" and error popped up

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809
 - Python version: 3.7.4

**Comment by tallalj** [comment]
can you show the full error prompt you got in terminal?
