### ISSUE TITLE
Invalid registration on tensor when calling .fix_prec().share(...)

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2625]
**Describe the bug**
when calling .fix_prec().share(...), the fix precision tensor gets registered at the same place than the normal tensor:

**To Reproduce**
```python
import torch as th
import syft as sy

hook = sy.TorchHook(th)

alice = sy.VirtualWorker(hook, id="alice")
bob = sy.VirtualWorker(hook, id="bob")
charlie = sy.VirtualWorker(hook, id="charlie")

hook.local_worker.is_client_worker = False
me = hook.local_worker

x = th.tensor([1.0])
x_sh = x.fix_precision().share(alice, bob, crypto_provider=charlie)
me.get_obj(x.id)

#observed: (Wrapper)>FixedPrecisionTensor>tensor([1000])
```
**Expected behavior**
```expected: x = th.tensor([1.0])```

**Comment by sukhadj** [comment]
I would like to work on this issue. Can you please tell me from where I can start? Thanks.

**Comment by LaRiffle** [comment]
Will be fixed with #2627

**Comment by murarugeorgec** [comment]
Shouldn't we close this issue? (the other PR was merged)

**Comment by datason** [comment]
@gmuraru @LaRiffle 
Is this issue valid?
I am going to solve if yes)

**Comment by gmuraru** [comment]
Tried the code @LaRiffle used in the description:
```
me.get_obj(x.id)
```
Gives back: ```tensor([1.])``` so I think we can close this one.

@datason thank you for offering to solve this issue :)
