### ISSUE TITLE
Method __array__ method not producing an array 

### ISSUE THREAD

**Issue by tahirdev** [OpenMined/PySyft#2634]
**Describe the bug**
When running tutorial “Part 10 - Federated Learning with Secure Aggregation”, fix_precision() gives this error.

**To Reproduce**
Run this tutorial file: https://tinyurl.com/y6yfcn57
Error comes at "Part B: Encrypted Aggregation"

**Expected behavior**
Run without any error

**Screenshots**
<img width="1002" alt="Screenshot 2019-09-28 at 2 49 56 PM" src="https://user-images.githubusercontent.com/17920989/65848745-e3386400-e360-11e9-996f-b9da84eb9629.png">

**Desktop**
 - OS: MacOS
 - Version: 10.14.6
 - Syft Version: 0.1.27a1
 - Python Version: 3.7
 - Torch Version: 1.1.0

**Comment by yeggasd** [comment]
I have traced the error to be thrown when we are trying to do a ```np.abs()``` on ```self.clone().detach.numpy()```. I have not found a fix or workaround for this yet.

**Comment by hi-hi-there** [comment]
Hmm seems like can't work directly on the pointer, so I called a "get" on the pointer.
I'm new to this so if someone thinks this is wrong, do point it out! but for now this works: 

Under **part B**:
Change `fixed_precision_param = copy_of_parameter.fix_precision()`
to `fixed_precision_param = copy_of_parameter.get().fix_precision()`

and change `new_param = (spdz_params[0] + spdz_params[1]).get().float_precision()/2`
To `new_param = (spdz_params[0] + spdz_params[1]).float_precision()/2`

Now the code part B code should run. 

After this. you will need to do the same for the code under **Let's put it all Together!**:
Change `spdz_params.append(params[remote_index][param_i].copy().fix_precision().share(bob, alice, crypto_provider=james).get())`
To `spdz_params.append(params[remote_index][param_i].copy().get().fix_precision().share(bob, alice, crypto_provider=james).get())`

and change `new_param = (spdz_params[0] + spdz_params[1]).get().float_precision()/2`
To `new_param = (spdz_params[0] + spdz_params[1]).float_precision()/2`

This is my output :
![image](https://user-images.githubusercontent.com/55134531/66533580-ff4cba00-eb45-11e9-9ac9-1fd285c94f39.png)

**Comment by tahirdev** [comment]
@hi-hi-there As I understand it, if you use copy_of_parameter.get() you are basically bringing each user's parameters to the server and then applying fix_precision, which is wrong. We need to apply fix_precision on user's device (pointers) for correct secure aggregation.

**Comment by codebecker** [comment]
@tahirdev  is right using get at this point will bring the gradients to your local machine which should be strongly prohibited in secure aggregation. 

I worked around this error by not using a copy of the parameters for calculation. I guess it is nicer to copy them but it's also working this way. 

For the workaround just change this line:

`        # select the identical parameter from each worker and copy it
        copy_of_parameter = params[remote_index][param_i].copy()
`

to this line to avoid copying:

`        # select the identical parameter from each worker and copy it
        copy_of_parameter = params[remote_index][param_i]
`

**Comment by Sofiascope** [comment]
@codebecker I tried to delete the copy, the cell works but later I have an issue when I launch the train : 

![image](https://user-images.githubusercontent.com/38509329/67577617-1e9c3780-f741-11e9-878c-a945ec35fd83.png)

**Comment by flo257** [comment]
Could you resolve this issue? Cause I receive the same error

**Comment by csqray** [comment]
I fixed this problem by using spdz_params.append(params[remote_index][param_i].get().fix_precision().share(bob, alice, crypto_provider=james))
new_param = (spdz_params[0] + spdz_params[1]).get().float_precision()/2
