### ISSUE TITLE
handle_command_function doesn't use @overloaded.module for pure tensors

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2637]
**Describe the bug**
In native.py lives the changes made to the torch tensor
In particular, like other syft tensors, it has the following decorator @overloaded.module
```python
    @staticmethod
    @overloaded.module
    def torch(module):
        def roll(tensor, shifts, **kwargs):
            int_shifts = int(shifts.item())
            return torch.native_roll(tensor, int_shifts, **kwargs)

        module.roll = roll
```
and a class method handle_func_command which is supposed to call it to change some torch function behaviours (here torch.roll)
But this is not the case for pure torch tensors, you can check it by yourself
handle_func_command shoudl be fixed accordingly.

-----

EDIT: So basically if you run torch.roll(x) with x pure torch tensor, the overloading I've written **will** be applied,
However if now I run it on a wrapper (any torch.tensor with a child), it **won't** be applied.

**Comment by sukhadj** [comment]
I am interested to work on this issue.

**Comment by sukhadj** [comment]
@LaRiffle Can you please give an example of `handle_func_command` call? And also what is the significance of `handle_fun_command`? I am a little confused. Thank you.

**Comment by LaRiffle** [comment]
handle_command_function is called automatically when you call a torch function. Depending on the type of the args provided to the torch function, the `handle_command_function` of the appropriate class will be called (you can check that there is indeed one per Tensor type class).

The mechanism which handles this is in hook.py line 425

`native.py` is intended to extend the torch Tensor. But recall that torch Tensor can be used either to perform pure torch operation or as wrappers of syft tensors (in which case they are empty and act just as a small shell)
`handle_command_function`  should always check if the function called could not be replaced by an overloaded one, defined in the "@staticmethod"  def torch of the same class.
`handle_command_function` in native.py should make sure that overloaded functions are used in both cases (as native tensors or wrappers)
Now, this check is done in
```python
# Check that the function has not been overwritten
            try:
                # Try to get recursively the attributes in cmd = "<attr1>.<attr2>.<attr3>..."
                command = cls.rgetattr(cls, cmd)
                return command(*args, **kwargs)
            except AttributeError:
                pass
```
so you just have to put it out of the wrapper/non wrapper disjunction materialized by the `try / except PureFrameworkTensorFoundError` to have it work in bother cases

**Comment by murarugeorgec** [comment]
Is someone working on this issue? If not I can take it. Or @LaRiffle is there another issue that is more important, but also has a low level of difficulty?

**Comment by sukhadj** [comment]
Hey @murarugeorgec!! I am working on this issue. Unfortunately will require 1 or 2 days more to solve it!! 😃

**Comment by sukhadj** [comment]
Hey @LaRiffle, @murarugeorgec.
While testing the working of the code I made some changes and installed the pysyft again.
I made these changes:
```python
@staticmethod
    @overloaded.module
    def torch(module):
        def roll(tensor, shifts, **kwargs):
            print("Overloaded roll called")  #New Line
            int_shifts = int(shifts.item())
            return torch.native_roll(tensor, int_shifts, **kwargs)
        module.roll = roll  
```
And 

```python
def handle_func_command(cls, command):
        print("In handle func command") #New line
""" ... """
        except PureFrameworkTensorFoundError:  # means that it's not a wrapper but a pure tensor

            # Check that the function has not been overwritten
            try:
                print("Pure FrameworkTensor") #New line
                # Try to get recursively the attributes in cmd = "<attr1>.<attr2>.<attr3>..."
                command = cls.rgetattr(cls, cmd)
                return command(*args, **kwargs)
            except AttributeError:
                pass
```

Now when I run
 
```python
th.roll(x,2)
print(type(x))
```
The output is 

```
 In handle func command
 Pure FrameworkTensor
 Overloaded roll called
 <class 'torch.Tensor'>
```
**Isn't this working correctly? (Calling correct overloaded function for Pure torch Tensor)**

Moreover, 
When I try running on a wrapper (pointer after sending the tensor to the virtual worker)

x_sh = x.send(bob)
torch.roll(x_sh,2)

Its raising TypeError with the following output:
```
In handle func command
In handle func command
Pure FrameworkTensor
`````
` TypeError: roll() missing 1 required positional argument: 'shifts' `

Is this working normal?
Thanks.

**Comment by gmuraru** [comment]
@sukhadj is this issue still present?

**Comment by sukhadj** [comment]
I just checked!!
Correct overloaded functions are called for both pure torch tensors and wrapper tensor!!
So I guess this issue is resolved !!
