### ISSUE TITLE
Make default frameworks datasets searchable

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2663]
**Is your feature request related to a problem? Please describe.**
`.search()` currently returns datasets manually added to workers.
We could extend the functionality to retrieve popular datasets from the framework when no local result is found.

- PyTorch: `torchvision.datasets` https://pytorch.org/docs/stable/torchvision/datasets.html
- TensorFlow `tf.data.Datasets` https://www.tensorflow.org/datasets
- Numpy `sklearn.datasets` https://scikit-learn.org/stable/datasets/index.html

**Comment by robert-wagner** [comment]
I'm not sure I agree with this in the long run. While I think this is great behavior for learning to use the framework, I do not think it is good for when the framework is actually in use (IE I think that I would be very unhappy as a user if you suggested to me to run imagenet in a federated way when I could just run it locally)
