### ISSUE TITLE
Wrong printout  in workers' verbose mode

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/PySyft#2665]
Let me expalin this issue directly with code. In the following code:
```
import syft as sy
import torch

hook = sy.TorchHook(torch)

me = hook.local_worker
bob = sy.VirtualWorker(hook, id = 'bob')

bob.verbose = True
a = torch.ones((1,1)) 
a = a.send(bob) 
```
The last line will print the following since the worker `bob` is in verbose mode:
``` worker <VirtualWorker id:bob #objects:0> received OBJ tensor([[1.]])```

This printout makes since since `bob` received the sent tensor.

Now let's get the tensor back to the worker `me`:

```
a = a.get()
```

This prints out the following:

```
worker <VirtualWorker id:bob #objects:1> received OBJ_REQ 24165954888
```

Which is wrong, since it is the worker `me` who received the object, not `bob`.

**Comment by PlamenHristov** [comment]
Hey Alan,

I am new to the project. I think I might be able to do that?

**Comment by AlanAboudib** [comment]
Sure @PlamenHristov , got ahead :)

**Comment by PlamenHristov** [comment]
Just to give an update on the "progress". 
I've setup my environment with the example test above and am debugging through the code.

**Comment by AlanAboudib** [comment]
Great, let us know how it goes :+1:

**Comment by PlamenHristov** [comment]
@AlanAboudib , I think I got to the root of it and I don't think there is a problem with the code;
* The message printout is from here: https://github.com/OpenMined/PySyft/blob/e6ef7c205c7898e4401287791672a41947cf846b/syft/workers/base.py#L290

1. In the first case it says that bob received the **tensor** (`OBJ`), that is a -> tensor -> b
2. In the second printout the log says that bob received a **request for a tensor** (`OBJ_REQ`), that is me -> OBJ_REQ -> bob.

Here is the code where the owner sends the tensor request: https://github.com/OpenMined/PySyft/blob/e6ef7c205c7898e4401287791672a41947cf846b/syft/workers/base.py#L595

After that the tensor is correctly assigned to `a`

**Comment by PlamenHristov** [comment]
@LaRiffle, I believe we can close this issue ?

**Comment by AlanAboudib** [comment]
@PlamenHristov You are right. I missed that _REQ part, my bad. The issue (non-issue) is solved :+1:
