### ISSUE TITLE
Send tensor to worker bug

### ISSUE THREAD

**Issue by luggi961** [OpenMined/PySyft#2669]
**Describe the bug**
If you send a tensor to a worker and you don't save the apprioriate pointer, you get an empty response list using the search functionality.

**To Reproduce**

`import torch as th`
`import syft as sy`

`hook = sy.TorchHook(th)`

`bob=sy.VirtualWorker(hook, id="bob")`

`x = th.tensor([1, 2, 3]).tag('#dataset')`
`x.send(bob)`
`results = bob.search(['#dataset'])`
`pointer = results[0]`
`print(pointer)`

**Expected behavior**
Results list shouldn't be empty.

Server traceback:

`IndexError                                Traceback (most recent call last)`
`<ipython-input-2-33a97d2ca3b1> in <module>`
`      9 x.send(bob)`
`     10 results = bob.search(['#dataset'])`
`---> 11 pointer = results[0]`
`     12 print(pointer)`

`IndexError: list index out of range`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.7.4
 - PyTorch Version: 1.1.0 
 - PySyft Version: 0.1.29a1

**Additional context**
Using `x_ptr = x.send(bob)` instead of `x.send(bob)` works fine.

**Comment by murarugeorgec** [comment]
@luggi961 I tried to reproduce it, but it seems it got fixed.
Could you also retest it on the latest version?

**Comment by LaRiffle** [comment]
`send` is not inplace, you need to do: `p = x.send(bob)` instead of `x.send(bob)`
