### ISSUE TITLE
Send & Get datasets

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2670]
We can currently send and get tensors, we would like to have the ability to directly fetch datasets with all the data inputs and targets in an easy way.

## Things to do:
- [x] Change `sy.BaseDataset` to inherit from `AbstractObject` to have tagging and description and to be registrable by workers: this allows datasets to be referenced for the search functionality
- [x] Extend `BaseDataset` with a `simplify` and `detail` method (see other objects with a simplify and detail method like the `FixedPrecisionTensor` to understand the behaviour): this allows to send and receive datasets. (+ reference BaseDataset in serde.py just like FixedPrecisionTensor). **You need to update syft-proto as well**
- [x] Support pointing to BaseDataset: create a new type of Pointer for BaseDataset which inherits from `ObjectPointer` (get inspiration for example from `PointerProtocol`)
- [x] Add the .send() and .get() functionality to BaseDataset (for .send() you can get inspiration from `Protocol` and for .get() `native.py`)
- [x] Allow search of datasets in .search to fetch remote datasets: make sure the `BaseWorker.search` method correctly retrieve datasets

Each of this point can be addressed in a separate PR if needed.

**Comment by NovaVic** [comment]
Hi Theo,
I can take this one.
I see similar coding structure (with tag, description, simplify, detail methods etc.) in protocol.py file - so can to some extent imagine what the "things to do" are referring to but I think I still need more context as a new person on this.
Thanks in advance Theo!

**Comment by NovaVic** [comment]
Hi Theo @LaRiffle, Thanks for the updated description - that definitely helps! And yes I feel it would be better manageable if I can address change related to each of the points as separate PR.

You can assign it to me. Thanks Theo!

**Comment by LaRiffle** [comment]
Hi @NovaVic, any updates on how the project is going? :)

**Comment by Guillem96** [comment]
@LaRiffle any updates on this issue? If you want I can give it a try

**Comment by LaRiffle** [comment]
Please go ahead :)

**Comment by Guillem96** [comment]
@LaRiffle When I try to send a Dataset I get this error:

`syft.exceptions.UndefinedProtocolTypeError: syft.frameworks.torch.fl.dataset.BaseDataset is not defined in the protocol file`

Should I modify syst proto package too?

**Comment by LaRiffle** [comment]
> @LaRiffle When I try to send a Dataset I get this error:
> 
> `syft.exceptions.UndefinedProtocolTypeError: syft.frameworks.torch.fl.dataset.BaseDataset is not defined in the protocol file`
> 
> Should I modify syst proto package too?

Yes you should!

**Comment by AbinavRavi** [comment]
Hi, Is this issue available? If so can I work on it?
