### ISSUE TITLE
<worker>.torch

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2678]
**Is your feature request related to a problem? Please describe.**
At present we cannot initialize tensors on a remote machine. Whenever we want to initialize something, we first initialize it locally and then call .send() to move it to the remote machine. This is *extremely* wasteful in some cases such as.
```
# BEGIN boilerplate
import syft as sy
import torch as th
hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, id="bob")
# END boilerplate

#BEGIN code relevant to this github issue
x = th.rand(3,3).send(bob) # this i the wasteful part
#END
```

**Describe the solution you'd like**
Instead I'd like to be able to run

(skipping boilerplate)

```
x = bob.th.rand(3,3)
```
or alternatively
```
x = bob.torch.rand(3,3)
```

**Describe alternatives you've considered**

```
x = bob.rand(3,3)
```

**Additional context**
bob.torch should have the full pytorch API available for us to call, all of which simply executes on the remote machine.

**Comment by gmuraru** [comment]
I can take it - it would be a challenge, but will try to do it :)
