### ISSUE TITLE
BaseWorker(trust_level={trustworthy, honest_but_curious, malicious})

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2681]
**Is your feature request related to a problem? Please describe.**
At present we assume that all workers have the same relationship with each other and we talk about permissions only at the tensor level.

**Describe the solution you'd like**
When creating a connection to another worker, I would like to be able to *request* a certain trust level, which will affect what tensors I can see and what I will be able to do with them.
```
bob = sy.VirtualWorker("bob", requested_trust_level=sy.trust.Trusted)
bob = sy.VirtualWorker("bob", requested_trust_level=sy.trust.HonestButCurious)
bob = sy.VirtualWorker("bob", requested_trust_level=sy.trust.Malicious)
```
and if the trust level is GRANTED, it should just execute, but if the trust level is DENIED, then it should return a TrustLevelException.

Also, the trust level should show up as a parameter on the client.
```
bob.trust
````

**Describe alternatives you've considered**
Instead of requesting a trust level we could also explicitly specify what trust level they will have with us, but this seems far less intuitive to me.

**Comment by robert-wagner** [comment]
I think this is a great way to address this problem. We should probably use these trust levels at tensor creation time to avoid having to check them for every call (since that changes protocols). In practice it is just changing a default

**Comment by iamtrask** [comment]
I think we'd need to have at least some operations for every call, at the
very least to know what kinds of permissions to give the result tensor, no?
