### ISSUE TITLE
Plans Notebook is Broken

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2682]
**Describe the bug**
When I try to create a neural network plan, I get an error.

**To Reproduce**
Run this notebook: https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Part%2008%20-%20Introduction%20to%20Plans.ipynb

and you'll see:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-1df7f0407b15> in <module>()
----> 1 net = Net()

<ipython-input-14-87940bb14ced> in __init__(self)
      5         self.fc2 = nn.Linear(3, 2)
      6 
----> 7         self.add_to_state('fc1', 'fc2')
      8 
      9     def forward(self, x):

AttributeError: 'Net' object has no attribute 'add_to_state'
```

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Version 0.1.29a1

**Additional context**

**Comment by LaRiffle** [comment]
Fixed by https://github.com/OpenMined/PySyft/pull/2671
