### ISSUE TITLE
.fix_precision() and .share() should allow us to set an arbitrary precision

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2688]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to set non-standard precision. 

**Describe the solution you'd like**
I'd like the ability to set the precision I want when calling .fix_precision() or .share(). To that end, I'm also thinking we should go back to requiring people to call both .fix_precision().share() when sharing a float tensor. Otherwise we're hiding important functionality from the end user.

Updates should be made here: https://github.com/OpenMined/PySyft/blob/e6ef7c205c7898e4401287791672a41947cf846b/syft/frameworks/torch/tensors/interpreters/native.py#L647

And Here: https://github.com/OpenMined/PySyft/blob/e6ef7c205c7898e4401287791672a41947cf846b/syft/frameworks/torch/tensors/interpreters/native.py#L748

**Additional context**
This issue came from Slack<Christian Becker> who was getting seriously damaged accuracy when doing SMPC based secure aggregation because of the low precision.

**Comment by fdroessler** [comment]
I am happy to take this one.

**Comment by LaRiffle** [comment]
@iamtrask I think we already have this, you can do
`x.fix_precision(precision_fractional=5).share(alice, bob, crypto_provider=crypto)` 
And it works quite well
