### ISSUE TITLE
Allow worker registration of objects within python context

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2689]
**Is your feature request related to a problem? Please describe.**
Tons of test and code samples using plans are currently like this:

```python
hook.local_worker.is_client_worker = False
# my awesome code
hook.local_worker.is_client_worker = True
```

**Describe the solution you'd like**
```python
with self.owner.registration_enabled():
    # my awesome code
```

**Describe alternatives you've considered**
Enabling registration all the time :O

**Comment by murarugeorgec** [comment]
I can start looking at this one
