### ISSUE TITLE
Have Notebooks build as part of the test/CI process

### ISSUE THREAD

**Issue by fdroessler** [OpenMined/PySyft#2693]
**Is your feature request related to a problem? Please describe.**
In Slack one of the most common request for help or fixes is that the tutorial notebooks don't work. Either some new feature results in the need for the Notebook to be updated or other measures to be taken.

**Describe the solution you'd like**
Have the notebooks be build as part of the CI and testing pipeline to flag up early when something stops working.

**Describe alternatives you've considered**
Remain in status quo where experienced users need to answer the same questions over and over again in Slack.

I'll be working myself on this issue. I wanted to put up an issue for that as a reminder and as a reference for others.

**Comment by youben11** [comment]
Great idea! But how do you plan to flag malfunctioning notebooks?

**Comment by fdroessler** [comment]
I was planning on combining papermill with pytest and write them as tests that run in an isolated filesystem. That way I think it should be possible to get websocket notebooks tested too. By using papermill it should also allow for reducing the execution time by parameterising the notebooks (like epochs etc) although in that case some parameters will be set in the first cell. It's an idea so far I'll see how far I get.

**Comment by fdroessler** [comment]
@youben11 @iamtrask I have submitted a __very__ raw [WIP] PR just to check if where I am going is in line with your ideas. Let me know your initial thoughts on the approach.

**Comment by karlhigley** [comment]
Notebooks tests are now running as part of the test/CI process. 👍
