### ISSUE TITLE
WebsocketClientWorker:  TimeoutError:Connection timed out

### ISSUE THREAD

**Issue by csqray** [OpenMined/PySyft#2715]
I use "python run_websocket_server.py --port 8780 --id bob --host 10.0.0.5" on my Mac to run the run_websocket_server.py under the examples/tutorials/advanced/websockets-example-MNIST-parallel folder. And I want to connect it with Linux server. I import packages and run the following codes in ipython.
hook = sy.TorchHook(torch)
kwargs_websocket = {"host": "10.0.0.5", "hook": hook, "verbose": False}
bob = WebsocketClientWorker(id="bob", port=8780, **kwargs_websocket)
But it reports an error--TimeoutError: [Errno 110] Connection timed out
How could I solve this problem?
If possible, could you write a detailed document that implements federated learning on different computer devices? I sincerely hope there can be an example realized by different computers, but not all servers in one computer.

**Comment by LaRiffle** [comment]
Hi, does it work in local mode? (connected through the localhost)

Also, cross device computation will increasingly handled in PyGrid 
https://github.com/OpenMined/PyGrid

**Comment by csqray** [comment]
If both servers' "host" are "localhost", it is OK

**Comment by LaRiffle** [comment]
Interesting! So yes I _think_ Websocket with PySyft currently only work in local networks. You need to use PyGrid across devices, but maybe the PyGrid team can confirm

**Comment by csqray** [comment]
OK, thank you
