### ISSUE TITLE
distributed worker.

### ISSUE THREAD

**Issue by AmberrrLiu** [OpenMined/PySyft#2718]
Hi, I‘m new to pysyft. I was wondering if I have some workers on different machines(External clients) with different IP. Can I use sy.TorchHook? or what should  I use to do this.
Hope you can give me  some advice! Thanks!

**Comment by murarugeorgec** [comment]
Yes, you can do that.
There is a tutorial [here](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/advanced/websockets-example-MNIST)
