### ISSUE TITLE
failed to run "python setup.py test"

### ISSUE THREAD

**Issue by JOJO0966** [OpenMined/PySyft#2720]
1. python setup.py test
2. run error
 result:
_________________________________________________________________________ test_connect_close _________________________________________________________________________

hook = <syft.frameworks.torch.hook.hook.TorchHook object at 0x0000022268C0EC50>
start_remote_worker = <function start_remote_worker.<locals>._start_remote_worker at 0x0000022270C128C8>

    def test_connect_close(hook, start_remote_worker):
>       server, remote_proxy = start_remote_worker(id="fed-connect-close", hook=hook, port=8771)

test\workers\test_websocket_worker.py:188:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test\conftest.py:65: in _start_remote_worker
    server = _start_proc(WebsocketServerWorker, dataset=dataset, **kwargs)
test\conftest.py:27: in _start_proc
    p.start()

**Comment by LaRiffle** [comment]
Can you add details and fix the display? Some elements are missing to understand your problem
