### ISSUE TITLE
Error Saving tf.keras model with save_mode='tf'

### ISSUE THREAD

**Issue by noumanriazkhan** [OpenMined/PySyft#2721]
**Error Saving tf.keras model**
After training tf.keras model with TF Hub model as keray layer, it must be saved with TF Format. When I am getting model back from virtual worker, it has not been saving it with following error.

`NotFoundError: /tmp/tmpt_dyri7n/assets/tokens.txt; No such file or directory`

This is how I am doing this:
 
```
model_trained = bob.get_obj(model_ptr.id_at_location)
model_trained.save('./1234', save_format='tf')
```
Also `.get()` method is not working for me with same error.

**To Reproduce**
1. Simply train tf.keras
2. try model_pointer.get()
3. or model_pointer.save()

**Expected behavior**
It should be gotten back and save as tf format.

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [18.04 LTS]

**Comment by lc0** [comment]
@noumanriazkhan would you mind to attach / upload to colab your minimum reproducible example?
