### ISSUE TITLE
Can Pysyft sopport Cuda now?

### ISSUE THREAD

**Issue by CHOSEN24** [OpenMined/PySyft#2726]
I have tried to train MNIST example on GPU using my computer. But there always will be some questios, such as connectionError or not a remarkable boost towards runtime ,so this version Pysyft can use cuda?
I need your help, thanks guys.

**Comment by CHOSEN24** [comment]
add: I created some websocketclientes not virtualworkers

**Comment by LaRiffle** [comment]
I think there is ongoing work on this topic: https://github.com/OpenMined/PySyft/pull/2690

**Comment by midokura-silvia** [comment]
Yes, it should work now. See #2735.
