### ISSUE TITLE
Copy Paste Notebook Tutorials into Unit Tests

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2731]
**Is your feature request related to a problem? Please describe.**
Right now our tutorials (https://github.com/OpenMined/PySyft/tree/master/examples/tutorials) are often broken because they aren't a part of our testing suite.

**Describe the solution you'd like**
I would like one unit test for each notebook in the tutorials folder (except the ones in the "advanced" folder)

**Comment by midokura-silvia** [comment]
But how do make sure that the code doesn't diverge between notebook and unit test?

**Comment by srivastava41099** [comment]
I would love to write parts of it with @midokura-silvia if you are willing. Should we use Treon, Andrew or just unittest in separate files/notebooks?

**Comment by midokura-silvia** [comment]
See #2754

**Comment by LaRiffle** [comment]
I think https://github.com/OpenMined/PySyft/pull/2755 fix this
