### ISSUE TITLE
Benchmark FixedPrecision, LargePrecision and CRTPrecision

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2734]
We want to test in real context and benchmark our 3 methods to convert float to fixed precision integers (which are used when encrypting tensors).

We'd like to do this with model evaluation. For example, let's do this on a simple model trained on MNIST (maybe just a 3-layer MLP).

So the job is to train this model, and then convert its parameters to fixed precision using the 3 strategy we currently support: FixedPrecision, LargePrecision and CRTPrecision (see the `.fix_prec()` api to learn how to do it)

Then, benchmark the runtime for evaluation for each of them.

This benchmark would be super valuable for the Crypto team and would help find hidden bugs!

The output of this project would be a jupyter notebook in 5 parts:
1) training the model in clear
2) -3-4) converting to the 3 fix precision strategies and monitor runtime of the evaluation + accuracy
5) Compare strategy pros and cons

**Comment by refactormyself** [comment]
Hello @LaRiffle, I will like to take this issue as my first issue.

**Comment by LaRiffle** [comment]
Sure go ahead!

**Comment by NateSolon** [comment]
Hey @refactormyself are you still working on this? I think this would be a great project for where I'm at right now - maybe we could both take a stab at it and compare?

**Comment by NateSolon** [comment]
@LaRiffle does the model need to be trained with federated learning or can I just train a model with vanilla PyTorch and then test the different precisions?

**Comment by refactormyself** [comment]
I am working on it.
