### ISSUE TITLE
SPDZ with security against malicious adversaries

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2736]
We have support for SMPC protocol SPDZ in the honest but curious setting,

We'd like to support active security as an optional feature, as explained for example in the following paper: _Multiparty Computation from Somewhat Homomorphic Encryption, Damgard_ 
https://eprint.iacr.org/2011/535.pdf

**Comment by PlamenHristov** [comment]
Just to double check, to cover the active case a ZK proof implementation needs to be added, correct?
