### ISSUE TITLE
Reduce optimizer communication effort for better Performance

### ISSUE THREAD

**Issue by codebecker** [OpenMined/PySyft#2737]
**Is your feature request related to a problem? Please describe.**

When processing the batch for a remote worker (all hosted on the same notebook) i recognized that the operations `optim.zero_grad()` and ` optim.step() ` each take ~ 10% of the whole batch processing time. 
The reason they take so long is that both iterate through each parameter and compute one after another each with a own send request. 

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
14        20     796188.0  39809.4     13.5          optim.zero_grad()
15        20     149609.0   7480.4      2.5          batch_data = worker.data[int(batch * n_data_worker / n_batches): int((batch + 1) * n_data_worker / n_batches)]
16        20     141676.0   7083.8      2.4          batch_labels = worker.labels[int(batch * n_data_worker / n_batches):int((batch + 1) * n_data_worker / n_batches)]
17        20    3409367.0 170468.4     58.0          pred = worker.model(batch_data)  
18        20     421985.0  21099.2      7.2          loss = worker.criterion(worker.pred, batch_labels)  
19        20     138121.0   6906.1      2.3          loss.backward() 
20        20     567434.0  28371.7      9.6          optim.step() 
21        20     258509.0  12925.5      4.4          lossTotal += worker.loss.data 
```

**Describe the solution you'd like**

There must be a possibility to bundle all the operations necessary for both functions into a single send operation. Two solutions are possible as discussed with @LaRiffle they are quoted here:

> Hook optim to send the call ".zero_grad", like we hooked torch.nn for example. It makes sense but only works for Python workers having PyTorch, while we would like to support more generic interactions in the long run.
> 
> Use Plans for this: they cache all the sub operations and send all of them at once, which make the computation much faster! because ops are more low level it's better to communicate across several types of workers

**Describe alternatives you've considered**
Another (fast?) option could be to make the current sequential execution parallel. But the total number of send operations would stay the same and thus large (unnecessary?) overhead can't be avoided by this option.

**Additional context**
As mentioned above this example measurement was made with remote grid workers hosted on the machine the script was running at. Thus when using remote machines for each worker the operations would need even more time because of the higher latency. 

With the above assumption this change could have a huge performance impact in the general training process.

**Comment by iamtrask** [comment]
+1 to using plans here!
