### ISSUE TITLE
Convert dense matrix to sparse matrix

### ISSUE THREAD

**Issue by Ujjwal-9** [OpenMined/PySyft#274]
This would speed up my matrix multiplies.

**Comment by AkashGutha** [comment]
can you write down a use case just like @iamtrask does? that would help others understand the issue better.

**Comment by piyush2896** [comment]
By Conversion you mean.
**Converting**:
```
A =
    0     0   11
    22    0    0
    0    33    0
```

**to something like**
```
S =
    (2,1)   22
    (3,2)   33
    (1,3)   11
```

Am I right here?

**Comment by iamtrask** [comment]
That looks right to me!

**Comment by piyush2896** [comment]
@iamtrask so what do you suggest?
I think making a new class inheriting from tensorbase and having functionalities like matmul and others.

As in the current scenarios  all the functionalities are present in math.py and the only possibility that I see is either make changes in the code of math.py or make a separate class with separate functionalities.

**Comment by iamtrask** [comment]
I think that's the right thing to do. This also sounds very similar to PyTorch's sparse tensor implementation as well.

**Comment by bharathgs** [comment]
we can do this with [`scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html#module-scipy.sparse) and for the above specific format you can check [`scipy.sparse.csr_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix) so including this as a function in the *math.py* would probably be sufficient. Also, you might be interested in [this](https://github.com/pytorch/pytorch/issues/2885) and [this](https://discuss.pytorch.org/t/how-to-convert-a-dense-matrix-to-a-sparse-one/7809)

**Comment by piyush2896** [comment]
@bharathgs the second [link](https://discuss.pytorch.org/t/how-to-convert-a-dense-matrix-to-a-sparse-one/7809) you sent displays a limitation that -> The user needs to find the non zero indices to send and make sparse matrix..


```
dense = torch.randn(3,3)
dense[[0,0,1], [1,2,0]] = 0 # make sparse
indices = torch.nonzero(dense).t()
values = dense[indices[0], indices[1]] # modify this based on dimensionality
torch.sparse.FloatTensor(indices, values, dense.size())
```


I think it is redundant. What do you say?
I mean can't just the class (in the above case FloatTensor) getting the values modify the data to a sparse representation directly?

**Comment by bharathgs** [comment]
@piyush2896 as you must have seen from the first link, pytorch does not let you do this directly(yet), so you have to do something as shown in that example. I think this is a nice feature to have natively, and we could probably put it in _math.py_ .

**Comment by ivuckovic** [comment]
Hey guys, I'd like to join in and help if necessary.

**Comment by fmhall** [comment]
Has anyone taken the lead on this? I'd like to help too.

**Comment by iamtrask** [comment]
I don't get the impression anyone has claimed the leading role for this issue. @fmhall or @ivuckovic if you're interested go ahead and open up a branch (and drop the link here so we can all see it)

**Comment by ivuckovic** [comment]
I created branch on my fork https://github.com/ivuckovic/PySyft/tree/dense_to_sparse_matrix but haven't had time to do any changes, hopefully I'll start in next couple of days.

**Comment by Ujjwal-9** [comment]
yeh i was also looking forward to do it. But I've been very busy lately. 
Now i am free & would love to do it.😄

**Comment by ivuckovic** [comment]
I'm having problems with tests.
I'm trying to assert.Equal two numpy arrays that should be equal. They are both array(<2x2 sparse matrix of type '<class 'numpy.int64'>' with 1 stored elements in Compressed Sparse Row format>, dtype=object).
When I run test I get following error:
"E       AssertionError: array[60 chars]stored elements in Compressed Sparse Row format>, dtype=object) != array[60 chars]stored elements in Compressed Sparse Row format>, dtype=object)"

Any ides or suggestions how to solve this?
