### ISSUE TITLE
Single run_websocket_server.py file

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#2744]
**Is your feature request related to a problem? Please describe.**
Currently we have a ```run_websocket_server.py``` file in the root of the project, but also in different tutorials. I think we should have only one such file and the notebooks to import the needed functionality from it.

**Describe the solution you'd like**
Have only one ```run_websocket_server.py``` file in the top dir of the project.
The notebooks should import this module.

**Describe alternatives you've considered**
Move the file to a separate directory like ```start_websocket```

**Additional context**
This will reduce the complexity/size of the repository, reduce the points of failures.

**Comment by bhadreshpsavani** [comment]
May i work on this issue?

**Comment by LaRiffle** [comment]
Sure! I just assigned you :)

**Comment by bhadreshpsavani** [comment]
Today I analyzed the issue and here are my observations,

1. I have compared all the  `run_websocket_server.py` in a different directory, they don't contain the same code. 

2. I have also analyzed codebase and come to know that we also have one another file named `start_websocket_servers.py` file which is using `run_websocket_server.py` in the same directories in the tutorials.

I think that suggested changes will not be valid unless we make generalized `start_websocket_servers.py`  and  `run_websocket_server.py` files to solve this issue

@LaRiffle  shall we do it or keep it as it is right now?

**Comment by gmuraru** [comment]
Sorry for the late response. My opinion is that we should (in a way) unify some of the files.
One of the idea is to have a ```start_websocket_servers``` that could be parameterized and depending on one paramter start specific workers.
Eg:
   ```start_websocket_server --notebook mnist-parallel```` and this should start the set of workers for the ```MNIST-Parallel tutorial```.

What do you think @LaRiffle ?

**Comment by JameerBabu** [comment]
Is this issue free to work ? If so, please assign me @LaRiffle

**Comment by vineeth14** [comment]
Hey, I'd love to work on this issue

**Comment by JameerBabu** [comment]
@gmuraru It was assigned to me and I started working on it.

**Comment by JameerBabu** [comment]
@vineeth14 .. I am working on it .. please take some other issue.

**Comment by karlhigley** [comment]
Could whoever has code (even if it's partial or not working yet) push a WIP PR and link it to this issue? It's hard for the maintainers to tell whether people are still working on something unless we can see code being written. 😄

**Comment by JameerBabu** [comment]
@karlhigley then why there is a system which assigns to some one. If you could have told this well before, I wouldn't have waited. I could've started working on the day I requested.

**Comment by karlhigley** [comment]
We do try to use the assignment system to signal that an issue has been claimed. It's just that sometimes we assign an issue and whoever has claimed it gets busy with other things and never pushes code. It's not uncommon for an issue to be assigned to 2 or 3 people in sequence and still never end up with a PR. So, we tend to err on the side of having too many people working on something than too few.

If you want to signal to people that you're already working on something, the best way is to show your progress in a WIP or draft PR. That also opens it up for other people to build on your work or collaborate with you. 🤷‍♂

**Comment by vineetjai** [comment]
@karlhigley I started working on this. Assign it to me.

**Comment by karlhigley** [comment]
@vineetjai It looks like there are still duplicate `run_websocket_server.py` scripts in the `test/` and `test/scripts` directories.
