### ISSUE TITLE
error: invalid command 'udacity'

### ISSUE THREAD

**Issue by chenjinhua1993** [OpenMined/PySyft#2748]
**Describe the bug**
all the step before "python setup.py install udacity" is ok, 
when i input "python setup.py install udacity
", return error: invalid command 'udacity'

i have tried in win10 and google colab.
![image](https://user-images.githubusercontent.com/35960345/69206740-7c793f00-0b88-11ea-91b9-5adfd2057f84.png)
win10
![image](https://user-images.githubusercontent.com/35960345/69206793-b0ecfb00-0b88-11ea-8eac-f7e673370604.png)
colab

i follow the instructions in https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2001%20-%20The%20Basic%20Tools%20of%20Private%20Deep%20Learning.ipynb

**Comment by iamtrask** [comment]
@jvmancuso looks like your recent chang e(https://github.com/OpenMined/PySyft/commit/ef8a61b264819c4b5b0c830f0f1333aec20752d6) might havee issues on win10 and colab?

**Comment by iamtrask** [comment]
@chenjinhua1993, for now just leave off ```udacity``` until @jvmancuso replies.

**Comment by iamtrask** [comment]
(Also, @chenjinhua1993 - make sure you're on the latest master branch)

**Comment by chenjinhua1993** [comment]
Hi, yesterday , in win10 , i try "python setup.py install "  without "udacity", it works. At the same time, i  do it in the same fashion. But after this , i try "pip install syft " in colab. It works as well.Anyway, now i can use PySyft in my local desktop or colab. thanks for yours contributions!
