### ISSUE TITLE
Translate our tutorials to French

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2779]
At present, our tutorial notebook series is only available in English, but it would be very desirable for people to be able to learn PySyft in their native language, such as French.

For this PR, copy the current notebooks and translate the inline text to French, placing the notebooks in a "french" folder within the "tutorials" folder.

https://github.com/OpenMined/PySyft/tree/master/examples/tutorials

**Comment by TTitcombe** [comment]
As nobody has picked this up yet, I'll put my hat in the ring. I'm not a native speaker, however, so I might be better placed reviewing other people's PRs

**Comment by elBichon** [comment]
Hello, I am a native french speaker, I can take a look at it
