### ISSUE TITLE
Translate our tutorials to German

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2781]
At present, our tutorial notebook series is only available in English, but it would be very desirable for people to be able to learn PySyft in their native language, such as German.

For this PR, copy the current notebooks and translate the inline text to German, placing the notebooks in a "german" folder within the "tutorials" folder.

https://github.com/OpenMined/PySyft/tree/master/examples/tutorials

**Comment by JulianSprung** [comment]
I will start working on this issue and translate Part 01

**Comment by 1firstml3** [comment]
I would like to start working on this by translating Part 02

**Comment by nvw1** [comment]
Hi, I am a native speaker and would be happy to help out and translate further parts. What is the current state?

**Comment by vineetjai** [comment]
@iamtrask I had opened pull request #3144 for Tutorials in german please review it.
