### ISSUE TITLE
Translate our tutorials to your native language!

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2782]
At present, our tutorial notebook series is only available in English, but it would be very desirable for people to be able to learn PySyft in their native language

For this PR, copy the current notebooks and translate the inline text to a language you know, placing the notebooks in a <language-name> folder within the "tutorials" folder.

https://github.com/OpenMined/PySyft/tree/master/examples/tutorials

Rules of Thumb:
- Only translate English which is in the notebook or generated from code in the notebook. Any English which is coming from the PySyft library itself (such as error messages) should remain in English.

**Comment by ricardopretelt** [comment]
I can start right now with the translation to spanish as it is my native languange, if anyone else wants to contribute can contact me

**Comment by iamtrask** [comment]
Make sure to collaborate with these folks too - submit one tutorial at a time via pull reequesets to minimize the chance of double work. https://github.com/OpenMined/PySyft/issues/2775

**Comment by ricardopretelt** [comment]
ok thanks, already coordinated with @arturomf94

**Comment by wonderit** [comment]
@iamtrask 
Could you please open an issue for Korean also? As a fan of this project, I would like to participate in this issue.

**Comment by ricardopretelt** [comment]
@wonderit I think that anyone can open the issue, just for convenience use the same format as the others and the labels translation, good first issue and feature

**Comment by fdroessler** [comment]
In order to avoid cluttering of the "root" tutorials directory my suggestion would be to have all translations in a`examples/tutorials/translations/` subdirectory. I have done this for some of the notebook tests already and suggested it in the PRs for Korean, Espanol and Romanian. If this is not opposed by the maintainers I would make this a more general suggestion?

**Comment by iamtrask** [comment]
Sounds great!

**Comment by ricardopretelt** [comment]
I have the 3rd tutorial translated to spanish, but we need the previous parts merged with the new updates to do a new PR avoiding version conflicts

**Comment by adilnaut** [comment]
I will translate to Russian, dm me if you want to collaborate!

**Comment by Metrix1010** [comment]
I can translate into French although not my native language (I'd be using nbTranslate).
DM me to collaborate.

I need some clarification for this task.

Are we:
1. Creating a hard copy of the tutorials folder translated into a specified language?
2. Updating the main installation file to require each user to install nbTranslate to self select language?
3. Both?

Thanks :)

**Comment by KyloRen1** [comment]
@adilnaut If you don't mind, I would also like to translate to Russian. I suppose you have already started with Part01. So I will start translating 2 and so on.

**Comment by thefirebanks** [comment]
@arturomf94 @ricardopretelt I would love to collaborate with the translation to Spanish as well!

**Comment by arturomf94** [comment]
@thefirebanks sure! :) send me a DM on Slack.

**Comment by ucalyptus** [comment]
@iamtrask Bengali is my native and has the 5th largest speaker base in the world. 
https://github.com/OpenMined/PySyft/pull/2938 for Part One

**Comment by Carwinyr** [comment]
@iamtrask 
I can start the translation to Turkish. Is it possible to open an issue for this?

**Comment by abhi9716** [comment]
@iamtrask, I would like to translate it into Hindi.

**Comment by aakankshadhurandhar** [comment]
@iamtrask , I would like to translate tutorial to Hindi. Let me know if this issue is still open.

**Comment by mehra-deepak** [comment]
@iamtrask i would like to translate the tutorials to Hindi , Please Let me know if the issue is still open!!

**Comment by karlhigley** [comment]
See #2774 for information on the Hindi translation effort. Many of the tutorials [have already been translated](https://github.com/OpenMined/PySyft/pulls?utf8=%E2%9C%93&q=is%3Apr+Hindi).

**Comment by TemitopeOladokun** [comment]
@iamtrask  Can I translate this into Pidgin?

**Comment by XuebinMa** [comment]
@iamtrask  I would like to translate the tutorials into Chinese, please open a new issue if it is possible.

**Comment by isthatdebbiej** [comment]
@iamtrask I would like to work on translation to Tamil.

**Comment by UtkarshChaurasia** [comment]
Can I translate readme of tutorials to into Hindi? @iamtrask
