### ISSUE TITLE
fix_prec() doesn't work for crt or large

### ISSUE THREAD

**Issue by NateSolon** [OpenMined/PySyft#2784]
**Describe the bug**
Converting a model to fixed precision doesn't work for LargePrecision or CRTPrecision.

**To Reproduce**
1. Run tutorial Part 11 - Secure Deep Learning Classification up to `model.fix_precision().share(alice, bob, crypto_provider=crypto_provider)`
If you're planning to run multiple tests, you may want to save the model and reload it as it can take awhile to train.
2. Change the parameters to `model.fix_prec(storage='crt')` or `model.fix_prec(storage='large')`

**Expected behavior**
Convert the model parameters to the specified precision strategy.

**Screenshots**
`model.fix_prec(storage='crt')`

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-25-e8fb399cdba4> in <module>()
> ----> 1 model.fix_prec(storage='crt').share(alice, bob, crypto_provider=crypto_provider)
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py in module_share_(nn_self, *args, **kwargs)
>     613             """Overloads fix_precision for torch.nn.Module."""
>     614             # TODO: add .data and .grad to syft tensors
> --> 615             if module_is_missing_grad(nn_self):
>     616                 create_grad_objects(nn_self)
>     617 
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py in module_is_missing_grad(model)
>     543             """Checks if all the parameters in the model have been assigned a gradient"""
>     544             for p in model.parameters():
> --> 545                 if p.grad is None:
>     546                     return True
>     547             return False
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py in grad(self)
>     343 
>     344             if hasattr(self, "child"):
> --> 345                 to_return = self.child.attr("grad")
>     346                 if to_return is not None and isinstance(to_return.child, PointerTensor):
>     347                     if to_return.child.is_none():
> 
> AttributeError: 'CRTPrecisionTensor' object has no attribute 'attr'

`model.fix_prec(storage='large')`

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-15-c2e4c0429286> in <module>()
> ----> 1 model.fix_prec(storage='large').share(alice, bob, crypto_provider=crypto_provider)
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py in module_fix_precision_(nn_self, *args, **kwargs)
>     630 
>     631             for p in nn_self.parameters():
> --> 632                 p.fix_precision_(*args, **kwargs)
>     633 
>     634             return nn_self
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in fix_prec_(self, *args, **kwargs)
>     721         """
>     722         # We specify id to make sure the inplace op doesn't change the tensor id
> --> 723         self.child = self.fix_prec(*args, no_wrap=True, id=self.id, **kwargs)
>     724         self.is_wrapper = True
>     725         return self
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in fix_prec(self, storage, field_type, no_wrap, *args, **kwargs)
>     687             fpt_tensor = (
>     688                 syft.LargePrecisionTensor(*args, **kwargs)
> --> 689                 .on(self, wrap=False)
>     690                 .fix_large_precision()
>     691             )
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/large_precision.py in fix_large_precision(self)
>     184 
>     185     def fix_large_precision(self):
> --> 186         self.child = self._create_internal_representation()
>     187         return self
>     188 
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/large_precision.py in _create_internal_representation(self)
>      71     def _create_internal_representation(self):
>      72         """Decompose a tensor into an array of numbers that represent such tensor with the required precision"""
> ---> 73         self_scaled = self.child.numpy() * self.base ** self.precision_fractional
>      74 
>      75         # floor is applied otherwise, long float is not accurate
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/generic/frameworks/hook/hook.py in overloaded_native_method(self, *args, **kwargs)
>     379                 except BaseException as e:
>     380                     # we can make some errors more descriptive with this method
> --> 381                     raise route_method_exception(e, self, args, kwargs)
>     382 
>     383             else:  # means that there is a wrapper to remove
> 
> ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/syft/generic/frameworks/hook/hook.py in overloaded_native_method(self, *args, **kwargs)
>     376 
>     377                 try:
> --> 378                     response = method(*args, **kwargs)
>     379                 except BaseException as e:
>     380                     # we can make some errors more descriptive with this method
> 
> RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14.5

**Comment by sukhadj** [comment]
Is this issue still open? If yes, I can work on it.

**Comment by karlhigley** [comment]
@sukhadj There's [an open PR](https://github.com/OpenMined/PySyft/pull/2982) that removes both of these classes. I'll leave this issue open until that PR gets merged, but probably not worth trying to fix the issue as described.
