### ISSUE TITLE
train_config.model_ptr.get() returns ObjectWrapper instead of ScriptModule

### ISSUE THREAD

**Issue by ammarvoloder** [OpenMined/PySyft#2788]
Steps to reproduce: 

1. Follow Federated Learning with TrainConfig
2. Create the worker, send the model to it
3. Get the model back with the function model_ptr.get() or with .get_model()
4. Pass the newly trained model to the train_config in order to send it to another worker
5. Exception ObjectWrapper has no attribute 'parameters'. 

I don't know if this is a defect or not, but I could not find a tutorial on how to update train_config with the already trained model (or how to update our initial model with the values from the new one)? 
Thanks.

Best regards

**Comment by karlhigley** [comment]
I'm not entirely sure how to fix that, but I think ScriptModules get bundled into an ObjectWrapper when sent to another worker. The ScriptModule inside an ObjectWrapper should be accessible via `wrapper.obj`.
