### ISSUE TITLE
Broken backprop from given gradient

### ISSUE THREAD

**Issue by H4LL** [OpenMined/PySyft#2789]
**Describe the bug**
The bug occurs when performing backprop from a given gradient when the gradient and variable are held on a remote host. 

**To Reproduce**
I have made two notebooks. One demonstrates what should [what should be happening](https://github.com/blockpass-identity-lab/PySyft/blob/dev/examples/experimental/Split%20Neural%20Network/Simple-VanillaSplitNN-NoPySyft.ipynb).

The other demonstrates [what happens when I try to do this function on a worker](https://github.com/blockpass-identity-lab/PySyft/blob/dev/examples/experimental/Split%20Neural%20Network/Simple-VanillaSplitNN.ipynb)

**Desktop:**
 - OS: Im using MacOS Catalina
 - Version 10.15

**Comment by gmuraru** [comment]
Hey @H4LL.

It is working now? What was the problem? :)

**Comment by H4LL** [comment]
The backward function was not on the list of ambiguous methods so the vesrion of backward() that i needed was not cached. Fixed though by this commit; https://github.com/OpenMined/PySyft/pull/2799
