### ISSUE TITLE
No module named 'syft.frameworks.torch.fl'

### ISSUE THREAD

**Issue by ticlazau** [OpenMined/PySyft#2796]
Hello,

when running the example:
'Federated learning with websockets and federated averaging.ipynb'

I am getting this error at very beginning: 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-720bf18bab2b> in <module>
      5 from torchvision import datasets, transforms
      6 
----> 7 from syft.frameworks.torch.fl import utils

ModuleNotFoundError: No module named 'syft.frameworks.torch.fl'

Any ideas?

**Comment by abdulbasitds** [comment]
you need to import like  `from syft.frameworks.torch.federated import utils`

**Comment by LaRiffle** [comment]
Which version of syft are you using? In the latest one it should be working... Tell me if it doesn't

**Comment by abdulbasitds** [comment]
Thanks for replying @LaRiffle , I am using version `syft==0.2.0a2`, I just used `pip install syft` and I believe its latest?

**Comment by ticlazau** [comment]
Here is my output:

pi@rasp-m:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.3.0a0+de394b6
>>> import syft as sy
>>> print(sy.__version__)
0.2.0a2
>>>

**Comment by ticlazau** [comment]
The change "from syft.frameworks.torch.federated import utils" must be done on run_websocket_client.py file as well. 
However, if the change is done, in the run_websocket_client.py we get the following error:
python3 run_websocket_client.py
Traceback (most recent call last):
  File "run_websocket_client.py", line 284, in <module>
    main()
  File "run_websocket_client.py", line 222, in main
    alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket)
  File "/home/pi/.local/lib/python3.7/site-packages/syft/workers/websocket_client.py", line 50, in __init__
    self.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/syft/workers/websocket_client.py", line 62, in connect
    self.ws = websocket.create_connection(**args)
**AttributeError: module 'websocket' has no attribute 'create_connection'**

This is connected to:
def main():
    args = define_and_get_arguments()

    hook = sy.TorchHook(torch)

    if args.use_virtual:
        alice = VirtualWorker(id="alice", hook=hook, verbose=args.verbose)
        bob = VirtualWorker(id="bob", hook=hook, verbose=args.verbose)
        charlie = VirtualWorker(id="charlie", hook=hook, verbose=args.verbose)
    else:
        kwargs_websocket = {"host": "localhost", "hook": hook, "verbose": args.verbose}
        alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket)
        bob = WebsocketClientWorker(id="bob", port=8778, **kwargs_websocket)
        charlie = WebsocketClientWorker(id="charlie", port=8779, **kwargs_websocket)

Any ideas?

Thx,
FM

**Comment by ticlazau** [comment]
@abdulbasitds is working 👍 
replace: "from syft.frameworks.torch.fl import utils"
with
"from syft.frameworks.torch.federated import utils"

**Comment by ShivaBadaja** [comment]
@LaRiffle It does not work in the official docker image provided

**Comment by karlhigley** [comment]
The Docker image is out of date. We’re working on getting updates published.

**Comment by jdohea** [comment]
I am seeing the same issue still with the openmined/pysyft-notebook image. I am also using the code "syft.frameworks.torch.federated"
