### ISSUE TITLE
Send (or not) Autograd Tensor

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2797]
**Is your feature request related to a problem? Please describe.**
Currently, sending/getting Autograd tensors cause an error because grad_fn is added to the args serialize which is not possible.

**Alternative solutions**
A. Either we want to serialize AutogradTensor and we A.1 remove the grad_fn arg or A.2 add serialization for all the grad_fn components or B. We don't want AutogradTensor to be sent across the wire and we raise an explicit error

**Describe the solution you'd like**
We need to serialize grad_fn for AutogradTensor. To do so, one needs to understand how grad_fn is built up in PySyft and how the components should be serialized is an easy way (= try avoiding modifying syft/serde too much)

This triggers weird errors like: https://github.com/OpenMined/PySyft/issues/2666

**Comment by LaRiffle** [comment]
Related to: https://github.com/OpenMined/PySyft/issues/2137

**Comment by iamtrask** [comment]
We should allow autograd tensor to be sendable across the wire, but we should serialize the functions using a string version of them (with specific ones whitelisted) instead of serializaing any function at all.

CC: @karlhigley this is related to what you were talking about.

**Comment by sukhadj** [comment]
Can I work on this?

**Comment by adityaprabhat01** [comment]
is this issue still open?

**Comment by karlhigley** [comment]
Looks like this got resolved in #2871.

**Comment by sachin-101** [comment]
@LaRiffle Please close this issue if it is resolved.
