### ISSUE TITLE
Folded Split Neural Network run with three machines

### ISSUE THREAD

**Issue by ProfXGiter** [OpenMined/PySyft#2839]
**Describe the bug**
Machine B show the bug: 
Worker me couldn't recognize worker alice
Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /"syft package path"/lib/python3.6/site-packages/syft/workers/websocket_server.py:95> exception=AttributeError("'str' object has no attribute '_recv_msg'", )>

Machine C show the bug: 
Websocket connection closed (worker: bob)
Created new websocket connection
....
RuntimeError: websocket connection closed and creation of new connection failed.

**To Reproduce**
1,  run alice server in Machine A:
`python3 run_websocket_server.py --host alice_ip --port 8777 --id alice`
2. run bob server in Machine B:
`python3 run_websocket_server.py --host bob_ip --port 8778 --id bob`
3. run Tutorial 3 - Folded Split Neural Network.ipynb in Machine C
change the alice and bob in Folded Split Neural Network.ipynb like below:
```
verbose = False
kwargs_websocket1 = {"host": "alice_ip", "hook": hook, "verbose": berbose}
kwargs_websocket2 = {"host": "bob_ip", "hook": hook, "verbose": berbose}
alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket1)
bob = WebsocketClientWorker(id="bob", port=8778, **kwargs_websocket2)
```

**Desktop (please complete the following information):**
 - OS: linux
 - Version: syft==0.2.0a1, torch==1.2.0, torchvision==0.4.0

**Additional context**
Could any one help? Or add a success example of Folded Split Neural Network run with multiple machines. Thanks.

**Comment by sug4ndh** [comment]
Did you get any solution to this problem? I am also facing similar problem and it looks like all reported issues similar to this one have gone stale!

**Comment by gmuraru** [comment]
Re-opened this. Will try to look into it. @ProfXGiter do you run using the latest pysyft version?

**Comment by Guest400123064** [comment]
Also facing the same problem :(

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
