### ISSUE TITLE
Weighted federated averaging for non-IID data

### ISSUE THREAD

**Issue by codergan** [OpenMined/PySyft#2845]
**Is your feature request related to a problem? Please describe.**
I am frustrated when the data provided by the clients are niid

**Describe the solution you'd like**
I want to send one more dictionary e.g. train_data or train_data_len to contain the data or number of data of each clients in order to do a federated average with weights difference among clients. In this way, iid will not be affected as well.

**Describe alternatives you've considered**
anything you can think of

**Additional context**
I want to add this feature if you think it is fine

**Comment by LaRiffle** [comment]
Yes it's a good idea!
I'd love to see your suggestion on this :)

**Comment by codergan** [comment]
I have requested for a pull request: fedavg #2893, plz help to review
