### ISSUE TITLE
Bind Address Fail when starting a local socketServerWorker

### ISSUE THREAD

**Issue by b02202050** [OpenMined/PySyft#2858]
**Describe the bug**
When I Use python commandline prompt to run the script in websocket tutorial, I cannot bind the address when start the worker.
* error message:
`OSError: [Errno 99] error while attempting to bind on address ('::1', 8182, 0, 0): cannot assign requested address`

**To Reproduce**
1. use terminal (not notebook)
1. run`python`
1. run (this code is copied from *PySyft/examples/tutorials/websocket/*):
```python
import torch
import os
import sys
import logging
import syft as sy
hook = sy.TorchHook(torch)
from syft.workers.websocket_server import WebsocketServerWorker
local_worker = WebsocketServerWorker(
                            host="localhost",
                            hook=hook,
                            id=0,
                            port=8182)
local_worker.start()
```

**Expected behavior**
server is launched with no error

**Screenshots**
![image](https://user-images.githubusercontent.com/35265996/71463583-d2797c00-27f1-11ea-883a-93f00c833950.png)

**Desktop (please complete the following information):**
* OS: Ubuntu 18.04
* pytorch version: 1.3.0
* syft version: 0.2.0a2

Thanks very much!

**Comment by karlhigley** [comment]
[This ipython issue](https://github.com/ipython/ipython/issues/6193) has some potentially relevant info about this socket error. Long story short, IPv6 `::1`, IPv4 `127.0.0.1`, and the `localhost` hostname are often but not always interchangeable. What happens if you change the `WebSocketServerWorker` instantiation to set `host="127.0.0.1"`?

**Comment by b02202050** [comment]
Wow you genius! It works!!

**Comment by karlhigley** [comment]
I've just seen these kinds of issues recently. 😄

**Comment by fermat97** [comment]
Hi @kabirkhan 
I am not sure if my question is relevant to this thread. I am running the [Federated Learning - MNIST Example of grid tutorial](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/grid/federated_learning/mnist/Fed.Learning%20MNIST%20%5B%20Part-1%20%5D%20-%20Populate%20a%20Grid%20Network%20(%20Dataset%20).ipynb) on Google Colab. Once using ``` NodeClient(hook, node) ```, I got the following error:

```
OSError: [Errno 99] Cannot assign requested address
```
Do you have any idea? Thank you.
