### ISSUE TITLE
module 'syft' has no attribute 'KerasHook' 

### ISSUE THREAD

**Issue by Li-Ziyuan** [OpenMined/PySyft#2859]
module 'syft' has no attribute 'KerasHook' 

how could it happend???

**Comment by gmuraru** [comment]
Do you have the ```tf-privacy``` module installed?

**Comment by Li-Ziyuan** [comment]
Nope...should I run pip install tensorflow.privacy?

**Comment by gmuraru** [comment]
Sorry for the late reply.
Could you run:
```pip install -r pip-deps/requirements_tensorflow.txt```

And check if it works?

**Comment by bingyue0610** [comment]
@Li-Ziyuan hi Ziyuan, did you solve the problem?

**Comment by makaveli10** [comment]
Has anybody been able to solve this? I installed both tf-privacy and tfencrypted in my pysyft environment but this attiribute error doesn't seem to go away!

**Comment by karlhigley** [comment]
Post the output of `pip list` in that environment?

**Comment by makaveli10** [comment]
The output is 
Package                Version            
---------------------- -------------------
absl-py                0.9.0              
appnope                0.1.0              
astunparse             1.6.3              
attrs                  19.3.0             
backcall               0.1.0              
bleach                 3.1.0              
cachetools             4.1.0              
certifi                2020.4.5.1         
chardet                3.0.4              
click                  7.1.1              
decorator              4.4.1              
defusedxml             0.6.0              
entrypoints            0.3                
Flask                  1.1.1              
Flask-SocketIO         4.2.1              
gast                   0.3.3              
google-auth            1.13.1             
google-auth-oauthlib   0.4.1              
google-pasta           0.2.0              
grpcio                 1.28.1             
h5py                   2.10.0             
idna                   2.8                
importlib-metadata     1.5.0              
ipykernel              5.1.4              
ipython                7.12.0             
ipython-genutils       0.2.0              
ipywidgets             7.5.1              
itsdangerous           1.1.0              
jedi                   0.16.0             
Jinja2                 2.11.1             
json5                  0.9.0              
jsonschema             3.2.0              
jupyter-client         5.3.4              
jupyter-console        6.1.0              
jupyter-core           4.6.1              
jupyterlab             2.1.0              
jupyterlab-server      1.0.7              
Keras-Preprocessing    1.1.0              
lz4                    3.0.2              
Markdown               3.2.1              
MarkupSafe             1.1.1              
mistune                0.8.4              
msgpack                1.0.0              
nbconvert              5.6.1              
nbformat               5.0.4              
notebook               6.0.3              
numpy                  1.18.1             
oauthlib               3.1.0              
opt-einsum             3.2.0              
pandocfilters          1.4.2              
parso                  0.6.1              
pexpect                4.8.0              
phe                    1.4.0              
pickleshare            0.7.5              
Pillow                 6.2.2              
pip                    20.0.2             
prometheus-client      0.7.1              
prompt-toolkit         3.0.3              
protobuf               3.11.3             
ptyprocess             0.6.0              
pyasn1                 0.4.8              
pyasn1-modules         0.2.8              
Pygments               2.5.2              
pyrsistent             0.15.7             
python-dateutil        2.8.1              
python-engineio        3.11.2             
python-socketio        4.4.0              
pyzmq                  18.1.1             
qtconsole              4.6.0              
requests               2.22.0             
requests-oauthlib      1.3.0              
rsa                    4.0                
scipy                  1.4.1              
Send2Trash             1.5.0              
setuptools             45.2.0.post20200210
six                    1.14.0             
syft                   0.2.4              
syft-proto             0.2.5a1            
tblib                  1.6.0              
tensorboard            2.2.0              
tensorboard-plugin-wit 1.6.0.post3        
tensorflow             2.2.0rc3           
tensorflow-estimator   2.2.0rc0           
termcolor              1.1.0              
terminado              0.8.3              
testpath               0.4.4              
torch                  1.4.0              
torchsummary           1.5.1              
torchvision            0.5.0              
tornado                6.0.4              
traitlets              4.3.3              
urllib3                1.25.8             
wcwidth                0.1.8              
webencodings           0.5.1              
websocket-client       0.57.0             
websockets             8.1                
Werkzeug               1.0.0              
wheel                  0.34.2             
widgetsnbextension     3.5.1              
wrapt                  1.12.1             
zipp                   2.2.0              
zstd                   1.4.4.0

**Comment by makaveli10** [comment]
@karlhigley tf privacy and tfencrypted are installed from source I think that's why they dont show up here

**Comment by karlhigley** [comment]
Even packages installed from source (at least via `pip install .`) should show up on that list.

**Comment by makaveli10** [comment]
Yeah thanks @karlhigley . My tensorflow privacy installation was broken thanks!
