### ISSUE TITLE
Inconsistency in tutorial 3 Section 3.2

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2864]
In tutorial 3 Section 3.2 it reads:
> So in the last section whenever we called a .send() or a .get() operation, it called that operation directly on the tensor on our local machine. However, if you have a chain of pointers, sometimes you want to call operations like .get() or .send() on the last pointer in the chain (such as sending data directly from one worker to another). To accomplish this, you want to use functions which are especially designed for this privacy preserving operation.

But the code example is the `.move` functionalily

I think we want to keep move() but introduce it differently (maybe before this text) and show the remote_get and remote_* functionalities just after the text quoted

**Comment by Aakash1822** [comment]
Interested to work on it @karlhigley. Please tell me what to change

**Comment by sachin-101** [comment]
Hi @LaRiffle 
Please review the above PR. And let me know, If I need to make any further changes.

**Comment by sachin-101** [comment]
@LaRiffle Can you please review the above issue. And provide me some advice so that I will try solving it.
