### ISSUE TITLE
Remove Numpy from LargePrecisionTensor

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2872]
**Is your feature request related to a problem? Please describe.**
We cannot use LargePrecisionTensor for remote executions or within plans if it depends on numpy. 

**Describe the solution you'd like**
Implement the same functionality without using numpy. In other words, remove the numpy import from this file.

https://github.com/OpenMined/PySyft/blob/b0b8a13524150002524c15c6c283b4b14de62d40/syft/frameworks/torch/tensors/interpreters/large_precision.py

**Describe alternatives you've considered**
Hooking numpy is also an option, but it's not one we want to consider at the moment because it adds a great deal of complexity to intentionally use multiple frameworks.

**Comment by systemshift** [comment]
I can work on this, please assign me the issue.

**Comment by bharatnishant** [comment]
@iamtrask Does removing numpy import implies use of alternate library or making alternate implementation?

**Comment by systemshift** [comment]
> @iamtrask Does removing numpy import implies the use of an alternate library or making alternate implementation?

Ideally to reimplement without importing any other library, but I've been scratching my head how replace numpy arrays with python lists without increasing code complexity too much.
The other option is to hook numpy, as mentioned above, but that should be our last option.

I have been looking at [other](https://wiki.python.org/moin/NumericAndScientific/Libraries) options but nothing stands out, and I don't think it would be wise to add a new dependency just to solve this one issue.

**Comment by LaRiffle** [comment]
From what I experienced, when we don't use numpy tensor ops we use torch ones which is ok but put a big dependency on pytorch (we from an historical point of view of pysyft is 100% ok)

However, I have also the feeling that some expressions (in particular crypto protocols) are better expressed using numpy which is way faster (I'm working on one where I have a 10 times improvements). Additionally numpy is independent from the GAFAs^^

**Comment by iamtrask** [comment]
The top priority is cross platform support and Plan/Promise support, both of which numpy prevents. Using Torch tensors instead does not.

**Comment by mccorby** [comment]
If I remember correctly, we had to use `numpy` to work with very large numbers as it was not possible to implement the basic operations by using only the representation in smaller tensors of those numbers.

`_internal_representation_to_large_ints`: This is where we should put the focus to remove `numpy`. If we could have a `tensor(dtype=object)` then it could easy to replace numpy.

**Comment by karlhigley** [comment]
Is this a situation where PyTorch's new support for extending tensors would make this easier/simpler?

**Comment by LaRiffle** [comment]
Yeah -  and I loop here again with the suggestion that if LargePrecision is not used it should be archived for the moment it would make our life simpler, @mccorby any thoughts?

**Comment by iamtrask** [comment]
> Is this a situation where PyTorch's new support for extending tensors would make this easier/simpler?

Sadly no

**Comment by iamtrask** [comment]
> Yeah - and I loop here again with the suggestion that if LargePrecision is not used it should be archived for the moment it would make our life simpler, @mccorby any thoughts?

Is it not being uesd?

**Comment by mccorby** [comment]
It is used when creating shares bigger than 2**62. If the new `TensorBigInt` does the same, it won't be necessary.
Initially LPT was necessary to allow these operations with big ints in the JVM.

I'll create a PR to delete it.

**Comment by mccorby** [comment]
Just in case, CRT is also using numpy

**Comment by mccorby** [comment]
Fixed in #2907
