### ISSUE TITLE
Add native support for Jetson Nano

### ISSUE THREAD

**Issue by onezerobinary** [OpenMined/PySyft#2873]
It would be amazing if pySyft will be directly available using hardware such as Jetson Nano

I’m trying to develop a consensus protocol using pySyft on a network of Jetson Nano but is hard to combine the two things together.  

It will be nice to have in the distro that is distributed with the Jetson Nano the pySyft library installed that allow developers to access directly to the device and just install the model that will be used for the scope of the projects.

I’ve tried to consider to partially write on top of Torch the functions that I need for building my personal protocol but sincerely I think that will be better and more secure to be part of a community based library rather then write again my personal wheel.

**Comment by hackenjoe** [comment]
Are there any news if Jetson Nano Kits are supported by PySyft?
