### ISSUE TITLE
Sharing of data among Workers using .federated method

### ISSUE THREAD

**Issue by Madhura12gj** [OpenMined/PySyft#2878]
I am trying the federated learning on a csv data. The training data has inputs and targets. Inputs contains all feature columns that are needed to predict and targets has one column.

I want to share some data from inputs, targets to Bob and some to Alice. I am following this particular blog. 
[https://blog.openmined.org/upgrade-to-federated-learning-in-10-lines/](url) 

What have I done till now?
1. Split the data set into test and train.
2. Training set consists of x_train and y_train.
3. Converted x_train and y_train to tensors as inputs and targets.

To Do:
Send the inputs, targets data among alice and bob.

Here is my code snippet which I was trying:
`train = torch.utils.data.TensorDataset(inputs, targets)`
`train_loader = torch.utils.data.DataLoader(train, batch_size=30, shuffle=True)`

`federated_train_loader = sy.FederatedDataLoader(train_loader.federated,shuffle=True)`

`test = torch.utils.data.TensorDataset(inputs_test, targets_test)`
`test_loader = torch.utils.data.DataLoader(test, batch_size=30, shuffle=True)`

I want to know how do I share the data among the workers?

**Comment by aynesss** [comment]
this triggers the error:

AttributeError: 'DataLoader' object has no attribute 'federated'

how do you resolve it?
