### ISSUE TITLE
build a uniform enviroment with a single command

### ISSUE THREAD

**Issue by systemshift** [OpenMined/PySyft#2885]
**Is your feature request related to a problem? Please describe.**
The current setup is messy with dependencies across different files and other guides or tutorials. Leading to dependency errors when someone is trying to build a new environment from scratch. 

**Describe the solution you'd like**
A conda file in the repo that is kept up to date by the community, so the environment can be created with the following command:```conda env create -f environment.yml```
or updated with ```conda env update --prefix ./env --file environment.yml  --prune```

**Describe alternatives you've considered**
from my research conda doesn't seem to support something like a private community repo where it has some command like `conda add repo name` and then simply use `conda update --all` and always get the newest packages.
Although I could be wrong, conda [channels](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/channels.html) and [conda-forge](https://conda-forge.org) could be what we need for our use case.

**Additional context**
I had some errors when running test units, so I decided to start a fresh environment, and now I get dependency errors and found out that things are broken and there is no easy way to have the same environment without sometime lost reading documentation

**Comment by karlhigley** [comment]
It seems like the biggest culprit lately has been the addition of the notebook tests to the test suite. I think the notebook dependencies were previously optional and hadn't been added to the Makefile venv target yet. IIRC, that's also where the missing scipy dependency cropped up, right?

**Comment by systemshift** [comment]
from a quick search, `scipy` is called in 2 notebooks, and `lr.py`. So even without the notebooks it was necessary  to add `scipy` to the main `requirements.txt` file.
Now thinking about it, it is possible that some users don't want to use conda(or can't) and would just prefer pip + venv, so that should be considered as well.
