### ISSUE TITLE
Serialization should return consistent types and should not modify objects being serialized

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#2887]
**Is your feature request related to a problem? Please describe.**
Msgpack simplification/detailing of PySyft objects sometimes modifies the state of the object (e.g. `AdditiveSharingTensor`) and sometimes returns a completely different type of object (e.g. `PointerTensor`.) These additional pieces of functionality intertwined with de/serialization make it harder to add additional serialization formats.

**Describe the solution you'd like**
Any transformations or modifications that currently happen inside simplification and detailing to be refactored to occur before/after instead.

**Describe alternatives you've considered**

- Duplicating these behaviors in Protobuf serialization (which creates a maintenance hassle and a danger of getting out of sync with each other.)

**Additional context**
List of known examples:

- [ ] `AdditiveSharingTensor.simplify()` [changes the value](https://github.com/OpenMined/PySyft/blob/475fd8d46a24d8f8ad81c7edaf0af29cb45b3426/syft/frameworks/torch/tensors/interpreters/additive_shared.py#L988) of the `garbage_collect_data` attribute 
- [ ] `PointerTensor.detail()` [sometimes loads tensors](https://github.com/OpenMined/PySyft/blob/475fd8d46a24d8f8ad81c7edaf0af29cb45b3426/syft/generic/pointers/pointer_tensor.py#L503-L525) instead of deserializing pointers
- [ ] `PointerPlan.detail()` [sometimes loads plans](https://github.com/OpenMined/PySyft/blob/475fd8d46a24d8f8ad81c7edaf0af29cb45b3426/syft/generic/pointers/pointer_plan.py#L169-L173) instead of deserializing pointers
- [ ] `PointerProtocol.detail()` [sometimes loads protocols](https://github.com/OpenMined/PySyft/blob/475fd8d46a24d8f8ad81c7edaf0af29cb45b3426/syft/generic/pointers/pointer_protocol.py#L110-L114) instead of deserializing pointers
- [ ] `ObjectPointer.detail()` [sometimes loads objects](https://github.com/OpenMined/PySyft/blob/475fd8d46a24d8f8ad81c7edaf0af29cb45b3426/syft/generic/pointers/object_pointer.py#L411-L433) instead of deserializing pointers

**Comment by vvmnnnkv** [comment]
Maybe this should be also in the list:
`Protocol.detail()` doesn't always reconstruct Protocol as it is presented in serialized form, worker_id's may change in detailed object.
