### ISSUE TITLE
.get() method deletes underlying objects at worker

### ISSUE THREAD

**Issue by sukhadj** [OpenMined/PySyft#2889]
**Describe the bug**
When we apply `.get` method to get the syft tensor (consider AdditiveSharing or FixedPrecisionTensor) it deletes the underlying tensor at workers also. This leads to ObjectNotFoundError in many tests. 

**To Reproduce**
```python
t = torch.tensor([1, 2, 3, 4.0])
ptr = t.send(james)
x = ptr.fix_prec().share(bob, alice)
x_fix = x.get()
x_fix.get()

>>> syft.exceptions.ObjectNotFoundError: Object "46643659781" not found on worker!!!
```
**Expected behavior**
Either underlying tensor doesn't get deleted or we should return the underlying tensor itself when use `.get()` 

**Additional context**
The `garbage_collect_data` for PointerTensor should be set to False if we don't intend to delete to objects. The above code works perfectly if we set `garbage_collect_data` of PointerTensors to False before calling get.

**Comment by LaRiffle** [comment]
FYI this error comes from recent changes in how we serialize AdditiveSharing tensors

**Comment by karlhigley** [comment]
Is [this change](https://github.com/OpenMined/PySyft/commit/5b9161eb326a3e5d5a4c0b6c3de18b8ce467c314#diff-5bfe6150bb5ee943c40230a4bdb0b054L990-R995) from the serde inconsistency fixes the relevant change that breaks this?

**Comment by sukhadj** [comment]
> Is [this change](https://github.com/OpenMined/PySyft/commit/5b9161eb326a3e5d5a4c0b6c3de18b8ce467c314#diff-5bfe6150bb5ee943c40230a4bdb0b054L990-R995) (from the serde inconsistency fixes) the relevant change that breaks this?

No. [this change from PR](https://github.com/sukhadj/PySyft/blob/f2754053352e7a0e01edc6eb326b551cf1f34cfe/syft/frameworks/torch/tensors/interpreters/additive_shared.py#L1008) breaking it. Currently commented out.

**Comment by karlhigley** [comment]
Rereading the code snippet, I'm not sure if `x` is a pointer to a fixed precision tensor. I *think* it works like this (but I could be wrong):

```python
t = torch.tensor([1, 2, 3, 4.0])
ptr = t.send(james)                      # PointerTensor to a Torch tensor
x_fix_ptr = ptr.fix_prec()               # PointerTensor to a FixedPrecisionTensor
x_ast_ptr = x_fix_ptr.share(bob, alice)  # PointerTensor to an AdditiveSharingTensor
x_fix = x_fix_ptr.get()                  # FixedPrecisionTensor
x_ast = x_ast_ptr.get()                  # AdditiveSharingTensor
```

I'm surprised that `x.get().get()` worked with any `garbage_collect_data` setting. 🤔
