### ISSUE TITLE
Refactor Protocols to be more friendly to single operation execution

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#2903]
**Is your feature request related to a problem? Please describe.**
Based on a conversation with @iamtrask: Many of the distributed computations involved in encrypted and private machine learning rely on a very small number of operations (e.g. 1 operation) being executed on a particular worker before returning a results. Protocols exist to chain together operations on PromiseTensors, but are currently based on Plans, which are more oriented toward pipelined execution of many operations on a single worker.

**Describe the solution you'd like**
Refactor Protocols to remove the dependency on Plans and move them toward the "graph of promises" vision.

**Describe alternatives you've considered**
- _Delete Protocols from the PySyft code base._ If the current version is already deprecated but not yet in use, maybe we can just vaporize the code to reduce complexity until someone gets around to doing a Protocol rewrite.
- _Disable the Protocol tests._ Concerned that this will leave increasingly out of date code in place while removing one of the concrete reminders to update it (i.e. test failures.)

**Additional context**
The web and mobile team has work around Protocols in flight now:
- https://github.com/OpenMined/syft-proto/pull/25
- https://github.com/OpenMined/PySyft/pull/2900
- https://github.com/OpenMined/syft.js/pull/74

**Comment by iamtrask** [comment]
CC: @Jasopaum

**Comment by iamtrask** [comment]
This work should probably be blocked until PromiseTensor is really at a place we're happy with. The culmination of a lot of discussion on what Protocols are ended with, "Protocols are a collection of VirtualWorker objects with a PromiseTensor graph traversing them (stored within the VirtualWorkers' collective object stores"

**Comment by cereallarceny** [comment]
This issue is associated with https://github.com/OpenMined/PySyft/issues/3008

**Comment by karlhigley** [comment]
Working with @Jasopaum to define an updated path forward for Protocols. Will open a new issue with our checklist.
