### ISSUE TITLE
Plans should support fixed precision and encrypted values

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#2915]
**Is your feature request related to a problem? Please describe.**
While Plans are being reworked, support for fixed precision and encrypted values in plans is being temporarily disabled.

**Describe the solution you'd like**
Re-build fixed precision and encrypted value support on top of the new version of Plans.

**Describe alternatives you've considered**
- *Include this in the rework* - Decided against this to keep the scope manageable and iteratively build out revamped Plans.

**Additional context**
Will build on #2910 as part of #2912.

**Comment by LaRiffle** [comment]
@karlhigley I'm closing this, it has been added to #2910 finally
