### ISSUE TITLE
Add support of PyTorch 1.4

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2916]
https://pytorch.org/blog/pytorch-1-dot-4-released-and-domain-libraries-updated/

**Comment by karlhigley** [comment]
What's involved in this? Do we just need to bump the dependency version and fix any compatibility issues? Are there new PyTorch features to incorporate?

**Comment by LaRiffle** [comment]
Yeah, we just need to bump the dependency version and fix any compatibility issues I'd say
