### ISSUE TITLE
Handcrafted RNNs are not Tested At All

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2926]
**Describe the bug**
This whole file seems to be largely un-tested by our unit testing suite.
https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/nn/rnn.py

**Expected behavior**
This file should have 100% test coverage.

Make sure to uncomment the codecov omit flag for this file https://github.com/OpenMined/PySyft/pull/2896#pullrequestreview-344948386

**Comment by ribhu97** [comment]
I can take this up

**Comment by jimboH** [comment]
Hi, I would like to know if this is still an active issue. If it is, could I take this issue?

**Comment by iamtrask** [comment]
It is and you may!

**Comment by AniTho** [comment]
Hi, I would like to work on this issue. Is it still active?

**Comment by jimboH** [comment]
@iamtrask thank you! I will work on it.

**Comment by AniTho** [comment]
@karlhigley thank you! I will start working on it.

**Comment by iamtrask** [comment]
Sounds like you should both work together on it.

**Comment by AniTho** [comment]
@iamtrask I have to implement test case as you have done for conv2d which is by creating a sample object using torch nn and one of the custom implementation and then finding maximum absolute difference in the two model output?

**Comment by AniTho** [comment]
@jimboH Can you share anything through which I can contact you to collaborate?

**Comment by jimboH** [comment]
@AniTho Thank you! I got some troubles with rounding while testing the handcrafted RNNs but finally solved it. Would you take a look at the test_rnn.py file to see if it really test all the RNNs?

**Comment by AniTho** [comment]
@jimboH yes I'd like to see the code.

**Comment by karlhigley** [comment]
See #3092 for the current state of the testing effort.

**Comment by sachin-101** [comment]
#3092 is merged. Do more tests need to be added ? @iamtrask @karlhigley 
If not, then you can close this issue.
