### ISSUE TITLE
Set up automated PyPI package publishing

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#2929]
**Is your feature request related to a problem? Please describe.**
New versions of the `syft` Python package haven't been released for the past several months, and it's starting to cause problems for `syft` users.

**Describe the solution you'd like**
Set up automated package publishing w/ Github Actions ([like syft-proto has](https://github.com/OpenMined/syft-proto/pull/16).)

**Describe alternatives you've considered**
- _Publish manually._ This is error prone and relies on someone to keep up with it.
- _Use a script._ Less error prone, still relies on someone to run it.

**Additional context**
The previous release script can be found [here](https://github.com/OpenMined/pypi_upload_scripts/blob/master/upload2pypi.fish).

**Comment by karlhigley** [comment]
@systemshift expressed an interest in working on this.

**Comment by systemshift** [comment]
@karlhigley so looks like this already exists. https://github.com/OpenMined/PySyft/commit/3fab328bd2f48c762e2f577f489f3649d8113214

**Comment by karlhigley** [comment]
@systemshift So it does! I'll close this then, but would still be nice to incorporate `versioneer`. That might be a separate issue though.
