### ISSUE TITLE
Conda install on Manjaro error on import. ModuleNotFoundError: No module named 'pysyft_proto'

### ISSUE THREAD

**Issue by IanQS** [OpenMined/PySyft#2931]
**Describe the bug**
Conda install on Manjaro error on import. Obtaining  `ModuleNotFoundError: No module named 'pysyft_proto' `

**To Reproduce**
```
conda create -n pysyft python=3
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install "syft[udacity]"
```

Then, in Python

```
import syft as sy
```

results in 

```
Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.15.0.so'
WARNING:tensorflow:From /home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/tf_encrypted/session.py:24: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/__init__.py", line 76, in <module>
    from syft import serde
  File "/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/__init__.py", line 1, in <module>
    from syft.serde.serde import *
  File "/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/serde.py", line 89, in <module>
    from syft.serde.proto import proto_type_info
  File "/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/proto.py", line 13, in <module>
    from pysyft_proto import proto_info
ModuleNotFoundError: No module named 'pysyft_proto'

```

**Expected behavior**
Import without issue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Python: 3.7.6
- syft: 0.2.1a1

**Additional context**
Installation on Conda

**Comment by karlhigley** [comment]
The library `pysyft-proto` has been renamed to `syft-proto` since `syft v0.2.1a1` was released. Our previous release manager no longer has time to fill that role, and we're a bit behind on publishing releases. 😅 

I'm in the process of sorting out our release pipeline and expect another release to published sometime this week, which should fix the underlying issue and which I assume will fix the `conda` issue.

**Comment by IanQS** [comment]
Thanks for the explanation! Do you have any suggestions on how to fix it in the meantime or should I just wait? :)

**Comment by karlhigley** [comment]
@IanQS PySyft v0.2.2.a1 has been published to PyPI. Give that a try, and let me know if it works better!

**Comment by IanQS** [comment]
@karlhigley Sorry, ran into a different bug now. Running 

```
import pysyft as sy
```

results in 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/__init__.py", line 44, in <module>
    from syft.grid.public_grid import PublicGridNetwork
  File "/home/ian/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/grid/public_grid.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Doing `pip install requests` solves the issue. 

Have verified that this is the case on 

```
syft                 0.2.2a1            
syft-proto           0.1.0a1.post36     
```

Should I mark this as closed?

**Comment by karlhigley** [comment]
Ah, interesting. Grid functionality just got moved into PySyft with somewhat partial tests, and I bet that's why our check suite didn't catch the dependency issue. Let's call this issue closed and create a separate issue for the `requests` dependency—that way I can assign it to the Grid team.

**Comment by karlhigley** [comment]
@IanQS When I create a new virtualenv with `make venv`, I end up with `requests` installed, but it's not directly listed in any of the requirements files. Seems like it must be a transitive dependency of something else in one of the requirements files, but I'm not sure which file or which package.

**Comment by IanQS** [comment]
Absolutely no worries :) Just wanted to let you know. FWIW it's a simple fix although I'm surprised conda didn't make it work out of the box

**Comment by karlhigley** [comment]
Yeah, `conda` packaging is kinda new and we haven't ironed out all the issues yet. (@systemshift has been working on it recently.)
