### ISSUE TITLE
Bandit for security

### ISSUE THREAD

**Issue by suhacker1** [OpenMined/PySyft#2933]
We should be concerned about the numerous security issues associated with Python code. However, there seem to be minimal security checks within the current development process. It would be nice if we implemented [Bandit](https://github.com/marketplace/actions/bandit-check) to provide stronger security guarantees with PySyft. I believe it would be optimal if we first implemented it as a GitHub action and then iterated upon the linter itself for future security issues.

**Comment by karlhigley** [comment]
We’re not quite migrated over to Github Actions yet, so we’d currently need to incorporate it into the Travis CI testing process. @suhacker1 would you be interested in setting up a bandit config and adding it to our Travis build process?

**Comment by karlhigley** [comment]
Did a test run with `bandit` (skipping the check for `assert`) and it does find a few things.

**Comment by suhacker1** [comment]
I'm good with setting up a bandit config and adding it to the Travis build process. Do you think it would be a good idea to create an issue for everything Bandit finds?

**Comment by karlhigley** [comment]
I'd probably just create a single issue. Having looked at the Bandit output, I think we probably care most about medium-high severity issues, and it would be nice to find a way to prevent low severity issues (mostly `assert`s) from breaking the build.

**Comment by karlhigley** [comment]
I'm working on creating Github Actions  for the build [over here](https://github.com/OpenMined/PySyft/pull/2936), so it's probably fine to go with a GH action instead of Travis.

**Comment by suhacker1** [comment]
Bandit is contained within the tests.yml file; should this issue now be closed?
