### ISSUE TITLE
Updating data without restarting server

### ISSUE THREAD

**Issue by patselle** [OpenMined/PySyft#2935]
Hi everyone,

I run a remote server that already contains a part of the data as shown by the following code:

`...
local_worker = WebsocketServerWorker(
                            host=host,
                            hook=hook,
                            id=id,
                            port=port)

data = torch.tensor([[1,0],[1,1.]], requires_grad=True).tag("#data")
target = torch.tensor([[1],[1.]], requires_grad=True).tag("#target")

remote_client_data = data.send(local_worker)
remote_client_target = target.send(local_worker)

local_worker.start() # start server
...`

After the server has started and is connected to a central server as a remote worker, I can create a PrivateGridNetwork and create a FederatedDataset to train a model (by the way, is this the default procedure?).

To my question, is it possible to change data at runtime without stopping the server (local_worker.start())?

For example, add more data points on the remote worker and train the model again?

**Comment by gmuraru** [comment]
@IonesioJunior^^ :)
