### ISSUE TITLE
Incorporate versioneer to packaging automation

### ISSUE THREAD

**Issue by systemshift** [OpenMined/PySyft#2947]
As mentioned in  #2929.
To streamline publishing syft to pypi, versioneer would help automate things further.

**Comment by systemshift** [comment]
@karlhigley please assign me the issue.

**Comment by imskr** [comment]
@karlhigley I would like to work on this, if no one is working.

**Comment by karlhigley** [comment]
@imskr There's already [a PR for it](https://github.com/OpenMined/PySyft/pull/2949), which I've been holding off on merging until I get a better handle on how we want to do versioning across the various Syft repos.

**Comment by imskr** [comment]
Okay.
