### ISSUE TITLE
No example with multiple models, and no federated average implementation

### ISSUE THREAD

**Issue by youyeg** [OpenMined/PySyft#2950]
Hi,
I have not seen a federated average example in your list. I was investigating your examples, and it was not clear for me for instance in CIFAR, advanced tutorial, do we send the model in parallel or not?
I mean do we train two separate models, and then merging them, or just, send the same model, to the clients, and back to the server?

I was trying to implement federated average, and it seemed that I should have a separate models, and optimizer to the clients to be trained.
Is it correct? if it is not, how can I implement federated average with PySyft?

**Comment by iamtrask** [comment]
This is coming - at present we haven't implemented the "platform" side of Federated Learning but it's a work in progress.

**Comment by iamtrask** [comment]
Check out what's going on in the https://github.com/OpenMined/PyGrid/ project. @vvmnnnkv, @cereallarceny , and @IonesioJunior are also working on the model averaging workflow as we speak.

**Comment by youyeg** [comment]
Thank you for the quick answer,
But I had another question, that is not answered, should I use two separate optimizer if I want to use two clients, and merge them? like the link below?
https://towardsdatascience.com/federated-learning-3097547f8ca3

**Comment by nitincic** [comment]
Is there any update on this? Does pysyft now support federated averaging and/or federated sgd the way that was being discussed by youyeg (without basically having to send the same model to the devices)? 
The link https://towardsdatascience.com/federated-learning-3097547f8ca3 does seem to motivate that it works but in practice there seems to be bugs in that code and fixing those didn't seem to work either.
