### ISSUE TITLE
asking for explanation about scale_model (for educational purpose)

### ISSUE THREAD

**Issue by youyeg** [OpenMined/PySyft#2961]
Hi,
I have seen a method to scale model, in PySyft, and I had some guesses, but I would appreciate it if you could please explain what is happening in here.
I mention my questions in the code as comments.
`
def scale_model(model, scale):

    """Scale the parameters of a model.
    Args:
        model (torch.nn.Module): the models whose parameters will be scaled.
        scale (float): the scaling factor.
    Returns:
        torch.nn.Module: the module with scaled parameters.
    """
    params = model.named_parameters()
    # in here, does params have references of model parameters? It only makes sense
    # for me only in this, way, but how a method return a pointer?
    dict_params = dict(params)
    # I was assuming that casting params as a dictionary, would change the pointer 
    # assignments, but it seems that it still has its references
    with torch.no_grad():
        for name, param in dict_params.items():
            dict_params[name].set_(dict_params[name].data * scale)
            # I am seeing that in the line above, the scale is applying to each layer separately. Is it 
            # correct? and then we have modified the parameters, and the data is changing in the 
            # model, as well
    return model
`

**Comment by iamtrask** [comment]
The weights are being multiplied by a scalar.

**Comment by iamtrask** [comment]
so if the weights were [1,2,3], and you call this with a scalar of "0.5", the weights would become [0.5, 1, 1.5]

**Comment by youyeg** [comment]
You did not understand my questions.
I know what the method is doing.
My question, was about how it uses the pointers to modify the parameters inside the model

**Comment by iamtrask** [comment]
Pointers can do anything that normal tensors can do. So yes, if you pass in pointers for all these inputs, then it will coordinate the execution of this method on the remote machine.
