### ISSUE TITLE
Illegal instruction error once trying to import syft

### ISSUE THREAD

**Issue by fermat97** [OpenMined/PySyft#2966]
Hi, I have done the `syft` installation as explained in the installation part. Everything goes fine, but after installation once I try to `import syft` it ends up with the following error `Illegal instruction` and even terminated the python prompt. Do you have any idea? thank you.

**Comment by karlhigley** [comment]
@fermat97 Could you post a stack trace? That will help with troubleshooting the issue.

**Comment by fermat97** [comment]
There is no stack trace. I start python prompt. Once I `import syft`, it quits python prompt and just showed `Illegal instruction`.

**Comment by karlhigley** [comment]
Wow, that is puzzling. What `syft` version and what Python version?

**Comment by fermat97** [comment]
I have installed them couple of days ago, so I think it is the latest version. I have followed the pre-installation and installation guide on [PySyft git](https://github.com/OpenMined/PySyft). It is version 3.7.6 for the Python, and version 1.3.0 for the PyTorch.

**Comment by karlhigley** [comment]
Hmm, well, we did see some issues with 0.2.2.a1 related to the update to PyTorch 1.4 and released a newer version (0.2.3.a1) yesterday that might help. Maybe give that a try?

**Comment by fermat97** [comment]
I tried to update I couldn't, then I removed the environment and install everything from beginning, then I got this error:

> ERROR: Could not find a version that satisfies the requirement tensorflow<2,>=1.12.0 (from tf-encrypted<0.6.0!=0.5.7,>=0.5.4; extra == "udacity"->syft[udacity]) (from versions: none)
ERROR: No matching distribution found for tensorflow<2,>=1.12.0 (from tf-encrypted<0.6.0!=0.5.7,>=0.5.4; extra == "udacity"->syft[udacity])

**Comment by fermat97** [comment]
I have tried once more, using `pip install syft` on the same environment, and it was successful. Now I can import syft without problem.
