### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by jfraj** [OpenMined/PySyft#2969]
**Describe the bug**
After installing, `import syft` gives the following error: 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxxx/opt/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/__init__.py", line 44, in <module>
    from syft.grid.public_grid import PublicGridNetwork
  File "/Users/xxxxx/opt/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/grid/public_grid.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
`

**To Reproduce**
1. `conda create -n pysyft python=3`
2. `conda activate pysyft`
3. `conda install jupyter notebook`
4. `pip install syft`
5. `python`
6. `import syft`
7. Result = See error above

**Environment :**
 - OS: macOS Catalina 10.15.1
 - python 3.7.6

**Comment by klize** [comment]
If you can't find the package through typing `pip list` or other commands that gives you a list of installed packages on your virtual system, you can simply install it manually.
`pip install requests` which might need to be included in requirements.txt or something.

**Comment by jfraj** [comment]
Seems like it will be fixed by this PR https://github.com/OpenMined/PySyft/pull/2970/commits/033fc646ddd9c023c738a22e4493407ab0043b24

**Comment by gmuraru** [comment]
Could you close this issue @jfraj?
