### ISSUE TITLE
SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by ymsaputra** [OpenMined/PySyft#2971]
I run the example in PySyft/examples/tutorials/advanced/websockets-example-MNIST-parallel/Asynchronous-federated-learning-on-MNIST.ipynb. However, there is a syntax error as follows:

File "coba_fed_async.py", line 73
    results = await asyncio.gather(
             ^
SyntaxError: 'await' outside function

I use Python 3.7.x. Is there any solution for this issue?

**Comment by fermat97** [comment]
hi @ymsaputra did you find any solution? I got the exact same thing. Hi @midokura-silvia do you have any idea?

**Comment by midokura-silvia** [comment]
@ymsaputra await needs to be called from within a function. So in your file coba_fed_async.py your await calls need to be in a function that is marked as async.

@fermat97 this is not enough information to deduce where the syntax error is coming from.

**Comment by fermat97** [comment]
@midokura-silvia I am using your code in [Asynchronous-federated-learning-on-MNIST](https://github.com/OpenMined/PySyft/blob/0831588f0795c226ce1057070e967d6846b015e6/examples/tutorials/advanced/websockets-example-MNIST-parallel/Asynchronous-federated-learning-on-MNIST.ipynb), howvere I don't use as a notebook. There you have:
```python
results = await asyncio.gather(
        *[
            rwc.fit_model_on_worker(
                worker=worker,
                traced_model=traced_model,
                batch_size=args.batch_size,
                curr_round=curr_round,
                max_nr_batches=args.federate_after_n_batches,
                lr=learning_rate,
            )
            for worker in worker_instances
        ]
    )
``` 
in this case `await` is used outside an `async` function. How didn't you get any error?

**Comment by newne** [comment]
> @midokura-silvia I am using your code in [Asynchronous-federated-learning-on-MNIST](https://github.com/OpenMined/PySyft/blob/0831588f0795c226ce1057070e967d6846b015e6/examples/tutorials/advanced/websockets-example-MNIST-parallel/Asynchronous-federated-learning-on-MNIST.ipynb), however I don't use as a notebook. There you have:
> 
> ```python
> results = await asyncio.gather(
>         *[
>             rwc.fit_model_on_worker(
>                 worker=worker,
>                 traced_model=traced_model,
>                 batch_size=args.batch_size,
>                 curr_round=curr_round,
>                 max_nr_batches=args.federate_after_n_batches,
>                 lr=learning_rate,
>             )
>             for worker in worker_instances
>         ]
>     )
> ```
> 
> in this case `await` is used outside an `async` function. How didn't you get any error?

I had the same error. but it worked in notebook.

**Comment by okazaki0** [comment]
try to create async function and use inside the await i think it will work

**Comment by harshkasyap** [comment]
I am getting similar issue in 

https://github.com/OpenMined/PySyft/blob/master/examples/experimental/FL%20Training%20Plan/Host%20Plan.ipynb in 

auth_response = await sendWsMessage(auth_request)
and
cycle_response = await sendWsMessage(cycle_request)

I am running it in Python, haven't checked it in IPython

**Comment by MusheerRepo** [comment]
The syntax for using it is:

async def function_name:
    Statement 1
    Statement 2
    .
    .

asyncio.run(function_name())
