### ISSUE TITLE
`conda update -q conda` in Travis configuration asks for user input

### ISSUE THREAD

**Issue by siarez** [OpenMined/PySyft#298]
[My built](https://travis-ci.org/OpenMined/PySyft/jobs/284442734) stalled after `conda update -q conda` asked for user input during CI build. 
I think in [our travis configuration](https://github.com/OpenMined/PySyft/blob/master/.travis.yml), we need to change:
`conda update -q conda`
to:
`conda update -q -y conda`

https://conda.io/docs/commands/conda-update.html

@meetvora I think that line was added with your [commit](https://github.com/OpenMined/PySyft/commit/67158f2af403a44270ca714647f45c4d14da151c).

**Comment by meetvora** [comment]
I might have missed out on that part. 
Thanks @siarez for fixing it.
