### ISSUE TITLE
Support field of 2**64

### ISSUE THREAD

**Issue by Yugandhartripathi** [OpenMined/PySyft#2981]
**Is your feature request related to a problem? Please describe.**
Too many modulo operations involved in basic operations which costs significant computation time and resources.

**Describe the solution you'd like**
AST and FPT should work in finite field of 2**64 and since LongTensor automatically wraps in that range we no longer need to explicitly call modulo operations at every stage.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Yugandhartripathi** [comment]
We can close this one now :smile:

**Comment by karlhigley** [comment]
🎉
