### ISSUE TITLE
Docs on adding a new message type

### ISSUE THREAD

**Issue by youben11** [OpenMined/PySyft#2984]
**Is your feature request related to a problem? Please describe.**
While implementing a new message type for syft workers, I didn't found a clear documentation on how to do so, I used some help from slack and grep utility to find what need to be updated.

**Describe the solution you'd like**
I think it would be great if we can put a doc describing how to do so, @karlhigley suggested a README file under syft/messaging, another possibility is to add a quick tutorial on this.

**Comment by vvmnnnkv** [comment]
Hey @youben11 
Have you noticed this section?
https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md#process-for-serde-protocol-changes
How helpful is it?

**Comment by youben11** [comment]
I missed that ! Really helpful on what to do to add a new type that will be serialized. Thanks @vvmnnnkv . Implementing a new message type also requires other changes and maybe we can focus only on the message implementation and refer to this for how to make changes to protobuf to support it.
