### ISSUE TITLE
Allow PySyft to package plan operations either as a list of individual commands or as TorchScript

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PySyft#2994]
TorchScript allows for the execution of a PyTorch model outside of Python using the LibTorch C++ library and is compiled by PyTorch’s native JIT compiler. PySyft compiles all plan operations into a list called the “list of procedures” (it also compiles any tensors you include with the plan as the plan’s “state”). Currently, these operations are listed in order, one by one. For instance, you may have the following plan in Python:

```py
def plan_double_abs(x):
    x = x + x
    x = torch.abs(x)
    return x
```

Which then returns the `__add__` operation, followed by the `abs` operation. Each operation also comes with various tensors or pointer tensors (which are literally pointers in memory to a tensor that doesn’t exist until you create it) that instruct you what to name the result of each operation. Syft.js utilizes this to then convert each operation’s commandname into a valid TensorFlow.js command (more on this later).

However, PyTorch for Android and iOS do not have the ability to execute an ordered list of operations because they only have access to LibTorch in C++. LibTorch does not expose operations such as `add` and `abs`, and instead is only capable of executing TorchScript.

For this project, we need to instruct PySyft to be able to simplify plans either into TorchScript (for Android and iOS) or into a list of procedures and state tensors (for Javascript).

**Comment by vvmnnnkv** [comment]
It seems initial thinking was that Plan with list of operations will be traced with torch.jit.trace.
The question is, do we need same Plan protobuf type to (be able to) hold both versions of Plan or it's fine to have ops list plan to be syft_proto.execution.v1.Plan and torchscript version to be syft_proto.types.torch.v1.ScriptModule?

**Comment by cereallarceny** [comment]
I would imagine we can do this conversion on the fly in PyGrid and avoid
storing it twice on protobuf.  If it doesn't take long to run the plan
through the JIT compiler then I say that we do that.  Protobuf can only
have the one true value, and then when we host a plan on PyGrid then it
runs the compiler, splitting the plan into two versions and storing each
separately.  Go ahead and do this Vova if you want.

**Comment by karlhigley** [comment]
I'd probably make the JIT compiled version a field of type `syft_proto.types.torch.v1.ScriptModule` on the `Plan` schema, because I'm not sure that the Torchscript will contain 100% of the information required to make Plans work. (It will definitely contain all the information required to run the computations in the Plan, but handling inputs/outputs/ids/etc isn't necessarily part of that.)

**Comment by cereallarceny** [comment]
That works for me!

**Comment by vvmnnnkv** [comment]
Should it be oneOf with existing operations and state fields? I.e. does it makes sense to store both operations/state and torchscript at the same time in one Plan? I see it may be beneficial for storage, but not for sending. For example, PySyft might make Plan with both ops and torchscript and send it to PyGrid, but PyGrid would deserialize, remove one unneeded part, serialize back before sending it to worker.

**Comment by karlhigley** [comment]
`oneof` would prevent us from storing both formats, so it seems like they should be separate fields, but Grid could remove one or the other when sending to save bandwidth.

**Comment by cereallarceny** [comment]
Let's avoid `oneof` then. Go ahead with the proposed solution @karlhigley!
