### ISSUE TITLE
Make .send() differentiable

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3000]
**Is your feature request related to a problem? Please describe.**
If you build a graph of computation across multiple workers, you'll use send or move to do so. But those are not differentiable and hence .backward() won't work except on the last worker where you call it

**Describe the solution you'd like**
I'd like send() to be crossable is the opposite direction (using a reference to the original value/ location) to send back a .backward() call when needed

**Additional context**
This is super useful for SplitNN

**Comment by karlhigley** [comment]
This would also be handy for garbage collection.
