### ISSUE TITLE
Error when try to send data using dataloader

### ISSUE THREAD

**Issue by joaolcaas** [OpenMined/PySyft#3002]
**Describe the bug**
Hello! I'm trying to build an all enviroment using PyGrid/PySyft since a while. My testes went good since today, when i update syft library and an error including dataloader shows up. The error hapens when i try to iterate on my last dataloader, no matter if 2, 3 or x dataloader, the error always appears when the last dataloader will be iterated.

**To Reproduce**
1. Build a data loader (in my case, my dataloader was built with cifar10 images)
2. Iterate trought this dataloader (sending the data for worker(s))
3. At the last interaction, the error below must appears

**Screenshots**
![image](https://user-images.githubusercontent.com/23393117/73663280-0743e300-467c-11ea-9a62-2b647061310c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate
 - Version 16.04

**Additional context**
If i add a False flag at line 63 syft/generic/frameworks/hook/trace.py it work's, but clearly not the best option.

**Comment by LaRiffle** [comment]
Hum, so it says that `syft.hook` is a function while it's supposed to be an instance of `TorchHook`

**Comment by LaRiffle** [comment]
Could you provide a small example? Because it is used bu Tutorial 6 and seems to be working there.

**Comment by joaolcaas** [comment]
That was exactly what i was writing, i was using DataLoader from torch and not from syft. Maybe if i use `sy.FederatedDataLoader` it works, but i don't know for sure. I'm going to test it and return with a feedback.

**Comment by joaolcaas** [comment]
While i was testing, i just realize that i want to send my dataset with tags in pygrid, so i think that is no the best option to me. For a now i'm using a stable verion that works to me, just a few commits ago.

Here is a small example that you asked for: https://gist.github.com/joaolcaas/4be061459b5893cfc2b73b9a1620c94f

The error here hapens before the any call to send because here exists just one `data_iter`.  The `./data2` is a path for cifar10 dataset. I don't know if you would like to test once the error is related to grid, but is a syft error.

**Comment by joaolcaas** [comment]
@LaRiffle sorry, my mistake. I was not instantiating `hook = sy.TorchHook(torch)` because i thought my main file was getting `hook` from another file. So, not to worry about :smile:
