### ISSUE TITLE
Automated Sphinx documentation for the module syft

### ISSUE THREAD

**Issue by Benardi** [OpenMined/PySyft#3005]
**Is your feature request related to a problem? Please describe.**
I believe it would be helpful if there was a readily available, accessible and always up to date documentation unveiling the interfaces and sub-modules of the module syft in one place.

**Describe the solution you'd like**
Ideally this documentation would be automatically generated by parsing the existing pydocs and creating respective html pages / pdf document.
The docs would be linked to a CI/CD testing environment to ensure that :
* each new feature/bug fix added to the stable branch does not break the documentation.
* the newest documentation version is made available to the domain where it's hosted (e.g. readthedocs)
* there's some version control to the documentation as well.

**Describe alternatives you've considered**
* A "private" readthedocs provided via an existing infrastructure administered by someone inside OpenMined, in case there's some reason not to use  the public one.
* Skip the readthedocs and provide the documentation in a site administered by someone inside OpenMined

**Additional context**
Examples of existing documentation using this solution:
* https://web3py.readthedocs.io/en/stable/
* https://docs.scipy.org/doc/numpy/reference/
* https://pandas.pydata.org/pandas-docs/stable/index.html

**Comment by karlhigley** [comment]
This sounds great! I’d vote for ReadTheDocs style.
