### ISSUE TITLE
Add latency simulation to Virtual workers

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3007]
**Describe the solution you'd like**
It would be great to add an option to simulate latency on virtual workers while sending message.
Basically just add a small sleep in the `_recv_msg` or `_send_msg` virtual worker methods.

**Comment by jefersonf** [comment]
What do you mean by latency simulation? It would be an new option to a _VirtualWorker_ like `add_latency=100`. Like the following example.
```
...
import time

class VirtualWorker(BaseWorker, FederatedClient):
    def _send_msg(self, message: bin, location: BaseWorker, latency: int = 0) -> bin:
        time.sleep(latency)
        return location._recv_msg(message)
```

**Comment by Vishal-Ramesh2** [comment]
I'd like to implement this

**Comment by BBloggsbott** [comment]
I'd like to implement this

**Comment by jefersonf** [comment]
Hi @BBloggsbott, I tried to tackle this. And I've actually started on, if you would like to give some help please take a look at this [branch](https://github.com/jefersonf/PySyft/tree/latency_simulation/syft/).

In fact, the following case is working so far:

```
import torch
import syft as sy
hook = sy.TorchHook(torch)

alice = sy.VirtualWorker(id="alice", hook=hook)
bob  = sy.VirtualWorker(id="bob", hook=hook)
x = torch.tensor([1,2,3])

# alice waits 2 seconds before sending 'x' to bob.
alice.send(x, bob, pending_time=2)

```

**Comment by BBloggsbott** [comment]
@jefersonf Why not just use the change you mentioned [here](https://github.com/OpenMined/PySyft/issues/3007#issuecomment-582028097)? I feel only the virtual workers will need to simulate latency.

**Comment by jefersonf** [comment]
> @jefersonf Why not just use the change you mentioned [here](https://github.com/OpenMined/PySyft/issues/3007#issuecomment-582028097)? I feel only the virtual workers will need to simulate latency.

At first I thought so too, but I think in cases where a tensor is sent to a worker like in the following:

```
torch.tensor([1,2,3]).send(alice, pending_time=2)
```
the same behavior should be hold.

**Comment by Vishal-Ramesh2** [comment]
Ah. Okay.

How can I help with this?

**Comment by BBloggsbott** [comment]
Ah. Okay.

How can I help with this?
