### ISSUE TITLE
Investigate alternatives to Plans

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3027]
Using Plans in CrypTen is both convenient and painful, because we can't easily ask Plans to support crypten specific operations. Hence, we're also exploring alternative solutions, if they exist, to collect (close to arbitrary) operations in a function and send them to another worker.

**Comment by youben11** [comment]
An alternative would be to send the source code of the function definition (we can get it from the function object using the dill library), then each worker will need to run static analysis (using [AST][https://docs.python.org/3/library/ast.html) or a similar library) to make sure the function is safe.

Running static analysis, we can have a whitelist of allowed function calls, and flag as unsafe any function that goes beyond those calls. We can do the same for attributes, however, we will also need to track variable types as  the _objects attribute might be a safe to access on object X but not on object Y. So the whitelist must be a list of (type, func | attr) pairs to have both flexibility and security.

**Comment by iamtrask** [comment]
If it helps - for Tensorflow the current roadmap is to use TFF to create Tensorflow's version of "plans" and then ship those over (still wrapped in a "Plan" like object?)

**Comment by youben11** [comment]
Another alternative would be to jail the execution of the sent function in a secure execution environment. This means that only crypten functionalities are available, no filesystem access, no networking etc. I'm checking this [library](https://github.com/zopefoundation/RestrictedPython) and if we can use it to secure the function sharing across workers.

**Comment by iamtrask** [comment]
Sending whitelisted functions from one machine to another is _exactly_ what Plans are supposed to do - if Plans don't support this use case, we need to fix plans (instead of build an alternative)

**Comment by LaRiffle** [comment]
Closing this as Jail is now being demo-ed.
