### ISSUE TITLE
Translate tutorials to Bengali 

### ISSUE THREAD

**Issue by adventuroussrv** [OpenMined/PySyft#3042]
For the PR, copy the current notebooks and translate the inline text to Bengali, placing the notebooks in the [Bengali](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/translations/bengali) folder under the [translations](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/translations)

- **Only translate English which is in the notebook or generated from code in the notebook. Any English which is coming from the PySyft library itself (such as error messages) should remain in English.**

cc #2782

- [x] Part 01 - The Basic Tools of Private Deep Learning.ipynb
- [x] Part 02 - Intro to Federated Learning.ipynb
- [x] Part 03 - Advanced Remote Execution Tools.ipynb
- [ ] Part 04 - Federated Learning via Trusted Aggregator.ipynb
- [ ] Part 05 - Welcome to the Sandbox.ipynb
- [ ] Part 06 - Federated Learning on MNIST using a CNN.ipynb
- [ ] Part 07 - Federated Learning with Federated Dataset.ipynb
- [ ] Part 08 - Introduction to Plans.ipynb
- [ ] Part 08 bis - Introduction to Protocols.ipynb
- [ ] Part 09 - Intro to Encrypted Programs.ipynb
- [ ] Part 10 - Federated Learning with Secure Aggregation.ipynb
- [x] Part 11 - Secure Deep Learning Classification.ipynb
- [x] Part 12 - Train an Encrypted Neural Network on Encrypted Data.ipynb
- [x] Part 12 bis - Encrypted Training on MNIST.ipynb
- [x] Part 13a - Secure Classification with Syft Keras and TFE - Public Training.ipynb
- [x] Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving.ipynb
- [x] Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb

**Comment by adventuroussrv** [comment]
@jabertuhin @ucalyptus here's the issue for the translations in Bengali language! are you working or would like to translate any notebook?

I'm currently working on 
- [ ] Part 08 - Introduction to Plans.ipynb
- [ ] Part 08 bis - Introduction to Protocols.ipynb
- [ ] Part 09 - Intro to Encrypted Programs.ipynb
- [ ] Part 10 - Federated Learning with Secure Aggregation.ipynb

**Comment by jabertuhin** [comment]
@adventuroussrv I will be working on these notebooks - 

1.  Part 04 - Federated Learning via Trusted Aggregator.ipynb
2.  Part 05 - Welcome to the Sandbox.ipynb

**Comment by ucalyptus** [comment]
I'll do 8 and 9

**Comment by ucalyptus** [comment]
* 6 and 7

**Comment by adventuroussrv** [comment]
Hey! @ucalyptus I have almost completed the  

-  Part 08 - Introduction to Plans.ipynb
-  Part 08 bis - Introduction to Protocols.ipynb
-  Part 09 - Intro to Encrypted Programs.ipynb
-  Part 10 - Federated Learning with Secure Aggregation.ipynb

**Comment by ucalyptus** [comment]
Yeah sorry I made a typo. I'll do 6 and 7

**Comment by adventuroussrv** [comment]
Awesome! Closing the issue for now!

**Comment by ucalyptus** [comment]
[    ] Part 04 - Federated Learning via Trusted Aggregator.ipynb @jabertuhin 
[    ] Part 05 - Welcome to the Sandbox.ipynb @jabertuhin 
[    ] Part 06 - Federated Learning on MNIST using a CNN.ipynb @ucalyptus 
[    ] Part 07 - Federated Learning with Federated Dataset.ipynb @ucalyptus 
[    ] Part 08 - Introduction to Plans.ipynb @adventuroussrv 
[    ] Part 08 bis - Introduction to Protocols.ipynb @adventuroussrv 
[    ] Part 09 - Intro to Encrypted Programs.ipynb @adventuroussrv 
[    ] Part 10 - Federated Learning with Secure Aggregation.ipynb @adventuroussrv

**Comment by adventuroussrv** [comment]
PR for Translation Part 9 & 10

#3049 
#3050

**Comment by ucalyptus** [comment]
@adventuroussrv done

**Comment by ucalyptus** [comment]
@jabertuhin any updates?

**Comment by jabertuhin** [comment]
Hopefully I will be done with the translations by this week.
Sorry, for taking some time.

**Comment by adventuroussrv** [comment]
PR for Part 8 and 8 bis #3096

**Comment by adventuroussrv** [comment]
Hi @jabertuhin @ucalyptus anyone wants to work on the part 3 maybe?

**Comment by jabertuhin** [comment]
Hi, @adventuroussrv .
I have a pending notebook(Part-4) to translate. After completing that I can go for the part 3.

**Comment by jabertuhin** [comment]
PR for Part 4 and 5 [#3121](https://github.com/OpenMined/PySyft/pull/3121)

**Comment by adventuroussrv** [comment]
Part 3 PR #3133

**Comment by ucalyptus** [comment]
@adventuroussrv @jabertuhin All notebooks done?
