### ISSUE TITLE
Create a syft.load(tensor, src=worker_id) functionality

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3043]
This should be equivalent to worker.search, but is supposed to be retrieving information _locally_, when src matches the current worker. (behaviour is supposed to be close to crypten.load)
As is, this function is supposed not to fail and to always return something  (even random) when using in a plan at building.
Details on implementation are not all solved yet.

**Comment by r0cketr1kky** [comment]
Can I work on this @LaRiffle ?

**Comment by gmuraru** [comment]
There is a PR on this, currently linked [here](https://github.com/OpenMined/PySyft/pull/3074). Sorry I did not put the reference in the PR :(
