### ISSUE TITLE
Try fix problem regarding to {RuntimeError} in Ch06 (please see detail thanks) 

### ISSUE THREAD

**Issue by Alfons0329** [OpenMined/PySyft#3045]
The bug can be found here (my pull request)
[here](https://github.com/OpenMined/PySyft/pull/2766), which shows the attempt to fix the GPU error by myself.

It is my first time contributing to open source project, please let me if there is any mistake, thank you so much!

**Comment by karlhigley** [comment]
Let's keep the conversation on this issue over in #2766. Left a comment there about a test failure in the CI checks.
