### ISSUE TITLE
Add Watermark to notebooks

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PySyft#3054]
**Is your feature request related to a problem?**
There are a few issues on GitHub and on the slack group (e.g. #2346) caused when running the tutorial notebooks with a different environment. The environment used to generate the tutorial should be made clear to help users identify problems more easily.

**Describe the solution you'd like**
Add a [watermark](https://github.com/rasbt/watermark) to the top of each tutorial.

The watermark should include:
* Date and time of last update
* versions of tutorial critical packages like `pytorch`
* version of `syft` or hash of most recent commit

Any others?
(I'm happy to open a PR on this once there's a consensus on watermark content)

**Other solutions considered**
* Including OS or GPU/CPU info in watermark
    - While some issues are platform/machine dependent, including this information could make users think it's a requirement to run the notebook

**Comment by BBloggsbott** [comment]
I can get this done

**Comment by BBloggsbott** [comment]
@TTitcombe I've added watermark to one file in tutorials. Can you verify id the information presented in it is enough?

**Comment by BBloggsbott** [comment]
@TTitcombe I've added the watermark to one [notebook](https://github.com/BBloggsbott/PySyft/blob/add-watermarks/examples/tutorials/Part%2001%20-%20The%20Basic%20Tools%20of%20Private%20Deep%20Learning.ipynb) in the tutorials. Can you verify if the information is sufficient?

**Comment by TTitcombe** [comment]
@BBloggsbott I would say no `-m` as it adds a lot of text and may make somebody thing they _need_ your computer architecture for it to run. 

Also, now I'm not sure that we should include the time. Date + hash is enough information to work out the state of the codebase when the tutorial was last edited. Including time + timezone will only add confusion, especially if notebooks get updated by people in different timezones.

I think
```
last updated on: Tue 03 Mar 2020

torch: x.y.z
syft: x.y.z
git hash
```
Is a clean way to provide all the necessary information

**Comment by BBloggsbott** [comment]
Okay.  I 'm having some issues with the openmined's hook with pytorch. I shared it in slack.

**Comment by TTitcombe** [comment]
Hey @BBloggsbott the messages in Slack are temporary. Could you post it here / message me on Slack so I could take a look
