### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by AnchalAgarwal21** [OpenMined/PySyft#3079]
module 'syft' has no attribute 'ID_PROVIDER'
![tempsnip](https://user-images.githubusercontent.com/41802909/75015792-778d9980-54af-11ea-86bf-b77b93e19837.png)

**Comment by karlhigley** [comment]
@AnchalAgarwal21 What PySyft version are you using?

**Comment by AnchalAgarwal21** [comment]
@karlhigley 0.2.3a1

**Comment by karlhigley** [comment]
@AnchalAgarwal21 Huh, haven't seen that issue with that version. Could you share the output of `pip list` and the imports above in the notebook?

**Comment by LaRiffle** [comment]
I have a silly question but have done a full ‘import syft as sy’ before?
I had a similar error when doing strange things during the syft import

**Comment by AnchalAgarwal21** [comment]
@karlhigley 
import torch as th
from torch import nn,optim
import syft as sy
from syft.workers.virtual import VirtualWorker
from syft.exceptions import WorkerNotFoundException

**Comment by AnchalAgarwal21** [comment]
I copied the entire code on another notebook and to my surprise, it didn't give any error but now I have encountered another error.
![tempsnip1](https://user-images.githubusercontent.com/41802909/75114484-2bdc1b00-567c-11ea-82c2-611d5c502344.png)

**Comment by pierrepocreau** [comment]
You forgot to hook torch with `hook = sy.TorchHook(torch) `to extend torch tensors methods.

**Comment by AnchalAgarwal21** [comment]
Thank you @pierrepocreau ..I missed placing the hook torch.
