### ISSUE TITLE
Cache dependencies in CI tests

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3088]
**Is your feature request related to a problem? Please describe.**
Running the tests and tutorials currently takes around 15 minutes, of which 4 minutes or so (~25%) is spent installing dependencies.

**Describe the solution you'd like**
Use [GH Cache Action](https://github.com/actions/cache) to cache the dependencies and speed up the build.

**Describe alternatives you've considered**
- Leave it as is. Slower, but works.
- Speed up the tests and tutorials. Maybe possible, but they will inevitably get slower again over time.

**Additional context**
We'll probably want to hash all of the `pip-dep/*.txt` files in order to come up with the cache key.

**Comment by imskr** [comment]
I would like to work on this @karlhigley

**Comment by karlhigley** [comment]
@imskr Thanks! Feel free to ping me on Slack with any questions.
