### ISSUE TITLE
AttributeError: module 'syft.messaging' has no attribute 'plan'

### ISSUE THREAD

**Issue by DanielMorales9** [OpenMined/PySyft#3091]
I get this problem when connecting to the WebSocketGridClient.  
Can anyone help me with this issue?
```
File "/usr/local/lib/python3.7/site-packages/grid/__init__.py", line 3, in <module>
   from grid.websocket_client import WebsocketGridClient
File "/usr/local/lib/python3.7/site-packages/grid/websocket_client.py", line 30, in <module>
    class WebsocketGridClient(WebsocketClientWorker, FederatedClient):
File "/usr/local/lib/python3.7/site-packages/grid/websocket_client.py", line 478, in WebsocketGridClient
    def serve_encrypted_model(self, encrypted_model: sy.messaging.plan.Plan) -> bool:
AttributeError: module 'syft.messaging' has no attribute 'plan'
```

**Comment by karlhigley** [comment]
It looks like that code was deprecated and later removed in #476, which [suggests](https://github.com/OpenMined/PyGrid/commit/2b543d075b86a6846d815ab5bdba45b551f48654#diff-b1ef8a3aed029ba9fb6663df43b6c7daL16) using PySyft's `syft.grid` module instead.

**Comment by gmuraru** [comment]
@DanielMorales9 is this issue still present?

**Comment by DanielMorales9** [comment]
Hi @gmuraru, after following this it works fine. 

> It looks like that code was deprecated and later removed in #476, which [suggests](https://github.com/OpenMined/PyGrid/commit/2b543d075b86a6846d815ab5bdba45b551f48654#diff-b1ef8a3aed029ba9fb6663df43b6c7daL16) using PySyft's `syft.grid` module instead.
