### ISSUE TITLE
TypeError in compute_q_noisy_max_approx function

### ISSUE THREAD

**Issue by r0cketr1kky** [OpenMined/PySyft#3095]
**Describe the bug**
Type error because of the subtraction between `counts`(which is a list) and `counts[winner]`(which is a float). 

**Expected behavior**
The final answer to this computation should be 0.8

**Screenshots**
![Screenshot from 2020-02-25 21-50-19](https://user-images.githubusercontent.com/39258575/75266815-e86ae380-5818-11ea-9eb3-3cbab288bbcc.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 16.04

**Additional context**
To solve this, there has to be a loop to iterate `counts` so that the correct code should be 
` 
for i in range(len(counts)):
   counts_normalized = noise_eps * (counts[i] - counts[winner])
`

**Comment by pierrepocreau** [comment]
Well sc should be a torch tensor, not a list.

**Comment by r0cketr1kky** [comment]
Ohh, my bad. Thank you for letting me know. You can close this issue.
