### ISSUE TITLE
Implement FV Homomorphic Encryption from Scratch

### ISSUE THREAD

**Issue by youben11** [OpenMined/PySyft#3097]
FV (Fan-Vercauteren) Homomorphic Encryption is one of the leading approaches to homomorphic encryption. While current work is under way within our community to wrap the SEAL homomorphic encryption library, this will have limited portability. However, algorithms which are natively implemented in PySyft can be automatically run across Python, GPUs, Javascript, Android (Kotlin), and iOS (Swift). Thus, it is very advantageous for us to re-implement FV encryption from scratch.

The goal of this project will be to create a new tensor type which allows one to leverage FV to perform encrypted tensor operations.

#### Context

I will be mentoring this project as part of the [Google Summer of Code](https://summerofcode.withgoogle.com/)

#### Required Skills:

- Knowledge of PyTorch and Deep Learning
- Familiarity (or willingness to become familiar) with PySyft
- Ability to either implement the FV algorithm from the [paper](https://eprint.iacr.org/2012/144.pdf), or ability to port an existing C++ implementation ([there](https://github.com/CryptoExperts/FV-NFLlib) [are](http://sealcrypto.org/) [many](https://github.com/jonaschn/awesome-he))

__Difficulty:__ Advanced

While the API aspects of this project are not complex (we have straightforward instructions for how to implement new tensor types), the FV algorithm is non-trivial.

**Comment by imskr** [comment]
Hi @youben11 I would like to work on this!

**Comment by youben11** [comment]
Hi @imskr ! Feel free to ask questions on the #gsoc channel or DM me on slack @Ayoub Benaissa

You can also comment here for any detail regarding the project.

**Comment by vineetjai** [comment]
Hi @youben11 
   I am Vineet Jain, a final year undergraduate student at IIT Kharagpur. I had experience in DL, TensorFlow, PyTorch, and PySyft. I had done my past summer internship in Federated Learning Project(where I had implemented FL on Raspberry pi's (as clients' server) using PySyft ) where I had used PySyft, Tensorflow federated learning, and Tensorflow Federated Core. I am interested in the PySyft projects. I would like to work on this.

**Comment by hskang9** [comment]
@youben11 is the port result can be rust code which is compiled to wasm?

**Comment by youben11** [comment]
@hskang9 the project should be implemented in Python.

**Comment by hskang9** [comment]
ok thank you @youben11

**Comment by KevinMathewT** [comment]
Hi @youben11, I believe this project is available for GSoC, I know I'm a little late but I would like to ask if this one is already assigned, because I'm interested in working on this one.

**Comment by youben11** [comment]
Hi @KevinMathewT, applications are still open for GSoC.
