### ISSUE TITLE
Implement Auto-Scaling on Google Cloud

### ISSUE THREAD

**Issue by hericlesme** [OpenMined/PySyft#3099]
### Description

In this project, you will implement functionality necessary to automatically spin-up Google cloud machines, load a PyGrid instance, run a training job, and tear down the instance upon completion (depositing the results into another long-running instance). The primary feature will be the ability to run a “hyperparameter sweep”, as exemplified below.

```python
parameters = {“alpha” : [0, 0.01, 0.02], “batch_size” : [32,64]}

gcloud = gr.GoogleCloud(credentials)

cluster = gcloud.LazyCluster(n_machines=10, 
                            type="n-series", 
                            priority="low",
                            eviction_policy="Delete",
                            max_price_usd=0.55,
                            reboot_max_price_usd=0.65)

cluster.sweep(model=model,
             parameters=parameters,
             optim=optim.SGD,
             results_node=grid['my node']
             )
```

### Context

I will be mentoring this project as part of the [Google Summer of Code](https://summerofcode.withgoogle.com/)

Also, this year we have some plans for PyGrid, along with our other projects, including a focus on production: Deployment on Cloud Providers (GCP, Amazon, Azure). You can check out the PyGrid Roadmap [here](https://github.com/OpenMined/Roadmap/tree/master/pygrid_team).

### Required Skills:

- Knowledge of [PyTorch](https://pytorch.org/) and Deep Learning
- Familiarity (or willingness to become familiar) with [PySyft](https://github.com/OpenMined/PySyft)
- Familiarity (or willingness to become familiar) with [Google Cloud’s Infrastructure](https://cloud.google.com/docs)

**Difficulty**: Beginner

While this is a sizeable project, the core functionality is relatively straightforward (provision machines, install and start PyGrid servers, and run training scripts). Furthermore, there are plenty of tutorials on how to run PyGrid servers and how to run Google Cloud machines.

If you are new to PyGrid and want to learn more about it, try out the tutorials. A comprehensive list of tutorials can be found [here](https://github.com/OpenMined/PySyft/tree/master/examples/tutorials/grid). These tutorials cover how to create a PyGrid node and what operations you can perform.

### Useful Links

- PyTorch - https://pytorch.org/blog
- PySyft - https://github.com/OpenMined/PySyft
- PyGrid - https://github.com/OpenMined/PyGrid
- GCP Docs - https://cloud.google.com/docs
- GCloud APIs for Python - https://cloud.google.com/python/docs/reference
- Google APIs (Python Client) - https://github.com/googleapis/google-api-python-client 
- Google Summer of Code - https://summerofcode.withgoogle.com
  - [Timeline](https://developers.google.com/open-source/gsoc/timeline)
  - [Student Guide](https://google.github.io/gsocguides/student/)
  - [OpenMined Org.](https://summerofcode.withgoogle.com/organizations/5561599089180672)

_List of all GSoC project ideas [here](https://docs.google.com/document/d/1OA8277RB9ZN8u7Wgn6NqZK7tzixnZbSlkfulyqoo2G4/edit?usp=sharing)._

**Comment by iamtrask** [comment]
Note: we want to allow for automatic node teardown after calling .sweep() as an option - where it deposits the results into a "main cluster node". In other words, if I spin up a cluster of 10 workers, this is ACTUALLY a cluster of 10 workers and 1 master, where the master can store resources produced by the 10 workers.

**Comment by carlodavid012** [comment]
I'd like to work on this project

**Comment by hericlesme** [comment]
Cool, @carlodavid012! I saw that you already know PySyft. I also think that basic PyGrid concepts can be useful. Feel free to chat with me if you need anything!

**Comment by MukulMaheshwari** [comment]
I am working on it.

**Comment by neeravjain24** [comment]
I have no experience related to Cloud but I am trying to learn PySyft .
I really want to contribute to this project.
Please can you help me .

**Comment by hericlesme** [comment]
Great! There are a lot of interested people.  I think you could also talk to each other about the issue. :rocket: :nerd_face:

**Comment by neeravjain24** [comment]
Is there any particular channel for this project or should I message in gsoc slack group

**Comment by hericlesme** [comment]
Yess @neeravjain24! Don't worry if you're not familiar with GCloud. There's a lot of tutorials, docs and codelabs to learn. I also recommend taking a look at the PyGrid tutorial. The links are in the issue description.

GCloud links:
https://cloud.google.com/getting-started
https://codelabs.developers.google.com/cloud/

**Comment by hericlesme** [comment]
> Is there any particular channel for this project or should I message in gsoc slack group

You can use the #gsoc channel :slightly_smiling_face:

**Comment by arghyadeep99** [comment]
I would like to work on this project and I am willing to learn PySyft. Also, I am learning about GCP already.

**Comment by Sasha1-0-0-9** [comment]
I'd like to contribute to this project

**Comment by hericlesme** [comment]
Great, guys. I'm thinking of creating a slack channel for this issue. It is even better to discuss it there too. What do you think? :slightly_smiling_face:

**Comment by sahiljit** [comment]
Hey guys, 
I am pursuing B.Tech from Unversity of Delhi and fully interested in contributing to this project. I also have started working on this.

**Comment by sahiljit** [comment]
Hey guys, 
I am pursuing B.Tech from University of Delhi and am fully interested in contributing to this project. I have also started working on this.

**Comment by iamtrask** [comment]
Wow! Really?
