### ISSUE TITLE
Implement ZKP From Scratch in PyTorch

### ISSUE THREAD

**Issue by Jasopaum** [OpenMined/PySyft#3100]
Zero-knowledge proofs have an important role to play in the future of verified machine learning prediction. However, no deep learning framework has the ability to perform verified computation of neural networks using ZKPs.
Furthermore, algorithms which are natively implemented in PySyft can be automatically run across Python, GPUs, Javascript, Android (Kotlin), and iOS (Swift). Thus, it is very advantageous for us to re-implement ZKP encryption from scratch using PyTorch tensor operations.
In this project, you will implement from scratch or port an existing ZKP library into PyTorch operations. This will allow us to generate, evaluate, and verify ZKP graphs across all platforms supported by PySyft.

We will be using the following resources: 
- https://eprint.iacr.org/2013/279
- https://eprint.iacr.org/2017/013
- https://github.com/Charterhouse/pysnark (reference implementation)
This is not totally blocked, we can discuss about other protocols if you think they could be suitable but do read these ones before anything else.

Required Skills:
- Knowledge of PyTorch and Deep Learning
- Familiarity (or willingness to become familiar) with PySyft
- Ability to understand the mathematics of ZKPs and/or current libraries implementing them

Difficulty: Advanced
While the API shouldn’t be complex, ZKP algorithms are challenging to understand and implement. There are, however, many great implementations to use as references.

**Comment by Kritikalcoder** [comment]
I'd like to contribute to this

**Comment by Jasopaum** [comment]
Note: I added a few resources in the issue

**Comment by pierrepocreau** [comment]
I also would like to work on this project.

**Comment by jimboH** [comment]
Hi @Jasopaum , I would like to work on this issue. I have made a merged PR at https://github.com/OpenMined/PySyft/pull/3092 and also filled up the application form. I would like to know how could I go further on this issue. Thank you!

**Comment by Jasopaum** [comment]
Could you guys (and also others that could be interested) contact me on Slack (Jason Paumier) so that we can talk about this?

**Comment by vineetjai** [comment]
Hi @Jasopaum
I am Vineet Jain, a final year undergraduate student at IIT Kharagpur. I had experience in DL, TensorFlow, PyTorch, and PySyft. I had done my past summer internship in Federated Learning Project(where I had implemented FL on Raspberry pi's (as clients' server) using PySyft ) where I had used PySyft, Tensorflow federated learning, and Tensorflow Federated Core. I am interested in PySyft projects. I am looking forward to contributing!

**Comment by jon-chuang** [comment]
Hi, what is the movement like on this issue? Could there be an elaboration on the potential use-cases? For instance, is ZK to be used wrt to MPC protocols? Is one to use interactive challenges or SNARKs? Or is this meant to be a standalone system? What are the design goals? For instance, ZK could introduce about ~1000x computational overhead, although for good schemes, communication and verification could be cheap. 

I am not convinced this could gel well with GPU computations, since one requires to store and encode all the intermediate values of a computation, unless the entire ZKP encoding was performed simultaneously on GPU.

**Comment by karynaur** [comment]
Hey! I would love to work on this issue!
