### ISSUE TITLE
Q: websocket-mnist example dataloader

### ISSUE THREAD

**Issue by klize** [OpenMined/PySyft#3101]
I have two machines and try to implement my own federated learning structure.

As the advanced example shows, I placed `WebsocketServerWorker` and `WebsocketClientWorker` like below:

Client:
```python
worker = websocket_server.WebsocketServerWorker(...)
```

Server:
```python
client = websocket_client.WebsocketClientWorker(...)
```

This is the basic implementation to play federated learning along with the design of syft.
After writing two lines above and here my questions arise:

* Q1: Why the dataloader, i,e FederatedDataLoader is in server's code ?

Server
```python
client = websocket_client.WebsocketClientWorker(...)
federated_train_loader = sy.FederatedDataLoader(
    datasets.MNIST(
        "../data",
        train=True,
        download=True,
        transform=transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
        ),
    ).federate(tuple(workers)),
    batch_size=args.batch_size,
    shuffle=True,
    iter_per_worker=True,
    **kwargs,
)
```

In this way Central server must download the data that is supposed to be held by clients.
In Federated Learning, data must not be exposed to the server even in the example codes.
Actually I checked that if i run the above, mnist data is downloaded on the server side and federate them to clients.

websocket-mnist-parallel example, in fact, is written in the way i expected, e.g. dataset is loaded on client's machines only.
 
* Q2: Can `torch.utils.data.DataLoader` also be accessed remotely by server ?
         In other words, Can I access a batch of client dataset remotely like `websocket-mnist-example-parallel accesses and processes the client dataset that reside only inside client's machine ?

All i need is just to define the dataloader in the client's code and tell client's while iterating over the batches do something for each one of them.

Client:
```python
worker = websocket_server.WebsocketServerWorker(...)
data_loader = torch.utils.data.DataLoader(...)

worker.start()
```

Server:
```python
def train(...):
    # remotely access to a batch of client data -> define some logic to do remote execution with the batch 
    # do something

client = websocket_client.WebsocketClientWorker(...)
train()


```

I hope this issue to give you any insights for improving this library if possible.
And of course, I will try to figure it out to work in my intention but i will be much appreciated if you give me any helps :)

-------------------------------------------------------------
Additional tryout

Server:
```python
for worker in client_workers_list:
    self.logger.debug(worker._send_msg_and_deserialize("_create_data_loader",
                                                                                            dataset_key="mnist"))
```
I tried to set `DataLoader` remotely and get batches from it, but client log says `DataLoader`
can't be serialized.

```bash
Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at .../federated-client-syft/venv/lib/python3.6/site-packages/syft/workers/websocket_server.py:95> exception=TypeError("can not serialize 'DataLoader' object",)>
Traceback (most recent call last):
  File ".../federated-client-syft/venv/lib/python3.6/site-packages/syft/workers/websocket_server.py", line 113, in _producer_handler
    response = self._recv_msg(message)
  File "/.../federated-client-syft/venv/lib/python3.6/site-packages/syft/workers/websocket_server.py", line 124, in _recv_msg
    return self.recv_msg(message)
  File ".../federated-client-syft/venv/lib/python3.6/site-packages/syft/workers/base.py", line 315, in recv_msg
    bin_response = sy.serde.serialize(response, worker=self)
  File ".../federated-client-syft/venv/lib/python3.6/site-packages/syft/serde/serde.py", line 43, in serialize
    return strategy(obj, worker, simplified, force_full_simplification)
  File ".../federated-client-syft/venv/lib/python3.6/site-packages/syft/serde/msgpack/serde.py", line 331, in serialize
    return _serialize_msgpack_binary(simple_objects)
  File ".../federated-client-syft/venv/lib/python3.6/site-packages/syft/serde/msgpack/serde.py", line 285, in _serialize_msgpack_binary
    binary = msgpack_lib.dumps(simple_objects)
  File ".../federated-client-syft/venv/lib/python3.6/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 286, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 283, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'DataLoader' object
```
DataLoader cannot be serialized and remotely executed ?

**Comment by b02202050** [comment]
Is there any reply of this question?
Thanks @klize  for pointing out the question so clear than my post (https://github.com/OpenMined/PySyft/issues/2901)
