### ISSUE TITLE
syft.exceptions.UndefinedProtocolTypeError: syft.messaging.message.Operation is not defined in the protocol file

### ISSUE THREAD

**Issue by newne** [OpenMined/PySyft#3102]
when i installed pysyft,  run  _python run_websocket_server.py_  in pysyft-master directoriy. it comes out "syft.exceptions.UndefinedProtocolTypeError: syft.messaging.message.Operation is not defined in the protocol file". 
    i have tried to re-install the system(ubuntu 16.04) and pysyft, but it did't work .   
    On my other machine, the same method is successful. What should i do to solve the problem?

**Comment by AndrewZhou924** [comment]
I met the same Error as your when importing syft.
Did anyone solve this problem?

**Comment by jazken** [comment]
the latest version of syft-proto seems to have issues.
try: pip install syft-proto==0.1.1a1.post20

**Comment by newne** [comment]
> the latest version of syft-proto seems to have issues.
> try: pip install syft-proto==0.1.1a1.post20

Perfect solution！

**Comment by karlhigley** [comment]
The [PR corresponding to those changes in PySyft](https://github.com/OpenMined/PySyft/pull/3090) hadn't yet been reviewed and merged. New PySyft version with those changes coming soon.

**Comment by karlhigley** [comment]
Should be fixed by recent releases (v0.2.3 or v0.2.4.)
