### ISSUE TITLE
Wrap Open-License Zero-Knowledge Proof Library

### ISSUE THREAD

**Issue by Benardi** [OpenMined/PySyft#3104]
Zero-knowledge proofs have an important role to play in the future of verified machine learning prediction. However, no deep learning framework has the ability to perform verified computation of neural networks using ZKPs. In this project, you will wrap an existing ZKP library into a new tensor type allowing users of PySyft to generate, evaluate, and verify tensor computations.

## Context
I will be mentoring this project as part of the [Google Summer of Code](https://summerofcode.withgoogle.com/)

Also, this year we have some plans for PyGrid, along with our other projects, including a focus on production: Deployment on Cloud Providers (GCP, Amazon, Azure). You can check out the PyGrid Roadmap [here](https://github.com/OpenMined/Roadmap/tree/master/pygrid_team).

## Required Skills:

* Knowledge of [PyTorch](https://pytorch.org/) and Deep Learning
* Familiarity (or willingness to become familiar) with [PySyft](https://github.com/OpenMined/PySyft)
* Ability to wrap an existing Python, C++, Rust, or Javascript library within Python

**Difficulty**: Easy

There are many libraries to choose from, [some of](https://github.com/kendricktan/zk-snarks-py) which are already in Python.

List of all GSoC project ideas [here](https://docs.google.com/document/d/1OA8277RB9ZN8u7Wgn6NqZK7tzixnZbSlkfulyqoo2G4/edit?usp=sharing).

## Useful Links

Useful Links
* PyTorch - https://pytorch.org/blog
* PySyft - https://github.com/OpenMined/PySyft
* PyGrid - https://github.com/OpenMined/PyGrid
* Google Summer of Code - https://summerofcode.withgoogle.com
   + [Timeline](https://developers.google.com/open-source/gsoc/timeline)
   + [Student Guide](https://google.github.io/gsocguides/student/)
   + [OpenMined Org](https://summerofcode.withgoogle.com/organizations/5561599089180672)

**Comment by vineetjai** [comment]
Hi @Benardi 
I am Vineet Jain, a final year undergraduate student at IIT Kharagpur. I had experience in DL, TensorFlow, PyTorch, and PySyft. I had done my past summer internship in Federated Learning Project(where I had implemented FL on Raspberry pi's (as clients' server) using PySyft ) where I had used PySyft, Tensorflow federated learning, and Tensorflow Federated Core. I am interested in PySyft projects. I am looking forward to contributing!

**Comment by codeboy5** [comment]
Hi @Benardi I was interested in working on this. I have experience in DL, TF , Pytorch. I have gone through the tutorials and i am familiar with the codebase.

**Comment by Benardi** [comment]
@codeboy5  and those interested please join the [Openmined Slack](https://openmined.slack.com/messages/team_pysyft), and contact me over there (username Benardi Nunes).

**Comment by imraniac** [comment]
Hi, My name is Imran Alam, I m an undergraduate student from Jadavpur University. I am interested in working on this project.

**Comment by shaanrockz** [comment]
Hi, Shahnawaz Alam here, graduate student from RWTH Aachen University germany. I am also interested to work on this project. I tried joining the link above but I suppose I cannot join with my old slack account. Its showing "Contact the workspace administrator for an invitation" @Benardi

**Comment by theparanoidprogrammer** [comment]
Hi @Benardi 

> Benardi Nunes

Its asking for a username and password. I dont have an account in that workspace, can you send an invite link please. Thanks.

**Comment by theparanoidprogrammer** [comment]
Hello @Benardi . Im currently a Computer Science Junior at LUMS Pakistan. I have experience with Deep Learning,and network Security. I would love to work on this project. Looking forward to being guided by you. Can you please give me an invite link to the Slack platform. Thanks.

**Comment by Benardi** [comment]
> @codeboy5 and those interested please join the [Openmined Slack](https://openmined.slack.com/messages/team_pysyft), and contact me over there (username Benardi Nunes).

@theparanoidprogrammer

**Comment by theparanoidprogrammer** [comment]
![Screenshot (95)](https://user-images.githubusercontent.com/47157583/77188898-8ab87700-6af8-11ea-8934-c23ea1945a80.png)
its asking for a username and password? i dont have an openmined email. im unable to join the slack :(  
@Benardi

**Comment by theparanoidprogrammer** [comment]
> > @codeboy5 and those interested please join the [Openmined Slack](https://openmined.slack.com/messages/team_pysyft), and contact me over there (username Benardi Nunes).
> 
> @theparanoidprogrammer

Thanks :) just joined
