### ISSUE TITLE
Custom federated learning network (LSTM)

### ISSUE THREAD

**Issue by Adblu** [OpenMined/PySyft#3105]
So, Im practicing federated learning with PyTorch, and I want to implement LSTM network for text generation. 

Here is the network: 
`
class LSTM(nn.Module):

    def __init__(self, vocab_size, embed_size, hidden_size, num_layers):
        super(LSTM, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_size)  
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers, batch_first=True)
        self.linear = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, h):
        x = self.embed(x)

        out, (h, c) = self.lstm(x, h)  # (input , hidden state)

        out = out.reshape(out.size(0) * out.size(1), out.size(2))

        out = self.linear(out)
        return out, (h, c)
`
But, because federated learning requires dataset to be in specific form:

`base = sy.BaseDataset(torch.tensor(train), torch.tensor(test))
base_federated = base.federate((bob, adrian, patrycja, alice))
federated_train_loader = sy.FederatedDataLoader(base_federated, batch_size=args.batch_size)
`
Im getting an error that wrong object is passed to the network:

`RuntimeError: input.size(-1) must be equal to input_size. Expected 6431, got 0
`

I know that, this is because of how the data is structured:
`(Wrapper)>[PointerTensor | me:29040208176 -> bob:89708341131]
`
`
20 # batch size 
`
`
<class 'torch.Tensor'> # type`

and what I actually need is:

> `tensor([[ 112,  193,  592,  ...,  503,  143,  630],
        [ 492,   96, 1080,  ...,  378, 1106,   73],
        [ 284,  386,   97,  ...,    0,  284, 1502],
        ...,
        [  44,   45,   17,  ..., 5666,    0, 5667],
        [ 783, 6020,    0,  ...,    0,  178,  206],
        [   0,  151,   79,  ..., 6408, 5044,   77]])`

bare tensor data. 

So my question is, how to strip that weird `(Wrapper)>[PointerTensor | me:29040208176 -> bob:89708341131]
`
and obtain raw data from that sensor ?

**Comment by mothukuriv** [comment]
hi,
wher you able to fix this error message
