### ISSUE TITLE
Error installing PySyft(syft package)

### ISSUE THREAD

**Issue by shuvamlal9** [OpenMined/PySyft#3112]
**Getting trouble in installing syft package**
I have cloned the pysyft repository and installed it in my local pc. 
After that, I followed the exact steps as written in the INSTALLATION.md.

`python setup.py install` command runs successfully but while testing using `python setup.py test` gives me the following error.

**Screenshots**
![Error](https://user-images.githubusercontent.com/38887333/75441027-e6bd2f00-5982-11ea-91d2-f1303371a68c.png)

**Desktop**
 - Windows 10

**Comment by karlhigley** [comment]
Make sure you have the latest version of the PySyft master branch and the latest version of syft-proto. This error indicates an incompatibility between your versions of the two.

**Comment by karlhigley** [comment]
@shuvamlal9 Any luck with upgrading?

**Comment by shuvamlal9** [comment]
@karlhigley nope still struggling to get the latest version.
I did what's given there to install the syft package but I'm not able to load that package.

**Comment by karlhigley** [comment]
@shuvamlal9 What's the latest commit you have on the `master` branch?

**Comment by shuvamlal9** [comment]
@karlhigley I have **commit 7d61c7** on my master branch. Previously, I wrote a simple article for installing pysfyt and get get rid of zstd error [(here)](https://medium.com/secure-and-private-ai-writing-challenge/installing-pysyft-package-ffa1ff0ad83c), but that doesn't seem to work now.

**Comment by karlhigley** [comment]
Ah, okay! That's from a few weeks ago, before v0.2.3 was released. I'm about to release v0.2.4 in the next day or two, so you can do one of these things:
* Update your master branch to the latest commit on the main repo (currently `784cd9df`)
* Install v0.2.3 (and the corresponding version of `syft-proto` listed in the requirements file)
* Install v0.2.4 (once it's released)

**Comment by karlhigley** [comment]
@shuvamlal9 Just released v0.2.4. Let me know if that works for you!

**Comment by LaRiffle** [comment]
_(Maybe not the good place but this a feedback I just got)_
**For Windows Users**
Install Microsoft VIsual C++ 14.0 first helps a lot

**Comment by shuvamlal9** [comment]
Thanks @karlhigley, v0.2.4 seems to work. Thanks a lot for the help.
