### ISSUE TITLE
Support for transfer learning with feature extraction

### ISSUE THREAD

**Issue by gconst02** [OpenMined/PySyft#3116]
**Is your feature request related to a problem? Please describe.**
Current version of [`federated_client.py`](https://github.com/OpenMined/PySyft/blob/master/syft/federated/federated_client.py#L60) optimizes **all** parameters of the model.
```
self.optimizer = optimizer(model.parameters(), **optimizer_args)
```

For [transfer learning with feature extraction](https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html), only the classifier needs to be optimized. 

**Describe the solution you'd like**
[train_config.py](https://github.com/OpenMined/PySyft/blob/master/syft/federated/train_config.py#L27) already accepts `optimizer_args` but cannot specify `params` parameter of the optimizer (if you do default you get `TypeError: __init__() got multiple values for argument 'params'` due to the default `model.parameters()`). 

This can be modified to optionally set `params` if appears in `optimizer_args` or else use current behavior , i.e.,
```
optimizer = getattr(th.optim, optimizer_name)
optimizer_args.setdefault("params", model.parameters())
self.optimizer = optimizer(**optimizer_args)
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AniTho** [comment]
Is this problem somewhat like what we do with fastai library that is at the beginning, we freeze all the layer and only train and optimize the final classifier layer and then we unfreeze the top layers to start optimizing the complete model?

**Comment by gconst02** [comment]
@AniTho I haven't used fastai but from you described:

> we freeze all the layer and only train and optimize the final classifier layer 

-> Is transfer learning with feature extraction

> and then we unfreeze the top layers to start optimizing the complete model

-> Is transfer learning with fine-tuning

With this change, we will have the flexibility to specify which `params` to optimize.
