### ISSUE TITLE
Sigmoid in SMPC failing for some shapes

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3131]
**Describe the bug**
 Examples to illustrate:

Working
```python
a = torch.Tensor([1,2,3])
a = a.fix_precision().share(bob, alice, crypto_provider = crypto_provider, requires_grad = True)
torch.nn.Sigmoid()(a)
```
Not working
```python
a = torch.Tensor([[1,2,3],[4,5,6]])
a = a.fix_precision().share(bob, alice, crypto_provider = crypto_provider, requires_grad = True)
torch.nn.Sigmoid()(a)
```
Error: `AssertionError: Must be batches of square matrices`

(same with `requires_grad=False`)

The error seems linked to tensor shape

**Comment by AlanAboudib** [comment]
It worked before by the way. Like a month ago

**Comment by karlhigley** [comment]
Might need to add a test for this.

**Comment by gmuraru** [comment]
I can take it @LaRiffle
