### ISSUE TITLE
Remove ZSTD

### ISSUE THREAD

**Issue by mccorby** [OpenMined/PySyft#3134]
**Is your feature request related to a problem? Please describe.**
ZSTD is used for compression in our serde process. However we don't need extra compression as we move to Protobuf.
ZSTD is usually a source of problems when installing PySyft with different hacks to solve it.

**Describe the solution you'd like**
Remove ZSTD dependency.
This will require removing the tests and its use in serde.

**Describe alternatives you've considered**
Protobuf covers compression.

**Additional context**

**Comment by r0cketr1kky** [comment]
Hi @mccorby , I would like to work on this.
So, I guess I would need to remove the ZSTD functionalities in the test folder right? Is that it? Or do I need to remove ZSTD from the compression.py file in `PySyft/syft/serde/` too?

**Comment by karlhigley** [comment]
We'll probably [still want compression](https://eng.uber.com/trip-data-squeeze-json-encoding-compression/) with Protobuf, but we can probably use zlib instead of zstd (if that's any easier to install.)

**Comment by mccorby** [comment]
Could we proceed with two steps? First remove ZSTD, then add another compression tool?

**Comment by karlhigley** [comment]
Sounds good to me!

**Comment by mccorby** [comment]
@r0cketr1kky : Ideally, ZSTD should be removed from any place where it's used. This should include:
- Production code
- Tests
- Requirement files

**Comment by rimijoker** [comment]
Hey, @mccorby I would like to work on this, is this issue taken up by someone?

**Comment by refactormyself** [comment]
@r0cketr1kky are working on this?

**Comment by r0cketr1kky** [comment]
Yes, I am working on it. Would be great to get some help though. You can
reach out to me on Slack @RakshitNaidu

**Comment by refactormyself** [comment]
@r0cketr1kky sorry, a PR was approved on this issue. I think you can still check it and review if you have some suggestions. Would you work on adding zlib? @karlhigley kind of indicated that it will be a good replacement.
Since you have started working on this, adding zlib should be easy. Let me know so I'll stop working on it.

**Comment by r0cketr1kky** [comment]
Not sure about how to add zlib to this. You can continue with this, I shall
drop out due to some other work.

**Comment by gmuraru** [comment]
Sooo...who is working on this issue? @refactormyself @r0cketr1kky?

**Comment by refactormyself** [comment]
PR #3150 should have closed this issue

**Comment by gmuraru** [comment]
Then we can close this issue.
