### ISSUE TITLE
Transfer Learning using PySyft

### ISSUE THREAD

**Issue by SanaAwan5** [OpenMined/PySyft#3138]
I am trying to implement transfer learning via feature extraction by modifying the tutorial "Part 12 bis: Encrypted Training on MNIST". I use mobilenet_v2 pretrained on ImageNet by importing the pretrained model from torchvision.models.mobilenet_v2. I replace the final classifier layer so that it works for the 10 classes from MNIST as follows: 
model.classifer = nn.Linear(1280,10).
 I get the following error:
****AttributeError: 'NoneType' object has no attribute 'is_wrapper'**** 
**To  Reproduce**
from torchvision import models
Modify the 9th cell of the tutorial as follows:
**#model = Net()
model = models.mobilenet_v2(pretrained = True)
model.classifier=nn.Linear(1280,10)**
model = model.fix_precision().share(*workers, crypto_provider=crypto_provider, requires_grad=True)
optimizer = optim.SGD(model.parameters(), lr=args.lr)
optimizer = optimizer.fix_precision() 

for epoch in range(1, args.epochs + 1):
    
    train(args, model, private_train_loader, optimizer, epoch)
    
    test(args, model, private_test_loader)**_

**Expected behavior**

I expected the training to proceed normally but program fails at train() function call.  I realize I need to replace some layers in the pre-trained model, such as MaxPooling with AvgPooling. I thought it would be straight-forward and loading pre-trained models would be built into Syft. Can somebody please guide on the rough steps on to proceed? I this functionality expected to be included in future versions?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Ubuntu
 - Version [e.g. 22]18.04

**Additional context**
**Error Trace**
AttributeError                            Traceback (most recent call last)
<ipython-input-9-3a7be82641dc> in <module>
     12 for epoch in range(1, args.epochs + 1):
     13 
---> 14     train(args, model, private_train_loader, optimizer, epoch)
     15 
     16     test(args, model, private_test_loader)

<ipython-input-7-9fe76535cf5b> in train(args, model, private_train_loader, optimizer, epoch)
      7         optimizer.zero_grad()
      8 
----> 9         output = model(data)
     10         end_model_update = time.time()
     11         local_model_update_time = end_model_update - start_model_update

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torchvision/models/mobilenet.py in forward(self, x)
    157 
    158     def forward(self, x):
--> 159         return self._forward_impl(x)
    160 
    161 

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torchvision/models/mobilenet.py in _forward_impl(self, x)
    151         # This exists since TorchScript doesn't support inheritance, so the superclass method
    152         # (this one) needs to have a name other than `forward` that can be accessed in a subclass
--> 153         x = self.features(x)
    154         x = x.mean([2, 3])
    155         x = self.classifier(x)

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
     98     def forward(self, input):
     99         for module in self:
--> 100             input = module(input)
    101         return input
    102 

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
     98     def forward(self, input):
     99         for module in self:
--> 100             input = module(input)
    101         return input
    102 

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py in forward(self, input)
    343 
    344     def forward(self, input):
--> 345         return self.conv2d_forward(input, self.weight)
    346 
    347 class Conv3d(_ConvNd):

~/Desktop/PySyft/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py in conv2d_forward(self, input, weight)
    339                             weight, self.bias, self.stride,
    340                             _pair(0), self.dilation, self.groups)
--> 341         return F.conv2d(input, weight, self.bias, self.stride,
    342                         self.padding, self.dilation, self.groups)
    343 

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/generic/frameworks/hook/trace.py in trace_wrapper(*args, **kwargs)
     81                 syft.hook.trace.logs.append((command, response))
     82             else:
---> 83                 response = func(*args, **kwargs)
     84 
     85             return response

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/generic/frameworks/hook/hook.py in overloaded_func(*args, **kwargs)
    603                 handle_func_command = syft.framework.Tensor.handle_func_command
    604 
--> 605             response = handle_func_command(command)
    606 
    607             return response

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/frameworks/torch/tensors/interpreters/native.py in handle_func_command(cls, command)
    298             # Send it to the appropriate class and get the response
    299             try:
--> 300                 response = new_type.handle_func_command(new_command)
    301             except RuntimeError:
    302                 # Change the library path to avoid errors on layers like AvgPooling

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/frameworks/torch/tensors/interpreters/autograd.py in handle_func_command(cls, command)
    259 
    260         # Send it to the appropriate class and get the response
--> 261         response = new_type.handle_func_command(new_command)
    262 
    263         # Put back AutogradTensor on the tensors found in the response

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/frameworks/torch/tensors/interpreters/precision.py in handle_func_command(cls, command)
    854 
    855         # Send it to the appropriate class and get the response
--> 856         response = new_type.handle_func_command(new_command)
    857 
    858         # Put back FixedPrecisionTensor on the tensors found in the response

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/frameworks/torch/tensors/interpreters/additive_shared.py in handle_func_command(cls, command)
    957             pass
    958         if not isinstance(cmd, str):
--> 959             return cmd(*args, **kwargs)
    960 
    961         tensor = args[0] if not isinstance(args[0], (tuple, list)) else args[0][0]

~/Desktop/PySyft/venv/lib/python3.8/site-packages/syft-0.2.3a3-py3.8.egg/syft/frameworks/torch/tensors/interpreters/precision.py in conv2d(input, weight, bias, stride, padding, dilation, groups, padding_mode)
    697             # Currently, kwargs are not unwrapped by hook_args
    698             # So this needs to be done manually
--> 699             if bias.is_wrapper:
    700                 bias = bias.child
    701 

AttributeError: 'NoneType' object has no attribute 'is_wrapper'

**Comment by andrijdavid** [comment]
I will take a look at it.

**Comment by SanaAwan5** [comment]
Thanks! Looking forward to your reply.
