### ISSUE TITLE
FLOptimizer

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3141]
**Is your feature request related to a problem? Please describe.**
Some optimizers (such as Adam) do not work with Federated Learning by default because they maintain a list of the N recent gradietns in a cache. For example, take this demo (https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2002%20-%20Intro%20to%20Federated%20Learning.ipynb) and replace the optimizer with Adam and you'll geet a bug.

The solution is to have a separate optimizer for each worker in the FL process which you use at the appropriate time.

**Describe the solution you'd like**

Obviously this would be really annoying to have to write by hand every time... so please create a FLOptimizer which will - under the hood - maintain a list of optimizer objects, one for each worker - and use them in the appropriate context,.

**Comment by roshray** [comment]
I will like to take this @iamtrask .

**Comment by gmuraru** [comment]
Thank you! I assigned you @roshray :D

**Comment by iamtrask** [comment]
@roshray please DM me on slack when you're done - we have someone who needs this feature asap

**Comment by roshray** [comment]
Sure @iamtrask

**Comment by ratmcu** [comment]
is this issue fixed? or @roshray still working on it?

**Comment by thehimalayanleo** [comment]
I would like to work on this issue @iamtrask, if it's still open. Do you want to work on this together @ratmcu?

**Comment by rimijoker** [comment]
Can I take up this issue?
