### ISSUE TITLE
Can I define my own fitting algorithm ?

### ISSUE THREAD

**Issue by klize** [OpenMined/PySyft#3145]
To run a federated learning with `WebsocketClientWorker` and `WebsocketServerWorker` with `_fit` method in FederatedClient.py, I want to additional steps in it.

Here is the method implementation
```python
    def _fit(self, model, dataset_key, loss_fn, device="cpu"):
        model.train()
        data_loader = self._create_data_loader(
            dataset_key=dataset_key, shuffle=self.train_config.shuffle
        )

        loss = None
        iteration_count = 0

        for _ in range(self.train_config.epochs):
            for (data, target) in data_loader:
                # Set gradients to zero
                self.optimizer.zero_grad()

                # Update model
                output = model(data.to(device))
                loss = loss_fn(target=target.to(device), pred=output)
                loss.backward()
                self.optimizer.step()

                # Update and check interation count
                iteration_count += 1
                if iteration_count >= self.train_config.max_nr_batches >= 0:
                    break

        return loss
```

Since DataLoader must be defined on server side to run a federated learning system with socket workers and i am not able to get a kind of pointers of batches from client side for now, I am supposed to remotely execute the `fit` function above like `websocket-mnist-example-parallel` is doing by `async def fit_model_on_worker()`. after sending `TrainConfig` to clients.

Here I want some kind of _clipping_ delta of model weights between somewhere in _#Update model lines_. 
```python
 # Update model
            output = model(data.to(device))
            loss = loss_fn(target=target.to(device), pred=output)
            loss.backward()
            self.optimizer.step()
```
For example in the case of Keras, it provides a callback structure between batches or epochs.
This is exactly what i need to do. Can I do this kind of things with recent version of PySyft ?
Is addtional Implementation required ?

This looks like a new feature in PySyft so far. If not, please close this issue :).

**Comment by maodong2056** [comment]
hello，have u solved this problem？i want to define my own fitting algorithm, but "async def async_fit" can't find the "fit" function.
