### ISSUE TITLE
Installation error: invalid command 'udacity'

### ISSUE THREAD

**Issue by J-Yash** [OpenMined/PySyft#3152]
**Describe the bug**
While installing pysyft according to steps in INSTALLATION.md, running `python setup.py install udacity` gives `error: invalid command 'udacity'`.

**To Reproduce**
1.Follow instructions in INSTALLATION.md to install PySyft for Linux.
2. run `python setup.py install udacity`

**Desktop (please complete the following information):**
 - OS: [linux ubuntu 18.04]

**Comment by bicycleman15** [comment]
Were you able to install PySyft or not ?
If not then just try running
`python setup.py install`

**Comment by bicycleman15** [comment]
I think udacity command also installs `tf_encrypted` besides core requirements.
That I think you can manually install in my opinion.

**Comment by rimijoker** [comment]
I think we should mention that you can install tf_encrypted using req_udacity.txt in the pip-dep folder, should I make changes in the INSTALLATION.md?

**Comment by punitvara** [comment]
@J-Yash  PR got merged. If this issue is resolved, it should not be opened anymore
