### ISSUE TITLE
[EPIC] Create PyGrid Client

### ISSUE THREAD

**Issue by hericlesme** [OpenMined/PySyft#3153]
### Context

Based on the [Federated Learning Roadmap](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md) (specifically in [Section 3 - Host](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md#3-host)), *"[...] The developer needs to connect to an existing PyGrid gateway and send the model, various worker plans and protocols, averaging plan, and various configurations to be stored in PyGrid properly."*

### Description

Having a PyGrid instance running, as specified, the developer needs to send all that data to the PyGrid using the grid library. The grid library no longer exists in PyGrid repository, it is now a PySyft module. So the interface used in the [example](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md#3-host) is no longer available.

So we need to create a grid client in this PySyft module. We would have the necessary methods, and these would use the endpoints that we implemented on the PyGrid side.

Something like:
```python
import syft.grid as gr

pygrid = gr.GridClient(
  hook,
  id="my-name",
  address="https://localhost:5000"
)

pygrid.connect()

pygrid.host_federated_training(
  model=model,
  client_plans={ "training_plan": training_plan },
  client_protocols={ "secure_agg_protocol": secure_aggregation_protocol },
  client_config=client_config,
  server_averaging_plan=averaging_plan,
  server_config=server_config
)
```

See the discussion at https://github.com/OpenMined/PyGrid/issues/435

### Functions
The client needs to implement the following functions

- `host_federated_training` - https://github.com/OpenMined/PyGrid/issues/435
- `get_model` - https://github.com/OpenMined/PyGrid/issues/436
- `get_plan`, `get_protocol` - https://github.com/OpenMined/PyGrid/issues/445

For additional information, see the [Federated Learning Roadmap](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md).

#### Related Issues
https://github.com/OpenMined/PySyft/issues/2995
https://github.com/OpenMined/PyGrid/issues/435
https://github.com/OpenMined/PyGrid/issues/436
https://github.com/OpenMined/PyGrid/issues/445

**Comment by cereallarceny** [comment]
Looks good to me @hericlesme !  By no means do I want to "reinvent the wheel" though. If we already have a similar way to connect to PyGrid from PySyft, then we should use that method. There's no reason to invent a whole new client for working with PyGrid from PySyft if we already have one.

If we don't already have one, go ahead with this!

**Comment by hericlesme** [comment]
What we currently have are workers, if you notice, we no longer have the `WebsocketGridClient` in `syft/grid`. And I think that in terms of functionality, it makes sense to separate from workers. It is not reinventing the wheel. There's already enough that we can reuse, but I thought it best to put it with a new client.

**Comment by hericlesme** [comment]
We have workers who connect with Grid Nodes. Now we'll have a client that connects to the Grid Gateway. Does that makes sense?

**Comment by cereallarceny** [comment]
Yep!  All good.  Move ahead.

**Comment by cereallarceny** [comment]
I don’t believe this actually is stale. @hericlesme can we get an update?

**Comment by hericlesme** [comment]
Yes, I'm working on it, @cereallarceny. Waiting for OpenMined/PyGrid#577 to be reviewed and merged to open a new one here with the `get_model` function.

**Comment by cereallarceny** [comment]
Reviewed and merged! Go ahead and get started. 😊

**Comment by cereallarceny** [comment]
Another update @hericlesme ?
