### ISSUE TITLE
Protocol abstraction currently expects an abstract worker along with the plans but this isn't needed

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#3156]
The Prototype abstraction currently expects an abstract worker along with the plans:
```protocol = sy.Protocol([("worker1", inc1), ("worker2", inc2), ("worker3", inc3)])```

Instead, we could expect only a sequence o plans:
```protocol = sy.Protocol((inc1, inc2, inc3))```

And assume that the protocol should be **explicitly** built (like plans).

This is cleaner and easier to understand for developers since these strings are being used only as placeholders internally and there's no need for users to define those.

**Comment by Kriyszig** [comment]
Can I give this a try?
If I'm not wrong, the starting point is [here](https://github.com/OpenMined/PySyft/blob/7dc983865a8db7e51918b44bff44ac0ba82b120a/syft/execution/protocol.py#L42) (syft/execution/protocol.py)

I would like to clarify one small thing however,
* Are we accepting the plans as just a `tuple` or both `tuple` and `list`? Will both of the below example work or just one?
```python
protocol = sy.Protocol((inc1, inc2, inc3))    # The plans are passed as a tuple
protocol = sy.Protocol([inc1, inc2, inc3])    # The plans are passed as a list
```

Thank you :octocat:

**Comment by karlhigley** [comment]
Heads up that there's a rework of Protocols underway in #3008. This looks like a good change though, so go for it!
