### ISSUE TITLE
Framework agnostic support for PySyft - TensorFlow

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/PySyft#3160]
## Framework agnostic support for PySyft - TensorFlow

**Mentor**: Marianne Monteiro (mari-linhares)

PySyft functionalities are mostly built on top of Pytorch, but ideally, PySyft should be completely framework agnostic. This meaning that all operations executed with PySyft should not depend on the framework that the actual low-level operations are being executed with.

In this project, you will be improving/implementing support for PySyft ops within TensorFlow 2.0.

These can be summarised in 3 main areas based on how PySyft is structured:

- Support TensorFlow ops and tensors: this is where most of the work is needed and consists of wrapping TensorFlow so it can be used with PySyft tensors and operations.

- Remove execution with TensorFlow: supporting remote operations of executing on different workers (Virtual or not). This should be more or less straightforward since this should be the same for all frameworks, maybe some work is needed around TF Tensor serialization

- Privacy related ops: making any changes in the codebase needed in order to have SMPC, Differential Privacy, SplitNN, etc. working with TensorFlow. Not clear right now how much work is needed in practice to get this working, but in theory not a lot.

### Completion criteria
PySyft Tutorials 1 - 4 running seamlessly on both TensorFlow and Pytorch. If more time available continue supporting operations for other tutorials.

### Required Skills

- Knowledge of TensorFlow & Python
- Familiarity (or willingness to become familiar) with PySyft
- Familiarity (or willingness to become familiar) with OpenMined Projects and OpenMined Community

Difficulty: Medium

### Development timeline
 
This is a summarized draft to help you with your proposal, you're free to change this as you'd like!

1. Support simple TensorFlow operations (e.g. tf.add, tf.matmul, tf.nn.relu, …) and basic Tensor support.
2. Support basic remote execution ops with pointers (send, move, get). At this point the tutorial 1 , tutorial 3 should be executing successfully with TensorFlow.
3. Support training logic with TensorFlow (i.e. backprop, optimizers). At this point, the tutorial 2 and tutorial 4 should be ready, notice that this will potentially be very different from the existing Pytorch tutorial due to framework differences (we can/should discuss this when implementing).
4. You did it :D!!!

**Extra**

1. Federated Dataset support: should be more or less straightforward :). tutorial 6 should be ready.
2. Grid and dataset support. tutorial 5 and tutorial 7 should be ready.
3. Plans and protocols support: this is potentially non-trivial, so we can/should discuss this when implementing. tutorial 8 and tutorial 8 bis ready.
4. Implement SMPC support. tutorial 9 ready.
5. SMPC support during training/inference. tutorials 10, 11 and 12 are ready.
6. You did it again :D!!!

**Comment by imskr** [comment]
I would like to work on this!

**Comment by mari-linhares** [comment]
https://github.com/OpenMined/PySyft/pull/3158 this is super relevant for this project ;)

**Comment by milindthakur177** [comment]
@mari-linhares mam can you please review my proposal?

**Comment by buchan123** [comment]
@mari-linhares I have been working with tensorflow from past 8-9 months and would love to work on this project.

**Comment by aashiqmuhamed** [comment]
@mari-linhares I'd like to work on this if no one's looking at this already. Could you help me get started?

**Comment by karlhigley** [comment]
@mari-linhares @iamtrask Since this didn't turn into a GSOC project, what are our next steps with this? Seems like it may depend on getting the new style of tensor hooking set up, so not sure if there's much to do that's directly Tensorflow-related right now. Thoughts?

**Comment by mari-linhares** [comment]
Thanks for being on top of this Karl!

> Seems like it may depend on getting the new style of tensor hooking set up, so not sure if there's much to do that's directly Tensorflow-related right now. Thoughts?

Yes! I think this is right. Probably the next steps are not super TensorFlow related but should be highly influenced by what is needed to have TensorFlow working (if that makes sense).

**Comment by karlhigley** [comment]
I think @iamtrask will be working on building out a few tensor types with next-gen framework hooking, so let’s revisit after that. 👍

**Comment by iamtrask** [comment]
@mari-linhares happy to work on this together as well

**Comment by mari-linhares** [comment]
Up to you @iamtrask, let's sync this week!
