### ISSUE TITLE
Porting HE libraries completely to Python

### ISSUE THREAD

**Issue by deevashwer** [OpenMined/PySyft#317]
The motivation behind this idea is to further the development of HE libraries viz. PyBV, PyAono, and potentially PyFV. Since more people are comfortable with Python and numpy, more people will be able to contribute to this project, which is currently the need of the hour. Moreover, this could serve as a mockup for faster CPU and GPU implementations. This will also solve the high maintenance issues that are persistent with the current Cython implementation.
All in all, I urge everyone who's interested in homomorphic encryption to contribute to building this library. I'll positively roll out the initial version soon and make sure that it mirrors the interface provided by syft.he.paillier.

P.S. We're not restricted to just numpy, but the implementation has to be in Python. We're starting off with numpy, but in the near future, it could be that numpy doesn't have the functionality we need, in which case, we can use multiple libraries.

**Comment by deevashwer** [comment]
I'll hand it over to @iamtrask to decide the acceptance criteria for this library/collection of libraries, in case I've left anything.

**Comment by iamtrask** [comment]
Here's a first pass... thoughts?

**Acceptance Criteria:**
- pure numpy implementations exist for our primary homomorphic encryption techniques (Paillier, PyAono, PyBV, and PyFV)
- implementations are well commented with unit tests
- Optional: blogposts explaining how they work.

**Comment by OceanCoding** [comment]
Looks like an interesting task. I'm currently working on new kernels for the GPU API, but I offer you my help, just let me know on slack (OceanCoding aswell)

**Comment by aeroaks** [comment]
wondering about the status of this issue?
