### ISSUE TITLE
Add Codecov support on every PR

### ISSUE THREAD

**Issue by imskr** [OpenMined/PySyft#3181]
**Is your feature request related to a problem? Please describe.**
A common practice in the modern developer's workflow is to test multiple build systems, split up tests in different containers, and group tests based on test focus (unit tests vs integration tests). Codecov is a tool that is used to measure the test coverage of your codebase. It generally calculates the coverage ratio by examining which lines of code were executed while running the unit tests. Codecov flawlessly supports all these setups.

[codecov.io/](https://codecov.io/)

**Describe the solution you'd like**

I would like to add codecov integration to show coverage on every PR

**Describe alternatives you've considered**

**Additional context**

**Comment by imskr** [comment]
I would like to add this feature.

**Comment by gmuraru** [comment]
@imskr could you update the issue description

**Comment by imskr** [comment]
@gmuraru Done.
