### ISSUE TITLE
Improve Plans flexibility

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3184]
**Is your feature request related to a problem? Please describe.**
Plans currently don't work exactly as normal function in the following scenarios:
- if some inputs that are not used in the computations
- if some inputs that are not used and are given in the output
- if input/ouput contain nested objects like list or tuple

**Describe the solution you'd like**
We want to support this by default

**Comment by tudorcebere** [comment]
I will have a look on this.
