### ISSUE TITLE
Setting requires_grad as True in Pysyft/examples/tutorials/Part 02 - Intro to Federated Learning.ipynb

### ISSUE THREAD

**Issue by eceisik** [OpenMined/PySyft#3208]
**Describe the bug**

In the file: Pysyft/examples/tutorials/Part 02 - Intro to Federated Learning.ipynb

Only the weights are needed to be updated. Why did we set requires_grad as True for x and y? I think it can be confusing for beginners.

data = torch.tensor([[0,0],[0,1],[1,0],[1,1.]], requires_grad=True)
target = torch.tensor([[0],[0],[1],[1.]], requires_grad=True)

**Comment by karlhigley** [comment]
@eceisik Send a PR that fixes it? 😄

**Comment by karlhigley** [comment]
Could be related to #3180
