### ISSUE TITLE
No module named 'syft.federated.floptimizer'

### ISSUE THREAD

**Issue by eceisik** [OpenMined/PySyft#3209]
**Describe the bug**
When I try to run PySyft/examples/tutorials/Part 02 - Intro to Federated Learning.ipynb
(https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2002%20-%20Intro%20to%20Federated%20Learning.ipynb), I get this error:

ModuleNotFoundError: No module named 'syft.federated.floptimizer'

**To Reproduce**
>>from syft.federated.floptimizer import Optims

torch version:1.4.0
syft version: 0.2.3

**Comment by rimijoker** [comment]
@eceisik Please follow this INSTALLATION.md, that should fix the issue for you.

**Comment by karlhigley** [comment]
We'll need to release a new version to address that. Coming soon!

**Comment by karlhigley** [comment]
@eceisik @rimijoker Just released v0.2.4, which should address this issue. Let me know if upgrading works for you!

**Comment by eceisik** [comment]
I followed the installation.md for windows 
I only needed to change installation part of torch as below:

pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html

It worked.
Thank you for help
