### ISSUE TITLE
Add Thread workers to stop having a remote virtual worker calling torch.ones() and have the result registered in the local_worker

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3210]

**Comment by LaRiffle** [comment]
Hahah this issue was created by **frustration**! :D
But I agree so much with you!

**Comment by karlhigley** [comment]
We've had it on the Syft Core board ever since, and decided yesterday that it makes sense to tackle it with @iamtrask's work on the longer-term future of tensor types as part of v0.4. (Meanwhile, the rest of us are mostly working on sorting out remote execution for v0.3.)

**Comment by gmuraru** [comment]
@karlhigley could you add more context for this issue? (an exemple with where is happening would be great!)

**Comment by karlhigley** [comment]
When running locally with `VirtualWorkers` they all run in the same thread, which causes some difficulties with the Torch hook. If you call `torch.ones()` on a `VirtualWorker`, the resulting tensor ends up registered on the `local_worker` instead.

**Comment by karlhigley** [comment]
(This issue was created from a card on the Syft Core project board, and Github project boards doesn't have a way to capture a description on cards that aren't issues. Hence the long title!)
