### ISSUE TITLE
Enhance encryption API

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3212]
Two features here:

- Make `crypto_provider` kwargs mandatory in `.share()`and check that it's not a client_worker
- Modify `.encrypt()` to add a kwarg and be used not only for Paillier encryption but only MPC (default should be MPC,  and it should call for mpc .fix_prec(...).share(...)  under the hood)

**Comment by nin-ed** [comment]
I can try the first part.

**Comment by AshwinRam2000** [comment]
I can take this up
