### ISSUE TITLE
BatchNorm is currently not supported for SMPC

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3231]
We'd love to have BatchNorm support for SMPC :)

**Comment by imskr** [comment]
I would like to fix this!

**Comment by LaRiffle** [comment]
Sure go ahead :)

**Comment by LaRiffle** [comment]
Hey @imskr!
How is it going? :)

**Comment by imskr** [comment]
Sorry for the delay, I will just make the PR by today @LaRiffle
