### ISSUE TITLE
Cannot find dataset pointers sent to a remote client 

### ISSUE THREAD

**Issue by wmlba** [OpenMined/PySyft#3250]
**Describe the bug**
After tagging a tensor and sending it to the NodeClient object, nothing comes out of the ClientNode. The search method returns no objects.

**To Reproduce**
- Setup a remote client (Grid node)
- Create a simple tensor `data = torch.tensor([1, 1, 1, 1, 1])`
- Tag the tensor `data.tag('mytag')`
- Send the tensor to the remote node `data.send(remote_node)`
- Search for the tenor `remote_node.search('mytag')`  -> This will return an empty list []
- Search for the tensor on the grid gateway (`grid_gateway.search('mytag')`) . It will return an empty list []

I checked the redis db and I found the tags but they won't show up in the search method:
`redis_db.hgetall('key')`

**Screenshots**
![Screen Shot 2020-03-24 at 6 50 31 PM](https://user-images.githubusercontent.com/18373707/77392705-6adac900-6e00-11ea-81ff-06222b0df71c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - PySyft 0.2.4 msgpack 1.0.0

**Comment by abogaziah** [comment]
worker.search() is for local use only. for a remote worker use `me.request_search(['mytag'], location= worker)`. this will send you back an object_pointer that points to the dataset. that enables you to call .get() on it only for now not full functionality of dataset_pointer.
me.request_search() will return a dataset_pointer soon, I'm currently working on it
