### ISSUE TITLE
Indexing pointer tensors with a list

### ISSUE THREAD

**Issue by artix41** [OpenMined/PySyft#3259]
When running the following code
```python
hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id="bob")

a = torch.tensor([10,20,30])
print(a[[0,2]])

b = torch.tensor([10,20,30]).send(bob)
print(b[[0,2]])
```
the first tensor `a` get displayed correctly as 
```python
tensor([10, 30])
```
but the second tensor raises the following error:
```python
IndexError: too many indices for tensor of dimension 1
```

I have Python 3.7.6, PySyft 0.2.4 and PyTorch 1.4.0.

I'm new to PySyft, so maybe it is an expected behavior for some reasons, but I don't really see why (since remote tensors are supposed to have the same functionalities as normal tensors as far as I understand).

**Comment by rotalex** [comment]
I can take a look.
