### ISSUE TITLE
Dependency SkLearn (used by Sandbox in Tutorial 5) is missing at notebook requirements

### ISSUE THREAD

**Issue by joseims** [OpenMined/PySyft#3272]
**Describe the bug**
The tutorial 5 uses the create_sandbox function wich requires sklearn. But sklearn in not in notebook requirement.

**To Reproduce**
1. Run the pre-installation as described in readMe
2. Run the installation as described in readMe
3. Run `make notebook`
4. Open tutorial 5 (~/Pysyft/examples/tutorials/Part 05 - Welcome to the Sandbox.ipynb)
5. Run the first code snippet

**Expected behavior**
The code would run and there would be no errors.

**Screenshots**
![Captura de tela de 2020-03-29 17-07-09](https://user-images.githubusercontent.com/25506122/77859445-c2ea4480-71df-11ea-85fc-94cac6ad56fc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Even if the sklearn it's no longer a dependence of the Pysyft I think it would make sense that it would be a dependence in the notebooks requirements specially because `make notebook` creates it's own venv so installing in my own pysyft conda venv would not resolve the problem, i would need to either edit the makefile or the notebook requirements in order to work.

**Comment by joseims** [comment]
I'd like to resolve if possible

**Comment by potsch** [comment]
Yeah, I have the same problem. 
Anyone from the dev team? Can you help us?

**Comment by karlhigley** [comment]
Sure, adding it to the notebook requirements makes sense to me. I've tripped over that issue a few times myself. Submit a PR?

**Comment by potsch** [comment]
I fixed this by adding the line scikit-learn~=0.22.2.post1 in the requirements.txt and then typing make notebook again.
After this I could run Tutorial Code 5 and 7 without any problems!

**Comment by ucalyptus** [comment]
@potsch  in the pip-dep/requirements-notebook.txt u meant?

**Comment by potsch** [comment]
@ucalyptus  No, I added it in the pip-dep/requirements.txt
