### ISSUE TITLE
Can the websocket handle large models?

### ISSUE THREAD

**Issue by wmlba** [OpenMined/PySyft#3274]
I am trying to train a VGG16 model which is not huge but I get a connection reset by peer error from the websocket connection:

---------------------------------------------------------------------------
ConnectionResetError                      Traceback (most recent call last)
<ipython-input-14-6dcce03a9f1e> in async-def-wrapper()
     25         ]
     26     )
---> 27 
     28 
     29 

<ipython-input-13-48a9a954037c> in fit_model_on_worker(worker, traced_model, batch_size, curr_round, max_nr_batches, lr, dataset_key)
     56 
     57     print("sending the train config to worker")
---> 58     train_config.send(worker)
     59     print("train config sent")
     60     print("now fitting")

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/federated/train_config.py in send(self, location)
    115         """
    116         # Send traced model
--> 117         self.model_ptr, self._model_id = self._wrap_and_send_obj(self.model, location)
    118 
    119         # Send loss function

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/federated/train_config.py in _wrap_and_send_obj(self, obj, location)
     95         """Wrappers object and send it to location."""
     96         obj_with_id = ObjectWrapper(id=sy.ID_PROVIDER.pop(), obj=obj)
---> 97         obj_ptr = self.owner.send(obj_with_id, location)
     98         obj_id = obj_ptr.id_at_location
     99         return obj_ptr, obj_id

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/workers/base.py in send(self, obj, workers, ptr_id, garbage_collect_data, create_pointer, **kwargs)
    385 
    386         # Send the object
--> 387         self.send_obj(obj, worker)
    388 
    389         # If we don't need to create the pointer

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/workers/base.py in send_obj(self, obj, location)
    678                 receive the object.
    679         """
--> 680         return self.send_msg(ObjectMessage(obj), location)
    681 
    682     def request_obj(

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/workers/base.py in send_msg(self, message, location)
    285 
    286         # Step 2: send the message and wait for a response
--> 287         bin_response = self._send_msg(bin_message, location)
    288 
    289         # Step 3: deserialize the response

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/workers/virtual.py in _send_msg(self, message, location)
     13             sleep(self.message_pending_time)
     14 
---> 15         return location._recv_msg(message)
     16 
     17     def _recv_msg(self, message: bin) -> bin:

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/workers/websocket_client.py in _recv_msg(self, message)
    100             logger.warning("Created new websocket connection")
    101             time.sleep(0.1)
--> 102             response = self._forward_to_websocket_server_worker(message)
    103             if not self.ws.connected:
    104                 raise RuntimeError(

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/syft/workers/websocket_client.py in _forward_to_websocket_server_worker(self, message)
     85 
     86     def _forward_to_websocket_server_worker(self, message: bin) -> bin:
---> 87         self.ws.send(str(binascii.hexlify(message)))
     88         response = binascii.unhexlify(self.ws.recv()[2:-1])
     89         return response

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/websocket/_core.py in send(self, payload, opcode)
    251 
    252         frame = ABNF.create_frame(payload, opcode)
--> 253         return self.send_frame(frame)
    254 
    255     def send_frame(self, frame):

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/websocket/_core.py in send_frame(self, frame)
    277         with self.lock:
    278             while data:
--> 279                 l = self._send(data)
    280                 data = data[l:]
    281 

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/websocket/_core.py in _send(self, data)
    447 
    448     def _send(self, data):
--> 449         return send(self.sock, data)
    450 
    451     def _recv(self, bufsize):

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/websocket/_socket.py in send(sock, data)
    155             return sock.send(data)
    156         else:
--> 157             return _send()
    158     except socket.timeout as e:
    159         message = extract_err_message(e)

~/anaconda3/envs/pysyft_py37/lib/python3.7/site-packages/websocket/_socket.py in _send()
    137     def _send():
    138         try:
--> 139             return sock.send(data)
    140         except SSLWantWriteError:
    141             pass

ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by ThorShockU** [comment]
I have the same question as yours.

**Comment by NeuZhangQiang** [comment]
@wmlba @ThorShockU I have one question. How do you load data in training? I think the data is very large to train VGG model. Am I right? In the tutorial of PySyft, it use data.send(work) to share data. However, if the data is very large (>10g), it is impossible to load it into memory. How can we share it?
One possible solution is FederatedDataLoader, but I have no idea how to convert DataLoader (torch) to FederatedDataset. Could you please give me some suggestion? Thank you very much in advance!

**Comment by wmlba** [comment]
+1
