### ISSUE TITLE
Error abou x.encrypt(protocol="paillier", public_key=pub)

### ISSUE THREAD

**Issue by ganjf** [OpenMined/PySyft#3282]
When I use `x.encrypt(protocol="paillier", `public_key=pub),` it tells me that **"'Tensor' object has no attribute 'encrypt'"**。But in fact I could excute `pub, pri = sy.keygen()` successfully, and I already download the class file **"paillier.py"**.

**Comment by Syzygianinfern0** [comment]
You can try the following
```python
import torch
import syft as sy

hook = sy.TorchHook(torch)

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
james = sy.VirtualWorker(hook, id="james")

x = torch.randint(10, (1, 5), dtype=torch.float32)

# MPC
x_encrypted = x.encrypt(workers=[bob, alice], crypto_provider=james)
x_decrypted = x_encrypted.decrypt()
assert (x == x_decrypted).all()

# Paillier
public, private = sy.frameworks.torch.he.paillier.keygen()
x_encrypted = x.encrypt(protocol="paillier", public_key=public)
x_decrypted = x_encrypted.decrypt(protocol="paillier", private_key=private)
assert (x == x_decrypted).all()
```

**Comment by ganjf** [comment]
There is  an error `encrypt() got an unexpected keyword argument 'protocol'.
I install the library with `pip install syft[udacity]`, the version is 0.2.4, but I found there is difference in /syft/frameworks/torch/tensors/interpreters/native.py/ about the defination of encrypt() method with codes on Github. It seems the updated version about the method encrypt(protocol="pailiar", *kwarg) don't exist. When I download the site package `syft` and place it to python3.7/site-packages, it show me an error when I import syft. So I think maybe you have fogot to update the library with pip method. 
And there is syft-proto= 0.2.8.a1， but the latest version of syft=0.2.4 could only match the syft-proto=0.2.5.a1. So I have no idea to update the latest syft which could use `encrypt(protocol="pailiar", *kwarg)` to achieve HE. So I really wish you could offer me help.Thanks

**Comment by Syzygianinfern0** [comment]
Since the feature was implemented very recently it's not available on any release as of now. Please try installing from source.
[Link](https://github.com/OpenMined/PySyft/blob/dev/INSTALLATION.md)

**Comment by ganjf** [comment]
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"The Syzygian Inferno"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 晚上11:37
收件人:&nbsp;"OpenMined/PySyft"<PySyft@noreply.github.com&gt;;
抄送:&nbsp;"ganjf"<1194520007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenMined/PySyft] Error abou x.encrypt(protocol="paillier", public_key=pub) (#3282)





 
Since the feature was implemented very recently it's not available on any release as of now. Please try installing from source.
 Link
