### ISSUE TITLE
Jupyter Notebook Version Conflict Following Conda Installation Instructions

### ISSUE THREAD

**Issue by dcato98** [OpenMined/PySyft#3289]
**Bug**
Following the Conda pre-installation and installation instructions in README.md in Linux results in the following version conflict:
ERROR: notebook 6.0.3 has requirement tornado>=5.0, but you'll have tornado 4.5.3 which is incompatible.

Then when running jupyter notebook, the browser tab fails to display any files and there is no option to create a Python notebook. This was also noticed by youben11 [here](https://github.com/OpenMined/PySyft/pull/3196#issuecomment-600144632).

**To Reproduce**
```
conda create -n pysyft python=3.7
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install syft[udacity]
```

**Workaround**
Per [this closed issue](https://github.com/OpenMined/PySyft/issues/3019#issuecomment-605706131), install jupyter notebook at the same time as syft using:
```
conda create -n pysyft python=3.7
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
pip install syft[udacity,notebooks]
```
To test the workaround, I've been able to successfully open and run the [first example jupyter notebook](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2001%20-%20The%20Basic%20Tools%20of%20Private%20Deep%20Learning.ipynb).

Running `conda list` shows the following versions were installed: 
tornado 4.5.3
ipykernel 5.2.0
ipython 7.13.0
ipython-genutils 0.2.0
ipywidgets 7.5.1
jupyter 1.0.0
jupyter-client 6.1.2
jupyter-console 6.1.0
jupyter-core 4.6.3
notebook 5.7.8

**Comment by karlhigley** [comment]
This has been fixed in the requirements file in #3204, but people with installations from before the fix will still need to run the workaround mentioned here.
