### ISSUE TITLE
BigIntTensor support in FPT

### ISSUE THREAD

**Issue by Yugandhartripathi** [OpenMined/PySyft#3291]
We need a way to represent larger precisions and we already have a BigIntTensor abstraction tensor type - not extending FixedPrecisionTensor with the ability to represent even larger precisions in progress and once #2905 is merged.
We will need a way to select "bigint" option for wrapping our values with BigIntTensor.
Which will work something like:
Wrapper -> FixedPrecisionTensor -> BigIntTensor
Wrapper -> FixedPrecisionTensor -> IntTensor
Wrapper -> FixedPrecisionTensor -> LongTensor

**Describe the solution you'd like**
Handle value "bigint" for dtype arg in FPT initialisation.

**Describe alternatives you've considered**
BigInt could have worked like CRT or LargePrec totally separate from FPT but that's not what we are aiming for so this alternative is a no go.

**Comment by rotalex** [comment]
I will look into this.
