### ISSUE TITLE
Tutorial Notebooks Incorrectly State Momentum is not Supported

### ISSUE THREAD

**Issue by dcato98** [OpenMined/PySyft#3293]
**Request**
Some tutorial notebooks incorrectly say that momentum is not supported. Support for optimizers using momentum was added in #3179.

**Describe the solution you'd like**
[Tutorial 2](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2002%20-%20Intro%20to%20Federated%20Learning.ipynb) has been updated to use the new floptimizer. The following notebooks still need to be updated:
 - https://github.com/OpenMined/PySyft/blob/2776cffc619dacf9486584f6e455104d80901928/examples/tutorials/Part%2006%20-%20Federated%20Learning%20on%20MNIST%20using%20a%20CNN.ipynb
 - https://github.com/OpenMined/PySyft/blob/ac3d6172c268e26bf0a7100c6ee0a7f4cc4d8890/examples/tutorials/advanced/Federated%20CIFAR10.ipynb
 - https://github.com/OpenMined/PySyft/blob/319d59c9aa3ab9b8dfda95c42f7dd5978b3bc48a/examples/tutorials/advanced/websockets-example-MNIST/run_websocket_client.py

**Next steps**
I intend to submit a PR for this shortly.

**Comment by dcato98** [comment]
The 3rd notebook mentioned above (training using websockets) has been changed so now these files ([here](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/websockets_mnist/run_websocket_client.py), [here](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/websockets_mnist_parallel/run_websocket_client.py)) need to be changed. The code to be changed is now in While the changes are straightforward, unfortunately I've not yet been able to get the websockets to run properly in order to test the changes.

**Comment by dcato98** [comment]
On further inspection, it is not at all obvious to me how (or even whether) the websocket examples need this change.

**Comment by karlhigley** [comment]
I'm not sure that #3179 was intended to add full support for momentum-based optimizers. It certainly seems like a step in the right direction, but it's not clear that momentum-based optimizers are fully compatible with the rest of PySyft.
