### ISSUE TITLE
AttributeError: module 'syft.grid' has no attribute 'WebsocketGridClient'

### ISSUE THREAD

**Issue by fermat97** [OpenMined/PySyft#3312]
Hi, I assumed that the `grid` functionality has been totally merged into the `syft` environment, and it is not necessary to install `grid` separately. But I have received this error:

> AttributeError: module 'syft.grid' has no attribute 'WebsocketGridClient'

Has the attribute's name changed?

**Comment by karlhigley** [comment]
I think it's just called `GridClient` now.
