### ISSUE TITLE
Call decrypt() without specifying the protocol

### ISSUE THREAD

**Issue by youben11** [OpenMined/PySyft#3329]
**Is your feature request related to a problem? Please describe.**
When we call decrypt on a tensor, we don't want to always provide the protocol if it can be known otherwise.

**Describe the solution you'd like**
I think that the current protocol that encrypted the tensor can be checked by looking at the child's type.

**Comment by Syzygianinfern0** [comment]
I'll take this up!

**Comment by youben11** [comment]
It would be great if you can wait till the CKKSTensor is merged to avoid any merge conflict

**Comment by Syzygianinfern0** [comment]
Sure 😊
