### ISSUE TITLE
Tutorial Part 05 Welcome to Sandbox- module scipy._lib not found

### ISSUE THREAD

**Issue by potsch** [OpenMined/PySyft#3331]
I am trying to run the first code snippet from the Tutorial and I keep getting a **ModuleNotFoundError : No module named 'scipy._lib'.** I have installed scikit-learn dependency with pip3 install scipy and pip install scipy in hopes to fix this error. It didn't work.
Can anybody assist me?

**To Reproduce**
1. I started my Juypter notebook locally by typing `juypter notebook` in the terminal.
2. Copied the code snippet
 `import torch`
 `import syft as sy`
 `sy.create_sandbox(globals())`
**Expected behavior**
That the code should run without errors

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by abogaziah** [comment]
have you restarted your kernel?

**Comment by potsch** [comment]
yes, I restarted the Python kernel many times.
