### ISSUE TITLE
Need changes in Experimental notebook for PaillierTensor

### ISSUE THREAD

**Issue by IamRavikantSingh** [OpenMined/PySyft#3333]
**To Reproduce**
Run PySyft/examples/experimental/PaillierTensor.ipynb and on running 3rd block it will throw an error.

**Expected behavior**
Should encrypt tensor without throwing the error 😁

**Additional context**
change encrypt and decrypt like:
x = th.Tensor([1,2,3]).encrypt(protocol="paillier", public_key=pub)
out = out.decrypt(protocol="paillier", private_key=pri)

**Comment by karlhigley** [comment]
What's the error? Post a stack trace.

**Comment by IamRavikantSingh** [comment]
> What's the error? Post a stack trace.

Error is due to the recent changes in encrypt method.
```
AttributeError                            Traceback (most recent call last)
 in 
----> 1 x = th.Tensor([1,2,3]).encrypt(pub)
      2 y = th.Tensor([2,2,2])

~/Desktop/PySyft/syft/frameworks/torch/tensors/interpreters/native.py in encrypt(self, protocol, **kwargs)
   1018 
   1019         """
-> 1020         if protocol.lower() == "mpc":
   1021             workers = kwargs.pop("workers")
   1022             crypto_provider = kwargs.pop("crypto_provider")

AttributeError: 'PaillierPublicKey' object has no attribute 'lower'
```

**Comment by karlhigley** [comment]
@Syzygianinfern0 I think this changed most recently in one of your PRs. Give it a look?

**Comment by Syzygianinfern0** [comment]
Ok. @karlhigley
