### ISSUE TITLE
Aggregated models or aggregated gradients tutorials part 10

### ISSUE THREAD

**Issue by jczestochowska** [OpenMined/PySyft#3340]
Hi! I have a quick question regarding the methodology as I am new to the federated learning concept and I would love to explore pysyft further. I looked through tutorials and I have one doubt. In tutorial 10 with CNN for MNIST do you send gradients to central node from all workers (clients) aggregate them, average them and update the model on central node and then send new model to all clients or do you send models of individual workers to the central node, aggregate them, average them and then send new model to all clients. Question is do we send gradients or do we send models? Thanks in advance for any help in that matter!

**Comment by rvoak** [comment]
My understanding is that in federated learning, you send model parameters to be aggregated, not gradients.

**Comment by karlhigley** [comment]
You can do either, and there is (for example) a line of research that seeks to compress gradients to reduce FL communication costs. The Syft ecosystem is oriented toward model aggregation at present, but I'd love to make other approaches workable too.

**Comment by jczestochowska** [comment]
thanks a lot!
