### ISSUE TITLE
securenn.maxpool2d isn't implemented appropriately 

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#3369]
**Describe the bug**
securenn.maxpool2d is implemented with arg a_sh that must be a **wrapped** AdditiveSharingTensor. and after calling .fix_prec() on it the chain becomes `fixed_prec>wrapper(torch.Tensor)>AdditiveSharingTensor` which is confused with a normal fixed_prec tensor chain `fixed_prec>torch.Tensor`
I could change the conditions to identify if it's a wrapper (I did that as a hot fix) but I don't know if that's the best solution since we'll have to change it in a lot of other places

**To Reproduce**
```
import torch
import syft as sy
import cProfile
from torch import nn

hook = sy.TorchHook(torch)
import torch.nn.functional as F

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
crypto_provider = sy.VirtualWorker(hook, id="james")


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


resnet = Net()
resnet.fix_prec().share(bob, alice, crypto_provider=crypto_provider)
data = torch.ones(1, 1, 32, 32).fix_prec().share(bob, alice, crypto_provider=crypto_provider)

cProfile.run(resnet(data))
```
run it in the debugger if you will :)

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10

**Expected behavior:** 
securenn.maxpool2d(a_sh: AdditiveSharingTensor) not securenn.maxpool2d(a_sh: torch.Tensor)

**Comment by karlhigley** [comment]
Might be good to fix this issue independently, but Syft Core has concluded that we should remove wrappers from the code base entirely. (It'll take a while.)
