### ISSUE TITLE
Move CrypTen Hook  functionality to a different file

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3385]
**Is your feature request related to a problem? Please describe.**
Currently, we have the functionality to hook the CrypTen module inside the ```TorchHook```.  We should separate the framework hook information. 
**Describe the solution you'd like**
We should move this functionality to a separate file and in ```TorchHook``` import that functionality and call it.

**Comment by IamRavikantSingh** [comment]
I would like to work on this issue.

**Comment by gmuraru** [comment]
Closing this as it is solved.
