### ISSUE TITLE
 syft.exceptions.UndefinedProtocolTypeError: syft.execution.placeholder_id.PlaceholderId is not defined in the protocol file

### ISSUE THREAD

**Issue by durden62** [OpenMined/PySyft#3388]
while running the start_websocket_servers.py, this issue (syft.exceptions.UndefinedProtocolTypeError) shows up. does anybody have a solution?
following below is the complete error:
File "/Users/shekhar/PySyft/syft/serde/msgpack/proto.py", line 71, in proto_type_info
    raise UndefinedProtocolTypeError(f"{type_name} is not defined in the protocol file")
    raise UndefinedProtocolTypeError(f"{type_name} is not defined in the protocol file")
syft.exceptions.UndefinedProtocolTypeError: syft.execution.placeholder_id.PlaceholderId is not defined in the protocol file
syft.exceptions.UndefinedProtocolTypeError: syft.execution.placeholder_id.PlaceholderId is not defined in the protocol file
    raise UndefinedProtocolTypeError(f"{type_name} is not defined in the protocol file")
syft.exceptions.UndefinedProtocolTypeError: syft.execution.placeholder_id.PlaceholderId is not defined in the protocol file

**Comment by karlhigley** [comment]
That sounds like a mismatch between PySyft and `syft-proto` versions. I'd try re-installing the PySyft requirements from `pip-dep/requirements.txt` and see if that resolves it.

**Comment by fodierna** [comment]
> That sounds like a mismatch between PySyft and `syft-proto` versions. I'd try re-installing the PySyft requirements from `pip-dep/requirements.txt` and see if that resolves it.

I had the same problem. Re-installing the requirements solved it. Thank you.

**Comment by durden62** [comment]
hey man, thanks a lot. although I did this earlier. it showed

>  [ERROR: syft 0.2.4 has requirement syft-proto~=0.2.5.a1, but you'll have syft-proto 0.2.9a2 which is incompatible. ]
then I quit this step of upgrading syft-proto but after your answer, I did that anyway and the error got resolved.
