### ISSUE TITLE
Bump PyTorch to 1.5

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3395]
**Is your feature request related to a problem? Please describe.**
PyTorch 1.5 is released and we want to start using that version.

**Describe the solution you'd like**
Bump the PyTorch version to 1.5 (and the torchvision) and fix the failing tests

**Comment by Syzygianinfern0** [comment]
https://del.dog/ylinebubin.txt
Stack trace of `pytest` on torch 1.5 for anyone working on it :+1:

**Comment by rotalex** [comment]
I will look on this

**Comment by Syzygianinfern0** [comment]
> I will look on this

Great! I've assigned it to you. Feel free to ping me if you feel you are caught up in any stage :smile: :+1:
