### ISSUE TITLE
Reduce complexity of route_method_exception

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3429]
Split the code from ```route_method_exception``` into two separate functions and remove the ```noqa: C901```.

**Describe alternatives you've considered**
Simplify the function such that no split is required.

**Additional context**
Code quality:
```
2020-04-29T13:13:32.5920184Z ./syft/exceptions.py:359:1: C901 'route_method_exception' is too complex (14)
2020-04-29T13:13:32.5920476Z def route_method_exception(exception, self, args_, kwargs_):
2020-04-29T13:13:32.5920733Z ^
```

**Comment by Nike682631** [comment]
hey , can i work on this issue?

**Comment by imrahul361** [comment]
Is the issue still open?I would like to work on it? @gmuraru

**Comment by gmuraru** [comment]
Hey. If the issue is still present, you can grab it :D

**Comment by imrahul361** [comment]
Can you guide through how to produce the bug?

**Comment by akshat1136** [comment]
@gmuraru sir, I tried to solve the mentioned problem
```
2020-04-29T13:13:32.5920184Z ./syft/exceptions.py:359:1: C901 'route_method_exception' is too complex (14)
2020-04-29T13:13:32.5920476Z def route_method_exception(exception, self, args_, kwargs_):
2020-04-29T13:13:32.5920733Z ^
```
But, instead of converting ```route_method_exception``` to two separate methods I just reduced the ```if...elif``` statements.
And it seems to work properly, it shows positive results in both Flake8 test(after removing C901) and pytest.

Will this change work instead of separating the method?

**Comment by gmuraru** [comment]
> @gmuraru sir, I tried to solve the mentioned problem
> 
> ```
> 2020-04-29T13:13:32.5920184Z ./syft/exceptions.py:359:1: C901 'route_method_exception' is too complex (14)
> 2020-04-29T13:13:32.5920476Z def route_method_exception(exception, self, args_, kwargs_):
> 2020-04-29T13:13:32.5920733Z ^
> ```
> 
> But, instead of converting `route_method_exception` to two separate methods I just reduced the `if...elif` statements.
> And it seems to work properly, it shows positive results in both Flake8 test(after removing C901) and pytest.
> 
> Will this change work instead of separating the method?

Sure!
