### ISSUE TITLE
Reduce complexity of ```forward``` from rnn

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3431]
Split the code from ```forward``` into two separate functions and remove the ```noqa: C901```.

**Describe alternatives you've considered**
Simplify the function such that no split is required.

**Additional context**
Code quality:
```
2020-04-29T13:13:32.6026063Z ./syft/frameworks/torch/nn/rnn.py:205:5: C901 'RNNBase.forward' is too complex (12)
2020-04-29T13:13:32.6026250Z     def forward(self, x, h=None):
```

**Comment by dcato98** [comment]
Hey, is it okay if I start working on this one?

**Comment by gmuraru** [comment]
Hey, sure. Assigned the issue to you.

**Comment by Nike682631** [comment]
is this issue active\

**Comment by dcato98** [comment]
Yes, it's been fixed in the PR above awaiting review.
