### ISSUE TITLE
Reduce complexity of ```conv2d``` functional.py

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3432]
Split the code from ```cov2d``` into two separate functions and remove the ```noqa: C901```.

**Describe alternatives you've considered**
Simplify the function such that no split is required.

**Additional context**
Code quality:
```
2020-04-29T13:13:32.6026755Z ./syft/frameworks/torch/nn/functional.py:38:1: C901 'conv2d' is too complex (13)
2020-04-29T13:13:32.6026967Z def conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1):
```

**Comment by MaksymPetyak** [comment]
Hi! I would like to contribute on this issue.

**Comment by gmuraru** [comment]
Hey. I assigned the issue to you ^_^

**Comment by LaRiffle** [comment]
Maybe don't change that function, @alhparsa is already working on it for some optimisation purpose, i will create merge conflicts! (And conv2d is complex by nature)

**Comment by gmuraru** [comment]
Closing this issue then!
