### ISSUE TITLE
torch.mean on AdditiveSharingTensor doesn't work

### ISSUE THREAD

**Issue by knexator** [OpenMined/PySyft#3447]
**Describe the bug**
torch.mean in SMPC on fixed precision tensors gives garbage results

**To Reproduce**
```python
import torch
import syft as sy

hook = sy.TorchHook(torch)
alice = sy.VirtualWorker(hook, id="alice")
bob = sy.VirtualWorker(hook, id="bob")
crypto = sy.VirtualWorker(hook, id="crypto")

values = torch.tensor([[1, 2, 3], [5, 6, 7]]).float().fix_precision().share(alice, bob, crypto_provider=crypto)
print(torch.mean(values).get().float_precision())
```

**Expected behavior**
The result should be the same as if calculating it by hand, which works correctly
`print((torch.sum(values).get() / 6).float_precision())`

**Additional context**
This might have to do with the fact that division also seems broken:
`print((torch.sum(values) / 6).get().float_precision())`
Curiously enough, this works (with slight precision issues):
`print((torch.sum(values / 6)).get().float_precision())`

**Comment by LaRiffle** [comment]
Part of solution can be found here: https://github.com/OpenMined/PySyft/pull/3438/commits/e9ea443d76f41e4cecf657a235c57114a5b5b02e
