### ISSUE TITLE
Syft and Jupyter have incompatible requirements for tornado

### ISSUE THREAD

**Issue by kennysong** [OpenMined/PySyft#3459]
In a fresh venv, run:

```
pip install jupyter
pip install syft
```

Jupyter requires `tornado>=5.0`, while Syft requires `tornado==4.5.3`. After running the second line, it downgrades tornado to `4.5.3` which breaks Jupyter.

Logs:

```
> pip install syft
...
ERROR: notebook 6.0.3 has requirement tornado>=5.0, but you'll have tornado 4.5.3 which is incompatible.
Installing collected packages: websocket-client, protobuf, syft-proto, websockets, tblib, Pillow, numpy, torch, torchvision, tornado, idna, chardet, urllib3, certifi, requests, Werkzeug, click, itsdangerous, Flask, lz4, scipy, phe, msgpack, python-engineio, python-socketio, flask-socketio, syft
  Found existing installation: tornado 6.0.4
    Uninstalling tornado-6.0.4:
      Successfully uninstalled tornado-6.0.4
  Running setup.py install for tornado ... done
  Running setup.py install for phe ... done
```

**Comment by karlhigley** [comment]
You can find a set of compatible versions in the [notebook requirements file](https://github.com/OpenMined/PySyft/blob/master/pip-dep/requirements_notebooks.txt). You can also use `make notebook` to set up an environment.

**Comment by kennysong** [comment]
Ah, thanks for the reference. In case someone else runs into the same problem (the Jupyter PyPi package is kind of confusingly versioned), I got this working in a venv with:

```
pip install 'syft[udacity]'
pip install notebook==5.7.8  # This installs normal jupyter as well
pip install jupyterlab  # Optional, currently working at 2.1.2
```

Didn't try `make notebook` since that seems more for doing development in the Syft repo than using it as a package. Thanks!

**Comment by karlhigley** [comment]
```
pip install -r pip-dep/requirements_notebook.txt
pip install jupyterlab
```
should also work.
