### ISSUE TITLE
test_fit[gaussian_mixture-1-cpu] is flaky

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#3467]
**Describe the bug**
test_fit[gaussian_mixture-1-cpu] has undefined behavior between multiple runs.

**To Reproduce**
Run the tests multiple times.

**Expected behavior**
To be deterministic between similar runs.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20

Error:
assert loss_after < loss_before
assert tensor(0.6931, grad_fn=<NllLossBackward>) < tensor(0.6931, grad_fn=<NllLossBackward>)

**Comment by gmuraru** [comment]
Closed because it was added an ```=``` sign in this [PR](https://github.com/OpenMined/PySyft/pull/3461/files#diff-1b4e80baf02b99d38e2a1837ac3620a8)

**Comment by karlhigley** [comment]
Does it still fail though? (I think it does, but could be wrong.)

**Comment by gmuraru** [comment]
Each time I have seen this failing was because there were the same values. Maybe we need to keep an eye open for this issue and if we see it again, re-open this?

**Comment by karlhigley** [comment]
Cool, will reopen if I see it happen.
