### ISSUE TITLE
Capsule zmq_client module error when running tests

### ISSUE THREAD

**Issue by tblazina** [OpenMined/PySyft#348]
I’ve installed capsule  within my openmined virtualenv and started an instance using `sh build_and_run.sh` as indicated but am still getting the ModuleNotFoundError: No module named ‘capsule.zmq_client’.  Maybe a dumb question but is it not possible to mock the client behavior in the tests so you don’t need to have a client running in order to be able to run tests?

**Comment by bharathgs** [comment]
can you do a `pip freeze` in your env, and see if it has been really installed?
I just, tested reinstalling capsule on my machine and  I could not reproduce your error.

**Comment by piyush2896** [comment]
I got the same error. If your system has python 3 and python 2 both installed. Then go to build_and_install.sh and change all *python* instances there to *python3*. It worked for me

**Comment by tblazina** [comment]
@bharathgs checked with pip freeze and have it installed. @piyush2896, ok so when I do as you said, it indeed runs the test however now in the termainal window where I have the capsule instance running it just is dumping 'Operation cannot be accomplished in current state'  repeatedly, did you happen to see this as well?

**Comment by piyush2896** [comment]
@tblazina got the same issue checked right now

**Comment by tblazina** [comment]
Nevermind, I did not have an instance of redis running.
Thanks a lot for the help!

Back to my other question though, is there no way to mock this for testing purposes? It seems a bit cumbersome to have three terminals running simply to run tests during development, no?
