### ISSUE TITLE
Don't use `assert` for non-debugging data validation (security risk)

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3480]
**Describe the bug**
`assert` is used throughout the code base as a way to validate assumptions about data shapes and properties. These checks can be globally disabled disabled with the -O and -OO flags, as well as the PYTHONOPTIMIZE env var.

**To Reproduce**
Search the `syft` module for `assert` and review the results. (Currently there are 86 such usages.)

**Expected behavior**
Data validation should be performed with `if/raise` instead of `assert`.

**Screenshots**
```
    # Check if t is 2-dim
    assert len(t.shape) == 2
```

**Additional context**
I think there's a setting for `bandit` to flag these, which we currently have disabled. Once these `asserts` are converted to `if/raise`, we can enable the `bandit` setting to prevent future recurrence of this issue.

**Comment by wicky1234444** [comment]
@karlhigley  can i take this?

**Comment by wicky1234444** [comment]
@karlhigley  should i convert all asserts in syft/ directory into if/raise or only that have data validation? for example should i convert `assert len(workers) > 0, "Please provide workers to receive the data" ` these also into if/raise.

**Comment by wicky1234444** [comment]
@iamtrask , @Jasopaum can i take this?

**Comment by gmuraru** [comment]
@wicky1234444 sorry for the late reply. If you are still interested in this, yes it is up for take :+1:

**Comment by teo-milea** [comment]
@gmuraru I can take this issue, if it is available.

**Comment by wicky1234444** [comment]
@teo-milea you can go ahead i am currently not working on this issue.

**Comment by duggalsu** [comment]
@gmuraru Hi, I can take this if still available

**Comment by ViveK-PothinA** [comment]
@kpiyush04 @wicky1234444 @gmuraru Is the issue closed?

**Comment by gmuraru** [comment]
Hey - This is available. Maybe @duggalsu you can sync with @ViveK-PothinA to work on it? :100:

**Comment by duggalsu** [comment]
Hi @ViveK-PothinA , have you started working on this? I will need a few days before I can begin

**Comment by ViveK-PothinA** [comment]
After this PR merge, there should be no assert statements in master branch. Maybe we can add the `bandit` flag on `assert` and close this issue.

**Comment by aanurraj** [comment]
thanks, @ViveK-PothinA closing this
