### ISSUE TITLE
Make `BaseWorker.send_command()` take explicit args instead of a `tuple`

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3481]
**Describe the bug**
`BaseWorker.send_command()` takes a `message` tuple, where position in the tuple indicates which argument is which. This makes it harder to provide proper type annotations and causes difficult to debug issues downstream.

**Expected behavior**
`BaseWorker.send_command()` should take explicit named arguments with type annotations.

**Screenshots**
```
    def send_command(
        self,
        recipient: "BaseWorker",
        message: tuple,
        return_ids: str = None,
        return_value: bool = False,
    ) -> Union[List[PointerTensor], PointerTensor]:
```

**Additional context**
A bunch of these issues surfaced while trying to trace `CommunicationActions` into `Roles` for `Protocols`.

**Comment by shubham3121** [comment]
@karlhigley created a pull request for this refactorization.
https://github.com/OpenMined/PySyft/pull/3487
