### ISSUE TITLE
Error in tutorial notebook 

### ISSUE THREAD

**Issue by Avyukth** [OpenMined/PySyft#349]
![screenshot from 2017-10-18 01-23-35](https://user-images.githubusercontent.com/3435944/31707696-acd01606-b40a-11e7-832f-d4cc9c5d40c0.png)

1> I could not understand how to pass the "pubkey" variable though the function don't take any variable in the implementation 

![screenshot from 2017-10-18 13-49-42](https://user-images.githubusercontent.com/3435944/31707938-4f6a6100-b40b-11e7-97df-24cc9085997c.png)
2>I think  in ModelRepository() call  ipfs=IPFS(host='ipfs')  as previous tutorial

**Comment by chunduri11** [comment]
I think issue raised here is resolved and merged in #332. This issue can be closed.
