### ISSUE TITLE
Jupyter Notebook Malfunctions from Clean Environment 

### ISSUE THREAD

**Issue by stephenjfox** [OpenMined/PySyft#3508]
**Describe the bug**
A clear and concise description of what the bug is:
In checking the validity of the project's documentation, I found the [pre-installation instructions](https://github.com/OpenMined/PySyft#pre-installation) don't leave me with a notebook-ready environment

```
conda create -n pysyft python=3.7
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
```

**To Reproduce**
1. Follow the aforementioned pre-installation instructions
2. Perform the installation `pip install 'syft[udacity]'`
3. cd into `PySyft`
4. run `jupyter notebook`
5. see what I see(?)

**Expected behavior**
Jupyter notebook should show me the folder structure

**Screenshots**

With the `pysyft` environment recommended by the documentation
![Jupyter notebook showing nothing by the container UI elements](https://user-images.githubusercontent.com/6251813/81689939-bbe26300-9428-11ea-89ae-56c7f17a3837.png)

With the environment I made by hand 

![Jupyter notebook showing a directory structure full of files](https://user-images.githubusercontent.com/6251813/81690821-d79a3900-9429-11ea-9123-4e45610ec30c.png)

Please note that in both environments, I can't create a new notebook. After clicking the "New" drop-down in the top-right corner
![image](https://user-images.githubusercontent.com/6251813/81690954-0fa17c00-942a-11ea-9ec2-a32ebf943446.png)

I can, however, run notebooks in the latter environment.

**Desktop (please complete the following information):**
 - Windows Subsystem for Linux on Windows 10 (latest, as of this post).
 - [WSL Ubuntu 16.04](https://www.microsoft.com/store/productId/9PJN388HP8C9)

**Additional context**

The output of `pip freeze | grep jupyter` :

* For pysyft

```
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.1
```

* For my environment
```
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
```

I have heard (and gleamed from too much time internet searching) that this can be a permissions error, but I have had no issue with other projects, repositories, file editing with other WSL projects on my system.
Thus, I am here.

Any assistance would be greatly appreciated.

**Comment by gmuraru** [comment]
Hey @stephenjfox.
Thank you for opening the issue.
It seems the problem is related to ```notebook```, ```tornado``` versions. More details can be seen in this [issue](https://github.com/jupyter/notebook/issues/3397).

The solution (for the moment) is to pin the ```notebook``` and the ```tornado``` versions like:
```
pip install jupyter notebook==5.7.8 tornado==4.5.3
```

Also, made a PR to update the description.

**Comment by gmuraru** [comment]
@stephenjfox could you point to me what version of tornado are you using?

**Comment by stephenjfox** [comment]
@gmuraru 
```
(pysyft) ➜  PySyft git:(master) pip freeze | grep tornado
tornado==4.5.3
```

I'll do you one better: here's my [my pip freeze output](https://github.com/OpenMined/PySyft/files/4719701/my_pip.txt)
