### ISSUE TITLE
Encryption design

### ISSUE THREAD

**Issue by MarcoROG** [OpenMined/PySyft#353]
We need to consider how we want to design the encryption functionality for Syft.

A lot of objects will have TensorBase members or even higher levels of nesting.
For such objects we want to provide "encrypt" and "decrypt" functionality, calling the corresponding functions on all its TensorBase and TensorBase-containing members.

This can lead to a lot of code duplication and boilerplate which can be avoided.
One idea would to use Mixins. The "Encryptable" mixin offers an "encrypt" method that iterates over all the members of the object and recursively calls "encrypt" on them, all the way down to TensorBase objects which actually get encrypted.

This is just a proposal, overall we should consider how to approach this problem.

We also need to consider, referring to issue #352, if we also want to encrypt the network hyperparameters (some might be obvious by inspecting object shapes)

**Comment by siarez** [comment]
@MarcoROG If I undestood you correctly, this sounds like a great idea. I think we can judge its merits better when we actually start implementing those “higher level” objects that use Encrypted Tensors. But it looks good from a distance :)

**Comment by MarcoROG** [comment]
This is inspired by Laravel Php traits. Where you have a Serializable trait/mixin and an attribute containing the list of fields you want that trait to apply to.
I'm fairly new to python (did mostly C++) so I don't know if it's a good pattern for the language
