### ISSUE TITLE
Make PySyft compatible with Google Colab

### ISSUE THREAD

**Issue by sukhadj** [OpenMined/PySyft#3533]
**Is your feature request related to a problem? Please describe.**
Google Colab is a great cloud platform to run your jupyter notebooks on GPUs/TPUs without having them connected to your local machines. Currently, PySyft doesn't run as expected on Colab, or sometimes doesn't even load properly.

(There are work-arounds to load pysyft - run the cell and restart the kernel but that doesn't guarantee the working of all the features)

The loading of pysyft produes following errors -
```python
!pip install pysyft
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.22.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible. 
```

I am not quite sure if the broken functionality is due to the incompatible dependency, but we should really get the syft working on colab. That would be awesome.

**Describe the solution you'd like**
Creating another requirements_colab.txt, if this because of the compatibility issue.

**Additional context**
Here is the link of colab notebook that I was working on - https://colab.research.google.com/drive/1QcZjXUIkBqAJa1baQH_2QfRE7UxhaJtP#scrollTo=K7WKRHKMLQiX . You can see that output if a cell is a tensor of NaN values. This works perfectly fine on my local machine. :sweat_smile:

**Comment by abogaziah** [comment]
Can you try to send a tensor then get it and see if you get a NaN? 
if not, can you try to regenerate the error with simpler code than that? I do not have the pickle file(s) so I can't really test if it works :)

**Comment by gmuraru** [comment]
I think we should not have those ```ERRORS```. Those appear because of our dependencies. ```Syft``` has ```requests``` as dependency, with version 2.22.
We need to check if we increase/install the correct dependencies we break our functionalities.

**Comment by hebabaze** [comment]
i think that can help 
``
!pip install syft==0.2.9 
``
![image](https://user-images.githubusercontent.com/54450458/116443903-7f379380-a854-11eb-96e5-09317b1144b3.png)
