### ISSUE TITLE
Code interfaces planning

### ISSUE THREAD

**Issue by MarcoROG** [OpenMined/PySyft#354]
We should start planning which components we will need, where will they go and how they will interact with each other.

This will offer developers a guarantee that certain functions won't change, so that they can start coding against them even if those functions are not implemented, and so that changes to a system don't break all the ones that depend on it.

This also gives an idea of what is already there and what are we doing, avoiding cases of "reinventing the wheel" (for instance implementing twice a Polynomial class for MPC and Nonlinearities in parallel)

**Comment by ebiwonjumit** [comment]
How should I start working on this?

**Comment by MarcoROG** [comment]
We should discuss the design, no coding needed for this issue
