### ISSUE TITLE
Assignment operator *= gives the wrong result! (for AdditiveSharingTensors)

### ISSUE THREAD

**Issue by kennysong** [OpenMined/PySyft#3542]
The assignment operator `*=` doesn't multiply properly for AdditiveSharingTensors.

See this example:

```python
import syft as sy
import torch as th
hook = sy.TorchHook(th)

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")

x = th.tensor([1,2,3,4])
x = x.share(bob, alice, crypto_provider=bob)

z = x[0]
for i in range(1, len(x)):
    z *= x[i]
z.get()  # <-- returns tensor(1)!
```

This gives `tensor(1)`, which is totally wrong!

Doing the assignment explicitly works, e.g. `z = z * x[i]`.

The addition assignment operator seems to work with no problems, e.g. `z += x[i]` works correctly.

**Comment by somiljain7** [comment]
AdditiveSharingTensors can be multiplied with long tensors and fixedPrecisionTensors
Don't directly multiply floats with AdditiveSharingTensor  as an error will come when you multiply an AdditiveSharingTensors with a FloatTensor.
But sharing with fixed_precision we will be able to handle float values like parameters in an encrypted way. 

1)if decrypt z
```
import syft as sy
import torch as th
hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
x = th.tensor([1,2,3,4])
x = x.share(bob, alice, crypto_provider=bob)
z = x[0].get() #z got decrypted 
for i in range(1, len(x)):
    z *= x[i]
z.get()  # <-- returns tensor(24)
```

2) if we use fixed_Precision
```
import syft as sy
import torch as th
hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
x = th.tensor([1.,2,3,4])
x = x.fix_prec().share(bob, alice, crypto_provider=bob)
z = x[0] # <--- z is encrypted
for i in range(1, len(x)):
    z *= x[i] # <-- inplace mul
z.get().float_prec()  # <-- returns tensor(24)
```
