### ISSUE TITLE
Iterate over wrapper of tensor pointer failed

### ISSUE THREAD

**Issue by KunlinY** [OpenMined/PySyft#3543]
**Describe the bug**
I would like to iterate over a torch tensor, which is send to a websocketclientworker. But it is non-iterator. 

**To Reproduce**
```
import torch
import syft as sy
import copy
hook = sy.TorchHook(torch)
from torch import nn, optim

bob = sy.VirtualWorker(hook, id="bob")
data = torch.tensor([[0,0],[0,1],[1,0],[1,1.]], requires_grad=True)
bob_data = data.send(bob)

for i in data:
    print(i)
for i in bob_data:
    print(i)
```

**Expected behavior**
It should list the tensors like the following:

> tensor([0., 0.], grad_fn=\<SelectBackward\>)
> tensor([0., 1.], grad_fn=\<SelectBackward\>)
> tensor([1., 0.], grad_fn=\<SelectBackward\>)
> tensor([1., 1.], grad_fn=\<SelectBackward\>)

**Screenshots**
However, it report the following error:

> TypeError: iter() returned non-iterator of type 'Tensor'

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu 18.04

**Comment by karlhigley** [comment]
Hmm, looks like this happens because our tensor types like `PointerTensor` don't implement the iterable interface for Python classes. That might be a missing feature, but if we implemented it, I don't think it would have the behavior you're expecting, since the resulting tensors would still be on the worker `bob` and not local.

As written, it would probably print something like:
```
[PointerTensor | me:12345 -> bob:23456]
[PointerTensor | me:34567 -> bob:45678]
[PointerTensor | me:56789 -> bob:67890]
[PointerTensor | me:78901 -> bob:89012]
```
To get the output you expect above, you'd need to fetch the results from `bob` to your local worker with something like:
```
for i in bob_data:
    print(i.get())
```

@gmuraru, what do you think about this? Is this something we can do with the current implementation of `PointerTensor`? Are there things I'm not thinking of that would make this difficult?

**Comment by gmuraru** [comment]
> Hmm, looks like this happens because our tensor types like `PointerTensor` don't implement the iterable interface for Python classes. That might be a missing feature, but if we implemented it, I don't think it would have the behavior you're expecting, since the resulting tensors would still be on the worker `bob` and not local.
> 
> As written, it would probably print something like:
> 
> ```
> [PointerTensor | me:12345 -> bob:23456]
> [PointerTensor | me:34567 -> bob:45678]
> [PointerTensor | me:56789 -> bob:67890]
> [PointerTensor | me:78901 -> bob:89012]
> ```
> 
> To get the output you expect above, you'd need to fetch the results from `bob` to your local worker with something like:
> 
> ```
> for i in bob_data:
>     print(i.get())
> ```
> 
> @gmuraru, what do you think about this? Is this something we can do with the current implementation of `PointerTensor`? Are there things I'm not thinking of that would make this difficult?

Currently, we allow indexing. We can do a ```bob_data[0]``` and it will create a ```PointerTensor``` on our machine that will point to the data on ```bob```'s machine. (like you specified @karlhigley).

What we can do, to implement the for: simply get the ```shape``` of the ```PointerTensor``` and then use the functionality we have for indexing.

To get a fast implementation:
```
shape = tensor_ptr.shape
for i in range(shape[0]):
    print(bob_data[i].get()) #
```

What can be a use-case for doing an iteration on a ````PointerTensor```? (you can replace the behavior with a ```get``` and then iterate over it)

**Comment by karlhigley** [comment]
Could we implement the iterable interface on `PointerTensor` to build that behavior in?

**Comment by gmuraru** [comment]
Sure. Started doing it :D
