### ISSUE TITLE
Raise an exception when crypto_provider is not provided when sharing the tensor

### ISSUE THREAD

**Issue by sukhadj** [OpenMined/PySyft#3545]
**Is your feature request related to a problem? Please describe.**
When we share the tensor using share() method, it by default assigns the calling worker (me) as a crypto provider. This allows us to perform addition and subtraction, however, it raises ObjectNotFound error after multiplication.   

**Describe the solution you'd like**
Raise warning when share() is called, something like 
>  You haven't provided crypto_provider. You won't be able to perform certain operations like multiplication

And a specific error when multiply or equate something like `CryptoProviderNotProvided` 

**To replicate**

```python

x = torch.tensor([1,2,3]).share(alice, bob)
y = torch.tensor([1,2,3]).share(alice, bob)

```

```python
print((x+y).get()) # Works
print((x*y).get()) # Raises ObjectNotFoundError

```

**Comment by ariannmichael** [comment]
I would like to take up this issue

**Comment by sukhadj** [comment]
Hey @ariannmichael I assigned you
