### ISSUE TITLE
Jupyter bug due to Tornado when following readme pre-installation

### ISSUE THREAD

**Issue by socd06** [OpenMined/PySyft#3546]
I followed the installation guide in the readme and had an issue using Jupyter due to its incompatibility with Tornado.

**To Reproduce**
1. Follow pre-installation and installation guide, Install virtual environment  
2. Run `conda install jupyter notebook ` to install `jupyter>6`
3. Running `pip install 'syft[udacity]'` will install `tornado==4.5.3` as required by [pip-dep requirements](https://github.com/OpenMined/PySyft/blob/master/pip-dep/requirements.txt)

**Expected behavior**
run `jupyter notebook` and you will not be able to see files or do any work.

![jupyter_acting](https://user-images.githubusercontent.com/51087091/82234559-914c4a80-98ff-11ea-830f-4ca781b580d3.png)

**Additional Context**
As stated by [ltalirz](https://github.com/ltalirz) "this occurs when using notebook>=6 with tornado<5
E.g. try pip install 'notebook<6' or conda install 'notebook<6'."

See [related issue](https://github.com/jupyter/notebook/issues/2400)

**Temporary solution**
`pip install 'notebook<6'` worked for me

I hope this can be fixed as it will prevent new people from doing any work without looking up a solution for this first.

**Comment by karlhigley** [comment]
Hmm, a compatible notebook version is listed in [`requirements_notebook.txt`](https://github.com/OpenMined/PySyft/blob/master/pip-dep/requirements_notebooks.txt#L2). Should it also be in `requirements_udacity.txt`?

**Comment by karlhigley** [comment]
Alternately, maybe it would be cleaner to add the notebook requirements to the `udacity` extras in [`setup.py`](https://github.com/OpenMined/PySyft/blob/master/setup.py#L53)?

**Comment by socd06** [comment]
Thanks for replying @karlhigley 
Any or both solutions look great. You could also add the `jupyter<6` version requirement to the readme  Jupyter install or `tornado>5` to [pip-dep requirements](https://github.com/OpenMined/PySyft/blob/master/pip-dep/requirements.txt)

I saw that it's listed in [requirements_notebook.txt](https://github.com/OpenMined/PySyft/blob/master/pip-dep/requirements_notebooks.txt#L2) but you won't install those requirements if you follow the readme. Maybe installing with `python setup.py install` won't yield this bug but I was not able to do so due to an `access denied` error, which could be another issue by the way.

**Comment by rajathpatel23** [comment]
Hi, I would like to work on this issue.

**Comment by socd06** [comment]
Please, go ahead @rajathpatel23

**Comment by rajathpatel23** [comment]
Thank you

**Comment by rajathpatel23** [comment]
PR created: [PR3605](https://github.com/OpenMined/PySyft/pull/3605)

**Comment by karlhigley** [comment]
Closed by #3606
