### ISSUE TITLE
torch.autograd.grad support/usage in PySyft?

### ISSUE THREAD

**Issue by KunlinY** [OpenMined/PySyft#3547]
**Describe the bug**
I would like to use torch.autograd.grad to calculate gradients. The input parameters are in the same WebsocketClientWorker. It would report this error:

> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

If I fetch both parameters using tensor.copy().get(), all the grad would be None because there is no grad_fn.

However, if I remove PySyft, my tensors contains grad_fn and it runs correctly without error

**To Reproduce**
`
loss = self.net.loss(trn_X, trn_y) 

gradients = torch.autograd.grad(loss, self.net.weights())
`

**Expected behavior**
No error. Not-None gradients.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
I guess there might be a workaround or hook for torch.autograd.grad in PySyft, so I didn't put much details of my code. How could I use torch.autograd.grad for remote tensor objects?

**Comment by iamtrask** [comment]
Hi @KunlinY - I’m afraid this is a known issue which will be fixed in the upcoming refactor. Look for the release of syft 0.3.

**Comment by shahdev** [comment]
Hi @KunlinY did you manage to solve this? I am getting the same error when I use torch.autograd.grad
