### ISSUE TITLE
Create a better Readme

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PySyft#3549]
[Based on this readme template](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md), we should improve our readmes across all OpenMined projects.

[Please consult the following document for our desired best practices.](https://docs.google.com/document/d/126smq1Gful_mo-x5Wm1M1UJW9CvB8fT9YYZmamNqk0M/edit?usp=sharing)

**Comment by ReshinthAdith** [comment]
I want to start the Technical Writing part, What's the procedure?

**Comment by krharsh17** [comment]
Hi, I'd like to work on this issue. Could you please assign it to me?

**Comment by cereallarceny** [comment]
Done! Keep us updated on your progress @krharsh17 !

**Comment by cereallarceny** [comment]
@iamtrask can we stop marking issues like this as stale?

**Comment by madhavajay** [comment]
This has already started to be addressed by our existing 0.3.x roadmap.
