### ISSUE TITLE
Create Docs Folder for All Repos

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3551]
**Is your feature request related to a problem? Please describe.**
In all OpenMined repos, we want to have a /docs folder which can contain markdown files for our documentation. To complete this issue, create a docs folder in each repo (not just PySyt) and add an initial boilerplate "README.md" in the folder.

**Comment by AlanAboudib** [comment]
We will work on this.

**Comment by eric-yates** [comment]
I'll handle this for PyGrid!

**Comment by eric-yates** [comment]
Should we use the README template from the .github repo? ie. [this one](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md)
