### ISSUE TITLE
'VirtualWorker' object has no attribute '_tensors' in tutorial - 9

### ISSUE THREAD

**Issue by vtanwar-iitr** [OpenMined/PySyft#3558]
I am completely new to PySyft and got an error of "VirtualWorker' object has no attribute '_tensors", when I am working in Encrypted Domain Computation. Please help me.

import torch
import syft as sy
hook = sy.TorchHook(torch)

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
bill = sy.VirtualWorker(hook, id="bill")

x = torch.tensor([25])

x
tensor([25])

x = torch.tensor([25]).share(bob, alice, bill)

bobs_share = list(bob._tensors.values())[0]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-66d08ba6d652> in <module>()
     13 x = torch.tensor([25]).share(bob, alice, bill)
     14 
---> 15 bobs_share = list(bob._tensors.values())[0]

AttributeError: 'VirtualWorker' object has no attribute '_tensors'

**Comment by karlhigley** [comment]
@vtanwar-iitr I think this was broken by a recent change. Try `bob.object_store._tensors`?

**Comment by vtanwar-iitr** [comment]
@karlhigley Thanks for your reply..

I tried "ob.object_store._tensors" but this is not working showing same error..

VirtualWorker' object has no attribute 'object_store

However, I reinstalled the complete Syft and other dependencies in a new Conda environment. It's working great.

**Comment by vtanwar-iitr** [comment]
The query has been resolved , therefore I am closing this issue.
