### ISSUE TITLE
Decrypting secret value from shares via adding in Line 22, tutorial 9

### ISSUE THREAD

**Issue by vtanwar-iitr** [OpenMined/PySyft#3564]
**EXISTING**
secret value = tensor([25])

In 22: (bob_share + alice_share + bill_share)
out 22: [tensor([a]),  tensor([b]),  tensor([c])] is not equal to tensor([25])

**CORRECTED**
In 22': (bob_share[0] + alice_share[0] + bill_share[0])
out 22': [tensor([a]),  tensor([b]),  tensor([c])] is equal to tensor([25])

**Comment by Jasopaum** [comment]
What do you mean? I think this part of the notebook is working fine. Maybe a version problem?
