### ISSUE TITLE
PySyft Tornado Version Breaks Jupyter Lab

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3568]
**Describe the bug**
Installing PySyft on a clean machine breaks jupyter notebook because our requirements.txt file has a fixed version.

**Comment by iamtrask** [comment]
Symptom: jupyter notebook fails to open... it just hangs.

**Comment by iamtrask** [comment]
Changing tornado depenency to 6.0.4 fixes it

**Comment by karlhigley** [comment]
See #3546 for discussion on this.

**Comment by karlhigley** [comment]
Closing as duplicate.

**Comment by iamtrask** [comment]
Not technically a duplicate - in the other issue we wont' change versions because we want to maintain compatibility with the build for the Udacity course.

However, this bug is about master instead (which I failed to specify)

**Comment by iamtrask** [comment]
Not technically a duplicate - in the other issue we wont' change versions because we want to maintain compatibility with the build for the Udacity course.

However, this bug is about master instead (which I failed to specify)

**Comment by karlhigley** [comment]
What do you mean “about master”?

**Comment by iamtrask** [comment]
Yes - brain fart - my apologies. 

That being said - given that it's been a year and we have big changes on the horizon - I think I'd rather have a pip install which worked with the latest jupyter by default and we just tell Udacity folks to use a specific version.

**Comment by MGough** [comment]
I'm aware this is a stale & closed issue, but it seems like a strange decision to force a pinned dependency on those using the library for the sake of a specific use case (Udacity course). 

As an aside, including `notebook` as a dependency for a specific use-case, when someone is using IPython on GCloud seems a little over the top, it seems like that would make more sense as an `extra`.
