### ISSUE TITLE
.private_tensor() requires a tuple when it should ask for a list and cast it to a tuple

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3569]
**Describe the new feature**
```
th.tensor([1,2,3,4]).private_tensor(allowed_users=("Ionesio",))
```

This is what I currently have to do to initialize a private tensor. However, the notation for initializing a tuple in Python is clunky because you have to create parentheses and then a comma.

```
th.tensor([1,2,3,4]).private_tensor(allowed_users=["Ionesio"])
```
This is what I'd like to do instead - which can cast to a tuple in the backend.

**Comment by AlanAboudib** [comment]
What is the reason it should be cast to a tuple? immutable? I tend to use sets whenever I need to use the `in` operator. like:

```
if user in allowed_users:
```
