### ISSUE TITLE
register() should not be hardcoded to our main AWS node

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3575]
**Is your feature request related to a problem? Please describe.**
We should create a separate repository in OpenMined which has a single file in which supported OpenMined nodes are listed. This should be a separate repo from PySyft because its permissions will be very restricted, and this repo will not be versioned (it will simply be updated to reflect the current available OpenMined hosted nodes).

Instead of PySyft being hard-coded to find a single AWS node. It should parse this file and extract the dictionary (string key -> http value) mapping to one or more nodes.

register() should optionally allow you to specify which OpenMined grid node you want to register with. If you don't specify one, it should choose the first one in the dictionary unless it fails to connect... then it should try the second one.

The information printed when you call .register() should VERY OBVIOUSLY tell you which node you've connected to. Best guess... it would be great if each node was keyed by a color name ("red", "blue", etc.). And then the output to .register() should change the color according to whichever node you connected to.

**Comment by IonesioJunior** [comment]
Any thoughts on the repository name?

**Comment by iamtrask** [comment]
Up to you - we used to call it "BootstrapNodes" 

Maybe "NodesWeHost"
