### ISSUE TITLE
Overload __getitem__ to be able to index into connected nodes

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3577]
**Is your feature request related to a problem? Please describe.**

When I call 

```
me = sy.grid.register()
```
I want to be able to select connected nodes by just calling 

```
me['another_node']
```

instead of having to use a private variable

me._connection_handler.get("another_node")

**Comment by joaolcaas** [comment]
Can i take this one?

**Comment by karlhigley** [comment]
May I suggest something like `me.peers[“another_node”]` to make explicit what’s happening?

**Comment by joaolcaas** [comment]
@karlhigley  in this case, overload `__getitem__` is not necessary anymore?

**Comment by karlhigley** [comment]
Yeah, I guess not. 👍
