### ISSUE TITLE
torch.tensor.size() function may get wrong shape after the tensor is sending to a gpu.

### ISSUE THREAD

**Issue by LiuChiennan** [OpenMined/PySyft#3580]
I use syft to execute a FL task, I found sometimes the torch.tensor.size() will get wrong results.
Here I implement the following code in a ubuntu 16 system to show this bug: 
>>> import torch
>>> import syft as sy
>>> data = torch.randn([8, 24, 24, 24, 3, 5])
>>> target = torch.randn([8, 24, 24, 24, 3, 5])
>>> data = data.cuda()
targe>>> target = target.cuda()
>>> hook = sy.TorchHook(torch=torch)
>>> worker1 = sy.VirtualWorker(hook, id="worker1")
>>> data.send(worker1)
(Wrapper)>[PointerTensor | me:32788080090 -> worker1:15663574719]
>>> data.location
>>> data = data.send(worker1)
>>> data.location
<VirtualWorker id:worker1 #objects:1>
>>> target = target.send(worker1)
>>> target.location
<VirtualWorker id:worker1 #objects:2>
>>> data.size()
torch.Size([0])
>>> target.size()
torch.Size([0])
>>> data.shape
torch.Size([8, 24, 24, 24, 3, 5])
>>> target.shape
torch.Size([8, 24, 24, 24, 3, 5])
>>> 

As shown above, we can see that when one tensor has been sent to a gpu and a worker , it's .size() function get torch.Size([0]), I don't know why this happens, and it's .shape attribute still works.

Another problem I found is for a torch.nn.Module object, we name it as model, model.send(worker).cuda() may throw exception, while model.cuda().send(worker) works.

**Comment by karlhigley** [comment]
Sadly, this is a known issue that we don't currently have a way to fix. See previous discussions in #2201, #2527, #3163, #3382, and #3554.
