### ISSUE TITLE
Refactor naming in syft.generic.pointer

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#3597]
## Description
Currently, in `syft.generic.pointer`, we are using pointer_* or *_pointer, we should stick to the second one. The refactor would mean to rename all files, classes and variables to respect *pointer.

Eg: pointer_dataset.py -> dataset_pointer.py

**Comment by punitkoura** [comment]
I would like to take up this issue. Seems like a good way to get familiar with the code base :)

**Comment by tudorcebere** [comment]
Amazing, ping me on slack if you have any questions. :+1:

**Comment by punitkoura** [comment]
Issue not stale... I'm in the process of sorting out a few issues before I can contribute. Apologies for the delay.

**Comment by punitkoura** [comment]
@tudorcebere Could you please remove the stale label? I don't have access to do this I think.

**Comment by tudorcebere** [comment]
@punitkoura Hey there, you might want to look at the new refactor issues, as we decided that there is some technical debt around, we are going to refactor syft. This version of pointers/workers/etc. won't be around for too much.
