### ISSUE TITLE
Improve documentation in syft.messaging.

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#3598]
## Where?
`syft.messaging.message.py` deserves some love, including some type hints/better documentation.

## What?
Describe the messages, maybe add better testing to some features class `ObjectRequestMessage` has the field user but it's not tested/used too much. Better documentation/testing would be epic.

**Comment by Coantox** [comment]
Hello, I think I can help with that in the next few days.

**Comment by tudorcebere** [comment]
Great! Ping me on Slack if you have any questions. :+1:
