### ISSUE TITLE
test coverage on local machine not working

### ISSUE THREAD

**Issue by IamRavikantSingh** [OpenMined/PySyft#3602]
## Where?
https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md#writing-test-cases

## Who?
Developers

## What?
I am trying to evaluate test coverage on my local machine but `coverage run --omit=*/venv/*,setup.py,.eggs/* setup.py test` does not execute.

## Additional Context
`zsh: no matches found: --omit=*/venv/*,setup.py,.eggs/*`

**Comment by karlhigley** [comment]
I can replicate this behavior on `zsh`. This command is structured to be run as part of the automated test suite (where packages are built with a `venv`), so you'll need a slightly different format to run it locally. Try:
```
coverage run --omit=setup.py setup.py test
```

**Comment by karlhigley** [comment]
(Closing, but feel free to re-open if this doesn't address your issue.)
