### ISSUE TITLE
Add the `obj_id` argument to the `register_obj` method of `BaseWorker`

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/PySyft#3616]
## Description

In `syft/workers/base.py` the `register_obj` method is defined as:

```
def register_obj(self, obj):
    self.object_store.register_obj(self, obj)
```

You can notice that we can only send the object we want to register to the function, the call is then forwarded to the `register_obj` method of the `object_store` property.

However, the `register_obj` method of the `ObjectStore` class in `syft/generic/object_storage.py` is defined as:

```
def register_obj(self, obj: object, obj_id: Union[str, int] = None):
```

Notice that we can pass not only the object but also its id. 

So the `register_obj` of `BaseWorker` prevents us from using the full potential provided by the `ObjectStorage` class when registering object.

I suggest to add the possibility to choose the id in the `BaseWorker`'s `register_obj` method.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context

In SyferText, I need to register `State` object using predefined `IDs` in the workers' object stores. I need the worker's `register_obj` method to allow me to do that.

**Comment by iamtrask** [comment]
Shouldn’t the object have an id at all times already? This seems like it might slow the api with an extra arg. Is there an exception here? 

If anything maybe we should remove the id option from the object store api.

**Comment by AlanAboudib** [comment]
I will test this quickly. I think you are right. the argument is redundant.
