### ISSUE TITLE
ForceDeleteMessage is an important proportion of the msg exchanged. In latency scenarios this is by default a blocking op and make computation much slower.

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3627]
Should we batch those messages ?

This is a suggestion from @LaRiffle to improve the performance of cryptographic protocols.

**Comment by iamtrask** [comment]
No need for this to be a blocking op is there.

I think the correct answer here is already in play via protocols and asynchronous comms.

We could work on sophisticated batching but not a high priority and increases the chance of leaks if comms get disconnected. Also torch re uses tensors intelligently so GC less might have perf issues elsewhere. 

The solution is plans and protocols - closing.

**Comment by karlhigley** [comment]
I think `Plans` and `Protocols` require a solution to this issue, but I don’t think they are the solution themselves.

If we rework `Workers` to have multiple threads for processing messages and executing actions, we’re going to need queues for passing incoming actions (from messages) in to the execution thread and outgoing messages back out to the communication thread. If we do that, then GC will mostly happen on the execution thread, so it will enqueue a lot of delete messages. My hunch is that having a queue that may contain multiple deletes would make batching easier—when you send a delete message, you iterate through the queue and pull _all_ the delete messages, then send them as a single message.

Our garbage collection probably needs bigger tweaks than this though. (Distributed system life is hard. 😅)

**Comment by iamtrask** [comment]
Is there a way to mark this as a part of the protocols project?

**Comment by karlhigley** [comment]
Labeled `protocols` and added to a new `Asynchronous Workers` milestone.
