### ISSUE TITLE
Figure out how to handle dependencies that work on a subset of the Python versions PySyft can support (Crypten >= 3.7, Tensorflow <= 3.7)

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#3628]

**Comment by gmuraru** [comment]
I had a discussion with @karlhigley about this and we were thinking about something like this:
* Have different workflows for each supported framework:
   Eg: torch, tensorflow, crypten, etc..
* Each workflow should have a specific dependency file which will get installed
* Each workflow can have multiple ```sub-flows``` which trigger the tests for that specific framework with the specific python version.

The idea is to have another top level workflow which is specific for each supported framework.
