### ISSUE TITLE
Running PySyft on v1.5.0+cpu by modifying the file that detects the version of pysyft.

### ISSUE THREAD

**Issue by AnthonyTheKoala** [OpenMined/PySyft#3633]
Sorry, the heading should be:
Running PySyft on v1.5.0+cpu of pytorch by modifying the file that detects the version of pytorch

I have tried to install PySyft, **BUT I KNOW** that it failed to install because I am using pytorch 1.5.0+cpu

Worked out that pysyft requires pytorch 1.4.0

- I tried to find source file that detects pytorch v1.4.0 to modify it to handle v1.5.0+cpu. What is the name of the source file that detects versions of pytorch so I can modify it to accept v1.5.0+cpu? Then I can re-install the pysyft package using  python setup.py install

Alternative question.
- Will there be a version of pysyft that will handle pytorch v1.5.0+cpu soon?

Thank you in advance
Anthony of Sydney

**Comment by gmuraru** [comment]
For the first question:
* I think you can simply install torch 1.5 by using the pip command in your environment:
```pip install torch==1.5```
Second question:
* There is already an opened [issue](https://github.com/OpenMined/PySyft/issues/3395) regarding this, but I do not know if there is a concrete timeline when this will get in (@karlhigley @iamtrask)

**Comment by AnthonyTheKoala** [comment]
Dear gmurau,
Thank you. I had no problem installing pytorch according to https://pytorch.org/ , in the section. "QUICK START LOCALLY", I used the pip version for Win without cuda to be:
pip install torch===1.5.0 torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html

So problem installing pytorch:

BUT the first question has not been answered because pysyft could not be installed because it required pytorch v 1.4.0. I have the **higher version** at 1.5.

My question again please:
I have the source code of pysyft. I want to know which file in the source code that detects v1.4.0 of pytorch such that I can modify the line to pass through v.1.5.0+cpu of pytorch such that I can compile and install. 

Again, which file in the pysyft package detects v1.4.0 of pytorch such that **I can modify the source code and replace v1.4.0. with v.1.5.0+cpu of pytorch?**

Thank you, merci, gracias, gracie 
Anthony of Sydney

**Comment by karlhigley** [comment]
There isn’t a specific line that detects the PyTorch version. You could update the requirements file and give that a try, but the work to make PySyft compatible with PyTorch 1.5 hasn’t happened yet. I would expect errors along that path, but we’d love to have help addressing them.

**Comment by AnthonyTheKoala** [comment]
Dear Karl,
Thank you for your reply.
It seems that I changed the requirements file' entry of pytorch 1.4.0 to pytorch 1.5.
In addition it also required me to pip additional packages:
av, crc32c, pyb, pylibsrtp, dataclasses, pyee, tblib, pydot, aioice 
I reinstalled pysyft using: python setup.py install  OK

Now in python I did the following:
import syft as sy    ;#so far so good
sy.__spec__
ModuleSpec(name='syft', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000000000364FA58>, origin='C:\\Python36\\lib\\site-packages\\syft-0.2.6-py3.6.egg\\syft\\__init__.py', submodule_search_locations=['C:\\Python36\\lib\\site-packages\\syft-0.2.6-py3.6.egg\\syft'])
sy.__package__
'syft'

It appears to work, BUT there is no sy.__version__

In sum, it appears to work,  
However I would like to be directed to a simple example to test installation.

Thank you, merci, gracias, gracie,
Anthony of Sydney

**Comment by karlhigley** [comment]
@AnthonyTheKoala 🎉 

I'd try running the test suite with `pytest test/` or `make test` to see what other issues crop up.

**Comment by AnthonyTheKoala** [comment]
Dear Karl,
Thank you for your reply.
After running `pytest test`, I had to install the following by pipping:

- papermill
- openssl
- nbformat
- pyopenssl (in order to import OpenSSL as ssl alternatively from OpenSSL import SSL)

In addition:
- Then I re-ran `pytest test`:
   * it was testing a lot of codes with a progress of the test expressed as a percentage. Then a summary...
   * 33 failed, 751 passed, 42 skipped, 163 warnings, 1 error in 2314.10 seconds - **What is the significance of this?**
   * then on two occasions displayed EOFError 

- **I also** I ran the jupyter notebook 'tutorial' in `C:\Python36\PySyft\examples\tutorials` running Part01 and Part02. They seem to work.
 
Thank you,
Anthony of Sydney

**Comment by karlhigley** [comment]
The 33 failed tests represent parts of PySyft that don’t work properly with PyTorch 1.5 yet. The Syft Core team plans to work on this is the near future, but hasn’t gotten there yet.

**Comment by AnthonyTheKoala** [comment]
Dear Karl,
Thank you for the reply.

For yours and the Syft Core team additional information, the other observation I make is when I tried the "experimental tutorials", using jupyter notebook there were errors produced. 

Question please: I'm patient and will wait. When Syft is developed for v1.5.0 Pytorch: Do I do this in the following ordered sequence?
* Do I uninstall Syft for Pytorch v1.4.0?
* Do I erase the Syft package for Pytorch v1.4.0? 
* Do I re-git Syft for Pytorch v1.5.0? - Alternatively, in other words, does re-gitting a package mean that I don't have to erase the Syft package for Pytorch v1.4.0?

Thank you, merci, gracias, gracie,
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
Dear team,
For your assistance, I have produced a file called "results - failures and skips.txt" which contains all those sections which have skipped and failed under the running of `pytest test`.

I hope this helps everyone,

Thank you, merci, gracias, gracie
[results - failures and skips.txt](https://github.com/OpenMined/PySyft/files/4716571/results.-.failures.and.skips.txt)

Anthony of Sydney
