### ISSUE TITLE
Explanation of server_config

### ISSUE THREAD

**Issue by erksch** [OpenMined/PySyft#3658]
## Question

Hey there!
I am getting confused with the parameters of `server_config` for GridClient's `host_federated_learning`:
```
server_config = {
  "min_workers": 3, 
  "max_workers": 3,
  "pool_selection": "random",
  "num_cycles": 5,
  "do_not_reuse_workers_until_cycle": 4,
  "cycle_length": 28800,
  "minimum_upload_speed": 0,
  "minimum_download_speed": 0
}
```

Could you explain one by one what the parameters do?
I am trying to figure out how to configure when my grid recomputes the model. Is it when there are a number of diffs received the same as min_workers? And then why is there max_workers? Why do I need a number of cycles? Shouldn't the model just update after each cycle? Or are the number of workers only for one cycle and with this configuration you would need 15 different workers that report diffs in a total 5 cycles? And then what does cycle length mean? 

So many questions :D

**Comment by erksch** [comment]
Anyone?

**Comment by IonesioJunior** [comment]
Hello @erksch!
I believe that a vague explanation of the meaning of each parameter can be even more confusing. Therefore, I'm linking this [document](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md) for a better understanding.

If any questions still persist, feel free to create another issue, or ask in our slack.

**Comment by IonesioJunior** [comment]
@erksch, Did it solve your question?
