### ISSUE TITLE
0.3.1 EPIC 3: Protobuf Object Serialization in Python

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3698]
## Description
Once #3696 has been completed, we have enough functionality to perform remote computations if we have the ability to serialize PySyft's objects. For this we will use Protobuf serialization within a new version of syft-proto.

## Why?
Protobuf is an industry standard, polyglot serialisation and deserialisation library.

## Breakdown
This epic can be broken down into the following issues:

MUST HAVES: (These were completed as part of 0.3.0)
- Protobuf Serde for Core PySyft Classes
- Protobuf Serde for Torch Classes

STRETCH: (These will be scheduled for 0.3.1+)
- Protobuf Serde for Tensorflow Classes
- Protobuf Serde for Numpy Classes
- Protobuf Serde for Jax Classes
- Protobuf Serde for Keras Classes
- Protobuf Serde for Pandas Classes
- Protobuf Serde for Scikit Learn Classes
- Protobuf Serde for matplotlib classes
- Protobuf Serde for Tensorflow Encrypted Classes
- Protobuf Serde for Crypten Classes
- Protobuf Serde for Tensorflow Federated Classes
- Protobuf Serde for PyDP Classes
- Protobuf Serde for PyPSI Classes
- Protobuf Serde for SyferText Classes
- Protobuf Serde for Spacy Classes
- Protobuf Serde for PIR Classes
- Protobuf Serde for PSI Classes
- Protobuf Serde for PyVertical Classes
- Protobuf Serde for PyFE Classes
- Protobuf Serde for PyDentity Classes

## Who else?
This work shouldn't affect too many teams as the class definitions are defined in a separate epic. However, we would mark most of these tickets as "good first issue" as they are ideal for entry-level contributors.

**Comment by madhavajay** [comment]
Most of this is completed, other libraries will be approached once we are ready to plan more third party support.
