### ISSUE TITLE
Unable to import syft from master branch

### ISSUE THREAD

**Issue by joaolcaas** [OpenMined/PySyft#3712]
## Description
When I try to import syft from the master branch, an error shows up. Look like a `Command` that before were in `pythreepio.utils` is there no longer. 

## How to Reproduce
1. install syft on master branch
2. import syft

## Expected Behavior
ImportError: cannot import name 'Command' from 'pythreepio.utils' (/home/joaolucas/Documents/PySyft/venv/lib/python3.7/site-packages/pythreepio/utils.py)

**UPDATE: PYSYFT IS BROKEN AS LONG AS THIS IS OPEN**

**Comment by LaRiffle** [comment]
Fixed by #3725
