### ISSUE TITLE
Automatic type-checking of Python type hints

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3722]
## Feature Description
In a previous prototype for a PySyft rebuild found [here](https://github.com/OpenMined/PySyft/blob/syft_4v2/syft/check.py), I wrote a new decorator which enforces type checking of python type hints when unit testing. To close this issue:

1) Move the functionality into syft_0.3.0 branch.
2) Add type hints to all methods in the codebase.
3) Create a "CONTRIBUTING.md" file and add hints as a requirement.

**Comment by tudorcebere** [comment]
I'll look into this one.

**Comment by iamtrask** [comment]
All yours!

**Comment by iamtrask** [comment]
Things to watch out for:
- I never tested whether it affected runtime performance (when it should be turned off). I hope it shouldn't but it might.
- I didn't check whether it impacted testing performance.

**Comment by iamtrask** [comment]
Fixed by https://github.com/OpenMined/PySyft/pull/3804
