### ISSUE TITLE
Automatic documentation from the start (with minimum "mergable" standards!)

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3723]
While at first glance it may seem that automatic documentation is already supported in the syft_0.3.0 branch, our adoption of automatic documentation technologies is not. In order to close this feature we want to:

1) define in a CONTRIBUTING.md file the minimum documentation standards for methods, classes, module functions, and high level features, including code generated code. It's not enough simply to have inline documentation, we must have explanations for how to do high level things in our library and, more importantly, we must know when new explanations/tutorials must be written.
2) Attach our documentation to a service for hosting sphinx based documentation so that when we merge into syft_0.3.0 the documentation on the internet is automatically updated.
3) Add documentation to all of the existing codebase to be compatible with (1). 

This is an issue which might seem like it's easy - but it actually requires quite a bit of creativity and extra care to really do a good job.

**Comment by iamtrask** [comment]
I'm currently working on this - but anyone is welcome to jump in and get the codebase up to minimum documentation standards.

**Comment by wip-abramson** [comment]
Will you be working on this tomorrow? I am keen to get more familiar with Syft and learn from the documentation approach so we can replicate something similar as we start to build out the identity repo.
