### ISSUE TITLE
Add OpenCollective to pip install

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3724]
## Feature Description
Some projects add a message during installation which solicits for donations to support the builders of the library. I think that this is an appropriate thing for us to do in a low-profile way such as through a simple message (https://github.com/Homebrew/brew/issues/4644).

For this issue, work on how to deliver a colored message at the end of a pip install which would link to OpenMined's OpenCollective account.

**Comment by em-blue** [comment]
Do you want it like this? 
https://github.com/preactjs/preact/pull/588/commits/36b02704413a79eefc28be133c8acc02a50d77e6

Which uses this: 
https://github.com/opencollective/opencollective-postinstall

If so, I would like to try!

**Comment by madhavajay** [comment]
This is an example of what we want:
https://github.com/Homebrew/brew/issues/4644

**Comment by Gokkulnath** [comment]
@madhavajay Based on discussions on slack, we decided to display the  solicitation message on import of library as pip natively doesn't support this feature yet (see https://github.com/pypa/pip/issues/5970 )

I made a PR here: https://github.com/OpenMined/PySyft/pull/4930
