### ISSUE TITLE
100% test coverage requirement

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3726]
## Feature Description
In previous versions of PySyft, we had a 95% requirement for testing coverage. However, this allowed for quite a bit of wiggle room. Some would merge big PRs with full coverage which would push us above 95 and then others would merge small PRs with no testing riding the coat tails of other PRs. This time I'd like us to start with 100% coverage and explicitly mark things as not testing if we don't want to test it.

So, for this PR to be closed, let's:

- [ ] get the syft_0.3.0 branch to 100% testing coverage (coverage testing is already in the codebase)
- [ ] get travis setup to block if coverage is less than 100%

**Comment by madhavajay** [comment]
Dupe: https://github.com/OpenMined/PySyft/issues/4805
