### ISSUE TITLE
Automatically tested (travis), multi-language support for example notebooks

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3727]
## Feature Description
In the previous version of PySyft, we automatically test our notebooks. However, they have fallen behind because multi-language support lead to the notebooks failing for lots of reasons which meant that we stopped blocking PRs for passing notebook testing. Now several of the notebooks are broken and people are complaining.

In this PR, please 
- [ ] create a small notebook which has smooth support for at least 2 languages in one notebook. We can talk on this issue about how best this should be done.
- [x] add notebooks to the unit testing suite, such that all notebooks in the notebook folder will be tested.

**Comment by ramesht007** [comment]
hey, @iamtrask can I work on this issue
