### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3729]
## Feature Description
This Epic captures Issues to be done to define an abstract worker class called "Client" which is currently defined [here](https://github.com/OpenMined/PySyft/blob/syft_0.3.0/src/syft/worker/client.py#L1). I am making this an Epic because we will very likely update this issue multiple times between now and when it's done, so we can link issues to this Epic as needed.

## Why?
The purpose of a Client is to cache functionality about how a remote worker including most importantly how to send messages of various types to it. The client also exposes an API which the rest of the Syft library can employ when attempting to send messages to the remote worker. The information cached locally is also used to attempt to lower the number of messages which need to be sent, to provide warnings when the number of messages may be exceeding the limit of the remote worker, and in general to make it as easy and intuitive as possible to coordinate actions regarding one or more remote workers.

## Breakdown
Provide a bulleted or numbered list of how you might break this epic down into smaller issues.

- Generate Clients from Workers
  - Sub-issue 1
  - Sub-issue 2
- Another high-level problem
- Et cetera

## Who else?
Does this work affect any other repositories, projects, or teams? If so, [provide links to the repos and teams you'll be involving](https://github.blog/2012-05-09-introducing-team-mentions/).

**Comment by gmuraru** [comment]
@tudorcebere you took over this, right?
