### ISSUE TITLE
ModuleNotFoundError: No module named 'pythreepio'

### ISSUE THREAD

**Issue by thormacy** [OpenMined/PySyft#3762]
## Description
Run examples/advance/websockets_mnist
ERROR: 
ModuleNotFoundError: No module named 'pythreepio'

## How to Reproduce
cd path/PySyft-master/examples/tutorials/advanced/websockets_mnist
python start_websocket_servers.py

## Expected Behavior
Example should work without error

## System Information
 - OS: Mac
 - OS Version: 10.15.5
 - Language Version: Python 3.6
 - Package Manager Version: latest

**Comment by NeuZhangQiang** [comment]
@thormacy, we should import syft rather than import PySyft-master/syft. 

There is something wrong with the original example, and we need some modifies. 

Copy the websockets_mnist in your Desktop or other folder (make sure it is not included by PySyft-master)

And the folder files is:
```
run_websocket_client.py
run_websocket_server.py
start_websocket_servers.py
```
the run_websocket_server.py is copied from the PySyft-master/run_websocket_server.py.

The start_websocket_servers.py should also be modified as following:
```
import subprocess
import sys
from pathlib import Path

python = Path(sys.executable).name

FILE_PATH = './run_websocket_server.py'

call_alice = [python, FILE_PATH, "--port", "8777", "--id", "alice"]

call_bob = [python, FILE_PATH, "--port", "8778", "--id", "bob"]

call_charlie = [python, FILE_PATH, "--port", "8779", "--id", "charlie"]


print("Starting server for Alice")
subprocess.Popen(call_alice)

print("Starting server for Bob")
subprocess.Popen(call_bob)

print("Starting server for Charlie")
subprocess.Popen(call_charlie)

```

Then, you can run:
```
python start_websocket_servers.py
python run_websocket_client.py
```

**Comment by HongdaWu1226** [comment]
This works! @NeuZhangQiang 
Thanks for the information
Do you have any idea that why this up to date version doen't have the tutorial on "websockets_mnist_parallel", which is about asynchronous federated learning and have shown in some other branch.

**Comment by NeuZhangQiang** [comment]
@HongdaWu1226 Sorry, I don't know why there is no "websockets_mnist_parallel" tutorial. If you can find one, please tell me.

**Comment by HongdaWu1226** [comment]
> @HongdaWu1226 Sorry, I don't know why there is no "websockets_mnist_parallel" tutorial. If you can find one, please tell me.

If we downgrade the syft version to 0.2.5. It should work if you following the tutorial on "websockets_mnist_parallel". Also, you may still face some minor problems, but it is not a big deal and easy to handle. 
If you have problem on this tutorial, just contact me via e-mail.

**Comment by HongdaWu1226** [comment]
@NeuZhangQiang 
If we downgrade the syft version to 0.2.5. It should work if you following the tutorial on "websockets_mnist_parallel". Also, you may still face some minor problems, but it is not a big deal and easy to handle.
If you have problem on this tutorial, just contact me via e-mail.

**Comment by NeuZhangQiang** [comment]
@HongdaWu1226 Thank you very much for the suggestion.

Currently, I meet a problem. PySyft use data.send(worker) to share the data. But, how can we deal with big data by PySyft? PyTorch use DataLoader, and Keras use generator for dataset lazy loading. Is it possible to share DataLoader or generator?

Any suggestion is appreciated!

**Comment by thormacy** [comment]
The point here is the latest version use a Module 'pythreepio' which is not included in the building process. Somehow I make it work for my task. Since I needs websocket works properly, I downgrade the version.

For reference:
websocket-client 0.54.0
syft             0.2.0a2

Hope they can make the latest working soon!

**Comment by Billy1900** [comment]
# Description & reproduce
I met a similar problem on windows,
when I type in my command, `from syft.frameworks.torch.dp import pate`, the error msg is as follows:
<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\__init__.py", line 14, in <module>
    import syft.frameworks.torch.hook.hook_args
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\hook\hook_args.py", line 4, in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\tensors\interpreters\native.py", line 16, in <module>
    from syft.generic.utils import memorize
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\utils.py", line 1, in <module>
    from syft.generic.frameworks.attributes import allowed_commands
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\attributes.py", line 8, in <module>
    from syft.generic.frameworks.hook.hook import FrameworkHook
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\hook\hook.py", line 11, in <module>
    from syft.generic.frameworks.hook.pointers import PointerHook
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\hook\pointers.py", line 8, in <module>
    from syft.generic.pointers.multi_pointer import MultiPointerTensor
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\pointers\multi_pointer.py", line 11, in <module>
    from syft.workers.base import BaseWorker
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\workers\base.py", line 12, in <module>
    from syft.execution.plan import Plan
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\plan.py", line 21, in <module>
    from syft.execution.translation.threepio import PlanTranslatorTfjs
  File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\translation\threepio.py", line 2, in <module>
    import pythreepio
ModuleNotFoundError: No module named 'pythreepio'
</pre>
How can I solve the problem? 

# System Information
python version: 3.7.6
os: windows 10
torch: 1.4.0 GPU
syft: 0.2.9

**Comment by Billy1900** [comment]
> # Description & reproduce
> I met a similar problem on windows,
> when I type in my command, `from syft.frameworks.torch.dp import pate`, the error msg is as follows:
> 
> Traceback (most recent call last):
>   File "", line 1, in 
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\__init__.py", line 14, in 
>     import syft.frameworks.torch.hook.hook_args
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\hook\hook_args.py", line 4, in 
>     from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\frameworks\torch\tensors\interpreters\native.py", line 16, in 
>     from syft.generic.utils import memorize
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\utils.py", line 1, in 
>     from syft.generic.frameworks.attributes import allowed_commands
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\attributes.py", line 8, in 
>     from syft.generic.frameworks.hook.hook import FrameworkHook
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\hook\hook.py", line 11, in 
>     from syft.generic.frameworks.hook.pointers import PointerHook
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\frameworks\hook\pointers.py", line 8, in 
>     from syft.generic.pointers.multi_pointer import MultiPointerTensor
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\generic\pointers\multi_pointer.py", line 11, in 
>     from syft.workers.base import BaseWorker
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\workers\base.py", line 12, in 
>     from syft.execution.plan import Plan
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\plan.py", line 21, in 
>     from syft.execution.translation.threepio import PlanTranslatorTfjs
>   File "D:\Anaconda\envs\torch\lib\site-packages\syft-0.2.9-py3.7.egg\syft\execution\translation\threepio.py", line 2, in 
>     import pythreepio
> ModuleNotFoundError: No module named 'pythreepio'
> How can I solve the problem?
> 
> # System Information
> python version: 3.7.6
> os: windows 10
> torch: 1.4.0 GPU
> syft: 0.2.9

I solved it by myself. 

1) First, uninstall the original pysyft--`pip uninstall syft`. 

2) And then to use this command `pip install syft -f https://download.pytorch.org/whl/torch_stable.html` from this [link](https://stackoverflow.com/questions/61850455/could-not-find-a-version-that-satisfies-the-requirement-torch-1-4-0-from-syft)

3) maybe you will meet this problem, `ModuleNotFoundError: No module named 'syft.frameworks.torch.differential_privacy'`, please change it into `ModuleNotFoundError: No module named 'syft.frameworks.torch.dp` according to this [link](https://stackoverflow.com/questions/58367187/modulenotfounderror-no-module-named-syft-pysyft)

**Comment by zzy211** [comment]
> 



> @thormacy, we should import syft rather than import PySyft-master/syft.
> 
> There is something wrong with the original example, and we need some modifies.
> 
> Copy the websockets_mnist in your Desktop or other folder (make sure it is not included by PySyft-master)
> 
> And the folder files is:
> 
> ```
> run_websocket_client.py
> run_websocket_server.py
> start_websocket_servers.py
> ```
> 
> the run_websocket_server.py is copied from the PySyft-master/run_websocket_server.py.
> 
> The start_websocket_servers.py should also be modified as following:
> 
> ```
> import subprocess
> import sys
> from pathlib import Path
> 
> python = Path(sys.executable).name
> 
> FILE_PATH = './run_websocket_server.py'
> 
> call_alice = [python, FILE_PATH, "--port", "8777", "--id", "alice"]
> 
> call_bob = [python, FILE_PATH, "--port", "8778", "--id", "bob"]
> 
> call_charlie = [python, FILE_PATH, "--port", "8779", "--id", "charlie"]
> 
> 
> print("Starting server for Alice")
> subprocess.Popen(call_alice)
> 
> print("Starting server for Bob")
> subprocess.Popen(call_bob)
> 
> print("Starting server for Charlie")
> subprocess.Popen(call_charlie)
> ```
> 
> Then, you can run:
> 
> ```
> python start_websocket_servers.py
> python run_websocket_client.py
> ```

hello, I can not find run_websocket_server.py， can you give me?
