### ISSUE TITLE
Colab Installation Instructions

### ISSUE THREAD

**Issue by ayushm-agrawal** [OpenMined/PySyft#3773]
## Where?
I want to add the installation of PySyft on Google Colab. This will go inside the INSTALLATION.md file. 

## Who?
The main audience for this would be anyone who wants to use PySyft on Google Colab.

## What?
This documentation should make it easier for anyone to quickly get PySyft setup on Google Colab and start using the GPU resources accessible there to train private models.

## Additional Context
While I was initially trying to figure out how to get PySyft installed on Google Colab, most of the search results on google link me to an old way of manually cloning PySyft and other steps. We can simply achieve this by the **pip install** command that I came across after searching around. 
I just want to make this accessible in our documentation for clarity. I have a working code on Colab that I can link to these instructions as well.

_Please let me know if you think I can go ahead and add this to our Documentation?_

**Comment by ariannmichael** [comment]
I would like to take up this issue

**Comment by abhi1nandy2** [comment]
> I would like to take up this issue

Could you please  help with colab? It shows an error `AttributeError: type object 'Tensor' has no attribute 'fft'`
