### ISSUE TITLE
add_dataset() function doesn't exist in websocket_server

### ISSUE THREAD

**Issue by wmlba** [OpenMined/PySyft#3796]
## Description
https://github.com/OpenMined/PySyft/blob/275efceca60e4f8b58e5b5c98f18b8bebd15f889/run_websocket_server.py#L87

It seems like the add_dataset() function has been removed from websocket_server file.

## How to Reproduce
run the example involving this: https://github.com/OpenMined/PySyft/blob/master/run_websocket_server.py

## Expected Behavior
Adding a dataset to websocket server to be discoverable.

**Comment by thormacy** [comment]
The new version does not support websocket. It seems that they can not solve it at this moment...
