### ISSUE TITLE
Crypten Init messages refactor

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3808]
## What?
The CryptenInitPlan and CryptenInitJail look very similar. They could be unified, maybe use the same parent class, and derive this.

### Context
Currently, for running CrypTen computation we must specify to the remote workers that we actually want to start the "computation".

For doing this we use messages for notification where we sent the necessary information. Those messages are ```CryptenInitPlan``` or ```CrypTenInitJail``` (depending on what approach we want to follow).

**Attention**
The code is on the ```crypten``` branch.

## Why?
Reduce code complexity and duplicate code removal.

**Comment by punitkoura** [comment]
Hi @gmuraru , I'd like to work on this issue. However, I'm fairly new to the code base. Could you elaborate a bit more about CryptenInitPlan and CryptenInitJail, and maybe point me to some code sections. Thanks a lot!

**Comment by gmuraru** [comment]
Hey @punitkoura. Sure - I updated the description - I think the most important part is that this code is on the ```crypten``` branch.

**Comment by gmuraru** [comment]
@punitkoura are you working on this?

**Comment by punitkoura** [comment]
Hi @gmuraru, yes, I was trying to ramp up on the repo. I'll have a Pull Request soon. Apologies for the delay.
