### ISSUE TITLE
How PySyft deal with big training dataset?

### ISSUE THREAD

**Issue by NeuZhangQiang** [OpenMined/PySyft#3813]
## Question
How can PySyft deal with big data?

## Further Information
Pysyft use data.send(worker) to share data. What if the dataset is very large? For example, the size of dataset is 100g. 
The PyTorch use DataLoader and Keras use yield to load one batch of data in one time. Can PySyft implement the similar function?
The FederatedDataLoader seem to a solution. But how can we convert the DataLoader (PyTorch) to FederatedDataLoader?

And is it possible to use fit_generator in Pysyft? Any suggestion is appreciate!

**Comment by chenwanqq** [comment]
Personally I haven't found such a method. many base class in PySyft, such as federatedclient, baseworker, Basedataset, directly use Tensor rather than dataset/dataloader. Unforunately the major FL framework, such as  Pysyft, Tensorflow-Federated and FATE don't support big data loading, which strongly limited the usage in many areas, such as CV. 
哥们我跟你研究的方向很像，有兴趣可以通过邮件联系wanqi0605@qq.com

**Comment by typhoon1104** [comment]
hello，I have the question too.I use dataLoader and dataset.But I have a new question that can not get model.

**Comment by NeuZhangQiang** [comment]
@typhoon1104 You need to have a look at this [tutorial](https://github.com/OpenMined/PySyft/tree/v0.2.5/examples/tutorials/advanced/websockets_mnist_parallel). Please note that only pysyft 0.2.5 support this tutorial, while the pysyft 0.2.6 do not support. And I do not know why pysyft 0.2.6 remove this function.

**Comment by typhoon1104** [comment]
> @typhoon1104 You need to have a look at this [tutorial](https://github.com/OpenMined/PySyft/tree/v0.2.5/examples/tutorials/advanced/websockets_mnist_parallel). Please note that only pysyft 0.2.5 support this tutorial, while the pysyft 0.2.6 do not support. And I do not know why pysyft 0.2.6 remove this function.

I use dataset and dataloader of pytorch 1.5.0, it not in PySyft.

**Comment by NeuZhangQiang** [comment]
@typhoon1104 you can try pytorch 1.4.0.

**Comment by typhoon1104** [comment]
I find it is not a question.
But I find a new question that model_str.get() is slow.
It takes 60 seconds to get a model of resnet34.
