### ISSUE TITLE
Cannot using the command ".share()" in distributed environment

### ISSUE THREAD

**Issue by chain45660** [OpenMined/PySyft#3819]
## Description
When I send the tensor X from python notebook to bob worker that running by using WebsockerServer instead of the virtual machine in another instance (IP address: A). I also create another instance Alice worker by using WebsocketServer (IP address: B).  I cannot run this command "x.share(Alice, bob)" They said cannot serialize the WebsocketClientWorker.
`
## How to Reproduce

```
from torchvision.models.resnet import ResNet, BasicBlock
import syft as sy
from torchvision.datasets import MNIST
import torch.nn.functional as F
from tqdm.autonotebook import tqdm
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import inspect
import time
from torch import nn, optim
import torch
from torchvision.transforms import Compose, ToTensor, Normalize, Resize
from torch.utils.data import TensorDataset, DataLoader
from torchvision import datasets, transforms
from syft.workers.websocket_client import WebsocketClientWorker                                                                                                                                                                                   hook = sy.TorchHook(torch)
# verbose mode
kwargs_websocket_worker_alice = {"host": "xx.xx.xx.xx", "hook": hook,"verbose":False}
kwargs_websocket_worker_bob = {"host": "x.xx.xxx.xxx", "hook": hook,"verbose":False}
alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket_worker_alice)
bob = WebsocketClientWorker(id="bob", port=8778, **kwargs_websocket_worker_bob)
test = torch.tensor([25]).send(bob)
check = test.share(bob,alice)
```
The error that I got.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-4ac801f8f830> in <module>
      1 test = torch.tensor([25]).send(bob)
----> 2 check = test.share(bob,alice)
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in share(self, protocol, field, dtype, crypto_provider, requires_grad, no_wrap, *owners)
    907                 dtype=dtype,
    908                 crypto_provider=crypto_provider,
--> 909                 **kwargs_,
    910             )
    911         else:
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/pointers/pointer_tensor.py in share(self, *args, **kwargs)
    380             raise RuntimeError("Error, share must have > 1 arguments all of type syft.workers")
    381 
--> 382         response = self.owner.send_command(self.location, "share", self, args, kwargs)
    383         return response
    384 
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py in send_command(self, recipient, cmd_name, target, args_, kwargs_, return_ids, return_value)
    624                 cmd_name, target, args_, kwargs_, return_ids, return_value
    625             )
--> 626             ret_val = self.send_msg(message, location=recipient)
    627         except ResponseSignatureError as e:
    628             ret_val = None
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py in send_msg(self, message, location)
    269 
    270         # Step 1: serialize the message to a binary
--> 271         bin_message = sy.serde.serialize(message, worker=self)
    272 
    273         # Step 2: send the message and wait for a response
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/serde.py in serialize(obj, worker, simplified, force_full_simplification, strategy)
     43         strategy = serialize
     44 
---> 45     return strategy(obj, worker, simplified, force_full_simplification)
     46 
     47 
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/msgpack/serde.py in serialize(obj, worker, simplified, force_full_simplification)
    335 
    336     simple_objects = _serialize_msgpack_simple(obj, worker, simplified, force_full_simplification)
--> 337     return _serialize_msgpack_binary(simple_objects)
    338 
    339 
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/msgpack/serde.py in _serialize_msgpack_binary(simple_objects, worker, simplified, force_full_simplification)
    289     # 2) Serialize
    290     # serialize into a binary
--> 291     binary = msgpack_lib.dumps(simple_objects)
    292 
    293     # 3) Compress
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/msgpack/__init__.py in packb(o, **kwargs)
     33     See :class:`Packer` for options.
     34     """
---> 35     return Packer(**kwargs).pack(o)
     36 
     37 
msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
TypeError: can not serialize 'WebsocketClientWorker' object
```

**Comment by yuucyf** [comment]
> ## Description
> When I send the tensor X from python notebook to bob worker that running by using WebsockerServer instead of the virtual machine in another instance (IP address: A). I also create another instance Alice worker by using WebsocketServer (IP address: B). I cannot run this command "x.share(Alice, bob)" They said cannot serialize the WebsocketClientWorker.
> `
> 
> ## How to Reproduce
> ```
> from torchvision.models.resnet import ResNet, BasicBlock
> import syft as sy
> from torchvision.datasets import MNIST
> import torch.nn.functional as F
> from tqdm.autonotebook import tqdm
> from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
> import inspect
> import time
> from torch import nn, optim
> import torch
> from torchvision.transforms import Compose, ToTensor, Normalize, Resize
> from torch.utils.data import TensorDataset, DataLoader
> from torchvision import datasets, transforms
> from syft.workers.websocket_client import WebsocketClientWorker                                                                                                                                                                                   hook = sy.TorchHook(torch)
> # verbose mode
> kwargs_websocket_worker_alice = {"host": "xx.xx.xx.xx", "hook": hook,"verbose":False}
> kwargs_websocket_worker_bob = {"host": "x.xx.xxx.xxx", "hook": hook,"verbose":False}
> alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket_worker_alice)
> bob = WebsocketClientWorker(id="bob", port=8778, **kwargs_websocket_worker_bob)
> test = torch.tensor([25]).send(bob)
> check = test.share(bob,alice)
> ```
> 
> The error that I got.
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-7-4ac801f8f830> in <module>
>       1 test = torch.tensor([25]).send(bob)
> ----> 2 check = test.share(bob,alice)
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in share(self, protocol, field, dtype, crypto_provider, requires_grad, no_wrap, *owners)
>     907                 dtype=dtype,
>     908                 crypto_provider=crypto_provider,
> --> 909                 **kwargs_,
>     910             )
>     911         else:
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/pointers/pointer_tensor.py in share(self, *args, **kwargs)
>     380             raise RuntimeError("Error, share must have > 1 arguments all of type syft.workers")
>     381 
> --> 382         response = self.owner.send_command(self.location, "share", self, args, kwargs)
>     383         return response
>     384 
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py in send_command(self, recipient, cmd_name, target, args_, kwargs_, return_ids, return_value)
>     624                 cmd_name, target, args_, kwargs_, return_ids, return_value
>     625             )
> --> 626             ret_val = self.send_msg(message, location=recipient)
>     627         except ResponseSignatureError as e:
>     628             ret_val = None
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py in send_msg(self, message, location)
>     269 
>     270         # Step 1: serialize the message to a binary
> --> 271         bin_message = sy.serde.serialize(message, worker=self)
>     272 
>     273         # Step 2: send the message and wait for a response
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/serde.py in serialize(obj, worker, simplified, force_full_simplification, strategy)
>      43         strategy = serialize
>      44 
> ---> 45     return strategy(obj, worker, simplified, force_full_simplification)
>      46 
>      47 
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/msgpack/serde.py in serialize(obj, worker, simplified, force_full_simplification)
>     335 
>     336     simple_objects = _serialize_msgpack_simple(obj, worker, simplified, force_full_simplification)
> --> 337     return _serialize_msgpack_binary(simple_objects)
>     338 
>     339 
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/serde/msgpack/serde.py in _serialize_msgpack_binary(simple_objects, worker, simplified, force_full_simplification)
>     289     # 2) Serialize
>     290     # serialize into a binary
> --> 291     binary = msgpack_lib.dumps(simple_objects)
>     292 
>     293     # 3) Compress
> ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/msgpack/__init__.py in packb(o, **kwargs)
>      33     See :class:`Packer` for options.
>      34     """
> ---> 35     return Packer(**kwargs).pack(o)
>      36 
>      37 
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()
> TypeError: can not serialize 'WebsocketClientWorker' object
> ```

I had the same problem. Did you solve it?
