### ISSUE TITLE
Import Whitelist From threepio

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3829]
## Description
We want to import the API functionality from threepio to generate torch, tensorflow, and other framework support. Workers shoudl automatically import everything 3po has to offer, and thus (in theory) all framework specific code can be limited to 3p0 except custom chain functionality.

## Are you interested in working on this improvement yourself?
Possibly - happy for someone to pick this up as well?

**Comment by ramesht007** [comment]
Hey, @iamtrask I have contributed to threepio and I want to work on this issue.
