### ISSUE TITLE
Pysyft Asynchronous Problem

### ISSUE THREAD

**Issue by NeuZhangQiang** [OpenMined/PySyft#3831]
Asynchronous training is an important function for federated learning, and I have several question:

1. In Pysyft 0.2.5, there is a tutorial "websockets_mnist_parallel", which implement the asynchronous training. However, it is removed in pysyft 0.2.6. Is there any other implements for asynchronous?

2. For "websockets_mnist_parallel", I find the communication between client and server ```train_config.model_ptr.get().obj``` cost much time which is longer than model fitting. Is there any solution to reduce the communication time?

3. Can Pysyft provide a tutorial of asynchronous training for Keras and Tensorflow? I can not find how to implement it.

**Comment by MetaT1an** [comment]
@NeuZhangQiang Hi, see you again here. >_<

I noticed that in [this tutorial](https://nbviewer.jupyter.org/github/OpenMined/PySyft/blob/master/examples/tutorials/Part%2006%20-%20Federated%20Learning%20on%20MNIST%20using%20a%20CNN.ipynb), the clients seem to not work in parallel.  Instead, the client updates the global model one after another.  Well, the training process is sort of different from the description in the original paper.  Despite the effectivenees of that model training process in PySyft, it acts in a weird way deviating from the reald world scenario/ correct FL paradigm.

By the way, I deeply agree with your requirement for asynchronous training.  Because It will make the trainning process more closer to the reality.

**Comment by NeuZhangQiang** [comment]
@MetaT1an You may want this [tutorial](https://github.com/OpenMined/PySyft/tree/v0.2.5/examples/tutorials/advanced/websockets_mnist_parallel), in which the clients work in parallel.

**Comment by MetaT1an** [comment]
@NeuZhangQiang Yeah, it is the exact the missing part in PySyft 0.2.6

**Comment by fermat97** [comment]
Hi guys @NeuZhangQiang @MetaT1an I am using async federated training with `TrainConfig` , my understanding is once the model and config file are sent to the remote machine there shouldn't be any other communication in between. But it seems even during the training on the remote machines (clients), there are still huge amount of communication between the server and each of the clients. Isn't it? Could you understand what are those communications for?

**Comment by NeuZhangQiang** [comment]
@fermat97 I am not sure what do you mean by "there are still huge amount of communication between ...". How do you know that there is still communication? Actually, after sent the model and config file to remote machine, the models would also be send from the remote machines to server, which would be used to calculate a average model.

**Comment by usamazf** [comment]
Does any one know why the module was removed in the first place? And if any alternative was provided?

**Comment by NeuZhangQiang** [comment]
@usamazf No idea why it is removed. The only solution is to install pysyft 0.2.5 so that we can use this module.

**Comment by usamazf** [comment]
Using pysyft 0.2.5 is probably the only solution for now. Super weird though to remove the only thing that actually simulated a real federated environment.

**Comment by NeuZhangQiang** [comment]
Hope pysyft provides an alternative solution.

**Comment by fermat97** [comment]
> @fermat97 I am not sure what do you mean by "there are still huge amount of communication between ...". How do you know that there is still communication? Actually, after sent the model and config file to remote machine, the models would also be send from the remote machines to server, which would be used to calculate a average model.

Thank you. Yes I know they have to send back the model to the server, but during the training on the remote machines there shouldn't be any communication between server and remote workers. I am using some networking tools and it shows there still are. In other words it shows server container starts receiving data while the client containers are still receiving packages from server.
