### ISSUE TITLE
Federated learning with plenty of clients?

### ISSUE THREAD

**Issue by MetaT1an** [OpenMined/PySyft#3832]
Is **PySyft** suitable for large-scaled federated learning scenario where hundreds or thounds of clients are participated?  

In the tutorial document, I only see clients such as *Alice* and *Bob*, which seems to be far away form the actual cross-device learning tasks.

Many thanks.

**Comment by NeuZhangQiang** [comment]
@MetaT1an Yes, PySyft can be used for large-scaled federated learning scenario. There is a [tutorial ](https://github.com/OpenMined/PySyft/tree/v0.2.5/examples/tutorials/advanced/websockets_mnist_parallel)that is helpful for your question. However, for some unclear reason, the pysyft 0.2.6 do not support the above tutorial. 

In addition, I can not find the similar tutorial for keras or tensorflow.

**Comment by MetaT1an** [comment]
@NeuZhangQiang Thanks for your kind reply.  Suppose I need 100 clients for a certain experiment, is it a good idea to create these clients with consecutive numbers(1~100) being their **id** property , and to put them into a list for future training?

**Comment by NeuZhangQiang** [comment]
Yes, you can. You only need to make sure the id is unique.
