### ISSUE TITLE
Capsule Snuck into PySyft Notebooks

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#384]
Several of the PySyft notebooks are now broken because they rely on a completely separate repository (Which has changed). We need to strip out reliance on Capsule in the following notebooks.

- https://github.com/OpenMined/PySyft/blob/master/notebooks/Syft%20-%20Paillier%20Homographic%20Encrypted%20Linear%20Classification%20example%20.ipynb
- https://github.com/OpenMined/PySyft/blob/master/notebooks/Syft%20-%20Paillier%20Encrypted%20Linear%20Classification.ipynb

Acceptance Criteria:
- Remove Capsule dependencies from these notebooks and get them working
- Move these notebooks to Capsule/notebooks folder and get them working

**Comment by sriranganathan** [comment]
@iamtrask, I'd like to take this up.

**Comment by iamtrask** [comment]
Excellent @sriranganathan that's great news!

**Comment by iamtrask** [comment]
@raul-jr3 wants to as well - perhaps you guys can each pick one of those notebooks to work with?

**Comment by taylorperkins** [comment]
@sriranganathan @raul-jr3 has there been any progress regarding this ticket? Is there any help that is still needed?

**Comment by raul-jr3** [comment]
any help is very much appreciated :)

**Comment by taylorperkins** [comment]
@raul-jr3 awesome!! Working through getting the dependencies installed now. Is there a particular branch you are working off of? If not, I can create one here locally.

**Comment by raul-jr3** [comment]
@taylorperkins nope!
