### ISSUE TITLE
Cannot move PointerTensors to GPU

### ISSUE THREAD

**Issue by ibayramli2001** [OpenMined/PySyft#3848]
So, while trying to retrieve a model on GPU using .get(), I came across the following error:

`RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_set_`

Here is the traceback:

```
~/splitnn/src/utils/trainer.py in split_train(client_ids, data_paths, server_model, client_model, hook, optim, optim_params, criterion, dataloader_fn, dataloader_params, save_path, num_epochs, verbose, cuda)
    262                            dataloaders=dataloaders, criterion=criterion, num_epochs=num_epochs,
    263                            save_path=save_path, verbose=verbose, device=device)
--> 264     stats = trainer.train()
    265 
    266     return stats

~/splitnn/src/utils/trainer.py in train(self, train_clts, val_clts)
     68                 print('\nTraining client {}, epoch {}\n'.format(client_id, epoch + 1))
     69 
---> 70                 train_metrics = self._run_epoch('train', client_id)
     71                 self._log('train', 'loss', client_id, epoch + 1, train_metrics['loss'])
     72                 if self.verbose > 0:

~/splitnn/src/utils/trainer.py in _run_epoch(self, mode, client_id)
    113             else:
    114                 pred, loss = self._validate_iter(image, label, client_id)
--> 115             client = self.network.clients[client_id].get()
    116             print("PASSED!!!!!!!!!!!!!!")
    117             running_loss += loss

~/splitnn/venv/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py in module_get_(nn_self)
    669             for element_iter in tensor_iterator(nn_self):
    670                 for p in element_iter():
--> 671                     p.get_()
    672 
    673             if isinstance(nn_self.forward, Plan):

~/splitnn/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in get_(self, *args, **kwargs)
    670         Calls get() with inplace option set to True
    671         """
--> 672         return self.get(*args, inplace=True, **kwargs)
    673 
    674     def allow(self, user=None) -> bool:

~/splitnn/venv/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in get(self, inplace, user, reason, *args, **kwargs)
    657 
    658         if inplace:
--> 659             self.set_(tensor)
    660             if hasattr(tensor, "child"):
    661                 self.child = tensor.child

RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_set_
```

I manually checked that all the parameters of the model and the input images are in fact located on GPU.  After investigating the `~/splitnn/venv/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py` line 671 with a lot of print statements, I found that when the model goes into the for loop:
```
~/splitnn/venv/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook.py in module_get_(nn_self)
    669             for element_iter in tensor_iterator(nn_self):
    670                 for p in element_iter():
--> 671                     p.get_()
    672 
```

one of the `p`  values is a PointerTensor located on the CPU with `tensor.Size([ ])` whereas the previous (non-erroring) `p`s are located on GPU with regular tensor sizes (e.g. `tensor.Size([64, 3, 3, 3])`). I tried to move the PointerTensors to GPU, using `.to()` and `.cuda()` methods, but those failed to change the pointer's device. The issue got finally resolved when I wrote:

`torch.set_default_tensor_type(torch.cuda.FloatTensor)`

I don't fully understand why this is happening, but I feel it may be related to [this issue](https://github.com/OpenMined/PySyft/issues/2518). It would also be greatly useful for debugging purposes if it were possible to move PointerTensors from one device to another.

**Comment by skywind29** [comment]
Hi @ibayramli2001, recently I ran into the same issue while training a ResNet18 model with PySyft on GPU.

After some investigation, I found the error was caused by `torch.nn.BatchNorm2d`, which would generate `num_batches_tracked` tensors in Buffers and push them to CPU while `forward()`.

A quick solution is to set `track_running_stats=False` when using `torch.nn.BatchNorm2d`. However, this results in batchnorm2d using batch statistics instead of running estimates while training ([[1](https://pytorch.org/docs/master/generated/torch.nn.BatchNorm2d.html)], [[2](https://discuss.pytorch.org/t/what-num-batches-tracked-in-the-new-bn-is-for/27097)]).

Definitely not the best solution we could have, but still hope this helps.
