### ISSUE TITLE
Make sure all tests on AST are performed with all crypto protocols

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3883]
## Description
We want to make sure all tests on AdditiveSharingTensors are performed not only on secureNN but also on FSS crypto protocol and future ones like FALCON

## Infos
Blocked by #3882 
Open to contributions!

**Comment by ramesht007** [comment]
Hey, @LaRiffle can I work on this issue

**Comment by LaRiffle** [comment]
Hey sure yes!
But some elements are required before addressing this issue: I need to merge stuff related to function secret sharing to have it behave in the exact same way than secureNN.
I will let you know when this issue is unblocked!

**Comment by ramesht007** [comment]
ok sure 😀

**Comment by LaRiffle** [comment]
Hey @ramesht007 !
It's ready to go! :)

**Comment by ramesht007** [comment]
ok 👍

**Comment by gmuraru** [comment]
@ramesht007 are you still working on this? :D

**Comment by ramesht007** [comment]
Hey, @gmuraru yup I'm still working on this, but will not be able to give any update as I have my exams till 10th September. After that I will start working on it with full force.🙂

**Comment by aanurraj** [comment]
work is done! thanks, @ramesht007 closing the issue
