### ISSUE TITLE
model.send fails in websocket workers

### ISSUE THREAD

**Issue by usamazf** [OpenMined/PySyft#3885]
## Description
I am implementing web-socket workers for my training, but when I try to send the model to respective workers for training I get:

AttributeError: 'AutogradTensor' object has no attribute 'send_'

## How to Reproduce
1. Install latest version of pysyft
2. Create asynchronous routines for worker / server modules
3. Create a torch neural network
4. Send the model to the worker.

## Expected Behavior
To be able to send the model to the websocket workers.

## System Information
 - OS: Ubuntu
 - OS Version:  16.04
 - Language Version: Python 3.7

## Additional Context
The error trace of the issue is as follows:
```
future: <Task finished coro=<training_handler() done, defined at start_federated_server.py:98> exception=AttributeError("'AutogradTensor' object has no attribute 'send_'")>
Traceback (most recent call last):
  File "start_federated_server.py", line 130, in training_handler
    for worker in sampled_workers
  File "start_federated_server.py", line 82, in fit_model_on_worker
    model_params.send(worker)
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook.py", line 629, in module_send_
    p.send_(*dest, **kwargs)
  File "/home/usama/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/autograd.py", line 171, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'AutogradTensor' object has no attribute 'send_'
```

**Comment by Zongshun96** [comment]
I have a related question about get() method actually. 
Can anyone point me out where it is implemented? I didn't see it in torch.tensor and sequential module but it seems their instances do have this method. 
And it seems to be the similar question here. The AutogradTensor class don't have this method. So why there is the difference and how to debug this issue?

Thanks,
