### ISSUE TITLE
Cannot move traced model to cuda

### ISSUE THREAD

**Issue by NProkoptsev** [OpenMined/PySyft#3887]
## Description
After initializing TorchHook and tracing model you can't move this model to another device (cuda or cpu). This happens because  method `parameters()` of a traced model returns list of torch.Tensor instead of list of nn.Parameter, so we can't move tensors to another device because they don't have setter for .data property
https://github.com/OpenMined/PySyft/blob/5c8e7b78eba693ea29e07eac7476aa7517e5dfef/syft/frameworks/torch/tensors/interpreters/native.py#L141

```
import torch
import syft as sy
hook = sy.TorchHook(torch)
model = torch.nn.Linear(1,1)
model = torch.jit.trace(model,torch.rand(1,1))
model.cpu()
```
This code produces error `AttributeError: can't set attribute`
The traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-54d42a2d39a0> in <module>
----> 1 model.cpu()

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in cpu(self)
    310             Module: self
    311         """
--> 312         return self._apply(lambda t: t.cpu())
    313 
    314     def type(self, dst_type):

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    224                 should_use_set_data = compute_should_use_set_data(param, param_applied)
    225                 if should_use_set_data:
--> 226                     param.data = param_applied
    227                 else:
    228                     assert isinstance(param, Parameter)

AttributeError: can't set attribute
```

## System Information
 - PySyft 0.2.7
 - Torch 1.4.0

**Comment by fermat97** [comment]
@NProkoptsev is there any workaround for this problem?

**Comment by NProkoptsev** [comment]
Save model to disk, then
torch.jit.load(f, map_location='cuda')

**Comment by fermat97** [comment]
@NProkoptsev thanks, I do so. But it seems saving and loading would break the object pointer so once you use the `get` command to retrieve your model from one of the workers it retrieves the old one (the same model before saving and not the updated one).
```Python
torch.jit.save(model,'model.pt')
model = torch.jit.load('model.pt',map_location='cpu')
```

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
