### ISSUE TITLE
Not able to access variable on remote worker!

### ISSUE THREAD

**Issue by aliraza0337** [OpenMined/PySyft#3888]
## Question
**Not able to access variable on remote worker! that I have already sent over the network using the send method.**

## Further Information

I created a model of the type of **torch.nn.Sequential(..)** and send it to my remote worker (running on localhost and different port number) using the following call, 
**_model.send(remote_worker_id)_**
After the first batch of training, I want to access the weights of my model on the remote worker.
So far I have tried _search_ which doesn't seem to be working. 
I have tried to use the method _list_object_remote()_ which only returns a string and I am not able to obtain the necessary information. 
I was wondering what is the correct way to access variables on the remote worker and also in case I want to update any. 

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Ubuntu 
 - OS Version: 18
 - Language Version: Python 3.69
 - Package Manager Version: PySft version 0.2.6, Torch 1.4.0

**Comment by LaRiffle** [comment]
Hey!
You can simply call `model.get()` if you want to get a local version of your model that's probably the best option.
Alternatively you can spot a parameter like `model.weight` if `model = nn.Linear(...)`, this should be a Pointer. You can then call `.copy().get()` on it to get a version back without deleting the remote version of the parameter (contrary to the .get() on the model)

**Comment by aliraza0337** [comment]
Hi Thanks for the reply, I tried that and it seems to be working but it's painfully slow to get a variable back from remote worker. Any suggestions for that?
