### ISSUE TITLE
split_neural_network tutorial fails at move() method when work with Websocket Workers

### ISSUE THREAD

**Issue by Zongshun96** [OpenMined/PySyft#3897]
## Description
After I changed VirtualWorkers to pairs of WebSocketServerWorker and WebSocketClientWorker. The move method stop working. 
The notebook prints "RuntimeError: Websocket connection closed and creation of new connection failed."
The WebSocketServerWorker prints "Worker alice1 couldn't recognize worker alice2" and raise an error saying "AttributeError: 'str' object has no attribute '_recv_msg'"

## How to Reproduce
1. Go to [Tutorial 1 - SplitNN Introduction.ipynb](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/split_neural_network/Tutorial%201%20-%20SplitNN%20Introduction.ipynb)
2. Modify the VirtualWorkers to WebSocket Workers and those related variables (Bob, Alice => Alice1, Alice2 in screenshot)
3. Make sure the WebSocketServerWorkers are running.
4. Click "Kernel" => "Restart & Run All"
5. See error

## Expected Behavior
Move() method can move objects from one WebSocketServerWorker to another.

## Screenshots
![Screen Shot 2020-07-25 at 5 31 30 PM](https://user-images.githubusercontent.com/34226180/88466687-e62ab500-ce9c-11ea-883c-37b4b9567c2e.png)
![Screen Shot 2020-07-25 at 5 32 14 PM](https://user-images.githubusercontent.com/34226180/88466688-ea56d280-ce9c-11ea-8718-d37d06564167.png)
![Screen Shot 2020-07-25 at 5 31 59 PM](https://user-images.githubusercontent.com/34226180/88466689-ecb92c80-ce9c-11ea-9ed9-72c57c6f3d9a.png)
![Screen Shot 2020-07-25 at 5 12 12 PM](https://user-images.githubusercontent.com/34226180/88466411-fd1bd800-ce99-11ea-8091-17af4ef577d3.png)

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.6.9; Syft 0.2.6
 - Package Manager Version: pip 20.1.1
 - Browser (if applicable): Safari
 - Browser Version (if applicable): Version 13.1.1 (15609.2.9.1.2)

Thank you for your help!

**Comment by sug4ndh** [comment]
This bug is still present unfortunately.

**Comment by abh15** [comment]
Is there any other way to bypass the problem by using some alternative method than **move()**

**Comment by Zongshun96** [comment]
Hi,
    Just in case for anyone in the same situation, this is fixed with PyGrid workers.(not supporting PySyft-0.3.0 for now)
    You can check [this slack posting](https://openmined.slack.com/archives/C6EEFN3A8/p1596720041221900?thread_ts=1596661549.217900&cid=C6EEFN3A8) for an example to setup PyGrid workers and then move() should work.

Thanks,
