### ISSUE TITLE
Syft Error detected in PySonar tutorial: "Sonar - Decentralized Model Training Simulation (local)"

### ISSUE THREAD

**Issue by borkjt9** [OpenMined/PySyft#390]
I am receiving a Decryption Overflow error in Step 3 -> Ln 14 of the tutorial. Even though it's a PySonar tutorial, this is a Syft error. I am having trouble understanding the cause of the error. See below for snapshot.

![image](https://user-images.githubusercontent.com/13172478/32207885-5a6b7c64-bdd5-11e7-95c7-ec16c24afedc.png)

**Comment by borkjt9** [comment]
I believe I have pinpointed the issue. Multiplying a Paillier Encrypted array with original elements less than 1, by a scalar less than one, produces the same error. I have reproduced the error by running the following code:

`pubkey,prikey = KeyPair().generate(n_length=1024)
x = PaillierTensor(pubkey, np.array([ 0.43188777,
        0.93408112,
        0.72565632,
        0.92994132,
        0.63109912,
        0.68034936,
        0.53725333,
        0.89133874,
        0.89126486,
        0.31854688]))
(x*0.1).decrypt(prikey)`

**Comment by replomancer** [comment]
I reproduced the bug on my machine. Can I take this issue?

**Comment by replomancer** [comment]
Commenting out this line:
https://github.com/OpenMined/PySyft/blob/489c3f31d0d1a68ad79632d663acd55e9b9f0136/syft/he/paillier/keys.py#L228
makes the problem go away. This issue is the same as #393.

**Comment by bharathgs** [comment]
this was resolved with #394 (for the time being, but we should work a bit more on this)
