### ISSUE TITLE
I tried to run CIFAR10 federated learning, it works fine with the code in the repo, but when I use resnet it breaks down

### ISSUE THREAD

**Issue by harshita1804** [OpenMined/PySyft#3903]
Model of resnet used -> https://github.com/kuangliu/pytorch-cifar
This resnet works fine in a non-federated scenario, but when i try to do federated learning it gives an error saying: 
RuntimeError: shape '[0, -1]' is invalid for input of size 65536

The stack trace: 

![image](https://user-images.githubusercontent.com/42465912/88559648-eed8d380-cfe1-11ea-913a-45669c7b1244.jpeg)

**Comment by fanyaorong** [comment]
out = out.view(out.size(0), -1)  
That is wrong in pysyft.  Cause the out.size() return a 0 . 
You need to change it like this :
        out=out.view(-1, 512 ) ###!!!!!!!!

**Comment by harshita1804** [comment]
correct, but I did try out=out.view(-1, 512 )  and I got huge negative losses which is why I went back to the default in the resnet code... not sure what's happening
