### ISSUE TITLE
#Plan :  That is wrong to use 'model(data)' in plan

### ISSUE THREAD

**Issue by fanyaorong** [OpenMined/PySyft#3908]
## Description
That is wrong to use 'model(data)' in plan.

## How to Reproduce
my demo like this:

import torch
import torch.nn as nn
from torch import optim
from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets
from tqdm import tqdm
import time
import syft as sy  # import the Pysyft library
hook = sy.TorchHook(torch)  # hook PyTorch ie add extra functionalities 
hook.local_worker.is_client_worker = False
server = hook.local_worker
x11 = torch.tensor([-1, 2.]).tag('input_data')

@sy.func2plan()
def plan_model(x, model):
    x = model(x)
    return x

model = nn.Linear(2, 1)
build_model = plan_model.build(x11, model)

## Expected Behavior
It should be a (1,2) tensor

## Screenshots
But it gets wrong:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-98-222ad6d0c80f> in <module>
----> 1 bd_model = plan_model.build(x11,model)

c:\users\fyrong\appdata\local\programs\python\python37\lib\site-packages\syft\execution\plan.py in build(self, trace_autograd, *args)
    267                 framework_kwargs[f_name] = wrap_framework_func(self.role)
    268 
--> 269         results = self.forward(*args, **framework_kwargs)
    270 
    271         # Register inputs in role

<ipython-input-96-42593bc52555> in plan_model(x, model)
      1 @sy.func2plan()
      2 def plan_model(x, model):
----> 3     x = model(x)
      4     return x
      5 

TypeError: 'PlaceHolder' object is not callable

## Additional Context
Does it can't be use model(data)?
if so, how I use this plan to train a model? 
Thanks a lot for your work!!!

**Comment by gmuraru** [comment]
Hey @fanyaorong. What was the issue here? :D
