### ISSUE TITLE
Paillier tensor multiplication throws an overflow error later during decryption

### ISSUE THREAD

**Issue by siarez** [OpenMined/PySyft#393]
#### Description:
Paillier tensor multiplication throws an overflow error later during decryption. This happens when both numbers that have been multiplied have fractions.

#### Steps/Code to Reproduce: 

Example:
```
b = PaillierTensor(pk, np.array([10]))
boo = (b*1).decrypt(sk)  #works

b = PaillierTensor(pk, np.array([10]))
boo = (b*1.1).decrypt(sk)  #works

b = PaillierTensor(pk, np.array([10.1]))
boo = (b*1).decrypt(sk)  #works

b = PaillierTensor(pk, np.array([10.1]))
boo = (b*1.1).decrypt(sk)  #overflow
```

#### Other details:
This happen because of a bug in the fixed-point multiplication method `my__mul__` in `he/paillier/keys.py`

**Comment by replomancer** [comment]
I believe #390 is because of the same reason (?).
