### ISSUE TITLE
Replicated Sharing Tensor (RST): Add support for FixedPrecisionTensor chain 

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#3931]
Replicated Sharing Tensor currently can work if the plain text type is float or int, we want it to be able to work given a FixedPrecisionTensor as plain text.
When this issue is solved this test case should work properly:
```
a = a.fix_perc().share(bob, alice, james, protocol = "falcon")
b = a.reconstruct().float_perc()
assert (a==b).all()
```
also, it should be tested on arithmetic operation (addition, multiplication, and matrix multiplication)

**Comment by aanurraj** [comment]
I'll like to work on this

**Comment by gmuraru** [comment]
GREAT! :D

**Comment by abogaziah** [comment]
@aanurraj  that's not going to be easy :D let me share my progress in this issue so far:
a.fix_perc().share(bob, alice, james, protocol = "falcon")
this line calls the share function of the native tensor instead of the FPT, they both have a "share" method, you want to call the one that belongs to FPT, so you'll probably want to edit the share function of the native tensor to do that, once you do that you'll be able to build the chain and unbuild it
to be able to do arithmetic, that's the hard part, you will want to edit the arithmetic functions of the FPT class (add/sub) we don't support decision yet so you won't be able to support multiplication or division
FPT class is messy and tightly coupled so making it more tightly coupled is a nightmare, so you should leave the class cleaner than you found it
good luck! ✊

**Comment by aanurraj** [comment]
> @aanurraj that's not going to be easy :D let me share my progress in this issue so far:
> a.fix_perc().share(bob, alice, james, protocol = "falcon")
> this line calls the share function of the native tensor instead of the FPT, they both have a "share" method, you want to call the one that belongs to FPT, so you'll probably want to edit the share function of the native tensor to do that, once you do that you'll be able to build the chain and unbuild it
> to be able to do arithmetic, that's the hard part, you will want to edit the arithmetic functions of the FPT class (add/sub) we don't support decision yet so you won't be able to support multiplication or division
> FPT class is messy and tightly coupled so making it more tightly coupled is a nightmare, so you should leave the class cleaner than you found it
> good luck! ✊

Thanks, I literally got a headache in trying to figure out, where to start from :P, Also, will ping you on slack if I have any issues.
