### ISSUE TITLE
Moving cryptography related packages to Capsule project

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/PySyft#395]
#### User story: 

Currently, some classes in Capsule depend on PySyft. However, functionality of these packages (syft.he and syft.mpc) in PySyft are meant to be in Capsule, as it is the component responsible for encryption.

That's why these two packages (and others if there are any) should be moved to Capsule project and removed from PySyft.

#### Acceptance Criteria: 

- [ Move packages syft.he and syft.mpc to Capsule ]

- [ Add Capsule dependency to PySyft's Docker image]

**Comment by iamtrask** [comment]
Hey Emre! Hit me up on slack before hopping in! Got some news.
