### ISSUE TITLE
Fixed precision tensor: linear operations with torch tensor are broken

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#3950]
fixed precision tensor is supposed to work correctly given an int or float to be subtracted from or added to, just like a torch tensor.
for example:
torch.tensor(5) + 5 = tensor(10)
torch.tensor(5) - 5 = tensor(0)
this should be the correct behavior of FPT:
(torch.tensor(5).fix_prec() - torch.tensor(5)).float_prec() = tensor(0)
(torch.tensor(5) + torch.tensor(5).fix_prec()).float_prec() = tensor(10)
but instead we get:
(torch.tensor(5).fix_prec() - torch.tensor(5)).float_prec() = PureFrameworkTensorFoundError
(torch.tensor(5) + torch.tensor(5).fix_prec()).float_prec() = tensor(5.0050)

multiplication also is broken. 
any fix should be tested against all arithmetic operations (add, sub, mul, div, ..etc)

**Comment by IanQS** [comment]
I'd like to take on this ticket but I'm not sure how quickly I'll be able to finish it so if someone else wants to take it on too then go for it

**Comment by IanQS** [comment]
I'd like to take this on :)

**Comment by gmuraru** [comment]
@IanQS how it goes with this issue. Did you start work on it?

**Comment by IanQS** [comment]
Heya @gmuraru ! 

I've started working on it but I'm running into roadblocks. I've solved the 

`torch.tensor(5) + torch.tensor(5).fix_prec()).float_prec() = tensor(5.0050)` but admittedly my solution isn't pretty and I've not run tests to make sure that my changes don't break anything. 

I'm not too sure about how to solve the first issue (`PureFrameworkTensorFoundError`) I'd love some guidance if you've got any insight into it

**Comment by IanQS** [comment]
@gmuraru 

I've linked my PR to this. Let me know if you think I'm going down the wrong path. I'd love to get feedback as I go along. I'm still trying to figure out how to address the `PureFrameworkTensorFoundError`

**Comment by abogaziah** [comment]
@IanQS you'd wanna look at the operations of the native tensor, since torch.Tensor+FPT calls the __add__ method of the native tensor (torch.Tensor)

**Comment by IanQS** [comment]
Got it! I'll look into `syft.frameworks.torch.tensor.interpreters.Tensor` specifically the `add`! I'll get to it this weekend and will try my best to have something up by Monday.

**Comment by IanQS** [comment]
Hey @abogaziah  @gmuraru 

I think it might be better for me to unassign myself. I'm really not sure how to fix the issue or where to put the fixes so it might be better for someone else to try and take it on. I'll close out the PR but leave a reference to it

**Comment by duggalsu** [comment]
Hi @abogaziah I would like to attempt this if still available

**Comment by abogaziah** [comment]
@duggalsu sure, go-ahead

**Comment by xutongye** [comment]
I would like to fix this if still available

**Comment by duggalsu** [comment]
Hi @xutongye , I've started to work on this now. Will need a few days. I'll let you know if I cannot finish it.

**Comment by gmuraru** [comment]
@LaRiffle I know we discussed yesterday regarding this behavior.

We throw an exception if:
- float_tensor (+|-|*|/) fix_prec_tensor
- fix_prec_tensor (+|-|*|/) float_tensor
