### ISSUE TITLE
FALCON: Private Compare

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#3967]
## Feature Description
This function evaluates the bit x > r where r is public and
the parties hold shares of bits of x in Zp. Algorithm 1 shows
the implementation of the private compare function

![image](https://user-images.githubusercontent.com/33666625/89720197-f7f97580-d9cf-11ea-8379-a5c49787a283.png)

## Additional Context
Private compare is described in section 3.3 in [FALCON paper](https://arxiv.org/pdf/2004.02229v1.pdf)

**Comment by gmuraru** [comment]
@omershlo talked with Sameer Wagh and the if-else from step 7 should be switched

**Comment by omershlo** [comment]
note that a new version of the Falcon is available as they promised. 
Besides line 7 there are few other changes to the protocol (which is now at subsection 3.2)
<img width="644" alt="Screen Shot 2020-09-14 at 15 34 21" src="https://user-images.githubusercontent.com/2446179/93086599-08bc9b80-f6a0-11ea-9a64-c3375789d34b.png">

https://arxiv.org/pdf/2004.02229.pdf
