### ISSUE TITLE
Do we use multiprocessing correctly?

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3992]
## Description
It was suggested by @gmuraru to use `.join()` instead as referenced in https://stackoverflow.com/questions/38271547/when-should-we-call-multiprocessing-pool-join
at various places including https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/mpc/fss.py#L170

Insights welcome on what leads to the fastest / fastest implem =)

**Comment by aanurraj** [comment]
I went through multiple articles suggesting that we should use .close() first followed by .join()
the official Python documentation stats the following:
![Screenshot 2020-09-07 at 9 01 03 PM](https://user-images.githubusercontent.com/28955148/92402480-4031c200-f14d-11ea-89fa-c3fa0312e606.png)
though at many places including the official examples have not used .close().

![Screenshot 2020-09-07 at 9 02 50 PM](https://user-images.githubusercontent.com/28955148/92402631-7f601300-f14d-11ea-9284-fb9dce4b12af.png)

so here I am in the dilemma of replacing it or not. :)
