### ISSUE TITLE
AttributeError: 'WebsocketServerWorker' object has no attribute 'add_dataset'

### ISSUE THREAD

**Issue by Nazila-H** [OpenMined/PySyft#3994]
Hi everyone,
I am trying to connect 4 virtual machines (3 as clients and one as server) as federated learning with websocket.
I installed python3.7 and pysyft on a virtual environment as following:

conda create -n <env_name> python=3.7
conda activate <env_name>
sudo apt install gcc
pip install syft[udacity]

and I got this error from client side:

``` AttributeError: 'WebsocketServerWorker' object has no attribute 'add_dataset' ```

in addition, I did exactly previous steps for python3.6 and I got the following:

``` AttributeError: module 'asyncio' has no attribute 'run' ```

I am new in this subject, could you please give me a hint?

**Comment by PalmLand** [comment]
Hi, I have the same problem, have you solved it?

**Comment by dymat** [comment]
Same here:


```
import pandas as pd
import numpy as np
import torch
import syft as sy

[...]

if __name__ == "__main__":
    
    # init PySyft
    hook = sy.TorchHook(torch)
        
    # load data
    data = pd.read_csv("worker-train.csv")

    # split data into sequences by using sliding window technique
    X, y = get_train_data_and_labels(data)
    
    # create syft dataset 
    dataset = sy.BaseDataset(data=X, targets=y)
    
    # setup server
    websocket_server = sy.WebsocketServerWorker(hook=hook, id="worker-0", host="0.0.0.0", port="9999")
    websocket_server.add_dataset(dataset)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-80-c62cd3dd5cb7> in <module>
     18     # setup server
     19     websocket_server = WebsocketServerWorker(hook=hook, id="worker-0", host="0.0.0.0", port="9999")
---> 20     websocket_server.add_dataset(dataset)
     21 
     22 

AttributeError: 'WebsocketServerWorker' object has no attribute 'add_dataset'
```

**Comment by dymat** [comment]
I tested PySyft versions 0.2.2 to 0.2.6 with the code above. Up to version 0.2.5 the `add_dataset()` method is working. In 0.2.6 it is broken.

Best regards!
d

ps: thanks for this great library

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
