### ISSUE TITLE
Benchmark tanh function methods

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3999]
## What?
Benchmark the ```tanh``` function from the ```FPT``` (Fixed Precision Tensor) using the implemented approximations (```sigmoid``` and ```chebyshev```)

The final output should be a graph or graphs (png images) where:
* X-axis - the used precision
* Y-axis - the time to compute the approximation

We can have multiple lines, each one representing an approximation method.

Some more possibilities:
* Y-axis (or Y2-Axis) - delta (difference) between the values - our method vs the one implemented in ```torch```
* X-axis - number of iterations used for the Chebyshev or the number of terms

See the [Epic](https://github.com/OpenMined/PySyft/issues/3997) to check more details regarding where to place the graphs.

**Comment by arturomf94** [comment]
I can take this up :)

**Comment by gmuraru** [comment]
Done :+1:
