### ISSUE TITLE
Benchmark AST operations

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4000]
## What?
Benchmark the ```AST``` operations using the already existing implemented protocols (```fss``` and ```snn```) - some of them might be ```relu```, ```conv2d```, ```batchnorm```.

A good idea for a more real-life scenario would be to use ```GridNodes``` from [PyGrid](https://github.com/OpenMined/PyGrid)
But, we can start with ```VirtualWorkers``` and then move to the Grid.

The final output should be a graph or graphs (png images) where:
* X-axis - the used precision for the ```FPT```
* Y-axis - the time to compute the operation

We can have multiple lines, each one representing an approximation method.

Some more possibilities:
* Y-axis (or Y2-Axis) - delta (difference) between the values - our method vs the one implemented in ```torch```
* X-axis - number of iterations used for the Chebyshev or the number of terms

See the [Epic](https://github.com/OpenMined/PySyft/issues/3997) to check more details regarding where to place the graphs.

**Comment by aanurraj** [comment]
I'll take this up :)
