### ISSUE TITLE
Aarch Support

### ISSUE THREAD

**Issue by patselle** [OpenMined/PySyft#4003]
Hi PySyft-Team,

In the past I was able to run PySyft completely on a Jetson Nano and Jetson TX2 (under v0.2.1.a1, torch==1.3.0). 
However, this installation was very cumbersome due to all the dependencies.

Currently I use a Jetson Xavier NX Developer Kit.
This comes with JetPack 4.4, so I can only use Torch version 1.6.0. This restricts me when installing PySyft, because I cannot use older versions.

Of course it would be best to use the current PySyft version. This fails because of the torch (torch~=1.4.0) and torchvision (torchvision~=0.5.0) version, as well as the installation of shaloop==0.2.1-alpha.11.

Can you help me further, because I would like to use PySyft.

Thanks in advance

Patrick

**Comment by Syzygianinfern0** [comment]
You could remove the lines  
https://github.com/OpenMined/PySyft/blob/1f36fbf0034bcaf2f8afe7ac9ccf85bcd425383e/pip-dep/requirements.txt#L21
and 
https://github.com/OpenMined/PySyft/blob/1f36fbf0034bcaf2f8afe7ac9ccf85bcd425383e/pip-dep/requirements.txt#L22

and install using a ```pip install -r pip-dep/requirements.txt```

**Comment by donarni** [comment]
Hi, I'm currently having the same problem. Does this really work?
