### ISSUE TITLE
Most recent version of the codebase is broken

### ISSUE THREAD

**Issue by abogaziah** [OpenMined/PySyft#4017]
## Description
I merged the master branch of pysyft to my fork of pysyft and now everything is broken, what I discovered so far is the .send() and .share() functions 
## How to Reproduce
1. Clone pysyft to your machine or pull the last version of the repo
2. run jupyter notebook or python shell from inside pysyft folder (to use the cloned code, not the installed one)
3. run torch.tensor(0).send(bob) or .share or anything else
4. AttributeError: type object 'EmptyCryptoPrimitiveStoreError' has no attribute 'get_msgpack_code'

**Comment by gmuraru** [comment]
Hmm...did you try upgrading ```syft-proto```?

**Comment by abogaziah** [comment]
@gmuraru that worked 😅
