### ISSUE TITLE
Implement FloatTensor Destructor

### ISSUE THREAD

**Issue by emregoynugur** [OpenMined/PySyft#402]
User should be able clean the memory of the Unity application, whenever a tensor's reference count reaches to zero. That means we need to send a "delete" command `controller.socket.send_json({"functionCall":"deleteTensor", "id": self.id` from the Python client to the Unity application, when the class destructor `def __del__(self):` is being called.

When the Unity application receives this command it should remove the tensor from `tensors` and call `tensor.Dispose()` method. Should we create another issue for the Unity side?

User also may want to explicitly free the memory. I read that `del object` might not be sufficient to call the destructor. In this case, we might need to add a new method which sends a delete request to the Unity backend.

**Comment by bosr** [comment]
I think this one can be closed.

**Comment by charlieanna** [comment]
Can someone close this one please. Will help the newbies to know which ones to work on.
