### ISSUE TITLE
PySyft installation in Raspberry Pi 4 (32bit, ARMv7l)

### ISSUE THREAD

**Issue by AbhishekPokala** [OpenMined/PySyft#4022]
### 
Trying to install PySyft from the pip command (without dependencies).

`pip3 install syft==0.2.3 --no-dependencies`
It installed with no errors.

But when I try importing syft, it throws the following error.

### Error Message

Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
> import syft

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/__init__.py", line 15, in <module>
>     import syft.frameworks.torch.hook.hook_args
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/frameworks/torch/hook/hook_args.py", line 6, in <module>
>     from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 13, in <module>
>     from syft.frameworks.torch.tensors.interpreters.crt_precision import _moduli_for_fields
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/crt_precision.py", line 7, in <module>
>     from syft.frameworks.torch.tensors.interpreters.precision import FixedPrecisionTensor
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/precision.py", line 7, in <module>
>     from syft.generic.pointers.multi_pointer import MultiPointerTensor
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/generic/pointers/multi_pointer.py", line 11, in <module>
>     from syft.workers.base import BaseWorker
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/workers/base.py", line 21, in <module>
>     from syft.generic.pointers.object_pointer import ObjectPointer
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/generic/pointers/object_pointer.py", line 15, in <module>
>     from syft.messaging.message import ForceObjectDeleteMessage
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/messaging/message.py", line 13, in <module>
>     from syft.frameworks.torch.tensors.interpreters.placeholder import PlaceHolder
>   File "/home/abhishek/.local/lib/python3.6/site-packages/syft/frameworks/torch/tensors/interpreters/placeholder.py", line 7, in <module>
>     from syft_proto.frameworks.torch.tensors.interpreters.v1.placeholder_pb2 import (
> ModuleNotFoundError: No module named 'syft_proto.frameworks.torch.tensors.interpreters.v1.placeholder_pb2'
 

### System Information
`uname -a` 

> Linux ubuntu 5.4.0-1015-raspi #15~18.04.1-Ubuntu SMP Fri Jul 10 09:20:51 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

### Tangential Question
The only reason I'm installing syft with `--no-dependencies` flag because I'm having trouble installing torchvision. I built torch (1.7) from the source but I'm having issues with torchvision. Can anyone provide any references for the installation here?

Thanks.

**Comment by alejandrosame** [comment]
Hi!

At the beginning of the year I successfully installed PySyft on Raspberry Pi 4s. You could check [here](https://github.com/brahman-ai/bb-aaa#setting-up-raspberry-pi-for-pysyft-and-pygrid) for inspiration, but beware that the PySyft fork used in that project is now outdated and I haven't been supporting it lately.

To install Torch and TorchVision, I used [this wheel](https://github.com/sungjuGit/PyTorch-and-Vision-for-Raspberry-Pi-4B).

I hope those pointers can help you!
Cheers.

**Comment by gmuraru** [comment]
@AbhishekPokala did it help? :D

**Comment by AbhishekPokala** [comment]
@alejandrosame:
I've installed torch and torchvision from the above wheels. 
But when I manually build syft, I get the following error: https://github.com/OpenMined/PySyft/issues/4033

And when I try to import syft after installing it from the your fork, 
I get the following error.

`import syft`

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/__init__.py", line 15, in <module>
    import syft.frameworks.torch.hook.hook_args
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/frameworks/torch/hook/hook_args.py", line 6, in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/frameworks/torch/tensors/interpreters/native.py", line 13, in <module>
    from syft.frameworks.torch.tensors.interpreters.crt_precision import _moduli_for_fields
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/frameworks/torch/tensors/interpreters/crt_precision.py", line 7, in <module>
    from syft.frameworks.torch.tensors.interpreters.precision import FixedPrecisionTensor
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/frameworks/torch/tensors/interpreters/precision.py", line 7, in <module>
    from syft.generic.pointers.multi_pointer import MultiPointerTensor
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/generic/pointers/multi_pointer.py", line 11, in <module>
    from syft.workers.base import BaseWorker
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/workers/base.py", line 21, in <module>
    from syft.generic.pointers.object_pointer import ObjectPointer
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/generic/pointers/object_pointer.py", line 15, in <module>
    from syft.messaging.message import ForceObjectDeleteMessage
  File "/home/abhishek/PySyftBuildFolder/PySyft/PyGrid/src/syft/syft/messaging/message.py", line 14, in <module>
    from syft_proto.messaging.v1.message_pb2 import OperationMessage as OperationMessagePB
ImportError: cannot import name 'OperationMessage' from 'syft_proto.messaging.v1.message_pb2' (/home/abhishek/.local/lib/python3.7/site-packages/syft_proto/messaging/v1/message_pb2.py)

**Comment by alejandrosame** [comment]
@AbhishekPokala did you also install syft-proto via `pip3 install syft-proto`?

**Comment by AbhishekPokala** [comment]
@alejandrosame:
Yep.

> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: syft-proto in /home/abhishek/.local/lib/python3.7/site-packages (0.5.1)
> Requirement already satisfied: protobuf>=3.12.2 in /home/abhishek/.local/lib/python3.7/site-packages (from syft-proto) (3.13.0)
> Requirement already satisfied: six>=1.9 in /home/abhishek/.local/lib/python3.7/site-packages (from protobuf>=3.12.2->syft-proto) (1.15.0)
> Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from protobuf>=3.12.2->syft-proto) (39.0.1)

**Comment by alejandrosame** [comment]
@AbhishekPokala Then I would try again by installing Torch through that wheel but now installing the official OpenMined fork. Back in January I made a custom repo because there were cross references and I merged two different forks to align them, but the codebase has moved a lot!

I'm not working with Pis and AI right now, but I could also try to replicate the installation on the weekend to try to see what has changed, in case you don't succeed by then :)

**Comment by alejandrosame** [comment]
@AbhishekPokala I found the base ISO that I generated then. In case it is of any use for you, you can get it from the link referenced in [this repo](https://github.com/brahman-ai/RPiSyft). Just remember that the syft and grid installed there are the pulled from the custom fork I mentioned before, which are outdated compared to current PySyft codebase. 

Maybe that is good enough for you right now, or maybe it is you succeed updating the code from the dependencies already installed in the ISO :crossed_fingers:

**Comment by AbhishekPokala** [comment]
My apologies for the late response, I must've missed your message. 

I've actually succeeded in installing the latest version of PySyft (v0.2.8) in a Raspberry Pi 4 (armv7l architecture).
I was successful in building torch from source but couldn't do it for torchvision so I had to use the wheel file from [HERE](https://github.com/sungjuGit/PyTorch-and-Vision-for-Raspberry-Pi-4B) to install it.
I did run into issues with aiortc and shaloop dependencies of PySyft but I eventually figured it out.

Thanks a lot for your help!

**Comment by madhavajay** [comment]
@AbhishekPokala is this now working? I imagine the same issues will happen with the new 0.3.0 release and Torch on arm linux, perhaps you could try this with 0.3.0 and document the process so we can add it to our docs? I have a TinkerBoard in the cupboard I can grab to do some testing as well on Raspbian.

**Comment by madhavajay** [comment]
@AbhishekPokala any chance you can test out the nightlies and see if they install on your hardware?
https://github.com/OpenMined/PySyft/issues/4826

**Comment by madhavajay** [comment]
I will close this for now since we support `torch==1.4.0` so the main thing preventing Arm usage is finding an up to date Python wheel of PyTorch which is a little out of our scope. We have a separate issue to track testing on Arm64 CI and once Apple's M1s are readily available on CI we can add more Arm tests.
