### ISSUE TITLE
Move benchmarks to use a framework

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4024]
## Description
At the point of implementing this issue, we should have some benchmark scripts/notebooks in the ```syft/frameworks/torch/mpc/benchmark``` folder.
A good idea is to use a benchmarking tool like [asv](https://asv.readthedocs.io/en/stable/writing_benchmarks.html).

## This will involve
* (Optional) Look for other benchmark tools and decide with the team on should be the best one
* Creating a benchmark folder at the top level of the PySyft repo (I think is good to have benchmarks for all the components not only for ```smpc```
* Have benchmarks run on a weekly/daily basis using [continuous-benchmark](https://github.com/marketplace/actions/continuous-benchmark)

## Additional Context
We might need to see how our future changes affect the time for all our operations.

**Comment by gmuraru** [comment]
@arturomf94 I think this is done. Could we close this?

**Comment by arturomf94** [comment]
Yes - closing...
