### ISSUE TITLE
Check dependency CrypTen tests

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4025]
## Description
Currently, CrypTen is available only on Linux and Mac, but if someone installs the PySyft repo and run the tests we also have some CrypTen related tests.
Those should be taken into consideration only if we have ```dependency_check.crypten```.

## How to Reproduce
Run the tests on Windows

## Expected Behavior
All the tests should pass - maybe skip the tests for CrypTen.

**Comment by Karnak123** [comment]
Hi, it's Sagnik from Slack, may I handle this issue?

**Comment by gmuraru** [comment]
Sure! :D
