### ISSUE TITLE
How can I use pygrid to do the encrypted deep learning? 

### ISSUE THREAD

**Issue by junrong1** [OpenMined/PySyft#4027]
## Question
**Describe your question in ONE SENTENCE.**

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by gmuraru** [comment]
Are the tutorials helping (they can be found in this repository)?

**Comment by junrong1** [comment]
> Are the tutorials helping (they can be found in this repository)?

Those are using Pysfyt and use the local virtual worker, I'd like to use the pygrid and to do the encrypted deep learning

**Comment by gmuraru** [comment]
In the PyGrid case, you will simply have to change the ```VirtualWorker``` with a different component.
Maybe also [this repo](https://github.com/OpenMined/PyGrid) will help
