### ISSUE TITLE
Flaky exp test

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4036]
## Description
The tolerance for the ```exp``` needs to be increased since it is failing randomly (because of the random order in which we run the tests).

## How to Reproduce
```
____________________ test_torch_sigmoid_approx[exp-3-0.065] ____________________

method = 'exp', prec_frac = 3, tolerance = 0.065
workers = {'alice': <VirtualWorker id:alice #objects:1>, 'bob': <VirtualWorker id:bob #objects:1>, 'charlie': <VirtualWorker id:charlie #objects:0>, 'james': <VirtualWorker id:james #objects:0>, ...}

    @pytest.mark.parametrize(
        "method, prec_frac, tolerance",
        [
            ("chebyshev", 3, 6 / 100),
            ("chebyshev", 4, 1 / 1000),
            ("exp", 3, 6.5 / 100),
            ("exp", 4, 1 / 100),
            ("maclaurin", 3, 7 / 100),
            ("maclaurin", 4, 15 / 100),
        ],
    )
    def test_torch_sigmoid_approx(method, prec_frac, tolerance, workers):
        """
        Test the approximate sigmoid with different tolerance depending on
        the precision_fractional considered
        """
        alice, bob, james = workers["alice"], workers["bob"], workers["james"]
        t = torch.tensor(range(-10, 10)) * 0.5
        t_sh = t.fix_precision(precision_fractional=prec_frac).share(alice, bob, crypto_provider=james)
        r_sh = t_sh.sigmoid(method=method)
        r = r_sh.get().float_prec()
        t = t.sigmoid()
        diff = (r - t).abs().max()
        norm = (r + t).abs().max() / 2
    
>       assert (diff / (tolerance * norm)) < 1
E       assert (tensor(1.2798e+13) / (0.065 * tensor(6.3991e+12))) < 1
```

## Expected Behavior
The test should be passing

**Comment by addy369** [comment]
Hey @gmuraru would want to work on this!

**Comment by gmuraru** [comment]
Assigned it to you! But I think this will require more research since it seems that the value is pretty high and probably we do something behind the scenes which brokes the ```exp```. A simple increase in the tolerance would not do the job.

**Comment by gmuraru** [comment]
The issue is related to the method we use for ```sigmoid``` when computing ```reciprocal```.
Could you make a PR where you can simply add ```method="division"``` to the reciprocal.

**Comment by addy369** [comment]
So multiple things. Firstly, should'nt we get a value >1 and not <1 as the assert suggests! Also the reciprocal method is tested.Passing method="division  is just a default parameter and anyway tests with all methods(divison,log,nr) are getting passed. Tell me if I am missing something

**Comment by gmuraru** [comment]
I merged yesterday a PR for [this](https://github.com/OpenMined/PySyft/pull/4044).
Yep - you are correct. The tests are passing, but there is a scenario that we do not take care of. Opened a new issue for this - [here](https://github.com/OpenMined/PySyft/issues/4048)

**Comment by devkumar24** [comment]
Hey, I want to work on this issue, Can you assign me on this issue?

**Comment by gmuraru** [comment]
Sure :D

**Comment by madhavajay** [comment]
@gmuraru is this issue still valid?

**Comment by gmuraru** [comment]
It can be closed - we would deal with it in SyMPC when the time would come
