### ISSUE TITLE
Create Tutorial regarding the different protocols

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4063]
## Description
Currently, we have implemented ```securenn``` and ```fss```.
It might be a good idea to showcase some of the features (from both) and also indicate the ```crypto_store``` and what it is doing.

**Comment by NiWaRe** [comment]
Hey, I'll start to work on this issue from now on, as discussed with @somiljain7 and @LaRiffle 👍

**Comment by gmuraru** [comment]
> hey @gmuraru !
> can i take this issue

I am very sorry that I did not see this reply :(. Maybe you guys can coordinate with each other.

**Comment by NiWaRe** [comment]
Hey @LaRiffle @gmuraru @somiljain7,
I started with creating a notebook outline and a first version of high level explanations of the different protocols. 
The idea was that even people who don't understand how exactly the SMPC-encryption works can still get a high level grasp of what it does and especially what kind of models they can train and infer on using the different encryption. 

As mentioned in my PR it would be nice if you could quickly give quick feedback on whether the outline makes sense (does what I did so far correspond with what you had in mind?) and whether the content is correct and understandable. I marked parts of the content where I'm not 100% sure red (I'm also new to the protocols) so those are especially important.  

Next steps would be do to the implementations and incorporate feedback/improve understandability, etc. 👍
