### ISSUE TITLE
PySyft Tensor Issues

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#407]
### User Story
As a Contributor to OpenMined - I would like to have bite-sized work increments spelled out in the form of individual Issues I can work on (1-2 hours or less) so that I can enjoy my time writing code in the platform instead of worrying about which part needs code next.

Specifically, I'd like bite sized issues to be created for each function in [PyTorch's Tensor Library](http://pytorch.org/docs/master/tensors.html) to be implemented according to the template in [This Issue](https://github.com/OpenMined/PySyft/issues/406). Each issue should be labeled with the "good first issue" and "help wanted" labels, and the template should be modified to fit the functionality of each function from PyTorch to which it refers.

For each issue, please comment a link to it in the comments below.

### Acceptance Criteria
- [ ] All issues are created for all tensor types and methods in [PyTorch's Tensor Library](http://pytorch.org/docs/master/tensors.html)

**Comment by iamtrask** [comment]
Made a first batch!!

https://github.com/OpenMined/PySyft/issues/403
https://github.com/OpenMined/PySyft/issues/404
https://github.com/OpenMined/PySyft/issues/405
https://github.com/OpenMined/PySyft/issues/406

**Comment by alberduris** [comment]
```
BatchManager().next_batch(batch_size=4)
```

#408 
#409
#410
#411

**Comment by alberduris** [comment]
Give me all

#412 #413 #414 #415 #416 #417 #418 #419 #420 #421 #422 #423 #424 #425 #426 #427 #428 #429 #430 #431 #432 #433 #434 #435 #436 #437 #438 #439 #440 #441 #442 #443 #444 #445 #446 #447 #448 #449 #450 #451 #452 #453 #454 #455 #456 #457 #458 #459 #460 #461 #462 #463 #464 #465 #466 #467 #468 #469 #470 #471 #472 #473 #474 #475 #476 #477 #478 #479 #480 #481 #482 #483 #484 #485 #486 #487 #488 #489 #490 #491 #492 #493 #494 #495 #496 #497 #498 #499 #500 #501 #502 #503 #504 #505 #506 #507 #508 #509 #510 #511 #512 #513 #514 #515 #516 #517 #518 #519 #520 #521 #522 #523 #524 #525 #526 #527 #528 #529 #530 #531 #532 #533 #534 #535 #536 #537 #538 #539 #540 #541 #542 #543 #544 #545 #546 #547 #548 #549 #550 #551 #552 #553 #554 #555 #556 #557 #558 #559 #560 #561 #562 #563 #564 #565 #566 #567 #568 #569 #570 #571 #572 #573 #574 #575 #576 #577 #578 #579 #580 #581 #582 #583 #584 #585 #586 #587 #588 #589 #590 #591 #592 #593 #594 #595 #596 #597 #598 #599 #600 #601 #602 #603 #604 #605 #606 #607 #608 #609 #610 #611 #612 #613 #614 #615 #616 #617 #618 #619 #620 #621 #622 #623 #624 #625 #626 #627 #628 #629 #630

**Comment by diegoalejogm** [comment]
Awesome

**Comment by iamtrask** [comment]
Wow - I suppose we can close this out!
