### ISSUE TITLE
Add type annotations and docstring to all the files related to Falcon

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4505]
## Description
* Having ```type annotations``` will give us (+ to the newcomers) a better understand what a parameter should be when calling a function/what a function should return, etc.. After we move our code to the new version of syft this having type annotations and docstrings will be a must otherwise the code will "explode".
* Docstring - will be good when Pysyft will have autogenerated library code

## Additional Context
Currently, the files related to the falcon protocol can be found in:
* ```syft/frameworks/torch/mpc/falcon```
* ```syft/frameworks/torch/tensors/interpreters/replicated_sharing_tensor.py```

**Comment by nahuakang** [comment]
@gmuraru I'd be interested in taking on this but might need some context. Will ping you on Slack :smiley:

**Comment by divyanshugit** [comment]
Hey, I would like to work on this issue. Can you suggest me some ways to get started?

**Comment by duggalsu** [comment]
@gmuraru hi, I can work on this if still available

**Comment by gmuraru** [comment]
Yep, you can both work on this. Currently, FALCON milestone is still ongoing but there are methods (like the ones from RST) that need documentation.

**Comment by devkumar24** [comment]
Hey, I am new to the open-source community and would to start contributing and Think of starting
 with this issue, can I start off this issue?

**Comment by dnabanita7** [comment]
Hello @gmuraru I am a newbie to openmined and would love to make my hands dirty with this project. Can you please make me the assignee? Thanks!:)

**Comment by gmuraru** [comment]
Hello! For the moment this issue is not available since it is targeting a previous version (0.2.x). Thank you for pointing this out!
