### ISSUE TITLE
Sending requests to the pygrid using os.path.join

### ISSUE THREAD

**Issue by xanderwallace85** [OpenMined/PySyft#4514]
## Description
I have just noticed a limitation of PySyft/PyGrid when relying on `os.path.join` to interface with the network. More specifically, nothing happens when I try to add a node to the network using `.\apps\node\run.sh --id Alice --port 5001 --host localhost --network http://localhost:7000 --start_local_db`. I manually checked this behavior as shown below. This is due to the fact that `os.path.join` uses back slashes instead of forward slashes. I temporally solved this using `.replace("\\","/")` after `os.path.join`.

## How to Reproduce
1. Create a grid via `.\apps\network>run.sh --port 7000 --start_local_db`
2. In a Jupyter notebook run

> import requests
> import os
> import json
> 
> node_id = 'Alice'
> port = '5001'
> GRID_NETWORK_PORT = '7000'
> 
> res = requests.post(
>      #  Expected path "http://localhost:7000//join"
>      # Actual path "http://localhost:7000\\join"
>      os.path.join("http://localhost:" + GRID_NETWORK_PORT, "join"),
>      data=json.dumps(
>          {"node-id": node_id, "node-address": "http://localhost:" + port}
>      ),
> )

3. Check response via `res.text`
4. Response: `'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'`

## Expected Behavior
The path should be "http://localhost:7000//join" (now "http://localhost:7000\\join").

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.7.3 (running on virtualenv)
 - Browser (if applicable): Google Chrome

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
