### ISSUE TITLE
Fix all warnings in documentation build

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#4518]
When I run 

```
python setup.py docs
```

in the syft_0.3.0 branch I currently get 92 warnings. My build finishes with:

```
common.UID, syft.core.common.uid.UID
/Users/atrask/Dropbox/Laboratory/openmined/PySyft/PySyft/docs/../src/syft/lib/python/primitive.py:docstring of syft.lib.python.primitive.PyPrimitive.__init__:: WARNING: more than one target found for cross-reference 'UID': syft.core.common.UID, syft.core.common.uid.UID
/Users/atrask/Dropbox/Laboratory/openmined/PySyft/PySyft/docs/../src/syft/lib/python/primitive.py:docstring of syft.lib.python.primitive.PyPrimitive.id:: WARNING: more than one target found for cross-reference 'UID': syft.core.common.UID, syft.core.common.uid.UID
generating indices...  genindex py-modindexdone
highlighting module code... [100%] torch.nn.parameter
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 92 warnings.

The HTML pages are in build/sphinx/html.
```

To solve this issue, fix all the warnings!

**Comment by imskr** [comment]
Can i work on this @iamtrask?

**Comment by sparkingdark** [comment]
@iamtrask I want to work on it to fix all the warnings,assign it to me.

**Comment by madhavajay** [comment]
@imskr and @sparkingdark if either of you are able to do this task that would be amazing! ❤️ Please let me know who still wants it first and i'll assign it. As @iamtrask is super busy, I will be helping with the 0.3 task management and going through the remaining backlog of tasks needed for the 0.3 release.

There will be a lot more issues like this and I would love any help on offer.

**Comment by sparkingdark** [comment]
I am on but I need some time as I have some other issues to solve as well.

**Comment by sparkingdark** [comment]
Hey @madhavajay can you give me the instruction to produce the problem scenario I run the `python setup.py docs` but get no option.

**Comment by madhavajay** [comment]
@sparkingdark on the latest syft_0.3.0 branch I did the following:
```
$ pip install sphinx_rtd_theme
$ python setup.py docs
```

Two issues:
- 1 the doc generation is paused as the code crawling accidentally launches a flask server
We should stop this happening, in the mean time hit Control + C to quit it
- 2 after running there are a lot of errors and warnings:
```bash
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 116 warnings.
```

Are you able to replicate these issues on your end?

**Comment by sparkingdark** [comment]
Yes I changed branch to swaft-0.3 and it's done to replicate in my local system.

**Comment by madhavajay** [comment]
@sparkingdark how did you go?

**Comment by sparkingdark** [comment]
It's going slowly I tried to fix it using warning library but not worked.Now I am trying to solve it @madhavajay

**Comment by madhavajay** [comment]
@sparkingdark, okay no problems. If you want to come onto slack and message me if you have any issues maybe I can help.

**Comment by sparkingdark** [comment]
Okay send me the slack invite my email is debomastet335@gmail.com

**Comment by madhavajay** [comment]
Hi @sparkingdark if you have any specific issues post them here, but if you want real time help join public slack https://openmined.slack.com/ where there are many other contributors who can potentially answer your questions.

**Comment by sparkingdark** [comment]
@madhavajay thanks for the reply and I was pretty busy with my college and assignments but now I am start working again the assigned issues.

**Comment by JMLourier** [comment]
Hi @madhavajay and @sparkingdark, do you need support on this issue? I'd like to contribute here.

**Comment by madhavajay** [comment]
@JMLourier Yes if you could I can assign it to you for now. @sparkingdark I didn't hear from you so ill just assign it to @JMLourier for now if thats okay.

**Comment by sparkingdark** [comment]
@madhavajay can you send me the slack invite?

**Comment by madhavajay** [comment]
Hi @sparkingdark the Slack is Public. Unfortunately I have no assigned this to @JMLourier so if you want to help see if theres some way you can sub divide the work otherwise there are other tickets available.
<img width="629" alt="Screen Shot 2020-12-04 at 8 58 33 am" src="https://user-images.githubusercontent.com/2882739/101098585-e6874980-360e-11eb-84b4-d65b41a6bfd0.png">

**Comment by sparkingdark** [comment]
Okay I try to find some other issues to work.

**Comment by JMLourier** [comment]
Hi @madhavajay, I fixed quite some simple issues around wrong docstring formating. For the remaining issues I would need some support. Shall I post the questions to the Slack channel or is there any other way of getting support? Many thanks!

**Comment by madhavajay** [comment]
Hi @JMLourier thats great! Any chance you can open a PR? That's our preferred way to collaborate as you can imagine copying and pasting code around Slack which is just overwhelmed with continual new posts isn't the best way to track a discussion about specific code. If you want some private DM conversation thats fine, but without some code to look it's going to be a lot harder to understand your questions.

https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md
