### ISSUE TITLE
Add Linux Build Instructions to Documentation

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#4519]
## Where?
https://pysyft.readthedocs.io/en/latest/installing.html#linux-installation

## Who?
Users of LInux

## What?
I would like for this documentation to help even the noobiest noob build PySyft from source successfully on their linux machine (for all the popular versions of Linux).

## Additional Context
See the Mac OS X documentation for an example on just how noob friendly we want to be!

**Comment by telemachosc** [comment]
I would like to work on this one

**Comment by ramesht007** [comment]
hey, @iamtrask, if this issue is still not taken I would like to work on this

**Comment by gmuraru** [comment]
You can both work and make PRs into the syft_0.3.0 branch :D

**Comment by madhavajay** [comment]
@ramesht007 great work, I will close this as completed for now!
