### ISSUE TITLE
Add Windows Build Instructions

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#4520]
## Where?
https://pysyft.readthedocs.io/en/latest/installing.html#windows-installation

## Who?
Users of Windows

## What?
I would like for this documentation to help even the noobiest noob build PySyft from source successfully on their windows machine (for all the popular versions of Windows).

## Additional Context
See the Mac OS X documentation for an example on just how noob friendly we want to be!

**Comment by rajathpatel23** [comment]
Can I work on this issue ?

**Comment by Boluwatifeh** [comment]
I feel this is a good one to start with. Can i work on this @iamtrask

**Comment by ramesht007** [comment]
hi @iamtrask, I would like to work on this one.

**Comment by gmuraru** [comment]
Closing this as it is fixed by [this](https://github.com/OpenMined/PySyft/pull/4622)
