### ISSUE TITLE
How to run pysyft-notebook docker image with docker volume?

### ISSUE THREAD

**Issue by grilhami** [OpenMined/PySyft#4523]
## Question
How can I run the `openmined/pysyft-notebook` image on docker volume?

## Further Information

I'm currently starting to dive into using PySift to learning about Private AI. I decided to use the docker container installation for my learning path using the `openmined/pysyft-notebook` image. However, docker containers remove all data that has been made will be deleted. That's why I decide to use docker volume.

Since I'm running the image on a remote server, I used the following to run the container

`docker container run -p 8888:8888 openmined/pysyft-notebook`

Then, in order to run with a volume, I modified the command to the following

`docker container run -p 8888:8888 -v syft:/workspace openmined/pysyft-notebook`

Where `syft` is the volume I created, and `/workspace` is the working directory. After additional configuration, I was able to access the notebook smoothly on my local machine without any issue. However, after starting a new container by doing the same command (the one with the added docker volume), the notebook that I worked with did not appear.

I tried other directories for the container such as `syft:/root/workspace`, `syft:/root`, and `syft:/notebooks`. It still the same case where the jupyter notebook still deleted each time I run a new container. I'm not really sure in which the directory the image saved data.

I was wondering if anybody could point out what I was missing here? Thanks in advance 

## System Information
 - OS: Linux Ubuntu
 - OS 18.04.5 LTS
 - Language Version: Python 3.7.6
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
