### ISSUE TITLE
Does the framework support IPv6 networks?

### ISSUE THREAD

**Issue by lusterr** [OpenMined/PySyft#4527]
Is this framework suitable for IPv6 network environment?

**Comment by LaRiffle** [comment]
Maybe @IonesioJunior @cereallarceny can provide some insight here?

**Comment by madhavajay** [comment]
I have checked this in 0.3.0 and it seems while the Flask server runs in IPV6 the sy.duet() joining function fails to connect.
We will investigate further.

**Comment by rajatrc1705** [comment]
I would like to work on this issue. I have only recently started exploring PySyft so I may need some hint or help to get started.
Could you assign this to me?

**Comment by madhavajay** [comment]
@rajatrc1705 Your help would be greatly appreciated. I would do the following:
- Run the local network signaling server with:
```
$ syft-network
```
- Start jupyter notebooks and load up any example like MNIST or even a basic connection
- Connect via your local network server using the instructions here: https://github.com/OpenMined/PySyft/tree/master/examples/duet/#host-a-network
```
duet = sy.launch_duet(network_url="http://127.0.0.1:5000")
```

Then once its working, modify the script and the code to get it working over IPV6.

Please note however, people often offer to help with issues but never get around to submitting a PR, as such if there is no Draft PR showing some initial attempt after a week, then if someone else wants to take this issue I will have to reassign it. I hope you can understand. If you have any questions feel free to ping me on Slack.

**Comment by rajatrc1705** [comment]
Yes, I will make sure to keep you informed about my progress on this issue.
