### ISSUE TITLE
## Under contributors guidelines to pysft, deploying workers guide returns a 404 page

### ISSUE THREAD

**Issue by Boluwatifeh** [OpenMined/PySyft#4530]
## Description
A clear and concise description of the bug.

## How to Reproduce
2. Click on '...'
3. Scroll down to '...'

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by LaRiffle** [comment]
Hey can you please precise what the bug is? Thanks 😄

**Comment by Boluwatifeh** [comment]
Hey there @LaRiffle i was reading through the contribution.md page and under the deploying workers section, the example link on how to deploy workers returns a 404 page. Here's the link https://github.com/OpenMined/PySyft/blob/master/examples/deploy_workers/deploy-and-connect.ipynb

**Comment by LaRiffle** [comment]
I guess it has been moved here: https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/tutorial-websocket/deploy_workers/deploy-and-connect.ipynb
Will fix this, thanks!
