### ISSUE TITLE
Implement Federated Learning optimizations: pruning & quantization

### ISSUE THREAD

**Issue by roberthoenig** [OpenMined/PySyft#4540]
## Feature Description
I would like to implement some optimizations for federated learning that would reduce communication cost. In particular, I am
considering pruning (https://arxiv.org/pdf/1909.12326.pdf) or quantization (https://arxiv.org/pdf/1909.13014.pdf).

Would these optimizations make for a good contribution to the PySyft repository? 

## Is your feature request related to a problem?
Federated learning is bottlenecked by communication costs.

## What alternatives have you considered?
None.

## Additional Context
I'm considering to make my Bachelor Thesis about federated learning. I'm thinking about reducing the communication overhead for federated learning. PySyft seems like a great basis for this project.

**Comment by gmuraru** [comment]
Hey @roberthoenig!

I think this is a good idea ^_^ and we will accept PRs that adds functionalities on top of PySyft. What do you think @LaRiffle ?

**Comment by LaRiffle** [comment]
Yeah that would be really great! :) 
I would strongly recommend to apply the Federated Learning team if you want to commit to such a project and be in touch with the rest of the team: https://placements.openmined.org/#h.mhok1srmapq4

**Comment by roberthoenig** [comment]
Thanks for the feedback! It's probably gonna be a couple more weeks before I've fully fledged out my project. I'll keep this issue updated with any relevant developments.

**Comment by LaRiffle** [comment]
Ok that's great! Get in touch with the team whenever you're ready to start :)

**Comment by roberthoenig** [comment]
Hi there -- I ended up using a different framework (https://github.com/adap/flower) to implement this, so I won't be working on this issue. Feel free to close this issue, but also feel free to keep it open for other contributors.

**Comment by MMorafah** [comment]
Please check out this repository (https://github.com/MMorafah/Sub-FedAvg). It provides an official implementation for Sub-FedAvg which is Federated Learning Pruning benchmark.
