### ISSUE TITLE
How to achieve training when the work itself has data, without calling send()

### ISSUE THREAD

**Issue by ConRresIm** [OpenMined/PySyft#4548]
## Question
**How to achieve training when the work itself has data, without calling send().**

**Comment by gmuraru** [comment]
You want to say that the worker that orchestrates the training/inference has a part of the data/model on their side?

**Comment by LaRiffle** [comment]
You could search for this data! We have a `search` functionality available! Your worker should only tag its data, and the you search for it and get a pointer (just like if you had send this data but you have not), and then the procedure is unchanged

**Comment by NeuZhangQiang** [comment]
@LaRiffle Could you please give a demo? Thank you very much!

**Comment by sug4ndh** [comment]
@gmuraru @LaRiffle For instance, here is my setup running Pygrid.  Model is on machine A, it's acting as grid node, node id 'alice' and also as grid network. Data is already present on machine B, acting as grid node, node id 'bob'. The data on machine B has been tagged. Now, if I leave it as it is and then search on the network, I don't get any results. However, if I send the data to bob, node id for the same machine where the data resides, then I get results! Am I missing something here?
