### ISSUE TITLE
Hi, I am getting import error ' from crc32c import crc32' when i am trying to run WebsocketServerWorker on GCP ,Please suggest to fix this 

### ISSUE THREAD

**Issue by chiragwadhwa08** [OpenMined/PySyft#4551]
## Description
A clear and concise description of the bug.
I installed the dependecies using !pip install syft[udacity,notebooks] using Google cloud Notebook . 
but getting this error.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/aiortc/rtcsctptransport.py in <module>
     32 try:
---> 33     from crc32c import crc32
     34 except ImportError:  # pragma: no cover

ImportError: cannot import name 'crc32' from 'crc32c' (/opt/conda/lib/python3.7/site-packages/crc32c/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-0df61b862dcd> in <module>
      1 import torch
----> 2 import syft as sy
      3 
      4 hook = sy.TorchHook(torch)
      5 

## How to Reproduce
Please run this script to reproduce 

import torch
import syft as sy

hook = sy.TorchHook(torch)

from syft.workers.websocket_server import WebsocketServerWorker

local_worker = WebsocketServerWorker(
                            host="localhost",
                            hook=hook,
                            id=0,
                            port=8183)

local_worker.start()

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome] -
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
