### ISSUE TITLE
Change the way to convey the compression method

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4559]
## Description
This is how we convey the compression lib used: by pre-pending a byte information (see below)
It implies concatening a byte with a potentially huge message, and then splitting it. Python is really not efficient at this, and it makes us loose precious time.

I am struggling to find a better way to do this. I'm looking for ideas!

```python
def _compress(decompressed_input_bin: bin) -> bin:
    """
    This function compresses a binary using the function _apply_compress_scheme
    if the input has been already compressed in some step, it will return it as it is

    Args:
        decompressed_input_bin (bin): binary to be compressed

    Returns:
        bin: a compressed binary

    """
    compress_stream, compress_scheme = _apply_compress_scheme(decompressed_input_bin)
    try:
        z = scheme_to_bytes[compress_scheme] + compress_stream
        return z
    except KeyError:
        raise CompressionNotFoundException(
            f"Compression scheme not found for compression code: {str(compress_scheme)}"
        )


def _decompress(binary: bin) -> bin:
    """
    This function decompresses a binary using the scheme defined in the first byte of the input

    Args:
        binary (bin): a compressed binary

    Returns:
        bin: decompressed binary

    """

    # check the 1-byte header to check the compression scheme used
    compress_scheme = binary[0]

    # remove the 1-byte header from the input stream
    binary = binary[1:]
    # 1)  Decompress or return the original stream
    if compress_scheme == LZ4:
        return lz4.frame.decompress(binary)
    elif compress_scheme == ZLIB:
        return zlib.decompress(binary)
    elif compress_scheme == NO_COMPRESSION:
        return binary
    else:
        raise CompressionNotFoundException(
            f"Compression scheme not found for compression code: {str(compress_scheme)}"
        )
```

## Additional Context
For the first layer of Resnet 18 for encrypted inference, 0.34s is lost simply just because of this.

**Comment by gmuraru** [comment]
@LaRiffle Do you know what percent of that time is lost in ```_compress``` and ```_decompress``` (in each function)?

**Comment by LaRiffle** [comment]
For the operation I mentioned, with my current optimization (working with cuda), the global runtime is 2.0s for 0.34 is 17%. For the resnet18 blogpost, it's 6% of the overall runtime :O

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
