### ISSUE TITLE
Cuda support for Federated Learning

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4560]
## Feature Description
Many users have reported failures with GPUs, I think classic FL could easily support cuda!

**Comment by NiWaRe** [comment]
I'll start with that this week-end. 👍  @LaRiffle

**Comment by NiWaRe** [comment]
For Vanilla FL remote shifting to and from CUDA is supported (which has to be done before and after calling the secure aggregation function, a showcase should be added to the current secure aggregation tutorial), remaining problems will be fixed through #4899 #4898. 
Complete encrypted training will be locally possible with Sycret.
