### ISSUE TITLE
Cuda support for Encrypted Computation

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4561]
## Feature Description
SPDZ has 7x more matmul ops than plaintext computations. Using cuda to optimize those would give significant speedups!
SecureNN / FSS use many intensive ops that could also be improved by cuda support. In particular, FSS uses many invocations to AES, and cuda support for AES from https://github.com/pytorch/csprng could be useful!

First investigation is being made here: https://github.com/OpenMined/PySyft/tree/ryffel/cuda + https://github.com/OpenMined/PySyft/tree/ryffel/cuda_fss

Help welcome! :)

**Comment by jlevy44** [comment]
It'd be great to have GPU support, or at least an example, for this tutorial.

https://github.com/OpenMined/PySyft/blob/44dd09d944ab4f927a1e35a6a1e623265cd6cb11/examples/experimental/CrypTen/CrypTen%20-%20Training%20an%20Encrypted%20Neural%20Network%20across%20Workers%20using%20Jails.ipynb

**Comment by jlevy44** [comment]
https://github.com/facebookresearch/CrypTen/issues/115

**Comment by LaRiffle** [comment]
Is fixed by #4895
