### ISSUE TITLE
Add send_to alias method for send

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PySyft#4566]
## Description
`model_pointer.send(vm_client)` is not horribly intuitive as it implies that `model_pointer` is sending the `vm_client` somewhere. In reality, this actually means that `model_pointer` is being sent to the `vm_client` - very different!

The easy way to fix this is to add an alias to the `send` method in 0.3 that is called `send_to`. Calling either method will do the same thing.

## Are you interested in working on this improvement yourself?
- No, but I think @iamtrask  would be interested.

**Comment by madhavajay** [comment]
This has been moved to this PR and will be merged shortly.
https://github.com/OpenMined/PySyft/pull/4638
