### ISSUE TITLE
[BUG] Pip install Typo in Contributing.md

### ISSUE THREAD

**Issue by darigovresearch** [OpenMined/PySyft#4575]
## Where?
CONTRIBUTING.md

## Who?
New Starters & people who want to contribute

## What?
When doing pip installs it mentions `pip-deps` but the only folder is `pip-dep` which contains requirements.txt files

## Additional Context
Need to change docs to `pip-dep` instead

**Comment by darigovresearch** [comment]
Issue would be resolved by pull request #4576

**Comment by LaRiffle** [comment]
Merged! Thanks 🙌
