### ISSUE TITLE
Transpose method `torch.Tensor.T` does not work

### ISSUE THREAD

**Issue by sssilvar** [OpenMined/PySyft#4617]
## Description
When performing the transpose operation `x.T` (where x is a tensor in a worker) returns an empty tensor instead of a pointer. Instead, it is necessary to use `.transform(1,0)`

## How to Reproduce
```python
import torch
import syft as sy

hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id='bob')

x = torch.rand(250, 84).send(bob)  # Synthetic tensor
x.T

# Output
# tensor([])
```

## Expected Behavior
Should return a pointer containing the transposed tensor.

## System Information
- The official released Docker container
- Same for pip package:
  - Ubuntu 18.04.5 LTS (Bionic Beaver)
  - Python 3.6.9

**Comment by Pranay144** [comment]
```python3
import torch
import syft as sy

hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id='bob')

x = torch.rand(250, 84) # Synthetic tensor
x.send(bob)
x.T

#Output : "transpose of x"
```
This code works.
But i don't understand what is your objective here!

**Comment by sssilvar** [comment]
Could you please verify the result is the same? I have tried in three different environments and I get empty tensors when performing the operation `x.T`. Additionally, it does not create a pointer as it should (raising an error when try to `.get()` the tensor from.

```python
x = torch.rand(250,84).send(bob)  # Creates a pointer
torch.eq(x.T, x.transpose(1,0)).get()  # Raises Error
```
Because I get the following:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-b6d586366917> in <module>()
----> 1 torch.eq(x.T, x.transpose(1,0)).get().min()

/usr/local/lib/python3.6/dist-packages/syft/frameworks/torch/tensors/interpreters/native.py in get(self, inplace, user, reason, *args, **kwargs)
    643 
    644         # If it is a local tensor/chain, we don't need to verify permissions
--> 645         if not isinstance(self.child, syft.PointerTensor):
    646             tensor = self.child.get(*args, **kwargs)
    647         else:  # Remote tensor/chain

AttributeError: 'Tensor' object has no attribute 'child'
```

**Comment by sssilvar** [comment]
> ```python
> import torch
> import syft as sy
> 
> hook = sy.TorchHook(torch)
> bob = sy.VirtualWorker(hook, id='bob')
> 
> x = torch.rand(250, 84) # Synthetic tensor
> x.send(bob)
> x.T
> 
> #Output : "transpose of x"
> ```
> 
> This code works.
> But i don't understand what is your objective here @sssilvar?

Plus, there is an error in what you're doing. You are not capturing the pointer after sending:
```python
x.send(bob)  # Does not capture the pointer (incorrect)
x = x.send(bob)  # Does capture the pointer by replacing x for the pointer (correct)
```

**Comment by LaRiffle** [comment]
Hey! Can you use `x.t()` instead?

**Comment by sssilvar** [comment]
> Hey! Can you use `x.t()` instead?

It works too, yeah. Thanks @LaRiffle 
Although, would be nice to have the behavior fixed for the next minor releases. :+1:

**Comment by Pranay144** [comment]
```python3

import torch
import syft as sy

hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id='bob')

x = torch.rand(250, 84) # Synthetic tensor
transpose_x = x.T

transpose_x.send(bob)

#output : (Wrapper)>[PointerTensor | me:76058087319 -> bob:43056241225]
```
here, this yields pointer.

**Comment by Pranay144** [comment]
> Could you please verify the result is the same? I have tried in three different environments and I get empty tensors when performing the operation `x.T`. Additionally, it does not create a pointer as it should (raising an error when try to `.get()` the tensor from the worker.
> 
> ```python
> x = torch.rand(250,84).send(bob)  # Creates a pointer
> torch.eq(x.T, x.transpose(1,0)).get()  # Raises Error
> ```
> 
> Because I get the following:
> 
> ```python
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-27-b6d586366917> in <module>()
> ----> 1 torch.eq(x.T, x.transpose(1,0)).get().min()
> 
> /usr/local/lib/python3.6/dist-packages/syft/frameworks/torch/tensors/interpreters/native.py in get(self, inplace, user, reason, *args, **kwargs)
>     643 
>     644         # If it is a local tensor/chain, we don't need to verify permissions
> --> 645         if not isinstance(self.child, syft.PointerTensor):
>     646             tensor = self.child.get(*args, **kwargs)
>     647         else:  # Remote tensor/chain
> 
> AttributeError: 'Tensor' object has no attribute 'child'
> ```

Yes , i have verified the results for x.T and x.transpose(1,0) are the same.

**Comment by LaRiffle** [comment]
Great! @sssilvar if you want to take a stab at it it can be a nice good first issue! :)
(basically adding a `def T` property to the pointer tensor that call self.t())

**Comment by Bhuvan-21** [comment]
Is this issue still available?
If not, you may wanna remove Status Available from this.
If available, I want to work on this.

**Comment by sparkingdark** [comment]
@sssilvar if open wanna work

**Comment by xutongye** [comment]
want to work on it.

**Comment by xutongye** [comment]
I found that this issue is not a lonely case, and most of the builtin_properties of Tensor dont work on wrapped tensors, including wrapped PointerTensor, FixedPrecisionTensor, and so on. 
Here are some examples:
```python
t = torch.randint(high=10,size=(2,3)).cuda()
fix_t = t.fix_prec()

print(t)
# tensor([[8, 2, 7],
#         [8, 7, 3]], device='cuda:0')
print(fix_t)
# (Wrapper)>FixedPrecisionTensor>tensor([[8000, 2000, 7000],
#                                        [8000, 7000, 3000]], device='cuda:0')

print(t.dtype)
# torch.int64
print(fix_t.dtype)
# torch.float32

print(t.device)
# cuda:0
print(fix_t.device)
# cpu

print(t.ndim)
# 2
print(fix_t.ndim)
# 1

print(t.T)
# tensor([[8, 8],
#         [2, 7],
#         [7, 3]], device='cuda:0')
print(fix_t.T)
# tensor([])

```
