### ISSUE TITLE
Error while installing PySyft

### ISSUE THREAD

**Issue by dA505819** [OpenMined/PySyft#4628]
## Description
The Error pops up while `pip install syft` in anaconda prompt.

ERROR: Could not find a version that satisfies the requirement torch~=1.4.0 (from syft) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2) ERROR: No matching distribution found for torch~=1.4.0 (from syft)

## Expected Behavior
Installation of the package. All the steps have been followed and worked with progress in order. Only in installation, it showed error.

## System Information
 - OS: [e.g. iOS] Windows 
 - OS Version: [e.g. 22] 10
 - Language Version: [e.g. Python 3.7, Node 10.18.1] Python 3.7
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1] pip
 - Browser (if applicable): [e.g. Google Chrome] Google Chrome
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by Boluwatifeh** [comment]
@dA505819 Are you sure you have pytorch installed on your machine? The error indicates you haven't installed pytorch yet. 

Head over here https://github.com/OpenMined/PySyft/blob/dev/INSTALLATION.md and follow the instructions and you should be good to go

**Comment by Boluwatifeh** [comment]
Or probably your pytorch version is lower than 1.4 . Try upgrading pytorch if that's the case

**Comment by dA505819** [comment]
@Boluwatifeh Yes, PyTorch is installed in the system.

**Comment by dA505819** [comment]
@Boluwatifeh Can you help me in upgrading the PyTorch by sharing a valuable article or video?

**Comment by Boluwatifeh** [comment]
Follow the instructions here https://github.com/OpenMined/PySyft/blob/dev/INSTALLATION.md

**Comment by Boluwatifeh** [comment]
@dA505819 have you resolved the issue?

**Comment by dA505819** [comment]
@Boluwatifeh I will be working on it in 6 hours. 
Will be updating soon.

**Comment by dA505819** [comment]
@Boluwatifeh I have installed a new version of PyTorch. After running this code:
`python setup.py install udacity`

It gives an error like:
`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'udacity'`

**Comment by Boluwatifeh** [comment]
Run this command instead

 python setup.py install

**Comment by dA505819** [comment]
Trying with it now.

**Comment by dA505819** [comment]
@Boluwatifeh 
python setup.py install

`error: Could not find suitable distribution for Requirement.parse('websockets~=8.1.0')`

**Comment by dA505819** [comment]
Following all the procedures, still the error.

**Comment by gmuraru** [comment]
if you try to install websockets with pip install what version it installs?

**Comment by gmuraru** [comment]
@dA505819 ping! :D

**Comment by dA505819** [comment]
@gmuraru I have to check. Please give a day!

**Comment by dA505819** [comment]
@gmuraru It installs websockets version 8.1

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
