### ISSUE TITLE
some questions about add workers

### ISSUE THREAD

**Issue by wlnancy** [OpenMined/PySyft#4629]
## Question
I want to add about 500 workers when using federated learning under the framework. Is there any more effective method to do that? Or I just can add it like the example add Alice and Bob?

## Further Information
Describe your question in greater length here.

**Comment by gmuraru** [comment]
I think you can do a for loop and create the workers? (and keep them in a list)

**Comment by wlnancy** [comment]
But how can I set id?By the way,do you know how to check the data size of each worker owns?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenMined/PySyft"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 下午4:19
收件人:&nbsp;"OpenMined/PySyft"<PySyft@noreply.github.com&gt;;
抄送:&nbsp;"王蕾"<945389942@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenMined/PySyft] some questions about add workers (#4629)





 
I think you can do a for loop and create the workers? (and keep them in a list)

**Comment by wlnancy** [comment]
But how can I set id?By the way,do you know how to check the data size of each worker owns?

**Comment by gmuraru** [comment]
You can set the id like id=f"i" (the index from the loop).
For the second question: you can search for a tag, get a pointer and then call shape on that object

**Comment by wlnancy** [comment]
Thanks, I get it

**Comment by gmuraru** [comment]
Does this solve your problem @wlnancy ? Could we close this issue?

**Comment by wlnancy** [comment]
Yeah, I would close the issue,thanks.
