### ISSUE TITLE
Update Org. contributions on the README

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4630]
Dozens of organizations have been contributing to PySyft development, however only 4 of them are represented on the main page. Although this distinguishes early supporters, it might be time to update the page so that Udacity, CoMind, Arkhn, DropoutLabs (CapePrivacy) can be joined by all the great support we currently have.
A simple item list might be sufficient, i'm not sure we need super fancy logos.

**Comment by Boluwatifeh** [comment]
@LaRiffle what other organisations do we need to add apart from the current four(udacity & co) ? Would love to work on this

**Comment by simcof** [comment]
We will need to get this updated prior to course launch. I'll work to resolve ASAP

**Comment by cereallarceny** [comment]
@simcof Please use this: https://allcontributors.org/
@madhavajay Please remove the stale issue labeler.

**Comment by madhavajay** [comment]
> @simcof Please use this: https://allcontributors.org/
> @madhavajay Please remove the stale issue labeler.

Thats really awesome @cereallarceny I rekon we should add that for sure, but does it also cover things like Organisational contribution / sponsorship credits? I think for this ticket we just need to know what other orgs to give shout-outs 📣 to since the last version README.md.

**Comment by madhavajay** [comment]
@LaRiffle some of these orgs have been added recently. Do you know where we can get a final definitive list of orgs so they can added in one go?
