### ISSUE TITLE
questions about adding local differential privacy  

### ISSUE THREAD

**Issue by wlnancy** [OpenMined/PySyft#4631]
## Question
I want to using some local differential privacy mechanisms during the training process, how can I do that?

**Comment by aanurraj** [comment]
Hi @wlnancy please refer this blog
https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/

**Comment by wlnancy** [comment]
Thanks ,I would try to experiment with the content of the blog

**Comment by wlnancy** [comment]
Hi @aanurraj when I try to download the package opacus, it occurs some troubles. It showed  that no opacus version can satisfied my torch 1.6.0, how can I solve the problem?

**Comment by wlnancy** [comment]
here is my error:
ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from opacus) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.6.0 (from opacus)

**Comment by karthikprasad** [comment]
Hello @aanurraj, @LaRiffle, I ran the code mentioned in the blog on Google Colab and ran into the following issue
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-c04e515dbba4> in <module>()
     40 print("$%%@*E^*@#^@&(#^@*@")
     41 for epoch in range(5):
---> 42     train(epoch, delta=1e-5)

6 frames
/usr/local/lib/python3.6/dist-packages/opacus/per_sample_gradient_clip.py in <genexpr>(.0)
    260             (n, p.grad_sample)  # pyre-ignore[16]
    261             for n, p in self.module.named_parameters()
--> 262             if p.requires_grad
    263         )
    264 

AttributeError: 'Parameter' object has no attribute 'grad_sample'
```

On the first glance, it seems like this is because privacy related attributes are not available to the `local_model` as the privacy engine is not attached to that model.

Could you please verify if the code on the blog still works? If yes, step are we missing?

Thanks.

**Comment by BambooPalace** [comment]
> Hi @wlnancy please refer this blog
> https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/
hi @aanurraj, i have same issue with wlnancy. Have u tried to run the code in this blog? Any ideas on what versions are able to run together? Thanks.
