### ISSUE TITLE
Update Tutorial Part 10 with secure aggregation

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4639]
## Description
We now support secure aggregation , let's update this tutorial!

## How to?
[EDIT: the link to the tutorial was wrong, it's now corrected]
Tutorial https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/ shows how to do federated aggregation
Start  from there and modify the federated aggregation function:
```python
def federated_aggregation(local_model, models):
    with th.no_grad():
        for local_param, *remote_params in zip(*([local_model.parameters()] + [model.parameters() for model in models])):
            param_stack = th.zeros(*remote_params[0].shape)
            for remote_param in remote_params:
                param_stack += remote_param.copy().get()
            param_stack /= len(remote_params)
            local_param.set_(param_stack)
```
To be
```python
def secure_aggregation(local_model, models):
    with torch.no_grad():
        for local_param, *remote_params in zip(*([local_model.parameters()] + [model.parameters() for model in models])):
            param_stack = remote_params[0].copy().fix_prec(precision_fractional=8).share(alice, bob, crypto_provider=james).get()
            for remote_param in remote_params[1:]:
                param_stack += remote_param.copy().fix_prec(precision_fractional=8).share(alice, bob, crypto_provider=james).get()
            param_stack = param_stack.get().float_prec()
            param_stack /= len(remote_params)
            local_param.set_(param_stack)
```

**Comment by LaRiffle** [comment]
not necessarily, there might be stuff to adapt, but give it a try! :)

**Comment by Bhuvan-21** [comment]
Okay, I will try to get it done.

**Comment by aksh-02** [comment]
@LaRiffle I would like to give it a try too.

**Comment by LaRiffle** [comment]
Sure! Please ping me on slack @Théo Ryffel whenever the PRs are ready :) 
@aksh-02 @Bhuvan-21

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
