### ISSUE TITLE
ERROR ImportError while loading conftest

### ISSUE THREAD

**Issue by SSSuperTIan** [OpenMined/PySyft#4651]
## Description
A clear and concise description of the bug.
When i follow the INSTALLATION.md in pycharm of win10, i wanna to run python setup.py test in CMD.
But always occur this ERROR.
How to fix it?Lots of thx!!!!!!!!
.
.
.
.
.
.
.
.

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\pathspec-0
.8.0-py3.7.egg
Searching for regex>=2020.1.8
Best match: regex 2020.10.11
Processing regex-2020.10.11-py3.7-win-amd64.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\regex-2020
.10.11-py3.7-win-amd64.egg
Searching for typed-ast>=1.4.0
Best match: typed-ast 1.4.1
Processing typed_ast-1.4.1-py3.7-win-amd64.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\typed_ast-
1.4.1-py3.7-win-amd64.egg
Searching for appdirs
Best match: appdirs 1.4.4
Processing appdirs-1.4.4-py3.7.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\appdirs-1.
4.4-py3.7.egg
Searching for textwrap3>=0.9.2
Best match: textwrap3 0.9.2
Processing textwrap3-0.9.2-py3.7.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\textwrap3-
0.9.2-py3.7.egg
Searching for pyflakes<2.3.0,>=2.2.0
Best match: pyflakes 2.2.0
Processing pyflakes-2.2.0-py3.7.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\pyflakes-2
.2.0-py3.7.egg
Searching for pycodestyle<2.7.0,>=2.6.0a1
Best match: pycodestyle 2.6.0
Processing pycodestyle-2.6.0-py3.7.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\pycodestyl
e-2.6.0-py3.7.egg
Searching for mccabe<0.7.0,>=0.6.0
Best match: mccabe 0.6.1
Processing mccabe-0.6.1-py3.7.egg

Using d:\program files (x86)\onedrive - mail.dhu.edu.cn\dhu\lab\self-talk\ex\just for fun\pysyft-master\.eggs\mccabe-0.6
.1-py3.7.egg
running egg_info
writing syft.egg-info\PKG-INFO
writing dependency_links to syft.egg-info\dependency_links.txt
writing requirements to syft.egg-info\requires.txt
writing top-level names to syft.egg-info\top_level.txt
reading manifest file 'syft.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'syft.egg-info\SOURCES.txt'
running build_ext
Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorF
low. Fix this by compiling custom ops. Missing file was 'D:\Anaconda3\envs\pysyft\lib\site-packages\tf_encrypted/operati
ons/secure_random/secure_random_module_tf_1.15.4.so'
WARNING:tensorflow:From D:\Anaconda3\envs\pysyft\lib\site-packages\tf_encrypted\session.py:24: The name tf.Session is de
precated. Please use tf.compat.v1.Session instead.

**ImportError while loading conftest 'D:\Program Files (x86)\OneDrive - mail.dhu.edu.cn\DHU\lab\self-talk\Ex\just for fun\
PySyft-master\test\conftest.py'.**
D:\Anaconda3\envs\pysyft\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary
incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Anaconda3\envs\pysyft\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary
incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Anaconda3\envs\pysyft\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary
incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Anaconda3\envs\pysyft\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary
incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
test\conftest.py:12: in <module>
    import syft
syft\__init__.py:14: in <module>
    import syft.frameworks.torch.hook.hook_args
syft\frameworks\torch\hook\hook_args.py:4: in <module>
    from syft.frameworks.torch.tensors.interpreters.native import TorchTensor
syft\frameworks\torch\tensors\interpreters\native.py:6: in <module>
    from syft.frameworks.torch.tensors.interpreters.precision import FixedPrecisionTensor
syft\frameworks\torch\tensors\interpreters\precision.py:5: in <module>
    from syft.frameworks.torch.tensors.interpreters.replicated_shared import ReplicatedSharingTensor
syft\frameworks\torch\tensors\interpreters\replicated_shared.py:3: in <module>
    from syft.generic.frameworks.hook import hook_args
syft\generic\frameworks\__init__.py:1: in <module>
    from syft.generic.frameworks.types import framework_packages  # noqa: F401
syft\generic\frameworks\types.py:39: in <module>
    import crypten
D:\Anaconda3\envs\pysyft\lib\site-packages\crypten\__init__.py:8: in <module>
    import crypten.communicator as comm
D:\Anaconda3\envs\pysyft\lib\site-packages\crypten\communicator\__init__.py:9: in <module>
    from .distributed_communicator import DistributedCommunicator
D:\Anaconda3\envs\pysyft\lib\site-packages\crypten\communicator\distributed_communicator.py:15: in <module>
    from torch.distributed import ReduceOp
D:\Anaconda3\envs\pysyft\lib\site-packages\crypten\communicator\distributed_communicator.py:15: in <module>
    from torch.distributed import ReduceOp
**E   ImportError: cannot import name 'ReduceOp' from 'torch.distributed' (D:\Anaconda3\envs\pysyft\lib\site-packages\tor
ch\distributed\__init__.py)**

**Comment by LaRiffle** [comment]
Hey ! this is a crypten error
Maybe related to https://github.com/SsnL/dataset-distillation/issues/12
please check the crypten repo for more details :) 
https://github.com/facebookresearch/CrypTen

**Comment by gmuraru** [comment]
The issue I think is that CrypTen is supported only on Windows. You might get away with it by removing crypten from the requirements file.
