### ISSUE TITLE
Is it possible to have Federated Learning on Cloud-Edge?

### ISSUE THREAD

**Issue by Martiniann** [OpenMined/PySyft#4652]
Hi everyone,
 
Currently I am working on a school project about federated learning and came across your framework during exploratory analysis. My project should utilize federated learning in this manner - I have an aggregation server (let's say in a cloud). I want this server to provide model to my 2 Raspberry PIs. These two RPIs would then train the model on a local data for x epochs and provide the trained models/gradients back to the global server. On this server, the results would be federated averaged and new model would  be sent to the PIs. Is such a workflow possible with your framework? If so, could you provide me a hint?
 
Thank you,
Best regards

**Comment by gmuraru** [comment]
Hello!

There was a blogpost about training on Raspi: https://blog.openmined.org/federated-learning-of-a-rnn-on-raspberry-pis/

**Comment by gmuraru** [comment]
hey @Martiniann.

Can this issue be closed?

**Comment by Martiniann** [comment]
Yes thank you for your feedback.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

pi 6. 11. 2020 o 18:55 George-Cristian Muraru <notifications@github.com>
napísal(a):
