### ISSUE TITLE
Add support for Continuous Benchmark action

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/PySyft#4654]
## Feature Description
Since performance is important. Writing benchmarks is a popular and correct way to visualize a software performance. Benchmarks help us to keep performance and to confirm the effects of optimizations. For keeping the performance, it's important to monitor the benchmark results along with changes to the software. To notice performance regression quickly, it's useful to monitor benchmarking results continuously. [GitHub Action Continuous Benchmark](https://github.com/marketplace/actions/continuous-benchmark#why)

## Is your feature request related to a problem?
We have recently added this feature in syft_0.2.9 (currently for mpc) as asked by @tudorcebere we need to extend this for syft_0.3.0

## Additional Context
A demo implementation can be found [here](https://github.com/aanurraj/pytest-benchmark-demo) with graphic charts [here](https://aanurraj.github.io/pytest-benchmark-demo/dev/bench/)

**Comment by gmuraru** [comment]
@aanurraj wasn't this done (also in syft_0.3.0)?

**Comment by aanurraj** [comment]
> @aanurraj wasn't this done (also in syft_0.3.0)?

No Tudor said he will come up with a plan, I am waiting for it.

**Comment by madhavajay** [comment]
Related: https://github.com/OpenMined/PySyft/issues/4757

**Comment by madhavajay** [comment]
I think as soon as we have this in place with the new GitHub Benchmark system we should create a benchmark test for Serde / transport of tensors between Duet nodes and then rebase this PR and see what the difference is: https://github.com/OpenMined/PySyft/pull/4807
