### ISSUE TITLE
Federated Learning examples give "RuntimeError: Websocket connection closed and creation of new connection failed." error when using Websocket client workers.

### ISSUE THREAD

**Issue by sug4ndh** [OpenMined/PySyft#4656]
## Description

I am following PySyft tutorials and I keep getting "RuntimeError: Websocket connection closed and creation of new connection failed." error when I use remote workers through websockets instead of VirtualWorkers. I have 2 vms running which act as Websocket client worker and a third vm where I run jupyter notebooks. I start the websocket server on the vms using run_websocket_server.py. Whenever I try to train a model in a notebook for Federated learning, for e.g. Federated learning with websockets and federated averaging.ipynb or Federated Recurrent Neural Network.ipynb, I get "RuntimeError: Websocket connection closed and creation of new connection failed." error. The full error in the notebook is as follows:
 ```
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-dec9889208dd> in <module>
      1 for epoch in range(1, args.epochs + 1):
      2     print("Starting epoch {}/{}".format(epoch, args.epochs))
----> 3     model = rwc.train(model, device, federated_train_loader, args.lr, args.federate_after_n_batches)
      4     rwc.test(model, device, test_loader)
~/PySyft/examples/tutorials/advanced/websockets_mnist/run_websocket_client.py in train(model, device, federated_train_loader, lr, federate_after_n_batches, abort_after_one)
    134             if curr_batches:
    135                 models[worker], loss_values[worker] = train_on_batches(
--> 136                     worker, curr_batches, model, device, lr
    137                 )
    138             else:
~/PySyft/examples/tutorials/advanced/websockets_mnist/run_websocket_client.py in train_on_batches(worker, batches, model_in, device, lr)
     68         optimizer.step()
     69         if batch_idx % LOG_INTERVAL == 0:
---> 70             loss = loss.get()  # <-- NEW: get the loss back
     71             loss_local = True
     72             logger.debug(
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py in get(self, inplace, user, reason, *args, **kwargs)
    646             tensor = self.child.get(*args, **kwargs)
    647         else:  # Remote tensor/chain
--> 648             tensor = self.child.get(*args, user=user, reason=reason, **kwargs)
    649 
    650         # Clean the wrapper
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/pointers/pointer_tensor.py in get(self, user, reason, deregister_ptr)
    324             object used to point to #on a remote machine.
    325         """
--> 326         tensor = ObjectPointer.get(self, user=user, reason=reason, deregister_ptr=deregister_ptr)
    327 
    328         # TODO: remove these 3 lines
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/generic/pointers/object_pointer.py in get(self, user, reason, deregister_ptr)
    267         else:
    268             # get tensor from location
--> 269             obj = self.owner.request_obj(self.id_at_location, self.location, user, reason)
    270 
    271         # Remove this pointer by default
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py in request_obj(self, obj_id, location, user, reason)
    603             A torch Tensor or Variable object.
    604         """
--> 605         obj = self.send_msg(ObjectRequestMessage(obj_id, user, reason), location)
    606         return obj
    607 
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py in send_msg(self, message, location)
    314 
    315         # Step 2: send the message and wait for a response
--> 316         bin_response = self._send_msg(bin_message, location)
    317 
    318         # Step 3: deserialize the response
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/virtual.py in _send_msg(self, message, location)
     10         """send message to worker location"""
     11 
---> 12         return location._recv_msg(message)
     13 
     14     def _recv_msg(self, message: bin) -> bin:
~/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/websocket_client.py in _recv_msg(self, message)
    115             if not self.ws.connected:
    116                 raise RuntimeError(
--> 117                     "Websocket connection closed and creation of new connection failed."
    118                 )
    119         return response
RuntimeError: Websocket connection closed and creation of new connection failed.
```

The trace on one of the worker vm is below:
```
2020-10-16 13:44:20,707 ERROR base_events.py(l:1619, p:2157) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /home/sug/PySyft/syft/workers/websocket_server.py:93> exception=IndexError('tuple index out of range')>
Traceback (most recent call last):
  File "/home/sug/PySyft/syft/workers/websocket_server.py", line 111, in _producer_handler
    response = self._recv_msg(message)
  File "/home/sug/PySyft/syft/workers/websocket_server.py", line 122, in _recv_msg
    return self.recv_msg(message)
  File "/home/sug/PySyft/syft/workers/base.py", line 338, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/home/sug/PySyft/syft/serde/serde.py", line 78, in deserialize
    return strategy(binary, worker)
  File "/home/sug/PySyft/syft/serde/msgpack/serde.py", line 383, in deserialize
    return _deserialize_msgpack_simple(simple_objects, worker)
  File "/home/sug/PySyft/syft/serde/msgpack/serde.py", line 374, in _deserialize_msgpack_simple
    return _detail(worker, simple_objects)
  File "/home/sug/PySyft/syft/serde/msgpack/serde.py", line 517, in _detail
    val = msgpack_global_state.detailers[obj[0]](worker, obj[1], **kwargs)
  File "/home/sug/PySyft/syft/messaging/message.py", line 385, in detail
    sy.serde.msgpack.serde._detail(worker, msg_tuple[3]),
IndexError: tuple index out of range
2020-10-16 13:44:20,941 ERROR base_events.py(l:1619, p:2157) - Task exception was never retrieved
future: <Task finished coro=<WebsocketServerWorker._producer_handler() done, defined at /home/sug/PySyft/syft/workers/websocket_server.py:93> exception=IndexError('tuple index out of range')>
Traceback (most recent call last):
  File "/home/sug/PySyft/syft/workers/websocket_server.py", line 111, in _producer_handler
    response = self._recv_msg(message)
  File "/home/sug/PySyft/syft/workers/websocket_server.py", line 122, in _recv_msg
    return self.recv_msg(message)
  File "/home/sug/PySyft/syft/workers/base.py", line 338, in recv_msg
    msg = sy.serde.deserialize(bin_message, worker=self)
  File "/home/sug/PySyft/syft/serde/serde.py", line 78, in deserialize
    return strategy(binary, worker)
  File "/home/sug/PySyft/syft/serde/msgpack/serde.py", line 383, in deserialize
    return _deserialize_msgpack_simple(simple_objects, worker)
  File "/home/sug/PySyft/syft/serde/msgpack/serde.py", line 374, in _deserialize_msgpack_simple
    return _detail(worker, simple_objects)
  File "/home/sug/PySyft/syft/serde/msgpack/serde.py", line 517, in _detail
    val = msgpack_global_state.detailers[obj[0]](worker, obj[1], **kwargs)
  File "/home/sug/PySyft/syft/messaging/message.py", line 385, in detail
    sy.serde.msgpack.serde._detail(worker, msg_tuple[3]),
IndexError: tuple index out of range
```

I have found some old issues here from folks had similar problem but the issues are either stale now or no solution has been posted yet!

Any help is really appreciated!

Thanks!  

## How to Reproduce
1. Create 3 systems/vms with access to each other.
2. Follow the instructions on PySyfts gtihub page to install pySyft, pyTorch on all three systems:
```
conda create -n pysyft python=3.7
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook==5.7.8 tornado==4.5
conda activate pysyft
pip install 'syft[udacity]'
```
3. Clone PySyft github repo on all 3 systems
4. On the 2 systems acting as websocket workers, execute:
cd PySyft; python3 run_websocket_server.py --host "host-ip" --port "port-number" --id "replace-with-name"
5. 
    a) On the 3rd system, change directories to go to the tutorial subdir inside PySyft.
    b) Run jupyter notebook 
    c) Open Federated Recurrent Neural Network.ipynb or  Federated learning with websockets and federated averaging.ipynb 
    d) Replace the following lines
```
              hook = sy.TorchHook(torch)  # <-- NEW: hook PyTorch ie add extra
              alice = sy.VirtualWorker(hook, id="alice")  
              bob = sy.VirtualWorker(hook, id="bob")  
              # charlie = sy.VirtualWorker(hook, id="charlie") 
              workers_virtual = [alice, bob]
``` 
         with these and execute the notebook:
 
```
             hook = sy.TorchHook(torch)  # <-- NEW: hook PyTorch ie add extra
             kwargs_websocket_alice = {"host": "ip_alice", "hook": hook}
             alice = WebsocketClientWorker(id="alice", port=8777, **kwargs_websocket_alice)
             kwargs_websocket_bob = {"host": "ip_bob", "hook": hook}
             bob = WebsocketClientWorker(id="bob", port=8778, **kwargs_websocket_bob)
             workers_virtual = [alice, bob] 
```

 
## Expected Behavior
The notebook should run without giving any errors.

## System Information
 - OS: Ubuntu 
 - OS Version: 18.04
 - Language Version: Python 3.7
 - Package Manager Version:  Conda 4.8.3
 - Browser (if applicable): Firefox for jupyter notebook
 - Browser Version (if applicable): 81.02

## Additional Context
I have also tried to run the above scenario with python-3.6.7 but I still get the same error.

**Comment by gmuraru** [comment]
@IonesioJunior any idea?

**Comment by DanyEle** [comment]
Hi, just wondering. Do you get this error also when replacing the Web Workers with local "dummy" Virtual Workers? 


FYI: The PySyft version I was using in the tutorial linked https://blog.openmined.org/federated-learning-of-a-rnn-on-raspberry-pis/, I was using version v0.1.19A1

**Comment by DanyEle** [comment]
> Hi @DanyEle, no, with virtualworkers most of the stuff runs as expected. The problem starts to occur when PySyft is being used in a pseudo realistic/realistic setup.

Yeah, that's indeed the problem I noticed as well... I will try to see if I managed replace the problem on my end with this example. Are you sure you're using exactly the same PySyft build version on both web workers? Did you try not to use conda, and building PySyft from source instead?

**Comment by sug4ndh** [comment]
> Yeah, that's indeed the problem I noticed as well... I will try to see if I managed replicate the problem on my end with this example. Are you sure you're using exactly the same PySyft build version on both web workers? Did you try not to use conda, and building PySyft from source instead?

I am not using v1.19a1 or rather I can't. When I search for tagged releases, I get results from hydrogen and onwards, there is no v1.19a1. I did use hydrogen release though and made sure that all my systems were using the same version but that did not help either. I did not try to build it from source. I might give that a shot!

**Comment by DanyEle** [comment]
Yeah, between August 2019 and 2017 there  don't seem to be any versions tracked. The most similar version could be: 0.1.23a though https://github.com/OpenMined/PySyft/releases/tag/0.1.23a

**Comment by sug4ndh** [comment]
Ah okay, I dont think I tried that version. I will try and see if it works. But I guess folks over at slack are recommending to use grid now.

**Comment by DanyEle** [comment]
So, I just cloned the latest version of PySyft and ran it all locally on an Ubuntu Virtual Machine from my local Windows. I then proceeded to start the websockets locally, and ran the example "Federated Recurrent Neural Network".

Everything went well, and the training went just fine. I suppose the problem you mentioned may arise when working with distributed machines instead of local ones? That's kinda weird though: from my experience, if something worked on local websockets, it worked on remote websockets just as well. 

![image](https://user-images.githubusercontent.com/4907418/96837052-1b1bb900-1446-11eb-941d-16480933e3d7.png)

**Comment by DanyEle** [comment]
I'm going to open a Pull Request with the new changes shortly

**Comment by sug4ndh** [comment]
> I suppose the problem you mentioned may arise when working with distributed machines instead of local ones?

Yeah, I believe so as well. With virtual workers things are working pretty much as expected.

**Comment by DanyEle** [comment]
Once PR #4697 gets approved and merged, could you please try and see if the issue got resolved for websockets as well?

**Comment by sug4ndh** [comment]
Sure!

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.

**Comment by Rateofteasing** [comment]
same questions
