### ISSUE TITLE
Unable to host model for Model Centric FL when using manually started grid network

### ISSUE THREAD

**Issue by sug4ndh** [OpenMined/PySyft#4657]
## Description
I have manually started PyGrid network using:
`./run.sh --port 7000 --start_local_db`

I am also using Part 01 - Create Plan.ipynb notebook and I am unable to send model to the network for hosting when I execute the following:
```
response = grid.host_federated_training(
    model=model_params_state,
    client_plans={'training_plan': training_plan},
    client_protocols={},
    server_averaging_plan=avg_plan,
    client_config=client_config,
    server_config=server_config
)
print("Host response:", response) 
```

The error that I get in the notebook states:
`Host response: {'status': 'error', 'message': 'Invalid request format!'}
`
However, on the server running grid network, I get 
`Message:  {'type': 'model-centric/host-training', 'data': {'model': 'XXXX`, 'plans': {'training_plan': 'XXXX'},  'protocols': {}, 'averaging_plan': 'XXXX', 'client_config': {'name': 'mnist', 'version': '1.0.0', 'batch_size': 64, 'lr': 0.005, 'max_updates': 100}, 'server_config': {'min_workers': 5, 'max_workers': 5, 'pool_selection': 'random', 'do_not_reuse_workers_until_cycle': 6, 'cycle_length': 28800, 'num_cycles': 5, 'max_diffs': 1, 'minimum_upload_speed': 0, 'minimum_download_speed': 0, 'iterative_plan': True}}}

## How to Reproduce
1. Start the Grid network manually using `./run.sh --port 7000 --start_local_db`
2. Run 'Part - 01 - Create Plan.ipynb' inside model centric tutorials
3. Error will occur in code cell 17 containing:
```
response = grid.host_federated_training(
    model=model_params_state,
    client_plans={'training_plan': training_plan},
    client_protocols={},
    server_averaging_plan=avg_plan,
    client_config=client_config,
    server_config=server_config
)
print("Host response:", response) 
```
4. See error - Host response: {'status': 'error', 'message': 'Invalid request format!'}

## Expected Behavior
Status : success  

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.7
 - Package Manager Version: Conda 4.8.3, Poetry 1.1.3
 - Browser (if applicable): Firefox
 - Browser Version (if applicable): 81.0.2

## Additional Context
It does not matter if the grid network is running on a different system or on the same system running Jupyter notebook, same thing happens.

**Comment by gmuraru** [comment]
@IonesioJunior ^^ if you have any idea

**Comment by sug4ndh** [comment]
Got it to work, I was using Network instead of Node app from PyGrid. Thanks @gmuraru anyway!

**Comment by gmuraru** [comment]
Great!
