### ISSUE TITLE
Add Blocking Permission Request to MNIST demo

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4661]
## Feature Description
To allow access to metrics during training or testing, we require permissions.
We need to implement an intentional blocking pause while permissions are requested so that the iteration doesn't fail or overload the remote system with requests.

If the remote party denies the request (possibly by accident) we should try to make this easy to recover rather than destroying the whole training loop state.

This is related to this ticket:
https://github.com/OpenMined/PySyft/issues/4660

## Definition of Done
The training / test loops should be runnable and block on permission requests. The Duet partner should be able to approve these requests and training / testing should continue. Rejection should not break the state of the loop allowing it to be re-requested.

**Comment by gmuraru** [comment]
This should not be dependent on the MNIST, because you can test it without it

**Comment by iamtrask** [comment]
Good point - progress could start before MNIST is done.

**Comment by madhavajay** [comment]
One suggestion for the API could be:
```
ptr.request(blocking=True)
or
ptr.request(block=True)
```

**Comment by madhavajay** [comment]
https://github.com/OpenMined/PySyft/pull/4722

**Comment by madhavajay** [comment]
https://github.com/OpenMined/PySyft/pull/4696/commits
