### ISSUE TITLE
Move TODOs to Issues

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4663]
## Goal
Before Beta launch we will remove any outstanding TODOs or QUESTIONs from the source code and move them into issues.

## Definition of Done
Searching the code should return 0 results for TODO or QUESTION

**Comment by tudorcebere** [comment]
This is coming to town this week.

**Comment by madhavajay** [comment]
@tudorcebere I created this too: https://github.com/OpenMined/PySyft/issues/5054
