### ISSUE TITLE
Prune unused old branches

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4666]
## What?
List all branches by user name.
Post the list in Core teams and ask to delete old unused branches.
Confirm any unused branches and delete them.
*Leave Trasks branches*

## Why?
To reduce the clutter of unused branches that were never PR / Merged.

## Definition of Done
There are no longer any dead branches for the milestone.
Moving forward all branches are deleted on merge, and people are encouraged to create branches on their own fork and PR from there.

**Comment by rasswanth-s** [comment]
The branches were pruned, two months back for a demo, 
Currently we have only the active branches.

Hence closing the issue
