### ISSUE TITLE
Introduce Logging Library

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4667]
## Description
Introduce a logging library like this:
https://github.com/Delgan/loguru

We want to to introduce a logging system so we can have meaningful messages while debugging without flooding users screens with too much verbose information.

The first goal should be to replace sy.VERBOSE and have a default setting of verbose off. Logging should be easy to configure a default level decided and set for testing as well.

If possible any existing syft library print statements or exceptions can be updated to include the new logging system.

By default we should log errors and exceptions only.

For our demos we should have logging off, but include a line of code to show it can be turned on.

## Definition of Done
- sy.VERBOSE is replaced and all references to it have been updated.
- logging levels are introduced for our pretty printing vs other types of messages
- Exceptions are logged

**Comment by ViveK-PothinA** [comment]
If this is open, I would like to work on it. I'll try to integrate with loguru.

**Comment by madhavajay** [comment]
@ViveK-PothinA, sorry I needed this done because of some errors we are trying to track down so I went ahead and implemented it.

https://github.com/OpenMined/PySyft/pull/4748
