### ISSUE TITLE
Update 0.3 README.md

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4668]
## Description
Take the README.md from main branch and update it to reflect changes for 0.3.
Add CI badges for 0.3 branch

## Definition of Done
Reading the README.md should make sense and look up to date with the goals and features of 0.3.
There should be no spelling mistakes or obvious formatting issues.

**Comment by HarshCasper** [comment]
Hello @madhavajay

I would like to work on this issue if it is still open. This would be my first contribution towards OpenMined, and I would like to take it up and complete it as soon as possible for me.

Also, I would like a bit of further clarity on this issue so I would ping you up on Slack for the purpose.
