### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4669]
## Description
The contribution guide should be updated to include sufficient instruction that someone can take an issue and work on it.

## Definition of Done
Find someone who can run through the guide and give their FIRST contribution to Syft and take any notes of issues or confusion with the process and fix them.

This should have clear instruction for LMW 🐧 🍏 💠 (Linux Mac and Windows).

**Comment by AkashM398** [comment]
Shall I take over it?

**Comment by madhavajay** [comment]
@AkashM398 Yes please.

**Comment by madhavajay** [comment]
Sorry, I think I forgot the 0.3 label on this task... 😬

**Comment by madhavajay** [comment]
Current CONTRIBUTING.md here: https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md
