### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4670]
## Description
Run a code level spell check across the entire code base, correcting issues in documentation and code where it makes sense.

## Language
The default language will be US English unless otherwise agreed upon.

**Comment by Harkirat155** [comment]
I'll take it.

**Comment by AkashM398** [comment]
Is this still open? I'll take over it

**Comment by gmuraru** [comment]
You can both work on it - maybe coordinate such that one takes some files and the other person takes some other files (you can always use the OpenMined slack for that :D )

**Comment by madhavajay** [comment]
@AkashM398 Yes please. 👍
