### ISSUE TITLE
Fix broken float tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4671]
## Description
There are two tests marked `@pytest.mark.xfail` in id_test.py which need to be fixed.

## How to Reproduce
Remove the annotations marked `@pytest.mark.xfail` then run the fast tests:
```
$ pytest -m fast
```

## Expected Behavior
Tests should pass

## Definition of Done
PR should be posted with passing test suite and `@pytest.mark.xfail` annotations removed.
If there is a good reason these tests cannot pass that should be documented and then explained here.

**Comment by rajathpatel23** [comment]
Can I work on this? @madhavajay

**Comment by gmuraru** [comment]
Sure @rajathpatel23. Assigned it to you :+1:

**Comment by gmuraru** [comment]
It is the ```syft_0.3.0``` branch

**Comment by rajathpatel23** [comment]
Thank you @gmuraru

**Comment by madhavajay** [comment]
@rajathpatel23 Yes, this is for 0.3 but contributions are welcome. If you checkout syft_0.3.0 and then branch from there and make this change that would be amazing. Just a note, the "slow" tests are currently failing on the 0.3.0 branch which i am fixing now in another PR, so don't be surprised if that happens. This task only applies to the fast tests.

Also this might not be the easiest task for starting on the 0.3 code base, so sorry if I labelled it that way, its hard to know if the work has been done yet or it's just still left off. Feel free to try or if you don't want to thats also okay. 😊

If you have any questions just write them here or ping me on slack and I can try to help.

**Comment by rajathpatel23** [comment]
@madhavajay , cool I would like to give it a try for next couple of days, if I do not make progress we can handover it to someone, does that work ?

**Comment by rajathpatel23** [comment]
@madhavajay I was not able to make progress on this, we can assign it somone.
