### ISSUE TITLE
Tutorial Part 11 - Secure Deep Learning Classification runs into a EmptyCryptoPrimitiveStoreError 

### ISSUE THREAD

**Issue by Bhuvan-21** [OpenMined/PySyft#4673]
## Description
Tutorial [Part 11 - Secure Deep Learning Classification](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2011%20-%20Secure%20Deep%20Learning%20Classification.ipynb) runs into an EmptyCryptoPrimitiveStoreError.

## How to Reproduce
Just running the tutorial as it is produces this error.

## Screenshots
![image](https://user-images.githubusercontent.com/51778760/96413765-bd9b2880-1209-11eb-9677-b89f99f0ac59.png)

## System Information
syft version 0.2.5
torch version 1.4.0

**Comment by gmuraru** [comment]
Thank you for opening this!

**Comment by aanurraj** [comment]
Hi @Bhuvan-21 just checked this notebook, runs perfectly on my machine. Please upgrade to the latest syft master, I am sure it will no longer throw this error.

**Comment by gmuraru** [comment]
@Bhuvan-21 is this problem still showing up?

**Comment by aanurraj** [comment]
Closing! Unable to get output from the author.
