### ISSUE TITLE
Add Word-level language modeling RNN Wikitext-2 Example

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4680]
## Description
Add two notebook's which reflect the Wikitext example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/tree/master/word_language_model

Subclasses of module.nn and custom corpus and dictionary code will likely need to be on the DO (Data Owner) side.

## Definition of Done
The partially runnable Wikitext notebook should be in the examples/pytorch/wikitext folder and a README.md should be added in the parent examples/pytorch directory with a link to the original example and our notebook.

**Comment by DanyEle** [comment]
Would be very interesting to have in PySyft indeed

**Comment by gmuraru** [comment]
Heads-up - this is for pysyft0.3.0 version

**Comment by AlanAboudib** [comment]
@madhavajay Anyone is working on this currently? 
I see it has a critical status, should it be completed before November 11th?

**Comment by AlanAboudib** [comment]
@madhavajay I am taking this one

**Comment by ydennisy** [comment]
hey @AlanAboudib do you have an ETA planned for this?

**Comment by madhavajay** [comment]
@ydennisy there are some other blockers preventing @AlanAboudib  from finishing this notebook. As soon as they are resolved we will get this notebook merged.
