### ISSUE TITLE
Finish Simple Tensor allowlist methods

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4683]
## Description
Finish all the methods which were from the old tests and create tickets for all the remaining non trivial ones.

## Definition of Done
The PR is ready to merge since the functionality is on par with the main syft_0.3.0 branch.
The more difficult methods are listed under a different heading in the allowlist file with some hint as to the issue.
Tickets have been created for each of them.
Old tickets for the other methods are cleaned up.
Update this ticket as well to reflect the latest state of progress: https://github.com/OpenMined/PySyft/issues/3696

**Comment by gmuraru** [comment]
Assigning this to you @madhavajay only to keep track who is working on what.
