### ISSUE TITLE
Garbage Collection Bug

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4684]
## Feature Description
Pointers to data that are no longer used should send a "DeleteObject" message to the data owner such that they can remove the data from the store - GC on pointers.

## Is your feature request related to a problem?
Doing computation with remote data (and not having a gc) will put a big constraint on the memory from the "Data Owner" side - until the point that they would not be able to serve any more requests.

**Comment by gmuraru** [comment]
The GC is already in the syft_0.3.0 branch.

This ticket addresses the problem when we do
```
ptr = x.send(alice)
ptr = x.send(alice)
```

**Comment by madhavajay** [comment]
Related PR: https://github.com/OpenMined/PySyft/pull/4674
