### ISSUE TITLE
PyGrid WebRTC Docker Example

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4690]
## Description
Create a simple PyGrid WebRTC broker as a docker container which can be easily ran locally on a users machine to broker their own Duet session.

## Definition of Done
Dockerfile and README.md explaining how to use this are in the repo and linked from the main README.md.

**Comment by IonesioJunior** [comment]
Can I work on it?

**Comment by madhavajay** [comment]
This is superseded by the upcoming PyGrid end-to-end test.
