### ISSUE TITLE
Add Parameter Tests to new Test Suite

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4694]
## Description
Add Parameter tests to the new Tensor AllowList test suite

## Definition of Done
Parameter tensors are created as well to test all of the tensor methods on its subclass parameter.
Tests all pass.

**Comment by vvmnnnkv** [comment]
Hmm, do you mean something like in #4707?

**Comment by madhavajay** [comment]
@vvmnnnkv I think you are correct here, we definitely don't want the tests to be 2x slower, and the fact that its passing the whole version matrix is a good sign that we can probably leave this off for now. Previously we had separate tests that shared mostly the same code but by having a single test this allows us to be much more confident they perform identically as expected.

**Comment by madhavajay** [comment]
PR is here for future reference: https://github.com/OpenMined/PySyft/pull/4707
