### ISSUE TITLE
ERROR installing syft with pip install syft on linux

### ISSUE THREAD

**Issue by Boluwatifeh** [OpenMined/PySyft#4706]
## Description
i tried installing syft via pip with 'pip install syft' command and "pip install 'syft[udacity]' "

## How to Reproduce
1. I followed the steps on the pre-installation section of  the pysyft repo
2. pytorch version ==1.4.0
3. after running pip install syft i got these error in the screenshots

## Screenshots
![Screenshot 2020-10-24 at 11 39 32 PM](https://user-images.githubusercontent.com/39227096/97095153-debda800-1653-11eb-9845-2d906f2de773.png)
![Screenshot 2020-10-24 at 11 39 13 PM](https://user-images.githubusercontent.com/39227096/97095156-e1b89880-1653-11eb-9729-a4b94b6303e2.png)

## System Information
 - OS: Linux(chromebook)
 - Language Version: [e.g. Python 3.8.5,]
 - Package Manager Version: [e.g. Conda 4.6.1]

## Additional Context
error log:
Running setup.py install for netifaces ... error
    ERROR: Command errored out with exit status 1:
     command: /home/tifeasypeasy/opt/miniconda3/envs/my_syft/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8f4hbpb4/netifaces/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8f4hbpb4/netifaces/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ffuxctmc/install-record.txt --single-version-externally-managed --compile --install-headers /home/tifeasypeasy/opt/miniconda3/envs/my_syft/include/python3.8/netifaces

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I’ll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I’ll reopen the issue.
