### ISSUE TITLE
Implement the Neural Style Transfer Duet Notebooks

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4718]
## Description
Add two notebook's which reflect the Neural Style Transfer example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/tree/master/fast_neural_style

- Download scripts from download_saved_models.py might need to be modified to suit the DO / DS split.
- Code like Namedtuple can be refactored if needed
- Libraries like PIL and image saving should be avoided across the Duet boundary where possible

## Definition of Done
The partially runnable Neural Style Transfer notebook should be in the examples/pytorch/fast_neural_style folder and a README.md should be added in the parent examples/pytorch directory with a link to the original example and our notebook.

**Comment by srinath1412001** [comment]
@madhavajay 
Can I try this? 
I'm a little busy next week but I will try to make it in my free time.

**Comment by srinath1412001** [comment]
@madhavajay 
Can I try this?
