### ISSUE TITLE
Variational Auto-Encoders Duet Notebooks

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4719]
## Description
Add two notebook's which reflect the VAE example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/tree/master/vae

## Definition of Done
The partially runnable VAE notebook should be in the examples/pytorch/vae folder and a README.md should be added in the parent examples/pytorch directory with a link to the original example and our notebook.

**Comment by ayush12gupta** [comment]
I am new to this library and have gone through all the tutorial I aim to contribute to this library. Can I try this issue and can you please clarify what you mean by  "which reflect the VAE example split into DO (Data Owner) and DS (Data Scientist)"
