### ISSUE TITLE
Add nn.Sequential

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4721]
## Description
Add nn.Sequential and some examples of using it to define a model on DS and executing on DO side.

A good place to test this would be on the MNIST Duet notebooks as the network should be simple enough to be defined with nn.Sequential and the result should be much faster training which is a current bottleneck.

## Definition of Done
Notebook example demonstrating working nn.Sequential training from DS to DO side.

**Comment by tudorcebere** [comment]
This got solved.
