### ISSUE TITLE
Add duet.openmined.org

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4725]
## Description
Add the subdomain duet.openmined.org to point to our Duet Examples README.md
https://github.com/OpenMined/PySyft/tree/syft_0.3.0/examples/pytorch

Note: The path will change to: https://github.com/OpenMined/PySyft/tree/syft_0.3.0/examples/duet shortly.

## Definition of Done
Loading up duet.openmined.org in your browser should take you to that READM.md file.

**Comment by cereallarceny** [comment]
Done.
