### ISSUE TITLE
Update Duet README.md

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4728]
## Description
Update examples/duet (previously examples/pytorch) README.md to include Duet Logo, imagery, links to youtube videos, pricon videos, colab notebooks, emojis.

## Definition of Done

**Comment by HarshCasper** [comment]
Hello @madhavajay 

I would like to work on this issue if it is still open. This would be my first contribution towards OpenMined, and I would like to take it up and complete it as soon as possible for me.
