### ISSUE TITLE
Duplicate Request after .get() is successful causes Issue

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4734]
## Description
When you keep a local reference to a pointer, then fetch the item and then make a request again you can get into a bad state.

DO:

```
x = sy.lib.python.Int(1)
x.send(duet, searchable=True)
duet.requests.add_handler(
    action="accept"
)
```

DS:

```
x = duet.store[0]
x.request()
y = x.get()
...
x.request() <---- this ID doesnt exist so this request causes a looping exception on the DO
```

Prevent `.request()` working on a deleted obj, just like garbage collection when disabled.

## Definition of Done
This should not cause any major issues to the state of the notebook and a test should be written to ensure the correct behaviour occurs.

**Comment by madhavajay** [comment]
This should be handled by the client registry.

**Comment by rodrgo** [comment]
Hi @madhavajay, I'm new to the community and I'd like to be assigned to this issue if possible :)

**Comment by rodrgo** [comment]
Hey @madhavajay! Just wanted to confirm, is it the case that this issue is no longer open to new contributors?
