### ISSUE TITLE
Implement Custom Logging Levels

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4755]
## Description
We need to introduce our own custom logging tags with loguru so that we can annotate things like:
- message events
- WebRTC layer
- permission requests
- RPC execution
- store events
- async handler loops
- exceptions etc
 
This will allow us to build more specific control into what appears in the log and what appears in the notebook.
We can then completely eliminate print statements except perhaps in a few isolated CLI areas of the code base.

Consider converting f-strings to varadic or .lazy(True) style to make logging more efficient:
https://loguru.readthedocs.io/en/stable/overview.html?highlight=lazy#lazy-evaluation-of-expensive-functions

## Definition of Done
All major log messages are tagged with these new event types, in particular the very noisy debug statements around the messaging layer should be easy to turn off.

A mechanism to control the output within the Jupyter Notebook environment should be added so that we can carefully control what types of events appear in the notebooks. This might require some extra thought but it seems possible in Jupyter to control the return cells of messages to some degree:
https://blog.nteract.io/nteract-building-on-top-of-jupyter-9cfbccdd4c1d

**Comment by bcebere** [comment]
I will work on this one, please assign it to me

**Comment by madhavajay** [comment]
@bcebere awesome work. What do you think would be the best way to achieve some kind of code area grepping? So for example if all the logging / print in WebRTC was tagged with network and the user could disable it so they don't see any of those messages while keeping say, the store event log?

**Comment by bcebere** [comment]
Sure, I can add filters too, I will investigate that.

Also, the current exceptions logging might be a bit aggressive, I will have to review that. I disabled the full traceback for now, not sure if we needed somewhere.
