### ISSUE TITLE
Prevent Windows Event Loop issues

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4766]
## Description
If the code runs without an event loop being created Windows fails to execute the code properly.
We should try to replicate this and create a fix so that the code always starts an event loop in Windows if needed.
This also happens in the tests if a test uses async code downstream like `domain_test.py` and does not have the `@pytest.mark.asyncio`.

## Definition of Done
The issue is replicated and a fix is provided that ensures this doesn't happen.

**Comment by ElsaBroso1** [comment]
Hi, when I start duet I have the message 
...waiting for partner to connect...
♫♫♫ > ...error getting a running event Loop... no running event loop
♫♫♫ > ...creating a new event loop...

And then, when with the data owner send the data, as soon as I make duet.store.pandas I have theRunTimeError: Task got Future <Future pending> attached to a different loop. How can I solve it?

**Comment by madhavajay** [comment]
@ElsaBroso1 Perhaps you can investigate and see if you can figure it out? We believe its something to do with the main process not having an asyncio event loop started under some scenarios so perhaps see if theres a way to ensure that the main event loop gets started when syft starts up?

**Comment by ElsaBroso1** [comment]
Well, at the end I did not know what was the problem. However, running the script un ubuntu has no problems, so I will doing in ubuntu

**Comment by replomancer** [comment]
I am getting the `RunTimeError: Task got Future attached to a different loop` exception on Ubuntu.

I see this:
> ♫♫♫ > ...error getting a running event Loop... no running event loop
♫♫♫ > ...creating a new event loop...

on both sides (data owner and data scientist). I can also see "CONNECTED" on both sides. The data owner can later do stuff with duet e.g. send a tensor without errors, but the data scientist gets RunTimeErrors as above when evaluating `duet.store.pandas`


My system is Ubuntu 20.04. I'm building a virtual environment with python 3.8.5

**Comment by madhavajay** [comment]
@replomancer Are you able to provide a reliable way to reproduce this so we can create a ticket and get it fixed?
My guess is that in some code paths the loop is being started and in others it's not (or a race condition). So perhaps the solution is just to explicitly start one at the top level of the syft library on first import so theres always one available?

**Comment by madhavajay** [comment]
This is getting annoying. Windows CI will fail randomly every now and then because of this issue probably due to a race condition.

<img width="712" alt="Screen Shot 2021-01-05 at 4 31 31 pm" src="https://user-images.githubusercontent.com/2882739/103614105-94ba4200-4f73-11eb-9691-2ef6deaefeb4.png">

**Comment by replomancer** [comment]
OK, I am starting to investigate this.

**Comment by madhavajay** [comment]
@replomancer I wonder if this is related: https://github.com/OpenMined/PySyft/pull/5006

**Comment by madhavajay** [comment]
I haven't seen this issue since the https://github.com/OpenMined/PySyft/pull/5006 fix so lets consider it resolved.
