### ISSUE TITLE
Refactor AST Mapping

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4806]
## Description
The goal is to refactor the building of the AST tree and its mapping between real classes, string paths and our pointer classes in a way such that the following are true:
- It is easy to convert from one of these types to any of the other types with a single command or property
- Paths to the Real Class or our AST Proxy can be found using any correct python module path for example:
```
torch.nn.Conv2d
torch.nn.modules.Conv2d
torch.nn.modules.conv.Conv2d
```
All result in the same AST object or Original Class depending on what you are asking for.

- Only 1 entry is required in the allowlist to prevent the need to add duplicate entries

`This is currently still an issue for fqn string -> Class or Pointer without reference to the obj`

## Definition of Done
- A test is created which demonstrates that this works for several cases as above.
- All old code which uses things like `full_name_with_qualname`, `get_fully_qualified_name` lookups and `obj2pointer_type`, or sys.modules `getattr(sys.modules[".".join(module_parts)], klass)` like in `message.py` `_proto2object` are replaced with this new system.

**Comment by Nilanshrajput** [comment]
@madhavajay  I would like to help, can you direct me to the location where I can see how current AST mapping works/created.

**Comment by madhavajay** [comment]
@Nilanshrajput this ticket stands to remind us that when we do a refactor of the whole AST we need to include this functionality. Currently its working with a workaround you can see here:
https://github.com/OpenMined/PySyft/blob/e956be84e277babe26e10c0d683227e853d7dccd/src/syft/util.py#L143
https://github.com/OpenMined/PySyft/blob/7af672148afc4476e3344c4bce7225ed484c2d18/src/syft/ast/module.py#L37

I would say this task isn't actionable right now and is blocked by some other larger refactors.

**Comment by madhavajay** [comment]
Most of this is done in the AST Refactor but we might still need some of the shortcut properties to jump between Class, Pointer and FQN.

**Comment by madhavajay** [comment]
This is currently still an issue for fqn string -> Class or Pointer without reference to the `obj`
