### ISSUE TITLE
No module named 'syft.frameworks'

### ISSUE THREAD

**Issue by zizi96** [OpenMined/PySyft#4816]
## Description
I'm trying to follow this(https://blog.openmined.org/build-pate-differential-privacy-in-pytorch/) tutorial to get started but I'm getting the following error.

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c12cfcd00d71> in <module>`

`----> 1 from syft.frameworks.torch.dp import pate`

`ModuleNotFoundError: No module named 'syft.frameworks'`

PySyft is currently installed as when I run pip install syft I get a long list of requirement already satisfied including `Requirement already satisfied: syft in c:\users\me\anaconda3\envs\dp_pt\lib\site-packages (0.3.0)`

## How to Reproduce
1. Open Jupyter notebook 
2. !pip install syft
3. from syft.frameworks.torch.dp import pate

## Expected Behavior
Pate package to be imported without error

## System Information
 - OS: Windows 1022]
 - Language Version: Python 3.6
 - Package Manager Version: conda 4.8.3

**Comment by madhavajay** [comment]
Hi @zizi96, Unfortunately due to the rebuild, 0.3.0 isn't at 100% parity with 0.2.x as yet, however this will be addressed very shortly. In the mean time if you need that specific functionality, you can still install 0.2.x like so:
```
$ pip install syft==0.2.9
```

**Comment by dnabanita7** [comment]
Thanks @madhavajay ! I had the same issue.

**Comment by markste-in** [comment]
PATE analysis still works with 0.2.9 but the module doesn't seem to be incorporated in 0.3 anymore. The entire folder structure is missing and there is no dp folder anywhere else.

Was that intentionally be removed?

**Comment by madhavi1102** [comment]
Getting error when using 'from syft.frameworks.torch.federated import utils'

ModuleNotFoundError: No module named 'syft.frameworks'  

Installed syft '0.5.0rc1' version using 
pip install syft==0.5.0rc1

**Comment by Irfan1001** [comment]
I have installed syft '0.5.0rc1' version using
pip install syft==0.5.0rc1

but still, I'm getting this error.

ModuleNotFoundError: No module named 'syft.frameworks'

can anybody help me with that?
thanks

**Comment by Irfan1001** [comment]
ModuleNotFoundError: No module named 'syft.frameworks'

can anybody help me on this issue , please ?

**Comment by madhavajay** [comment]
Hi @Irfan1001 I don't believe `syft.frameworks` is part of `0.5` is there a reason you are using `syft==0.5.0rc1`, can you try the final `0.5.0`?
https://pypi.org/project/syft/0.5.0/

Or the 0.5.1 hotfix?
https://pypi.org/project/syft/0.5.1/

**Comment by madhavajay** [comment]
Hi @Adsensess can you elaborate on your issue? This issue was opened years ago relating to `0.2.x`?

**Comment by Adsensess** [comment]
ModuleNotFoundError: No module named 'syft.frameworks'

**Comment by madhavajay** [comment]
Hi @Adsensess the guide you referenced is for `0.2.x`, it won't work in any other version of syft.

**Comment by Mithula** [comment]
What's the alternative for 0.5.0 or 0.5.1?

**Comment by subhranil2605** [comment]
After installing ```syft==0.2.9``` with
```console
pip install syft==0.2.9
```

Then import like this
```python
import syft.frameworks.torch.dp.pate as pate
```

This is how I resolved it.
