### ISSUE TITLE
Unable to get Datapointers from WebSocketClient to the WebSockerServer

### ISSUE THREAD

**Issue by NavyaSreeY** [OpenMined/PySyft#4819]
Steps to reproduce

1) Created data in client.py and sent to the worker. Now I have data on the client with which i have data pointer for it.
2) Now I want to get that data pointer in server.

Is it possible to do like that?

When i see the approaches, most of them are creating data pointer in the server only to the client and using it there itself.

Please help me out.

**Comment by madhavajay** [comment]
Hi @NavyaSreeY all `Pointer` classes have a `.get()` method to allow you retrieve the real result. If the user has insufficient permission you will get an Authorization error and you may request with the blocking request API and allow the Data Owner to approve the request.

If the data was created by the client and sent it is usually not made "searchable". However we have a method for this in an open PR which should be merged shortly. If you check the `duet.store.pandas` on the server / Data Owner side you might see the entry in there and you could attempt to retrieve it that way.

The documentation on the Duet README.md is here: https://github.com/OpenMined/PySyft/blob/master/examples/duet/README.md is more comprehensive right now so I would recommend taking a look there and follow the examples and the MNIST notebook. We will be updating the main docs and root README.md very shortly.

I hope that helps answer your question.

**Comment by NavyaSreeY** [comment]
Thanks for the reply.

Actually I have two machines and try to implement my own federated learning structure.

All i need is just to define the dataloader in the client's code and tell client's while iterating over the batches do something for each one of them.

For more insight

Client:
![image](https://user-images.githubusercontent.com/26565713/99510288-e3545280-29ac-11eb-90e1-5a3fd06b6e63.png)

Server:
![image](https://user-images.githubusercontent.com/26565713/99510383-067f0200-29ad-11eb-8ce7-85427d266791.png)

As it is federated learning, I should be able to pull out the data from client and not like send the data from server to the client.

Please guide me to achieve this.

**Comment by madhavajay** [comment]
@NavyaSreeY is this still an active issue?

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
