### ISSUE TITLE
Add Torch Module / Layer Tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4831]
## Description
Add a test suite just like the Tensor op test which checks the modules and their return types work as expected.

## Definition of Done
CI runs Module tests in parallel and they pass.

**Comment by hershd23** [comment]
@madhavajay is any help needed on the issue? If so let me know how to get started

**Comment by madhavajay** [comment]
Hi @hershd23 that would be hugely appreciated.
Currently, this test file here:
https://github.com/OpenMined/PySyft/blob/dev/tests/syft/lib/allowlist_test.py

Tests all of the torch.Tensor ops listed in here:
https://github.com/OpenMined/PySyft/blob/dev/src/syft/lib/torch/allowlist.py

These ones:
```
allowlist["torch.Tensor"] = "torch.Tensor"
allowlist["torch.Tensor.xxxxxx"] = "torch.Tensor"
...
```

What this ticket is about, is adding a similar testing suite for all of the other entries in that file, like say conv2d:
```
allowlist["torch.nn.Conv2d"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.__call__"] = "torch.Tensor"
allowlist["torch.nn.Conv2d.parameters"] = "syft.lib.python.List"
allowlist["torch.nn.Conv2d.train"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.cuda"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.cpu"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.state_dict"] = "syft.lib.python.collections.OrderedDict"
allowlist[
    "torch.nn.Conv2d.load_state_dict"
] = "syft.lib.python._SyNone"  # torch.nn.modules.module._IncompatibleKeys
allowlist["torch.nn.Conv2d.extra_repr"] = "syft.lib.python.String"
```

Since the layers and modules nearly always have the exact same methods and return types we should be able to write code a bit like the allowlist_tests for Tensors which can loop through all of these and test them. There will be some unexpected issues for example the inputs to some types vary, like LSTMs and therefore so does their return types for .__call__ forward pass and thats exactly why we want to test them and make sure the return types are labelled correctly. If the return type is wrong the user can't use it properly because the synthetic pointer won't match.

If you create a Draft PR and get started I can keep an eye on it and show you how to keep going. 👍🏼

**Comment by hershd23** [comment]
I'll make the Draft PR and let you know. I got the sense of what is to be done. Just the question of where do I start as `allowlist.py` contains a pretty long dict.

**Comment by madhavajay** [comment]
I would do something like `conv2d` first:
```
allowlist["torch.nn.Conv2d"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.__call__"] = "torch.Tensor"
allowlist["torch.nn.Conv2d.parameters"] = "syft.lib.python.List"
allowlist["torch.nn.Conv2d.train"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.cuda"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.cpu"] = "torch.nn.Conv2d"
allowlist["torch.nn.Conv2d.state_dict"] = "syft.lib.python.collections.OrderedDict"
allowlist[
    "torch.nn.Conv2d.load_state_dict"
] = "syft.lib.python._SyNone"  # torch.nn.modules.module._IncompatibleKeys
allowlist["torch.nn.Conv2d.extra_repr"] = "syft.lib.python.String"
```

If those are tested then we can easily update that code to do nearly all the same for all the other layer modules.
Also we arent trying to prove correctness, we are just trying to make sure that when you call the functions with a a variety of valid input types (mostly tensors of all the different dtypes) that it works and the result is of the expected type and that the result on the remote version is the same as the result we get running it locally. Check the `allowlist_tests.py` to see what i mean. Also it will probably be easier to make a new allowlist_tests file like say `allowlist_module_tests.py` since allowlist_tests is very geared towards the tensors.

**Comment by madhavajay** [comment]
@hershd23 how did you go? Are you able to push a Draft PR? If not I might need to delegate this task to someone else.

**Comment by hershd23** [comment]
Hey @madhavajay been keeping busy with work lately. Feel free to assign this one to someone else.
