### ISSUE TITLE
Add Duet Integration Tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4832]
## Description
Add Duet Integration Tests so we can be confident that the pairing and basic communication is working at all times during PR / CI.

## Definition of Done
Additional Integration tests type and the Duet WebRTC tests are added to CI and pass.

**Comment by madhavajay** [comment]
There are some outstanding issues with operating Duet in CLI mode and the event loop, possibly on Windows which we should test for and ensure we have fixed.
See https://github.com/OpenMined/PySyft/issues/4766

**Comment by tudorcebere** [comment]
:pray:
