### ISSUE TITLE
ModuleNotFoundError: No module named 'syft.frameworks'

### ISSUE THREAD

**Issue by friendsAI** [OpenMined/PySyft#4840]
## Question
No module named 'syft.frameworks'

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: [Darwin]
 - OS Version: [19.6.0 ]
 - Language Version: [Python 3.6]
 - Package Manager Version: [Conda 4.7.12]

## Additional Context
I installed syft and checked by this command :python3.6 -c 'import torch, torchvision, syft'  ,no error was  occurred. Then I entered python environment, ' import syft ' is ok, but 'from syft.frameworks.torch.pointers import PointerTensor'  caused error.  It says "No module named 'syft.frameworks' ". And, bob = sy.VirtualWorker(hook, id='bob')  also caused error, it says 'module 'syft' has no attribute 'VirtualWorker' '. How to fix this problem?

**Comment by madhavajay** [comment]
Hi @friendsAI the recent 0.3.x release is a complete rebuild of PySyft and as such there is no longer a torch hook. I apologise that this isn't 100% clear on the new documentation, and we have several tickets already created to address this. We are aware that the two releases are not identical in functionality however we have some very exciting things coming which are only possible with the new 0.3.x architecture so bear with us. Some of the new API is already documented on our Duet example README.md here: https://github.com/OpenMined/PySyft/tree/dev/examples/duet

**Comment by vnt1537** [comment]
how to I use from syft.frameworks.torch.dp import pate?
As it shows ModuleNotFoundError: No module named 'syft.frameworks

**Comment by RoyRin** [comment]
I am also running into this issue - 
`from syft.frameworks.torch.dp import pate`
returns:
`ModuleNotFoundError: No module named 'syft.frameworks'`

Directly running code from https://blog.openmined.org/maintaining-privacy-in-medical-data-with-differential-privacy/

**Comment by vnt1537** [comment]
> I am also running into this issue - `from syft.frameworks.torch.dp import pate` returns: `ModuleNotFoundError: No module named 'syft.frameworks'`
> 
> Directly running code from https://blog.openmined.org/maintaining-privacy-in-medical-data-with-differential-privacy/

As told by @madhavajay, 0.3 version of pysyft is a completely new rebuild. Hence I would suggest you to download previous version of pysyft, maybe 0.1x or 0.2x

**Comment by Sanmaryjoseph** [comment]
> Hi @friendsAI the recent 0.3.x release is a complete rebuild of PySyft and as such there is no longer a torch hook. I apologise that this isn't 100% clear on the new documentation, and we have several tickets already created to address this. We are aware that the two releases are not identical in functionality however we have some very exciting things coming which are only possible with the new 0.3.x architecture so bear with us. Some of the new API is already documented on our Duet example README.md here: https://github.com/OpenMined/PySyft/tree/dev/examples/duet

what should be written in the code to fix this error
