### ISSUE TITLE
Upgrade GA by adding bot and moving tests

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#4841]
## Description
The slow tests are taking a long time to run and we should not block "devs" with them.
Steps:
- Run fast tests only on PRs
- Slow tests will run only on merges
- Add a bot to run slow tests (with a comment)
- If merged PR fails we should (manually) revert the changes and talk with the dev

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
The slow tests are taking a long time to run and we should do it as

**Comment by madhavajay** [comment]
Related: https://github.com/OpenMined/PySyft/issues/4830
