### ISSUE TITLE
Support Public Key Technology

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4844]
## Description
This ticket relates to implementing some kind of MVP PyDentity integration for educational purposes. Due to the unique aspects of PyDentity this might vary slightly from the other library integrations.

## Definition of Done
If the allowlist is needed for RPC calls of PyDentity then these should be added to the Syft code base. A notebook is created in `examples/pkt` or something similar which demonstrates how PyDentity could be used with Duet sufficiently to achieve the educational goals.

## Contacts
- @madhavajay
- @wip-abramson 

## TODO
- [x] Initial Hello World Duet Notebooks
- [x] Support LMW (🐧🍎💠)
- [x] Uses DuetCredentialExchanger

**Comment by H4LL** [comment]
@wip-abramson you've got the solution now right?

**Comment by wip-abramson** [comment]
Got an initial implementation here
https://github.com/OpenMined/PySyft/pull/4911/commits
