### ISSUE TITLE
Add CPython Tests for Set

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4856]
## Description
The same way we have the official CPython tests for types like String and Dict we should also port over the official Set test suite.

## Definition of Done
The official CPython Set tests have been ported over with as little modification as possible and pass on our Set subclass.

**Comment by xutongye** [comment]
Hi @madhavajay , do we have a Set class? I did not find it in source code. Which branch should I be in?

**Comment by madhavajay** [comment]
This is blocked by the possible refactor to remove SyPrimitive: https://github.com/OpenMined/PySyft/issues/5171
