### ISSUE TITLE
Error with TorchHook or VirtualWorker

### ISSUE THREAD

**Issue by TryFL** [OpenMined/PySyft#4865]
Hello. I have tried to use PySyft today. But I always get these error messages when I try to run sy.VirtualWorker(..) or hook = sy.TorchHook(torch):

AttributeError: module 'syft' has no attribute 'VirtualWorker'

Does anyone know the problem and knows a solution ? 

## System Information
 - Google Colab
 - Python 3.6.9
 - Syft 0.3.0

**Comment by madhavajay** [comment]
@TryFL . The new 0.3.0 release no longer uses sy.TorchHook. Some updated documentation is here: https://github.com/OpenMined/PySyft/tree/dev/examples/duet
More to come shortly.

If you need to use 0.2.x it is still available on PyPI.
