### ISSUE TITLE
How can I receive a tensor from server side and continue computations in client side?

### ISSUE THREAD

**Issue by Nazila-H** [OpenMined/PySyft#4874]
## Question

Hi everybody,
I am working with PySyft 0.2.X.
I want to send a tensor from a server side to a client side and receive it then start to do some computations there. I have defined worker and server as following:

Server side:
```
from syft.workers.websocket_client import WebsocketClientWorker
alice = WebsocketClientWorker( related arguments)

print(type(alice))
x = torch.tensor([1,3,5])
x_ptr = x.send(alice)
print(x_ptr)
print(x)
```
Client side:
```
from syft.workers import websocket_server


server = websocket_server.WebsocketServerWorker( id=id, host=host, port=port, hook=hook, verbose=verbose)
    
server.start()
print('server.list_objects():', server.list_objects())
```
after running from client side then server side I got the following results from server side:

```
<class ‘syft.workers.websocket_client.WebsocketClientWorker’>
(Wrapper)>[PointerTensor | me:56794581876 -> Alice:90382785850]
tensor([1, 3, 5])
```

then from client side I did not get anything before I stopped execution which I got:

```
server.list_objects(): {90382785850: tensor([1, 3, 5])}
```

I want to have the tensor in client side I know syft.workers.websocket_server. WebsocketServerWorker has _recv_msg function but I do not know haw I can use it.

Thank you in advance.

## Further Information
0.2.X is a hard requirement

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
