### ISSUE TITLE
Add pointer tests on syft.lib.python.Dict

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#4886]
## Description
Similar to `tests.syft.lib.python.list.pointer_test.py`, we want a way to test that the original `dict`, `Dict` and `DictPointer` have the same behaviour.

## Type of Test
- [x] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [x] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)

**Comment by matei-s** [comment]
I would like to work on this.
