### ISSUE TITLE
Error in PySyft Autograd for Convolution

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#4887]
## Description
It looks like convolution are not handle by the PySyft 0.2.9 Custom Autograd system, resulting in poor performance for training CNN in fixed precision or in a fully private way

## How to Reproduce
Take any small CNN and train it in fixed precision over MNIST. If you observe the convolution parameters during training, they don't change.

## System Information
 - PySyft 0.2.9

**Comment by mahad852** [comment]
Hey!
I notice the same issue on my end, and was wondering if you found any solution to this? 
I am currently using PySyft 0.2.9 (the same as you mentioned in the post).

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
