### ISSUE TITLE
Allowlist on all supported libraries 

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#4888]
## Description
All libraries should follow the allowlist system existing in `syft.lib.torch`. Currently, `syft.lib.python` does not respect the same structure when creating the AST.

## Definition of done
A file in all supported libraries (especially in `syft.lib.python`) named `allowlist.py` that creates the allowlist for the python AST.

**Comment by devkumar24** [comment]
hey @tudorcebere, can you help me to get started with this issue?

**Comment by tudorcebere** [comment]
Hello @devkumar24,

This has been already addressed in a PR that will be merged soon.

Thank you for your interest in the syft! I would recommend searching for the issues tagged with `Good first issue` and grab one of those as your first issue in 0.3.X!

**Comment by madhavajay** [comment]
@tudorcebere was this finished in the API Refactor?
