### ISSUE TITLE
StorableObject refactor

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#4892]
## What?
The StorableObject is not in a great shape, some love is needed there.

## Why?
We glued together a way of using it, but it's quite unreadable, error-prone and we might be doing useless stuff in the serde. We should have a proper way of not using wrappers in our own objects, wrappers are only for external objects to make them storable.

Notes:
* `construct_new_object` should be removed from the codebase.
* a perfect implementation of this would remove the wrappers from the syft objects.

**Comment by madhavajay** [comment]
See: https://github.com/OpenMined/PySyft/pull/5104
