### ISSUE TITLE
How to set parameters in SyNet class?

### ISSUE THREAD

**Issue by thodosss** [OpenMined/PySyft#4893]
Is there an equivalent of the following expression of PySyft previous version tutorial to set aggredated weight and bias in a new model via SyNet class? 

```
with torch.no_grad():
    model.weight.set_(((alices_model.weight.data + bobs_model.weight.data) / 2).get())
    model.bias.set_(((alices_model.bias.data + bobs_model.bias.data) / 2).get())
```

Thank you in advance

**Comment by thodosss** [comment]
Can anyone help please ?

**Comment by madhavajay** [comment]
0.5 is no longer supported.
