### ISSUE TITLE
ptr.__len__() returns None in syft 0.3.0 dev

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/PySyft#4903]
## Description
While testing the Duet MNIST tutorials with latest version of syft (dev branch) I ran into the following error
![len](https://user-images.githubusercontent.com/36858630/101894253-e74e4b80-3bcb-11eb-98d1-fef7594c0cb2.png)

## How to Reproduce
1. Run the MNIST example notebooks
2. The error occurs on `def get_train_length(train_data_ptr)` cell in Data Scientist notebook

Also the `try-except` block seems redundant here. 

## System Information
 - OS: Windows 10
 - Language Version: Python 3.8.5, 
 - Syft Version - Syft Dev 0.3.0.post0.dev34+ga9a7874a

**Comment by madhavajay** [comment]
@jaintj95. Good spot, this is most likely in the dev branch which is not 100% stable. We recently added a new __len__ getter mechanism for iterators, so this code will need to change but the API hasn't been fully worked out yet.

You can see in these cells that there is an automatically generated request in the background.
<img width="1083" alt="Screen Shot 2020-12-14 at 10 25 41 am" src="https://user-images.githubusercontent.com/2882739/102028621-e4836e80-3df6-11eb-98c1-210e33f1d46d.png">


<img width="793" alt="Screen Shot 2020-12-14 at 10 26 00 am" src="https://user-images.githubusercontent.com/2882739/102028619-e0efe780-3df6-11eb-81b2-bd2397f9f2b2.png">

I will make sure we get this example updated once we get the Iterators / Len stuff sorted.

**Comment by madhavajay** [comment]
I believe this is related to the scenario in which the request is made:
https://github.com/OpenMined/PySyft/issues/5170

This does need to be fixed.

**Comment by tudorcebere** [comment]
This has been solved by #5275.
