### ISSUE TITLE
Add Torch 1.7.1

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4906]
## Description
Add Torch 1.7.1 to support matrix and tests.

## Definition of Done
Torch 1.7.1 in the compatibility matrix. New Ops added to the allowlist.

**Comment by devil-cyber** [comment]
Hey @madhavajay can you help me to get started with this issue

**Comment by madhavajay** [comment]
@devil-cyber, take a look at the merge and pr tests.yml files for GitHub Actions.
Then go see the `src/syft/lib/torch/allowlist.py`:

```
allowlist["torch.Tensor.amax"] = {
    "return_type": "torch.Tensor",
    "min_version": "1.7.0",
}
```

What you need to do is import torch 1.7.1 and `dir(torch)` and dump the entire API or check the changelog and see if there are any new OPS we need to support, if there are you need to add them to the `allowlist.py` and then also add tests to the `allowlist_test.json`.

If you can create a PR which shows some progress I will assign this to you.

**Comment by devil-cyber** [comment]
Ok thanks i will start my work

**Comment by devil-cyber** [comment]
Hey @madhavajay for PyTorch 1.7.1 we have to add all API functionality 
as well as we have to update the respective torch vision in the YML file.
 Am I in the right direction?

**Comment by madhavajay** [comment]
@devil-cyber That is correct. If you can submit a PR with your progress I can give you feedback. 👍🏼

**Comment by devil-cyber** [comment]
Ok, I will do that.
