### ISSUE TITLE
Duet loop issue

### ISSUE THREAD

**Issue by mgale694** [OpenMined/PySyft#4914]
## Description
When I try and run the simple duet example at the top of the Duet README file it throws an error. It seems to be to do with how the event loop is initialised. Can someone let me know if this is a bug, or an issue on my end?

## How to Reproduce
1. go to the duet main README page and copy out the example.

## Expected Behavior
on the data science side I should be able to run 'duet.store.pandas' and get the table of whats in the store as a tensor has been sent to the duet from the data owner side.

## Screenshots
![Screenshot 2020-12-15 at 16 54 29](https://user-images.githubusercontent.com/51291404/102246045-365eee00-3ef6-11eb-9b20-478a7d9dda57.png)
![Screenshot 2020-12-15 at 16 54 49](https://user-images.githubusercontent.com/51291404/102246076-41198300-3ef6-11eb-8510-c879d70d038e.png)

## System Information
 - OS: macOS
 - OS Version: 10.15.5
 - Language Version: Python 3.7

**Comment by LaRiffle** [comment]
Same problem for me when running https://github.com/OpenMined/PySyft/tree/dev/examples/duet/mnist

**Comment by LaRiffle** [comment]
Ok apparently this is because we have an old version of jupyter notebook!
`pip install --upgrade notebook`  should fix this!

**Comment by mgale694** [comment]
@LaRiffle Thank you, this has solved the issue for me!
