### ISSUE TITLE
Bug in torch.square for additive shared tensor

### ISSUE THREAD

**Issue by plotkiny** [OpenMined/PySyft#4916]
## Description
torch.square(t) currently fails  with encrypted-shared tensors

## How to Reproduce

`import syft as sy`
`import torch`

`hook = sy.TorchHook(torch)`

`alice = sy.VirtualWorker(hook, id="alice")`
`bob = sy.VirtualWorker(hook, id="bob")`
`crypto_provider = sy.VirtualWorker(hook, id="crypto_provider")`
`t = torch.tensor([1.5, 2.5])`
`t_encrypt = t.fix_precision().share(alice, bob, crypto_provider=crypto_provider, protocol="fss")`
`print(t_encrypt)`

Computing the mean and centering the tensor works just fine:

`t_mean = torch.mean(t_encrypt)`
`new_t = t_encrypt - t_mean `
`new_t.get().float_precision()`     # returns the correct output tensor = [-0.5, 0.5]

What if we want to square the tensor after centering:

`t_mean = torch.mean(t_encrypt) `
`new_t = t_encrypt - t_mean`
`new_t_square = torch.square(new_t)`
`new_t_square.get().float_precision()`   # returns the wrong output tensor = [-7.3e+15, -7e+15]*. 

*Tensor values vary with relative magnitude on the order of ~ e+15

The desired output tensor can be calculated as:

`new_t_square = torch.square(t - torch.mean(t))`    # returns the desired output tensor = [0.25, 0.25]

## System Information
 - OS: macOS 
 - OS Version: 10.15.6
 - Language Version: Python 3.7.9
 - Package Manager Version: Conda 4.8.4
 - Syft version: 0.2.9

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
