### ISSUE TITLE
Opacus won't work with Syft 0.2.9

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4917]
## Description
Existing Ticket on PriMIA: https://github.com/gkaissis/PriMIA/issues/47

**Comment by BambooPalace** [comment]
This still does not work, when i try to run https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/
How were they able to run both together at that time? i tried pysyft 0.2.8 + opacus 0.9.x also can not.

**Comment by BambooPalace** [comment]
This still does not work, when i try to run https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/
How were they able to run both together at that time? i tried pysyft 0.2.8 + opacus 0.9.x also can not.
Any ideas on what versions of both library can work together?
@madhavajay

**Comment by bigmoumou** [comment]
Same issue here. Any tutorial for 0.2.x or 0.3.x to work with privacy engine in Opacus is really helpful. I have been waiting for 2 months so far.

**Comment by cherrytora** [comment]
I have the same problem. I tried pysyft 0.2.8 + opacus 0.9.x and  pysyft 0.2.9 + opacus 0.9.x , but it still doesn't work.

**Comment by madhavajay** [comment]
@bigmoumou and @cherrytora 
The current example is here:
https://github.com/OpenMined/PySyft/tree/dev/examples/differential-privacy/opacus

Its still a work in progress but you can remotely train MNIST with opacus.

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
