### ISSUE TITLE
Support @Property setters in Syft

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4918]
## Description
We need to allow the ability to set properties over a Pointer.
The way this might work is we could synthesise our own @property setter on the pointer and then forward that across the network.

## Definition of Done
Tests with property setters over Pointers passing and TenSEAL: `context.global_scale = 2**40` working on a pointer.
https://github.com/OpenMined/TenSEAL

**Comment by libratiger** [comment]
I am new to this repo, I want to begin the contribution from this issue, is there any adivces?

**Comment by tudorcebere** [comment]
Hello @libratiger!

Currently, this has been solved in a PR, thanks for your interest!

Keep an eye out for the `Good first issue` tag!
