### ISSUE TITLE
Support to FastAI

### ISSUE THREAD

**Issue by rondey** [OpenMined/PySyft#4924]
## Feature Description
It could be great write private neural networks using the modern best practices implemented in FastAI. I tried PySyft 0.2 alongside with FastAI (v1) and they are not perfectly compatible each other. Do you think is possible make compatible the new PySyft 0.3 with FastAI v2?

**Comment by madhavajay** [comment]
It totally could be possible. I know a few people from the FastAI Audio group who might be interested in helping. @rbracco ?

**Comment by madhavajay** [comment]
@rondey I would also highly recommend posting this on the FastAI Discord / Forums as well and see if @jph00 is potentially interested in giving it some official sanctioning.

**Comment by rondey** [comment]
@madhavajay Thank you so much, I have created [a new post](https://forums.fast.ai/t/fast-ai-support-for-ml-privacy-preserving-using-pysyft/83607) on the FastAI forum.

**Comment by jph00** [comment]
Looking forward to seeing how you get along with this! :D

**Comment by madhavajay** [comment]
> @jph00 I'll consider that officially sanctioned 👍🏼 

@rondey I am a big FastAI fan myself but we don't have the bandwidth to start this right now while we are building support for all the other libraries needed to provide the PPML functionality you mentioned in the FastAI forum post. 😂. However if you are interested in opening an initial PR on this I can walk you through the process. ❤️

**Comment by rondey** [comment]
I like the idea, but actually I have a paper to complete (I'm using PySyft for the implementation).

**Comment by madhavajay** [comment]
@rondey No worries, I am sure we will get to very soon, but we just have a few priorities of our own as well. 😊 Good luck with the paper and thanks for using PySyft in the implementation. ❤️

**Comment by rondey** [comment]
Thank you! I perfectly understand your priorities

**Comment by madhavajay** [comment]
This is going into a backlog, don't worry, we will be doing this. 😊
