### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by beichen777** [OpenMined/PySyft#4936]
## Question
**Hello!All the members of my project team used Ubuntu-20.04.1 to build PySyft0.30, and there was no problem in the building process. But when "Light Tests" and "All Tests" are run, they're All stuck at 32%[kool-cuda-self_tensor6855-0-false-torch.tensor -true]. Why?**

## Screenshots
![](https://raw.githubusercontent.com/beichen777/paperimage/main/51.PNG)

## System Information
 - OS: [Ubuntu]
 - OS Version: [20.04.1]
 - Language Version: [ Python 3.8.2]
 - Package Manager Version: [Conda 4.9.2]

**Comment by madhavajay** [comment]
@beichen777 are you able to report what version of torch you are using since those are torch tests?

**Comment by beichen777** [comment]
> 
> 
> @beichen777 are you able to report what version of torch you are using since those are torch tests?

torch 1.7.1

**Comment by madhavajay** [comment]
@beichen777 `torch.1.7.1` is not supported yet, but we will be adding it very shortly. My guess is that some of the rules we have set to explicitly run certain tests on certain torch versions is passing through which is intended behavior to prevent us from accidentally thinking that a new torch version is fully supported without explicitly checking and testing all op changes etc.

**Comment by madhavajay** [comment]
Related: https://github.com/OpenMined/PySyft/issues/4906

**Comment by beichen777** [comment]
Thank you very much, I will change the torch version and try again.  keep in touch! @madhavajay ^_^

**Comment by madhavajay** [comment]
@beichen777 no worries, we are working on `1.7.1` so as soon as it passes CI we will merge it in and you can upgrade. 👍🏼

**Comment by beichen777** [comment]
@madhavajay Come on, look forward to it!
