### ISSUE TITLE
Convert Torch Install Steps into Scripts

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4944]
## Description
The Torch install steps in CI are getting long and verbose, we should convert these into scripts so they can be easily updated outside of CI and tested as well as used to enforce torch versions during the support library tests.

See these two steps:
https://github.com/OpenMined/PySyft/blob/866f401b3327f98f7b3b764d14c2a9af3afa80c4/.github/workflows/pr_tests.yml#L109
https://github.com/OpenMined/PySyft/blob/866f401b3327f98f7b3b764d14c2a9af3afa80c4/.github/workflows/pr_tests.yml#L130

## Definition of Done
These steps are removed from *.yaml and replaced with a script file for both BASH and PowerShell on windows.

**Comment by devkumar24** [comment]
I want to work on this, can you assignee me to this issue?

**Comment by agnim25** [comment]
@madhavajay made pull request #4954, hoping you could take a look?

**Comment by madhavajay** [comment]
@agnim25 that was awesome work, I merged it here: https://github.com/OpenMined/PySyft/pull/4966
