### ISSUE TITLE
Fix @pytest.mark.xfail tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4974]
## Description
We have several @pytest.mark.xfail tests which we should fix.

## Definition of Done
@pytest.mark.xfail annotations are removed and tests are fixed and pass.

**Comment by rajatrc1705** [comment]
I want to work on this issue.

**Comment by madhavajay** [comment]
@rajatrc1705 Please make sure to post some PR progress otherwise the task might be taken by someone else.

**Comment by rajatrc1705** [comment]
Pickling of the iterator for Dict keeps failing the test, any tip on where I should be poking around?
Pickling of the data for Dict passes, but the iterator fails.
![image](https://user-images.githubusercontent.com/52173002/104832213-965e0100-58b5-11eb-9244-124c4e3c28ec.png)

**Comment by rajatrc1705** [comment]
I am not able to figure out how to go about this. No matter what I do, the iterator for UserDict and Dict fails the pytest.
![image](https://user-images.githubusercontent.com/52173002/105450724-1cf15480-5ca1-11eb-84b9-b3d51058b006.png)
The same code works on a Jupyter Notebook, 
![image](https://user-images.githubusercontent.com/52173002/105450767-31355180-5ca1-11eb-90e3-fd28d58925f5.png)

**Comment by rajatrc1705** [comment]
If anyone has any ideas how to go about this, I would be grateful for any help.
