### ISSUE TITLE
ConnectionError in notebooks/PySyft/examples/duet/mnist/MNIST_Syft_Data_Owner.ipynb

### ISSUE THREAD

**Issue by lk1983823** [OpenMined/PySyft#4979]
## Question
**ConnectionError in notebooks/PySyft/examples/duet/mnist/MNIST_Syft_Data_Owner.ipynb**

## Further Information
I successfully installed syft following the instruction. However, when I run the MNIST_Syft_Data_Owner.ipynb in  PySyft/examples/duet/mnist, Connection error happened.  Here is the errors:

```
🎤  🎸  ♪♪♪ Starting Duet ♫♫♫  🎻  🎹

♫♫♫ > DISCLAIMER: Duet is an experimental feature currently in beta.
♫♫♫ >             Use at your own risk.
♫♫♫ >
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connection.py in _new_conn(self)
    168         try:
--> 169             conn = connection.create_connection(
    170                 (self._dns_host, self.port), self.timeout, **extra_kw

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     95     if err is not None:
---> 96         raise err
     97 

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     85                 sock.bind(source_address)
---> 86             sock.connect(sa)
     87             return sock

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    698             # Make the request on the httplib connection object.
--> 699             httplib_response = self._make_request(
    700                 conn,

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    381         try:
--> 382             self._validate_conn(conn)
    383         except (SocketTimeout, BaseSSLError) as e:

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1010             conn.connect()
   1011 

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connection.py in connect(self)
    352         # Add certificate verification
--> 353         conn = self._new_conn()
    354         hostname = self.host

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connection.py in _new_conn(self)
    180         except SocketError as e:
--> 181             raise NewConnectionError(
    182                 self, "Failed to establish a new connection: %s" % e

NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbcab4ac940>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    754 
--> 755             retries = retries.increment(
    756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    572         if new_retry.is_exhausted():
--> 573             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    574 

MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /OpenMined/OpenGridNodes/master/network_address (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbcab4ac940>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-3-851416344cd0> in <module>
      1 import syft as sy
----> 2 duet = sy.launch_duet()
      3 # sy.logging(file_path="./syft_do.log")

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/syft/grid/duet/__init__.py in launch_duet(logging, network_url, loopback, db_path)
    197 
    198     if not network_url:
--> 199         network_url = get_available_network()
    200     print("♫♫♫ > Punching through firewall to OpenGrid Network Node at:")
    201     print("♫♫♫ > " + str(network_url))

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/syft/grid/duet/__init__.py in get_available_network()
     60 
     61 def get_available_network() -> str:
---> 62     network_addr = json.loads(requests.get(ADDR_REPOSITORY).content)
     63     for addr in network_addr:
     64         try:

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/requests/api.py in get(url, params, **kwargs)
     74 
     75     kwargs.setdefault('allow_redirects', True)
---> 76     return request('get', url, params=params, **kwargs)
     77 
     78 

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/requests/api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 
    544         return resp

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/requests/sessions.py in send(self, request, **kwargs)
    653 
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 
    657         # Total elapsed time of the request (approximately)

~/.pyenv/versions/anaconda3-5.0.1/envs/pysyft/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /OpenMined/OpenGridNodes/master/network_address (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbcab4ac940>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

## System Information
 - OS: Ubuntu 
 - OS Version: 16.04
 - Language Version: Python 3.8.6
 - Package Manager Version: anaconda3-5.0.1

**Comment by madhavajay** [comment]
@lk1983823 The error says it can't load github to resolve the OpenGrid URLS, are you able to visit this URL: https://raw.githubusercontent.com/OpenMined/OpenGridNodes/master/network_address

**Comment by lk1983823** [comment]
> @lk1983823 The error says it can't load github to resolve the OpenGrid URLS, are you able to visit this URL: https://raw.githubusercontent.com/OpenMined/OpenGridNodes/master/network_address

Yes. It shows: 
["http://ec2-18-216-8-163.us-east-2.compute.amazonaws.com:5000",
 "http://ec2-3-22-236-160.us-east-2.compute.amazonaws.com:5000",
 "http://ec2-18-221-100-52.us-east-2.compute.amazonaws.com:5000"]

**Comment by madhavajay** [comment]
@lk1983823 did it connect?

**Comment by lk1983823** [comment]
> @lk1983823 did it connect?

No...

**Comment by lk1983823** [comment]
> @lk1983823 did it connect?

**Comment by madhavajay** [comment]
Hi @lk1983823, are you interested in helping us debug the issue. As you can imagine its important that our connection system works with zero configuration so it would be great to get to the bottom of the issue.

**Comment by lk1983823** [comment]
> Hi @lk1983823, are you interested in helping us debug the issue. As you can imagine its important that our connection system works with zero configuration so it would be great to get to the bottom of the issue.

Yes, I am willing to offer help.

**Comment by madhavajay** [comment]
@lk1983823 Are you able to DM me on Slack? I can give you some commands to do some pinging and trace-routing but the output would reveal your approximate location in the world and you might not want to post your ISP or IP addresses on the public internet. Also what operating system are you using and what kind of network? Is it at home, work, office, university all that info will help as these issues are usually caused by complex Corporate or University networks.

**Comment by lk1983823** [comment]
> @lk1983823 Are you able to DM me on Slack? I can give you some commands to do some pinging and trace-routing but the output would reveal your approximate location in the world and you might not want to post your ISP or IP addresses on the public internet. Also what operating system are you using and what kind of network? Is it at home, work, office, university all that info will help as these issues are usually caused by complex Corporate or University networks.

How can I add you in slack? I am newer to that.

**Comment by lk1983823** [comment]
After trying the following code:

```
import syft as sy
duet = sy.launch_duet(network_url="http://ec2-18-216-8-163.us-east-2.compute.amazonaws.com:5000")
import syft as sy
duet = sy.join_duet(target_id="xxxxx", network_url="http://ec2-18-216-8-163.us-east-2.compute.amazonaws.com:5000")
```

it works.

So my problem is with the GitHub URL not loading. It is that 
` curl https://raw.githubusercontent.com/OpenMined/OpenGridNodes/master/network_address`
does not work. So it is not a pysyft problem.

**Comment by zhengjiawei001** [comment]
Is this problem solved, I have the same problem

**Comment by madhavajay** [comment]
@zhengjiawei001 This is not a problem with Syft its a problem with not being able to access `githubusercontent.com` through certain firewalls. You can manually set the `network_url` like above to one of the three listed above.

**Comment by TerryPei** [comment]
Dear madhavajay:
There is a problem when I connected.  The Error is: `Task <Task pending name='Task-20' coro=<WebRTCConnection.send_sync_message() running at /opt/anaconda3/lib/python3.8/site-packages/typeguard/__init__.py:944>> got Future <Future pending> attached to a different loop`

Owner have uploaded data by  `data_features_pointer = data_features.send(duet, searchable=True)`, but Server can't get the data which Owner has been sent. 

The owner code is here:
`
import torch
import syft as sy
sy.VERBOSE = False
duet = sy.launch_duet(network_url="http://ec2-18-216-8-163.us-east-2.compute.amazonaws.com:5000")

data_features = torch.tensor([1, 2, 3, 4, 5])
data_features.tag('#tag_data')
data_features.describe("This is a test of features' data.")
# Upload the data to the server
data_features_pointer = data_features.send(duet, searchable=True)
`
The server code:
`
import syft as sy
sy.VERBOSE = False
duet = sy.join_duet(target_id='626aed2eca9c1aa9b73e4fd02ad874dc', network_url="http://ec2-18-216-8-163.us-east-2.compute.amazonaws.com:5000")
duet.store
# Appear error here
`

**Comment by polzinben** [comment]
I am having this same issue, but I am able to visit this url https://raw.githubusercontent.com/OpenMined/OpenGridNodes/master/network_address

If this issue has been resolved, please post the solution here as this is extremely frustrating..

**Comment by Githeo** [comment]
I'm able to curl the address and receive the three alternative addresses, but the same error persist.
I also tried @zhengjiawei001 solution: it tries to connect but stops after some time not getting any response.
I'd like to use it on the loopback too, but it doesn't work neither :/.

`
#import syft as sy
#duet = sy.duet(loopback=True)
`

I'm with pysyft version 0.5.0.
