### ISSUE TITLE
Contributing guide links in dev README point to different versions

### ISSUE THREAD

**Issue by gleec14** [OpenMined/PySyft#4983]
## Question
There are two contributing guides in the dev branch README: one leading to a copy in the master branch and another to dev. The dev branch copy has more information but lacks some of the instructions in the master branch. As a newcomer, this was confusing for me. Should both links in the README point to the dev contributing guide and should the information in the master copy be copied over?

**Comment by madhavajay** [comment]
That should probably be a relative path to CONTRIBUTING.md, opening a PR would be appreciated.

**Comment by gleec14** [comment]
PR here: https://github.com/OpenMined/PySyft/pull/4985. It includes typo fixes in the notebooks as well.
