### ISSUE TITLE
ModuleNotFoundError: No module named 'torchcsprng' (PySyft 0.2.9 last commit)

### ISSUE THREAD

**Issue by rondey** [OpenMined/PySyft#4984]
## Description
On a system with CUDA, importing syft module results in a "ModuleNotFoundError: No module named 'torchcsprng' (PySyft 0.2.9 last commit)". torchcsprng because it requires at least pytorch 1.6 (torchcsprng version 0.1.0). On the other hand, PySyft requires pytorch 1.4

## How to Reproduce
1. Install PySyft 0.2.9 last commit
2. Run on a notebook "import syft as sy"
3. See error

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
