### ISSUE TITLE
ModuleNotFoundError: No module named 'syft' (PySyft 0.3)

### ISSUE THREAD

**Issue by sbasu26** [OpenMined/PySyft#4986]
I have installed PySyft versions 0.3 and 0.2.9 in different VMs before(in Nov and Dec 2020), and they have worked fine.

But when I am trying to install pysyft in a new machine now, using Ananconda Prompt, I am getting a pysyft=0.3 installation completed successfully message, but on accessing syft in Jupyter Notebook using the import statement (import syft as sy), I am getting the module not found error.

I am following the pre-installation and installation instructions in https://github.com/OpenMined/PySyft

How to Reproduce
$ conda create -n pysyft python=3.8
$ conda activate pysyft
$ conda install jupyter notebook
$ pip install syft
$ jupyter notebook

Run on a notebook "import syft as sy"
See error

**Comment by Abhishek-1Bhatt** [comment]
Facing the same problem

**Comment by kishansairam9** [comment]
@sbasu26 @Abhishek-1Bhatt 
I tried to reproduce the issue, but was unable to. There seems to be no error.
Can you attach the output of `conda env export` run in your environment?

**Comment by sbasu26** [comment]
@kishansairam9 Please find attached
[PySyftEnv.txt](https://github.com/OpenMined/PySyft/files/5765981/PySyftEnv.txt)

**Comment by kishansairam9** [comment]
@sbasu26 As you can observe from the output, pysyft hasn't been installed in this environment
This might have occurred due to "pip" referring to different executable on Windows when you ran install..
Please try running `python3 -m pip install syft`, this might fix your issue

**Comment by sbasu26** [comment]
@kishansairam9 Neither of the commands have been able to fix the error.
I had suspected the same that pysyft had not been installed, hence I had tried uninstalling and installing it multiple times.

On Uninstalling (pip uninstall pysyft), I get the bellow confirmation of uninstallation:

(pysyft4) C:\Users\dell>pip uninstall syft
Found existing installation: syft 0.3.0
Uninstalling syft-0.3.0:
  Would remove:
    c:\users\dell\appdata\local\conda\conda\envs\pysyft4\lib\site-packages\syft-0.3.0.dist-info\*
    c:\users\dell\appdata\local\conda\conda\envs\pysyft4\lib\site-packages\syft\*
    c:\users\dell\appdata\local\conda\conda\envs\pysyft4\scripts\syft-device.exe
    c:\users\dell\appdata\local\conda\conda\envs\pysyft4\scripts\syft-domain.exe
    c:\users\dell\appdata\local\conda\conda\envs\pysyft4\scripts\syft-network.exe
    c:\users\dell\appdata\local\conda\conda\envs\pysyft4\scripts\syft-proto.exe
Proceed (y/n)?

And again on installing with the command _python3 -m pip install syft_ and importing syft in Jupyter notebook, i get the same Module Not found Error!

Also executing the command !pip install syft in Jupyter Notebook has Not helped!

**Comment by madhavajay** [comment]
It could be that the jupyter instance you are running is not mapped to the same virtualenv environment site packages that you are installing pysyft to. Can you try this:
```
$ conda create -n pysyft python=3.8
$ conda activate pysyft
$ pip install syft
$ which python3
$ python3
>>> import syft as sy
>>> sy.__version__
```

**Comment by madhavajay** [comment]
> @kishansairam9 Please find attached
> [PySyftEnv.txt](https://github.com/OpenMined/PySyft/files/5765981/PySyftEnv.txt)

Also, doesn't this file imply that conda has not installed pysyft. Don't you need to tell conda to install it not pip? I don't use conda so I can't comment.

```
(pysyft4) C:\Users\dell>conda env export
name: pysyft4
channels:
  - defaults
dependencies:
  - ca-certificates=2020.12.8=haa95532_0
  - certifi=2020.12.5=py38haa95532_0
  - openssl=1.1.1i=h2bbff1b_0
  - pip=20.3.3=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - setuptools=51.0.0=py38haa95532_2
  - sqlite=3.33.0=h2a8f88b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
prefix: C:\Users\dell\AppData\Local\conda\conda\envs\pysyft4
```

**Comment by sbasu26** [comment]
@madhavajay I would like to point out, that I am installing PySyft 0.3 after freshly installing Anaconda (after a laptop crash).
Am I missing something apart from the installation steps mentioned in the Guide.

I have installed Ananconda and run the below commands only to install Pysyft, and I am getting the ModuleNotFound error for importing PySyft.

How to Reproduce
$ conda create -n pysyft python=3.8
$ conda activate pysyft
$ conda install jupyter notebook
$ pip install syft
$ jupyter notebook

**Comment by madhavajay** [comment]
> @madhavajay I would like to point out, that I am installing PySyft 0.3 after freshly installing Anaconda (after a laptop crash).
> Am I missing something apart from the installation steps mentioned in the Guide.
> 
> I have installed Ananconda and run the below commands only to install Pysyft, and I am getting the ModuleNotFound error for importing PySyft.
> 
> How to Reproduce
> $ conda create -n pysyft python=3.8
> $ conda activate pysyft
> $ conda install jupyter notebook
> $ pip install syft
> $ jupyter notebook

Can you please run these commands and report back the output where the `...` are:
```
$ conda create -n pysyft python=3.8
$ conda activate pysyft
$ conda install jupyter notebook
$ where jupyter
...
$ pip install syft
$ where python3
...
$ python3
>>> import syft as sy
>>> sy.__version__
...
```

**Comment by sbasu26** [comment]
@madhavajay Below is the output of the command "where python3"

(pysyft3) C:\Users\dell>where python3
C:\Users\dell\AppData\Local\Microsoft\WindowsApps\python3.exe

And executing the line import syft as sy fives me the below error:
AttributeError: module 'torchvision.datasets' has no attribute 'VisionDataset'

Somehow when I install pysyft using pip, the torchvision version which gets installed is 0.2.2.

And if I uninstall 0.2.2 and try to install torchvision 0.8.0, I get the below error screen!
<img width="960" alt="torchvisionError" src="https://user-images.githubusercontent.com/26589431/103889520-923f2000-510c-11eb-8050-c4eafa547280.png">

**Comment by madhavajay** [comment]
@sbasu26 Thanks. Thats interesting, you have a few issues there that I can see.
1) The path to your python3 is the system but not a virtualenv.
You can see here on my output when I use a virtualenv the first location found for python is in the virtualenv.
```
C:\dev\pysyft>pipenv shell
Warning: Your Pipfile requires python_version 3.8, but you are using 3.7.9 (C:\Users\me\.\p\S\python.exe).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Launching subshell in virtual environment…
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

(pysyft-8bj21zgT) C:\dev\pysyft>where python
C:\Users\me\.virtualenvs\pysyft-8bj21zgT\Scripts\python.exe
C:\Users\me\AppData\Local\Programs\Python\Python36\python.exe
C:\Users\me\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\me\AppData\Local\Programs\Python\Python38\python.exe
C:\Users\me\AppData\Local\Microsoft\WindowsApps\python.exe

(pysyft-8bj21zgT) C:\dev\pysyft>
```

Always use a virtualenv when creating python projects on a Desktop OS. The only time you don't need them is inside containers since thats already a kind of virtual environment with its own PATH, Python version and site-packages.

2) The syft version is totally wrong, it says its using a cache.
Maybe try installing with a more forceful command like:
```
$ pip install --upgrade syft
Collecting syft
  Downloading syft-0.3.0-py2.py3-none-any.whl (289 kB)
     |████████████████████████████████| 289 kB 6.4 MB/s
Collecting websockets
  Using cached websockets-8.1-cp36-cp36m-win_amd64.whl (66 kB)
Collecting aiortc
  Using cached aiortc-1.0.0-cp36-cp36m-win_amd64.whl (975 kB)
```

It should get version 0.3.0 right now.

The fact that you aren't getting an up to date version leads me to believe that perhaps your systems architecture isn't supported.

Can you run these two commands and how me the output:
```
```

**Comment by rahul-art** [comment]
try syft 0.2.9 it's a stable one

**Comment by madhavajay** [comment]
@sbasu26 Did you get a chance to run my commands or get this working?

**Comment by amva13** [comment]
Facing same issue from conda. Is syft not runnable from conda (i see the working example is from pyenv)?

**Comment by amva13** [comment]
Fixed. In my case, it turned out conda was using the system-wide pip and not the pip from the conda environment. seems like a conda bug actually... regardless, locating the bin file for the conda pip and using that pip should solve the problem.
