### ISSUE TITLE
How can I use pysyft 0.3.0 to do Federated Averagng? Is there a complete tutorial like that of pysyft 0.2.x?

### ISSUE THREAD

**Issue by lk1983823** [OpenMined/PySyft#4990]
I found a tutorial of FEDERATED LEARNING OF A RECURRENT NEURAL NETWORK ON RASPBERRY PIS
useful and instructive for pysyft 0.2.x. I wonder is there any example or tutorial for pysyft 0.3? In the mnist tutorial, I couldn't know how to use the 0.3 version package to do FL in two clients. Thanks.

**Comment by tudorcebere** [comment]
Hello @lk1983823,

This is the goal for us on the next few months, to reach feature parity with 0.2.x. We lack a few features yet to do FL, but as soon as we get them done, a similar tutorial to the one in 0.2.x will be released.

**Comment by lk1983823** [comment]
Thanks!

**Comment by quocnh** [comment]
> e lack a few features yet to do FL

Have you done with tutorial for FL with pysyft 0.3.x?

**Comment by vnt1537** [comment]
Waiting for the tutorial for FL on non IID dataset in pysyft 0.3

**Comment by rafaelaBrum** [comment]
Also waiting for this tutorial

**Comment by MissiontoMars** [comment]
Also waiting for this tutorial of 0.3
