### ISSUE TITLE
Reduce Memory Load on torch tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4992]
## Description
The torch tests being run in `merge_tests.yml` and run with: `pytest -m torch` make heavy use of pytest parametrization. Unfortunately this causes the memory of each permutation test to be held until they all complete which is leading to OOM errors on Windows in GitHub CI. Currently we are chunking them up to try to reduce the memory pressure. It would be great to fix this with a better solution. Either we could try to force some `del var` and `gc.collect()` or find another way to ensure that the memory doesn't grow with the number of tests.

## Definition of Done
Memory stays under 4 GB and doesn't cause OOM errors and require chunking on CI.

**Comment by devkumar24** [comment]
Hey @madhavajay, I want to work on this issue, could you help me to where to start from?

**Comment by madhavajay** [comment]
Hi @devkumar24 if you run the `python -m torch` tests inside the `0.4` branch and monitor your memory usage you will see that it gets pretty high. You can see in `allowlist_test.py` that the test is heavily parameterized:
```
@pytest.mark.torch
@pytest.mark.parametrize(
    "tensor_type, op_name, self_tensor, _args, is_property, return_type, deterministic",
    TEST_DATA,
)
def test_all_allowlisted_tensor_methods(
```

pytest is holding on to all these variables until the entire test method is finished all possible combinations, we need to find a way to reduce the amount of memory it uses by cleaning up in between or splitting up the parameterization into multiple tested functions to reduce the memory watermark.

**Comment by devkumar24** [comment]
I won't get it, Can you tell in brief?

**Comment by madhavajay** [comment]
Fixed here: https://github.com/OpenMined/PySyft/pull/5220
