### ISSUE TITLE
Delete pysyft.readthedocs.io

### ISSUE THREAD

**Issue by prajotsl123** [OpenMined/PySyft#4995]
No Documentation on [https://pysyft.readthedocs.io/en/latest/dev_environment.html]
The whole Developer documentation is empty
Since i want to work on client-server based real time project on federated learning

Plz update it
or send relevant links

**Comment by madhavajay** [comment]
Hi @prajotsl123 Yes the docs need generating and theres an open ticket for this in the mean time the contribution guide is fairly big already: https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md

**Comment by madhavajay** [comment]
@cereallarceny Says we will not be using https://pysyft.readthedocs.io anymore, so we should delete it.

**Comment by cereallarceny** [comment]
Do it, I agree. We'll be using Gitbook or something else. Definitely not
RTD.

**Comment by ShubhamPalriwala** [comment]
Can we close this issue now as it is solved (readthedocs sends a 404 maze)? @IrinaMBejan

**Comment by IrinaMBejan** [comment]
Great point @ShubhamPalriwala, thank you - closing it now!
