### ISSUE TITLE
can i launch data owner & data scientist (duet) on same PC..

### ISSUE THREAD

**Issue by prajotsl123** [OpenMined/PySyft#4998]
If Yes,,,,
Plz suggest the steps from which i can carry on

**Comment by rajatrc1705** [comment]
Yes you can, open two jupyter notebooks, name one Data Scientist and the other Data Owner.
The Data Scientist notebook should contain the code for Data Scientist, and same goes for Data Owner.
Launch the Flask server using following command:
`syft-network`
Now run the respective codes of both the Scientist and the Owner as given in the manual, I have given the link below.
https://github.com/OpenMined/PySyft/blob/dev/examples/duet/README.md

**Comment by prajotsl123** [comment]
ya thanks @rajatrc1705 
it worked ......
is there any way where i can connect multiple clients PC?

**Comment by tudorcebere** [comment]
Hello!

Thank you @rajatrc1705 for the help, your answer is correct! :100: 

@prajotsl123 yet we support only duet: only 2 entities can communicate over duet, upcoming work will introduce 2+ parties. Stay tuned!

**Comment by prajotsl123** [comment]
i was not asking on duet....
Like in general how can i have more than 1 clients
@tudorcebere

**Comment by tudorcebere** [comment]
We did not release anything else yet, we offer support only for duet right now.
