### ISSUE TITLE
The example update

### ISSUE THREAD

**Issue by Williance** [OpenMined/PySyft#5000]
There is only one example in duet：Image classification (MNIST) using Convnets.When will the other examples be updated?eg:Time sequence prediction - use an LSTM to learn Sine waves.

**Comment by tudorcebere** [comment]
Hello, @Williance!

We are working on getting all of them + many more. Stay tuned, more will show up in the next few weeks.

**Comment by xinxilwl** [comment]
> Hello, @Williance!
> 
> We are working on getting all of them + many more. Stay tuned, more will show up in the next few weeks.

Hello, is there any LSTM examples except Sine waves now?
