### ISSUE TITLE
Having multiple clients on single server?

### ISSUE THREAD

**Issue by prajotsl123** [OpenMined/PySyft#5003]
in syft 0.3 theres no **workers** module....
Any tutorial where i can follow .....
or any supported links which can help me solve my problem

**Comment by rahul-art** [comment]
check notebooks in this github   https://github.com/udacity/private-ai

**Comment by prajotsl123** [comment]
it doesnt have it,,,,
i want in real world case...not virtual

**Comment by koloskova** [comment]
> check notebooks in this github https://github.com/udacity/private-ai

this notebook is not working with the new version of syft 0.3

**Comment by rahul-art** [comment]
use this
pip install 'syft[udacity]'

**Comment by madhavajay** [comment]
@prajotsl123  An end-to-end example with PyGrid and Workers is coming soon, stay tuned.
