### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by harikrishnankh** [OpenMined/PySyft#5009]
I used the command **pip install syft** but it is showing an error, Cannot build wheel for av. I tried installing microsoft visual c++ build tools. Still the issue persist.
![error syft](https://user-images.githubusercontent.com/14846379/104362284-a3879280-5539-11eb-8814-a34aa2612ba5.PNG)

**Comment by madhavajay** [comment]
@harikrishnankh Please provide all of the relevant details required to debug such an error.
- OS version
- Python version
- Instructions followed
- Command ran
- Errors Outputted

**Comment by rahul-art** [comment]
follow this blog post https://blog.openmined.org/how-to-setup-pysyft-on-windows-10/

**Comment by madhavajay** [comment]
@harikrishnankh I can see mention of 3.9 in the output above, are you using Python 3.9? It's still not supported yet, so I would suggest using something lower like 3.8 if you can. Can you confirm the output of this command:
```
where python3
python3 --version
```

**Comment by harikrishnankh** [comment]
@madhavajay  I am using windows 10. I am running this on anaconda. My python version is 3.9.1. I will try to install python 3.8, Can you please recommend an exact version of python.

**Comment by harikrishnankh** [comment]
@madhavajay 
Successfully installed syft  after changing python version to 3.8.0
Thank you for your help!

But a new issue raised. An Attribute error while importing syft. torchvision.datasets has no attribute visiondataset. Please check the attachment for more details

I tried importing syft module alone, but the issue still persists.

## Screenshots
![e1](https://user-images.githubusercontent.com/14846379/104411930-5df6b400-5591-11eb-8f13-a116292b0264.PNG)
![e2](https://user-images.githubusercontent.com/14846379/104411936-5f27e100-5591-11eb-8790-cb6581b069d3.PNG)

**Comment by madhavajay** [comment]
@harikrishnankh the Torch Vision API hasn't been completely added yet. This would probably be a pretty easy fix. If you would like to open a PR that would be greatly appreciated. See `src/syft/lib/torchvision/allowlist.py`

**Comment by madhavajay** [comment]
Closing this for now. https://github.com/OpenMined/PySyft/issues/5186
