### ISSUE TITLE
AttributeError: module 'torchvision.datasets' has no attribute 'VisionDataset'

### ISSUE THREAD

**Issue by harikrishnankh** [OpenMined/PySyft#5010]
## Description
I tried to import syft package to run a federated leaning code using MNIST dataset. I am now stuck with an attribute error after importing the packages.

## Code

import pickle
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset,DataLoader
import time
import copy
import numpy as np
import syft as sy
from syft.frameworks.torch.federated import utils
from syft.workers.websocket_client import WebsocketClientWorker

## Screenshots
![e1](https://user-images.githubusercontent.com/14846379/104409313-0144ca80-558c-11eb-9f31-a3cc3c52fa40.PNG)
![e2](https://user-images.githubusercontent.com/14846379/104409318-0275f780-558c-11eb-8211-49b2f37cbfb3.PNG)

## System Information
 - OS: Windows 10
 - Language Version: Python 3.8.0
 - Package Manager Version: Conda 4.8.2,

**Comment by rahul-art** [comment]
it looks like orchvision is not installed

**Comment by Leo3967** [comment]
install torchvision or update torchvision

**Comment by harikrishnankh** [comment]
can you please mention a stable version of torchvision

**Comment by harikrishnankh** [comment]
will torch vision package automatically add with syft?

**Comment by rahul-art** [comment]
in requirements.txt you can see clearly that it is installing torch>=1.5 and the version of torch vision which is compatible with that 
if you want stable pysyft i say go with pi install syft=0.=2.9

**Comment by harikrishnankh** [comment]
Thanks, I'll check it out.

**Comment by harikrishnankh** [comment]
I tried installing syft 0.2.9 but I got the error:" Could not find a version that satisfies the requirement torch~=1.4.0 (from syft)"
I tried installing pytorch 1.4,0 manually, but got the same error

**Comment by madhavajay** [comment]
@harikrishnankh what python version are you using? Python 3.9 is not supported by syft==0.2.9 or any version of syft currently.

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
