### ISSUE TITLE
Rounding Off Placeholders and Tensors in Plans using NumPy

### ISSUE THREAD

**Issue by mustansarsaeed** [OpenMined/PySyft#5014]
Hi, I am using `pysyft 0.2.x`. I want to round computed `gradients`. Can anyone please give me a pointer how can I round of gradients computation in `loss.backward()` step? 

Secondly, after `loss.backward()` in `@sy.func2plan()`, I am rounding off `param.grad` using following code:

```
rounded_result = np.around(param.grad.detach().numpy(), decimals=7)
converted_tensor =  th.from_numpy(rounded_result)
```

I am getting error:

> <ipython-input-125-85c5022c7fb7> in naive_sgd(param, rounding, **kwargs)
>       2     if rounding:
>       3             rounded_result = np.around(param.grad.detach().numpy(), decimals=7)
> ----> 4             converted_tensor =  th.from_numpy(rounded_result)
>       5             return param - kwargs['lr'] * converted_tensor
>       6     else:
> 
> **TypeError: expected np.ndarray (got PlaceHolder)**

Can anyone please help.

Thank you.

**Comment by rahul-art** [comment]
@mustansarsaeed  you can do  it like this
![pysyfit_issure_solved](https://user-images.githubusercontent.com/56379013/104660672-08371e80-56ed-11eb-975b-c08c1185206f.png)

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
