### ISSUE TITLE
Autoapprove requests made by root clients

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5015]
## Description
Requests made by root clients in the `VirtualMachine` context should be automatically accepted.

## How to Reproduce
```
import syft as sy
alice = sy.VirtualMachine(name="alice")
alice_client = alice.get_root_client()

alice_client.torch.Tensor([1, 2, 3]).get(
    request_block=True,
    name="Test"
)
```

## Expected Behavior
To receive the requested object.

**Comment by devkumar24** [comment]
Hey, I want to work on this issue, can you help from where to get started?

**Comment by uid42** [comment]
Can I work on this?

**Comment by avinsit123** [comment]
@tudorcebere I am getting the following error(in screenshot) when I run your code snippet. I am not able to understand the purpose of `request_block = True` as when I use a normal `Tensor([1,2,3]).get()` I am able to retrieve the tensor from alice_client . Do you want the .get() function to still return if the `request_block` is set to `True` .
![Screenshot 2021-01-19 at 12 22 20 PM](https://user-images.githubusercontent.com/33565881/104998712-af031e00-5a51-11eb-8809-c2123344fc62.png)

**Comment by tudorcebere** [comment]
Hi all!

An issue will be assigned after a PR is opened to tackle the progress/give feedback.

Open a PR and ping me where you get stuck, thank you for your interest in syft!
