### ISSUE TITLE
KerasHook is not working

### ISSUE THREAD

**Issue by rahul-art** [OpenMined/PySyft#5016]
## Description
kerashook is not working

## System Information
 - OS: [ubuntu]
 - Language Version: [e.g. Python 3.7,]
 - Browser (if applicable): [e.g. Google Chrome]
![Screenshot from 2021-01-14 19-53-13](https://user-images.githubusercontent.com/56379013/104603713-b073c580-56a2-11eb-84f5-a8f9df5edbee.png)

**Comment by madhavajay** [comment]
Do you have syft `0.2.x` installed? There is no KerasHook in 0.3+ anymore.

**Comment by madhavajay** [comment]
Also try installing tf_encrypted:
```
$ pip install tf_encrypted
```
https://github.com/OpenMined/PySyft/issues/4875
