### ISSUE TITLE
Add Encryption to Transport Layer

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5022]
## Description
WebRTC Transport layer needs encryption.

## Definition of Done
Encryption in transit is added to the WebRTC code and turned on by default.

**Comment by wip-abramson** [comment]
I would strongly advocate for exploring DIDComm as a potential solution to this - https://identity.foundation/didcomm-messaging/spec/

It may be a future improvement to this one, but certainly something we should keep in mind.

**Comment by madhavajay** [comment]
It turns out WebRTC is using encryption with `DTLS` so we can close this for now.
