### ISSUE TITLE
Flaky Duet Test

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5024]
## Description
The test in tests/syft/grid/duet/duet_test.py can fail due to a race conditional/already used port, etc.

## How to Reproduce
Remove the `@pytest.mark.skip` decorator from the test and run it multiple times.

## Expected Behavior
The test must pass.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by bcebere** [comment]
I can work on this one.
