### ISSUE TITLE
TODOs fix - Torchvision - mean and std

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5031]
## Description
In `src/syft/lib/torchvision/allowlist.py` we have a TODO: `mean and std are actually tuples`. 

## Additional Context
The fix has to be made and a test has to be written.

## Note
This issue will not be assigned to anybody until a PR is opened.

**Comment by avinsit123** [comment]
@tudorcebere I hv opened a PR for the same. This is my first time contributing to this repo. Pls look at the PR and provide guidance if I am headed in the right direction.

**Comment by madhavajay** [comment]
So it turns it out mean and std aren't tuples, Normalize is the tuple, so its mean and std are what ever you want them to be... 😬

```
>>> a = torchvision.transforms.Normalize(1, 1)
>>> a
Normalize(mean=1, std=1)
>>> type(a.mean)
<class 'int'>

>>> b = torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
>>> b
Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
>>> type(b.std)
<class 'tuple'>

😱
>>> c = torchvision.transforms.Normalize([0.5, 0.5, 0.5], (0.5, 0.5, 0.5))
>>> c
Normalize(mean=[0.5, 0.5, 0.5], std=(0.5, 0.5, 0.5))
>>> type(c.mean)
<class 'list'>

>>> d = torchvision.transforms.Normalize(torch.Tensor([0.5, 0.5, 0.5]), (0.5, 0.5, 0.5))
>>> d
Normalize(mean=tensor([0.5000, 0.5000, 0.5000]), std=(0.5, 0.5, 0.5))
>>> type(d.mean)
<class 'torch.Tensor'>

😱😱😱
>>> e = torchvision.transforms.Normalize("test", (0.5, 0.5, 0.5))
>>> e
Normalize(mean=test, std=(0.5, 0.5, 0.5))
>>> e.mean
'test'

```

**Comment by madhavajay** [comment]
Looks like it ends up as this:
```
```

**Comment by avinsit123** [comment]
Ok, I see but if u have a look at the parameters for `normalize` we can see that in the function `mean` and `std `both are List[Float] type so shouldn't we just allow `syft.python.lib.List `

https://github.com/pytorch/vision/blob/ced96a0ca66e35ae61b64267e083fc3e3a62172a/torchvision/transforms/functional.py#L297 - have a look at this

**Comment by madhavajay** [comment]
Yes, although the types ultimately mean nothing, all that matters is it gets passed to `torch.as_tensor()` so I think we should allow anything which can get passed into that which so far seems like, int, float, Tuple and List, and probably Tensor and Numpy's ndarray.

```
>>> import torch
>>> torch.as_tensor(1)
tensor(1)
>>> torch.as_tensor(1.1)
tensor(1.1000)
>>> torch.as_tensor([1])
tensor([1])
>>> torch.as_tensor((1, 2))
tensor([1, 2])
array([1, 2, 3])
>>> torch.as_tensor(a)
tensor([1, 2, 3])
>>> torch.as_tensor({1, 2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not infer dtype of set
>>> torch.as_tensor({1.1, 2.1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not infer dtype of set
>>> torch.as_tensor({1.1, 2.1})
KeyboardInterrupt
>>> {"a":1}
{'a': 1}
>>> torch.as_tensor({"a": 2.1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not infer dtype of dict
>>>
```

**Comment by avinsit123** [comment]
Ok I see, yes then we should add support for all types
