### ISSUE TITLE
TODOs fix - Torchvision - normalize 

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5032]
## Description
In `src/syft/lib/torchvision/allowlist.py` we have a TODO: ` Normalize properties only exists on the object not on the class?`. 

## Additional Context
The fix has to be made and a test has to be written that the methods are working and are added to the allowlist.

## Note
This issue will not be assigned to anybody until a PR is opened.

**Comment by stoic-signs** [comment]
Hey, I noticed there hasn't been much progress here and that the other PRs were closed. Could I work on it?
