### ISSUE TITLE
TODOs fix - Torchvision - Compose.transforms

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5033]
In `src/syft/lib/torchvision/allowlist.py` we have a TODO: `Compose.transforms property only exists on the object not on the class?`. 

## Additional Context
The fix has to be made and a test has to be written.

## Note
This issue will not be assigned to anybody until a PR is opened.

**Comment by rahul-art** [comment]
i created PR #5064 try to solve this issue give some guidance to solve this
