### ISSUE TITLE
TODOs fix - TorchModule - make work nested

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5035]
## Description
In `src/syft/lib/torch/module.py` we have a TODO: `make work nested with a counter and add tests`. 

## Additional Context
The fix has to be made and a test has to be written that the methods are working and are added to the allowlist.

## Note
This issue will not be assigned to anybody until a PR is opened.

**Comment by madhavajay** [comment]
We also need the top level to work properly.
