### ISSUE TITLE
Fix issue with AWS / Proxy not connecting

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5047]
## Description
A user has reported being unable to connect to their notebook on an AWS instance through a proxy.
We should investigate this and GCE to see if there are any particular network settings which are required or if this is just an issue with the proxy and what can be done to resolve it.

This might be related to the Colab issue: https://github.com/OpenMined/PySyft/issues/4738

## Definition of Done
Determine what combinations work:
AWS Instance -> Local Notebook
AWS Instance -> AWS Instance
GCE Instance -> Local Notebook
GCE Instance -> GCE Instance

Investigate the issue and propose a solution to any connectivity problems.

**Comment by christiandompierre** [comment]
I didn't test GCE, only AWS.
In my case, I have the following behavior:
 - data owner AWS <-> data scientist local network: doesn't work (there's no timeout either, it just sits there indefinitely).
 - data owner AWS <-> data scientist AWS: works fine
 
Note that the VM on AWS is behind a proxy
