### ISSUE TITLE
Replace all Commented out Tests with @pytest.mark.xfail

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5054]
## Description
There are a lot of tests that have been commented out with TODOs like:

```
# TODO this should work
# assert Int(Foo0()) == 42
```

These should be uncommented and the tests should be marked as @pytest.mark.xfail

## Definition of Done
All failing tests are being run with @pytest.mark.xfail instead of being commented out.

**Comment by ariannmichael** [comment]
I would like to take this issue
