### ISSUE TITLE
Figure out GitHub CI Warnings

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5056]
## Description
Bonus points to who ever can figure out why these warnings happen and how to get rid of them. They don't seem to be an issue but they clutter up the CI reports.

<img width="1114" alt="Screen Shot 2021-01-22 at 3 43 27 pm" src="https://user-images.githubusercontent.com/2882739/105451679-af591e80-5cc8-11eb-9802-82c38e23d1ab.png">

## Definition of Done
These warnings are removed.

**Comment by tacitvenom** [comment]
Could you also help me with the CI build where this occurs please?

**Comment by madhavajay** [comment]
@tacitvenom its all of them 😊
https://github.com/OpenMined/PySyft/actions

**Comment by tacitvenom** [comment]
Apologies for my ignorance, I still couldn't locate it. Would it be possible for you to share a link to the exact line where this occurs, for example? Or the step?

a simple search doesn't yield much, I looked at a few steps but to no avail, unfortunately.

**Comment by lucastliu** [comment]
Here's an example:
https://github.com/OpenMined/PySyft/runs/1834413505?check_suite_focus=true
Look under "Post Run actions/checkout@v2"

I peeked at a couple of builds. The warnings all spit from the same issue "fatal: No url found for submodule path 'docs/_themes/sphinx-theme-graphite' in .gitmodules"

Looks like your documentation tool theme (sphinx-theme-graphite) submodule is not being recognized. Is your theme file even supposed to be a submodule? Why not just have a regular file to define the theme?

In any case, this does not seem like a critical part of the codebase.

**Comment by madhavajay** [comment]
@lucastliu Awesome, great catch! ❤️ The `.gitmodules` file must have been deleted a long time ago but not properly removed from git itself.

I ran this to confirm that it still thought there should be some kind of submodule:
```
$ git submodule status
```

Then to remove it:
```
$ git rm docs/_themes/sphinx-theme-graphite
```

Let's see if this fixes the issue.
