### ISSUE TITLE
Benchmarking Inference and Training Latency on Android

### ISSUE THREAD

**Issue by phoenix-meadowlark** [OpenMined/PySyft#5060]
## Question
Is there a recommended flow for compiling TensorFlow and PyTorch models to target Android and benchmark inference and training latency on device?

## Further Information
I would like to compile some simple TensorFlow and PyTorch models for on-device training with a few optimizers, and benchmark their inference and training latency on a Pixel phone. One of my target use cases is single device real-time meta-learning from user inputs.

It seems like most of the tutorialized APIs in PySyft and KotlinSyft are designed around multi-party training, but I'm hoping there's a way to interact with the compiler/runtime at a lower level for single-device use cases.

I've looked through the docs and examples for PySyft and KotlinSyft but didn't find anything on working with single devices. [This](https://pysyft.readthedocs.io/en/latest/codebase_walkthrough.html) seems like it would be helpful, but it looks like the readthedocs site is still in development?

Could you point me in the direction of where I should be looking in the codebase(s)?

**Comment by cereallarceny** [comment]
Interesting question - I feel that @vkkhare might be your best bet for help on this. I'll assign this ticket to him @phoenix-meadowlark.

**Comment by vkkhare** [comment]
Benchmarking currently is not supported in KotlinSyft. If you want, you can explicitly write tests/timestamp evaluations for benchmarking in kotlin. Also, you don't need to run multiple devices, you can set the number of workers to 1 in pygrid server config.
