### ISSUE TITLE
Accepting requests on objects from an iterable

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5069]
## Description
We would like to be able to do on the DS side:
```
torch_ptr = duet.torch.Tensor([1, 2, 3])
torch_ptr[0].request(reason="some reason")
```
And on the DO side:
```
duet.requests[0].accept()
```
Currently, the execution fails due to unknown UID of torch_ptr[0] in the store.

## Expected Behavior
We would like to be able to get the described object.

## Additional Context
The issue will be assigned after a PR will be opened. The PR has to have the base branch the `0.4` one.

**Comment by ayush268** [comment]
Hi, I think there is a bug in the functionality provided here,

When we execute the following statement from the DS side:

```
torch_ptr = duet.torch.Tensor([1, 2, 3])
```

It adds the data in the store of the Data Owner beforehand (even before administering the request itself). The Data Scientist can flood the data store of the data owner via this, an example

```
>>> duet.store.pandas
                                        ID Tags Description             object_type
0  <UID: cd63b75dfa55405eaabe28546e7b9717>  [x]      xasdad  <class 'torch.Tensor'>
1  <UID: e50520210b4244ca87eb274c4659f997>   []              <class 'torch.Tensor'>
2  <UID: 4ca9b63f45534f7a8e53bee1bec5bb96>   []              <class 'torch.Tensor'>
3  <UID: 01a56e5218884d90b0b396869959001b>   []              <class 'torch.Tensor'>
4  <UID: 38560424aacf44af834daf73b6236927>   []              <class 'torch.Tensor'>

>>> duet.store[0].get()
tensor([1., 2., 3.])
```
