### ISSUE TITLE
IndexError: too many indices for tensor of dimension 

### ISSUE THREAD

**Issue by Linardos** [OpenMined/PySyft#5070]
## Description
Using a boolean matrix I wanted to index a matrix with zero elements. This produces an error if TorchHook is active. (For my particular case the reason I wanted this was to split a segmentation mask to 3 parts, but here I show you a minimal reproducible code to investigate the error). 

## A small reproducible example:
```
import torch
import syft as sy
import matplotlib.pyplot as plt

# This will work
bool_mat= (torch.FloatTensor(torch.Size([10, 1, 150, 150, 10])).uniform_() > 0.8).type(torch.uint8)   
test_mask = torch.zeros(bool_mat.shape)
test_mask[bool_mat==1]=1
plt.imshow(test_mask[7,0,...,4])

# This will not work
hook = sy.TorchHook(torch)
bool_mat= (torch.FloatTensor(torch.Size([10, 1, 150, 150, 10])).uniform_() > 0.8).type(torch.uint8)   
test_mask = torch.zeros(bool_mat.shape)
test_mask[bool_mat==1]=1
plt.imshow(test_mask[7,0,...,4])
```

## Screenshots
![image](https://user-images.githubusercontent.com/26694607/106269022-973b4f00-6234-11eb-8895-434f335dec48.png)

**Comment by iamtrask** [comment]
Looks like this is still on 0.2.x. Have you tried on the latest version?

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
