### ISSUE TITLE
Investigate pytest warnings

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5075]
## Description
When running the test suite, a ton of warning are currently raised. One should take a look at them and:
* solve them if they are short fixes
* create issues out of them if they are hard to solve

**Comment by ariannmichael** [comment]
I would like to take this issue

**Comment by madhavajay** [comment]
We should make sure to run:
```
$ pytest -m 'fast or slow' --no-cov -n auto
```

There are a number of warnings that come from the slow tests and we can check the `torch` tests as well but since its a single test with parameterization I wouldn't expect many.

Right now on `dev` im getting:
```
= 2120 passed, 1 skipped, 4 xfailed, 4171 warnings in 64.62s (0:01:04) ==
```

**Comment by ariannmichael** [comment]
Oh thanks @madhavajay , I was just running:
`$ pytest -m fast -n auto`
that was the one I saw on the CONTRIBUTING.md.
Sorry, I'll be looking up again.

**Comment by ariannmichael** [comment]
Hello @madhavajay and @tudorcebere, I check again running ` $ pytest -m 'fast or slow' --no-cov -n auto ` and was raised 4117 warnings. I did some changes that is on the PR #5125 and decrease to 24 warnings.

Then I opened issues for the warnings there are left, the issues are #5137, #5138, #5139, #5140, #5141, #5142, #5143.

I think that with this, this issue can be closed.
