### ISSUE TITLE
Tags for pointers generated mid-computation

### ISSUE THREAD

**Issue by H4LL** [OpenMined/PySyft#5076]
## Feature Description
With the new mechanism for requests, where I reference the tag of the variable I am requesting, it has become more difficult to pull back pointers which are the product of some computation. Let's say I want to pull back 'pred_ptr' from

`pred_ptr = model_ptr(x_ptr)
`
In order to request pred_ptr I need to reference its tag, however it currently has no tag as it was generated through some computation on the Data Scientist side. I propose the following new features to get around this;

- pointers should _inherit the tags_ of the variables they are generated from further up in the computation graph. If pointers of are the product of multiple tagged pointers, we make each tag present go with the permissions of the most restrictive tag . In this case that would mean all tags must have been given the OK by the Data Owner to be pulled back by the Data Scientist.
- There may be times where the Data Scientists needs to reference a newly created variable to the Data Owner by some unique tag. In this circumstance it'd be good to be able to tag a pointer.

## Is your feature request related to a problem?
I need to auto-allow the retrieval of the result of a computation in a loop but I can't do it bc the resultant pointer is not reference-able in a handler.

## Data Scientist
![Screenshot 2021-01-31 at 13 34 38](https://user-images.githubusercontent.com/46713492/106385601-119cd800-63c9-11eb-841b-436080d60f5a.png)

## Data Owner
![Screenshot 2021-01-31 at 13 36 59](https://user-images.githubusercontent.com/46713492/106385672-66405300-63c9-11eb-95b1-794ca68d0391.png)

## What alternatives have you considered?
At the moment my workaround is just to add a handler with no tags which accepts everything. This isn't ideal though as there should be some access control in the notebook.

**Comment by madhavajay** [comment]
Update here: https://github.com/OpenMined/PySyft/pull/5205
