### ISSUE TITLE
Using custom dataset with Duet

### ISSUE THREAD

**Issue by LasTAD** [OpenMined/PySyft#5078]
## Question
Is there any possibility to work with custom dataset with Duet?

## Further Information
I tried adapting the existing MNIST example for a different [dataset](https://www.kaggle.com/gloseto/traffic-driving-style-road-surface-condition) and ran into the impossibility of creating my own dataset and sending it to Duet. Whichever side (DO or DS) I try to create a dataset, either it is impossible to serialize the DataLoader, or the remote Torch does not contain TensorDataset.

## Screenshots
<img width="702" alt="Снимок экрана 2021-01-31 в 21 09 33" src="https://user-images.githubusercontent.com/10279149/106393518-a07d1500-6408-11eb-90d5-3c8570a90237.png">

## System Information
 Running in Colab

## Additional Context
I will describe the process: I create tensors on the DO side, then use the `torch.Tensor.send()` method to transfer tensors to Duet, on the DS side I receive tensor copies by `pointer.get_copy()`, create a TensorDataset, then a DataLoader.

**Comment by geoffkip** [comment]
I am having this exact same issue. Is there any way in Pysyft to create a Custom Dataset pointer using remote tensor pointers? Ultimately I need to use this in a remote torch dataloader etc.

**Comment by madhavajay** [comment]
@LasTAD There is an example of using a different dataset in one of the SuperResolution notebooks which is close to being merged. https://github.com/OpenMined/PySyft/pull/5122

We will be creating more examples and documentation for the next release.

**Comment by geoffkip** [comment]
@madhavajay Thank you! This is exactly what I was looking for. Appreciate you sharing!

**Comment by dylanil** [comment]
Hi I can't seem to find the notebook in any of the branches anymore. Does anyone have the solution? I noticed an older version of PySyft (before Duet) had:

base=sy.BaseDataset(torch.from_numpy(X_train),torch.from_numpy(y_train))

But I would love to find the Duet version equivalent. My non-federated model uses a pretty simple dataset which I'd like to replicate:

class RegressionDataset(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)
