### ISSUE TITLE
Duet: send a model in the store for debugging purposes.

### ISSUE THREAD

**Issue by bcebere** [OpenMined/PySyft#5080]
## Description
For the TenSEAL training/inference scenarios, I want to compare the encrypted results with the plain results.
More specifically, I want to evaluate N ciphertexts with a model and get their accuracy.
Then, I want to test the N underlining plaintexts with the same model and get the plain accuracy.

Then, I want to show a comparison between the plain accuracy and the encrypted accuracy. 
But for the second step, I have to share the model with the DO instance.

The model inherits sy.Module, but I cannot add tags on Duet send.

model.send(duet, tags=["model"])
results in the error
```
TypeError: send() got an unexpected keyword argument 'tags'
```
I cannot retrieve the model_ptr otherwise

## System Information
 - Language Version: Python 3.8

**Comment by madhavajay** [comment]
@bcebere We also need something similar for Opacus so we can remotely attach the PrivacyEngine to the model. The way the SyModule currently works is its a thin veneer over the submodule layers. Perhaps we can simply create a real torch module on either side inside the SyModule to help attach all of the layers to thus providing a very real normal model to get a pointer to. The main issue is that `send` requires serialization so if we want to send the whole model we need to support sending everything the model supports where as currently we just invoke the creation of the same modules remotely. I would love some input on the best way to tackle this one.

**Comment by madhavajay** [comment]
@bcebere this is resolved now that torch.nn.module is serializable properly.
