### ISSUE TITLE
Add support for slice objects

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5082]
## Description
We don't have support for `slice` objects. We would like to add slices in our primitive supported types.

TODO:
- [x] Add some serde tests
       The proto only takes ints so you might need to change that to support None as well.
- [ ] Add the tests from CPython: https://github.com/python/cpython/blob/3.9/Lib/ctypes/test/test_slicing.py
- [ ] Add the CPython test filename to the LICENSE.txt file
- [x] Make sure Slice works on other types like Tensor or Pandas
        If there are issues we might need to override the Pointer with a wrapped __getitem__
- [ ] Make sure that __setitem__ also works: https://stackoverflow.com/questions/32772755/how-do-getitem-setitem-work-with-slices
- [x] Add to `primitive_factory`

Theres a bit of work here so it might make sense if we split it up. Could you start by writing some tests for the `serde` and fixing up the proto?

## Additional Context
We would like to have wrappers for slice objects, to be able to manipulate them.

**Comment by dnabanita7** [comment]
I want to work on this.

**Comment by madhavajay** [comment]
See: https://github.com/OpenMined/PySyft/pull/5228
