### ISSUE TITLE
import syft error

### ISSUE THREAD

**Issue by shujaat81** [OpenMined/PySyft#5083]
Tried to install syft in windows using anaconda virtual environment, installation went successfull. But when trying to import syft, I get the following error:``---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-44770bd007ea> in <module>
----> 1 import syft
~\Anaconda3\envs\lasttest\lib\site-packages\syft\__init__.py in <module>
     59 from syft.core.common.serde.serialize import _serialize as serialize  # noqa: F401
     60 from syft.core.node.common.service.repr_service import ReprMessage  # noqa: F401
---> 61 from syft.core.node.device.device import Device  # noqa: F401
     62 from syft.core.node.device.device import DeviceClient  # noqa: F401
     63 from syft.core.node.domain.domain import Domain  # noqa: F401
~\Anaconda3\envs\lasttest\lib\site-packages\syft\core\node\device\__init__.py in <module>
      1 # syft relative
----> 2 from .client import DeviceClient
      3 from .device import Device
      4 
      5 __all__ = ["DeviceClient", "Device"]
~\Anaconda3\envs\lasttest\lib\site-packages\syft\core\node\device\client.py in <module>
     14 from ...io.location import SpecificLocation
     15 from ...io.route import Route
---> 16 from ..common.client import Client
     17 
     18 
~\Anaconda3\envs\lasttest\lib\site-packages\syft\core\node\common\client.py in <module>
     18 from ....core.pointer.pointer import Pointer
     19 from ....decorators import syft_decorator
---> 20 from ....lib import lib_ast
     21 from ....proto.core.node.common.client_pb2 import Client as Client_PB
     22 from ....proto.core.node.common.metadata_pb2 import Metadata as Metadata_PB
~\Anaconda3\envs\lasttest\lib\site-packages\syft\lib\__init__.py in <module>
     24 
     25 # constructor: copyType = create_lib_ast
---> 26 lib_ast = create_lib_ast()
     27 lib_ast._copy = create_lib_ast
~\Anaconda3\envs\lasttest\lib\site-packages\syft\lib\__init__.py in create_lib_ast()
     11     python_ast = create_python_ast()
     12     torch_ast = create_torch_ast()
---> 13     torchvision_ast = create_torchvision_ast()
     14     # numpy_ast = create_numpy_ast()
     15 
~\Anaconda3\envs\lasttest\lib\site-packages\syft\lib\torchvision\__init__.py in create_torchvision_ast()
     37         if version_supported(support_dict=return_type_name_or_dict):
     38             return_type = get_return_type(support_dict=return_type_name_or_dict)
---> 39             ast.add_path(
     40                 path=method,
     41                 framework_reference=tv,
~\Anaconda3\envs\lasttest\lib\site-packages\syft\ast\globals.py in add_path(self, path, index, return_type_name, framework_reference)
     63         attr = self.attrs[framework_name]
     64         if hasattr(attr, "add_path"):
---> 65             attr.add_path(  # type: ignore
     66                 path=path, index=1, return_type_name=return_type_name
     67             )
~\Anaconda3\envs\lasttest\lib\site-packages\syft\ast\module.py in add_path(self, path, index, return_type_name, framework_reference)
    118             self.lookup_cache[attr_ref] = path
    119         if hasattr(attr, "add_path"):
--> 120             attr.add_path(  # type: ignore
    121                 path=path, index=index + 1, return_type_name=return_type_name
    122             )
~\Anaconda3\envs\lasttest\lib\site-packages\syft\ast\module.py in add_path(self, path, index, return_type_name, framework_reference)
     69     ) -> None:
     70         if path[index] not in self.attrs:
---> 71             attr_ref = getattr(self.ref, path[index])
     72 
     73             if isinstance(attr_ref, module_type):
AttributeError: module 'torchvision.datasets' has no attribute 'VisionDataset'``

**Comment by madhavajay** [comment]
@shujaat81 this is strange, `torchvision.datasets.VisionDataset` is available in torch>=0.5 at least. Can you confirm what version of torchvision you have and that if you go to a python console and type and show what your output is:
```
import torchvision
torchvision.__version__
torchvision.datasets.VisionDataset
```

For me with torchvision 0.5 I get:
```
>>> import torchvision
>>> torchvision.__version__
'0.5.0'
>>> torchvision.datasets.VisionDataset
<class 'torchvision.datasets.vision.VisionDataset'>
```

**Comment by shujaat81** [comment]
@madhavajay As I can see I have the latest one:
`>>> import torchvision
>>> torchvision.__version__
'0.8.2'
>>> torchvision.datasets.VisionDataset
<class 'torchvision.datasets.vision.VisionDataset'>
>>> 
`

**Comment by madhavajay** [comment]
@shujaat81 Can you please let us know what version of Windows and Python you are using, what the version of Syft you are using is (or commit hash, if you run pip freeze you can see what version) and the commands you ran to cause the issue?
