### ISSUE TITLE
Tagging ListPointer with a list results in one tag entry

### ISSUE THREAD

**Issue by Rene36** [OpenMined/PySyft#5086]
## Description
PySyft allows to add one or multiple tags to each pointer with `pointer.tag("tag1", "tag2", "tag3")`. However, they have to be added separately and using a list for tagging like `pointer.tag(["tag1", "tag2", "tag3"])` adds the whole list as one tag and not three separate tags. `pointer.tag(["tag1", "tag2", "tag3"])` results in pointer.tags -> [["tag1", "tag2", "tag3"]]

## How to Reproduce
`import syft as sy`
`from syft.lib.python.list import List`
`bob = sy.VirtualMachine(name="Bob")`
`bob_client = bob.get_client()`
`pointer = List([0, 1, 2, 3])`
`pointer.tag(["tag1", "tag2", "tag3"])`

## Expected Behavior
`pointer.tag()` takes a list as an argument and tags the pointer with all tags from that list separately.
`pointer.tag(["tag1", "tag2", "tag3"])` should result in pointer.tags = ["tag1", "tag2", "tag3"]

## Screenshots
None

## System Information
 - OS: Ubuntu
 - OS Version: 20.04.2 LTS
 - Language Version: Python 3.8.3
 - Package Manager Version: Conda 4.8.3
 - Browser (if applicable): -
 - Browser Version (if applicable): -

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
Syft 0.3.0

**Comment by madhavajay** [comment]
@Rene36 If you want to update the code to accept both a list and the varadic args that would be great.
I'm getting `TypeError: unhashable type: 'list'` for your example though, not a nested list.
