### ISSUE TITLE
Question about SMPC example

### ISSUE THREAD

**Issue by eddykaya** [OpenMined/PySyft#5090]
## Question
Regarding [this example](https://notebook.community/OpenMined/PySyft/examples/tutorials/advanced/Encrypted%20Linear%20Regression) and after reading the linked papger, I do not understand if data remains at the workers or if data is transported across the network.

## Further Information
The examples uses EncryptedLinearRegression. Is test data transported encrypted via the network or only training results?

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
