### ISSUE TITLE
Fix usage of request name vs tag in Notebooks and Docs

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5102]
## Description
**Note:** Do this off dev once 0.4 is merged
- Fix all broken references to handler `name` and add new handler `tag`:
```
/examples/differential-privacy/pydp
/examples/differential-privacy/opacus
/examples/homomorphic-encryption (should already be done)
/examples/private-set-intersection
/examples/secure-multi-party-computation
```

- Remove unused examples folder:
```
/examples/experimental
```

- Rename duet folder
```
/examples/duet
```
to:
```
/examples/pytorch
```
- Search docs and READMEs for references to `examples/duet` and update
- Search docs and READMEs for references to `add_handler(name=)` / `get/request(name=)`

**Comment by bhadreshpsavani** [comment]
Can I work on this?

**Comment by madhavajay** [comment]
@bhadreshpsavani Sure, but make sure to push a PR while you are working on it so that if we need to help get it ready for merging your commits will be included.

**Comment by apzl** [comment]
@bhadreshpsavani are you working on this, or else I'm interested.

**Comment by bhadreshpsavani** [comment]
@apzl I haven't started yet, 
If you are interested to work on please go ahead
