### ISSUE TITLE
I get syft.frameworks isn't a module error

### ISSUE THREAD

**Issue by dnabanita7** [OpenMined/PySyft#5134]
## Description
I have downloaded syft 3.0, 0.2.9 and 0.2.8. syft 3.0 shows this error. While syft 0.2.9 and syft 0.2.8 shows mismatched torch version. I use the latest version of pytorch.

```
Collecting syft==0.2.8
  Downloading syft-0.2.8-py3-none-any.whl (415 kB)
     |████████████████████████████████| 415 kB 71 kB/s  eta 0:00:01
Requirement already satisfied: websockets~=8.1.0 in /home/nabanita07/anaconda3/envs/pysyft/lib/python3.9/site-packages (from syft==0.2.8) (8.1)
ERROR: Could not find a version that satisfies the requirement torch~=1.4.0 (from syft)
ERROR: No matching distribution found for torch~=1.4.0
```

## How to Reproduce
1. !pip install syft==0.2.9 or lower versions
2. See the error

## Expected Behaviour
0.2 versions and lower of syft doesn't support PyTorch's latest version. Syft 3.0 doesn't support the latest versions of frameworks package. Shall I have to downgrade PyTorch's version?

## System Information
 - OS: [e.g. Ubuntu Linux]
 - Language Version: [e.g. Python 3.8]
 - Package Manager Version: [e.g. Conda latest]
 - Browser (if applicable): [e.g. Google Chrome latest]

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
