### ISSUE TITLE
Add Runtime TypeChecking to Public API

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5136]
## Description
Define what is the Public API and consider adding back the TypeChecking decorator perhaps first by creating a @public decorator so we can keep track of what we consider to be public API and introduce some versioning / deprecation features.

## Definition of Done
- Public API is marked
- Methods are dynamically typechecked
- Tests are benchmarked to ensure there is no severe performance regressions

**Comment by public** [comment]
I love finding out about cool libraries because of this username :D

**Comment by madhavajay** [comment]
@public hahahah lol... welcome. Syft is a very cool library.
