### ISSUE TITLE
Markdown not rendered in documentation

### ISSUE THREAD

**Issue by stefanv** [OpenMined/PySyft#5144]
At https://pysyft.readthedocs.io/en/latest/index.html there are a bunch of HTML tags, as if the page was rendered using RST instead of Markdown.

**Comment by madhavajay** [comment]
@stefanv yes, the docs have not been properly rebuilt yet.
We have several PRs and issues to:
- implement a docstring checker: https://github.com/OpenMined/PySyft/pull/5123
- fix the documentation build warnings: https://github.com/OpenMined/PySyft/issues/4518

We are aiming to fix this for the next release.

**Comment by stefanv** [comment]
Thanks, @madhavajay.  This seems like a different issue than the two you referred to, but I'm glad to hear that it will be fixed in the next release.

**Comment by madhavajay** [comment]
Hi @stefanv right, I guess I was trying to say we know the Docs are broken and we will be going over them with a closer eye soon. Thanks for pointing out the rendering issue. We haven't decided yet on if we will keep using `sphinx` or switch to another docs tool, but either way we will keep an eye on the formatting. 🙂

**Comment by stefanv** [comment]
Thanks, that sounds good!  Feel free to close this as you see fit.

**Comment by madhavajay** [comment]
We will be removing readthedocs, so ill close this issue.
