### ISSUE TITLE
License incomplete

### ISSUE THREAD

**Issue by stefanv** [OpenMined/PySyft#5146]
There's a small, seemingly accidental, oversight in the project license.

PySyft includes source copied verbatim from Python (like [this file](https://github.com/OpenMined/PySyft/blob/dev/tests/syft/lib/python/collections/ordered_dict/ordered_dict_sanity_test.py)), so should follow the appropriate [license terms](https://docs.python.org/3/license.html).

**Comment by cereallarceny** [comment]
Do you have a proposal for what should be added in order to comply @stefanv?

**Comment by stefanv** [comment]
Here's an example from scikit-image, of the form that is used by the Debian project:

https://github.com/scikit-image/scikit-image/blob/master/LICENSE.txt

**Comment by cereallarceny** [comment]
Could you be more specific about what you’d like for us to do in PySyft? I
think we’re all highly interested in offering credit where credit is due,
but I’m not sure I correctly understand what you’d like for us to do to
resolve the situation.

**Comment by stefanv** [comment]
You should add a line that states that files under '/path/to/python/code' are licensed under the PSF license.

**Comment by cereallarceny** [comment]
Roger that. In order to avoid us having to sweep every file in our codebase, do you have a readymade list of the offending files? We'd be happy to patch them with the appropriate inline documentation at the top of each file. 😄

**Comment by madhavajay** [comment]
@stefanv Can this PSF license statement just be added to the top of any file that was copied and modified from the CPython repo tests?

**Comment by stefanv** [comment]
@madhavajay Yes, that should be fine if you have add a sentence along the line of "Unless otherwise specified in a file header, all code is licensed: ..." to your LICENSE file.

You can see why that is a bit annoying, because the reader then has to scan the whole code base for such exceptions.  The alternative is what I proposed above, that you add a section to the license file. What you suggest is a valid option, though.

**Comment by madhavajay** [comment]
@stefanv Does that change match your description?

**Comment by stefanv** [comment]
:+1: Perfect, thanks!
