### ISSUE TITLE
Fix all darglint docs warnings

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5148]
## Description
Currently there are 419 warnings:
```
$ flake8 src tests | wc -l
419
```

We can progressively improve this with multiple PRs.
If you are interested, please run the checker on the `src` and `tests` folders and try to fix the warnings until there are none.
Some will require adding docs that don't exist while others are just fixes.

This will likely require multiple PRs so if you are interested open a PR with a few fixes and we will go from there.

## Definition of Done
All docstring warnings are fixed and CI has the darglint checker turned on to fail the build.

**Comment by avinsit123** [comment]
@madhavajay I have opened a PR to fix darglint warnings for `src/syft/utils.py` . What I wish to know is whether you want a seperate PR for each file or just for `src/syft` or `tests/syft`

**Comment by madhavajay** [comment]
Updated to use `flake8` as per this PR: https://github.com/OpenMined/PySyft/pull/5195

**Comment by divinit7** [comment]
@madhavajay I am trying to fix warnings in `src/syft/core/store`
but I'm getting `7     DAR202 Excess "Returns" in Docstring: + return`
`2     DAR402 Excess exception(s) in Raises section: +r ValueError`
in `src/syft/core/store/store_interface.py`. Should they be ignored with `#noqa`?

**Comment by madhavajay** [comment]
@divinit7 yeah this is a little weird, since `def traceback_and_raise(e: Any, verbose: bool = False) -> NoReturn:` technically never returns because it always raises. I think ignore is fine if its complaining that the abstract methods dont have an explicit return.
