### ISSUE TITLE
Resolve all bandit issues 

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5149]
## Description
Currently we are running `bandit` with -ll in Medium severity mode.
We should fix all the issues when running bandit without the -l flag and update CI to check all levels.

To get started run:
```
$ bandit -r src
```

## Definition of Done
CI is updated to check all levels of severity with `bandit` and the tests pass.

**Comment by ariannmichael** [comment]
I would like to take this issue

**Comment by ariannmichael** [comment]
Correct me if I'm wrong, but with this PR from @animesh-007, it's just necessary to update the CI
