### ISSUE TITLE
API Refactor Private Klass Methods

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5172]
## Description
As an intermediary step we should immediately rename all private API calls so they, a) dont clash with target classes we patch and b) make it obvious that they will be deprecated soon by making them private.

Check insde `klass.py` and anywhere where we use `aggressive_set_attr`.
Rename the following:
- .serializable_wrapper_type
- .serialize
- .to_proto
- .proto
- .to_bytes

To:
`f"_sy_{name}"`

Remove duplicates and workarounds like 
- .sy_serialize
- ._to_bytes

## Definition of Done
Everything except `send` `tag` and `describe` are renamed and the tests still pass.

**Comment by xutongye** [comment]
`.serialize` is a private API? Library users should not call it?
