### ISSUE TITLE
Define SyMPC Needs from SyftTensor class

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5180]
## Description
Determine what will be needed for SyMPC to utilise SyftTensor and document it so we can create issues:
https://www.notion.so/openmined/2021-02-04-0-5-Custom-Tensors-98750988235342f682da94d82dab41c6

## Contacts
- @gmuraru 
- @ koenvanderveen

## Definition of Done
A clear pathway to converting SyMPC to use SyftTensor is established and issues are created.

**Comment by gmuraru** [comment]
For the moment there is an issue when we want to call a method that is "native" to the ```torch.tensor``` and the custom tensor is remote.

Currently, I am trying to come with a fix for this using metaclasses (the hard part might be to catch the differences between properties and methods).
