### ISSUE TITLE
Setup GitHub CI Runner on AWS

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5181]
## Description
To allow us to do special integration tests or GPU tests we need some custom runners on AWS.
In addition it might be possible to speed up some of our normal tests using these runners.

## Definition of Done
The first example CI runner and token is setup and running in GitHub CI.
Then we can discuss special integration tests and GPU tests.

**Comment by madhavajay** [comment]
https://www.lotharschulz.info/2019/12/09/github-action-self-hosted-runners-on-aws-incl-spot-instances/
https://docs.github.com/en/actions/hosting-your-own-runners

**Comment by madhavajay** [comment]
https://github.com/actions/runner/issues/845

**Comment by JTunis** [comment]
I'm excited for [LambCI](https://github.com/lambci/serverless-actions) to be released. Not a solution right now, but good to keep an eye on!

**Comment by madhavajay** [comment]
@JTunis that looks perfect, any idea on ETA, or if we can get into a private beta?

**Comment by aktech** [comment]
Hi @madhavajay I am the creator of Cirun.io, "GPU support" and "CI Runner on AWS" caught my eye.

FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/

It is used in multiple open source projects needing GPU support like the following:

- https://github.com/pystatgen/sgkit/
- https://github.com/qutip/qutip-cupy

It is fairly simple to setup, all you need is a cloud account (AWS or GCP) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.

Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)
