### ISSUE TITLE
Add torch==1.7.1

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5185]
## Description
We can add torch==1.7.1 we just need to fix up CI.

## Definition of Done
Add 1.7.1 to CI and update README.md.

This would close: https://github.com/OpenMined/PySyft/issues/4936

**Comment by marcalph** [comment]
I'd ike to try this one out

**Comment by marcalph** [comment]
Hi, 

`torch==1.7.1` does look good thanks  to `autofix_allow_list_test.py` but I have a couple more questions (sorry):
- If I got this right, in the autofix process "skip rules" are added to `allowlist_test.json`,  is this file maintained manually? do I need to refine some of these rules e.g.:

```
 "__ifloordiv__": {
        "profile": "tensor_float_division_method_v150",
        "not_available": [
          {
            "data_types": [
              "bool",
              "float16"
            ],
            "lte_version": "1.7.0"
          },
          {
            "data_types": [
              "bool",
              "float16"
            ],
            "lte_version": "1.7.1", << REMOVE THIS?
            "gte_version": "1.7.1" 
          }
        ]
      }
```
- Other markers in the test suite are almost fine : 
   * marker `fast` runs OK
   * for the `libs` one, where I had to install a couple dependencies should these be added to `requirements.dev.txt`? (namely `opacus`, `openmined_psi`, `python-dp`) 
   * for the `slow` one , I'm still looking into an error with `test_duet`

- On the CI side, to get this straights is it just about changing the *torch-version* var in the matrices for the `pr_tests.yml` and `merge_test.yml` workflows?

Thanks!

**Comment by madhavajay** [comment]
@marcalph good questions.

Regarding the `allowlist_test.json` file, it used to be handled manually but now the script `autofix_allow_list_test.py` automatically updates it. That is why you will see a rule like:
```
```

For the tests if you check the `pr_tests.yml` file you can see how they run. The `libs` tests installs the packages inside `requirements/supported_libs.txt`. For the failing `test_duet` in `slow` are you on macOS? There is a situation where that tests sometimes stalls on mac.

As far as torch version matrix, yes, I have removed older torch versions from `dev` so your PR should add `1.7.1` to the existing `1.6.0` and `1.7.0`.

**Comment by marcalph** [comment]
@madhavajay Thank you so much for your input!

I've updated the matrices now, so apart from duet things look fine.
As for the failing duet test, I am on linux so I'll keep looking. it looks weird to me an exception is raised because an uuid seems empty post, so I'm guessing it comes from serde ?
I'm new to protobuf so I am slow

**Comment by madhavajay** [comment]
Hi @marcalph thanks for the help, its all merged including your commits: https://github.com/OpenMined/PySyft/pull/5268/commits
