### ISSUE TITLE
Fix event loop closed in Windows Tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5189]
## Description
When our GitHub CI Windows tests run they end successfully but with an exception about the event loop closing at the end: https://github.com/OpenMined/PySyft/actions/runs/580372926

<img width="831" alt="Screen Shot 2021-02-19 at 3 14 26 pm" src="https://user-images.githubusercontent.com/2882739/108460911-59769700-72c5-11eb-88af-b60522acd00f.png">

## Definition of Done
Figure out why and how to fix this so we don't see it appear on the summary page.

**Comment by prodigy803** [comment]
Hi, I wanted to get started on this problem but I have no idea about CI/CD. Is it okay if I am assigned this and I take some time to figure out the problem?

**Comment by madhavajay** [comment]
Hi @prodigy803 go for it. As far as CI, I think if you just check the logs:

<img width="832" alt="Screen Shot 2021-03-15 at 4 04 28 pm" src="https://user-images.githubusercontent.com/2882739/111110369-2368c200-85a8-11eb-8982-cc6880e9656a.png">
```
2021-02-19T04:57:27.9371418Z ##[error]      raise RuntimeError('Event loop is closed')
```

So it looks like you should be able to just replicate the error on Windows and try to get it to not happen.
