### ISSUE TITLE
pandas inclusion

### ISSUE THREAD

**Issue by avinash463** [OpenMined/PySyft#5200]
## Question
Does it support pandas 1.2.2

## System Information
 - OS: MS Windows
 - OS Version: windows 10
 - Language Version: Python 3.7, Node 10.18.1
 - Package Manager Version: Conda 4.6.1, NPM 6.14.1

**Comment by madhavajay** [comment]
@avinash463 Theres an active PR and we are working on it: https://github.com/OpenMined/PySyft/pull/5152

Contributions are always welcome. 😊
