### ISSUE TITLE
Add Support for NLTK 3.5

### ISSUE THREAD

**Issue by avinash463** [OpenMined/PySyft#5201]
## Description
Add NLTK 3.5 for Tokenizer which enables to implement Visual Question Answering

Are you interested in working on this improvement yourself?
- Yes, I am.

**Comment by madhavajay** [comment]
@avinash463 We are working on some tooling which will make this much quicker and easier but if you wish to start I would look at the existing library support inside the `dev` branch to help understand how it works.
