### ISSUE TITLE
Support Split NNs

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5204]
## Description
This ticket relates to implementing of Split NNs.

## Definition of Done
Split NN example works.

## Contacts
- @madhavajay
- @H4LL 

## TODO
- [x] Initial Duet Notebooks
- [x] Fix Issues with Tags / Intermediate Data

**Comment by H4LL** [comment]
[I've got something here which works: ](https://github.com/H4LL/PySyft/blob/0.4/examples/duet/vertical_learning/advanced/MNIST/DS.ipynb)

It took an hour++ to run though
