### ISSUE TITLE
Handler Serde

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5208]
## Description
The `duet.requests.handler` return value is broken currently due to serialization errors.

```
TypeError: You tried to deserialize an unsupported type. This can be caused by several reasons. Either you are actively writing Syft code and forgot to create one, or you are trying to deserialize an object which was serialized using a different version of Syft and the object you tried to deserialize is not supported in this version.
```

## How to Reproduce
Run: `duet.requests.handler`

## Expected Behavior
No error

## Additional Context
We will be refactoring this anyway.

**Comment by uid42** [comment]
want to work on this
