### ISSUE TITLE
Basic Pandas Support

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5215]
## Description
Add Pandas and Statsmodels support for CDC Diabetes Mortality notebooks.

Notebooks are here:
https://github.com/OpenMined/PySyft/tree/dev/examples/data-science/pandas

TODO:
- [x] Create integration tests from notebooks
- [x] Investigate alternative serde method than dicts.
       http://arrow.apache.org/docs/python/feather.html
       http://matthewrocklin.com/blog/work/2015/03/16/Fast-Serialization
       https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html
       We could try:
       feather / apache arrow
       msgpack
       h5py
- [x] Use dataloader or improved serde to remove 10k row limit
- [ ] Investigate supporting df.attr vs df["attr"]
       Currently we support the getitem version but we might want to look at offering the getattr / setattr version
- [x] Add statsmodels support for these types
- [x] `iloc` added with the UnionGenerator as a post ast update
        See: https://github.com/OpenMined/PySyft/issues/5323

Statsmodel methods and types listed in the notebooks:
- [x] statsmodels.api.add_constant
- [x] statsmodels.genmod.generalized_linear_model.GLMResultsWrapper
- [x] statsmodels.genmod.generalized_linear_model.GLMResultsWrapper.summary
- [x] statsmodels.genmod.generalized_linear_model.GLMResultsWrapper.results
- [x] statsmodels.genmod.families.Binomial

## Definition of Done
The notebooks completely work, all the operations on the DO side can be run on the DS side as well with the final results being retrieved and used to graph the output in seaborn.

**Comment by madhavajay** [comment]
Related: https://github.com/OpenMined/PySyft/pull/5152

**Comment by Koukyosyumei** [comment]
I'm interested in this issue. How is the current situation?

**Comment by madhavajay** [comment]
@Koukyosyumei I have updated the ticket with some of the remaining tasks and pushed the CDC Dataset to the web and updated the notebooks to download them automatically.

The ultimate goal is getting the notebooks fully functioning.
The things which might be a little trickier are:
- `df.attr`
- `iloc`
- alternative serde method for Pandas DF using say `hdf5` or `msgpack`

**Comment by Koukyosyumei** [comment]
@madhavajay 
I am not sure if I have enough time to implement this, but I'll search for this.

**Comment by madhavajay** [comment]
This is done.
