### ISSUE TITLE
Remote Data Loading

### ISSUE THREAD

**Issue by nooralahzadeh** [OpenMined/PySyft#5217]
I wonder if the following claim is true : from https://www.inovex.de/blog/federated-learning-frameworks-part-2/ 

`In pysyft, the data used for training can not be loaded from the remote worker itself but must be sliced and distributed by the central curator. This is, of course, contrary to the paradigm of Federated Learning, which consists of never centralizing data to preserve privacy. `

**Comment by madhavajay** [comment]
@vkkhare can you answer this question?

**Comment by tudorcebere** [comment]
Hi @nooralahzadeh 

The blogpost is not quite up to date with PySyft (it's related to the versions prior to 0.3.0). Currently, this is possible in Syft (everything lower than 0.3.0 hit EOL in April :))

Thanks for your interest in Syft!

**Comment by ncioj10** [comment]
Is there an example of that, where it is currently done?
