### ISSUE TITLE
Communication log

### ISSUE THREAD

**Issue by svenvanderburg** [OpenMined/PySyft#5218]
## Question
How do I get a log of communication between workers?

## Further Information
I want to get a sense of the amount of communication between workers, eventually I want to be able to benchmark the balance between communication and compute for a few algorithms implemented in pysyft. How do I get a log of communication between workers (or between the executor (i.e. 'me') and the workers)?

## System Information
 - syft==0.2.9
 
## What I tried so far
I tried instantiating a worker with `log_msgs=True`, and then take a look at the `worker.msg_history` log. But it seems that not all `Message` objects being logged actually require some communication. See this example:
```python
alice = sy.VirtualWorker(hook, id='alice', log_msgs=True)
bob = sy.VirtualWorker(hook, id='bob', log_msgs=True)

alice.add_workers([bob])
bob.add_workers([alice])

x = th.Tensor([1,2,3])
x_p = x.send(alice)

x_share = x_p.fix_prec().share(bob, alice)
alice.msg_history
```
Results in: 
```
[(ObjectMessage tensor([1., 2., 3.])),
 (TensorCommandMessage ComputationAction[74716439393 = tensor([1., 2., 3.]).fix_prec(owner=<VirtualWorker id:me #objects:0>)]),
 (TensorCommandMessage ComputationAction[51196321021 = (Wrapper)>FixedPrecisionTensor>tensor([1000, 2000, 3000]).share(<VirtualWorker id:bob #objects:2>, <VirtualWorker id:alice #objects:3>, protocol=snn, field=None, dtype=None, crypto_provider=None, requires_grad=False)]),
 (ObjectMessage tensor([-7376825144748423250,  2791388692294860218, -5205075258080131568])),
 (ForceObjectDeleteMessage [74716439393])]
```

**Comment by svenvanderburg** [comment]
Searching through the code it seems that the `msg_history` only contains received messages. Setting `verbose=True` helps in getting a clearer image. I am still puzzled though how this corresponds to actual communication between workers. See this example:
```python
alice = sy.VirtualWorker(hook, id='alice', verbose=True)
x = th.Tensor([1,2,3])
x_p = x.send(alice)
x = x_p.get()
```
Which prints:
```
worker <VirtualWorker id:alice #objects:0> received ObjectMessage
worker <VirtualWorker id:alice #objects:1> received ObjectRequestMessage
```
After receiving the ObjectRequestMessage Alice must have sent the tensor back to the central orchestrator (me), but I don't see her sending anything?

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
