### ISSUE TITLE
Syft Share and Get API for SyMPC

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5231]
## Description
Add a `.share` / `.get` API to Syft to interact with the SyMPC `Session` / `.reconstruct`.

## Definition of Done
SyMPC can be used within Syft transparently (if installed) by using `.share` `.get` like the old `0.2.x` notebooks:

https://github.com/OpenMined/PySyft/blob/raais/examples/tutorials/Part%209%20-%20Intro%20to%20Encrypted%20Programs.ipynb

**Comment by tushar-semwal** [comment]
Waiting for this feature. Thanks!
