### ISSUE TITLE
Fix organization logos for GitHub dark mode

### ISSUE THREAD

**Issue by letmerecall** [OpenMined/PySyft#5235]
## Where?
Where are you looking to add/improve the documentation? Which file? Which feature?

`README.md`

## Who?
Who is your audience for this documentation issue?

Anyone who is using GitHub's dark mode and reading `PySyft` documentation.

## What?
Describe what you would like this documentation to accomplish.

The logos of organizations under the "Organizational Contributions" section of README looks a bit off in the dark mode. Ideally they should be clearly visible in the light as well as dark mode. 
https://github.com/OpenMined/PySyft#organizational-contributions

In light mode
![logos-in-light](https://user-images.githubusercontent.com/19938474/109615875-7713ee00-7b5a-11eb-9d49-9a57e2e7c984.PNG)

In dark mode
![logos-in-dark](https://user-images.githubusercontent.com/19938474/109615900-81ce8300-7b5a-11eb-8b91-24d5d3be7cc8.PNG)

## Additional Context

I think the issue is the transparent background of `.png` images. Having a white background in these logo images might just work perfectly.

**Comment by karynaur** [comment]
Hey! I would like to fix this one. 
A small clarification: Do the images have to be from the organization's/OpenMined's website or can it be from other sources as well? I could not find an image with a white background from the official website/GitHub.

**Comment by RaghavPrabhakar66** [comment]
Created a pr(#5293) to solve the issue.
