### ISSUE TITLE
Torch 1.8

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5258]
## Description
Add support for Torch 1.8 and Python 3.9 in CI

Python 3.9 only has torch 1.7.1 and torch 1.8.0

## Definition of Done
Both versions are tested in our CI.

**Comment by Param-29** [comment]
@madhavajay We will also have to make changes in the allowlist(for torch) because as torch removed support for a lot of things (in Torch 1.8)
Example: 
`torch.fft`
