### ISSUE TITLE
how to extract outputs from each workers?

### ISSUE THREAD

**Issue by yourotea12** [OpenMined/PySyft#5267]
It is about method question.. 
Lets say I have 3 workers, and made federated dataset. I try to extract output values from each workers. How can I do that? output values means the ones that are propagated through the network I designed for each worker to run the Neural network.

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
