### ISSUE TITLE
TypeError: send() got an unexpected keyword argument 'tags'

### ISSUE THREAD

**Issue by thodosss** [OpenMined/PySyft#5271]
Ηello and greetings from greece
I am trying to execute the following example but i cant run this line of code
`data_pointer = data.send(duet, tags=["dataset"], description="simple binary dataset", pointable=True)`
because send does not have those attributes

 [the link of the example](https://colab.research.google.com/github/OpenMined/PySyft/blob/dev/examples/vertical-learning/basic_splitnn/DS_local_data.ipynb#scrollTo=lWz6sCuf9oZN)

is there any version of syft that can execute this example or another way to solve this issue
thank you in advance

**Comment by madhavajay** [comment]
The API is under flux and all the working examples in CI are off `dev`. Its possible you are using `0.3.0` from PyPI. Try installing the `dev` branch directly and play with the examples which are in the examples folder as most of them are tested with CI against the `dev` directly.
