### ISSUE TITLE
Rename load_lib to load

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5273]
## Description
- [x] Rename `sy.load_lib` to `sy.load`.
Leave old method but pass through to new method and add DeprecationWarning like here:
https://github.com/OpenMined/PySyft/blob/fb4f99028338d4e59fb702f1f6ec60f1e16bc660/src/syft/ast/klass.py#L322

- [x] Add test to `api/deprecated_test.py`
- [x] Look into auto loading libraries using a post import hook:
https://stackoverflow.com/questions/40623889/post-import-hooks-in-python-3
https://github.com/GrahamDumpleton/wrapt
https://www.youtube.com/watch?v=u7oj-ghfhUk
- [x] Update notebooks

## Definition of Done
`sy.load_lib` is deprecated but still functional and replaced with `sy.load`

**Comment by avinsit123** [comment]
Hi @madhavajay can I work on this?

**Comment by gmuraru** [comment]
@avinsit123 could you also open a PR in [SyMPC](https://github.com/OpenMined/SyMPC/blob/main/src/sympc/__init__.py#L23) for changing the name?

**Comment by avinsit123** [comment]
Sure @gmuraru I will do that after completing the PR here if thats fine!!

**Comment by tudorcebere** [comment]
Hello @avinsit123 !

Open a PR and lets talk directly on that. :100:
