### ISSUE TITLE
Improve inline documentation

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5279]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks already carried out is to audit the code, see this  [spreadsheet](https://docs.google.com/spreadsheets/d/1ExD1EQIQtLx03a_h7lBPlvasVsmb38S02Bfw5a7Q62Y/edit#gid=1159978476). This audit has raised some docstring that is missing.

## Goal
The goal of this issue is to improve inline docstring of pysyft according to the spreadsheet, starting for those marked in red.

This issue could be carried out for more than one person, just let us know in order to coordinate the efforts.

This is a great issue if you want to get involved into the code.

**Comment by bug-debug-done** [comment]
I am new to open source can please assign this to me.

**Comment by dnabanita7** [comment]
I am starting with ``/ast/klass``

**Comment by jmaunon** [comment]
@IrinaMBejan and @bug-debug-done  , please, open a new PR making reference to this issue. In this way is easier to keep trace and more people can help
