### ISSUE TITLE
Audit tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5280]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the list of current tutorials and the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications
* Good/Green means that the tutorials works as expected.

This issue could be done for more than one person, just let us know to coordinate the effort.

This is a great oportunity to get involved into pysyft!

**Comment by felixfaisal** [comment]
Hey @jmaunon , So I wanted to know the tutorials in the readme folder, takes me to the examples using Duet, Do we have to try that out or find all existing tutorials on the web and do this.

**Comment by animesh-007** [comment]
I would like to contribute to this issue.

**Comment by IrinaMBejan** [comment]
Hey @felixfaisal and @animesh-007! To clarify a bit, we have been auditing the source code so far in this spreadsheet: https://docs.google.com/spreadsheets/d/1ExD1EQIQtLx03a_h7lBPlvasVsmb38S02Bfw5a7Q62Y/edit#gid=1159978476

The plan is to go through each tutorial/example/readme file in the PySyft/Pygrid repo and assign each a status (as explained above), together with some short explanation in the document. Feel free to start with any that has not been yet documented.

**Comment by jmaunon** [comment]
Thanks @felixfaisal  and @animesh-007 for your collaboration. Please, update the spreadsheet with your feedback. To keep trace, if you want you can open a dummy PR referencing this issue, or please, address here your updates (or even via slack).

**Comment by felixfaisal** [comment]
@jmaunon Awesome, I'll create a dummy PR, Also mentioning which parts I worked on.

**Comment by ashkan-pirmani** [comment]
Is there any room still available to contribute to this issue?

**Comment by felixfaisal** [comment]
@ashkan-pirmani Hey, I've sort of written down all the files in duet examples, you could do that with other examples, as there are a number of notebooks to cover

**Comment by jmaunon** [comment]
@felixfaisal @ashkan-pirmani , which is the status of your tasks? More people want to contribute. 
It might be more efficient if we split this issue in more specific ones (maybe one per folder...) but we did not have time

**Comment by marcalph** [comment]
Hi @all,

I'd be glad to contribute alongside. Let's start with the obvious for syft, according to the google doc we have : 
- [ ] cli/
- [ ] dcgan/
- [ ] fast_neural_style/
- [ ] information_flow_demo_splitnn_tenseal
- [ ] mnist/
- [ ] reinforcement_learning/
- [ ] snli/
- [ ] super_resolution/
- [ ] time_sequence_prediction/
- [ ] vae/
- [ ] word_language_model/
 
 @felixfaisal @ashkan-pirmani 
 Can you indicate which tutorials you guys have been dealing with so far (DM me over slack maybe?) I'll update the task list accordingly and it will then be used to keep track of the tutorials audit, also we could link easily related issues/PR.

**Comment by jmaunon** [comment]
@felixfaisal @ashkan-pirmani @marcalph I have created an issue per folder in PySyft, in that way you and rest of community can work more efficient. 
I close this issue, but please, continue with your work!, just asign to yourself any of the new issues.

Your feedback is very very useful for us
