### ISSUE TITLE
Create Opacus DP Plans Integration Test

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5284]
## Description
Create a notebook which uses plans and Opacus and then turn it into a test.
This will need to be iterated on to build Plans so that it can cover the use case we are aiming for.

## Definition of Done
Opacus runs on a simple model in Plans and we can discuss the next steps.

**Comment by dnabanita7** [comment]
I am interested in writing the notebook. Let's discuss how to start, what to include.
