### ISSUE TITLE
Dataloader for sending large dataset to duet server

### ISSUE THREAD

**Issue by znreza** [OpenMined/PySyft#5294]
## Feature Description
I am using a dataset of 20K images. But I am having hard time to upload the data to the duet server using .send(), because it's a big data, my notebook crashes each time I try. I think a feature for serializing the data would be great.

## Is your feature request related to a problem?
Here is the link to the dataset I am trying to send. The folder has both the original image dataset and also the torch dataloaders at .pt files. DO_data.pt has 20K images and test_data.pt has 12024 images.

https://drive.google.com/drive/folders/1MEHqyB-kmoSSxO6_VqkhLXqXjGiAGD3-?usp=sharing

**Comment by ArtistBanda** [comment]
@znreza can you share the code to reproduce?

**Comment by madhavajay** [comment]
Initial PR is here: https://github.com/OpenMined/PySyft/pull/5314
