### ISSUE TITLE
Add new torch 1.8.0 ops

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5295]
## Description
A clear and concise description of what you want to improve.

Add all these new Ops from `torch==1.8.0` and add tests for them in the allowlist tests.

- [ ] torch.are_deterministic_algorithms_enabled
- [ ] torch.broadcast_shapes
- [ ] torch.broadcast_to
- [ ] torch.column_stack
- [ ] torch.copysign
- [ ] torch.diff
- [ ] torch.float_power
- [ ] torch.fmax
- [ ] torch.fmin
- [ ] torch.igamma
- [ ] torch.igammac
- [ ] torch.inner
- [ ] torch.kron
- [ ] torch.ldexp
- [ ] torch.ldexp_
- [ ] torch.mkldnn_linear_backward_weights
- [ ] torch.moveaxis
- [ ] torch.msort
- [ ] torch.nan_to_num
- [ ] torch.nan_to_num_
- [ ] torch.nanmedian
- [ ] torch.narrow_copy
- [ ] torch.pixel_unshuffle
- [ ] torch.profiler
- [ ] torch.quint4x2
- [ ] torch.ravel
- [ ] torch.row_stack
- [ ] torch.sinc
- [ ] torch.sinc_
- [ ] torch.swapaxes
- [ ] torch.swapdims
- [ ] torch.tensor_split
- [ ] torch.tile
- [ ] torch.use_deterministic_algorithms
- [ ] torch.warnings
- [ ] torch.xlogy
- [ ] torch.xlogy_

- [ ] torch.nn.ChannelShuffle
- [ ] torch.nn.GaussianNLLLoss
- [ ] torch.nn.LazyConv1d,
- [ ] torch.nn.LazyConv2d,
- [ ] torch.nn.LazyConv3d,
- [ ] torch.nn.LazyConvTranspose1d,
- [ ] torch.nn.LazyConvTranspose2d,
- [ ] torch.nn.LazyConvTranspose3d,
- [ ] torch.nn.LazyLinear,
- [ ] torch.nn.PixelUnshuffle
- [ ] torch.nn.UninitializedParameter
- [ ] torch.nn.quantizable

- [ ] torch.nn.functional.Callable
- [ ] torch.nn.functional.gaussian_nll_loss
- [ ] torch.nn.functional.has_torch_function_unary
- [ ] torch.nn.functional.has_torch_function_variadic
- [ ] torch.nn.functional.pixel_unshuffle
- [ ] torch.nn.functional.reproducibility_notes
- [ ] torch.nn.functional.tf32_notes

- [ ] torch.Tensor.__imod__
- [ ] torch.Tensor.broadcast_to
- [ ] torch.Tensor.copysign
- [ ] torch.Tensor.copysign_
- [ ] torch.Tensor.cumprod_
- [ ] torch.Tensor.cumsum_
- [ ] torch.Tensor.float_power
- [ ] torch.Tensor.float_power_
- [ ] torch.Tensor.fmax
- [ ] torch.Tensor.fmin
- [ ] torch.Tensor.igamma
- [ ] torch.Tensor.igamma_
- [ ] torch.Tensor.igammac
- [ ] torch.Tensor.igammac_
- [ ] torch.Tensor.inner
- [ ] torch.Tensor.is_vulkan
- [ ] torch.Tensor.is_xpu
- [ ] torch.Tensor.kron
- [ ] torch.Tensor.ldexp
- [ ] torch.Tensor.ldexp_
- [ ] torch.Tensor.moveaxis
- [ ] torch.Tensor.msort
- [ ] torch.Tensor.nan_to_num
- [ ] torch.Tensor.nan_to_num_
- [ ] torch.Tensor.nanmedian
- [ ] torch.Tensor.new_empty_strided
- [ ] torch.Tensor.ravel
- [ ] torch.Tensor.sinc
- [ ] torch.Tensor.sinc_
- [ ] torch.Tensor.swapaxes
- [ ] torch.Tensor.swapaxes_
- [ ] torch.Tensor.swapdims
- [ ] torch.Tensor.swapdims_
- [ ] torch.Tensor.tensor_split
- [ ] torch.Tensor.tile
- [ ] torch.Tensor.xlogy
- [ ] torch.Tensor.xlogy_
- [ ] torch.Tensor.xpu

**Comment by symabbas** [comment]
He @tudorcebere I would like to work on this issue. May I know where these operations need to be added? I'm a bit new to PySyft but know PyTorch well.
