### ISSUE TITLE
Change get_root_data_path to use HOME dir

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5304]
## Description
We probably need to change `get_root_data_path` in utils to use some kind of HOME dir thats cross platform.
The `Path` class in `pathlib` library includes a `Path.home` so hopefully that works on all 3 platforms.

The goal is that when Syft Examples are used that their datasets are downloaded to a common shared location.
This could be something like `~/.syft/data` or something similar.

Once this is done the other notebooks which download datasets should also be updated to use this common `get_root_data_path` method like the SuperResolution example.

# Definition of Done
The `get_root_data_path` method uses a common location like user HOME dir, so that it will work as a pip package as well as editable source during `dev`.

**Comment by ArtistBanda** [comment]
So instead of creating a directory as `../pysft/data` use a universal directory `~/.syft/data` or `~/.pysyft/data`.
I am new to this repository and a GSOC aspirant. I will create a PR to resolve this issue.
