### ISSUE TITLE
Move Send Tensor script into a benchmarking tools folder

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5308]
## Description
Currently we have some scripts like this: https://github.com/OpenMined/PySyft/blob/dev/examples/duet/mnist/send_tensor.py

They should be moved from `examples` and into a `benchmarking` folder inside scripts.

## Definition of Done
This file is moved from the examples folder somewhere else.

**Comment by karynaur** [comment]
hey @madhavajay !! Made a PR #5309 that should solve the issue. Please let me know if anything has to be done. Ill look into it asap.
