### ISSUE TITLE
Installation in Colab

### ISSUE THREAD

**Issue by abhi1nandy2** [OpenMined/PySyft#5311]
## Description
import  shows error

## How to Reproduce
1. Open a colab notebook
2. 
```bash
!pip install syft
import syft as sy
```
## Expected Behavior
No error

## Screenshots
![image](https://user-images.githubusercontent.com/19462637/111311632-73b55200-8684-11eb-8a30-219e54960c9e.png)
![image](https://user-images.githubusercontent.com/19462637/111311692-8465c800-8684-11eb-971c-b1e6bbcd5c0b.png)

## System Information
 - Environment - colab.research.google.com

**Comment by gmuraru** [comment]
@abhi1nandy2 could you try to install ```torch == 1.7.1``` after installing syft.
The issue might be because ```torch1.8``` is out and syft was not released (YET!) with torch1.8 support.

**Comment by r0cketr1kky** [comment]
@gmuraru I tried this out the other day but to no avail. You still get the same error!

**Comment by iamtrask** [comment]
The latest version of PySyft is not compatible with some of the ways Colab is locked down - pip install locally and we'll address colab integration in a later version.

**Comment by madhavajay** [comment]
We can install in Colab, but there are issues running in Colab after the connection is established which relates to networking between Colab and another system which we are investigating.

To install in colab do this:
```python
%%capture
# This only runs in colab and clones the code sets it up and fixes a few issues, 
# you can skip this if you are running Jupyter Notebooks
import sys
if "google.colab" in sys.modules:
    branch = "dev"    # change to the branch you want
    ! git clone --single-branch --branch $branch https://github.com/OpenMined/PySyft.git
    ! cd PySyft && ./scripts/colab.sh      # fixes some colab python issues
    sys.path.append("/content/PySyft/src") # prevents needing restart
```

You can see more about whats going on in the script `scripts/colab.sh`.

Additionally if you are reading this ticket because you are trying to use Syft for the Privacy Course on your local Jupyter until the next PyPI release you will need to install via git:
```
pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft
```

**Comment by abhi1nandy2** [comment]
Thanks a lot!

**Comment by Nazmul92** [comment]
> Sadly - this is a known issue. The latest version of PySyft is not compatible with some of the ways Colab is locked down - pip install locally (using conda) and we'll address colab integration in a later version.
> 
> CC: @madhavajay to confirm.

syft==0.6.0 is compatible in colab? I installed this version. Import is ok, but when I try to create virtual worker using hook=sy.TorchHook(torch) then it shows TorchHook module error

**Comment by Nazmul92** [comment]
syft==0.6.0 is compatible in colab? I installed this version. Import is ok, but when I try to create virtual worker using hook=sy.TorchHook(torch) then it shows TorchHook module error

**Comment by Madhuri1506** [comment]
> syft==0.6.0 is compatible in colab? I installed this version. Import is ok, but when I try to create virtual worker using hook=sy.TorchHook(torch) then it shows TorchHook module error

Same happens with me.. anybody having solution to this ..will be great help for me ..
