### ISSUE TITLE
Check and Fix notebook / jupyter client warning on Colab

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5315]
## Description
This needs to be checked on Colab, since it seems colab has its own outdated versions of notebook and jupyter-client as well.
https://github.com/OpenMined/PySyft/issues/4915

## Definition of Done
Fix for Colab if possible.

**Comment by ArtistBanda** [comment]
`import syft as fy` shows this exception 
```
Exception: Your Jupyter Notebook is too old. Please upgrade to version 6 or higher.
```

and running `pip install --upgrade notebook` shows this error 

```
ERROR: google-colab 1.0.0 has requirement notebook~=5.3.0; python_version >= "3.0", but you'll have notebook 6.2.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement tornado~=5.1.0; python_version >= "3.0", but you'll have tornado 6.1 which is incompatible.
```

alongside this warning 
```
WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit or pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Factory reset runtime" from the "Runtime" menu.
```

although the exception goes away after restarting runtime as the notebook is updated.

So, what exactly is the definition of the fix?

**Comment by madhavajay** [comment]
@ArtistBanda well, there was a bug with notebook 5.x where it wouldnt work, but I think its unrelated to colab, so in this instance we could allow the `Exception: Your Jupyter Notebook is too old` check to pass if the code is running in colab for now, which is detected by doing this:
```python
if "google.colab" in sys.modules:
```

**Comment by ArtistBanda** [comment]
@madhavajay I have created a PR to fix it
