### ISSUE TITLE
The JupyterNotebook in example/duet should be updated!

### ISSUE THREAD

**Issue by densechen** [OpenMined/PySyft#5316]
It is out to correctly run!

**Comment by madhavajay** [comment]
@densechen can you be more specific?

**Comment by densechen** [comment]
Some functions have been removed, such as utils.get_data_path().

**Comment by madhavajay** [comment]
@densechen I think you have the wrong version installed.
See this issue: https://github.com/OpenMined/PySyft/issues/5334
