### ISSUE TITLE
How to make peer to peer connection without AWS?

### ISSUE THREAD

**Issue by rishkum** [OpenMined/PySyft#5318]
# Making peer to peer connection without AWS 

I am trying to deploy my pysyft based analytics to my colleague's computer. I have been able to run the examples on localhost using syft-server. My network is restricted so it would not go through the AWS channel which I assume the standard duet example uses. Is there a way to use grid.webRTC class to make this possible?

Would i need to buy a signaling server somewhere to make this happen?

Thanks for your help!

**Comment by madhavajay** [comment]
@rishkum the `syft-server` should work you just need to make sure that you are connecting on the right IP and port from the other machine.

Since its set to `0.0.0.0` it should bind on all interfaces. If you can't connect it could be a firewall issue.

```python
HOST = "0.0.0.0" if IP_MODE == "IPV4" else "::"  # nosec
PORT = os.getenv("PORT", 5000)
```
