### ISSUE TITLE
Allow Classes to opt out of data attributes in the AST

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5322]
## Description
Allow Classes to opt out of data attributes in the AST.
This is required for libraries like Pandas where data attributes like `tags` and `description` would change the underlying dict.

## Definition of Done
`klass.py` is refactored to remove the work around:
```python
if outer_self.pointer_name not in ["DataFramePointer", "SeriesPointer"]:
    attach_tags(self, tags)
    attach_description(self, description)
```

**Comment by avinsit123** [comment]
@madhavajay I would like to work on this issue. Could you elaborate a little more on what `attach_tags()` is doing here. Does this mean that in case of pandas DataFrame or Series we need to ignore value of tags and description and store it as None?
