### ISSUE TITLE
Add updated CPython integration tests for 3.9

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5327]
## Description
We need to update our CPython integration tests to also support python 3.9.

## Definition of Done
The following files are updated to include changes for Python 3.9: https://github.com/python/cpython/tree/3.9/Lib/test
```
tests/syft/lib/python/collections/ordered_dict/ordered_dict_sanity_test.py
tests/syft/lib/python/complex/complex_test.py
tests/syft/lib/python/dict/dict_test.py
tests/syft/lib/python/float/float_test.py
tests/syft/lib/python/list/list_test.py
tests/syft/lib/python/string/string_utils_test.py
```

**Comment by ArtistBanda** [comment]
Will work on the required changes.
The above like is broken, working link for Lib tests: https://github.com/python/cpython/tree/3.9/Lib/test

**Comment by ArtistBanda** [comment]
@madhavajay created a PR for the improvement.
