### ISSUE TITLE
Fail Fast on Preferred latest versions in CI

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5328]
## Description
We should test the latest versions of everything in CI first and fail first, that way we will spin up less checks initially and the tests which fail will be related specifically to version compatibility regression issues which is less common.

## Definition of Done
`python-tests-fast` runs the latest versions first or is split into another test which runs first.
This would be python 3.9, torch 1.8.0 and all 3 OSes.

**Comment by Param-29** [comment]
I'd like to work on this issue.

**Comment by Param-29** [comment]
PR merged, this issue can be closed.

**Comment by madhavajay** [comment]
This is done.
