### ISSUE TITLE
ImportError: cannot import name 'get_root_data_path'

### ISSUE THREAD

**Issue by yashmaurya01** [OpenMined/PySyft#5334]
## Description
ImportError when executing `from syft.util import get_root_data_path`

## How to Reproduce
1. Go to 'PySyft/examples/duet/dcgan/DCGAN_Syft_Data_Owner.ipynb'
2. Execute second cell.
4. See **ImportError: cannot import name 'get_root_data_path'**

## Screenshots
![Screenshot from 2021-03-21 18-09-30](https://user-images.githubusercontent.com/59893283/111905455-b48cdc80-8a71-11eb-8631-3901acadec20.png)
****

## System Information
 - OS: Ubuntu 18.04 LTS
 - Language Version: Python 3.6.9

**Comment by madhavajay** [comment]
Hi @yashmaurya01 since many of the notebooks, including this one in particular are run in our integration tests in CI, your error probably means you don't have the right version of Syft installed.

Until the next release it's advised to install directly from the `dev` branch.
```
$  pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft
```

**Comment by madhavajay** [comment]
This should be fixed.

**Comment by rafaelaBrum** [comment]
Hello @madhavajay !

I have the same problem with this function, but when I tried to install PySyft from the dev branch, an error raised. How can this can be fixed?

Thank you!


![image](https://user-images.githubusercontent.com/2991063/121261791-8f965180-c889-11eb-905d-112cc944d4af.png)
