### ISSUE TITLE
Allow Object Attributes in AST

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5338]
## Description
Allow for object attributes to be allowed in the allowlist AST.
The issue being that they do not exist at Class analysis time, and we would want the bound function to have the context of the target data item.

One method could be to provide a flag that these are dynamic and not bind the method but attach generated function to the Pointer so that on the retrieval side we can attempt to locate the attribute at execution time. 

## Definition of Done
Items like the following can be enabled and work as expected:
```
allowlist["torch.nn.Linear.weight"] = "torch.Tensor"
allowlist["torch.nn.Linear.bias"] = "torch.Tensor"
```

**Comment by madhavajay** [comment]
Additional use case is `grad` and `data` for Tensors which are used in the `UnionGenerator` for `Plans`.
```
torch.Tensor.grad
torch.Tensor.data
```

**Comment by madhavajay** [comment]
Also see `torchvision`: https://github.com/OpenMined/PySyft/issues/5031

**Comment by madhavajay** [comment]
Also see `torchvision`: https://github.com/OpenMined/PySyft/issues/5032

**Comment by avinsit123** [comment]
Hi, I did create a PR for the same issue a few months ago but it was closed due to some reason. I would like to work on this PR and try out the method that you have suggested. Also, you can refer to the conversation we had previously in this PR #5117 .
