### ISSUE TITLE
DictPointer.items() can't be iterated

### ISSUE THREAD

**Issue by xutongye** [OpenMined/PySyft#5341]
## Description
I got error when trying to iterate on `DictPointer.items()`, (while I can iterate on `ListPointer`).
## How to Reproduce
```python
# on DO side
duet.requests.add_handler(action="accept")

# on DS side
d = sy.lib.python.Dict({"1":1,"2":2})
dptr = d.send(duet)
itemsptr = dptr.items() # you get a ListPointer
itemsptr.__len__() # got error
for e in itemsptr: # got error too
    print(e)
```

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
@tudorcebere Did we end up supporting Dicts in the `Iterator`? Seems like you can get `.len()` on the `dptr` but not on the `itemsptr` interestingly.

**Comment by tudorcebere** [comment]
@madhavajay Awkward, I remember solving this at some point. @xutongye fixed and added tests to be sure to not have a regression again.
