### ISSUE TITLE
Refactor PyGrid Messages to use a common Message type

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5351]
## Description
Currently Grid messages are a request response pair like this:
```proto
message SendAssociationRequestMessage {
  syft.core.common.UID msg_id = 1;
  syft.core.io.Address address = 2;
  string content = 3;
  syft.core.io.Address reply_to = 4;
}

message SendAssociationRequestResponse {
  syft.core.common.UID msg_id = 1;
  int32 status_code = 2;
  string content = 3;
  syft.core.io.Address address = 4;
}
```

Since they are all the same it might benefit to refactor this to use a single common GridRequestMessage / GridResponseMessage type and then add an additional field with an enum of the message / action type being delivered.

## Definition of Done
All of the PyGrid messages that have duplicate structure have been refactored.

**Comment by JDuchniewicz** [comment]
Do we want to perform the same change with the messages themselves or just protobuffers representing them? I am currently working on unifying the messages, but I am not sure how, for example approach the constructor of `AssociationRequestAPI` which looks like this:
```
    def __init__(self, send: Callable):
        super().__init__(
            create_msg=SendAssociationRequestMessage,
            get_msg=GetAssociationRequestMessage,
            get_all_msg=GetAssociationRequestsMessage,
            delete_msg=DeleteAssociationRequestMessage,
            send=send,
            response_key=AssociationRequestAPI.response_key,
        )
        ```
        
if they are to be unified, how would this be reflected in this constructor?
