### ISSUE TITLE
Give Plan outputs names

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5356]
## Description
Ensure that Plans have a way to provide names to their outputs, perhaps with some kind of default to `output0` or something for the case of only returning 1 object, but try to enforce a return type of Dict[str, Any] so that we can always have a known set of names for the outputs and can address them differently with permissions.

## Definition of Done
Plans must return a Dict[str, Any] of return values, we could potentially automatically create this in the instance of unnamed return value or tuple and give it the names: "output0", "output1" etc... for now.

**Comment by koenvanderveen** [comment]
Conceptually I always compared plans to python functions, they have args (in our case they are not allowed) and kwargs, execute some operations, and return a tuple of outputs. This would move away from that abstraction, but I don't completely understand why yet. Could you elaborate about the permission part?
