### ISSUE TITLE
Create Plans Duet MLP Integration Test

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5357]
## Description
To ensure that Plans are tested well and work over Duet we should create an integration test.
This will help when we start testing out the permission model by not using a blanket `add_handler(action="accept")`.

## Definition of Done
The existing `experimental/koen/MLP%20Plan.ipynb` is created as an Integration Test.

**Comment by avinsit123** [comment]
Hey @madhavajay I would like to work on this and help you guys create Integration Tests for Duet. However had 2 doubts before I would create a PR. 

1.  Should we also create Tests like the ones created by Koen in `basic_plans.ipynb` or `Plan API.ipynb`?
2. Also, what would we compare in case of the MLP Integration Test - the local and remote model parameters or the actual and predicted image values.

Thanks

**Comment by avinsit123** [comment]
@madhavajay are you currently working on this?
