### ISSUE TITLE
Add fix_inputs to Plans

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5362]
## Description
Add fix_inputs to Plans to allow the DO to lock and supply any of the input variables to a Plan.

```python
# DS
@make_plan
def my_plan(data, arg2):
	y = data + data
	z = y * y + arg2

    output = {}
    output['z'] = z
    output['y'] = y
    return output

my_plan.send(duet)
```

```python
# DO
duet.store["my_fav_plan"].fix_inputs({"data", data_ptr})
duet.store["my_fav_plan"].fix_inputs(None) <--- clears any fixing of inputs
```

By fixing an input, the remote side cannot pass it in and will get an error, or the value will simply be ignored.
The input will instead be taken from the pointer supplied by the DO.

**Comment by Jasopaum** [comment]
Long time no see 👋 
I can try to do that! The only problem I see for the moment is that if I try to do
```
data_ptr = data.send(duet)
duet.store["my_fav_plan"].fix_inputs({"data": data_ptr})
```,
the `{"data": data_ptr}` arg will be serialized with a `syft.proxy.torch.TensorPointer` inside of it, which we don't know how to serde, right?

**Comment by madhavajay** [comment]
@Jasopaum hey man, long time no speak, I didn't see this while I was on break. Do you want to join the syft Slack channel and discuss, just ping @tudorcebere.
