### ISSUE TITLE
Invalidate Pointer after .get()

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5364]
## Description
After `.get()` has been used on a Pointer with the flag `delete_obj=True`, the pointer should be invalidated as well, as the underlying remote object will no longer be in the store if the request is going to be successful.

Snippet to reproduce the current behaviour:

```
import syft as sy
client = sy.VirtualMachine().get_root_client()

int_ptr = client.syft.lib.python.Int(0)
result = int_ptr.get() # delete_obj = True by default

# int_ptr is still alive
# this will result in an error on the other side, but we know this already, we should
# not make a network call anymore.
int_ptr.get()
```

Ideally, int_ptr shouldn't be usable after the `.get()`.

**Comment by ArtistBanda** [comment]
So, once the `get` function is called by the `pointer` with the flag `delete_obj=True` it should raise an error like `ReferenceError` for the next call?
Will this solution work?
