### ISSUE TITLE
Refactor TorchVision tests to use PIL Image

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5368]
## Description
We can now support PIL images so the torchvision tests can be updated to take advantage of this.
As per this comment: https://github.com/OpenMined/PySyft/pull/5332#issuecomment-805979800

## Definition of Done

This method is enabled and tested and unused `imageTensor.pt` removed.
```python
allowlist["torchvision.transforms.functional.pil_to_tensor"] = "torch.Tensor"
```

**Comment by vsquareg** [comment]
Would be handled in #5368 (PR #5383).
