### ISSUE TITLE
Failed to import syft

### ISSUE THREAD

**Issue by TudouJack** [OpenMined/PySyft#5370]
## Question
  File "D:/PycharmProjects/HDFED/main.py", line 2, in <module>
    import syft as sy
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\__init__.py", line 61, in <module>
    from syft.core.node.device.device import Device  # noqa: F401
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\core\node\device\__init__.py", line 2, in <module>
    from .client import DeviceClient
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\core\node\device\client.py", line 16, in <module>
    from ..common.client import Client
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\core\node\common\client.py", line 20, in <module>
    from ....lib import lib_ast
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\lib\__init__.py", line 26, in <module>
    lib_ast = create_lib_ast()
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\lib\__init__.py", line 12, in create_lib_ast
    torch_ast = create_torch_ast()
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\lib\torch\__init__.py", line 53, in create_torch_ast
    ast.add_path(
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\ast\globals.py", line 65, in add_path
    attr.add_path(  # type: ignore
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\ast\module.py", line 120, in add_path
    attr.add_path(  # type: ignore
  File "C:\Users\xd_69\AppData\Roaming\Python\Python38\site-packages\syft\ast\callable.py", line 82, in add_path
    attr_ref = getattr(self.ref, path[index])
AttributeError: type object 'Tensor' has no attribute 'fft'

## System Information
 - OS: windows 10
 - Language Version:Python 3.8
 - Package Manager Version:Conda 4.9.2, pycharm, syft 0.3, torch1.8.0
 
I followed the README to install the syft, but I can not import it successfully. Please tell me what else I need to do to make the environment correct. Thanks!

**Comment by madhavajay** [comment]
Did you install syft with?
```
$ pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft
```

**Comment by TudouJack** [comment]
> Did you install syft with?
> 
> ```
> $ pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft
> ```

thank u soooooooooooooooooooooo much!!!

**Comment by RomainGoussault** [comment]
Hello, I had the same issue and your proposition worked @madhavajay, thanks!
But why do we have to that and why `pip install syft` alone does not work?

**Comment by TudouJack** [comment]
> Hello, I had the same issue and your proposition worked @madhavajay, thanks!
> But why do we have to that and why `pip install syft` alone does not work?

Maybe it is because the packge installed by pip is an old version which is different from https://github.com/OpenMined/PySyft@dev#egg=syft

**Comment by yyyanananan** [comment]
> Did you install syft with?
> 
> ```
> $ pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft
> ```

**Comment by vnt1537** [comment]
It is mos

> 
> 
> Hello, I had the same issue and your proposition worked @madhavajay, thanks!
> But why do we have to that and why `pip install syft` alone does not work?

It is mostly because of the torch version!
We need torch version <=1.8.0 & >=1.4.0 and torchvision<=0.9 & >=0.5 .

**Comment by youngfish42** [comment]
> 
> 
> It is mos
> 
> > Hello, I had the same issue and your proposition worked @madhavajay, thanks!
> > But why do we have to that and why `pip install syft` alone does not work?
> 
> It is mostly because of the torch version!
> We need torch version <=1.7.0 & >=1.4.0 and torchvision<=0.9 & >=0.5 .

I tried to downgrade **torch==1.7.0 and  torchvision==0.8.1**

an installation with CUDA
`pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

an installation without CUDA
`pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

And it works.

**Comment by youngfish42** [comment]
> 
> 
> It is mos
> 
> > Hello, I had the same issue and your proposition worked @madhavajay, thanks!
> > But why do we have to that and why `pip install syft` alone does not work?
> 
> It is mostly because of the torch version!
> We need torch version <=1.7.0 & >=1.4.0 and torchvision<=0.9 & >=0.5 .

I also had to deal with the same problem and my System Information as follows:

- OS: windows 10
- Language Version:Python 3.7
- Package Manager Version: syft 0.3, torch1.8.1


I tried to downgrade **torch==1.7.0 and  torchvision==0.8.1**

an installation with CUDA
`pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

an installation without CUDA
`pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

And it works.

**Comment by mkeshav** [comment]
`File "setup.py" or "setup.cfg" not found for legacy project syft from git+https://github.com/OpenMined/PySyft@dev#egg=syft`

I get above error when i try to install using `https://github.com/OpenMined/PySyft@dev#egg=syft`

**Comment by phenomenal-manish** [comment]
pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft

ERROR: File "setup.py" not found for legacy project syft from git+https://github.com/OpenMined/PySyft@dev#egg=syft.

**Comment by code-radiator** [comment]
> 

I was also getting the same error as @mkeshav  and @phenomenal-manish . I tried installing an earlier version using pip and it worked for me.

`pip install syft==0.5.0`

https://pypi.org/project/syft/0.6.0/#history

**Comment by Nazmul92** [comment]
> $ pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft

When I tried using ! pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft in colab. 

The error: 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting syft
  Cloning https://github.com/OpenMined/PySyft (to revision dev) to /tmp/pip-install-tjhwud16/syft_5391efd74ee248e785982ea2e00f5980
  Running command git clone --filter=blob:none --quiet https://github.com/OpenMined/PySyft /tmp/pip-install-tjhwud16/syft_5391efd74ee248e785982ea2e00f5980
  Resolved https://github.com/OpenMined/PySyft to commit f43cfe650f02944cc48dc784594274baa9e87b04
ERROR: syft from git+https://github.com/OpenMined/PySyft@dev#egg=syft does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found

**Comment by VirajGhorpade** [comment]
Below worked for me.
It is about torch and torchvison version compatibility

```
1. pip install syft
2. pip install torchvision===0.1.6 torchaudio===0.11.0 -f https://download.pytorch.org/whl/torch_stable.html
```
