### ISSUE TITLE
Batched GC

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5374]
## Description
We would like to be able to batch multiple GC requests and afterwards send them all at once after some heuristic. (used memory/number/time <- some research has to be done)

We might lower the network usage and increase the overall performance of syft.

## Definition of Done
Have a flag introduced in syft named `BATCHED_GC` that when it's set to True, it will lookup for the desired `GC_HEURISTIC`. A new message type named `BatchGCMessage` will be created with a Service/Action attached to it that will be sent after a few pointers will be collected and released after the `GC_HEURISTIC`. A nice starting heuristic would be to release every 10 garbage collected pointers or every 25 secs. It can be a separate process or an async process that does this, the person implementing this should argue which is best (async sounds good to me).

**Comment by LaRiffle** [comment]
We actually had this in 0.2.x! But it was very simplistic

**Comment by tudorcebere** [comment]
@LaRiffle I know, it was actually implemented by you if I remember correctly, I liked the idea and I think that we can do a more customizable version of this for our next release. :)

**Comment by gmuraru** [comment]
Started working on this!
