### ISSUE TITLE
No documentation on readthedocs?

### ISSUE THREAD

**Issue by riccardo94p** [OpenMined/PySyft#5377]
Hello I am currently researching the FedL field for my thesis and was trying to understand the PySyft framework.
I was looking for some tutorials on how to use PySyft with PyTorch in order to do Federated Learning.
Sadly I found out that the official documentation [https://pysyft.readthedocs.io/en/latest/](url) is broken.

I read in #4995 and #5144 that you are aware of this and will fix it by the next release. Any idea on when the next release is going to be?

**Comment by tudorcebere** [comment]
Hi @riccardo94p 

Our awesome writing team is helping us to create some nice docs for our next release! In the meantime, the `examples` folder is where you can understand syft in the best way.

**Comment by jmaunon** [comment]
@riccardo94p @tudorcebere , I have included this to `docs-team` project.

**Comment by madhavajay** [comment]
@jmaunon I spoke to @cereallarceny and I believe we will be deleting the readthedocs.io profile so we can close this.
