### ISSUE TITLE
Uniformize __init__.py files of libraries 

### ISSUE THREAD

**Issue by vsquareg** [OpenMined/PySyft#5388]
## Description
Currently, `__init__.py` files of libraries don't follow any particular template, working with them requires constant referencing with individual ones.

A few instances:
- some libs (like torchvision, torch) use `allowlist.py`, others just directly list the classes/methods in the `__init__.py`.
- create_ast method name, some use `create_libname_ast()`, some use `create_ast()`.

## Resolution
Uniform `__init__.py` files for all libraries.

**Comment by madhavajay** [comment]
@vsquareg some libraries are not optional dependencies yet like `torch` while others are. What exactly is the issue here?

**Comment by vsquareg** [comment]
I see, so non-optional libraries follow one kind of template and optional ones another kind.
