### ISSUE TITLE
Randomize Testing

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5389]
## Description
The testing suite should run in a random order, so we can prevent flakiness on our tests.

## Additional Context
A pytest plugin should be searched for that randomizes the order of test files and the tests that exists in a test file. A nice example would be [0], but other solutions exist as well. The PR should fix any flaky tests that appear as well.

**Comment by vsquareg** [comment]
duet_examples are extremely flaky, most of the times tests fail is due to `ds_proc` being hanged. Should fix this.
