### ISSUE TITLE
Add support for ranges

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5391]
## Description
We don't have support for `range` objects. We would like to add ranges in our primitive supported types.

Definition of DONE:
- [ ] Add some serde tests
- [ ] Make sure Ranges works on other types like Tensor or Pandas
- [ ] Add to `primitive_factory`

## Additional Context
We would like to have wrappers for range objects, to be able to manipulate them.

**Comment by ArtistBanda** [comment]
@tudorcebere I will create a WIP PR, would like to have in-progress feedback.

**Comment by galalen** [comment]
@ArtistBanda also started to work on this issue, I was about to submit a WIP PR
