### ISSUE TITLE
Investigate time.sleep 

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5394]
## Description
Around the codebase, there are a few places where we do `time.sleep`. Each of them should be investigated and preferably removed from the codebase. If a few are kept, a reason why should be added in the PR.

**Comment by ArtistBanda** [comment]
Will create a PR to fix this issue.

**Comment by stoic-signs** [comment]
Hey @tudorcebere  I was looking into this and noticed that there are quite a few used in the benchmark tests. I assume that those are run via the GH Actions. Quite confused about what to do with them. Should I just leave them there?

**Comment by cgoxo** [comment]
I would like to work in this one
