### ISSUE TITLE
PyGrid Messages Tests refactor

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5398]
## Description
Currently, in `tests/syft/grid/messages`, we have quite some duplicate code. Less code means fewer bugs, so we would like to refactor all those files in only one file that covers the same functionality (or even more).

**Comment by teo-milea** [comment]
I can work on that if possible

**Comment by tudorcebere** [comment]
Hi @teo-milea! :wave: 

Please open a PR before starting to work on this so we can give feedback as you go. :1st_place_medal: 

Thanks for your interest in Syft! :100:
