### ISSUE TITLE
Primitive Pointer tests refactor

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5399]
## Description
In `tests/syft/lib/python/*/pointer_test.py` we are testing that pointers behave like they should when working with primitive types. That's a lot of duplicate code, less code means fewer bugs, we would like to move these tests in `tests/syft/core/pointer` without any duplicate code. Bonus points if you add new types to these tests like torch data types, slices, etc.

**Comment by razvanmatisan** [comment]
I would give it a try!:D

**Comment by tudorcebere** [comment]
Hi @razvanmatisan :wave:,

Please open a PR before actually starting to work on it (be sure to check `allow edits from maintainers`) so we can give continuous feedback on your work. :book:

Thanks for your interest in Syft! :raised_hands:

**Comment by stoic-signs** [comment]
Is it okay if I try my hand at it too?
