### ISSUE TITLE
Implement Default index Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#54]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, we want to implement a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, index() and index_select() should return a new tensor and index_add_(), index_copy_(), and index_fill_() should perform the operation inline. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by nahuakang** [comment]
Hi, I'd like to dig into this issue. It seems like `index_select()` is already implemented in tensor.py?

**Comment by samuxiii** [comment]
Hi, I talked to @nahuakang who told me there is no problem if I take the issue.
So I gonna implement this one.

**Comment by samuxiii** [comment]
My first question is about index(), apparently pytorch is able to receive as parameter a 'm' value which can be an integer, ByteTensor or slice. Right now I have the solution for integer but I have no clear if we need the other types. Do we really need these? For example, right now we don't support slices (I didn't see it and if I'm wrong tell me please). Thanks.
