### ISSUE TITLE
Trim needed requirements

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5400]
## Description
We should explore what requirements we actually need in our requirements file `requirements.txt`, as we want to speedup CI. One example would be to investigate the removal of `pyfscaffold` as we don't use it anymore.

**Comment by stoic-signs** [comment]
Could I take this up?

**Comment by tudorcebere** [comment]
Hey! I did this because I figured out it would speed CI. We will post a new issue in a few days on separating in a fancier way our dependencies based on what libs you are using. :)

**Comment by stoic-signs** [comment]
No worries. Thanks for the heads up!
