### ISSUE TITLE
Plan stripped re-construction

### ISSUE THREAD

**Issue by vsquareg** [OpenMined/PySyft#5412]
## Description
Currently, when a plan is created, it contains a lot of metadata like Pointer UIDs, VM addresses, etc. So, if the same plan is created twice, its representation would be completely different.

Solution: to re-construct the plan without any metadata.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
https://github.com/OpenMined/PySyft/issues/5359#issuecomment-807726213

**Comment by madhavajay** [comment]
Duplicate of this: https://github.com/OpenMined/PySyft/issues/5292
