### ISSUE TITLE
Integration test for Duet creation with ID

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5422]
## Description
Create an integration test that validates that Duet creation works fine when passing the IDs (not through loopback).

## Type of Test
- [ ] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [x] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)
- [ ] **Regression test** (e.g. checking if by adding or removing a module of code allows other systems to continue to function as intended)
- [ ] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)
- [ ] **Performance test** (e.g. checking to see how efficient a system is as performing the intended task)
- [ ] Other...

## Expected Behavior
A clear and concise description of what you expected to happen. Do you intend to reach a certain percentage of test coverage for this file, feature, or codebase?

## Additional Context
Add any other context about the tests here.

**Comment by madhavajay** [comment]
Test `OpenGridTokenManualInputExchanger`.
