### ISSUE TITLE
Audit data-science/pandas tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5427]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications.
* Good/Green means that the tutorials works as expected.

This is a great oportunity to get involved into pysyft!

**Comment by jayasuryajsk** [comment]
Hey Can I work on this issue as a part of gsoc application process?

**Comment by jayasuryajsk** [comment]
@jmaunon In data owner notebook, the url to download the dataset and name assigned to the csv file needs to be fixed.
In data scientist notebook the column modification on the data frame can not be performed and we get this error.
![Screenshot_20210409_004147](https://user-images.githubusercontent.com/13784001/114083434-970e9e00-98cc-11eb-8f7f-6a7e0c7dec21.png)

**Comment by blackcymbal** [comment]
I would like work on pandas tutorial documentation.
