### ISSUE TITLE
Audit duet tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5429]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications.
* Good/Green means that the tutorials works as expected.

This is a great oportunity to get involved into pysyft!

**Comment by marcalph** [comment]
I'd like to work on this, I'll open a PR later today!

**Comment by marcalph** [comment]
@jmaumon sry for the delay, finished and duplicated/updated the google doc accordingly
I'd like to continue working on this as I feel comfortable resolving "issues" (apart from the lightning version of mnist where I must confess I'm at loss). 
Am I correct assuming mnist has priority?

**Comment by jmaunon** [comment]
Yes, I would say that `MNIST` had priority. I will try open new issues related to this.
I though that some of these tutorials were integrated in our CI system. Could you check it please?

**Comment by marcalph** [comment]
Okay I'll check for related tests in the CI and start a PR for `MNIST` if needed.

**Comment by marcalph** [comment]
You are absolutely right.. It shows I seem to have a broken install, cannot figure how to fix it, so I opened an issue

**Comment by marcalph** [comment]
@jmaunon you are right, it had to do with the use of GPU as a default, I've fixed things accordingly...
Would you recommend I open a separate PR for each tutorial?

**Comment by jmaunon** [comment]
@marcalph , yes please, open as many PR as you need.

Many of you have contributed to audit tutorials. I will try open the associated issues in order to fix them.

Thanks a lot for your effort!

**Comment by marcalph** [comment]
@jmaunon No worries, I'll open them as I go if that is any help.
