### ISSUE TITLE
Audit homomorphic-encryption tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5430]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications.
* Good/Green means that the tutorials works as expected.

This is a great oportunity to get involved into pysyft!

**Comment by javipus** [comment]
Hi! I can start working on this issue today. Should I just post the results on this thread or is there a better place to submit them?

**Comment by javipus** [comment]
All tutorials work as expected after installing TenSEAL.

Since TenSEAL is not a PySyft dependency, it's likely that it won't be in the user's env. For this reason, I believe it should be made explicit that installing the package is necessary and explain how to do it, e.g. `pip install tenseal`.

**Comment by jmaunon** [comment]
Thanks a lot for your feedback

**Comment by blackcymbal** [comment]
I want to contribute on this issue.
