### ISSUE TITLE
Audit private-ai-series tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5432]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications.
* Good/Green means that the tutorials works as expected.

This is a great oportunity to get involved into pysyft!

**Comment by stoic-signs** [comment]
Hi @jmaunon , can I work on this? I'm going through the Private AI Series right now as well, so it should be fairly quick. I'll open a PR soon and keep updating the progress there!

**Comment by stoic-signs** [comment]
@jmaunon An update. I've updated the Audit doc as well.

NOTE: This list also includes notebooks present in the courses repo.
---

- [x] federated_learning
    - duet_basics: Good
    - duet_fl: Good
    - duet_iris: Good
    - (courses) duet_mnist: Bad (throws error while training). (covered in #5429 )
- [x] (courses) split-nn
    - splitnn/basic: Good
    - splitnn/advanced: Good
    - multilimb-splitnn/basic: Good
    - multilimb-splitnn/advanced: Decent (throws error while training).
    ```
  [2021-04-09T18:56:15.964802+0530][CRITICAL][logger]][18795] Request to access data length rejected.
  [2021-04-09T18:56:15.965163+0530][CRITICAL][logger]][18795] Request to access data length rejected.

  ---------------------------------------------------------------------------
  Exception                                 Traceback (most recent call last)
  ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __len__(self)
      249                 if data_len is None:
  --> 250                     raise Exception
      251 

  Exception: 

  During handling of the above exception, another exception occurred:

  ValueError                                Traceback (most recent call last)
  ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __iter__(self)
      222             try:
  --> 223                 data_len = self.__len__()
      224             except Exception:

  ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __len__(self)
      253             except Exception:
  --> 254                 traceback_and_raise(
      255                     ValueError("Request to access data length rejected.")

  ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/logger.py in traceback_and_raise(e, verbose)
       60         e = Exception(e)
  ---> 61     raise e
       62 

  ValueError: Request to access data length rejected.

  During handling of the above exception, another exception occurred:

  ValueError                                Traceback (most recent call last)
  <ipython-input-15-230656f1092f> in <module>
        3     train_total = 0
        4 
  ----> 5     for in1, in2, label in zip(dl_1, dl_2, dl_local):
        6         opt1.zero_grad()
        7         opt2.zero_grad()

  ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __iter__(self)
      223                 data_len = self.__len__()
      224             except Exception:
  --> 225                 traceback_and_raise(
      226                     ValueError("Request to access data length rejected.")
      227                 )

  ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/logger.py in traceback_and_raise(e, verbose)
       59     if not issubclass(type(e), Exception):
       60         e = Exception(e)
  ---> 61     raise e
       62 
       63 

  ValueError: Request to access data length rejected.
  ```


    - concepts-definition-code: Good
    - attack-on-splitnn: Good
   
- [ ] (course) cryptography
    - ciphers: Good

**Comment by jmaunon** [comment]
> @jmaunon An update. I've updated the Audit doc as well.
> 
> ## NOTE: This list also includes notebooks present in the courses repo.
> * [x]  federated_learning
>   
>   * duet_basics: Good
>   * duet_fl: Good
>   * duet_iris: Good
>   * (courses) duet_mnist: Bad (throws error while training). (covered in #5429 )
> * [x]  (courses) split-nn
>   
>   * splitnn/basic: Good
>   * splitnn/advanced: Good
>   * multilimb-splitnn/basic: Good
>   * multilimb-splitnn/advanced: Decent (throws error while training).
>   
>   ```
>   [2021-04-09T18:56:15.964802+0530][CRITICAL][logger]][18795] Request to access data length rejected.
>   [2021-04-09T18:56:15.965163+0530][CRITICAL][logger]][18795] Request to access data length rejected.
>   
>   ---------------------------------------------------------------------------
>   Exception                                 Traceback (most recent call last)
>   ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __len__(self)
>     249                 if data_len is None:
>   --> 250                     raise Exception
>     251 
>   
>   Exception: 
>   
>   During handling of the above exception, another exception occurred:
>   
>   ValueError                                Traceback (most recent call last)
>   ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __iter__(self)
>     222             try:
>   --> 223                 data_len = self.__len__()
>     224             except Exception:
>   
>   ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __len__(self)
>     253             except Exception:
>   --> 254                 traceback_and_raise(
>     255                     ValueError("Request to access data length rejected.")
>   
>   ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/logger.py in traceback_and_raise(e, verbose)
>      60         e = Exception(e)
>   ---> 61     raise e
>      62 
>   
>   ValueError: Request to access data length rejected.
>   
>   During handling of the above exception, another exception occurred:
>   
>   ValueError                                Traceback (most recent call last)
>   <ipython-input-15-230656f1092f> in <module>
>       3     train_total = 0
>       4 
>   ----> 5     for in1, in2, label in zip(dl_1, dl_2, dl_local):
>       6         opt1.zero_grad()
>       7         opt2.zero_grad()
>   
>   ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/ast/klass.py in __iter__(self)
>     223                 data_len = self.__len__()
>     224             except Exception:
>   --> 225                 traceback_and_raise(
>     226                     ValueError("Request to access data length rejected.")
>     227                 )
>   
>   ~/miniconda2/envs/pysyft/lib/python3.9/site-packages/syft/logger.py in traceback_and_raise(e, verbose)
>      59     if not issubclass(type(e), Exception):
>      60         e = Exception(e)
>   ---> 61     raise e
>      62 
>      63 
>   
>   ValueError: Request to access data length rejected.
>   ```
>   
>   
>   
>   * concepts-definition-code: Good
>   * attack-on-splitnn: Good
> * [ ]  (course) cryptography
>   
>   * ciphers: Good

Thanks a lot!!

**Comment by soham29640** [comment]
Hi! I'm interested in contributing to this issue. Could you please assign it to me?
