### ISSUE TITLE
Audit secure-multi-party-computation tutorials

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5435]
## Context
`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes)

one of the tasks that is not done is to check tutorials in order to know what of them work without problem and what of them need to be updated.

## Output
The output of this issue is just the status:
* Bad/Red means that does not work at all.
* Needs to updated/yellow means that the tutorial works but needs some clarifications.
* Good/Green means that the tutorials works as expected.

This is a great oportunity to get involved into pysyft!

**Comment by dimasquest** [comment]
Can do this one if its open

**Comment by dimasquest** [comment]
From a quick round of importing and running the notebooks, VM notebook does not seem to be compatible with the most recent version of syft

pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft allows to import syft without fft error (which has been brought up in slack multiple times), however, it just ends up failing to import sympc

checking the others ones as well

**Comment by dimasquest** [comment]
all tutorials for smpc fail with exactly 2 types of issues:

1.  `AttributeError: type object 'Tensor' has no attribute 'fft' ` when using the latest version of syft
2. `ModuleNotFoundError: No module named 'sympc'` when using syft 0.3.0.post0.dev1280+gce2510e65 (as suggested in https://openmined.slack.com/archives/C6EEFN3A8/p1616892669121500)

the latter is explained by 
import torch  #  tensor computation

import syft as sy  # core library for remote execution

```
sy.load("sympc")

[2021-04-03T15:22:08.608322+0100][CRITICAL][logger]][1168755] Unable to load package support for: sympc. No module named 'sympc'

```

So looks Red to me unfortunately at this moment

**Comment by jmaunon** [comment]
@dimasquest , thanks a lot for your feedback! 
I have tried to reproduce the tutorial because I colaborated  in this one  and I was familiar. I do not get your errors, I have been capable of installing `pysyft` and `sympc` (separately, if I try to install just `syft` I get your 2nd error)

In any case, I am not capable of running any of tutorials for the following:
* VMs: I get `Request to access data length rejected.`
* Duet: (After some  minor but required modifications) I get `UnknownPrivateException`


@gmuraru , are you aware of this? we could open an issue for fixing

I attach the corresponding errors.

![VMs](https://user-images.githubusercontent.com/16245436/113524567-d9c03580-95af-11eb-90e1-8c7d55926baf.png)

-----
![Duet-error](https://user-images.githubusercontent.com/16245436/113524566-d9279f00-95af-11eb-9ff9-d04a85912d80.png)

**Comment by gmuraru** [comment]
Hello @jmaunon.

For the VM I think that if we use ```get_root_client``` - not the ```get_client``` it should work.
For the other one, I need to look into it.

**Comment by Luminginx** [comment]
Duet:I found when I ran the example that it stopped in the second DUET connection creation process. Console print 'Connecting...' or '..waiting for partner to connect...' and didn't go on.

**Comment by idoiagamiztec** [comment]
> @dimasquest , thanks a lot for your feedback!
> I have tried to reproduce the tutorial because I colaborated in this one and I was familiar. I do not get your errors, I have been capable of installing `pysyft` and `sympc` (separately, if I try to install just `syft` I get your 2nd error)
> 


How did you manage to install them separately?

I have tried everything explained on the Slack page https://openmined.slack.com/archives/C6EEFN3A8/p1616892669121500
, but I keep getting the error. :
 Unable to load package support for: sympc. No module named 'sympc
