### ISSUE TITLE
Update docstrings of src/syft/ast py files

### ISSUE THREAD

**Issue by IrinaMBejan** [OpenMined/PySyft#5437]
# Update docstrings of src/syft/ast

Packages/modules on `dev` branch.

- [ ] callable
- [ ] enum
- [ ] globals
- [ ] klass
- [ ] module
- [ ] property
- [ ] static_attr

## Overview
Documentation is critical in any project. If we want to see our libraries used by other users, they need to understand it, otherwise they will dissapear.

`docs_team` is trying to push some good practices about documentation (inline docstring, tutorials, examples and Readmes). 

One of the tasks already carried out is to audit the code, see this [spreadsheet](https://docs.google.com/spreadsheets/d/1ExD1EQIQtLx03a_h7lBPlvasVsmb38S02Bfw5a7Q62Y/edit#gid=1159978476). This audit has raised some docstring that is missing.

There are many `python` packages and modules, so this issue is restricted add/update/improve **`src/syft/ast` package inline documentation**

### Current docstring status
The quality of the docstring is measured in the following way:

* `interrogate -P -ignore-private <syft>`: Returns the percentage of docstring coverage: `RESULT: FAILED (minimum: 80.0%, actual: 30.1%)`
* `pydocstyle --convention=google <syft/grid package>`: Raises errors according to Google convention (see [this link](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for examples)
* `darglint <syfg/grid package>`: Raises errors according to docstring consistency

### Goal
**The goal is to improve docstring in terms of quality and understanding**. The associated Pull Request must check that previous commands do not raise any unexpected error.

This is a very good first issue if you want to get involved into base code. You probably will **have doubts** becuase you do not fully undesrstand what a python `class` or `function` does. Please **do not hesitate to contact via slack**.

**Comment by dnabanita7** [comment]
I am working on this one already.
