### ISSUE TITLE
 Is there are any branch I can run the example of MNIST?

### ISSUE THREAD

**Issue by IMVector** [OpenMined/PySyft#5444]
## Question

My python version is  3.7.10 ,torch 1.8.1, syft 0.3.0

### The branch of  MNIST_duet
![image](https://user-images.githubusercontent.com/20250697/113544512-0198b300-961b-11eb-85eb-51368fd26391.png)
### The branch of dev
![image](https://user-images.githubusercontent.com/20250697/113544841-a1564100-961b-11eb-9ec2-f45075a8736e.png)

**Comment by marcalph** [comment]
@IMVector did you solve this?

**Comment by IMVector** [comment]
> @IMVector did you solve this?

Thanks，I got the release code,and I successfully ran it.
