### ISSUE TITLE
Use Safety and Snyk as part of CI tests

### ISSUE THREAD

**Issue by hwrdtm** [OpenMined/PySyft#5448]
## Feature Description
We need more security checks to happen during CI in order to gain confidence that we are not introducing vulnerabilities during development.

## Is your feature request related to a problem?
We currently run `bandit` during CI but bandit is a tool for us to check the security of _how_ we write code. We are missing checks for the security of _what_ we are writing code with (eg. 3rd party libraries). We can achieve the latter by looking towards tools such as [Safety](https://pyup.io/safety/) and [Snyk](https://support.snyk.io/hc/en-us/articles/360004699377-Snyk-for-Python). 

We should consider using both for the following reasons:
- each tool checks for vulnerabilities against their own databases so it's best to have a wider coverage from using multiple tools
- Safety, when on the Free pricing plan, checks for vulnerabilities against a database that is updated only **once per month**. AFAICS, with Snyk we are able to always check our code against the latest vulnerability database. 

## Additional Context
As per my Dependency Report (`dep_report.txt`) in [this comment here](https://github.com/OpenMined/X-PenTest/issues/14#issuecomment-813445073), there is currently one vulnerability that Snyk reports:

```
Tested 53 dependencies for known issues, found 1 issue, 1 vulnerable path.

Issues with no direct upgrade or patch:
  ✗ Timing Attack [High Severity][https://snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-1022152] in cryptography@3.4.6
    introduced by aiortc@1.2.0 > cryptography@3.4.6
  No upgrade or patch available

```
 
There are currently no known patches for this vuln and given the importance of `aiortc` to syft, it doesn't seem like we can remove `aiortc` soon. Perhaps we can replace it with a different package? Otherwise, if Snyk is reporting this vuln and is causing CI tests to fail, we should find ways to include Snyk into CI without having it prevent us from merging PRs.

cc @tudorcebere

**Comment by madhavajay** [comment]
@hwrdtm Just to understand you would like us to?
- pin cryptography>=3.4.7
- add synk and safety scanning to our CI

**Comment by Param-29** [comment]
I'd like to take up this issue. 

Q: @security-team As report generated is highly dependent on versions of the packages, I think it would be a good idea to run these commands with minimum versions of the packages we support? Example: Pillow, 
I see following as the output of `safety check`

```
+==============================================================================+
| REPORT                                                                       |
| checked 178 packages, using free DB (updated once a month)                   |
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| urllib3                    | 1.26.3    | >=1.26.0,<1.26.4         | 40014    |
| pyyaml                     | 5.3.1     | <5.4                     | 39611    |
| pip                        | 21.0.1    | <21.1                    | 40291    |
| pillow                     | 7.2.0     | <8.0.1                   | 40264    |
| pillow                     | 7.2.0     | <8.1.0                   | 40265    |
| pillow                     | 7.2.0     | <8.1.0                   | 40270    |
| pillow                     | 7.2.0     | <8.1.0                   | 40271    |
| pillow                     | 7.2.0     | <8.1.1                   | 40266    |
| pillow                     | 7.2.0     | <8.1.1                   | 40272    |
| pillow                     | 7.2.0     | <8.1.1                   | 40273    |
| pillow                     | 7.2.0     | <8.1.1                   | 40274    |
| pillow                     | 7.2.0     | <8.1.1                   | 40275    |
| pillow                     | 7.2.0     | <8.1.2                   | 40263    |
| pillow                     | 7.2.0     | <8.1.2                   | 40267    |
| pillow                     | 7.2.0     | <8.1.2                   | 40268    |
| pillow                     | 7.2.0     | <8.1.2                   | 40269    |
+==============================================================================+

```

**Comment by hwrdtm** [comment]
@madhavajay 

>add synk and safety scanning to our CI

That's correct. I see from https://github.com/OpenMined/PySyft/pull/5542/files we've added `safety`, do we plan on adding Snyk too?

>pin cryptography>=3.4.7

I'd say upgrade to whichever latest version `cryptography` which fixes the vuln that is mentioned. Not sure if by 3.4.7 they would've fixed that vuln yet. But yea, whichever version is vuln-free, we could pin to next IMO.

**Comment by tudorcebere** [comment]
@Param-29 solved this. Congrats!
