### ISSUE TITLE
How to realize the Federated Learning parellelly with syft?

### ISSUE THREAD

**Issue by TudouJack** [OpenMined/PySyft#5453]
## Question
How to realize the Federated Learning parellelly with syft?

## Further Information
The version 0.3.0 seems still does not provide functions about FL which can help us realize it conveniently. And there is also no tutorials for FL with version 0.2.9 in the github project. 

for example,

`
for i in range(10):

    # train bob's model

    bobs_opt.zero_grad()
    bobs_pred = bobs_model(bobs_data)
    bobs_loss = ((bobs_pred - bobs_target)**2).sum()
    bobs_loss.backward()
    bobs_opt.step()
    bobs_loss = bobs_loss.get().data

    # train alice's model

    alices_opt.zero_grad()
    alices_pred = alices_model(alices_data)
    alices_loss = ((alices_pred - alices_target)**2).sum()
    alices_loss.backward()
    alices_opt.step()
    alices_loss = alices_loss.get().data
`

Now I train two models in order(bob first, alice second). If I want to train them parellelly in a federated learning way, 
what should I do with pysyft?

## System Information
 - OS: windows 10
 - Language Version: Python 3.7
 - Package Manager Version: syft 0.2.9

**Comment by TudouJack** [comment]
https://blog.openmined.org/upgrade-to-federated-learning-in-10-lines/

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
