### ISSUE TITLE
Add Connection Diagnostic Information

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5456]
## Description
To help people debug their connections we could provide information like:
- Able to reach github domain
- Able to get network_addresses
`https://raw.githubusercontent.com/OpenMined/OpenGridNodes/master/network_address`
- Able to reach STUN server

## Definition of Done
Each of these steps should be logged out with meaningful messages and errors and a separate function called, `sy.test_network()` could be added which runs through these checks and reports the output.

**Comment by teo-milea** [comment]
Hello, can I work on this?

**Comment by tudorcebere** [comment]
Sure! Assigned.

**Comment by cgoxo** [comment]
I want to work on this issue
