### ISSUE TITLE
RuntimeError: The size of tensor a (640) must match the size of tensor b (64) at non-singleton dimension 0

### ISSUE THREAD

**Issue by TudouJack** [OpenMined/PySyft#5459]
## Question
syft.exceptions.PureFrameworkTensorFoundError and RuntimeError: The size of tensor a (640) must match the size of tensor b (64) at non-singleton dimension 0

## Further Information
`
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

class Arguments():
    def __init__(self):
        self.batch_size = 64
        self.test_batch_size = 8
        self.epochs = 5
        self.lr = 0.001
        self.log_interval = 100

args = Arguments()

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 500)
        self.fc2 = nn.Linear(500, 10)
    def forward(self, x):
        x = x.view(-1, 784)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x

import syft as sy

hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
james = sy.VirtualWorker(hook, id="james")
compute_nodes = [bob, alice]

federated_train_loader = sy.FederatedDataLoader(
        datasets.MNIST('../data', train=True, download=True, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))  
        ])).federate(compute_nodes),   
        batch_size=args.batch_size, shuffle=True)

test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])),
        batch_size=args.test_batch_size, shuffle=True)

remote_dataset = (list(), list())

for batch_idx, (data, target) in enumerate(federated_train_loader):
    remote_dataset[compute_nodes.index(data.location)].append((data, target))

def update(data, target, model, optimizer):
    model.send(data.location)
    optimizer.zero_grad()
    pred = model(data)
    loss = F.mse_loss(pred.view(-1), target)
    loss.backward()
    optimizer.step()

    if batch_idx % args.log_interval == 0:
        print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
            epoch, batch_idx * args.batch_size, len(federated_train_loader) * args.batch_size,
                   100. * batch_idx / len(federated_train_loader), loss.item()))
    return model

bobs_model = Net()
alices_model = Net()

bobs_optimizer = optim.SGD(bobs_model.parameters(), lr=args.lr)
alices_optimizer = optim.SGD(alices_model.parameters(), lr=args.lr)

models = [bobs_model, alices_model]
params = [list(bobs_model.parameters()), list(alices_model.parameters())]
optimizers = [bobs_optimizer, alices_optimizer]

def train(epoch):
    print("train begins")
    for data_index in range(len(remote_dataset[0])-1):
        # update remote models
        for remote_index in range(len(compute_nodes)):
            data, target = remote_dataset[remote_index][data_index]
            # data, target = data.to(device), target.to(device)
            models[remote_index] = update(data, target, models[remote_index], optimizers[remote_index])
        # encrypted aggregation
        new_params = list()
        for param_i in range(len(params[0])):
            spdz_params = list()
            for remote_index in range(len(compute_nodes)):
                spdz_params.append(params[remote_index][param_i].copy().fix_precision().share(bob, alice, crypto_provider=james).get())

            new_param = (spdz_params[0] + spdz_params[1]).get().float_precision()/2
            new_params.append(new_param)

        # cleanup
        with torch.no_grad():
            for model in params:
                for param in model:
                    param *= 0

            for model in models:
                model.get()

            for remote_index in range(len(compute_nodes)):
                for param_index in range(len(params[remote_index])):
                    params[remote_index][param_index].set_(new_params[param_index])
    print("over")

def test():
    print("test")
    models[0].eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        # data, target = data.to(device), target.to(device)
        print(data,target)
        output = models[0](data)
        test_loss += F.mse_loss(output.view(-1), target, reduction='sum').item()  # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1]  # get the index of the max log-probability
        correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))

import time
t = time.time()

for epoch in range(args.epochs):
    print(f"Epoch {epoch + 1}")
    train(epoch)
    test()

total_time = time.time() - t
print('Total', round(total_time, 2), 's')
`
## Screenshots
![image](https://user-images.githubusercontent.com/47101111/114298788-9c493400-9aea-11eb-9e96-e77261b92275.png)

![image](https://user-images.githubusercontent.com/47101111/114298666-19c07480-9aea-11eb-92ac-7124524adebb.png)

## System Information
 - OS: windows 10

 - Language Version:  Python 3.7
 - Package Manager Version: syft 0.2.9, torch 1.4.0

**Comment by tudorcebere** [comment]
Hi! 0.2 hit EOL with the release of 0.5.0rc1, no issues/PRs are going to target this specific version anymore, but checkout 0.5.0rc1, as it's close to feature parity with 0.2.x.
