### ISSUE TITLE
Integrating Pandas into PySyft

### ISSUE THREAD

**Issue by arpitvaghela** [OpenMined/PySyft#5466]
## Feature Description
Integrating pandas into PySyft, currently, PySyft supports `pd.Dataframe` and `pd.Series`. Adding more modules, classes and methods to PySyft
### Classes
- [ ] BooleanDtype
- [x] Categorical (#5449) 
- [ ] CategoricalDtype 
- [ ] CategoricalIndex
- [x] DataFrame
- [ ] DateOffset
- [ ] DatetimeIndex
- [ ] DatetimeTZDtype
- [ ] ExcelFile
- [ ] ExcelWriter
- [ ] Float64Index
- [ ] Grouper
- [ ] HDFStore
- [ ] Index
- [ ] Int16Dtype
- [ ] Int32Dtype
- [ ] Int64Dtype
- [ ] Int64Index
- [ ] Int8Dtype
- [ ] Interval
- [ ] IntervalDtype
- [ ] IntervalIndex
- [ ] MultiIndex
- [ ] NamedAgg
- [ ] Period
- [ ] PeriodDtype
- [ ] PeriodIndex
- [ ] RangeIndex
- [x] Series
- [ ] SparseDtype
- [ ] StringDtype
- [ ] Timedelta
- [ ] TimedeltaIndex
- [ ] Timestamp
- [ ] UInt16Dtype
- [ ] UInt32Dtype
- [ ] UInt64Dtype
- [ ] UInt64Index
- [ ] UInt8Dtype 

### Global Function
- [ ] array
- [ ] bdate_range
- [ ] concat
- [ ] crosstab
- [ ] cut
- [ ] date_range
- [ ] eval
- [ ] factorize
- [ ] get_dummies
- [ ] infer_freq
- [ ] interval_range
- [ ] isna
- [ ] isnull
- [ ] json_normalize
- [ ] lreshape
- [ ] melt
- [ ] merge
- [ ] merge_asof
- [ ] merge_ordered
- [ ] notna
- [ ] notnull
- [ ] period_range
- [ ] pivot
- [ ] pivot_table
- [ ] qcut
- [ ] set_eng_float_format
- [ ] show_versions
- [ ] test
- [ ] timedelta_range
- [ ] to_datetime
- [ ] to_numeric
- [ ] to_pickle
- [ ] to_timedelta
- [ ] unique
- [ ] value_counts
- [ ] wide_to_long

### Modules
- [ ] array (along with the classes in the module )
- [ ] plotting
- [ ] io
- [ ] api
- [ ] tseries

**Comment by Bhuvan-21** [comment]
Is this issue available to work on?

**Comment by arpitvaghela** [comment]
It was created for a GSoC Project by the same name.
