### ISSUE TITLE
Integrating numpy to syft

### ISSUE THREAD

**Issue by cgoxo** [OpenMined/PySyft#5467]
## Integrating numpy to PySyft.
Currently syft supports np.ndarray. The methods, classes and modules are listed below.

#### Array Objects
- [x] Constructing arrays
- [x] Array attributes
- [x] Array methods
- [ ] Arithmetic, matrix multiplication, and comparison operations
- [ ] Special methods
#### Scalers
- [ ] Attributes
- [ ] Methods
#### Data Type Objects
- [ ] Attributes
- [ ] Methods
#### Standard Array Subclasses
- [ ] Character arrays
- [ ] Record arrays
- [ ] Standard container class
#### Masked arrays
- [ ] Methods Listed
#### Constants
- [ ] Methods listed
#### Universal Functions
- [ ] Attributes
- [ ] Methods
- [ ] Math Operation
- [ ] Trigonometric functions
- [ ] Bit-twiddling functions
- [ ] Comparison functions
- [ ] Floating functions 
#### Routines
- [ ] Array Creation Routines
- [ ] Array manipulation routines
- [ ] Binary operations
- [ ] String Operation
- [ ] Datetime Support Functions
- [ ] Business Day Functions
- [ ] Data type routines
- [ ] Creating data types
- [ ] Optionally SciPy-accelerated routines
- [ ] Mathematical functions with automatic domain
- [ ] Floating point error handling
- [ ] Functional programming
- [ ] NumPy-specific help functions
- [ ] Indexing routines
- [ ] Input and output
- [ ] Linear algebra
- [ ] Logic functions
- [ ] Matrix library
- [ ] Miscellaneous routines
- [ ] Padding Arrays
- [ ] Set routines
- [ ] Sorting, searching, and counting
- [ ] Statistics
- [ ] Window functions

**Comment by madhavajay** [comment]
@cgoxo Great work so far, but can we discuss this before any more work is done. I would like to take a more programmatic approach to lib support rather than manually adding ops, tests, serde and return types.
