### ISSUE TITLE
Integrate NumPy into PySyft

### ISSUE THREAD

**Issue by stoic-signs** [OpenMined/PySyft#5470]
## Feature Description
This issue will eventually integrate NumPy into PySyft.

## Is your feature request related to a problem?
No, it is due to a lack of current support. 

## What alternatives have you considered?
There are presently no alternatives.

## Are you interested in working on this yourself?
Yes.

## Additional Context
The checklist will be added soon.

**Comment by Bhuvan-21** [comment]
Is this available to work on?

**Comment by madhavajay** [comment]
This is being worked on.
