### ISSUE TITLE
Perform Federated Learning of encrypted model

### ISSUE THREAD

**Issue by harikrishnankh** [OpenMined/PySyft#5476]
## Question
**Can we do Federated Learning of encrypted model**

Hi, I am working on the federated learning code of yours and successfully executed that. I have doubt regarding the the model training. Is it possible to train on encrypted model using SMPC.  **I will brief out the steps that I am looking for.**
1. Distribute the datasets to virtual workers.
2. Encrypt the model using sy.share() method and distribute among the same virtual workers
3. Do training on the this encrypted model in two virtual workers
4. Get back the models and aggregate it.

**Is that Possible?**
**Will it provide an accurate model?**

**Comment by iamtrask** [comment]
Just my 2 cents - we absolutely want to get there. I'd say biggest blocker (Among several) is encrypted autograd

**Comment by Wuliaxue** [comment]
Did you achieve this goal?

**Comment by rasswanth-s** [comment]
@Wuliaxue , This feature is being implemented in the upcoming 0.7.0 release
