### ISSUE TITLE
Support Torch 1.8.1

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5496]
## Description
We should check torch 1.8.1 change log and add support in the AST and CI as needed.
For now we could replace 1.8.0 with 1.8.1 in the matrix to reduce CI actions.

## Definition of Done
Torch 1.8.1 is supported at least to the same set of methods that are currently supported in 1.8.0 and any new functionality is added to the remaining torch functionality ticket.

**Comment by ArtistBanda** [comment]
I think #5265 could be used as a good reference. 
Is this already been worked or can I create a PR?

**Comment by Param-29** [comment]
> I think #5265 could be used as a good reference. 
> Is this already been worked or can I create a PR?

It's slightly different than #5265, anyway it's already assigned so I'd suggest you to either talk to Tudor or take up some other issue.

**Comment by Param-29** [comment]
I'd like to take up this issue.
