### ISSUE TITLE
AttributeError: module 'syft' has no attribute 'TensorFlowHook'

### ISSUE THREAD

**Issue by JozefKondas** [OpenMined/PySyft#5507]
https://stackoverflow.com/questions/67248373/attributeerror-module-syft-has-no-attribute-tensorflowhook

**Comment by avinsit123** [comment]
Which version of Syft are you using? If it is 0.2.x, switch to 0.5. PySyft has been completed revamped after 0.2 and there is no use of hooks anymore.

**Comment by JozefKondas** [comment]
here is my syft version from pip list
syft 0.3.0.post0.dev1298+g30278611f
syft-proto 0.5.3
syft-tensorflow 0.1.0

**Comment by avinsit123** [comment]
@JozefKondas seems like you are running the wrong code for this version. Support for hooks is deprecated in `0.3.0` .  Try running the below code to create a vm and have a root user. 
```python
import syft as sy
bob_vm = sy.VirtualMachine(name="bob")
bob_root = bob_vm.get_root_client()
ptr = bob_root.torch.Tensor([1,2,3])
ptr = ptr.get()
print(ptr)
```
Also, syft no longer supports Tensorflow.

**Comment by JozefKondas** [comment]
I will use torch, thanks for help

**Comment by HninPannPhyu** [comment]
@avinsit123  could you please share me the link for syft updated documentation?

**Comment by nidhitiwari11998** [comment]
@avinsit123 I am using syft 0.5.0 and what you recommended is working, but could you please tell me how can I send some different data to a client ?
