### ISSUE TITLE
Can I use syft and pygrid to implement MPC on multiple computers with different IPs，（not DUET）?Are there any program cases?

### ISSUE THREAD

**Issue by Lone-Survivor2020** [OpenMined/PySyft#5508]
Hello，Can I use syft and pygrid to implement MPC on multiple computers with different IPs，（not DUET）? 
And Can I run the program in a .py file instead of jupyter botebook?
For example，I have three nodes: Alice(192.168.10.1), Bob(192.168.10.2),Mark(192.168.10.3).Mark wants to get the data of Alice and Bob through MPC to sum.

**Comment by madhavajay** [comment]
Hi @Lone-Survivor2020 we are working on Multi-worker functionality and examples for PyGrid, and yes it will be runnable without Jupyter Notebooks. We recently published an updated video of PyGrid 0.5 here: https://www.youtube.com/watch?v=IW4Tt4qBpHo

**Comment by PravinChandran** [comment]
Do we have support for multi-worker now ??
