### ISSUE TITLE
MNIST GPU training is failed

### ISSUE THREAD

**Issue by JosephKang** [OpenMined/PySyft#5509]
## Description
Try to run MNIST GPU training example from https://github.com/OpenMined/PySyft/tree/dev/examples/duet/mnist but failed. However, CPU training works fine.

## How to Reproduce
1. Open Data owner and Data Scientist notebook based on https://github.com/OpenMined/PySyft/tree/dev/examples/duet/mnist
2. Run Data Owner Code Part 1 to launch duet
3. Run Data Scientist Code Part 1 to join duet
4. Run Data Owner Code Part 2 to add handler
5. Run Data Scientist Code Part 2 to do training
6. Error log show both on Data Scientist training cell and Data Owner handler cell. 

## Expected Behavior
No error happened

## Screenshots
- Data Scientist
> Code
```
import time

args["dry_run"] = True  # comment to do a full train
print("Starting Training")
for epoch in range(1, args["epochs"] + 1):
    epoch_start = time.time()
    print(f"Epoch: {epoch}")
    # remote training on model with remote_torch
    train(model, remote_torch, train_loader_ptr, optimizer, epoch, args, train_data_length)
    # local testing on model with local torch
    test_local(model, torch, test_loader, test_data_length)
    scheduler.step()
    epoch_end = time.time()
    print(f"Epoch time: {int(epoch_end - epoch_start)} seconds")
    if args["dry_run"]:
        break
print("Finished Training")
```
> Error
![image](https://user-images.githubusercontent.com/3213161/115989749-72b40080-a5f2-11eb-9df7-bbcb14e43b14.png)

- Data Owner
![image](https://user-images.githubusercontent.com/3213161/115989784-9e36eb00-a5f2-11eb-9620-021fbe7431b3.png)

## System Information
 - OS: ubuntu Server
 - OS Version: LTS 18.04
 - Language Version: Python 3.6.9
 - Package Manager Version: syft = 0.5.0rc1, torch=1.8.0, torchcsprng=0.2, torchvision=0.9.0
 - Browser (if applicable): Google Chrome
 - Browser Version (if applicable):  90.0.4430.85
 
## Additional Context
Found some explanation on https://stackoverflow.com/questions/59013109/runtimeerror-input-type-torch-floattensor-and-weight-type-torch-cuda-floatte, but failed to send data to cuda  for data_ptr and and target_ptr for the following pySyft training def.
```

def train(model, torch_ref, train_loader, optimizer, epoch, args, train_data_length):
    # + 0.5 lets us math.ceil without the import
    train_batches = round((train_data_length / args["batch_size"]) + 0.5)
    print(f"> Running train in {train_batches} batches")
    if model.is_local:
        print("Training requires remote model")
        return

    model.train()

    for batch_idx, data in enumerate(train_loader):
        data_ptr, target_ptr = data[0], data[1]
        optimizer.zero_grad()
        output = model(data_ptr)
        loss = torch_ref.nn.functional.nll_loss(output, target_ptr)
        loss.backward()
        optimizer.step()
        loss_item = loss.item()
        train_loss = loss_item.resolve_pointer_type()
        if batch_idx % args["log_interval"] == 0:
            local_loss = None
            local_loss = train_loss.get(
                reason="To evaluate training progress",
                request_block=True,
                timeout_secs=5
            )
            if local_loss is not None:
                print("Train Epoch: {} {} {:.4}".format(epoch, batch_idx, local_loss))
            else:
                print("Train Epoch: {} {} ?".format(epoch, batch_idx))
        if batch_idx >= train_batches - 1:
            print("batch_idx >= train_batches, breaking")
            break
        if args["dry_run"]:
            break
```

**Comment by aeinrw** [comment]
Has the problem been solved?

**Comment by JosephKang** [comment]
I didn't test it for the moment so I close it.
