### ISSUE TITLE
SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by Rateofteasing** [OpenMined/PySyft#5511]
## Question
**  File "<ipython-input-13-6e515c33d8a7>", line 22
    results = await asyncio.gather(
             ^
SyntaxError: 'await' outside function**

## Further Information
run from /examples/tutorials/advanced/websockets-example-MNIST/Federated learning with websockets and federated averaging.ipynb
## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
python = 3.6.5
syft = 0.2.4
torch = 1.4

**Comment by yigedage** [comment]
@midokura-silvia

**Comment by madhavajay** [comment]
0.2 is no longer supported.
