### ISSUE TITLE
Add proto support for SyferText's BERTIterator

### ISSUE THREAD

**Issue by AlanAboudib** [OpenMined/PySyft#5539]
## Feature Description

Add a protobuf template for the BERTIterator in SyferText. This will be similar to the BPTT iterator

https://github.com/OpenMined/PySyft/blob/alan_syfertext_lm/proto/lib/syfertext/data/iterators/language_modeling/bptt_iterator.proto

**Comment by Dat-Boi-Arjun** [comment]
@AlanAboudib I will work on this
