### ISSUE TITLE
Fix Pandas Categorical ordered=False

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5543]
## Description
In `tests/syft/lib/pandas/categorical_test.py`:
```
# pd.Categorical(["a", "b", "c", "a"], ordered=False), # Results in Error in comparision func
```

## Definition of Done
Test is fixed and passes.

**Comment by arpitvaghela** [comment]
@madhavajay This is expected behavior as pandas don't allow comparison of `pd.Categorical` if 'ordered' is the same

**Comment by madhavajay** [comment]
@arpitvaghela good call, although I think we should still check the object contains the same elements or when sorted matches so the test should be updated.
