### ISSUE TITLE
Encrypted sharing of data and model.

### ISSUE THREAD

**Issue by harikrishnankh** [OpenMined/PySyft#5550]
## Question
**How the additive secret sharing works on model and data?**

## Further Information
I was looking at a problem in which both data and model are encrypted using secure multiparty computation before training to not expose both data and model.  I am using the function **x.fix_precision().share(*workers, crypto_provider)** of pysyft to encrypt both data and model.

I would like to know what's happening inside that function. How the splitting is done on data and model.

- Is data is split by rows? ie. if there are100 rows, it is split as two 50 rows tables.
- Is the model is split based on layers? ie. If there are 8 layers, splits that into two 4 layer network

**Comment by rasswanth-s** [comment]
@harikrishnankh To answer your question on additive secret sharing.

**Secure Multiparty Computation (MPC)**: It is one of the privacy advocates. It allows multiple parties to compute a joint function without revealing their private inputs beyond what is revealed by the output of the function.

**Secret Sharing** is one of the primitives of MPC.

Secret sharing allows you to split the secret into shares such that no party or a subset can determine the secret.

Additive Secret Sharing: The secret is split into shares and addition of the all the shares would reveal the secret.

Ex: Consider the integer  7 and 3 parties, it can be split as 4,2,1
Each of the three parties holds a share, all three parties have to combine the shares to reveal the secret. It is an **n-out-of-n secret sharing**, where n parties have to combine the shares to reveal the secret.
4+2+1=7(Reconstructed Secret)

Generally, sharing is done over finite fields.

Consider the MPC functionality with three parties, where we want to multiply two numbers a,b. The number a,b are shared between the parties by secret sharing. Each party holds shares of a,b. We apply a custom protocol for multiplication and maintain the **invariant** that output  (a*b) is also secret shared. Each party has only the shares at each computation revealing nothing about the private input.

Considering the ML scenario of private inference, the model (weights and biases) are secret shared between parties after training. The user wanting to do inference shares his data as shares to the parties and the output shares are sent to the user. The invariant is maintained at each step.


There are also various secret sharing schemes such as Threshold Secret Sharing, Verifiable Secret Sharing.

I have abstracted many technical details.
Here are resources that would be helpful :
[Crypto Notes](https://www.cs.cornell.edu/courses/cs4830/2010fa/lecnotes.pdf)
[Crypto Notes -SM](https://cseweb.ucsd.edu/~mihir/papers/gb.pdf)

**Comment by tudorcebere** [comment]
Hi @harikrishnankh !

I hope @rasswanth-s managed yo answer your question! I will be closing this for now.
