### ISSUE TITLE
AttributeError: type object 'Tensor' has no attribute 'fft'

### ISSUE THREAD

**Issue by anshulg825** [OpenMined/PySyft#5571]
I tried running !pip install syft on google colab, and it gets installed without any errors.
But while doing import syft as sy
I am getting error: type object 'Tensor' has no attribute 'fft'
Please help!!!

**Comment by anshulg825** [comment]
Same thing happened when I tried on my windows using Conda.

**Comment by mojtaba732** [comment]
Hi,
Try this
pip uninstall syft
pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft

**Comment by napoay** [comment]
> Hi,
> Try this
> pip uninstall syft
> pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft

@mojtaba732 

I tried on my mac and get  the error :
```
 ✘ 👍  ~  sudo pip3 install git+https://github.com/OpenMined/PySyft@dev#egg=syft
WARNING: The directory '/Users/pan/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/pan/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting syft
  Cloning https://github.com/OpenMined/PySyft (to revision dev) to /private/tmp/pip-install-289tqzaz/syft
  Running command git clone -q https://github.com/OpenMined/PySyft /private/tmp/pip-install-289tqzaz/syft
  fatal: unable to access 'https://github.com/OpenMined/PySyft/': Failed to connect to github.com port 443: Operation timed out
ERROR: Command errored out with exit status 128: git clone -q https://github.com/OpenMined/PySyft /private/tmp/pip-install-289tqzaz/syft Check the logs for full command output.
```

**Comment by anshulg825** [comment]
Okay so what I figured out was, the course on Private and Secure AI on Udacity has old pysyft implementations, and therefore while installing you will have to install lower versions of Pysyft and torch version. I feel it's better to pursue the course on Openmined website as it has more recent pysyft implementations.
Although I still don't understand that If the developers change so much in one update, why did they not add this as a caution in the documentation or on udacity's course.
