### ISSUE TITLE
How to use GPU on syft?

### ISSUE THREAD

**Issue by JHSUYU** [OpenMined/PySyft#5582]
## Question
 When I use .cuda(), GPU does not come into effect.

## System Information
 - OS: [MacOS]
 - Language Version: [Python 3.7,]
 - Package Manager Version: [syft=0.2.4, pytorch=1.4.0, torchvision=0.5.0]

**Comment by LaplaceZhang** [comment]
Syft got totally re-written after version 0.3.0 and functions in v0.2.x are no longer supported, see source code for v0.2.x [here](https://github.com/OpenMined/PySyft/blob/syft_0.2.x/syft/frameworks/torch/mpc/cuda/tensor.py). The new way to use is just like Pytorch, see source code [here](https://github.com/OpenMined/PySyft/blob/dev/packages/syft/src/syft/lib/torch/module.py#L196)
