### ISSUE TITLE
[Experimental] Gradient compression

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5587]
## Description
We would like to have a method to compress gradients in a federated learning setup.

Notes:
* https://arxiv.org/pdf/1912.04977.pdf
* https://arxiv.org/abs/1712.01887

## Are you interested in working on this improvement yourself?
- Yes, I am.
- 
## Additional Context
Part of the High Performance Data Channel

**Comment by koenvanderveen** [comment]
This would be super exciting to have!
