### ISSUE TITLE
How to calculate communication cost between workers and central server(me)?

### ISSUE THREAD

**Issue by SamiurRahman1** [OpenMined/PySyft#5607]
## Question
How to calculate communication cost between workers and central server(me)?

## Further Information
I want to calculate the communication cost(amount of data in MB transferred between the workers and central server each epoch) during the training process. The aim is to implement different model compression methods and see how effective they are in regards to the communication cost.

## System Information
 - OS: Linux
 - OS Version: Ubuntu 20.04
 - Language Version: Python 3.8

**Comment by tudorcebere** [comment]
Hey @SamiurRahman1!

Currently, we are working on a benchmarking suite internally, but we are not close to over. This is an interesting idea to have as a metric, we will add it to our benchmarking suite.

Thank you for your interest in Syft!

**Comment by Tintumarygeorge** [comment]
@tudorcebere any update on this Question ? I am also having same requirement. Please let me know
