### ISSUE TITLE
duet cannot be searialized

### ISSUE THREAD

**Issue by StrangeTcy** [OpenMined/PySyft#5612]
## Description
Trying to run duet MNIST example leads to the following error:
>UserWarning: The following variables cannot be serialized: duet

## How to Reproduce
1. Clone the PySyft repository
2. Install syft==0.5.0rc1
3. Go to the `duet` folder and then to the MNIST folder.
4. Run Data Owner and Data Scientist notebooks on different machines
5. See error

## Expected Behavior
Errorless processing of remote dataset

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.8
 - Package Manager Version pip

## Additional Context
Both notebooks were run in Yandex.DataSphere on c1.4 machines. It's possible to use machines with GPUs if this is the cause of the problem (which seems unlikely)

**Comment by tudorcebere** [comment]
Hi @StrangeTcy,

With the latest release/dev branch, I can't reproduce the error (python 3.8, torch 1.7.1, Ubuntu OS).

Could you give me more info/could you test with the latest branch of dev to see if you can still reproduce it?

Thank you!

**Comment by StrangeTcy** [comment]
Hello. 

@tudorcebere , as far as I can recall, I'm using torch 1.8, which might be one of the reason for the error.

Anyway, test results on the latest dev are to follow.

**Comment by StrangeTcy** [comment]
@tudorcebere 

Ok, so far the results have revealed the following: the problem persists if I try to install `syft==0.5.0rc1` from pip, and it doesn't arise if I `pip install syft==0.3.0`, but in the latter case syft.util has no `get_root_data_path`
