### ISSUE TITLE
Torch Tensor Serialization/Deserialization must include complete TensorProto 

### ISSUE THREAD

**Issue by kamathhrishi** [OpenMined/PySyft#5616]
## Feature Description
Currently, serialization/deserialization methods just serialize/deserialize tensor data methods which include shape, datatype, and contents of tensor. But, for future requirements such as training and CUDA it is necessary to have methods for serialization/deserialization for complete tensorProto which include attributes such as has_grad,device and grad. 

The protobuf definition is found here https://github.com/OpenMined/PySyft/blob/dev/packages/syft/proto/lib/torch/tensor.proto
 
The serialization/deserialization methods 
https://github.com/OpenMined/PySyft/blob/629ee53a098310766153f897c2e9885f7fd193fb/packages/syft/src/syft/lib/torch/tensor_util.py#L50

## Is your feature request related to a problem?
Required for future requirements of SyMPC training and device information (toggling CPU and CUDA). 

Even the current implementation of ShareTensor proto uses only TensorData which must be changed after serialization/deserialization methods for complete TensorProto is implemented.

**Comment by gmuraru** [comment]
I changed the description because, for the moment, this is not something we require. It would be good to have all the tensor info (that it is in the proto file) at the serialization time, but this is not a blocker for us

**Comment by madhavajay** [comment]
We currently have the following:
```
message TensorProto {
    TensorData tensor = 1;
    bool requires_grad = 2;
    TensorData grad = 3;
    syft.lib.torch.Device device = 4;
}
```

@kamathhrishi Can you explain what fields specifically need to be added?

**Comment by kamathhrishi** [comment]
@madhavajay No fields need to be added. Right now methods exist only for serialization/deserialization of TensorData and not TensorProto. 

It's not an immediate requirement like @gmuraru mentioned. But, in the future.

**Comment by gmuraru** [comment]
The problem is in the `tensor_util.py` because we do not take into account all the fields (like "device"). But this is not an urgent matter.
