### ISSUE TITLE
Get objects from Duet's store not working properly (even with added handler and request submitted)

### ISSUE THREAD

**Issue by daler3** [OpenMined/PySyft#5617]
## Description
In Duet, the Data Scientist is not able to get an object from the duet store immediately, even if handlers have been added and requested have been submitted. However, when running the code to get the object a second time, everything works fine (even though errors keep getting printed on the Data Owner side.

## How to Reproduce
Example with OpenMined's PSI Lbrary: 

Data Owner's side (assuming Duet is setup):
```
fpr=1e-6 
duet.requests.add_handler(
    action="accept", 
    tags=["fpr"]
)
sy_fpr = sy.lib.python.Float(fpr)
sy_fpr_ptr = sy_fpr.send(duet, pointable=True, tags=["fpr"], description="false positive rate")
```

Data Scientist's side:

```
#get False Positive Rate
fpr_ptr = duet.store["fpr"]
fpr_ptr.request(reason="I want to know the fpr", timeout_secs=-1)
fpr = fpr_ptr.get()
```

## Expected Behavior
When running ` fpr_ptr.get()`  I expect to get the variable immediately, as the request has been submitted and the handler has been added. This does not always happen (see description above).

## Screenshot
I attach a screenshot of what happens on the Data Owner's side when the problem described above happens. Even after re-running the `.get()` function the second time (and after actually getting the object then), the print out of the error message in the screenshot keeps occurring.
![doside](https://user-images.githubusercontent.com/15127774/120234184-be904000-c257-11eb-9bc2-816a72c1fd5d.png)

**Comment by tudorcebere** [comment]
Hey @daler3 !

Using the latest release of syft and python 3.9 with a fresh install I couldn't replicate this issue. Could you try again (if it still replicates, could you give me OS info)
