### ISSUE TITLE
Retrieval from duet store loading endlessly

### ISSUE THREAD

**Issue by AdrianGlauben** [OpenMined/PySyft#5638]
## Description
After exploring some issue with loading pointers from the duet store I found the size of the objects in the duet store to be the problem. When the objects in the duet store are over a certain size threshold (for me that threshold is somewhat consistent between a tensor of size 9.000.000 an 11.000.000) then the DS on the other side can´t load the pointer. The program will just get stuck in an endless loop, however if the tensor in the store is below the threshold the pointer will load instantly.

## How to Reproduce
See screenshots.

## Expected Behavior
The pointer to the data should not take any significant amount of time to load.

## Screenshots
![image](https://user-images.githubusercontent.com/36222794/120785655-9fcacb80-c52d-11eb-8f5c-bdc5172b7577.png)
Run this then load on the DS side. With 9.000.000 it should run instantly, with 11.000.000 the data_ptr = duet.store[0] instruction gets stuck in endless loop on DS side.

## System Information
 - OS: Windows 10
 - OS Version: 20H2 (Build 19042.985)
 - Language Version: Python 3.9.4 / syft 0.5.0rc1 / pytorch 1.8.0 / jupyterlab 3.0.14
 - Package Manager Version: Conda 4.10.1

**Comment by tudorcebere** [comment]
Hey @AdrianGlauben!

Could you install the latest from the dev branch to see if you can replicate the error anymore? Thank you!
