### ISSUE TITLE
Protoc flag --experimental_allow_proto3_optional not supported for protoc_version>=3.16

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#5639]
## What?
We use build_proto.sh in scripts for compiling protobuf files. The flag `--experimental_allow_proto3_optional` is not available for protoc versions>=3.16

The protoc flag:
https://github.com/OpenMined/PySyft/blob/446214984547e6885c9a8fe6e8b66240faddcc7f/packages/syft/scripts/build_proto.sh#L13

## Additional Context
Optional is allowed by default from https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0, we do not need that flag.We could include a condition by allowing the build_proto.sh to execute only when version>=3.15.Allow for version>= 3.15 explicit `optional` is not allowed , as fields are `optional` by default.

**Comment by madhavajay** [comment]
@rasswanth-s Since `--experimental_allow_proto3_optional` is not needed anymore and we are in control of the version of `protoc` that we use to compile our protobufs, we should just remove this flag and force everyone to upgrade their `protoc`. Can you provide a PR for this?
