### ISSUE TITLE
Attribute error with Syft

### ISSUE THREAD

**Issue by spnzig** [OpenMined/PySyft#5641]
I have installed Pysyft version 0.3.0 on my windows machine and imported it in jupyter. When I try to run the commands from the examples (PySyft/packages/syft/examples/homomorphic-encryption/Tutorial_0_TenSEAL_Syft_Data_Owner.ipynb) , it gives attribute errors.

```
import syft as sy
import tenseal as ts
import pytest 
sy.load(tenseal)

```
Here it throws an attribute error.

![image](https://user-images.githubusercontent.com/30037676/120957947-49030300-c774-11eb-9384-f5090b723d8f.png)

## System Information
 - Vitual env on a Windows 10 OS
 - Python                   3.7.1
 - pip                         21.1.2
 - torch                      1.7.1+cpu
 - torchaudio             0.7.2
 - torchvision             0.8.2+cpu
 - tenseal                   0.3.4

**Comment by madhavajay** [comment]
Two issues, one your version is likely very out of date, we will be doing an official release as soon as we merge the monorepo until then the latest release candidate is available here:
```
$ pip install syft==0.5.0rc2
```

Second issue, sy.load takes a string:
```
import syft as sy
import tenseal as ts
import pytest 
sy.load("tenseal")
```

**Comment by spnzig** [comment]
Thank you for the response. I re-installed it as per the above. Now I am getting the below error. 

`ModuleNotFoundError: No module named 'notebook'`

![image](https://user-images.githubusercontent.com/30037676/120984348-369ac080-c798-11eb-8b34-7aa607aa9865.png)

Are there any dependencies that I need to pre-install prior to installing syft==0.5.0rc2?
