### ISSUE TITLE
Scaling up PySyft with Cython

### ISSUE THREAD

**Issue by rhobro** [OpenMined/PySyft#5656]
## Question
Does cythonizing PySyft code have any effect? Would it be possible in the future to cythoniz PySyft for increased performance?

**Comment by tudorcebere** [comment]
Hi @rhobro!

We have a few use cases for sure! Currently, we are exploring this option, porting down stuff to Rust, creating bindings, etc. We did not settle for something yet, but we are interested for sure in this! :)

**Comment by rhobro** [comment]
That is great to know @tudorcebere . My use case requires high performance for production deployment.

In the meantime, is there any other way to speed up PyGrid server side?

I've seen the rust experimental repo you are referring to. Will it be able to run grid on the server side or will it be an alternative for KotlinSyft on client side?

**Comment by tudorcebere** [comment]
Hey @rhobro,

We are working on this, but I can't give you an estimated timeline or roadmap for performance improvement on pygrid.

In terms of rust, we don't know exactly how it's going to look like, but we would like at some point to have our networking backbone in it for our workers (swift, js, kotling, python, etc). Long road ahead tho, don't expect to see this too soon 😆

**Comment by rhobro** [comment]
@tudorcebere Can KotlinSyft be used server side? Does it utilise the GPU to train?
