### ISSUE TITLE
[PyGrid] Update broken hyperlinks

### ISSUE THREAD

**Issue by jmaunon** [OpenMined/PySyft#5669]
## Description
With the new monorepo structure, most of the examples from pygrid made reference to pygrid repositoy. These notebooks needs to be updated with the proper hyperlink

PyGrid Examples can be found at this [link](https://github.com/OpenMined/PySyft/tree/dev/packages/syft/examples/pygrid)

**Comment by jmaunon** [comment]
Thanks @divyadixit . What is needed is to review and update the links that appear in the notebooks from PyGrid example folder. Some of them are broken due to the monorepo recent structure

**Comment by SauravMaheshkar** [comment]
At the moment [**`notebooks/`**](https://github.com/OpenMined/PySyft/tree/dev/notebooks) contains all the examples right ?
