### ISSUE TITLE
Make PyGrid Node and Network API's a no-delete database

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PySyft#5695]
## Description
We should never delete records in the DB so that we have a complete, historical log of every event that takes place in the system. This is very important for many data owners for legal purposes.

This will be done by adding a `created_at`, `updated_at`, and `deleted_at` key to models in the database. Likewise, for any GET requests, we should default to not showing rows with the `deleted_at` key set to anything except `Nil`.

## Are you interested in working on this improvement yourself?
- No, but I think @Benardi  would be interested.

**Comment by madhavajay** [comment]
0.2 is no longer supported.
