### ISSUE TITLE
Static FL: /get-model is not protected

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/PySyft#5697]
## Description
FL model can be protected.
In this case, `/federated/get-model` checks that the worker is authenticated.
However, new `/get-model` endpoint (https://github.com/OpenMined/PyGrid/pull/609) is not protected.
There seems to be need for 2 types of auth:
1. Existing: worker authentication - for training the model, sending diff, etc.
2. Missing: user authentication - for hosting the model, downloading the model, etc.

I think `/get-model` needs type 2 auth and should be available only to user who hosted the FL model.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
Add any other context or screenshots.

**Comment by madhavajay** [comment]
0.2 is no longer supported.
