### ISSUE TITLE
Implement median aggregation

### ISSUE THREAD

**Issue by vnitu02** [OpenMined/PySyft#5699]
## Question
I want to implement other aggregation plans (e.g., based on the median instead of the mean)

## Further Information
I'm starting from the _01-Create-plan_ example and I'm replacing:

```
def avg_plan(avg, item, num):
    new_avg = []
    for i, param in enumerate(avg):
        new_avg.append((avg[i] * num + item[i]) / (num + 1))
    return new_avg
```

with

```
def avg_plan(diffs):
    return th.stack(diffs).median(dim=0)[0]
```

I see that when the `iterative_plan` is `False`, `avg_plan` takes all the model updates as parameter. My question is how to define `diffs` so that this "averaging" plan can be compiled? 
I tried `diffs = [model_params, model_params]` but it does not seem to work.

**Comment by madhavajay** [comment]
0.2 is no longer supported.
