### ISSUE TITLE
If 0.2.9 pysyft supports 3 workers.

### ISSUE THREAD

**Issue by fu1001hao** [OpenMined/PySyft#5723]
Hi I just want to know in 0.2.9 pysyft, if by minor modifying some files, we could make it support more virtual workers. Because I have the following issue:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/57201660/122941252-375c5680-d343-11eb-95ba-97edbc6ed575.png">

**Comment by fu1001hao** [comment]
BTW, the new pysyft version does not support 3 parties, either.

When I do

<img width="497" alt="image" src="https://user-images.githubusercontent.com/57201660/122945244-72ac5480-d346-11eb-9c3b-4d3d918f7098.png">

I have 

<img width="989" alt="image" src="https://user-images.githubusercontent.com/57201660/122945321-822b9d80-d346-11eb-87de-035ba7a30a32.png">

When will the 3 or more parties' computation be supported?

**Comment by madhavajay** [comment]
@fu1001hao syft 0.2x was deprecated in 2020 and syft 0.5 was deprecated in 2021. We will be providing lots of new tutorials on FL in 0.7.0 shortly.
