### ISSUE TITLE
Is there a case of Pygrid+SyMPC?

### ISSUE THREAD

**Issue by LoneSurvivor1993** [OpenMined/PySyft#5742]
This page cannot be opened
https://github.com/OpenMined/PySyft/blob/pygrid_demo/examples/pygrid/model_inference/Model%20Inference%20PyGrid%20%2B%20SyMPC.ipynb
![image](https://user-images.githubusercontent.com/10841478/123603592-9d0d7e80-d82c-11eb-9922-d16d7843d5fa.png)

**Comment by madhavajay** [comment]
Both PyGrid and SyMPC are now part of the monorepo and we have working implementations of SMPC inside the core. Our docs are undergoing an update.
