### ISSUE TITLE
This page cannot be opened 

### ISSUE THREAD

**Issue by LoneSurvivor1993** [OpenMined/PySyft#5743]
https://github.com/OpenMined/PySyft/blob/pygrid_demo/examples/pygrid/model_inference/Model%20Inference%20PyGrid%20%2B%20SyMPC.ipynb

![image](https://user-images.githubusercontent.com/10841478/123604199-350b6800-d82d-11eb-8b35-ab52fa3d5e73.png)

**Comment by madhavajay** [comment]
These are out of date. Our docs are undergoing an update.

**Comment by madhavajay** [comment]
These are out of date. Our docs are undergoing an update.
