### ISSUE TITLE
Slack Links are Dead

### ISSUE THREAD

**Issue by ngagesmu** [OpenMined/PySyft#5744]
All of the invite links to the slack channels do not work anymore.

## Where?
All GitHub pages & links on the websites

## Who?
People who want to join the Slack

## What?
Have a working link to the Slack

**Comment by ganzuul** [comment]
I would like to discuss bioethics for a project proposal involving PySyft. I hope this open issue can get some attention.

**Comment by ruch798** [comment]
The link seems to be fixed on the main website as of now.

**Comment by ngagesmu** [comment]
> The link seems to be fixed on the main website as of now.

Unfortunately, you need a @canada.ca email address to sign up. So, the links are still broken.

**Comment by tcp** [comment]
Hi @ngagesmu! That is very strange. What link in particular is requiring that?

All Slack links appear to be working — slack.openmined.org

Are you having the same issue @ganzuul?

**Comment by ganzuul** [comment]
@tcp Same issue, yes. I just tried it on Android and it says that something went wrong. I'm using a gmail.com address.

**Comment by ngagesmu** [comment]
![image](https://user-images.githubusercontent.com/54559789/125205278-0f2b8d80-e247-11eb-9303-491273f1e085.png)

**Comment by tcp** [comment]
Thank you @ngagesmu and @ganzuul. I'll pass this along to the workspace admins.

**Comment by iamtrask** [comment]
I've updated the link but it may take a few hours to propagate - for now use this: https://communityinviter.com/apps/openmined/openmined
