### ISSUE TITLE
Broken. New API changes have broken the ModelCentricFLClient in the FL examples of model centric and possibly others. Please advise or fix.

### ISSUE THREAD

**Issue by algarecu** [OpenMined/PySyft#5747]
Broken. New API changes have broken the ModelCentricFLClient in the FL examples of model centric and possibly others. Please advise or fix.

_Originally posted by @algarecu in https://github.com/OpenMined/PySyft/issues/5410#issuecomment-870802970_

The code is out of date, and cannot be used with latest examples of pygrid as far as it was tested. There must be another way to host the federated training plan with the new API  of v0.5.0 but undocumented or code of model_centric_fl_client.py in in the syft package is actually broken.

**Comment by madhavajay** [comment]
@algarecu the MCFL tests are still passing in the `0.5.0` branch here: https://github.com/OpenMined/PySyft/blob/syft_0.5.0/packages/syft/tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py

All code from `0.5.0` is public on PyPI, dockerhub and available in the `syft_0.5.0` branch.
The PyGrid repo is `deprecated` and the latest stable version is in the branch above.

`dev` is undergoing lots of changes at the moment so please use the above branch for `0.5.0` stability.

**Comment by algarecu** [comment]
Already using package syft 0.5.0, however using branch `main` (e.g., as the file version seems equal there), which seemingly had integrated latest stable commits I see coming up yes. However, I still see not all integration tests were passed in that file I mention above over the branch `main`, yet it was committed 1 month ago approx. Will check back a conda deployment on 0.5.0 to see if anything changes but I suspect it won't if they model centric example contains any deprecated methods for hosting the training plan on a grid domain of pygrid as it gets stucked just at the end there.

**Comment by algarecu** [comment]
This works for the connect part only,
```
from syft.grid.client.client import connect  # Method used to connect with the node.
from syft.grid.client.grid_connection import GridHTTPConnection

domain = connect(
     url="http://localhost:5000",  # Domain Address
     conn_type=GridHTTPConnection,
 )  # HTTP Connection Protocol
 print(domain)
```
Result:
<GridClient: <UID: 66bc7c48b36044e285a3448d43fcff20>>
Process finished with exit code 0

===============================================================================================

However, old code does results in a 404 Handshake Error, which does not seem right as said and relates to not finding the server of the app in the server. 
```
grid_address = "127.0.0.1:5000"
grid = ModelCentricFLClient(address=grid_address, secure=False)
grid.connect()
```
Result:
```
Traceback (most recent call last):
  File "/home/algarecu/Documents/github/PySyft/packages/syft/examples/federated-learning/model-centric/mcfl_create_plan_mobile.py", line 285, in <module>
    grid.connect()
  File "/home/algarecu/anaconda3/envs/pysyft/lib/python3.9/site-packages/syft/federated/model_centric_fl_base.py", line 52, in connect
    self.ws = websocket.create_connection(**args_)
  File "/home/algarecu/anaconda3/envs/pysyft/lib/python3.9/site-packages/websocket/_core.py", line 595, in create_connection
    websock.connect(url, **options)
  File "/home/algarecu/anaconda3/envs/pysyft/lib/python3.9/site-packages/websocket/_core.py", line 252, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/algarecu/anaconda3/envs/pysyft/lib/python3.9/site-packages/websocket/_handshake.py", line 59, in handshake
    status, resp = _get_resp_headers(sock)
  File "/home/algarecu/anaconda3/envs/pysyft/lib/python3.9/site-packages/websocket/_handshake.py", line 145, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 404 NOT FOUND

Process finished with exit code 1
```
===============================================================================================
Server itself runs in development mode as follows, as well as database which I see it is created using also the next command correctly.

./run.sh --name bob --port 5000 --start_local_db 'postgresql+psycopg2://postgres:@localhost:5432/localdb'
...
[2021-06-30 11:40:48]: 22009 INFO domain version: 0.5.0 in Dev is Ready
===============================================================================================
Does any of this ring any bells @madhavajay ?  I also want to try the same in the dockerized version rather than local, but these results make me think it is not a matter of local environment setup but a network problem with websockets or the pygrid api.

**Comment by madhavajay** [comment]
0.5 is deprecated. I did release a new version today but only to fix issues with installing syft on Apple Silicon.
