### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused while trying grid.connect() (examples/federated-learning/model-centric/mcfl_create_plan.ipynb)

### ISSUE THREAD

**Issue by k0gane** [OpenMined/PySyft#5754]
## Question
I tried tutorial of federated learning on examples/federated-learning/model-centric/mcfl_create_plan.ipynb.
And a ConnectionRefusedError was raised at the location shown in the image below.
What should I do to resolve this error?
## Screenshots
![image](https://user-images.githubusercontent.com/50335010/124384114-d94c4d80-dd0a-11eb-9d77-daac4ae11015.png)

## System Information
 - OS: Whidows + wsl2
 - OS Version: [10 Education]
 - Language Version: [Pytnon 3.9.4]
 - Package Manager Version: [Conda 4.10.1]

**Comment by SimaZD** [comment]
hah, at first, i met the same problem.
then, you would find that you should you miss the step starting the pygrid domain.
when you try to start a domain no matter using the docker or manual
you will find some other problems like "missing environment varibles","ConnectionRefusedError: [Errno 111] Connection refused","BrokenPipeError: [Errno 32] Broken pipe" and so on.
i still dont know how to fix some of them.

using syft0.5.0

**Comment by madhavajay** [comment]
0.5 is no longer supported.
