### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by zpskt** [OpenMined/PySyft#5772]
## When I execute part02 in the example, I use Python file to execute it directly, prompting an error

ERROR is :AttributeError: 'NoneType' object has no attribute 'serialize'

![截屏2021-07-13 上午9 06 06](https://user-images.githubusercontent.com/49719634/125374805-5b4b0f00-e3ba-11eb-83fe-50c5ceb2dc72.png)

## System Information
 - OS: Ubuntu 20.04.1 LTS
 - OS Version: 5.4.0-77-generic
 - Language Version:python3.8.5
 -syft Version:2.9.0

**Comment by madhavajay** [comment]
syft 0.2 is deprecated
