### ISSUE TITLE
Reduce the binary size of 'hagrid' so that it's small enough to be added to PyPI

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#5775]
At the time of writing, the [hagrid tool](https://github.com/OpenMined/PySyft/tree/demo_strike_team_branch_4/packages/hagrid) can be locally installed, but it cannot be pip installed.

The first step in this project is to reduce the binary size of hagrid so that it can be added to PyPI. At present it is too large!

------

If you would like to claim this issue, you must first open a pull request with the following attributes:
- **Title:** [WIP] Reduce the binary size of 'hagrid' so that it's small enough to be added to PyPI
- **Branch merging into:** [iamtrask/ch65/pip-install-hagrid-and-it-s-deps-automagically](https://github.com/OpenMined/PySyft/tree/iamtrask/ch65/pip-install-hagrid-and-it-s-deps-automagically)
- **Description:** must include the text "[ch65]" and "#5777"

If you do not claim this issue by creating a pull request, others will assume you are not working on it and will pick up the task themselves (regardless of whether you comment on this issue).

**Comment by divyanshsinghvi** [comment]
Hi @iamtrask , 
I was interested to solve this `good first issue`. How should I go about reducing the size of the binary? If you could point me where I should begin with that would be indeed helpful. 
Also, while sending the pull request do I have to merge changes from the branch `demo_strike_team_branch_4` to the hagrid tool?

**Comment by iamtrask** [comment]
HI @divyanshsinghvi - i'm afraid that I shouldn't have marked this one as a good first issue. Per your comment, I don't have clear instructions on how we should make the binary smaller and would need someone to dig in and help the team figure that out. :) That said, if the project is still interesting to you given that additional challenge, let us know!
