### ISSUE TITLE
Lint Errors (0.6 alpha branch)

### ISSUE THREAD

**Issue by bottomparm** [OpenMined/PySyft#5782]
## Description
Tox lint errors (generally styling) need to be resolved.

## How to Reproduce
1. Checkout PySyft branch: `demo_strike_team_branch_4`
2. Run `tox -e lint`

## Expected Behavior
No lint errors!

## Screenshots
`Check python ast.........................................................Failed
- hook id: check-ast
- exit code: 1

packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/encoder.py: failed parsing with CPython 3.9.5:

    Traceback (most recent call last):
      File "/Users/dhrebenach/.cache/pre-commit/repodgmp_4en/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_ast.py", line 20, in main
        ast.parse(f.read(), filename=filename)
      File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
      File "packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/encoder.py", line 318
        False=False,
        ^
    SyntaxError: invalid syntax
    
packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py: failed parsing with CPython 3.9.5:

    Traceback (most recent call last):
      File "/Users/dhrebenach/.cache/pre-commit/repodgmp_4en/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_ast.py", line 20, in main
        ast.parse(f.read(), filename=filename)
      File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
      File "packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py", line 163
        (s, end),
        ^
    SyntaxError: invalid syntax

Trim Trailing Whitespace.................................................Passed
Check docstring is first.................................................Failed
- hook id: check-docstring-first
- exit code: 1

packages/grid/ansible/mitogen/ansible_mitogen/transport_config.py:33 Module docstring appears after code (code seen on line 30).
packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/mitogen_get_stack.py:33 Module docstring appears after code (code seen on line 30).

Check JSON...............................................................Passed
Check for added large files..............................................Passed
Check Yaml...............................................................Passed
Check for merge conflicts................................................Passed
Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen_free.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen_free.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_kubectl.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_kubectl.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/node/tasks/main.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/node/tasks/main.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/containers/tasks/containers.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/containers/tasks/containers.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/mixins.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/mixins.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/setns.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/setns.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/core.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/core.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/containers/handlers/main.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/containers/handlers/main.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/containers/tasks/main.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/containers/tasks/main.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/parent.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/parent.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/utils.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/utils.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_local.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_local.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/loaders.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/loaders.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/connection.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/connection.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/jail.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/jail.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/target.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/target.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/services.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/services.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/docker-compose.override.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/docker-compose.override.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/mitogen_get_stack.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/mitogen_get_stack.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/unix.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/unix.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible.cfg: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible.cfg`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_machinectl.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_machinectl.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/su.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/su.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/profiler.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/profiler.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/fork.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/fork.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/buildah.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/buildah.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/select.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/select.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/planner.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/planner.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/minify.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/minify.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/strategy_plugins/mitogen_linear.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/strategy_plugins/mitogen_linear.py`
  If it is supposed to be executable, double-check its shebang.
README.md: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x README.md`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/fakessh.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/fakessh.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/node/tasks/docker.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/node/tasks/docker.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_sudo.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_sudo.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/mitogen_fetch.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/action/mitogen_fetch.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_ssh.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_ssh.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/module_finder.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/module_finder.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/kubectl.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/kubectl.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/docker-compose.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/docker-compose.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/docker.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/docker.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_buildah.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_buildah.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/group_vars/all/vars.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/group_vars/all/vars.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/logging.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/logging.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/ssh.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/ssh.py`
  If it is supposed to be executable, double-check its shebang.
.gitignore: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x .gitignore`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/debug.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/debug.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/site.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/site.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/master.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/master.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_doas.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_doas.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/os_fork.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/os_fork.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_jail.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_jail.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/compat/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/compat/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/Vagrantfile: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/Vagrantfile`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_su.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_su.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/affinity.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/affinity.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/strategy.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/strategy.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_lxd.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_lxd.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/compat/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/compat/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen_linear.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen_linear.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/transport_config.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/transport_config.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/__init__.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/__init__.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/runner.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/runner.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/compat/pkgutil.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/compat/pkgutil.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_setns.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_setns.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/doas.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/doas.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/encoder.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/encoder.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/scanner.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/scanner.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/compat/tokenize.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/compat/tokenize.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/node/handlers/main.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/node/handlers/main.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/parsing.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/parsing.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/service.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/service.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_lxc.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_lxc.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/lxd.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/lxd.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/node/tasks/system.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/node/tasks/system.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/process.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/process.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen_host_pinned.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/strategy/mitogen_host_pinned.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_docker.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/ansible_mitogen/plugins/connection/mitogen_docker.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/roles/containers/tasks/hagrid.yml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/roles/containers/tasks/hagrid.yml`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/lxc.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/lxc.py`
  If it is supposed to be executable, double-check its shebang.
packages/grid/ansible/mitogen/mitogen/sudo.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x packages/grid/ansible/mitogen/mitogen/sudo.py`
  If it is supposed to be executable, double-check its shebang.

Debug Statements (Python)................................................Failed
- hook id: debug-statements
- exit code: 1

packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/encoder.py - Could not parse ast

        Traceback (most recent call last):
          File "/Users/dhrebenach/.cache/pre-commit/repodgmp_4en/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/debug_statement_hook.py", line 55, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
          File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
          File "packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/encoder.py", line 318
            False=False,
            ^
        SyntaxError: invalid syntax

packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py - Could not parse ast

        Traceback (most recent call last):
          File "/Users/dhrebenach/.cache/pre-commit/repodgmp_4en/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/debug_statement_hook.py", line 55, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
          File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
          File "packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py", line 163
            (s, end),
            ^
        SyntaxError: invalid syntax

Tests should end in _test.py.............................................Passed
Fix requirements.txt.....................................................Passed
isort (python)...........................................................Passed
black....................................................................Passed`

## System Information
 - OS: iOS
 - OS Version: 11.4
 - Language Version: Python 3.9.5, Node v14.17.3
 - Package Manager Version: Conda 4.10.1
 - Browser (if applicable): Not Applicable
 - Browser Version (if applicable): Not Applicable

**Comment by iamtrask** [comment]
Thank you sir!
