### ISSUE TITLE
 hagrid deploy and teardown aws machines

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#5785]
Blocked By: None

We need the ability for [hagrid](https://github.com/OpenMined/PySyft/tree/demo_strike_team_branch_4/packages/hagrid) to perform basic deployment and teardown of single nodes on AWS, which can subsequently be provisioned with Domain/Network functionality (perhaps using a tool like ansible).

If another github issue has already provided this for another cloud provider, please follow their conventions on the CLI grammar!

**Acceptance Criteria:**

- this feature shouldn't require any additional local file configuration
- this feature should be usable out of the box immedaitely after running "pip install hagrid" (see [ch65])
- this feature should ask for any additional information it needs in the command prompt (login information, what machine to use, etc.). 
- this feature should provide good defaults and there should be an optional place to put local file configuration for inputs like username/password relating to a cloud provider (but this should be optional as mentioned)
- all three cloud providers should be configurable using the same CLI grammar

------

If you would like to claim this issue, you must first open a pull request with the following attributes:

- **Title:** [WIP]  hagrid deploy and teardown aws machines
- **Branch merging into:** [iamtrask/ch108/hagrid-create-and-terminate-vms-on-aws-azure](https://github.com/OpenMined/PySyft/tree/iamtrask/ch108/hagrid-create-and-terminate-vms-on-aws-azure)
- **Description:** must include the text "[ch108]" and "#5784"

If you do not claim this issue by creating a pull request, others will assume you are not working on it and will pick up the task themselves (regardless of whether you comment on this issue).

**Comment by hershd23** [comment]
Hi @iamtrask is this issue still available? If so I am interested to take it up and will create the PR for it.

**Comment by Rohan581** [comment]
Hey @iamtrask !  Is this issue still available? If yes, then I'm interested to work on it.
