### ISSUE TITLE
assocition_requests error

### ISSUE THREAD

**Issue by fantasticboy19** [OpenMined/PySyft#5794]
## Description
When i want to try /syft/examples/federating_learning , when i use do_client.assocition_requests.create(), it failed.

`
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-5-227a9703b797> in <module>
     13 #     conn_type= GridHTTPConnection, # HTTP Connection Protocol
     14 # )
---> 15 domain_node = setup_and_connect(url="http://localhost:5002", email="admin@email.com", password="pwd123")
     16 
     17 # network_node = connect(

<ipython-input-5-227a9703b797> in setup_and_connect(url, email, password, node_name, domain_name)
      4         return _connect()
      5     except Exception as e:
----> 6         client = connect(url=url)
      7         client.setup(email=email, password=password, node_name=node_name, domain_name=domain_name)
      8         return _connect()

~/anaconda3/envs/pysyft-0.5-latest-release/lib/python3.9/site-packages/syft/grid/client/client.py in connect(url, conn_type, credentials, user_key)
    234     user_key: Optional[SigningKey] = None,
    235 ) -> GridClient:
--> 236     return GridClient(
    237         credentials=credentials,
    238         url=url,

~/anaconda3/envs/pysyft-0.5-latest-release/lib/python3.9/site-packages/syft/grid/client/client.py in __init__(self, credentials, url, conn_type, client_type, user_key)
     70             _user_key = SigningKey(_user_key.encode(), encoder=HexEncoder)
     71         else:
---> 72             metadata = self.conn._get_metadata()  # type: ignore
     73             if not user_key:
     74                 _user_key = SigningKey.generate()

~/anaconda3/envs/pysyft-0.5-latest-release/lib/python3.9/site-packages/syft/grid/client/grid_connection.py in _get_metadata(self)
    103 
    104         response = session.get(self.base_url + "/metadata")
--> 105         content = json.loads(response.text)
    106 
    107         metadata = content["metadata"].encode("ISO-8859-1")

~/anaconda3/envs/pysyft-0.5-latest-release/lib/python3.9/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    344             parse_int is None and parse_float is None and
    345             parse_constant is None and object_pairs_hook is None and not kw):
--> 346         return _default_decoder.decode(s)
    347     if cls is None:
    348         cls = JSONDecoder

~/anaconda3/envs/pysyft-0.5-latest-release/lib/python3.9/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~/anaconda3/envs/pysyft-0.5-latest-release/lib/python3.9/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end
JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

## System Information
 - OS: ubuntu
 - OS Version: 16.04
 - Language Version: syft 0.5.0 , grid-network grid-domain docker image latest
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
0.5 is no longer supported.
