### ISSUE TITLE
PyGrid PyDP example broken

### ISSUE THREAD

**Issue by szczepanTopolski** [OpenMined/PySyft#5797]
## Description
PyDP [example](https://github.com/OpenMined/PySyft/blob/dev/packages/syft/examples/pygrid/tutorials/PyDP.ipynb) doesn't work with PyGrid. It crashes every time at .get() with "Unknown private Exception".

## Expected Behavior
Approximate value of the float pointer should be displayed as a result of private_mean function.

## Screenshots
![image (2)](https://user-images.githubusercontent.com/52822004/126120503-fbb023fa-d1ac-4540-b1b4-7648db817aa6.png)
![image (3)](https://user-images.githubusercontent.com/52822004/126120529-36f18849-0a41-45a2-b5eb-fe0368c97278.png)

## System Information
 - OS: Windows 10, Ubuntu 20.04, iOS
 - Language Version: Python 3.8

**Comment by madhavajay** [comment]
@szczepanTopolski I believe this is an issue with PyDP. Check the latest versions here: https://github.com/OpenMined/PyDP/
