### ISSUE TITLE
Fix Syft Unit Tests

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5813]
## Description
Fix all broken tests in `demo_strike_team_branch_4` branch marked as @pytest.mark.xfail with the string "MADHAVA" next to them.

https://app.clubhouse.io/openmined/story/289/fix-syft-unit-tests

## Acceptance Criteria
Tests all pass in tox and CI.

- [ ] gc_test.py
- [ ] functionality_test.py
- [ ] message_test.py
- [ ] resolve_pointer_type_test.py
- [ ] domain_test.py
- [ ] pointer_test.py
- [ ] gc_strategies_test.py
- [ ] duet_test.py
- [ ] messages_test.py
- [ ] ordered_dict_serde_test.py
- [ ] dict_serde_test.py
- [ ] parameter_test.py
- [ ] tensor_remote_and_serde_test.py

**Comment by rasswanth-s** [comment]
I am closing long standing Github issues belonging to older PySyft versions(<=0.7). Kindly re-open the issue , if this issue needs to be addressed.
