### ISSUE TITLE
The error of example of remote MPC?

### ISSUE THREAD

**Issue by jiyanxin** [OpenMined/PySyft#5824]
I want to run a remote example of MPC, but when I run the PySyft/packages/syft/examples/secure-multi-party-computation/Duet/1-DS-1-DO, there's a bug "The session *** could not be found". I also run some local example of MPC, but I don't kown how to write a remote example according to local example. I want to get a help of remote example. Now, I have two choices, one is that if I want to run remote example 1-DS-1-DO without bugs, which version of syft and sympc I should install ? the other is that how to write a remote example according to local example without bugs , anyone can give help? thanks!!!

**Comment by rasswanth-s** [comment]
Hi @jiyanxin , 
At that time  we had SyMPC  in another repo, https://github.com/OpenMined/SyMPC , PySyft did not have full fledged SyMPC
Currently we have some example notebooks in https://github.com/OpenMined/PySyft/tree/dev/notebooks/smpc/Training%20Demo
For Initial Training Part, 

Creating Good SMPC Example notebook is at top of TODO list, Within maybe one or two weeks, I will create good SMPC notebook example.

**Comment by rasswanth-s** [comment]
To work with examples, you would need to launch Domain Nodes through hagrid , 
The syft documentation,would help you with the initial setup and deployment
https://openmined.github.io/PySyft/

**Comment by rasswanth-s** [comment]
I am closing this issue, as this was for the old notebooks,
For any question feel free to DM me on OM slack
My handle `Rasswanth`
Joining LInk : [OM Slack](https://slack.openmined.org)
