### ISSUE TITLE
Add documentation for the new SMPC functionality from Syft

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#5881]
## Where?
This is an umbrella ticket to add documentation to the SMPC functionalities class.
See title - There is a new MPCTensor and ShareTensor and they both need documentation.
There is also a SMPCExecutor service that requires documentation.
For more information, contact me on Slack.

## Who?
Any person that wants to read the codebase.

## What?
 - Write docstring to the methods/functions

**Comment by DARK-art108** [comment]
Can I work upon this @gmuraru ?

**Comment by somiljain7** [comment]
hey @gmuraru ,can i work on this?

**Comment by gmuraru** [comment]
Sure

**Comment by gmuraru** [comment]
Yep! I will assign both of you to the issue and you can sync on how to split the work :+1:
