### ISSUE TITLE
Slack invitation link directly jumps to https://communityinviter.com/

### ISSUE THREAD

**Issue by camelop** [OpenMined/PySyft#5891]
## Where?
https://github.com/OpenMined/PySyft/blob/866eae4a295adf9c202cf4f467c6e7ac50cf74d8/README.md#L27

## Who?
People who want to join the Slack

## What?
What you would like this documentation to accomplish: a working link to join the slack workspace

## Additional Context
The link in #5744 also doesn't help.

**Comment by rasswanth-s** [comment]
The link is updated as of this issue.
https://github.com/OpenMined/PySyft/issues/5744
