### ISSUE TITLE
Not able to install PySyft on Anaconda

### ISSUE THREAD

**Issue by anaghasimha** [OpenMined/PySyft#5909]
As mentioned in the openmined website, I tried to install PySyft using the following commands:
$ conda create -n pysyft python=3.9

$ conda activate pysyft

$ conda install jupyter notebook

$ pip install syft
I had also installed Microsoft Build Tools prior to making the installations

![Screenshot (7)](https://user-images.githubusercontent.com/80323298/129441485-8911a73c-3a10-4bd1-84b8-7fce2e307083.png)

System Information
 - OS: windows
 - OS Version: 20H2
 - Language Version:  Python 3.7
 - Package Manager Version: Anaconda3

**Comment by Boluwatifeh** [comment]
Hi there @anaghasimha are you trying to run tutorials from the private AI series? if yes, try following the guide [here](https://github.com/OpenMined/pysyft/tree/syft_0.5.0)  and if it's for pysyft 0.2.x you can reference this branch [here](https://github.com/OpenMined/PySyft/tree/syft_0.2.x)

**Comment by anaghasimha** [comment]
Hello. Yes, I am trying to install PySyft on my Anaconda prompt. Tried the
link that you have mentioned. Got the following error:
ERROR: Cannot install syft[udacity]==0.2.3, syft[udacity]==0.2.4,
syft[udacity]==0.2.5, syft[udacity]==0.2.6, syft[udacity]==0.2.7,
syft[udacity]==0.2.8, syft[udacity]==0.2.9, syft[udacity]==0.3.0 and
syft[udacity]==0.5.0 because these package versions have conflicting
dependencies.

The conflict is caused by:
    syft[udacity] 0.5.0 depends on torchvision<=0.9.1 and >=0.5
    syft[udacity] 0.3.0 depends on torch>=1.5
    syft[udacity] 0.2.9 depends on torch~=1.4.0
    syft[udacity] 0.2.8 depends on torch~=1.4.0
    syft[udacity] 0.2.7 depends on torch~=1.4.0
    syft[udacity] 0.2.6 depends on torchvision~=0.5.0
    syft[udacity] 0.2.5 depends on torch~=1.4.0
    syft[udacity] 0.2.4 depends on torch~=1.4.0
    syft[udacity] 0.2.3 depends on torch~=1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency
conflict

ERROR: ResolutionImpossible: for help visit
https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
