### ISSUE TITLE
duet.torchvision.datasets has no attribute ImageFolder

### ISSUE THREAD

**Issue by bardhan141** [OpenMined/PySyft#5913]
## Question
How to build train pointer in duet connection for customized Image datasets (other than MNIST or CIFAR10)? As there is no attribute ImageFolder in duet.torchvision.datasets.
## Further Information
I go through duet tutorials on MNIST datasets (https://github.com/OpenMined/PySyft/blob/dev/packages/syft/examples/duet/mnist/MNIST_Syft_Data_Scientist.ipynb) . There duet.torchvision.datasets.MNIST is used to create train pointer. But how to create a train pointer for customized datasets.

**Comment by danny0628** [comment]
I have the same problem.. Did you solved it ?

**Comment by madhavajay** [comment]
I updated 0.5 today and tested the latest version of torchvision, this doesnt add new functionality but just lets you import syft. However the fix was for Apple Silicon not other 0.5 bugs as 0.5 is now considered deprecated.
