### ISSUE TITLE
Tabular data example

### ISSUE THREAD

**Issue by Madelon-Molhoek** [OpenMined/PySyft#5934]
## Question
Is there an example code to use vertical Federated Learning for tabular data?

## Further Information
The example in this git is generated for images. I would appreciate an example how to deal with tabular data in PySysft. 
Which pieces of code do I need to alter to make the algorithm work for tabular data? Thank you!

## Example table
X_features = [0, 1, 2, 3 ,4, 5; 0, 1, 3, 6, 10, 15]
Y_target =    [0, 2, 4, 6, 8, 10]
ML model: Neural Network, 2 layers

**Comment by Githeo** [comment]
Hello,
Extending @Madelon-Molhoek question, it would be nice if in this example Alice has half of the features, Bob the other half + labels.

**Comment by madhavajay** [comment]
Unfortunately PyVertical does not support any newer versions of Syft. I believe the authors were interested but we haven't spoken since ICLR 2021.
