### ISSUE TITLE
Unable to share pointer after having successful connection

### ISSUE THREAD

**Issue by Pem14604** [OpenMined/PySyft#5962]
## Question
Unable to perform training on internal VM after having successful connection using Duet.

## Further Information
I am able to run end to end training process when I make connection b/w colab-colab or Azure VM-Colab but when it comes to the internal VM where we have some securities as well pysyft unable to share data pointer however connection established successfully using Duet. It seems like pysyft unable to send data using "data_pointer = X.send(duet, pointable=True),
target_pointer = y.send(duet, pointable=True)" after this when I try to run "data_ptr = duet.store[0]" it keeps runing.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by Boluwatifeh** [comment]
Hi there @Pem14604 i guess this is an event loop issue, did you add loopback=True argument when creating your duet object ? In context
```duet = sy.join_duet(loopback=True)``` 


Also adding a screenshot would go a long way
