### ISSUE TITLE
Where can I find the official PySyft tutorials?

### ISSUE THREAD

**Issue by iliasbibas** [OpenMined/PySyft#5969]
## Question
As the title says, where can I find the official PySyft tutorials?

## Further Information
After reading various posts regarding PySyft from https://blog.openmined.org/, I saw that many of them referred to a list of official tutorials that could be found in this repo (divided in parts and numbered). The link where they were previously available is: https://github.com/OpenMined/PySyft/tree/master/examples/tutorials. However this link is currently dead, and the structure of the repo seems to have changed. Are these tutorials still available and structured in a similar helpful manner? If so, where can I find them?

## Screenshots
The following is a screenshot that shows the tutorial files, as found on Wayback Machine:

![Screenshot from 2021-09-12 16-52-13](https://user-images.githubusercontent.com/12512633/132990295-959c09f5-8890-483d-9273-6bfc4761d7ac.png)

Sorry, if this is not the correct place to ask.

Thank you in advance!

**Comment by Boluwatifeh** [comment]
hi there @iliasbibas the screenshot you added above is specific to the pysyft 0.2.x version on the branch Pysyft/syft_0.2.x branch which can be found [here](https://github.com/OpenMined/PySyft/tree/PySyft/syft_0.2.x/examples/tutorials). 

those tutorials on the openmined blog are mostly based on the syft 0.2.x version which can be found in the link i shared. I hope this answers your question

**Comment by iliasbibas** [comment]
Thank you for your answer @Boluwatifeh ! 
Are there any tutorials for the latest stable version (if I am not mistaken it's 0.5.x)?

**Comment by Boluwatifeh** [comment]
Then current stable release is 0.5.0 and the private AI series on  https://courses.openmined.com uses this version to implement the course

**Comment by ManojTaleka** [comment]
I have one follow up question to this
There is a major change in PySyft 0.5.0 (current stable version) compared to 0.2.x series. So where I can understand about the changes done to PySyft modules?
Can I still use  PySyft 0.2.x for my coding or should I make a shift to 0.5.0?
What is the replacement for syft.frameworks module in 0.5.0?
It is quite confusing to understand the changes that has happened from 0.2.x series to 0.5.0. If any documentation is available to understand these changes then kindly help.

**Comment by ShowLongYoung** [comment]
> Then current stable release is 0.5.0 and the private AI series on https://courses.openmined.com uses this version to implement the course

However, this course website is down.

**Comment by riclazz** [comment]
> > Then current stable release is 0.5.0 and the private AI series on https://courses.openmined.com uses this version to implement the course
> 
> However, this course website is down.

This is the correct link:
https://courses.openmined.org/
