### ISSUE TITLE
 No module named 'syft.frameworks'

### ISSUE THREAD

**Issue by GH-Dong** [OpenMined/PySyft#5984]
## Question
** No module named 'syft.frameworks'**

## Further Information
When **from syft.frameworks.crypten.context import run_multiworkers**, I got the error **No module named 'syft.frameworks'**.
I have **syft==0.5.0, syft-proto==0.5.3**, and I did not find the context.py under crypten file.
I was trying to use GPU multiprocessing within the function under @run_multiworkers decorator.  Anyone help pls! Thx!!!
## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Ubuntu
 - OS Version: 16.04.4 LTS
 - Language Version: Python 3.8
 - Package Manager Version: Conda 4.10.1

**Comment by Rene36** [comment]
I guess `from syft.frameworks.crypten.context import run_multiworkers` might work with `syft==0.2.9`. However, the general structure changed significantly to version 0.5.0. I cannot help you with your question directly, but I suppose you search for your `run_multiworkers` in the latest [documentation](https://pysyft.readthedocs.io/en/latest/). which unfortunately is for v0.3.0.

The `from syft.` only gives for me core, lib, grid, federated, ast and proto. So for example `from syft.core.node.common.action.exception_action import UnknownPrivateException` works.
