### ISSUE TITLE
Create a changelog file

### ISSUE THREAD

**Issue by tchaton** [OpenMined/PySyft#5985]
## Feature Description

Dear PySyft Team, tracking progress on the repo is extremely hard between branches.
I would advice you to adopt a changelog to document all changes: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md

Best,
T.C

**Comment by danielorihuela** [comment]
This github action could be interesting https://github.com/marketplace/actions/changelog-ci
