### ISSUE TITLE
Error when executing syft-network

### ISSUE THREAD

**Issue by iliasbibas** [OpenMined/PySyft#5991]
## Description
I have created a conda environment (called `test_syft`) and installed PySyft 0.5.0 (using `pip install pip install syft==0.5.0`). After activating the conda environment, I execute `syft-network` to create a network using localhost in order to test the Duet functionality, without having to redirect traffic through the 3rd party duet AWS endpoint (e.g. http://ec2-18-218-7-180.us-east-2.compute.amazonaws.com:5000). 

I am getting the following error:

```
Traceback (most recent call last):
  File "...../anaconda3/envs/test_syft/bin/syft-network", line 5, in <module>
    from syft.grid.example_nodes.network import run
ImportError: cannot import name 'run' from 'syft.grid.example_nodes.network' (...../anaconda3/envs/test_syft/lib/python3.8/site-packages/syft/grid/example_nodes/network.py)
```

## How to Reproduce
1. Create a conda environment.
2. Install PySyft 0.5.0 using pip.
3. Execute in a terminal, in which the conda environment is activated, the command `syft-network`.
4. See error.

## Expected Behavior
I was expecting that a network in my localhost would be initiated that could be used by Duet. (Although I am not sure, because I didn't find any documentation describing the expected behaviour of the command).

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.8.11
 - Package Manager Version: conda 4.10.3, pip 21.0.1

Thank you in advance!

**Comment by Pem14604** [comment]
I have also tried this, same error am i getting.

**Comment by shashankc28** [comment]
hi , I am getting same error . tried with different python versions and os.
`ImportError: cannot import name 'run' from 'syft.grid.example_nodes.network' (....\anaconda3\envs\syft\lib\site-packages\syft\grid\example_nodes\network.py)   `

**Comment by Rene36** [comment]
With `syft==0.6.0a0` I get a similar error after running `syft-network` in a terminal with the respective virtual environment active:

```
Traceback (most recent call last):
  File "/home/karsten/Dokumente/venvs/fl60/bin/syft-network", line 5, in <module>
    from syft.grid.example_nodes.network import run
ModuleNotFoundError: No module named 'syft.grid.example_nodes'
```

## System Information
 - OS: Ubuntu
 - OS Version: 20.04.3 LTS
 - Language Version: Python 3.8.10
 - Package Manager Version: Virtual Environment, Pip 20.0.2

**Comment by Githeo** [comment]
Same error for me.
I use pyenv with a python version 3.7.4.
I'm not sure, but I think it happened when I updated the pyOpenSSL lib to the 22.0.0 version.

**Comment by xinxilwl** [comment]
If you launch version 0.5.0, the solution below may help:
```
import syft.grid.example_nodes.network as network
network.signaling_server()
```
