### ISSUE TITLE
Unable to run model-centric federated learning example

### ISSUE THREAD

**Issue by sikhapentyala** [OpenMined/PySyft#6011]
## Description
On running the notebook examples/federated-learning/model-centric/mcfl_create_plan.ipynb, the cell with response = grid.host_federated_training(...) gives BrokenPipeError: [Errno 32] Broken pipe. As per notebook on executing Step 4, "WebSocket request accepted, switching protocols" but is closed immediately, "Closed WebSocket".

## How to Reproduce
1. Installed pysyft (and cloned 0.5.0 version)
2. Cloned default branch of pygrid
3. Ran notebook - notebook examples/federated-learning/model-centric/mcfl_create_plan.ipynb

## Expected Behavior
Expected to first run mcfl_create_plan.ipynb and then mcfl_execute_plan.ipynb without errors 

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.9.7
 - Package Manager Version: Conda 4.10.3
 - Browser (if applicable): Chrome
 - Browser Version (if applicable): 93.0.4577.82

## Additional Context
I am new to federated learning and experimenting with Syft, where I can have a few nodes and a central server in a subnet to perform federated learning.

**Comment by sarthak-chakraborty** [comment]
I am experiencing the same issue. Has there been any solution to this?

**Comment by chulahlou** [comment]
Has this notebook/the mnist training demo been removed entirely? Is it no longer supported?

**Comment by madhavajay** [comment]
0.5 is no longer supported.
