### ISSUE TITLE
Technical Queries regarding PySyft

### ISSUE THREAD

**Issue by ManojTaleka** [OpenMined/PySyft#6012]
## Question
**Technical Queries regarding  PySyft**

## Further Information
There is a major change in PySyft 0.5.0 (current stable version) compared to 0.2.x series. 
(i) From where I can understand about the changes done to PySyft modules?
(ii) Can I still use PySyft 0.2.x for my coding or should I make a shift to 0.5.0?
(iii) What is the replacement for syft.frameworks module in 0.5.0?

It is quite confusing to understand the changes that has happened from 0.2.x series to 0.5.0. If any documentation is available to understand these changes then kindly help.

**Comment by Rene36** [comment]
From what I've read and heard is v0.2.x not supported anymore and it went through a huge overhaul resulting in v0.5.0. Therefore, I suggest you move forward as well to the newest version. Even though it probably means that most of your code base is waste now.
