### ISSUE TITLE
AttributeError: 'TensorPointer' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by Salahalib** [OpenMined/PySyft#6047]
Pysyft 0.5.0

I got this error when trying to train an LSTM autoencoder, it works fine locally. But when I try to do a FL training I got this error:
File "C:\Users\ABC\anaconda3\envs\pysyft\lib\site-packages\torch\nn\modules\rnn.py", line 649, in forward

    dtype=input.dtype, device=input.device)

AttributeError: 'TensorPointer' object has no attribute 'dtype'.

The error is triggered by the forward function :
def forward(self, x):
        x1 = x.reshape((1, self.seq_len, self.n_features))
        x2, (_, _) = self.rnn1(x1)   <---------------------
        x3, (hidden_n, _) = self.rnn2(x2)

**Comment by RoyRin** [comment]
Please provide a small script to recreate the issue, but I suspect you are either not sending the model to the device
(`model.send(device)`) or not pulling the data from device to the central server (`x= x.get()`).

However, this is a guess, and if you could provide more information, I could provide a better answer.
