### ISSUE TITLE
Beaver triples - generate multiple instances

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#6054]
## Feature Description
For the moment if we want a beaver triple to be able to do a multiplication between MPC tensor `a` and `b` we generate and send only one cryptographic primitive.
This means that if we want to do 32 multiplications between `a` and `b` we will need to generate 32 primitives and do 32 sends.

We want to do this only by calling the primitive generator once and the send once -- probably this will require to add/modify a new parameter (`nr_instances`) for the generate/send function.

## Is your feature request related to a problem?
- Be able to do multiplication/private compare/convolution faster.

## Additional Context
- For questions/more information ask George Muraru or Rasswanth.

**Comment by rasswanth-s** [comment]
Feature Integrated. https://github.com/OpenMined/PySyft/pull/6032
