### ISSUE TITLE
Need credentials of PyGrid admin UI 

### ISSUE THREAD

**Issue by 786mariamumtaz** [OpenMined/PySyft#6235]
## Question
**Describe your question in ONE SENTENCE.**

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

## Additional Context
[dp output.docx](https://github.com/OpenMined/PySyft/files/7740406/dp.output.docx)
![image](https://user-images.githubusercontent.com/92711997/146666314-9c911a26-8f81-489d-9841-c87e6133ce8b.png)

**Comment by madhavajay** [comment]
@786mariamumtaz The default credentials are:
email: info@openmined.org
pass: changethis
