### ISSUE TITLE
PySyft + Opacus: Federated Learning With Differential Privacy

### ISSUE THREAD

**Issue by PoojaPrasd** [OpenMined/PySyft#6241]
## Question
Extending Federated Learning tutorial code to implement differential privacy using opacus privacyengine

## Further Information
I have followed Federated Learning tutorial that uses Duet and following model for iris dataset
class SyNet(sy.Module):
    def __init__(self, torch_ref):
        super(SyNet, self).__init__(torch_ref=torch_ref)
        self.layer1 = self.torch_ref.nn.Linear(in_dim, 20) 
        self.layer2 = self.torch_ref.nn.Linear(20,30) 
        self.out = self.torch_ref.nn.Linear(30, out_dim) 
    
    def forward(self,x):
        x = self.torch_ref.nn.functional.relu(self.layer1(x))
        x = self.torch_ref.nn.functional.relu(self.layer2(x))
        output = self.torch_ref.nn.functional.log_softmax(self.out(x), dim=1)
        return output

I want to add differential privacy and tried to followed the steps 
https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/
by adding 
workers = [duet1, duet2]

models, dataloaders, optimizers, privacy_engines = [], [], [], []
for worker in workers:
    model = local_model
    #optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    #optim1 = remote_torch1.optim.Adam(params = params, lr = 0.01) 
    model.send(worker)
    dataset = worker.store[0]
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=128, shuffle=True, drop_last=True)
    privacy_engine = PrivacyEngine()
    model, optimizer, data_loader = privacy_engine.make_private(
        module=model,
        optimizer=optimizer,
        data_loader=dataloader,
        noise_multiplier=1.1,
        max_grad_norm=1.0,
    )
    models.append(model)
    dataloaders.append(dataloader)
    optimizers.append(optimizer)
    privacy_engines.append(privacy_engine)

but getting below error-  AttributeError: 'SyNet' object has no attribute 'named_modules'

**Comment by madhavajay** [comment]
We have our own AutoDP system in 0.7 now and Opacus and 0.5 are no longer supported.
