### ISSUE TITLE
Training of a CNN does not work due to _object2proto missing

### ISSUE THREAD

**Issue by Rene36** [OpenMined/PySyft#6260]
## Question
I would like to run a CNN training with the MNIST data set with a VirtualMachine and over the network. Do I have to use something else than a ModulePointer or is this functionality not yet included?

To reproduce run the following:

```
import syft as sy
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(28 * 28, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 64)
        self.fc4 = nn.Linear(64, 10) 

    def forward(self, x):
        # and not limit to binary outputs.
        x = nn.functional.relu(self.fc1(x))
        x = nn.functional.relu(self.fc2(x))
        x = nn.functional.relu(self.fc3(x))
        x = self.fc4(x)
        return torch.nn.functional.log_softmax(x, dim=1)


vm = sy.VirtualMachine(name="pi07")
vm_client = vm.get_client()
model = Net()
model_ptr = model.send(vm_client, pointable=True)
```

## Further Information
The above code gives the error `AttributeError: 'Net' object has no attribute '_object2proto'`.
To avoid this I tried two things:

1. Inherit the `_object2proto` from `from syft.core.common.message import AbstractMessage`
2.  Inherit the `_object2proto` from `from syft.core.pointer.pointer import Pointer`

The Net class for the 1. approach changes to the following and it gives the error `TypeError: 'ModulePointer' object is not subscriptable`:
```
from syft.core.common.message import AbstractMessage  

class Net(AbstractMessage, nn.Module):
    def __init__(self):
        super().__init__()
        # One image has 28pixels * 28pixels
        self.fc1 = nn.Linear(28 * 28, 64)
...
```

The Net class for the 2. approach changes to the following and it gives the error `TypeError: 'ModulePointer' object is not subscriptable` in line 1204 in `torch/nn/modules/module.py`:
```
from syft.core.pointer.pointer import Pointer  

class Net(Pointer, nn.Module):
    def __init__(self, client):
        super().__init__(client=client)
        # One image has 28pixels * 28pixels
        self.fc1 = nn.Linear(28 * 28, 64)
...

vm = sy.VirtualMachine(name="pi07")
vm_client = vm.get_client()
model = Net(vm_client)
model_ptr = model.send(vm_client, pointable=True)
```

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: PySyft 0.6.0, Python 3.8.10, torch 1.10.0

**Comment by Rene36** [comment]
I dig a bit deeper into the source code and I am getting more confused, but maybe these information might help others:

When importing syft, the ` lib/__init__.py` is called in which runs `lib_ast = create_lib_ast(None)` all the way at the end. I haven't figured this part out yet, but for each data type three functions are assigned (send, tag, describe).

Checkout out `util.py`, where you can find the obj, name and attr (send, tag, describe) I printed below. The attr/functions are defined in `ast/klaas.py`. For example,
```
<class 'syft.lib.python.Bytes'> send <function Class.create_send_method.<locals>.send at 0x7fb8287b7280>
<class 'syft.lib.python.Bytes'> tag <function Class.create_storable_object_attr_convenience_methods.<locals>.tag at 0x7fb8287b7310>
<class 'syft.lib.python.Bytes'> describe <function Class.create_storable_object_attr_convenience_methods.<locals>.describe at 0x7fb8287b73a0>
```

So, this approach is also done for all kinds of torch data types.
```
<class 'torch.nn.parameter.Parameter'> send <function Class.create_send_method.<locals>.send at 0x7fb8286341f0>
<class 'torch.nn.parameter.Parameter'> tag <function Class.create_storable_object_attr_convenience_methods.<locals>.tag at 0x7fb8285b9820>
<class 'torch.nn.parameter.Parameter'> describe <function Class.create_storable_object_attr_convenience_methods.<locals>.describe at 0x7fb8285b98b0>
<class 'torch.nn.modules.module.Module'> send <function Class.create_send_method.<locals>.send at 0x7fb8285b9940>
<class 'torch.nn.modules.module.Module'> tag <function Class.create_storable_object_attr_convenience_methods.<locals>.tag at 0x7fb8285bc040>
<class 'torch.nn.modules.module.Module'> describe <function Class.create_storable_object_attr_convenience_methods.<locals>.describe at 0x7fb8285bc0d0>
<class 'torch.nn.modules.conv.Conv2d'> send <function Class.create_send_method.<locals>.send at 0x7fb8285bc160>
<class 'torch.nn.modules.conv.Conv2d'> tag <function Class.create_storable_object_attr_convenience_methods.<locals>.tag at 0x7fb8285bc700>
<class 'torch.nn.modules.conv.Conv2d'> describe <function Class.create_storable_object_attr_convenience_methods.<locals>.describe at 0x7fb8285bc790>
<class 'torch.nn.modules.dropout.Dropout2d'> send <function Class.create_send_method.<locals>.send at 0x7fb8285bc820>
<class 'torch.nn.modules.dropout.Dropout2d'> tag <function Class.create_storable_object_attr_convenience_methods.<locals>.tag at 0x7fb8285bcdc0>
<class 'torch.nn.modules.dropout.Dropout2d'> describe <function Class.create_storable_object_attr_convenience_methods.<locals>.describe at 0x7fb8285bce50>
```

**Question: How do I use them for my CNN which I want to send to a VirtualMachine and eventually to a remote host?**

**Comment by madhavajay** [comment]
Not all object types are serializable. In 0.5 we have a local proxy object called SyNet which holds the functionality locally but refers to remote data Module pointers. Since 0.7 includes our own Tensor type this is no longer required.
