### ISSUE TITLE
Examples link is dead

### ISSUE THREAD

**Issue by Murat-U-Saglam** [OpenMined/PySyft#6276]
## Description
There is no documentation for this project which is fine, however, the examples link is dead and getting started with this library is a nightmare. 

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
I am a student who intends on utilising federation learning.

**Comment by meetgandhi123** [comment]
Is there any improvement with the documentation part? I am a student and want to use the library for projects but there is not way of getting started. 

If there is no documentation can someone please suggest any other library to do a Federated Learning-based project.
