### ISSUE TITLE
Error when Using the Docker image

### ISSUE THREAD

**Issue by daishu-li** [OpenMined/PySyft#6280]
## Question
**When I copy the url: 'http://172.17.0.2:8888/?token=f3fceb0fe010e917203171496ff42cc53a03ff6e5ffa92f2 ' shown in the following picture into the local browser,  I can't open it!**
## Screenshots
![image](https://user-images.githubusercontent.com/74223978/151662687-b217b2ac-0179-4cad-b8ae-ead0fd6ecc87.png)

**Comment by madhavajay** [comment]
That container is deprecated and has been removed.
If you want to use a jupyter environment with syft easily do this:
```
$ git clone https://github.com/OpenMined/PySyft.git
$ cd PySyft
$ pip install tox
$ tox -e syft.jupyter
```
