### ISSUE TITLE
Not able to start the duet connection

### ISSUE THREAD

**Issue by Githeo** [OpenMined/PySyft#6286]
## Description
Starting from a fresh installation of pysyft with pyenv, the very first time a data owner can launch a duet connection with
`import syft as sy;
duet = sy.duet(loopback=True)`

but the next times, it stucks in the following:

`🎤  🎸  ♪♪♪ Starting Duet ♫♫♫  🎻  🎹

♫♫♫ > DISCLAIMER: Duet is an experimental feature currently in beta.
♫♫♫ > Use at your own risk.

    > ❤️ Love Duet? Please consider supporting our community!
    > [https://github.com/sponsors/OpenMined]()`

without going further. Obviously, a data scientist cannot establish any connection with the data owner with `duet = sy.join_duet(loopback=True)`

After the cell is running for almost 4 minutes, this is the error popping up:

```
Exception                                 Traceback (most recent call last)
/var/folders/f5/1fpy821d4cv783czwrb2m2fr0000gp/T/ipykernel_6819/4282418770.py in <module>
      1 import syft as sy
----> 2 duet = sy.duet(loopback=True)

~/.pyenv/versions/3.7.4/envs/openmined-pysyft/lib/python3.7/site-packages/syft/grid/duet/__init__.py in duet(target_id, logging, network_url, loopback, db_path)
    163     else:
    164         return launch_duet(
--> 165             logging=logging, network_url=network_url, loopback=loopback, db_path=db_path
    166         )
    167 

~/.pyenv/versions/3.7.4/envs/openmined-pysyft/lib/python3.7/site-packages/syft/grid/duet/__init__.py in launch_duet(logging, network_url, loopback, credential_exchanger, db_path)
    198 
    199     if not network_url:
--> 200         network_url = get_available_network()
    201     info("♫♫♫ > Punching through firewall to OpenGrid Network Node at:", print=True)
    202     info("♫♫♫ > " + str(network_url), print=True)

~/.pyenv/versions/3.7.4/envs/openmined-pysyft/lib/python3.7/site-packages/syft/grid/duet/__init__.py in get_available_network()
     60             error(f"Failed request addr: {e}")
     61             continue
---> 62     traceback_and_raise(Exception("Couldn't find any available network."))
     63 
     64 

~/.pyenv/versions/3.7.4/envs/openmined-pysyft/lib/python3.7/site-packages/syft/logger.py in traceback_and_raise(e, verbose)
     59     if not issubclass(type(e), Exception):
     60         e = Exception(e)
---> 61     raise e
     62 
     63 

Exception: Couldn't find any available network.
```

## How to Reproduce
1. Install pysyft==0.5.0 in pyenv
2. open a new notebook in vscode and run a cell with `import syft as sy; duet = sy.duet(loopback=True)`
3. restart the kernel and repeat step 2
4. duet is not totally initiated

## Expected Behavior
It should listen for connection and connect when a data scientist joins the duet.

## System Information
 - OS: MacOS Big Sur 
 - OS Version: 11.6
 - Language Version: Python 3.7.4
 - Package Manager Version: pyenv 1.2.21
 - PySyft Version: 0.5.0
 - DevTool: Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0 

## Additional Context
Uninstalling and reinstalling the new virtualenv the behaviour is the same.

**Comment by Githeo** [comment]
Unfortunately not. It works running the same code on colab though (just removing loopback=True).

**Comment by pastyy** [comment]
Thanks! Actually, I tried one day later the same code and the error was gone lol...

**Comment by madhavajay** [comment]
We had some small issue and the Signalling server was rebooted and it is now working again. There is also a maintenance release of syft 0.5 which allows newer Torch which should fix issues with Apple Silicon.
