### ISSUE TITLE
Hagrid launch issue on GCP VM(Debian)

### ISSUE THREAD

**Issue by Crazynovatech** [OpenMined/PySyft#6287]
Hi, Hagrid is installed successfully. But while launching the domain node with hagrid getting error as follows. 

Updating HAGrid from branch: 0.6.0
docker: 'compose' is not a docker command.
See 'docker --help'
This may be a linux machine, either that or docker compose isn't s
Result:

You are running an old version of docker, possibly on Linux. You need to install v2.
At the time of writing this, if you are on linux you need to run the following:

DOCKER_COMPOSE_VERSION=v2.1.1
curl -sSL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64      -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose

ALERT: you may need to run the following command to make sure you can run without sudo.

echo $USER              //(should return your username)
sudo usermod -aG docker $USER

... now LOG ALL THE WAY OUT!!!

...and then you should be good to go. You can check your installation by running:

docker compose version

## System Information
 - OS: Debian GNU/Linux 10 (buster)
 - OS Version: 10
 - Language Version: Python 3.9.7
 - Package Manager Version: conda 4.10.1

## Additional Context
I have installed Pysyft and Hagrid on a GCP VM(Debian). Docker is up and running. I have installed docker-compose too following the instructions given. **docker-compose version** is working fine giving the result as "Docker Compose version v2.1.1".

**Comment by madhavajay** [comment]
@Crazynovatech HAGrid currently only supports Ubuntu 20.04, the only difference I can imagine is that the docker version or docker compose install isn't functioning properly. `docker-compose` is deprecated and should be removed, all of the new docker compose versions act as a plugin to docker engine. This should give you an indication of what ansible is doing:
https://github.com/OpenMined/PySyft/blob/dev/packages/grid/ansible/roles/node/tasks/docker.yml
