### ISSUE TITLE
Error from the tutorials 1

### ISSUE THREAD

**Issue by VIGNESHinZONE** [OpenMined/PySyft#6291]
In first tutorial, the `sy.launch_duet` is giving a connection TimeoutError. Could you please update with the correct link?

My code- 
```
duet = sy.launch_duet(network_url="http://ec2-18-216-8-163.us-east-2.compute.amazonaws.com:5000/")
```

notebook link - [here](https://github.com/OpenMined/courses/blob/foundations-of-private-computation/federated-learning/duet_basics/Duet_Basics_Data_Owner.ipynb)

Error Message-
```
ConnectionError: HTTPConnectionPool(host='ec2-18-216-8-163.us-east-2.compute.amazonaws.com', port=5000): Max retries exceeded with url: //metadata (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04988c9b20>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

I have made opened an issue here as well - [here](https://github.com/OpenMined/courses/issues/402)

**Comment by xinxilwl** [comment]
Building a local Duet server can help you. #5991

**Comment by madhavajay** [comment]
@VIGNESHinZONE it was fixed recently: https://github.com/OpenMined/PySyft/issues/6286
