### ISSUE TITLE
[CRITICAL][logger]][29360] UnknownPrivateException has been triggered at the point ptr.get()

### ISSUE THREAD

**Issue by Crazynovatech** [OpenMined/PySyft#6300]
Hi, Getting below error
[CRITICAL][logger]][29360] UnknownPrivateException has been triggered at the point ptr.get()

Getting this issue only when we append multiple field values into the tensor.

 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.9
 - Package Manager Version: conda 4.11.0

Whether the budget will create any issues? Attached the  screenshot.
![image](https://user-images.githubusercontent.com/73330091/154220319-ee38f116-1ea4-4170-8ab9-020dd7e63b9f.png)

**Comment by madhavajay** [comment]
@Crazynovatech are you able to provide more example code and the version of Grid / Syft you are using?

**Comment by linhnt31** [comment]
Hi @madhavajay and @Crazynovatech, I have faced the same issue when I try to run this example [DEPLOYING A SINGLE DOMAIN NODE](https://blog.openmined.org/remote-data-science-part-3-deploying-a-single-domain-node/) at the final step to calculate *the total number of Covid cases*.

**Comment by linhnt31** [comment]
```python
# Calculate the total number of COVID cases 
results = [dataset[f'{i}'] for i in range(10)]
# print(results)

from time import sleep
total_cases = 0

for result in results:
    ptr = result.publish()
#     print(ptr.get())
    sleep(1)
    total_cases += ptr.get()

print('The total number of COVID19 cases are: {}'.format(total_cases))
```

**Comment by hadjipantelis** [comment]
I am trying to follow the tutorial in `L2C6 - Remote Data Science` and I get the same error.

**Comment by ricardocarvalhods** [comment]
Hello, I was having the exact same error in L2C6, and it was solved by restarting the celeryworker container:
- In Docker, go to the "Container / Apps" menu on the upper left
- Expand "local_node"
- In "local_node-celeryworker-1" on the bottom right, click on restart

**See image below.**

![image](https://user-images.githubusercontent.com/7207015/188537305-1bef612c-3ab4-4d1a-b79e-37cc5b7a8776.png)

After doing this, the code from L2C6 worked without changing anything.

**Comment by madhavajay** [comment]
Yes as per @hadjipantelis suggestion 0.6 is a bit dated now we have the `course3` code here which is compatible with `dev` / `0.7.0 betas`:
https://github.com/OpenMined/courses/tree/introduction-to-remote-data-science-dev
