### ISSUE TITLE
Storage of uploaded data

### ISSUE THREAD

**Issue by Crazynovatech** [OpenMined/PySyft#6303]
Hi, Is the data uploaded to the domain(url port activated by Hagrid) moved and stored on the server where Hagrid is installed? If means what if the format of the stored data and can we find the path of the stored data?

**Comment by madhavajay** [comment]
@Crazynovatech HAGrid can deploy to local docker or a remote VM so it depends on where you deployed it. Where ever you did, there will be a redis store and a seaweed blob store and any data sent will go into either of those depending on what type or size it is.

In local dev mode you can run:
```
$ hagrid launch domain to docker:8081 --dev
```

Then you can use the dev tools to see the different data stores.
```
$ ./scripts/dev_tools.sh 
```
