### ISSUE TITLE
Wrong Test Command?

### ISSUE THREAD

**Issue by Sihan-Song** [OpenMined/PySyft#6316]
## Question
**Describe your question in ONE SENTENCE.**
When I ran "pytest -m fast -n auto",I got an  error，which is as follows.
## Further Information
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: D:\ssh\Research\Projects\gsoc\PySyft\packages\syft\setup.cfg
  rootdir: D:\ssh\Research\Projects\gsoc\PySyft\packages\syft

What should I do to solve this problem?

## System Information
 - OS: windows

**Comment by madhavajay** [comment]
@Sihan-Song you need to run `pip install -e .[dev]` to make sure that the pytest packages also get installed.

You can see how all of this is done in our `tox` tasks or github CI.
We run all our main tests on Windows on every PR and nightlies.

What are you trying to do?

**Comment by madhavajay** [comment]
I will close this for now.
