### ISSUE TITLE
ERROR: 'network_mode' and 'networks' cannot be combined

### ISSUE THREAD

**Issue by MissiontoMars** [OpenMined/PySyft#6328]
## Description
When i try to start PyGrid stack following the tutorial instructions https://github.com/OpenMined/PySyft/blob/dev/packages/grid/README.md, I got the error when executing docker-compose up:

`ERROR: 'network_mode' and 'networks' cannot be combined`

My OS environment:  macOS Big Sur 11.4

## System Information
 - OS: macOS Big Sur
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
@MissiontoMars My guess is that your docker version is out of date.
Please install the latest version of `docker desktop` and enable `docker compose v2` in the settings.
