### ISSUE TITLE
Integration Test Prototype

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#633]
### User Story
As a developer of PySyft functionality that links to the Unity backend, I want the ability to create Python integration tests which can evaluate whether the client is operating with correct behavior.

### Acceptance Criteria
- [ ] An example integration test evaluating (https://github.com/OpenMined/PySyft/pull/631)

**Comment by alexanderConstantinescu** [comment]
I wouldn't mind picking this issue up as I am imagining that it can be done using separate Docker containers with communicating services. 

How are the tests being executed today / how do you imagine it should be in the future? Integrated into an automatic build and release cycle ? Or only ad hoc execution by each contributor?

**Comment by iamtrask** [comment]
@alexanderConstantinescu and @bendecoste  - do we feel we can close this now?

**Comment by bendecoste** [comment]
#144 isn't merged yet but i'm into it

**Comment by bendecoste** [comment]
err .. it is merged I was thinking of the CI one .. but yeah i'm down to close

**Comment by alexanderConstantinescu** [comment]
I guess you can close this, looking at what has been mentioned/referenced here.
