### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by AmitDavidi** [OpenMined/PySyft#6330]
## Question
I want to get started with PySyft but can't find updated tutorials \ examples.

## Further Information
I want to know how to send tensors and using pysyft in my existing pytorch networks but I Can't find examples. and the ones I did find are old which uses stuff that doesn't exist like x_ptr = x.send(bob) 
or hook = sy.TorchHook(torch)

Furthermore, can I run pysyft with cuDNN ?

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by madhavajay** [comment]
@AmitDavidi we are working on our docs as we speak, however in the mean time the best resource is https://courses.openmined.org/
