### ISSUE TITLE
Saving Tensors / Models to Disk on the Websocket Server Worker

### ISSUE THREAD

**Issue by bentay85** [OpenMined/PySyft#6338]
## Question
My objective is to be able to save tensors / models to disk on the Websocket Server Worker

## Further Information
I am running the following code on the server. When I send tensors from the Websocket client, I do not see them listed by the list_objects() function. Is there a way I can access and manually save the tensors / models to disk from the Websocket Server side?

    import syft as sy
    import torch
    import multiprocessing as mp
    from syft.workers.websocket_server import WebsocketServerWorker
    
    def start_server(worker):
        worker.start()
    
    if __name__ == '__main__':
        hook = sy.TorchHook(torch)
    
        local_worker = WebsocketServerWorker(
                                    host="0.0.0.0",
                                    hook=hook,
                                    id=0,
                                    port=yyyy)
        
        p1 = mp.Process(target=start_server, args=(local_worker,)).start()
        
        while True:
            #Is there a way to see the objects that are sent from the client?
            print(local_worker.list_objects())
            time.sleep(3)

I am running the following code on the Websocket Client. Is there a remote version of the torch.save() method?

    import torch
    import syft
    from syft.workers.websocket_client import WebsocketClientWorker
    
    hook = syft.TorchHook(torch)
    
    remote_worker = WebsocketClientWorker(
                                host='x.x.x.x',
                                hook=hook,
                                id=0,
                                port=yyyy,
                                log_msgs=True,
                                verbose=True)
    
    a = torch.tensor([5])
    a = a.send(remote_worker)
    #Is there a way to save a to worker's disk? 
    torch.save(public_key,"test_save.pt")

## Screenshots
Not Applicable. 

## System Information
 - OS: Windows
 - OS Version: 11
 - Language Version: Python 3.7
 - Package Manager Version: Conda 4.11.0
 - Syft Version: 0.2.8

## Additional Context
Nil.

**Comment by madhavajay** [comment]
@bentay85 theres nothing stopping you from modifying the worker code to do this, however we are about to release 0.7.0 and no longer support <0.5 including 0.2.
