### ISSUE TITLE
openmined/grid-node docker image missing

### ISSUE THREAD

**Issue by MissiontoMars** [OpenMined/PySyft#6340]
## Question
`$ docker pull openmined/grid-node:production
Error response from daemon: pull access denied for openmined/grid-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by MissiontoMars** [comment]
Is this project not maintained now?

**Comment by madhavajay** [comment]
@MissiontoMars these versions are no longer supported. Please checkout `dev` and our `0.7.0` release.

We will be updating our docs shortly but you can get started with:
```
$ pip install hagrid
$ hagrid launch domain to docker:8081 --tag=latest
```
