### ISSUE TITLE
ConnectionClosedOK: code = 1000 (OK), no reason

### ISSUE THREAD

**Issue by yigedage** [OpenMined/PySyft#6349]
## Description
A clear and concise description of the bug.
In Asynchronous learning - federated - learning - on - MNIST, changed the run_websocket_client. Py the model lead to the above problems, the complete error as follows  
ConnectionClosedOK                        Traceback (most recent call last)
<ipython-input-12-edf38bb6dbe9> in async-def-wrapper()
     19         ]
     20     )
---> 21     models = {}
     22     loss_values = {}
     23 

D:\Federated Learning\PySyft\examples\tutorials\advanced\websockets-example-MNIST-parallel\run_websocket_client.py in fit_model_on_worker(worker, traced_model, batch_size, curr_round, max_nr_batches, lr)
    170     )
    171     train_config.send(worker)
--> 172     loss = await worker.async_fit(dataset_key="mnist", return_ids=[0])
    173     model = train_config.model_ptr.get().obj
    174     return worker.id, model, loss

D:\anaconda\lib\syft\workers\websocket_client.py in async_fit(self, dataset_key, return_ids)
    156             serialized_message = sy.serde.serialize(message)
    157             await websocket.send(str(binascii.hexlify(serialized_message)))
--> 158             await websocket.recv()  # returned value will be None, so don't care
    159 
    160         # Reopen the standard connection

D:\anaconda\lib\websockets\protocol.py in recv(self)
    507                     # Wait until the connection is closed to raise
    508                     # ConnectionClosed with the correct code and reason.
--> 509                     await self.ensure_open()
    510 
    511         # Pop a message from the queue.

D:\anaconda\lib\websockets\protocol.py in ensure_open(self)
    810             # case self.close_connection_task will complete even faster.
    811             await asyncio.shield(self.close_connection_task)
--> 812             raise self.connection_closed_exc()
    813 
    814         # Control may only reach this point in buggy third-party subclasses.

ConnectionClosedOK: code = 1000 (OK), no reason

**Comment by madhavajay** [comment]
@yigedage We no longer support these old websocket versions of Grid. I believe the libraries have changed causing issues with how these old versions run now. I can highly recommend you checkout our latest version with:
```
$ pip install hagrid
$ hagrid launch domain to docker:8081 --tag=latest
$ pip install --pre syft
```

Then checkout some of our integration tests or notebooks for examples on how to use. More docs coming shortly.
