### ISSUE TITLE
How to implement the client_protocols in  model-centric federated learning example  with syft0.5.0 ?  Such as secure aggregation protocols?  

### ISSUE THREAD

**Issue by Whiplashcandobear** [OpenMined/PySyft#6354]
## Question
How to implement the client_protocols in  model-centric federated learning（MCFL） example  with syft 0.5.0 release?  Such as secure aggregation protocols?  

## Further Information
the exemple notebook in syft_0.5.0/packages/syft/examples/federated-learning/model-centric only implements the client plan and does not show how to implement the client protocol.Beyond this example,I couldn't find any more reference implementation code in the repository for model-centric federation learning or instructions on how to write client-side protocols in MCFL.I want to implement client-side secure aggregation protocols in model-centric federated learning. How do I write the code?  How to implement model-centric federated learning and secure aggregation protocol for multi-machine communication in real scenarios on multiple client devices?  Are there tutorials, documentation, or implementation examples from anyone else to refer to?

**Comment by Whiplashcandobear** [comment]
@vvmnnnkv @madhavajay

**Comment by madhavajay** [comment]
Hi @Whiplashcandobear we are no longer supporting 0.5. We have Automatic DP and SMPC built into `0.7.0` which is about to be released from `dev`.

I can highly recommend you checkout our latest version with:
```
$ pip install hagrid
$ hagrid launch domain to docker:8081 --tag=latest
$ pip install --pre syft
```

Then checkout some of our integration tests or notebooks for examples on how to use. More docs coming shortly.
