### ISSUE TITLE
Access Duet Client Id in 0.5.0

### ISSUE THREAD

**Issue by adamFinastra** [OpenMined/PySyft#6361]
## Question
**How can you access the Client ID from a duet object from syft.core.node.domain.client.DomainClient?**

## Further Information
In Jupyter, once you launch a duet session between you and your partner you are presented with a Client ID to share. Is the Client ID stored in the duet object? 

`duet = sy.launch_duet()`

i.e. is there a way to access say, duet.client_id and not just obtain it from a print statement in a jupyter cell? 

## System Information
 - OS: MacOS Big Sur
 - OS Version: 11.6.1
 - Language Version: Python 3.9
 - Pysyft version: 0.5.0

**Comment by madhavajay** [comment]
@adamFinastra any reason you want the client ID after the fact? We no longer support 0.5 but we did have a custom class you could implement to control the connection flow.

Checkout the `DuetCredentialExchanger`:

https://github.com/OpenMined/PySyft/blob/f07116ffc4bd6ed6f262ddacf9e77ece988ddad0/packages/syft/src/syft/grid/duet/exchange_ids.py#L1
