### ISSUE TITLE
no definition of useDomainStatus from '@/lib/data'

### ISSUE THREAD

**Issue by mathews** [OpenMined/PySyft#6373]
## Description
no definition of useDomainStatus from '@/lib/data'
But there four references of useDomainStatus  in frontend code, so build the frontend will throw errors. 
I wonder where the definition of  useDomainStatus 
the version I used is v0.6.0 and master.

## How to Reproduce
2. Click on '...'
3. Scroll down to '...'

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
@mathews this could be fixed in `dev`, I will see what @tcp says.

**Comment by madhavajay** [comment]
@mathews any update on this?
