### ISSUE TITLE
module 'sympc' has no attribute 'merge'

### ISSUE THREAD

**Issue by yuanbw** [OpenMined/PySyft#6389]
## Description
Hi, Openmined experts,
Per to https://github.com/OpenMined/PySyft/blob/0.6.0/notebooks/trade_demo/Part%204%20-%20Perform%20JOIN%20(backed%20by%20SMPC).ipynb, 

## How to Reproduce
Run the code below,
import sympc
merged_dataset_ptr = sympc.merge(
    left=ca_filtered_dataset_ptr,
    right=it_filtered_dataset_ptr,
    on="Commodity Code",
    how="inner",
    suffixes=("_ca", "_it"),
)

The following error will occurs,
AttributeError: module 'sympc' has no attribute 'merge'

I check the sourcecode from  https://github.com/OpenMined/SyMPC,  and  no method 'merge' was found. So is there anything missing from "Part 4 - Perform JOIN (backed by SMPC).ipynb" ? @iamtrask  Thanks!

**Comment by madhavajay** [comment]
@yuanbw 0.6 and 0.7 (dev) do not use SyMPC, instead they use a built in SMPC implementation from the same authors @gmuraru and @rasswanth-s.

@rasswanth-s what is the equivalent of `merge` in 0.7?

**Comment by rasswanth-s** [comment]
Hi @yuanbw,
The Old Notebook was one of our Nice to have features, 

It was not fully completed, There are some example smpc examples in https://github.com/OpenMined/PySyft/tree/dev/notebooks/smpc/Training%20Demo
For the initial Training,

To work with the example you would need to launch Domain Nodes through **hagrid**,
Our current syft documentation would help you in the same 
https://openmined.github.io/PySyft/

Creating new examples notebooks for our current architecture is at the top of my `TODO` list, within one or two week , I will create good Starting notebooks for SMPC.

I am closing this issue, as the feature was not implement.
Feel to reach out to me for any questions on OM slack,
Joining link: slack.openmined.org
My handle: @Rasswanth
