### ISSUE TITLE
Show a demo showing that either CNNs or Transformers do work

### ISSUE THREAD

**Issue by kovkev** [OpenMined/PySyft#6400]
## Where?
Somewhere in the README.md or the splash pages of the website.

## Who?
People who just stumbled upon OpenMined

## What?
I think there should be a small demo of what OpenMined can do. The "Is it a hotdog" for image classifiers. Or "What is an animal with four feet that meows at home" -> "cat" for NLP. 

## Additional Context
I am excited to learn more about homomorphic encryption, but after looking at a few pages, I am not sure what is Achievable! It would be nice to know that - yes, machine learning on homomorphic encrypted data does work!

Actually, I found something that gives a working example, but I'm not enrolled into the course to view it, yet:

 - Go to https://courses.openmined.org/courses/foundations-of-private-computation
 - Click on (1) Federated Learning
 - You will find "Duet: Classifying Flowers"

I might be missing something. I just looked into OpenMined today..

**Comment by soma2000-lang** [comment]
@kovkev  Can I work on this.I will take part in Gsod this year

**Comment by kovkev** [comment]
Of course

What is Gsod?

**Comment by soma2000-lang** [comment]
Google season of docs

**Comment by NightOnDark** [comment]
Did you find an demo? I also have the same problem.

**Comment by madhavajay** [comment]
@kovkev we have 2 people from GSOD working on docs and tutorials. We are also working on something related to CNNs and will be demonstrating it soon.
