### ISSUE TITLE
hagrid launch network is not working

### ISSUE THREAD

**Issue by pgupta07** [OpenMined/PySyft#6418]
## Description
I am using pysyft version 0.6.0 and trying to launch network using the below commands and getting errors.
1. hagrid launch network 
      getting below message in loop and network is not launching
      **control: authRoutine: backoff: 13265 msec**

2. hagrid launch United Nations --type network 
      getting below error message
      **Error: No such option: --type** 

3. hagrid launch United Nations --port 8085 --type network
      getting below error message
      **Error: No such option: --port**

I am trying to follow the below notebook from pysyft github notebooks-
    https://github.com/OpenMined/PySyft/blob/dev/notebooks/trade_demo/mock_notebooks/Part%201%20-%20Setup%20Use%20Case.ipynb

## System Information
 - OS: Linux (ubuntu 20.04)
 - Language Version: [e.g. Python 3.8]

**Comment by madhavajay** [comment]
Hi @pgupta07 those notebooks are pretty old and are mock notebooks, please see the more up to date docs here: https://openmined.github.io/PySyft/
