### ISSUE TITLE
pip install syft==0.6.0 raise a warning about version incompatible

### ISSUE THREAD

**Issue by xinxilwl** [OpenMined/PySyft#6424]
# Description
When i install pysyft 0.6.0, there is a conflict in packaging version.
'pip install syft==0.6.0', raise the ERROR below:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
statsmodels 0.13.2 requires packaging>=21.3, but you have packaging 21.2 which is incompatible.

'pip install --upgrade packaging==21.3', raise the ERROR below:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
syft 0.6.0 requires packaging==21.2, but you have packaging 21.3 which is incompatible.

# System Information
- OS: Red Hat 4.8.5-36
- Language: Python 3.7.11

**Comment by madhavajay** [comment]
We have upgraded packaging to `21.3` in `dev` and the API in `0.6` and `dev` (0.7.0) is nearly identical.
