### ISSUE TITLE
FL use Pysyft 0.6.0

### ISSUE THREAD

**Issue by NightOnDark** [OpenMined/PySyft#6467]
## Question
** Syft 0.6.0 cannot perform matrix calculation?**

**Comment by madhavajay** [comment]
Hi @NightOnDark we are about to release `0.7.0` from `dev` with a examples of NN training and FL as well as other great things. `0.6.0` was a big change from previous versions that introduced our containerized server for PyGrid, however during 0.6.0 our internal Tensor type was still being implemented. Please checkout `dev` to see our latest code which can handle a variety of operations with both DP and SMPC.
