### ISSUE TITLE
RecursiveScriptModule

### ISSUE THREAD

**Issue by JacksonSung** [OpenMined/PySyft#6469]
I want to know why training the model gets RecursiveScriptModule ,but it is marked?

**Comment by madhavajay** [comment]
@JacksonSung Can you please elaborate on what version you are running and what code you are running?

**Comment by JacksonSung** [comment]
@madhavajay I elaborate on pysyft-0.2.3a3，and my purpose is extracting  original torch.nn.Module or torchscript including original torch.nn.Module  from RecursiveScriptModule which derives from  train_config.TrainConfig().get_model().obj. 
Thank you for your quick reply.

**Comment by madhavajay** [comment]
Hi @JacksonSung sorry we don't support `0.2.x` any more, the old branch is here:
https://github.com/OpenMined/PySyft/tree/syft_0.2.x

The deprecation FAQ is here:
https://github.com/OpenMined/PySyft/blob/main/packages/syft/docs/FAQ_0.2.x.md
