### ISSUE TITLE
Provide visual feedback

### ISSUE THREAD

**Issue by tcp** [OpenMined/PySyft#6504]
## What?
Provide visual feedback when an action is performed. For example, when clicking a submit or save changes button, we should add a spinner to the button.

## Why?
Right now there's no indication to the user and that's a poor UX. Let's add visual indicators where needed - from button pressing to successful/failed actions - because we don't have anything meaningful right now. We can add them as we see fit.

## Indicators
- When a successful action is made, provide positive feedback
- When an action fails, display an error message and any other indication that the action failed
- When a button is pressed and the action is not resolved (e.g. a network request is pending response)
- If the user does not have the ability to execute an action

## Additional Context
Feel free to add any instances not listed above.

**Comment by tcp** [comment]
I'll just "throw" this here:
- Provide "Show" option on password fields

**Comment by madhavajay** [comment]
@tcp is this completed?
