### ISSUE TITLE
Extract strings to JSON files

### ISSUE THREAD

**Issue by tcp** [OpenMined/PySyft#6508]
## What?
Get all strings we have in PyGrid UI and extract them to JSON file(s) that we can share with the backend and use for internationalization.

## Why?
Have a single place for editing UI strings.

## Breakdown
- It has to cover all PyGrid UI routes
- There are no limitation on number of files - let's ensure it makes sense

**Comment by rasswanth-s** [comment]
I am closing long standing Github issues belonging to older PySyft versions(<=0.7). Kindly re-open the issue , if this issue needs to be addressed or is still  relevant.
