### ISSUE TITLE
Refactor Requests page

### ISSUE THREAD

**Issue by tcp** [OpenMined/PySyft#6511]
## What?
Refactor the pages under `/requests`.

## Why?
We have some updated content in Figma that should see the light of day asap. The entire flow needs to be reworked; it needs tests, we need to double check the routes and if we're showing the right information. In addition, there's a great chance for componentizing the requests pages.

## Breakdown
- Write e2e tests for `/requests`
- Check if all routes being used are correct
- Check if the contents being displayed are correct (e.g. current budget != requested budget)

## Additional Context
I'll leave space here for a better breakdown when this issue is underway.

**Comment by rasswanth-s** [comment]
I am closing long standing Github issues belonging to older PySyft versions(<=0.7). Kindly re-open the issue , if this issue needs to be addressed or is still relevant.
