### ISSUE TITLE
Overhaul Getting Started Section

### ISSUE THREAD

**Issue by ShubhamPalriwala** [OpenMined/PySyft#6593]
## Where?
The Entire Getting Started section recursively which is currently hosted [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

## Who?
First-timers who are compiling as well as running Syft for the first time

## What?
This would primarily update the structure, add multimedia wherever necessary, and update the commands wherever necessary

**Comment by ShubhamPalriwala** [comment]
@madhavajay I had an idea to revamp the current Getting started section in more of a _story format_ heavily inspired from our "Remote Data Science in 15 minutes" from the "Introduction to Remote Data Science course".
This would involve **gamifying** their experience with a storyline such as "predicting the number of heads in a coin toss" and introducing characters such as:
- Alice: One who tosses the coin aka Data Owner
- Bob: Who says he can predict the outcome without actually knowing the original result aka Remote Data Scientist
- Macy: Node where Alice keeps her record of the flips aka Domain node
- etc as the story progresses if needed

As the story progresses, they would be guided for the setup accordingly and whenever a setup is required, the page will split into 3 options:
- Linux OS
- Mac
- Windows


This will be very friendly as well as involving in nature for first-timers, **but** I doubt if the audience that just directly wants to get started with the local setup ASAP will not like this.

@IrinaMBejan @Kiaka007 @abhiwalia15 Would like to know your thoughts as well on the same!

**Comment by ShubhamPalriwala** [comment]
As discussed today, the Getting Started will focus primarily on the setup and we will be having something like "What's next guides" after the setup that will have micro-notebooks such as "Adding a data scientist", and "Increasing the Privacy Budget".

**Comment by abhiwalia15** [comment]
@ShubhamPalriwala I have added the screenshots.
