### ISSUE TITLE
Can PySyft train a model in distributed fashion?

### ISSUE THREAD

**Issue by lepangdan** [OpenMined/PySyft#6597]
## Question
**Can PySyft train model in distributed fashion?**

## Further Information
For example, I have multiple GPUs or multiple machines.  How can I use PySyft train my model in this case?
please help, thanks in advance.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by madhavajay** [comment]
@lepangdan if you create a Domain on each machine and split your data up, then you can connect to them via a `client` and do data parallel, however we currently don't support multiple distributed workers for a single action graph, but this is something we will build down the track.

**Comment by lepangdan** [comment]
> 
@madhavajay  I don't really get that multiple distributed workers for a single action graph?  could you explain it in more detail? In fact, what I want to know is if I have multiple machines that have their own data, could I train a model using federated learning.  I really care if these machines can communicate with each other and, if possible, how to communicate in PySyft. Is there any tutorial for the case?

**Comment by madhavajay** [comment]
@lepangdan We are doing something in this vein currently but it has not been released as a tutorial. If you look at the SMPC examples you will see that operations can be done against multiple nodes via SMPC. The communication is handled via the client class which is the same one that you get when logging into a node.
