### ISSUE TITLE
send doesn't affect Identity layers

### ISSUE THREAD

**Issue by JosephChataignon** [OpenMined/PySyft#6611]
## Description
Identity layers, or models composed only from Identity layers, cannot be sent to a worker. It doesn't happen if there are other types of layers in the model (for example if the model has one Linear layer and one Identity layer), so I suppose this is due to Identity layers not including any tensors.
 
## How to Reproduce
bob = sy.VirtualWorker(hook, id="bob")
model = nn.Sequential(nn.Identity(10),nn.Identity(10))
model.send(bob)
print(model.location)
--> None

**Comment by madhavajay** [comment]
@JosephChataignon `sy.VirtualWorker` is from 0.2.x which is no longer supported.
