### ISSUE TITLE
PyTorch-based getting started examples

### ISSUE THREAD

**Issue by naga-karthik** [OpenMined/PySyft#6612]
## Question
Are there any getting-started examples using PyTorch Models with PySyft?

## Further Information
I am trying to find a few examples for getting started with PySyft using PyTorch. I noticed that torch was installed during the installation of PySyft but I've been unable to find the relevant examples for the same. Previous blog posts and other tutorials do have torch commands but in all of them there's a note that that version of PySyft has been deprecated. Hence, my questions are:
1. Currently, are there any active PyTorch examples for training federated learning models with PySyft? In particular, I was wondering if there's torch-based version of [this tutorial](https://github.com/OpenMined/PySyft/blob/1d9142139b3a8559b09b6fa3379d91b184670e69/notebooks/medical-federated-learning-program/data-scientists/01-data-scientists-start.ipynb), which train a _NumPy_ model on MedNIST. 
2. If not, is this feature going to be available soon in the near future?  
3. I also looked into the FL course seen [here](https://github.com/OpenMined/courses/tree/foundations-of-private-computation/federated-learning/duet_fl). Seeing as this was last updated in March 2021, I am wondering whether examples presented there are still supported in the current PySyft version. 

It would be great if you could provide some more information on these. Thanks!

## System Information
 - OS: MacOS
 - OS Version: Monterey 12.4
 - Language Version: Python 3.9
 - Package Manager Version: Conda 4.13.0

**Comment by naga-karthik** [comment]
Thanks for getting back, @madhavajay! Looking forward to working with the examples! I'll keep this issue open for any updates until then.

**Comment by kiristern** [comment]
Hi @madhavajay I noticed this issue has been closed but unsure where to find the (new) examples of using PySyft for training PyTorch FL models, as described in the original comment. Would you please be able to direct me to the tutorial? Thank you for your work !

**Comment by madhavajay** [comment]
Hi @kiristern it's not ready yet, but we do have a docs team working on new documentation and the PyTorch training code is being worked on. Thanks for your patience.

**Comment by luameows** [comment]
@madhavajay Hi， any update about the torch example?
