### ISSUE TITLE
Whether the grid node will see the data uploaded from the data owner?

### ISSUE THREAD

**Issue by lepangdan** [OpenMined/PySyft#6614]
## Question
**Whether the grid node will see the data uploaded from the data owner?**

## Further Information
I recently study the course in OpenMined website. Currently, I am running the code in /courses/federated-learning/duet_basics/exercise. I am wondering whether the grid node will see the data uploaded from the data owner because I notice there needs a data owner uploading its data to the grid node.   So if it is, is the data of the data owner still safe and private? I am not sure what gridNode will see about the data of worker. Another computation is performed in worker of data owner or gridNode?

Any help is welcome!

![image](https://user-images.githubusercontent.com/24525814/175882199-943c8e8d-a359-4e31-ab96-fa1a664a74dc.png)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by madhavajay** [comment]
Hi @lepangdan, data sent to a Domain is visible by the person who sent it there, and anyone who owns the domain since they have control of the physical database and the data is not stored encrypted at rest by default. Typically this means that private data is only added by Data Owners to their Domains.

Does that answer your question?

**Comment by lepangdan** [comment]
Hi, @madhavajay  Thanks for your reply. And I have 3 confusing problems which need to be clarified with your help.  
1. **Whether Duet or GridNode or OpenMined could see the data uploaded by the data owner** because the following code shows data owner needs to send their data to duet `age_data_pointer = age_data.send(duet, pointable=True)` [see here](https://github.com/OpenMined/courses/blob/foundations-of-private-computation/federated-learning/duet_basics/Duet_Basics_Data_Owner.ipynb).  
2. **Or the data owner doesn't send actual data to the duet, which only creates a data address pointer**, and makes the duet know where the data is stored, and sent the address of the dataset if the data owner allows, then the duet sent to address to the data scientist?
3. The speaker says GridNode exit and does not participate in connection anymore after the data owner and data scientist create a connection [see here](https://courses.openmined.org/courses/foundations-of-private-computation/5b4beea5-9e95-42a5-9b8e-c5222386314a/7ed3019d-3d1f-4cc1-9231-b61143bda983),  however, we can see in code, duet still do much work,  is the two things conflict?

**Comment by madhavajay** [comment]
@lepangdan In the version you refer to syft `0.5` with Duet, there are two nodes and they communicate peer to peer. There is a signalling server used to establish the p2p connection through a firewall but after that the traffic is purely peer to peer and uses this library:
https://github.com/aiortc/aiortc

I believe it has some kind of encryption of the UDP packets but you would need to check their documentation. Regardless, Syft 0.5 is not intended for production use.

**Comment by lepangdan** [comment]
@madhavajay  so you mean the data owner did upload the actual data (encrypted version) to duet,  not duet just knowing an address pointer?

**Comment by madhavajay** [comment]
@lepangdan in Duet there are two nodes, one is the Data Owner side with a store, and the other is the Data Scientist. All data that is send with `.send` goes to the Data Owner side. None of that traffic goes through any other servers.

**Comment by lepangdan** [comment]
I see，many many thanks!

发自我的iPhone

在 2022年6月29日，10:33，Madhava Jay ***@***.***> 写道：

﻿

@lepangdan<https://github.com/lepangdan> in Duet there are two nodes, one is the Data Owner side with a store, and the other is the Data Scientist. All data that is send with .send goes to the Data Owner side. None of that traffic goes through any other servers.
