### ISSUE TITLE
Could I  do multi-party communication via PySyft ?

### ISSUE THREAD

**Issue by lepangdan** [OpenMined/PySyft#6615]
## Question
**Could I  do multi-party communication by PySyft, I know Pysyft can do two-party communication?**

## Further Information
Could I  do multi-party communication by PySyft, I know Pysyft can do two-party communication, where one party is the data owner and another is the data scientist. If data is stored on multiple servers, or we need many worker to communicate simultaneously？

If many workers can communicate simultaneously, what is their topology architecture? ring-shape, star-shape, and so on?

**Comment by madhavajay** [comment]
Hi @lepangdan the nodes can talk to each other directly, or via a network using something we call a ProxyClient.
If you look at our SMPC Integration tests you can see that they have 3 party communication going on.

https://github.com/OpenMined/PySyft/blob/f62ba29ff944b456e62ad03ee1fad9baa87974dd/tox.ini#L334
https://github.com/OpenMined/PySyft/tree/dev/tests/integration/smpc
