### ISSUE TITLE
Getting Started for Personas

### ISSUE THREAD

**Issue by abhiwalia15** [OpenMined/PySyft#6621]
## Description
Writing a new getting started section for each of the user personas. It will tell where to start, the basic requirements, and the role of that persona. 

## Why this improvement?
The current information needs more context to explain the role of particular personas.

## Additional Context
Link to the existing doc: https://openmined.github.io/PySyft/deployment/glossary.html#personas

**Comment by IrinaMBejan** [comment]
Hi Mrinal,

I will close this one since there are other issues to cover every batch of notebooks we work on ([first one](https://github.com/OpenMined/PySyft/issues/6677), [second one](https://github.com/OpenMined/PySyft/issues/6688))
