### ISSUE TITLE
HAGrid quickstart

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6624]
## Feature Description
```
$ hagrid quickstart
```

## Requirements
- hagrid creates a virtualenv
- installs syft (latest pre version) into the virtualenv
- installs jupyter / jupyterlab
- launches jupyter with the quickstart notebook dir

## Prototype code
```python
# these will probably need to be dependencies
pip install virtualenv
pip install virtualenv-api

directory = "/tmp/b"

from virtualenvapi.manage import VirtualEnvironment
env = VirtualEnvironment(directory)

env.install("syft==0.7.0b30") # cant figure out how to add --pre
env.install("jupyter")

import subprocess
cmd = 'source bin/activate; jupyter notebook --notebook-dir=/Users/madhavajay/dev/PySyft/notebooks/quickstart'
subprocess.call(cmd, shell=True, cwd="/tmp/b")
```

## Open Questions
- when do we choose to upgrade syft, perhaps we should put the latest version of Syft into HAGrid so that it knows and can compare and prompt the user, "would you like to upgrade your syft?"
- currently we have a git checkout of syft with notebooks in hagrid, but it would be nice to move away from this at some point so my guess is we would be best to "download" the notebooks/quickstart directory or something and put it into this destination sandbox for them.
- perhaps we need an option to reset it with:
```bash
$ hagrid quickstart reset
Warning all your changes to the quickstart environment will be lost. Are you sure you wish to conintue? (y/n)
```

Works pretty well!
<img width="532" alt="Screen Shot 2022-07-01 at 2 06 26 pm" src="https://user-images.githubusercontent.com/2882739/176821500-d4a366b2-e460-4f71-9712-d4afca1b3c35.png">

**Comment by ShubhamPalriwala** [comment]
@madhavajay We can close this also?
