### ISSUE TITLE
GSOD - Finish first two DO Notebooks

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6677]
## Description
Awesome work on `quickstart` and the first two notebooks.

I think we should finish these up end to end and then once theyre mergable we can plan out the next few.

### Notebooks
- [x] Finish DO Create Domain and Upload Flow
- [x] rename files to be 00, 01, use hyphens and lowercase, remove redundant text like Data Owner
- [x] Create breadcrum and link top of Notebook to Install Wizard
- [x] Remove utils import from Upload notebook
- [x] Update README.md with links to published docs
- [x] Update HAGrid to download files and folders based off dev
- [x] Add relative path downloads to quickstart
- [x] Deploy notebook should use port 8081 or 9082 (just conventions we use in other places)
- [x] Add --silent to hagrid launch cell
- [x] Change hagrid check cell to use localhost:8081 (or 9082)
- [x] Change login to use no url but to include port=8081 (or 9082)
- [x] Link Notebooks in Sequence at the bottom of each tutorial
- [x] Move `hagrid quickstart` command to the top right of RST Docs

### HAGrid
```
$ hagrid quickstart data-owner
# downloads all files in dev branch data-owner
# and launches the 0th notebook
$ hagrid quickstart data-owner/00-deploy-domain 
# downloads just that notebook
```

- [x] Quickstart download overwrite prompt should include (all option) (y/n/a)
- [x] Add repo and branch/tag override to quickstart

```
$ hagrid quickstart data-owner/00-deploy-domain --repo=madhavajay/PySyft --branch=mybranch
$ hagrid quickstart data-owner/00-deploy-domain --repo=madhavajay/PySyft --commit=c75d98c3543954bfc8d1386205fbba1855f72b95
# downloads from those repo and or commit / branches where the default is `openmined/PySyft` and `dev`
```

- [x] hagrid disable jupyter extension on install
```
$ jupyter labextension disable @jupyterlab/cell-toolbar-extension
```

### Linting and Testing
- [ ] Make sure the notebooks run
- [x] Keep an eye out for formatting of code in cells
- [x] remove excess spacing on headings
- [x] Use normal font size for main text and custom headings
- [x] Proof read spelling and punctuation
- [x] Check for consistency

**Comment by madhavajay** [comment]
@abhiwalia15 and @ShubhamPalriwala can you comment on this issue so I can assign you both?

**Comment by abhiwalia15** [comment]
Hey @madhavajay, I would like to start with the Notebooks. Please assign this task to me; thanks!!

**Comment by ShubhamPalriwala** [comment]
Yep, on it with @abhiwalia15

**Comment by abhiwalia15** [comment]
> Hey @madhavajay, I would like to start with the Notebooks. Please assign this task to me; thanks!!

Hello @madhavajay, can you please assign this to me so I can tickmark the tasks I am completing?
