### ISSUE TITLE
GSoD: Quickstart notebooks for data owners 

### ISSUE THREAD

**Issue by IrinaMBejan** [OpenMined/PySyft#6688]
## Where?
We would like to extend the quickstart section of the documentation with the main remaining tutorials for the data owners:

1. Create Network (@ShubhamPalriwala )  - #6800 
    - Learning objective: How data can be shared among multiple people, the concept of a network
2. Join a network (@ShubhamPalriwala ) - #6693 
    - Learning Objective: How to discover networks and contribute to them
3. Create Accounts + Manage Privacy Budget (@abhiwalia15 ) - #6759 #6789 
    - Learning objective: How to manage the access to your domain and uploaded dataset and why is it important

The first iteration of all notebooks should be ready for review by Friday (2nd).

## Who?
New users to OpenMined looking to learn how to use PySyft and PyGrid as a data owner.

## What?

- [x] Define create a network, join a network flow 
- [x] Define functionalities to be showcased in the management of the privacy budget
- [x] Finish notebook tutorials in notebooks/quickstart
   - [x] Create a network
   - [x] Join a network
   - [x] Create account + manage privacy budget 
- [ ] Add corresponding pages to docs/ section
   - [x] Create a network
   - [x] Join a network
   - [ ] Create account + manage privacy budget
- [ ] Link tutorials in the README.md

Quality control (Linting and testing):
- [ ] Make sure the notebooks run
- [ ] Keep an eye out for formatting of code in cells
- [ ] No excess spacing on headings
- [ ] Use normal font size for main text and custom headings
- [ ] Proofread spelling and punctuation
- [ ] Check for consistency

**Comment by abhiwalia15** [comment]
@IrinaMBejan Hey, can you assign this issue to me? Thanks

**Comment by ShubhamPalriwala** [comment]
Hey @IrinaMBejan Now that all the PRs are open for this, can you reference them in the issue title itself so that it gets easier to track them?
