### ISSUE TITLE
Failed to import hagrid - Windows

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#6711]
## Description
A clear and concise description of the bug.

## Expected Behavior
hagrid should have listed the dependency table.

## Screenshots

```
(syft_env) C:\Users\huseyin.demirci> hagrid
Traceback (most recent call last):
  File "C:\Users\huseyin.demirci\Anaconda3\envs\syft_env\lib\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "C:\Users\huseyin.demirci\Anaconda3\envs\syft_env\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\huseyin.demirci\Anaconda3\envs\syft_env\lib\site-packages\git\cmd.py", line 341, in refresh
    raise ImportError(err)
ImportErr
```

## System Information
 - OS: [e.g. iOS] Windows
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
Looks like its complaining about git not being installed. But it could be another issue. Do we have access to this users test environment?

**Comment by madhavajay** [comment]
https://github.com/OpenMined/PySyft/issues/6748

**Comment by shubham3121** [comment]
We don't have access to the user env, but I think you're right, git seems to be the issue.

**Comment by shubham3121** [comment]
Fixed in: https://github.com/OpenMined/PySyft/pull/6755
