### ISSUE TITLE
Resolution - Build dependency issue in M1

### ISSUE THREAD

**Issue by factdroid** [OpenMined/PySyft#6712]
## Where?
Where are you looking to add documentation? Which file? Which feature?
- FAQs

## Who?
Who is your audience for this documentation issue?
- People with new M1 machine

## What?
Describe what you would like this documentation to accomplish.

```
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output

```
Appears to be resolved with `sudo xcodebuild -license`

**Comment by madhavajay** [comment]
We need to add `brew` to their `dependency check` because without brew they wont be able to install much stuff, and brew itself will check for and install the xcode tool chain.

**Comment by madhavajay** [comment]
Also if this is for normal pip install syft this will go away now that we dont require pycapnp to be compiled with cmake....

**Comment by madhavajay** [comment]
Related to this:
https://github.com/OpenMined/PySyft/issues/6714

This is caused by the requirement to compile pycapnp which is no longer required.
