### ISSUE TITLE
Update hagrid install README instructions

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6724]
We should change `pip install hagrid` to `pip install -U hagrid` to ensure users get an updated version at all times.

Check the repo for areas where this is written and replace them.

**Comment by madhavajay** [comment]
@Boluwatifeh Thanks for the PR, there were a few more changes required so I merged Stephens PR. If you want to help out we can use your help with some user testing. Come to Slack and ping myself or Stephen and we can point you at the private signup form.

**Comment by Boluwatifeh** [comment]
Alright, thanks @madhavajay i'll do that right away. See you on Slack!
