### ISSUE TITLE
Uploading Dataset tutorial issues

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6733]
Uploading Dataset tutorial that was linked from the Tinker User Testing Upload guide was broken. We should make sure to go through these and fix them and test them before we include them in our user test sessions.

**Comment by shubham3121** [comment]
Fixed through this PR: https://github.com/OpenMined/PySyft/pull/6669/commits/4230e697bef88fd087b75bed059a20cd63f2f92d

**Comment by madhavajay** [comment]
@shubham3121 was this PR merged already but just not used in that previous session?

**Comment by shubham3121** [comment]
@madhavajay The Upload tutorial link used in the session was broken because the tutorial wasn't merged in dev. Now the corresponding PR has been merged and the Tester guide updated with correct tutorial notebooks.
