### ISSUE TITLE
Create python + html output version of hagrid launch docker

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6734]
Allow hagrid launch to docker to be runnable via python rather than CLI and make the output nice and formatted with HTML the way quickstart / install wizard works.

Once this works remove `!hagrid launch` from the install wizard and replace with python version `hagrid.launch()`

**Comment by rasswanth-s** [comment]
Currently this is possible with the new Syft Orchestra Feature, hence closing the issue.Kindly Re-open the issue, if the issue is not fully addressed in the current version.
