### ISSUE TITLE
Create 1 liner powershell script for Windows Bootstrapping

### ISSUE THREAD

**Issue by jackbandy** [OpenMined/PySyft#6763]
## Question
What are best practices for checking PySyft dependencies on Windows?

## Further Information
Machines running Windows seem to encounter a wider range of issues during playing with PETs sessions. Today this included issues that required re-installing `rust` and `ansible` before PySyft got up and running. Is there additional testing that could/should be done for PySyft on windows? What are best practices for checking dependencies beyond what's in the [documentation](https://openmined.github.io/PySyft/install_tutorials/windows.html)?

## System Information
 - OS: Windows
 - OS Version: Windows 10 version 2004 or higher

**Comment by madhavajay** [comment]
I think we can create something similar to this:
https://github.com/OpenMined/PySyft/issues/6737

Check for a few basic pre-reqs that `hagrid` needs and then attempt to install them and hagrid.

**Comment by madhavajay** [comment]
New CLI tool syftcli handles windows.
