### ISSUE TITLE
How to Average the Models in tutorials/Part 06

### ISSUE THREAD

**Issue by kongfany** [OpenMined/PySyft#6765]
## Question
*How to Average the Models in tutorials/Part 06？*

## Further Information
As I understand it, during the training process, the model is sent to bob for training, and then sent to alice for training. There is no model aggregation process, just like the parameter averaging in part04.
Is there a simple way of model aggregation in subsequent tutorials? Use version 0.2

**Comment by madhavajay** [comment]
Version 0.2 is no longer supported.
