### ISSUE TITLE
HAGrid quickstart --reset permissions on Windows

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#6775]
## Description
A clear and concise description of the bug.

## How to Reproduce
1. Go to powershell as Adminstrator
2. Install hagrid: pip install -U hagrid
3. Run hagrid quickstart --reset
4. Permission error

```
[WinError 5] Access is denied: 'C:\\Users\\Laura\\.hagrid\\quickstart\\.venv\\Lib\\site-packages\\hagrid\\PySyft\\.git\\objects\\pack\\pack-d464f40812a20a92f97bb94fa6427185dc1346d8.idx'
Error running quickstart: [WinError 5] Access is denied: 'C:\\Users\\Laura\\.hagrid\\quickstart\\.venv\\Lib\\site-packages\\hagrid\\PySyft\\.git\\objects\\pack\\pack-d464f40812a20a92f97bb94fa6427185dc1346d8.idx'
Traceback (most recent call last):
  File "c:\users\laura\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\laura\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Laura\anaconda3\Scripts\hagrid.exe\__main__.py", line 7, in <module>
  File "c:\users\laura\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\laura\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\laura\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\laura\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\laura\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\laura\anaconda3\lib\site-packages\hagrid\cli.py", line 2767, in quickstart_cli
    return run_quickstart(
  File "c:\users\laura\anaconda3\lib\site-packages\hagrid\cli.py", line 2699, in run_quickstart
    raise e
  File "c:\users\laura\anaconda3\lib\site-packages\hagrid\cli.py", line 2590, in run_quickstart
    quickstart_setup(
  File "c:\users\laura\anaconda3\lib\site-packages\hagrid\cli.py", line 2887, in quickstart_setup
    raise e
  File "c:\users\laura\anaconda3\lib\site-packages\hagrid\cli.py", line 2847, in quickstart_setup
    shutil.rmtree(virtual_env_dir)
  File "c:\users\laura\anaconda3\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\laura\anaconda3\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\laura\anaconda3\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\laura\anaconda3\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 4 more times]
  File "c:\users\laura\anaconda3\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\laura\anaconda3\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Laura\\.hagrid\\quickstart\\.venv\\Lib\\site-packages\\hagrid\\PySyft\\.git\\objects\\pack\\pack-d464f40812a20a92f97bb94fa6427185dc1346d8.idx'
```

## Expected Behavior

hagrid quickstart runs and starts a jupyter server

## System Information
 - OS: [e.g. iOS] Windows
 - OS Version: [e.g. 22] Windows 10
 - Language Version: [e.g. Python 3.7, Node 10.18.1] : Python 3.8.12
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

## Additional Context
`hagrid debug`

"datetime": "22/09/2022 09:25:54 Mountain Daylight Time", "python_binary": "c:\\users\\laura\\anaconda3\\python.exe", "dependencies": {"docker": "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.EXE", "git": "C:\\Program Files\\Git\\cmd\\git.EXE", "ansible-playbook": "C:\\Users\\Laura\\anaconda3\\Scripts\\ansible-playbook.EXE", "wsl": ".\\wsl.EXE"}, "environment": {"uname": ["Windows", "MSI", "10", "10.0.19043", "AMD64", "Intel64 Family 6 Model 158 Stepping 13, GenuineIntel"], "platform": "windows", "os_version": "10", "python_version": "3.8.12", "os": "Windows", "apple_silicon": false}, "hagrid": "0.2.100", "hagrid_dev": false, "hagrid_path": "c:\\users\\laura\\anaconda3\\lib\\site-packages", "hagrid_repo_sha": "8b719374164e56a44e12d496aa40c0720fc2e67e", "docker": "Command 'docker info' returned non-zero exit status 1.", "wsl": "D\u0000e\u0000f\u0000a\u0000u\u0000l\u0000t\u0000 \u0000D\u0000i\u0000s\u0000t\u0000r\u0000i\u0000b\u0000u\u0000t\u0000i\u0000o\u0000n\u0000:\u0000 \u0000U\u0000b\u0000u\u0000n\u0000t\u0000u\u0000-\u00001\u00008\u0000.\u00000\u00004\u0000\r\u0000\r\u0000\n\u0000D\u0000e\u0000f\u0000a\u0000u\u0000l\u0000t\u0000 \u0000V\u0000e\u0000r\u0000s\u0000i\u0000o\u0000n\u0000:\u0000 \u00002\u0000\r\u0000\r\u0000\n\u0000\r\u0000\n\u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000S\u0000u\u0000b\u0000s\u0000y\u0000s\u0000t\u0000e\u0000m\u0000 \u0000f\u0000o\u0000r\u0000 \u0000L\u0000i\u0000n\u0000u\u0000x\u0000 \u0000w\u0000a\u0000s\u0000 \u0000l\u0000a\u0000s\u0000t\u0000 \u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000d\u0000 \u0000o\u0000n\u0000 \u00002\u00000\u00002\u00001\u0000-\u00001\u00001\u0000-\u00000\u00008\u0000\r\u0000\r\u0000\n\u0000T\u0000h\u0000e\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000S\u0000u\u0000b\u0000s\u0000y\u0000s\u0000t\u0000e\u0000m\u0000 \u0000f\u0000o\u0000r\u0000 \u0000L\u0000i\u0000n\u0000u\u0000x\u0000 \u0000k\u0000e\u0000r\u0000n\u0000e\u0000l\u0000 \u0000c\u0000a\u0000n\u0000 \u0000b\u0000e\u0000 \u0000m\u0000a\u0000n\u0000u\u0000a\u0000l\u0000l\u0000y\u0000 \u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000d\u0000 \u0000w\u0000i\u0000t\u0000h\u0000 \u0000'\u0000w\u0000s\u0000l\u0000 \u0000-\u0000-\u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000'\u0000,\u0000 \u0000b\u0000u\u0000t\u0000 \u0000a\u0000u\u0000t\u0000o\u0000m\u0000a\u0000t\u0000i\u0000c\u0000 \u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000s\u0000 \u0000c\u0000a\u0000n\u0000n\u0000o\u0000t\u0000 \u0000o\u0000c\u0000c\u0000u\u0000r\u0000 \u0000d\u0000u\u0000e\u0000 \u0000t\u0000o\u0000 \u0000y\u0000o\u0000u\u0000r\u0000 \u0000s\u0000y\u0000s\u0000t\u0000e\u0000m\u0000 \u0000s\u0000e\u0000t\u0000t\u0000i\u0000n\u0000g\u0000s\u0000.\u0000\r\u0000\r\u0000\n\u0000T\u0000o\u0000 \u0000r\u0000e\u0000c\u0000e\u0000i\u0000v\u0000e\u0000 \u0000a\u0000u\u0000t\u0000o\u0000m\u0000a\u0000t\u0000i\u0000c\u0000 \u0000k\u0000e\u0000r\u0000n\u0000e\u0000l\u0000 \u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000s\u0000,\u0000 \u0000p\u0000l\u0000e\u0000a\u0000s\u0000e\u0000 \u0000e\u0000n\u0000a\u0000b\u0000l\u0000e\u0000 \u0000t\u0000h\u0000e\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000U\u0000p\u0000d\u0000a\u0000t\u0000e\u0000 \u0000s\u0000e\u0000t\u0000t\u0000i\u0000n\u0000g\u0000:\u0000 \u0000'\u0000R\u0000e\u0000c\u0000e\u0000i\u0000v\u0000e\u0000 \u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000s\u0000 \u0000f\u0000o\u0000r\u0000 \u0000o\u0000t\u0000h\u0000e\u0000r\u0000 \u0000M\u0000i\u0000c\u0000r\u0000o\u0000s\u0000o\u0000f\u0000t\u0000 \u0000p\u0000r\u0000o\u0000d\u0000u\u0000c\u0000t\u0000s\u0000 \u0000w\u0000h\u0000e\u0000n\u0000 \u0000y\u0000o\u0000u\u0000 \u0000u\u0000p\u0000d\u0000a\u0000t\u0000e\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000'\u0000.\u0000 \u0000\r\u0000\r\u0000\n\u0000F\u0000o\u0000r\u0000 \u0000m\u0000o\u0000r\u0000e\u0000 \u0000i\u0000n\u0000f\u0000o\u0000r\u0000m\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000p\u0000l\u0000e\u0000a\u0000s\u0000e\u0000 \u0000v\u0000i\u0000s\u0000i\u0000t\u0000 \u0000h\u0000t\u0000t\u0000p\u0000s\u0000:\u0000/\u0000/\u0000a\u0000k\u0000a\u0000.\u0000m\u0000s\u0000/\u0000w\u0000s\u0000l\u00002\u0000k\u0000e\u0000r\u0000n\u0000e\u0000l\u0000.\u0000\r\u0000\r\u0000\n\u0000\r\u0000\n\u0000K\u0000e\u0000r\u0000n\u0000e\u0000l\u0000 \u0000v\u0000e\u0000r\u0000s\u0000i\u0000o\u0000n\u0000:\u0000 \u00005\u0000.\u00001\u00000\u0000.\u00001\u00006\u0000\r\u0000\r\u0000\n\u0000", "wsl_linux": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 18.04.5 LTS\nRelease:\t18.04\nCodename:\tbionic\n"}

=================================================================

**Comment by madhavajay** [comment]
Hrm, I wonder if this happens when installs are done with an Admin shell? Also I think that needs a UTF-16 decode on Windows.
