### ISSUE TITLE
Move private compare to one action from DS -> DO

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#6795]
## Description
The private compare is done with multiple messages passing between the DS and the DOs.

We could reduce this communication cost by transferring all the responsibility to do the operation to the DO.
The DS should only specify what action the DOs should run.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
Add any other context or screenshots.

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues which are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
