### ISSUE TITLE
Quickstart Improvements

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6797]
## Description
Fix spacing in quickstart install wizard text on first startup.
To test delete install_wizard_complete from your hagrid cache.

![image](https://user-images.githubusercontent.com/2882739/193166111-a0696fd2-b6e5-46f0-b6e7-155fd1e619eb.png)

Change hagrid check to accept kwargs only and pass in things like host instead of an array of args. I know we parse these with the cli click tooling later but they should match kwargs or we can create a different entrypoint so they do.
![image](https://user-images.githubusercontent.com/2882739/193166151-1e70db29-0f76-4fe6-8ac7-e689f535e08e.png)

Change timeout to 1 minute and in notebook mode, remove silent but allow for some really basic output (the rich tables are probably going to spam the notebook so we might not want to use them.)

**Comment by shubham3121** [comment]
Fix for removing silent but allowing for some really basic output is covered in Issue 6727: https://github.com/OpenMined/PySyft/issues/6727
