### ISSUE TITLE
Hagrid should automatically land if in-active for 'x' minutes or hours 

### ISSUE THREAD

**Issue by Sukanya-rs** [OpenMined/PySyft#6821]
## Description
When Hagrid is locally installed. The CPU on Mac is fully used to 99% or 100%. If we forget to get out of the session, it heats up. To Avoid CPU running idle and heating up the system, We can land the Hagrid after 'X' minutes or hours. Decision of after 'X' minutes should Hagrid should land should be decided by the core team. 

## Are you interested in working on this improvement yourself?
Not sure of how Hagrid code works, Can try if anyone can help me out !

## Additional Context
<img width="951" alt="Screenshot 2022-10-06 at 1 19 42 PM" src="https://user-images.githubusercontent.com/78011093/194248831-134c98ca-9f6a-4b22-b4c8-c7a6c46a77c6.png">

Current CPU temperature says it's "Nominal" after starting Hagrid but could feel the Mac heating up slowly. I think I had forgot to exit out of Hagrid at end of the day and after 12 hours , Mac had heated up. 

<img width="628" alt="Screenshot 2022-10-06 at 1 09 43 PM" src="https://user-images.githubusercontent.com/78011093/194248904-b6e03520-d52a-43e3-a3b0-90d08dc417a9.png">

**Comment by madhavajay** [comment]
Hi @Sukanya-rs I suspect there's no easy way to know if a server which waits for incoming requests should be safely automatically shutdown. In theory we could do some kind of loadbalancing and detect no traffic and shut down containers but I suspect that is out of the scope of local dev mode deployments anyway. I will close this for now.
