### ISSUE TITLE
Link to ` 01-upload-data` is broken in Deploy domain notebook

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#6833]
## Description
Link to the upload data notebook is broken in [Deploy domain notebook](https://github.com/OpenMined/PySyft/blob/dev/notebooks/quickstart/data-owner/00-deploy-domain.ipynb).

The `01-upload-data` should point to the [data upload notebook](https://github.com/OpenMined/PySyft/blob/dev/notebooks/quickstart/data-owner/01-upload-data.ipynb)

**Comment by abhiwalia15** [comment]
Hey @shubham3121 and @IrinaMBejan, the changes have been made and are in PR #6837. 

Please merge when checked ✅
