### ISSUE TITLE
Improve documentation with Annotate Data for Automatic DP Step

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#6836]
## Where?
https://openmined.github.io/PySyft/guides/data-owner/01-upload-data.html

- Can we simply or clarify what DP annotation means?
- If possible add an example to explain how does AutoDP preserve the privacy of the data subjects.
- simply language around what are min and max values and why they are needed. 

## Who?
General Audience

## What?
Make it easy for people to add DP metadata to the dataset they are uploading

**Comment by Boluwatifeh** [comment]
@shubham3121 can i work on this ?

**Comment by Boluwatifeh** [comment]
Okay, great!  A similar issue #6841 was opened  by @iamtrask  can you check it out and let me know so i can put that into consideration @shubham3121

**Comment by madhavajay** [comment]
@Boluwatifeh Are you able to submit a PR with progress? If you are too busy, I can unassign the ticket so that the task can be taken by someone else.

**Comment by madhavajay** [comment]
Hi @Boluwatifeh I have unassigned this for now as there has been no progress in 6 weeks.

**Comment by shubham3121** [comment]
Fixed by: https://github.com/OpenMined/PySyft/issues/6841 and https://github.com/OpenMined/PySyft/pull/6878
