### ISSUE TITLE
Improve DP Tensor UI/UX

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6841]
```
On the following page https://openmined.github.io/PySyft/guides/data-owner/01-upload-data.html

we describe how to annotate with DP metadata using code like this:

In:

# run this cell
data_subjects = sy.DataSubjectArray.from_objs(dataset["ID"])

age_data = sy.Tensor(dataset["Age"]).annotated_with_dp_metadata(
   min_val=0, max_val=100, data_subjects=data_subjects
)
```

Instead let's do something like:
```
age_data = sy.Tensor([40, 39, 9, 8]).annotate_with_dp_metadata(
   min_val=0, max_val=100, data_subjects=["Ishan", "Shubham", "Irina", "Osam"] 
)
```

This maximizes the intuitive understanding of what's going on. This has several changes:

- Instead of using sy.DataSubjectarray.from_objs() to annotate using a list of IDs, we pass in a simple, intuitive list of strings.
- "annotated_with_dp_metadata" ->"annotate_with_dp_metadata"
- Instead of first creating a DataFrame we just create a simple list of integers. Note that these could still be displayed in their own table in Step 3 just for intuition's sake.
- Instead of IDs being integers they're the names of people.

**Comment by shubham3121** [comment]
Fixed by: https://github.com/OpenMined/PySyft/pull/6845

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older versions of PySyft (<=0.7) and are not aligned in our current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
