### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by amdjedbens** [OpenMined/PySyft#6850]
## Description
It used to work normally on previous notebooks these last days, but when I ran: [notebooks/padawan/03-architecture.ipynb](https://github.com/OpenMined/PySyft/blob/dev/notebooks/padawan/03-architecture.ipynb) and when importing syft, it produces the following error (traceback below):
`ModuleNotFoundError: No module named '_lzma'`.

## How to Reproduce
with my system information mentioned below
1. `import syft as sy`
2. See error

## Expected Behavior
I expected Syft to be imported successfully like usual.

## System Information
 - OS: Linux Mint
 - OS Version: 20.3 "Una"
 - Syft version: 0.5.1
 - Hagrid Version: 0.2.106
 - Language Version: Python 3.10.4
 - Package Manager Version: conda 4.14.0

## Additional Context
- I tried to install that package but it says that the package is already up to date, So it wasn’t missing in the first place.

	I tried via: `sudo apt-get install lzma; sudo apt-get install liblzma-dev`.

- I've installed Syft again via: `pip install syft==0.6.0`, but still it produces same error.

### Traceback:
---
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    Input In [12], in <cell line: 2>()
          1 # ⚔️ Runnable Code
    ----> 2 import syft as sy

    File ~/.local/lib/python3.10/site-packages/syft/__init__.py:48, in <module>
         46 from syft.core.common.serde.serialize import _serialize as serialize  # noqa: F401
         47 from syft.core.node.common.service.repr_service import ReprMessage  # noqa: F401
    ---> 48 from syft.core.node.device.device import Device  # noqa: F401
         49 from syft.core.node.device.device import DeviceClient  # noqa: F401
         50 from syft.core.node.domain.domain import Domain  # noqa: F401

    File ~/.local/lib/python3.10/site-packages/syft/core/node/device/__init__.py:2, in <module>
          1 # syft relative
    ----> 2 from .client import DeviceClient
          3 from .device import Device
          5 __all__ = ["DeviceClient", "Device"]

    File ~/.local/lib/python3.10/site-packages/syft/core/node/device/client.py:16, in <module>
         14 from ...io.location import SpecificLocation
         15 from ...io.route import Route
    ---> 16 from ..common.client import Client
         19 @final
         20 class DeviceClient(Client):
         22     device: SpecificLocation  # redefine the type of self.device to not be optional

    File ~/.local/lib/python3.10/site-packages/syft/core/node/common/client.py:18, in <module>
         16 # syft relative
         17 from .... import serialize
    ---> 18 from ....lib import create_lib_ast
         19 from ....logger import critical
         20 from ....logger import debug

    File ~/.local/lib/python3.10/site-packages/syft/lib/__init__.py:29, in <module>
         27 from ..lib.remote_dataloader import create_remote_dataloader_ast
         28 from ..lib.torch import create_torch_ast
    ---> 29 from ..lib.torchvision import create_torchvision_ast
         30 from ..logger import critical
         31 from ..logger import traceback_and_raise

    File ~/.local/lib/python3.10/site-packages/syft/lib/torchvision/__init__.py:8, in <module>
          6 # third party
          7 from packaging import version
    ----> 8 import torchvision as tv
         10 # syft relative
         11 from ...ast.globals import Globals

    File ~/.local/lib/python3.10/site-packages/torchvision/__init__.py:5, in <module>
          2 import warnings
          4 import torch
    ----> 5 from torchvision import datasets
          6 from torchvision import io
          7 from torchvision import models

    File ~/.local/lib/python3.10/site-packages/torchvision/datasets/__init__.py:1, in <module>
    ----> 1 from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
          2 from .caltech import Caltech101, Caltech256
          3 from .celeba import CelebA

    File ~/.local/lib/python3.10/site-packages/torchvision/datasets/_optical_flow.py:13, in <module>
         10 from PIL import Image
         12 from ..io.image import _read_png_16
    ---> 13 from .utils import verify_str_arg
         14 from .vision import VisionDataset
         17 __all__ = (
         18     "KittiFlow",
         19     "Sintel",
       (...)
         22     "HD1K",
         23 )

    File ~/.local/lib/python3.10/site-packages/torchvision/datasets/utils.py:6, in <module>
          4 import hashlib
          5 import itertools
    ----> 6 import lzma
          7 import os
          8 import os.path

    File /usr/local/lib/python3.10/lzma.py:27, in <module>
         25 import io
         26 import os
    ---> 27 from _lzma import *
         28 from _lzma import _encode_filter_properties, _decode_filter_properties
         29 import _compression

    ModuleNotFoundError: No module named '_lzma'

**Comment by shubham3121** [comment]
@amdjedbens can you install syft 0.7 beta version: `pip install -U syft --pre`.

**Comment by amdjedbens** [comment]
Yes, that solved my issue, but looking forward to know the fix for the issue for `syft==0.5.1` or `0.6.0` version.
