### ISSUE TITLE
Public facing documentation about how Hagrid works

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6881]
## Where?
Where are you looking to add documentation? Which file? Which feature?
Add documentation that explains how Hagrid works behind the scenes, to refer people/partners to when they ask.

## Who?
Who is your audience for this documentation issue?
Partners and people interested in combining PySyft with their systems.

## What?
Describe what you would like this documentation to accomplish.
Instead of Hagrid being a black box, give a summary of its achitecture as well as a summary

**Comment by madhavajay** [comment]
Docs and README can be based off this notebook:
https://github.com/OpenMined/PySyft/blob/dev/notebooks/padawan/05-hagrid.ipynb
