### ISSUE TITLE
domain.apply_to_network(sy.networks[0]) works but is ugly

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6891]
## Description
The following creates a bunch of really ugly output.

<img width="1077" alt="Screenshot 2022-10-25 at 01 01 50" src="https://user-images.githubusercontent.com/4328594/197652357-8e056976-cf66-4c41-b11e-7de37026100b.png">

My theory is that because I didn't create a special variable for the network... aka

```
my_net = sy.networks[0]
domain.apply_to_network(my_net)
```

it created some errors but I could be totally wrong it's just a guess.

## How to Reproduce
1. launch a domain node with hagrid quickstart
2. run the code above

## Expected Behavior
The normal/clean apply_to_network output.

**Comment by shubham3121** [comment]
This is caused because of how we use multiprocessing during printing dynamic logs for when apply_to_network. https://superfastpython.com/filenotfounderror-multiprocessing-python/
