### ISSUE TITLE
Data Marketplace/Data space

### ISSUE THREAD

**Issue by kkech** [OpenMined/PySyft#6896]
## Description
The idea is to create a data marketplace/data space. This will allow data holders to expose their datasets to other users or organizations, to enable them to perform computations. Such computations can be training of machine learning models etc.

## Why?
Epics require a lot of work and often require a change in the scope of development. Justify your epic - why can't it just be a simple issue?
The above idea requires a lot of development because it requires a whole new platform to be constructed. Basically, is a feature on top of PySyft where the data holders with similar datasets, need to agree a common data model in order to enable scientists and engineers computation over the distributed dataset.

## Breakdown
Provide a bulleted or numbered list of how you might break this epic down into smaller issues.

- Authentication - Authorization - Identity
  - Common Issues to handle login who will have access to this data (Data will be distributed across several data holders, and a common data model will be agreed between those data holders). 
  - Grant/Revoke access from data owners in 
- Make data holders a community
  - Data Holders firsts need to come together and understand that they have similar data
  - Then, if data holders wants, they can be organized as a community of data
  - The community need to agree in a common data model
  - Needs to find a metric to measure the utility of the data that every member contribute to the community
  - Share the data model with some mock data (those data can be generated with synthetic data technique)
- Data Marketplace
  - Create a marketplace where data scientist and engineers will be able to find the "community" data
  - After a validation process, users or organization will get access to those data
  - The data engineers will be able to run computation over the datasets, using the agreed data model.

## Who else?
Does this work affect any other repositories, projects, or teams? If so, [provide links to the repos and teams you'll be involving](https://github.blog/2012-05-09-introducing-team-mentions/).

## Additional Context
Several papers are written into that directions such as:
https://link.springer.com/chapter/10.1007/978-3-030-63076-8_17
https://link.springer.com/chapter/10.1007/978-3-030-67270-6_6
https://www.sciencedirect.com/science/article/abs/pii/S0140366422000081

**Comment by iamtrask** [comment]
Hi @kkech - this does have a lot in common with PySyft's roadmap. One specific difference, the "need to agree a common data model" is something we think we've gotten past through the use of pointers and RPC. With PySyft, in theory you don't need to convince a bunch of data holders to agree to format their data in similar ways. We assume data scientists will do that remotely using the PySyft API.
