### ISSUE TITLE
Comment out GarbageCollectObjectAction because its not Implemented on Domain yet

### ISSUE THREAD

**Issue by teo-milea** [OpenMined/PySyft#6906]
## Description
When a pointer is no longer in use, the Garbage Collector is giving an error in the backend logs. If we don't support it anymore maybe we could disable it so we offer a cleaner experience for the data owners.

## How to Reproduce
You can use this code snippet: 
```
import syft as sy
import numpy as np 
do_client = sy.login(
    email="info@openmined.org",
    password="changethis",
    port=8081
)
x = sy.Tensor(np.array([1,2,3]))
# Send a tensor using the Data Owner Session
x_s = x.send(do_client, tags=["#X", "#diabetes"], description="My diabetes y label")
do_x_pointer = do_client.store[0]
result = do_x_pointer 
result = do_x_pointer * 2
```
## Expected Behavior
No error should appear in the backend log.

## Screenshots
![image](https://user-images.githubusercontent.com/29687796/198218977-f60e2f30-7fcc-4533-83b6-eb7526ecf60d.png)
![image](https://user-images.githubusercontent.com/29687796/198219149-e8cf7a34-b027-4a93-8595-9bb02196362a.png)
![image](https://user-images.githubusercontent.com/29687796/198219225-2a81b638-6aea-457a-b729-8295d446c47e.png)

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.10.4
 - Package Manager Version: Conda 4.10.3

**Comment by iamtrask** [comment]
Do we have a sense of how difficult it is to fix? My guess from this stack trace is that it's just missing a method called "reply_to" which is usually a no-op method. Garbage collection is a pretty important feature to have working - so if it's a quick fix it'd be better to fix than to disable.

**Comment by madhavajay** [comment]
I guess It's not broken, it's just not implemented. This error occurs because the code was written to send a GarbageCollection message but the Domain has no service to handle it. The only implementation I can find was for Worker / VM. In `0.8` this has been commented out already but the fix wasn't back ported to dev. I think we might want to do that to cut down on incorrect bug reports.
