### ISSUE TITLE
Calling .get() prematurely gives un-intuitive stack trace.

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6913]
Upon a freshly launched domain ("hagrid launch --tag=latest"), the following generates a very unintuitive stack trace.

```import syft as sy

me = sy.login(email="info@openmined.org", password="changethis", port=8081)

import numpy as np

n = 10000
_x = (np.random.randn(n) * 10).astype(np.int64)
x = sy.Tensor(_x).annotate_with_dp_metadata(min_val=0, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x), range(0,n))))

me.load_dataset(assets={"x":x}, 
                name="Test Dataset", 
                description="Short Desc")

me.create_user(name='Bob',
               email="andrew2@openmined.org",
               password="abc123",
               budget=10000000)

bob = sy.login(email="andrew2@openmined.org",
               password="abc123",
               port=8081)

initial_budget = bob.privacy_budget

x = bob.datasets[-1]['x']

out_ptr = x.mean().publish(sigma=10)
out = out_ptr.get()                                   #  <<<<<------   error occurs here

final_budget = bob.privacy_budget
```

![Image](https://user-images.githubusercontent.com/4328594/198748383-5174498c-26a0-4228-bd5c-a98890eaf11a.png)

**Comment by iamtrask** [comment]
Because I know how PySyft works - I know that this is because the user called .get() before the object existed and so the user needs to call .block.get() in order to be able to run this code without triggering a trace. 

However, even though I know this it's still painful from a UX experience. In a perfect world we'd be able to say "Hey - it looks like you're asking for an object that won't exist for another 4 seconds"... or at maybe .get() should be a blocking function by default?

In any rate - the error of "object with id can't be found" is a really opaque way to fail and is quite misleading. Would love to hear better ideas for how this UX could be.

**Comment by kirkdemeroukas** [comment]
Was having exactly the same issue and I was wondering why. Sometimes it worked but others it didn't even while changing absolutely nothing. I also tried calling .block.get() and while this doesn't throw an error anymore it just keeps loading for ever.

**Comment by madhavajay** [comment]
@iamtrask we are discussing providing more robust feedback during 0.8 specifically relating to all of the `async` actions that have been queued which would allow us to provide information about this since we would know that it was submitted but not completed as opposed to something which never existed or was deleted. I think the correct solution here is to expose better feedback about the state of the action graph to users.

**Comment by iamtrask** [comment]
Let's at least update this text to describe possible issues for the 0.7 release.

**Comment by iamtrask** [comment]
@kirkdemeroukas - sorry this was giving you trouble as well.

**Comment by madhavajay** [comment]
@kirkdemeroukas the PR I just merged should mean that .get will auto retry for 60 seconds by default. We will be doing more to provide information to the users on top of this soon.
