### ISSUE TITLE
PySyft lets me annotate data with min_val and max_val ranges narrower than the data

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6915]
I ran this code against a fresh domain ("hagrid launch --tag=latest")

```
import syft as sy

me = sy.login(email="info@openmined.org", password="changethis", port=8081)

import numpy as np

n = 10000
_x = (np.random.randn(n) * 100).astype(np.int64)
x = sy.Tensor(_x).annotate_with_dp_metadata(min_val=-20, 
                                                   max_val=20, 
                                                   data_subjects=list(map(lambda x:str(x), range(0,n))))

me.load_dataset(assets={"x":x}, 
                name="Test Dataset", 
                description="Short Desc")

```

This shouldn't work but it does.

**Comment by iamtrask** [comment]
Ideally it triggers an error if you try to pass in min_val or max_val ranges on a tensor which holds data that lies outside of those ranges.

**Comment by teo-milea** [comment]
While solving this we could also add a warning when min_val = min(x) and max_val = min(x)

**Comment by teo-milea** [comment]
Added checks in PR #6912 but should we also add server-side checks to prevent malicious uploads?
