### ISSUE TITLE
Showing accurate shape of tensor leaks a count query

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6920]

**Comment by iamtrask** [comment]
This was actually opened by @IshanMi

**Comment by rasswanth-s** [comment]
@iamtrask , @IshanMi  One small question, Accurate shape as in the public shape of TensoWrappedPhiTensorPointer/TensorWrappedGammaTensorPointer?

**Comment by iamtrask** [comment]
This has been remedied - because we don't have any tensor ops which return a different set of rows based on the private data values - this is a non-issue.

When we eventually add methods which return a different amount of data based on the private data values (a kind of filter method), we will need to revisit this.
