### ISSUE TITLE
Login with an URL doesn't work without specifying port

### ISSUE THREAD

**Issue by teo-milea** [OpenMined/PySyft#6929]
## Description
When specifying an URL, we need to add the port to both the URL and port parameters. This is not a big deal as the error output helps with that but it might be a better UX to remove the one or the other.  

## How to Reproduce
Start a domain with `hagrid launch --tag=latest` and run

```
import numpy as np
import syft as sy

client = sy.login(email="info@openmined.org", password="changethis", port=8081,url="http://0.0.0.0:8081")
client = sy.login(email="info@openmined.org", password="changethis", port=8081,url="http://0.0.0.0")
```

## Expected Behavior
If we already specify the port as a parameter we shouldn't specify it in the URL as well.

## Screenshots
This is the output when running the code:
![image](https://user-images.githubusercontent.com/29687796/199264346-b48ec68f-b654-4a74-854d-9bb0e0b62817.png)

## Additional Context
This is relevant when connecting to a domain over the Internet.

**Comment by madhavajay** [comment]
Yes, I think we should take the url and create a `GridURL` object, if there is no passed in url the default is `localhost` and then any `optional` supplied port, if its a valid `int` can be added to the `GridURL`. After that all the validation and convenience methods are available already to extract anything we want back out, so then we can raise an exception if the final resultant GridURL isnt valid.
