### ISSUE TITLE
Data subject checks fail when using the result of an operation like sum

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6933]
In several places in the codebase, we do the following check:
`if (self.data_subjects == other.data_subjects).all():`

If `self` and `other` is the result of an operation like sum, then this `self.data_subjects == other.data_subjects` returns a single Bool (since we're comparing two singletons) instead of an array of booleans (which has the attribute `all()`). This causes the check above to fail: 

![Image](https://user-images.githubusercontent.com/32711264/199333586-613306b6-92d1-48f8-93c2-7087366438b3.png)

**Comment by IshanMi** [comment]
This will also cause failures for methods like __mod__, __truediv__, __eq__, etc

**Comment by madhavajay** [comment]
Agreed. Since we are trying to support Tensors and Scalars in the same data types we should be more careful and perhaps introduce an `equality` check function we can call which checks the sizes and does the correct comparison in the event of a Scalar.

**Comment by teo-milea** [comment]
I added a quick fix in #7024 but no `equality` check function, maybe we can add it in `0.8`
