### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2' when importting syft

### ISSUE THREAD

**Issue by kiendang** [OpenMined/PySyft#6936]
## Description
`import syft` causes `error: ModuleNotFoundError: No module named '_bz2'` if using a python compiled without `bz2` support and thus the `_bz2` python standard module is not available causing the error. This happens when compiling `python` using `pyenv` on a linux system without the libbz2 header, for example on Ubuntu without `libbz2-dev` installed.

There is not much we can do within PySyft since this is a python/system requirements. We could either include this in documentation, but at I also think it's fine if we don't do anything about it. For this bug the fix is easy to find (googling brings the exact stackoverflow page with the fix). I submitted this issue so that next time if someone searches for it on github they can also find it here.

## How to Reproduce
1. On a ubuntu machine (tested with 20.04 but should be applicable to other versions) without the `libbz2-dev` apt package
2. Compile `python` with `pyenv`, *e.g* `pyenv install 3.10.8`
3. `pip install syft --pre`
4. Run `import syft` inside python

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: Python 3.10.8 installed with pyenv
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
I agree, thanks for filing the bug here so that future google searches end up here and help users to solve their problem! 🙂
