### ISSUE TITLE
When looking at a data science API doc string - I have to do a google search to find the corresponding numpy documentation

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6937]
see example at: https://youtu.be/bmZTu2gRrjA?t=710

**Comment by madhavajay** [comment]
What is the suggestion here? Should we include a link to the official numpy docs as a worst case backup?

**Comment by iamtrask** [comment]
Yes I think that's the solution here, at least until we have our own tensor API doc.

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues which are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
