### ISSUE TITLE
Wrong signatures for method `clip` for data pointer

### ISSUE THREAD

**Issue by kiendang** [OpenMined/PySyft#6941]
## Description
`clip` according to [numpy API](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.clip.html) has signature `ndarray.clip(min=None, max=None, out=None, **kwargs)` and does not require supplying both `min` and `max`. However in `syft` it requires both min and max passed in as the first 2 positional arguments. Thus things like `ptr.clip(500)` or `ptr.clip(max=500)` don't work.

## How to Reproduce
```py
import syft as sy
import numpy as np

domain_client = sy.login(email="info@openmined.org", password="changethis", port=8081)
arr = np.random.randint(0, 10000, (10000))
data = sy.Tensor(arr).annotate_with_dp_metadata(-1, 11000, data_subjects="Bob")
data_ptr = data.send(domain_client, tags=["my_data"])

domain_client.create_user(name="DS", email="test@email.com", password="password", budget=99999)
ds_client = sy.login(email="test@email.com", password="password", port=8081)

ds_client.store

d_ptr = ds_client.store[data_ptr.id_at_location]
```

Use `clip` with only min

```py
data_ptr.clip(500)
```

```
TypeError: _clip_dispatcher() missing 1 required positional argument: 'a_max'
```

or max

```py
data_ptr.clip(max=500)
```

```
TypeError: _clip_dispatcher() missing 2 required positional arguments: 'a_min' and 'a_max'
```

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by kiendang** [comment]
assigned to @sim017

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues which are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
