### ISSUE TITLE
UX: Spinner Animation to Hagrid Launch 

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6942]
## Feature Description
Currently when silent flag is provided during launching of node through hagrid, progress bars are displayed to show 

- `Pull`
- `Build`
- `Launch`
 
of docker containers.When we initially try to launch in a new system without any cached packages these steps take a `lot of time.`
Since we cannot provide time estimation in the progress bars, we could replace the ⌛ emoji by a spinner animation of rich library.

Current loading part:
![Screenshot 2022-11-03 at 9 45 39 AM](https://user-images.githubusercontent.com/43314053/199647158-c9a8f188-9194-4787-881d-05548973a8af.png)

Spinner animation example:
https://www.npmjs.com/package/cli-spinners

Reference to solve the issue.
https://rich.readthedocs.io/en/stable/progress.html

We could a spinner column to the rich progress in folder
`packages/hagrid/hagrid/cli.py` in `execute_commands` functions
https://github.com/OpenMined/PySyft/blob/5de360b9fc4cff81dda76bd0a35af7c0167554c4/packages/hagrid/hagrid/cli.py#L597

This is mainly to show new users that the thread is not frozen and it is still working as it takes time.

**Comment by bipinKrishnan** [comment]
Hi @rasswanth-s, I'm new to the PySyft codebase but I have some familiarity with using rich progress bars. I would like to work on this issue to get started here.

To add the spinner, I should change the code below:
https://github.com/OpenMined/PySyft/blob/5de360b9fc4cff81dda76bd0a35af7c0167554c4/packages/hagrid/hagrid/cli.py#L613

to this:
```python3
with Progress(
    SpinnerColumn(), 
    TextColumn("[progress.description]{task.description}"), 
    console=console, 
    auto_refresh=False,
  ) as progress:
```
Is this correct or am I missing something?

**Comment by rasswanth-s** [comment]
Sure , Go for it 🚀

**Comment by rasswanth-s** [comment]
We mainly need the spinner animation instead of clock gif when doing hagrid launch
You could follow the pysyft main readme, to install hagrid and launch quickstart which inturn would help to launch a domain, which would show if the spinner animation works.
Comment on the thread , if there were any blockers.

**Comment by madhavajay** [comment]
I would add that it would be great to make sure this also works inside the `Jupyter` notebook interface as that currently freezes between updates and can look blocked for a long time before it suddenly completes.
