### ISSUE TITLE
Convert non integer values when publishing/ Typecasting the output to the type of the pointer post publish

### ISSUE THREAD

**Issue by teo-milea** [OpenMined/PySyft#6946]
When publishing an array with values such as bool, the operation fails silently and the only way to do it is to convert them to int. Possibly this applies to other non-integer values. We should be able to do the conversion automatically and if possible even convert the results to the original data type

**Comment by shubham3121** [comment]
That's a good catch @teo-milea, I just noticed that today. 

Code to reproduce:
Launch domain:  `hagrid launch canada domain to docker:8081 --tag=latest --tail=false --dev`

**Comment by shubham3121** [comment]
Possibly related to issue: https://github.com/OpenMined/PySyft/issues/6967

**Comment by shubham3121** [comment]
As discussed, on publishing bool type results (e.g. mask = values > 100) we will convert the booleans to ints, add noise, and publish normally (so that flow is not broken). Also, we will warn the client that publishing bool values maybe provide inconsistent results. cc @IshanMi
