### ISSUE TITLE
Importing Syft causes errors in the logs

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6951]
Co-authored by @teo-milea

Just importing Syft (the first cell in the notebook) raises errors in the backend container: 

![Image](https://user-images.githubusercontent.com/32711264/199748592-8483a16f-6fdc-4644-b5dc-8d4c6fce5f08.png)

**Comment by madhavajay** [comment]
Duplicate of GarbageCollectionAction error.
