### ISSUE TITLE
Raise exception if min_vals and/or max_vals are nan when publishing

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6952]

**Comment by IshanMi** [comment]
co-authored by: @teo-milea 
Division by zero for instance would cause min/vals and max_vals to be NaN



![Image](https://user-images.githubusercontent.com/32711264/199749766-003eab9e-6e56-4a3f-89a6-7cd1ed7c02b0.png)

**Comment by madhavajay** [comment]
Would this allow someone to detect 0's by dividing and publishing without spending?

**Comment by teo-milea** [comment]
That should not be the case, as min and max are public values, the problem is that publishing fails and we feel like the problem should be raised here rather than on publishing. The problem you are describing is more related to #6956 if we raise an error instead of returning an array of Nans or maybe just noise.

**Comment by madhavajay** [comment]
Okay so essentially were just saying, hey what ever op you used to get here, the ability to add noise to the result is undefined and therefore we can't let you publish it. Seems reasonable to me.

**Comment by teo-milea** [comment]
yep, I think at this point is mostly and UX issues, as we are adding guards against NaN/Inf values in publish. The way we solved this for the demo is to add `1` to both members of the fraction, which is a pretty common thing to do in data science, so the practice should be kept for remote data science

**Comment by iamtrask** [comment]
See https://github.com/OpenMined/PySyft/issues/6950#issuecomment-1321004067 for a related exception.

Adding 1 to both members of the fraction is not enough to ensure that the privacy budget is preserved. I'm confident I could use this to attack the system and leak more information than the accountant was keeping track of. Please see the other comment above for how to deal with this issue for now.

**Comment by madhavajay** [comment]
Just for clarity I will link the comment from the other ticket here: https://github.com/OpenMined/PySyft/issues/6950#issuecomment-1321004067

I believe @iamtrask is suggesting this ticket should also use the same "I'm sorry, but our privacy accountant can't yet divide by a number which might be zero..." message.
