### ISSUE TITLE
Sum outputs an overflow error when it shouldn't be

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6954]
co-authored by @teo-milea

![Image](https://user-images.githubusercontent.com/32711264/199752162-aae977fa-6431-48bf-96a5-654967a18841.png)

**Comment by madhavajay** [comment]
Is this because of the underlying data type? E.g. Int32? The error is coming from `numpy` so unless we change the precision to higher how can we avoid this issue?

**Comment by teo-milea** [comment]
That's a good point. It probably is, as we were summing 10k values with a max_val of 700_000. The real question is whether this overflow creates a privacy problem when publishing, so I guess it is pretty urgent.

**Comment by shubham3121** [comment]
But this also happened for me, I was doing a mean query over a dataset of 13k rows with a max value of 150.

**Comment by teo-milea** [comment]
My guess is that in was on the `bounds` so it should be both locally and on the server as well, but I can investigate today.

**Comment by madhavajay** [comment]
@teo-milea and @IshanMi Considering that we shouldnt change precision for users unless they want it, and this happens locally the same as it would with any overflows and there is a numpy warning already, would you say that this can be closed for now?

**Comment by teo-milea** [comment]
I couldn't reproduce the numpy warning and the overflows happen on the server too, but given the new checks from #7008 and #7002 we should be safe for now, maybe keep it in a backlog somewhere for when we do another red teaming effort?
