### ISSUE TITLE
Test if we can handle `NaN` values in the publish system without revealing private data

### ISSUE THREAD

**Issue by teo-milea** [OpenMined/PySyft#6956]
Currently, in our test suite, we don't test with `NaN` values which can be a problem as we expect to spend `NaN` privacy budget when publishing arrays with at least one unknown value. 

Co-authored by @IshanMi

**Comment by madhavajay** [comment]
Given the issues that `NaN` causes im inclined to mark this as a `bug` even though its more pre-emptive.

**Comment by teo-milea** [comment]
I tested this and indeed the RDP constants become `NaN` and you can leak a whole array with a single `NaN` value. I inspected the code for `compute_rdp_constant` in `data_subject_ledger.py` and I was thinking that maybe when we detect `NaN` values (or `Inf` values) we can call computer_rdp_constant with private=False to use the bonds when computing the budget spent. @IshanMi what do you think about this solution?

**Comment by IshanMi** [comment]
If there's a NaN or Inf value in our array, my gut feeling says there's a good chance the min_val or max_val might also be NaN or Inf so private=False might also fail

**Comment by IshanMi** [comment]
Perhaps we can fall back on `private=False`, and throw an exception if `min_vals.data` or `max_vals.data` is a NaN or Inf

**Comment by madhavajay** [comment]
Fixed by: https://github.com/OpenMined/PySyft/pull/7008
