### ISSUE TITLE
Type is not reflected when viewing assets from .datasets API

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#6964]
## Description
A clear and concise description of the bug.

## How to Reproduce
1. `hagrid launch canada domain to docker:8081 --tag=latest --tail=false`
2. Upload dataset using this [notebook.](https://github.com/OpenMined/PySyft/blob/dev/notebooks/petlab_sessions/Population%20Census/Age%20Data%20of%20a%20Sample%20Population%20-%20Data%20Owner%20Notebook.ipynb) 
3. One can use [this dataset URL](https://raw.githubusercontent.com/OpenMined/datasets/main/synthetic_people_2020/people_in_indonesia.csv) as an example for the above notebook

## Screenshots

On viewing the assets the type column is empty for the given asset.
![Screenshot from 2022-11-04 16-25-19](https://user-images.githubusercontent.com/11032835/199957025-e29dc1cc-b7d6-4a26-b1a6-8b6c0db30c01.png)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
Strange.
