### ISSUE TITLE
Modifying the Pointer result of Publish Operation.

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6967]
## Description
The result of Publish operation is an Any pointer, which is  programmatically a correct result, but it is unintuitive for a beginner, 
we should re-enable the `resolve pointer type` service, which resolves the the underlying data in Any Pointer to corresponding result.

Screenshot of output:
![Screenshot 2022-11-04 at 6 07 17 PM](https://user-images.githubusercontent.com/43314053/199974275-ffeaa7c7-12e5-47c0-a0e4-42815fdb5251.png)

**Comment by madhavajay** [comment]
I think, this just means moving `def publish` to the `GammaTensorPointer` and returning a `numpy` pointer type.
