### ISSUE TITLE
Combining Pointer Subclasses of PhiTensor and GammaTensor.

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6968]
## Feature Description
Currently we have two subclasses for DP Tensors

- TensorWrappedPhiTensorPointer
- TensorWrappedGammaTensorPointer

Given these two pointer class, based on each operation we convert them into subsequent pointer classes.
We make so crucially on the fact that , we have data subjects on the Pointer side. 
Since we intend to remove Data subjects in reference  to the issue https://github.com/OpenMined/PySyft/issues/6958

## Possible Solutions:
We could tend to have an umbrella DP Tensor Pointer , which handles all the computation of PhiTensor/GammaTensor.
such that the only public values of the Pointer are the `min_vals`,` max_vals` such that the user is oblivious to the type of DP tensor pointer.

## Critical Note
Implementing this feature would break the `DP+SMPC` functionality in the codebase.

**Comment by madhavajay** [comment]
I agree that we shouldn't have a lot of manually constructed Pointer classes but we might want to address during `Derived Services`.

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues which are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
