### ISSUE TITLE
Remove Non-Working/Partial Functioning Code from public interface.

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6969]
## Problem
There are several places in which we allow experimental code interface publicly and some functionality which also partially works.
`Partial Functionality`:
TensorPointer Methods in (TensorWrappedPhiTensorPointer,TensorWrappedGammaTensorPointer)

- exp (Incorrect min/max calculation)
- softmax (Incorrect min/max calculation)
- reciprocal (Incorrect min/max calculation)

I think it would be a good idea to remove similar partial working code or fix them, such that beginners users do not stumble on them.

**Comment by madhavajay** [comment]
Yes if we have known incorrect / incomplete methods lets comment them out so they don't get shipped! This might break some tests but we can just disable them the functionality is not valid anyway.
