### ISSUE TITLE
When running "hagrid launch" I don't know what version of hagrid or syft I'm launching

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6970]
Often we care about what version of Syft or Hagrid we're launching (especially Syft) and it's a bit frustrating to not be able to find out until after all the containers have downloaded, launched etc.

![Image](https://user-images.githubusercontent.com/4328594/200049912-7f15ff34-89b6-443f-a0bd-b88f9944bbdd.png)

**Comment by madhavajay** [comment]
Agree, lets remove most of that unimportant information like the `tag` (this is unrelated to the docker tag its totally useless info for the user which isolates the containers between stacks with the proxy) and add something about the `docker tag` or `local dev build` version and the `hagrid` version.
