### ISSUE TITLE
"hagrid launch --tail=False" should be default + a table that lists containers and the commands to see their live logs

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6971]
The new user experience when --tail=False is incredible and by far the best experience for most users (everyone except devs?), especially since there's a definitive "you're fully launched' moment, as opposed to just watching logs until it stops. --tail=false should be the default experience except when you're in dev mode.

That said - finding logs is hard and scary to docker noobs and they're going to experience bugs. I think it would be great if we added a table to the final output of hagrid launch --tail-False which listed every container with a single command for how to see the logs. (and a highlight for where "if you get errors they'll be here or here" pointing somehow towards the streaming and backend containers. 

STRETCH: link to Rasswanth's video for finding logs in case people need it.

**Comment by madhavajay** [comment]
I agree we should default to `tail=false`. To provide more access to information we should build `hagrid status` which will show all the known nodes and allow a user to explore them further, either by checking logs or running commands like, land, update, backup, etc. A small step in that direction would be a `hagrid logs` command which could provide a quick way to access the logs of different containers.

In the meantime some helpful print statements is likely the best short term solution.

**Comment by bitsofsteve** [comment]
@madhavajay @iamtrask for this improvement, I have a PR open for this and have built the first working version of `hagrid logs`. 
 See PR [Here](https://github.com/OpenMined/PySyft/pull/7011) 

Please take a look here to leave a comment, if there's how we can make more improvements especially related to the wording of the output etc. 

I also assumed it will be best to default `--tail=false` even in dev mode, except explicitly set to `true.`

**Comment by bitsofsteve** [comment]
@madhavajay I am also thinking for the hagrid logs command we should have an option for log file dump to a directory.. something like `hagrid logs {{DOMAIN_NAME}} --dump_file=true` or something. I'd assume, this can be helpful, maybe?

**Comment by madhavajay** [comment]
@bitsofsteve great work but please stick to the scope of the ticket for now. This ticket only needs `--tail=fase` and a list of the docker commands.

**Comment by madhavajay** [comment]
@bitsofsteve great work.
I tested it and it works. I think there are some small changes that we want to do before merge.

It seems like it shows the health check twice?
<img width="611" alt="Screen Shot 2022-11-18 at 3 52 15 pm" src="https://user-images.githubusercontent.com/2882739/202630865-bd43d41f-759e-40d2-954e-43bc9a4c4b10.png">

The description on logging doesnt wrap properly.
<img width="667" alt="Screen Shot 2022-11-18 at 3 53 06 pm" src="https://user-images.githubusercontent.com/2882739/202630905-a6cf8871-291e-4d5b-aa6b-a0a925b1eeb9.png">
I think what you want to do here is remove the line breaks from the actual quoted text and instead break up the string like this to format it:

```python
long_string = (
+ "a really long line here"
+ "more long line continued here\n" # \n for explicit line breaks
)
```

That might fix it.
<img width="764" alt="Screen Shot 2022-11-18 at 3 52 59 pm" src="https://user-images.githubusercontent.com/2882739/202630888-b48ac71a-73e2-4258-8584-a6fb3536e05d.png">
