### ISSUE TITLE
Incorrect reconstruction when publishing the result of an op with args/kwargs

### ISSUE THREAD

**Issue by IshanMi** [OpenMined/PySyft#6972]
If the Data Scientist has enough privacy budget to use some of the data (but not all), we filter out the inputs they don't have the PB for, and "reconstruct" the tensor using the inputs they do have the privacy budget for. This is facilitated by `gamma_tensor.func_str` which tells us which functions to use when reconstructing the tensor.

The problem is that passing in args/kwargs like `axis=` or `order=` doesn't work for all operations. Flatten() is an example where it's done correctly, other ops like copy() or ravel() need to be modified so that reconstruction works as expected.

**Comment by iamtrask** [comment]
Quick fix: instead of removing values entirely, replace them with 0s so that all ops work as designed for the full computation.

**Comment by IshanMi** [comment]
We actually do this already- we replace values with 0 using `GammaTensor.filtered()` instead of doing any in-place replacing (since that can be difficult with JAX)

This issue has more to do with the fact that when using the new tensor, it's trying to call tensor.flatten() instead of tensor.flatten(order="F") because of an oversight on our end.

**Comment by madhavajay** [comment]
Fixed by this: https://github.com/OpenMined/PySyft/pull/7103

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
