### ISSUE TITLE
I can't click "How to use Ctop" on OSX

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#6975]
![Image](https://user-images.githubusercontent.com/4328594/200077151-078762cd-2a84-48d0-9b90-c53226192d43.png)

**Comment by madhavajay** [comment]
Interestingly this works for me, but I do have to press and hold `command` button first which is normal for highlighting links in my terminal. It might be a good idea to just output the raw link though for maximum compatibility.
<img width="329" alt="Screen Shot 2022-11-07 at 3 48 42 pm" src="https://user-images.githubusercontent.com/2882739/200235518-b3322b41-cdec-4632-b116-86ff8babe901.png">

**Comment by bipinKrishnan** [comment]
@madhavajay  I would like to work on this issue if no one else has already started. 

Replacing [this](https://github.com/OpenMined/PySyft/blob/d2bc2290b545c37bb0b6f0a0ad888530ae284405/packages/hagrid/hagrid/cli.py#L2981) print statement with the below one should solve the issue, right?
```python3
print("Video Explanation: https://youtu.be/BJhlCxerQP4\n")
```

**Comment by madhavajay** [comment]
@bipinKrishnan Thanks. I have assigned you, let me know if you have any questions. 🙂

**Comment by bipinKrishnan** [comment]
Cool! I will start my work on this :rocket:
