### ISSUE TITLE
Incorrect Mutation check by Capnp

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6976]
## Description
For the `inplace` operations in the `RunClassMethodAction.py` , after the function has completed execution, we do a mutation check by serializing the original data before and after the computation, to check if an `inplace` operation has happened by which we modify the original data in the database.
Code reference:
https://github.com/OpenMined/PySyft/blob/6f92240c336ad233cdef3e4e739cb1d15420b6fa/packages/syft/src/syft/core/node/common/action/run_class_method_action.py#L238

`Protobuf` seemed to generate the same bytes value, when we serialize the same object   several times, but `pycapnp` serialized objects tends to have different bytes when we serialize the same data.

This inturn causes it to think , it is mutated and we store the same data again to the Database.

The screenshot contains the serialization example with `pycapnp`

![Screenshot 2022-11-05 at 2 31 43 PM](https://user-images.githubusercontent.com/43314053/200112101-1b34c7c0-5419-45bf-a52d-9d7b4679e7c7.png)

## Expected Behavior
To be able to detect correctly mutated and non mutated data and modify the database data accordingly

## Bonus Performance Point
Serialization happens at four stages at RunClassMethod.

data = Original data to operate on .
- Deserialization of `data` to operate on from the DB
- Serialization of the data as resolved_self_previous_bytes( for mutation check)
- Serialization of the data after the computation has completed(for mutation check)
- Serialization of the result of the method of RunClassMethod.

Serialization is costly when we work with large datasets, migrating from serialization to check for mutation would give a `major performance hit`.

**Comment by madhavajay** [comment]
Great find. I can replicate this and it appears that the part of the `bytes` which varies are the `Int` values, assuming the data is after the type.


![Image](https://user-images.githubusercontent.com/2882739/200234820-5b9e7a35-7ddc-4be5-b2c2-bcf0cf607f5e.png)


![Image](https://user-images.githubusercontent.com/2882739/200234851-5719d75a-0749-4827-bd46-21564097b6d5.png)

Most comparisons seem to pass so this is definitely weird, but we should add the `bytes` equality to our tests.

**Comment by madhavajay** [comment]
@tudorcebere since this forces a mutation do you think this is an issue? Or does it not matter since the user who has permission can anyway and as you said the bytes representation is stable in `0.8`?

**Comment by tudorcebere** [comment]
My call is that all of this is generated from the usage of python primitives & associated IDs. Every time we serialize a primitive object like `str`, `int`, etc we upcast to sy.String, sy.Int. When upcasting, we need to have an associated unique id. This unique id is generated randomly, and it's added to the serialized format of the object . Right now, it cannot be made the same across multiple consecutive serializations.

Good news:
* in `0.8.0`, we don't have primitives anymore in the serialization stack, and I think this won't reproduce. (to be properly tested)
* This feature never worked at all; we should see a performance improvement, congrats @rasswanth-s for pointing this out.

Bad news:
* fixing this would mean that we should mangle with the randomness of UIDs or propagate the randomness when serializing.
 
Possible fixes:
* (more involved) - pass an optional random seed when serializing/deserializing, but this would mean changing many logic/function signatures, and we should roll back this when we merge with 0.8.
*  We can save the current random state, then serialize, then reset the random seed used by the uuid library to the previous, we should be able to get away with this, but it's so hacky it makes me cry
* remove the usage of uuids in our primitives - I think they were never useful in the first place, but it's slightly involved. I think this would kinda make sense, making us question if we ever needed sy.primitives in the first place.

**Comment by madhavajay** [comment]
@tudorcebere we want the quickest solution for 0.7 since its fixed in 0.8.

So right now, users still need to have the correct permission to save on mutation but the code will always compare and find the equality false therefore saving the self back to Redis. So this just means like 2 saves instead of one. If you agree that there is no security issues with this just some performance penalty perhaps we leave it?
