### ISSUE TITLE
Security: DS could maliciously become  Owner/Admin

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6977]
## Description
We have an initial setup process in PySyft ,in which we create the initial Owner and the credentials, 
At the client side we have .get_setup() method as a public method.
In the view of the Data Scientist when we access this method we are able to the `signing_key` of the  Owner itself
as a dictionary.

![Screenshot 2022-11-05 at 4 04 07 PM](https://user-images.githubusercontent.com/43314053/200115588-cee36296-0add-4a33-ad14-13cfd25fdf1b.png)

This allows a malicious Data Scientist or a guest admin access , to have `admin/owner`  access to all the queries.

## Example Scenario:
The following example , shows how the Data Scientist  could use the signing key to obtain `private` uploaded by the `DataOwner`

Since our code is public, the Data Scientist  has two advantages

- He could create custom Syft message with a particular id_at_location
- Sign it with the admin key

 1): Initially he is not able to access the data.
![Screenshot 2022-11-05 at 4 11 01 PM](https://user-images.githubusercontent.com/43314053/200115972-6390e84d-66be-446f-8542-6a45d9f7b580.png)

2) Custom GetObjectActionMessage Creation and retrieval of Data

![Screenshot 2022-11-05 at 4 12 13 PM](https://user-images.githubusercontent.com/43314053/200116049-cd5bc4a8-de69-4a3d-a5e0-ca5e37c5a3ed.png)

## Possible Solution:
Include a sanity check in get_setup method in node_setup_service, which allows only admins to get the setup table or delete signing key itself while sending the setup table, as the other metadata are public.

**Comment by madhavajay** [comment]
@rasswanth-s excellent find, this one is critically bad. It seems like this might be left over from when we were going to allow the `frontend` to setup a domain from scratch. I suspect we can just completely delete the `get_setup` methods in settings.py and domain_client.py.

**Comment by rasswanth-s** [comment]
Placeholder: Also calling 
domain.settings retrieves the setup values and the private key.

**Comment by madhavajay** [comment]
Nuke it from orbit.
