### ISSUE TITLE
DP Annotate accepts `int` for min / max but won't return it

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#6983]
## Description
In syft 0.7.0-beta.55 DP Annotate accepts `int` for min / max but won't return it.

```
x = np.array([1, 2, 3])
data = sy.Tensor(x).annotate_with_dp_metadata(max_val=3, min_val=1, data_subjects="a")
data.min_vals
```

<img width="1131" alt="Screen Shot 2022-11-07 at 3 34 03 pm" src="https://user-images.githubusercontent.com/2882739/200233696-0b7f3dfc-5526-4d1d-98eb-f7e4aec689a3.png">

**Comment by madhavajay** [comment]
This looks like its trying to `init` a Tensor that matches the type of the parent but in this case the `Scalar` values for `min_vals` the `init` function rejects it.

**Comment by shubham3121** [comment]
@madhavajay @IshanMi what do we want the return type to be here for min_vals and max_vals, Tensor or lazyrepeatarray: 

![Screenshot from 2022-11-07 18-12-32](https://user-images.githubusercontent.com/11032835/200313395-f3fd70e1-b773-4cd4-8e0c-d666d7b820bd.png)

Currently, in the code, we are trying to convert the min_vals and max_vals to Tensor (or the class the variable `data` represents).

**Comment by madhavajay** [comment]
@shubham3121 The code seems fine if the type is `np.ndarray` which is what a lazyrepeatarray is supposed to represent right? So maybe we just need a `NumpyLike` type which can also be `lazyrepeatarray`?
