### ISSUE TITLE
Fix Requests in PyGrid UI

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6984]
## Description
When a Data Scientist would like to view the result of the computation after the submitting a request through the python API, when we go to the frontend page to see the requests(after `refreshing` the page again), we get a random stack trace of error, the `functionality works` after closing it , but  it would be good to not have the error stack trace displayed on the frontend.

## Example Scenario: Submitting a Data Request
1.) Submitting Request through python api.
![Screenshot 2022-11-07 at 12 18 22 PM](https://user-images.githubusercontent.com/43314053/200243218-7a6876a0-c6df-486a-869d-c332d41c1440.png)

2.) Error in frontend page after refreshing the requests page.
![Screenshot 2022-11-07 at 12 13 49 PM](https://user-images.githubusercontent.com/43314053/200243307-595e185f-4475-4cf3-97aa-fea1933117e2.png)

## Note: 
This also happens for budget upgrade requests.

**Comment by tcp** [comment]
Yes :) Let's get it done.

**Comment by tcp** [comment]
@IonesioJunior can we prio this?

**Comment by IonesioJunior** [comment]
Sure!

**Comment by madhavajay** [comment]
The react error is actually unrelated and happens when we refresh but we can address it separately if we want to keep using react.
