### ISSUE TITLE
Docker Ports not open in dev mode.

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6987]
## Description
The docker  ports for seaweedfs, redis, postgres are not opened in development mode.

## How to Reproduce
Launch a domain in dev mode on the `current dev branch`
hagrid launch --dev
Run: 
./scripts/dev_tools.sh

Screenshots:
![Screenshot 2022-11-07 at 1 01 22 PM](https://user-images.githubusercontent.com/43314053/200251294-265de0a3-f547-4b1b-a38f-26528c4ce0e8.png)

## Expected Behavior
To be able to view the ports in devlopment mode.

**Comment by shubham3121** [comment]
We are not adding the docker-compose.dev.yml file when launching the containers.

![Screenshot from 2022-11-07 13-07-22](https://user-images.githubusercontent.com/11032835/200252343-616272e4-b76b-4d2f-892a-3495f567cc1a.png)

**Comment by shubham3121** [comment]
Also, this command is broken, as it runs health checks post printing the docker commands.
hagrid launch canada to docker:8082 --tag=latest --tail=false --dev --cmd=true
![Screenshot from 2022-11-07 13-09-45](https://user-images.githubusercontent.com/11032835/200252818-bee1f5a7-7e3c-4f54-a0c1-7159ef172de3.png)
