### ISSUE TITLE
Frontend: Partial Functionality Delete Function

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#6990]
## Description
In the frontend UI , in the users page, we provide a delete button, but it is non functional, maybe it is good idea to fix/remove the delete functionality from the Frontend UI

![Screenshot 2022-11-07 at 1 30 15 PM](https://user-images.githubusercontent.com/43314053/200256527-f0b8512d-8311-46fb-915d-39382bd666b6.png)

**Comment by madhavajay** [comment]
@tcp we can just remove this from the HTML unless you think it should work or theres a better way?

**Comment by tcp** [comment]
Let me see if I can get this working as expected -- if we need to do many backend changes, we drop this part.
