### ISSUE TITLE
Implement Default narrow Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#70]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, narrow() should return a new tensor. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by sakchhams** [comment]
I would like to aim for this. Seems doable, any algorithmic preferences?

**Comment by nishanthprakash** [comment]
I see that this issue has no update for 7+ days; I would like to pick it up if no one else is working on it now.

**Comment by nishanthprakash** [comment]
I have submitted PR #313, that resolves this. It would be great if this could be reviewed.
