### ISSUE TITLE
DPTensor ID Checks

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7012]
## Description
Currently we generate a random int to use in the `source` dict on GammaTensor. This allows us to easily work on a Tensor Object, filter, change etc and then to easily find its position in the children's dict of `source` parents and replace itself etc.

While its very unlikely we generate a random int that is the same as one that was already generated, its not impossible, so it might be worth writing a simple function which checks if a key is already taken and keeps generating until it creates a unique one.

![image](https://user-images.githubusercontent.com/2882739/200988074-4b6a1e64-1c6c-4ab5-9abe-5377fff94d47.png)

## Additional Context
This would apply to any `op` which assigns a DPTensor `int` id to the `source` dict. This is not the same thing as the `UID` id's in other parts of the system.

**Comment by Noob-can-Compile** [comment]
Hi @madhavajay, I am unable to find the above code. is this still open?
