### ISSUE TITLE
Small thing: let's move pointers to their own files

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#7019]
These files are really big - let's move the pointer classes to their own files:
- https://github.com/OpenMined/PySyft/blob/dev/packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py#L82
- https://github.com/OpenMined/PySyft/blob/dev/packages/syft/src/syft/core/tensor/autodp/phi_tensor.py

**Comment by ankitshaw** [comment]
Hi @iamtrask, I am new to open source contributions and would like to pick this issue.

**Comment by akalliokoski** [comment]
I would like to work on this issue on Thursday 2023-2-9. Discussed picking this issue with @madhavajay in Slack.

**Comment by akalliokoski** [comment]
There is a draft PR at https://github.com/OpenMined/PySyft/pull/7300. I will continue work on that again next week, latest on Friday. 
TODO:
* fix circular imports
* fix my local dev env to be able to run the tests

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
