### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by kangxiangping** [OpenMined/PySyft#7037]
## Question
Is the quick start tutorial incomplete?

## Further Information
I like the Quick Start tutorial a lot, but it seems that there is only a partial tutorial. Can the author upload all the tutorials? Thank you so much.

**Comment by madhavajay** [comment]
@kangxiangping did you run the cells? The `quickstart` command in the notebook gives you a list of other tutorials to download.

**Comment by madhavajay** [comment]
<img width="436" alt="Screen Shot 2022-11-14 at 2 19 46 pm" src="https://user-images.githubusercontent.com/2882739/201574443-71b80ae1-5d96-433e-b932-f396da6d41f4.png">

**Comment by kangxiangping** [comment]
> @kangxiangping did you run the cells? The `quickstart` command in the notebook gives you a list of other tutorials to download.

Yes! I've learned all these tutorials and run all the cells. This benefits me a lot, so I want to learn a tutorial on data-scientist, such as how to have domain nodes jointly train a model with federated learning.

**Comment by madhavajay** [comment]
@kangxiangping I am glad you got this working. The Docs team are working on more notebooks and when they are merged in they will be linked from the README and available in this notebook. 🙂

I will close this issue for now.

**Comment by kangxiangping** [comment]
> @kangxiangping I am glad you got this working. The Docs team are working on more notebooks and when they are merged in they will be linked from the README and available in this notebook. 🙂
> 
> I will close this issue for now.

OK! Thank you and your team for your hard work.
