### ISSUE TITLE
Fix DataSubjectLedger Mask

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7038]
## Description
The `DataSubjectLedger` has some issues currently. The code uses the sequential int index system which we should continue to use, but the code expects DataSubjectArray which contains `sets` of `strings`.

There are a few issues:
1) The ids are reindexed (0....n) based on the current Tensor's Data Subjects every time so they will overlap between operations and different data subjects, this should be resolved with this issue: https://github.com/OpenMined/PySyft/issues/7036

2) calculating the mask in `convert_dsa_to_index_array` for a given scalar position currently does not work with `np.isin`. 
Example:
```python
ids = [{1}, {1, 2}, {2}, {3}]
x = np.array(ids)
x
> array([{1}, {1, 2}, {2}, {3}], dtype=object)

np.isin(x, {1})
> array([ True, False, False, False])
```

The correct result would be True for index 1 as well since we want to match all situations where DataSubject A is in any Scalar position.

It seems we need the following:
    - irregular shaped np.ndarrays (hence the last dimension being set (or could be list) but not an additional tensor dimension as this would become very sparse at millions of data subjects
    - ability to test for membership in the final dimension quickly
Suggested solution:
i) change to ints
ii) use np.vectorize
iii) test `set` vs `list`
```python
def int_in_set(a, b):
    return a in b
ids = [{1}, {1, 2}, {2}, {3}]
vfunc = np.vectorize(int_in_set)
vfunc(1, ids)
> array([ True,  True, False, False])


# vs
def int_in_list(a, b):
    return a in b
    # or potentially, even though there might be a copy it might be really fast
    return np.isin(a, np.ndarray(b))

vfunc = np.vectorize(int_in_list)
vfunc(1, ids)
> array([ True,  True, False, False])
```

**Considerations**:, while `set` membership is quick, sets are larger. Additionally its possible that references from lists of lists might provide some additional benefits below. We should experiment with large collections of ints as sets or lists at the root node (or maybe even sparse np.arrays) to see how they perform and what sizes they use.

## Acceptance Criteria
Simple test cases of mixing PhiTensors need to be added such as:
1) Operations where dimensions are reduced and DataSubjectLedger values are correctly updated for all relevant DataSubjects
```python
ages = np.array([25, 35, 21, 19, 40, 55, 31, 18, 27, 33])
names = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
phi_tensor = sy.Tensor(ages).private(min_val=0, max_val=122, data_subjects=names)
phi_ptr = domain.datasets[2]["ages"]
phi_sum_ptr = phi_ptr.sum()
result = phi_sum_ptr.publish()
```

2) Operations where two different PhiTensor DataSubjects are mixed and published with different budgets to ensure filtering occurs and correctly blocks out source tensors as expected.
```python
import numpy as np
fred_nums = np.array([25, 35, 21, 19, 40, 55, 31, 18, 27, 33])
sally_nums = np.array([8, 11, 10, 50, 44, 32, 55, 29, 6, 1])
assert len(fred_nums) == len(sally_nums)
fred_tensor = sy.Tensor(fred_nums).private(min_val=0, max_val=122, data_subjects="fred")
sally_tensor = sy.Tensor(sally_nums).private(min_val=0, max_val=122, data_subjects="sally")

# ... upload

fred_nums_ptr = domain1.datasets[3]["fred_nums"]
sally_nums_ptr = domain1.datasets[4]["sally_nums"]
comb_ptr = fred_nums_ptr + sally_nums_ptr
op1 = comb_ptr * 2
op2 = op1.sum()
res = op2.publish(sigma=1.5)

# This results in the following epsilons:

# Full publish: epsilon_spend: 272736.8344262072
# Freds source data epsilon: 2659.3815902944493
# Sallys source data epsilon: 2484.649114063719
# test with > full publish and test with just enough to publish one DataSubject source.

3) Correct values are saved to the DataSubjectLedger for each `IndexedDataSubject` int.
```

**Comment by shubham3121** [comment]
Seems like `np.isin` is restricted to 1D 😢

**Comment by shubham3121** [comment]
Fixed here: #7103

**Comment by madhavajay** [comment]
Fixed by PR: https://github.com/OpenMined/PySyft/pull/7103

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
