### ISSUE TITLE
error in data.send function from Pytorch 

### ISSUE THREAD

**Issue by chinmaydas96** [OpenMined/PySyft#7047]
## Description
When I am sending the data to the virtual worker I got the following error. Also, I didn't find any latest implementation in Pytorch.

I am a beginner would be great if anyone guide me here.

## Screenshots
![Screenshot 2022-11-14 at 11 45 00 PM](https://user-images.githubusercontent.com/13569963/201735464-700ad496-1006-4332-ae01-57f6dc387abc.png)

## System Information
 - OS: [MacOS]
 - Language Version: [Python 3.9]

**Comment by gmuraru** [comment]
Hello @chinmaydas96.

Thank you for opening the issue.
Are you using the latest version of PySyft?

Looking at the code, the VirtualWorker it is something that I am not aware that we use anymore.

**Comment by madhavajay** [comment]
@chinmaydas96 yeah the VirtualMachine doesn't have the service try a `Domain`. I would highly recommend updating to `syft` 0.7. Install `hagrid` from the main README and use `hagrid quickstart` and follow the install wizard and tutorials.
