### ISSUE TITLE
DP Tensor Pointer apply op data_subject comparison

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7049]
## Description
Depending on the contents of `data_subject` the method `_apply_op` can fail during the comparison because the result is not `numpy`-like and therefore has no `.all()` attribute.

```python
if (self.data_subjects != other.data_subjects).all():  # type: ignore
    return getattr(self.gamma, op_str)(other.gamma)
```

Probably need something like this:
```python
res = self.data_subjects != other.data_subjects
if hasattr(res, "all"):
    if (self.data_subjects != other.data_subjects).all():  # type: ignore
        return getattr(self.gamma, op_str)(other.gamma)
else:
    if not res:
        return getattr(self.gamma, op_str)(other.gamma)
```

**Comment by teo-milea** [comment]
I think this should have been fixed by #7024. TLDR: just wrap the check everywhere in the codebase with a NumPy array. Can we close this?

**Comment by madhavajay** [comment]
@teo-milea won't this incur a copy to the CPU with numpy if it happens to be in jax or another tensor library on GPU?

**Comment by teo-milea** [comment]
That is a good question, but given that all these checks happen in `phi_tensor.py` on the server side, that shouldn't be an issue as we don't support GPU yet (or at least that is what I thought). If that is not the case, we can change it to something that prevents this, but my suspicion is that this will not be the only problem when adding GPU support.
