### ISSUE TITLE
Publish While Loop Variable Broken

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7050]
## Description
This PR has changed the behavior of the publish while loop and prevents it from working: https://github.com/OpenMined/PySyft/commit/02d6e83c98d3fd7bc61757c2ab4a15b5c7934f57#diff-3a545178990897379af8b2d29a78b4573397be7f1e84853b7e9f4fa4e57500e4

All references of `tensor` changed to `value` need to change back so that the line:
`tensor = tensor.swap_state(filtered_sourcetree)` can effect the while loop and 
`original_output = tensor.child` can exit with filtered data.

**Comment by teo-milea** [comment]
I modified all the occurrences of `value` but it does not solve the problem. To me, it seems that during the filtering, the epsilon computed for each leaf tensor is lower than the available budget so no filtering is happening. My initial guess is that maybe changing the code from recursive to iterative broke the filtering, but maybe there was a change in the way we compute the RDP parameters/privacy budget spent. Tomorrow I will delve deeper into the paper to debug that but if you have any insights let me know.

**Comment by teo-milea** [comment]
I have discussed this with @IshanMi at it seems like the filtering is working as "intended". We will review the budget computation for `0.8` and optimize the filtering with the new DSA. I have opened a PR that is adding just noise when the filtering fails, and I have also refactored that part of the code. It might not be compatible with full Jax execution as I am doing in-place filtering. but whenever we will be working on that I will make sure to fix it. I have also added a basic publish test, but I have no idea how to check execution on the worker container.

**Comment by madhavajay** [comment]
Are we sure this is not an issue. If you follow the output from the function backwards it appears that the value never gets mutated.

Here is where `value` gets set at the start of `publish`.
line 78: 
```python
if isinstance(tensor.child, FixedPrecisionTensor):
    # Incase SMPC is involved, there will be an FPT in the chain to account for
    value = tensor.child.decode()
else:
    value = tensor.child

while isinstance(value, PassthroughTensor):
    # TODO: Ask Rasswanth why this check is necessary
    # ATTENTION: we do the same unboxing below with root_child
    # is this still needed to be done twice?
    value = value.child
```

After that the variable never changes.
But inside `line 227: if has_budget:`

`line 228: original_output = value`
`line 268: return original_output + noise`

The part which mutates the filtered value is:
`line 370: tensor = tensor.swap_state(filtered_sourcetree)`

In the old code it used to have:
```
original_output = tensor.child
```

But since the final output is now from `value` not `tensor.child` it doesn't change.

Do we need to set `value = tensor.child` after `tensor = tensor.swap_state(filtered_sourcetree)`?

And, even if the mutation is happening somehow implicitly internally with `jax` could this be problematic for reading the code and future refactors?

**Comment by madhavajay** [comment]
Fixed by PR: https://github.com/OpenMined/PySyft/pull/7103

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
