### ISSUE TITLE
How to train a text classification model with duet in version 0.5.0

### ISSUE THREAD

**Issue by shashankc28** [OpenMined/PySyft#7053]
## Question
Hi I need to build a text classification model using 1-1 connection in pysyft. I have been using version 0.5.0 which works fine with structured data but in the case of text classification I am using torch text to create vocab and hence create tensors. in this scenario the the torch text version supported by 0.5.0 version is old and does not have call definition for create vocab function . due to this i am not able to create tensors. 
Is there any example/tutorial available for either 0.5.0 version or latest version to train a text classification model in a duet kind of scenario where we have 2 nodes only .

**Comment by madhavajay** [comment]
Hi @shashankc28

If you want to try to fix this yourself you can checkout the branch here:
https://github.com/OpenMined/pysyft/tree/syft_0.5.0

Then just take a look at the `torch` code and enable any additional methods you might need.

Unfortunately we can't support 0.5 anymore.
