### ISSUE TITLE
Merge shubhams code cleanup

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7059]
## Description
[Shubham's Code Cleanup 2 #6256](https://github.com/OpenMined/PySyft/pull/6256/files)

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
