### ISSUE TITLE
Refactor Metadata Storage & Data Models without SQL

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7066]
## Description
We want to refactor our end to end data modelling including removing multiple steps between Data Model definition, serialization, services and RPC.

The first step here is to try changing to a more document style model.
PRs here:
https://github.com/OpenMined/PySyft/pull/6696
https://github.com/OpenMined/PySyft/pull/6706
https://github.com/OpenMined/PySyft/pull/6707
https://github.com/OpenMined/PySyft/pull/6719
https://github.com/OpenMined/PySyft/pull/6721

Design Docs are here:
https://www.notion.so/openmined/SYEP-0006-End-to-End-Data-Modelling-685857193619408fb459a7e4d27fd175

**Comment by rasswanth-s** [comment]
Closing the issues, as the above PR's are merged.
