### ISSUE TITLE
Fix flakey bugs in CI

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7072]
## Description
A number of tests flap in CI and are likely to be related to race conditions or other timeout  issues when using external services like pypi packages etc.

It would be great to remove these issues as they create a distracting testing environment.

Work started here:
https://github.com/OpenMined/PySyft/pull/6822

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
