### ISSUE TITLE
Make Syft Tensor annotation process more beginner-friendly

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7075]
## Description
Improve interface to `DP Tensor` `.private` with better naming and docstrings.

Work has begun here:
https://github.com/OpenMined/PySyft/pull/6912

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
