### ISSUE TITLE
Fix ast.callable circular import

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7077]
## Description
Solve the circular import issue created while importing lib module.

Work started here:
https://github.com/OpenMined/PySyft/pull/7031

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
