### ISSUE TITLE
DS could get the result of MPC computations without request/response.

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#7082]
## Description
Data Scientist could get the result of SMPC computations without a request/response
```python
import syft as sy
import numpy as np
alice = sy.login(email="info@openmined.org",password="changethis", port=8081)
bob = sy.login(email="info@openmined.org",password="changethis",port=8082)
# create a data scientist account using alice and bob client
skywalker_alice = sy.login(port=8081, email="rey@skywalker.net", password="jakku")
skywalker_bob = sy.login(port=8082, email="rey@skywalker.net", password="jakku")
data = sy.Tensor(np.array([1,2,3]))
data.send(alice)
data.send(bob)
alice_ptr = skywalker_alice.store[-1]
bob_ptr = skywalker_bob.store[-1]
res = alice_ptr+bob_ptr # SMPC computation.
res.get() 
```
.get() should fail, as the Data Scientist should not get the result of intermediate computation in SMPC without a request/response.

Solution:
`remove DS verify_key in przs_action.py`

**Comment by iamtrask** [comment]
Yikes. Do we know how big of a fix this would be?

**Comment by madhavajay** [comment]
@rasswanth-s what can we do to split this into two tasks.
1) prevent theft of data using this code path for non SMPC situations
2) fix this in SMPC itself

The goal would be to ship the first in 0.7 and discuss the second for later prioritization

**Comment by rasswanth-s** [comment]
I have solved it for both scenario's , I have it in the branch
https://github.com/OpenMined/PySyft/tree/padawan_smpc, 
will create a PR for it soon.
