### ISSUE TITLE
Why there is no examples in the new version like 0.6.0?

### ISSUE THREAD

**Issue by superjdz** [OpenMined/PySyft#7101]
Why there is no examples in the new version like 0.6.0?

**Comment by madhavajay** [comment]
@superjdz We haven't released it yet. We are currently finishing off all bugs relating to the 0.7 release. There are a number of notebooks being worked on by the docs team and course3 notebooks are tested against 0.7 in CI.

**Comment by madhavajay** [comment]
@superjdz we now have notebooks which run through CI here:
https://github.com/OpenMined/PySyft/tree/dev/notebooks

New release coming shortly with more blog post tutorials.
