### ISSUE TITLE
Styling of hagrid launch message

### ISSUE THREAD

**Issue by kiendang** [OpenMined/PySyft#7114]
Just an UI thing. The 🚨 and red `hagrid logs test_domain` text gives the notion of errors/something gone wrong that requires actions. Should we change them to something else?

<img width="545" alt="Screenshot 2022-11-23 at 8 53 44 PM" src="https://user-images.githubusercontent.com/6521018/203892175-9208996f-bafd-48e8-bc1b-1e07daf3c12e.png">

**Comment by madhavajay** [comment]
Yes, I agree, but lets circle back after 0.7.
