### ISSUE TITLE
Budget update throwing 500 on UI

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#7117]
## Description
Not able to update the privacy budget of a user from the UI.
This was working in the previous beta versions.

## How to Reproduce
1. Log into the UI with admin credentials
2. Select a user
3. Click on adjust budget
4. update the budget value and click save

## Expected Behavior
User budget is updated successfully.

## Screenshots
![Screenshot from 2022-11-25 16-41-03](https://user-images.githubusercontent.com/11032835/203979609-a59eabd4-e58c-49a1-9843-23170c7874e2.png)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
@tcp do you know if this will be difficult or is it related to a common problem with PyGrid UI in 0.7?

**Comment by tcp-cetrez** [comment]
@madhavajay hopefully with https://github.com/OpenMined/PySyft/pull/7112 we'll get it over the hump

**Comment by tcp** [comment]
@madhavajay hopefully with https://github.com/OpenMined/PySyft/pull/7112 we'll get it over the hump

**Comment by shubham3121** [comment]
@tcp @madhavajay I have found the issue, it was a minor fix on the backend API itself. Created a fix here:
https://github.com/OpenMined/PySyft/pull/7127
