### ISSUE TITLE
In hagrid boolean arguments (e.g. `--cmd=True`) should be flags (just `--cmd`) instead

### ISSUE THREAD

**Issue by kiendang** [OpenMined/PySyft#7141]
## Description
This has always been a gripe for me when working with hagrid. This and #7140 seem like small things but the main purpose of is to reduce friction between users and the entire Syft stack and would benefit from a smoother dev ex.

Boolean options like `--cmd=True`, `--tail=True`, `--headless=True` should have just been flags, *i.e.* `--cmd`, `--tail` and `--headless`. Reasons:

1. This is how most cli tools work.
2. `--cmd` achieves the same functionality and is also much shorter. Plus with `--cmd=True` users not familiar with the tools or those only use it once in a while will have a hard time remembering whether it's `--cmd`, `--cmd=True`, or `--cmd=true`, how about `--cmd=1`?
3. In hagrid there already exist other flags like `--silent`, `--tls`, `--test`, `--dev`, so this is both against cli best practice and inconsistent within hagrid itself.

## Are you interested in working on this improvement yourself?
Yes

@iamtrask gave his 👌 on fixing this and #7140. We're still deciding on the timeline. I know this is not originally planned as required for 0.7, and hagrid version is separated from syft, but with a new syft release a lot of folks are gonna use hagrid, some for the first time, so would be quite appropriate to make the changes available on 0.7 release.

My proposal is that I will work on these for the next week. If it takes more than that we can reassess.

## Additional Context
Add any other context or screenshots.

**Comment by madhavajay** [comment]
Totally agree. I think its worth doing some planning around rebuilding hagrid from scratch so that its much cleaner and more consistent and modular.

I think a new python cli code base could be started and the functionality we want ported over pretty quickly once we include the desired capabilities.

Lets discuss this post 0.7.
