### ISSUE TITLE
Refreshing PyGrid UI causes Hydration Error

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#7155]
## Description
If a user refreshes the Requests page it can cause a hydration error.
<img src="https://user-images.githubusercontent.com/43314053/200243307-595e185f-4475-4cf3-97aa-fea1933117e2.png" />

**Comment by madhavajay** [comment]
@tcp is this hard to fix, seems unrelated to the actual backend.

**Comment by rasswanth-s** [comment]
I am closing long standing Github Issues related to older PySyft versions (<=0.7) or  are not aligned in the current roadmap.Kindly re-open the issue if the needs to be addressed or is still relevant.
