### ISSUE TITLE
Install Wizard is broken

### ISSUE THREAD

**Issue by shubham3121** [OpenMined/PySyft#7184]
## Description
A clear and concise description of the bug.

## How to Reproduce
- hagrid quickstart
- run check_hagrid

![Screenshot from 2022-12-16 21-38-09](https://user-images.githubusercontent.com/11032835/208353270-8f23aee1-cb06-454e-8b45-c4ddaf68655d.png)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by madhavajay** [comment]
Oooff @shubham3121 good catch. I guess we need to add this to a test?
