### ISSUE TITLE
 AttributeError: module ‘syft’ has no attribute ‘FederatedDataLoader’

### ISSUE THREAD

**Issue by omerfaruktuna** [OpenMined/PySyft#7188]
Hi,

I am trying to use syft for federated learning.
I used below commands to import syft and define the virtual machines.

import syft as sy

alice = sy.VirtualMachine(name="alice")
bob = sy.VirtualMachine(name= "bob")
ken= sy.VirtualMachine(name="ken")
ryu = sy.VirtualMachine(name= "ryu")
tim= sy.VirtualMachine(name="tim")

I have a dateset named “train”.

When I try to define my trainloader, I got an error as below:

train_loader_1 = sy.FederatedDataLoader(train.federate((bob, alice, ken, ryu , tim)),  batch_size=120, shuffle=False)

**AttributeError: module 'syft' has no attribute 'FederatedDataLoader**

Would you please help me on how to define my federateddataloader?

Note:

torch version: 1.10.0+cpu
syft version 0.6.0

Best wishes,
Ömer

**Comment by omerfaruktuna** [comment]
The question/problem is still open. I would really appreciate if you can comment on how to fix this issue.

Best wishes,

**Comment by BalajiAI** [comment]
Your Syft version is 0.6.0. I'm not sure whether FederatedDataLoader is present in your version. Which tutorial are you following?

**Comment by skhand17** [comment]
Hi,
Please let me know if this issue is resolved or not. I am facing similar issue : 
federated_train_loader = syft.FederatedDataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ]))
    .federate((CS1, CS2)),
    batch_size=args['batch_size'], shuffle=True)

This is the error I am seeing : 
AttributeError: module 'syft' has no attribute 'FederatedDataLoader'

**Comment by madhavajay** [comment]
@omerfaruktuna the code you have is for `0.2.x` so it won't work in other versions.
Adding FL primitives back is on our roadmap.
