### ISSUE TITLE
syft 0.7 Simple SMPC You do not have permission to .get()

### ISSUE THREAD

**Issue by avdvg** [OpenMined/PySyft#7205]
## Description
Dear developer, I ran the official Simple SMPC code in syft 0.7, and the following error occurred. It seems that I do not have the right to view the data. How can I solve this problem to enable me to view the data after the operation.

========================================================
MPCTensor
	<TensorPointer -> domain1:051ae49574cf434da8d40843d9a16910, status=Ready>
	<TensorPointer -> domain2:b027a5e774d94ce588b4de31faa00458, status=Ready>
	<TensorPointer -> elegant_ng:326808d32f1f42a78222d2120f98a108, status=Ready>
	<TensorPointer -> great_hochreiter:138dc4cda8c54376bb1a0235e1b07b96, status=Ready>

========================================================
AuthorizationException                    Traceback (most recent call last)
Cell In[14], line 1
----> 1 shares_locally_print = "\n".join([str(share.get_copy()) for share in mpc_tensor.child])
      2 print(f"Shares values\n{shares_locally_print}")

Cell In[14], line 1, in <listcomp>(.0)
----> 1 shares_locally_print = "\n".join([str(share.get_copy()) for share in mpc_tensor.child])
      2 print(f"Shares values\n{shares_locally_print}")

File ~/anaconda3/envs/syft/lib/python3.8/site-packages/syft/core/pointer/pointer.py:333, in Pointer.get_copy(self, request_block, timeout_secs, reason, verbose)
    320 def get_copy(
    321     self,
    322     request_block: bool = False,
   (...)
    325     verbose: bool = False,
    326 ) -> Optional[StorableObject]:
    327     """Method to download a remote object from a pointer object if you have the right
    328     permissions. Optionally can block while waiting for approval.
    329 
    330     :return: returns the downloaded data
    331     :rtype: Optional[StorableObject]
    332     """
--> 333     return self.get(
    334         request_block=request_block,
    335         timeout_secs=timeout_secs,
    336         reason=reason,
    337         delete_obj=False,
    338         verbose=verbose,
    339     )

File ~/anaconda3/envs/syft/lib/python3.8/site-packages/syft/core/pointer/pointer.py:454, in Pointer.get(self, request_block, timeout_secs, reason, delete_obj, verbose, proxy_only)
    449     raise ReferenceError(
    450         "Object has already been deleted. This pointer is exhausted"
    451     )
    453 if not request_block:
--> 454     result = self._get(
    455         delete_obj=delete_obj,
    456         verbose=verbose,
    457         proxy_only=proxy_only,
    458         timeout_secs=timeout_secs,
    459     )
    460 else:
    461     if timeout_secs is None:

File ~/anaconda3/envs/syft/lib/python3.8/site-packages/syft/core/pointer/pointer.py:249, in Pointer._get(self, delete_obj, verbose, proxy_only, timeout_secs)
    247 while is_processing_pointer and future_time > time.time():
    248     try:
--> 249         obj = self.client.send_immediate_msg_with_reply(
    250             msg=obj_msg, timeout=timeout_secs, verbose=True
    251         )
    253         # If we reached here it's because we didn't have any failure,
    254         # so we were able to retrieve the pointer successfully.
    255         # So it isn't a processing pointer anymore and we can exit the while loop.
    256         # without wait the timeout
    257         is_processing_pointer = False

File ~/anaconda3/envs/syft/lib/python3.8/site-packages/syft/core/node/common/client.py:260, in Client.send_immediate_msg_with_reply(self, msg, timeout, return_signed, route_index, verbose)
    258     exception = exception_msg.exception_type(exception_msg.exception_msg)
    259     error(str(exception))
--> 260     traceback_and_raise(exception, verbose=verbose)
    261 else:
    262     if return_signed:

File ~/anaconda3/envs/syft/lib/python3.8/site-packages/syft/logger.py:70, in traceback_and_raise(e, verbose)
     68 if not issubclass(type(e), Exception):
     69     e = Exception(e)
---> 70 raise e

AuthorizationException: You do not have permission to .get() Object with ID: <UID: 326808d32f1f42a78222d2120f98a108> on node elegant_ng Please submit a request.

**Comment by rasswanth-s** [comment]
Hello @avdvg , could you share the snippet of the code, which produced this error ?
On the Error part, you would have to submit a request on the MPCTensor to view the  result.
assume `mpc_tensor` was the resultant variable
We would have to call
mpc_tensor.request(reason="Input a valid reason to view the result of the computation")

This request would then be approved by the Data Owner

**Comment by avdvg** [comment]
> Hello @avdvg , could you share the snippet of the code, which produced this error ? On the Error part, you would have to submit a request on the MPCTensor to view the result. assume `mpc_tensor` was the resultant variable We would have to call mpc_tensor.request(reason="Input a valid reason to view the result of the computation")
> 
> This request would then be approved by the Data Owner

thanks @rasswanth-s, when i run "print(f"Reconstruct\n{mpc_tensor.reconstruct()}")" producted that error:

the code is:

import syft as sy
import torch
import numpy as np
from syft.core.tensor.smpc.mpc_tensor import MPCTensor
sy.logger.remove()

ravenclaw = sy.login(email="122@openmined.org", password="122", port=8080)
(..... 4 domains)

parties = [gryffindor, slytherin, hufflepuff, ravenclaw]
value_secret = gryffindor.syft.core.tensor.tensor.Tensor(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.int64))
mpc_tensor = MPCTensor(secret=value_secret, shape=(2,5), parties=parties)
print(f"Reconstruct\n{mpc_tensor.reconstruct()}") 

i don't know how to read the mpc_tensor data for data scientist, we look forward to your reply!

**Comment by avdvg** [comment]
> Hello @avdvg , could you share the snippet of the code, which produced this error ? On the Error part, you would have to submit a request on the MPCTensor to view the result. assume `mpc_tensor` was the resultant variable We would have to call mpc_tensor.request(reason="Input a valid reason to view the result of the computation")
> 
> This request would then be approved by the Data Owner

thanks @rasswanth-s, when i run "print(f"Reconstruct\n{mpc_tensor.reconstruct()}")" producted that error:

the code is:

import syft as sy
import torch
import numpy as np
from syft.core.tensor.smpc.mpc_tensor import MPCTensor
sy.logger.remove()

ravenclaw = sy.login(email="122@openmined.org", password="122", port=8080)
(..... 4 domains)

parties = [gryffindor, slytherin, hufflepuff, ravenclaw]
value_secret = gryffindor.syft.core.tensor.tensor.Tensor(np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.int64))
mpc_tensor = MPCTensor(secret=value_secret, shape=(2,5), parties=parties)
print(f"Reconstruct\n{mpc_tensor.reconstruct()}") 

i don't know how to read the mpc_tensor data for data scientist, we look forward to your reply!

**Comment by avdvg** [comment]
> Hello @avdvg , could you share the snippet of the code, which produced this error ? On the Error part, you would have to submit a request on the MPCTensor to view the result. assume `mpc_tensor` was the resultant variable We would have to call mpc_tensor.request(reason="Input a valid reason to view the result of the computation")
> 
> This request would then be approved by the Data Owner

I call mpc_tensor.request(reason="Input a valid reason to view the result of the computation"). Then i logged in to the administrator, passed the request, and successfully printed the data. Thank you very much for your help.
