### ISSUE TITLE
syft data request

### ISSUE THREAD

**Issue by avdvg** [OpenMined/PySyft#7212]
Dear developer, as a data scientist, I want to apply for using the data in the domain, so I sent a use request and wanted to obtain the data in the domain, but the administrator did not receive the data request. What is the reason.

My code is:
import syft
zha = syft.login(email=" 123@163.com ", password="123dw", port=8083)
imports_ data = zha.datasets[1]["imports"]
imports_ data.request(reason="I really need to see this")
print(imports_data.get())

Result of error report:
AuthorizationException: You do not have permission to .get() Object with ID: <UID: d61f6dd31a3c4557b0e6787b4e937688> on node great_ hochreiter Please submit a request.

Please note that in the pygrid ui interface, as an administrator, I do not see the request information.

**Comment by madhavajay** [comment]
@avdvg you have to wait until the request is approved before you can run `.get`. Try going through these examples from start to finish:
https://github.com/OpenMined/PySyft/tree/dev/notebooks/api/0.8
