### ISSUE TITLE
Uploading data to a domain server

### ISSUE THREAD

**Issue by AndreMPCosta** [OpenMined/PySyft#7271]
## Description
I'm following this guide: [https://openmined.github.io/PySyft/guides/data-owner/01-upload-data.html](url)

## How to Reproduce
```python
import syft as sy

dataset = None
domain_client = None

try:
    domain_client = sy.login(
        port=8081,
        email="info@openmined.org",
        password="changethis"
    )
except (Exception,) as e:
    print("Unable to login. Please check your domain is up with `!hagrid check localhost:8081 --timeout=120`")

try:
    import pandas as pd

    data = {'ID': ['011', '015', '022', '034'],
            'Age': [40, 39, 9, 8]}

    dataset = pd.DataFrame(data)
    print(dataset.head())
except (Exception,):
    print("Install the latest version of Pandas using the command: !pip install pandas")

if dataset is not None:
    data_subjects = sy.DataSubjectArray.from_objs(dataset["ID"])

    age_data = sy.Tensor(dataset["Age"]).annotate_with_dp_metadata(
        lower_bound=0, upper_bound=100, data_subject=data_subjects
    )

    domain_client.load_dataset(
        name="Family_Age_Dataset",
        assets={
            "Age_Data": age_data,
        },
        description="Our dataset contains the Ages of our four Family members with unique ID's. There are 2 columns "
                    "and 4 rows in our dataset."
    )


```

## Expected Behavior
The dataset should be uploaded to the domain server, instead:

`Loading dataset... uploading...🚀                        Traceback (most recent call last):
  File "/Users/andrecosta/demo-syft.py", line 34, in <module>
    domain_client.load_dataset(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/node/domain_client.py", line 729, in load_dataset
    proxy_obj = upload_to_s3_using_presigned(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/node/common/util.py", line 188, in upload_to_s3_using_presigned
    binary_dataset: bytes = serialize(data, to_bytes=True)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/common/serde/serialize.py", line 77, in _serialize
    return validate_type(is_serializable._object2bytes(), bytes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/tensor/tensor.py", line 635, in _object2bytes
    chunk_bytes(serialize(self.child, to_bytes=True), "child", tensor_msg)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/common/serde/serialize.py", line 77, in _serialize
    return validate_type(is_serializable._object2bytes(), bytes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/tensor/autodp/phi_tensor.py", line 3957, in _object2bytes
    pt_msg.dataSubject = serialize(dstonumpyutf8(self.data_subject), to_bytes=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/syft/core/adp/data_subject.py", line 199, in dstonumpyutf8
    name_bytes = data_subject.to_string().encode("utf-8")
AttributeError: 'numpy.ndarray' object has no attribute 'to_string'. Did you mean: 'tostring'?`

Evaluating the data_subject.py file:
```python
def dstonumpyutf8(data_subject: DataSubject) -> ArrayLike:
    name_bytes = data_subject.to_string().encode("utf-8")
    np_bytes = np.frombuffer(name_bytes, dtype=np.uint8).astype(np.uint64)
    return np_bytes
```

It receives a numpy.ndarray.
to_string method is a method from the class DataSubject, which does not exist on a numpy.ndarray.

```python
def to_string(self) -> str:
    return f"{self.name}"
```

Another note, on this line:
```python
age_data = sy.Tensor(dataset["Age"]).annotate_with_dp_metadata(
    lower_bound=0, upper_bound=100, data_subject=data_subjects
)
```
After inspecting the annotate_with_dp_metadata, it receives **data_subject** keyword argument, not **data_subjects** as implied in the guide. I don't know if the behavior of the method also changed, since the keyword is now singular, instead of plural.

## System Information
 - OS: macOS
 - OS Version: Ventura 13.1
 - Language Version: Python 3.10

**Comment by AndreMPCosta** [comment]
Workaround:

```python
def dstonumpyutf8(data_subject: DataSubject | np.ndarray) -> ArrayLike:
    name_bytes = data_subject.astype('U13').tobytes()
    np_bytes = np.frombuffer(name_bytes, dtype=np.uint8).astype(np.uint64)
    return np_bytes
```

**Comment by madhavajay** [comment]
@AndreMPCosta, yes the API changed slightly right before release and we haven't been able to update the docs. Sorry about this, i'm glad you were able to fix it. We have a small patch for `0.7` coming and will try to fix this up at the same time.

**Comment by TwsThomas** [comment]
Hello, 

I have the same issue when following the guide [https://openmined.github.io/PySyft/guides/data-owner/01-upload-data.html](https://github.com/OpenMined/PySyft/issues/url)

However, I don't understand how I could use the workaround. Should I need to re-build pysyft from source with this modification? And how could I do that?

**Comment by AndreMPCosta** [comment]
@TwsThomas You can go to the folder where Syft is located (if you are using hagrid quickstart you should look for the .hagrid folder) and change the function that I mentioned. 

For example in Windows:

You should go to 'C:\Users\<youuserhere>\.hagrid\quickstart\.venv\Lib\site-packages\syft\core\adp\data_subject.py'

And modify that file.

**Comment by madhavajay** [comment]
The DataSubject interface changed before the final release of 0.7. Thanks for the above solutions. I will close this for now.
