### ISSUE TITLE
Implement Default neg Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#73]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, neg() should return a new tensor, while neg_() should operate inline. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by Ujjwal-9** [comment]
hey trask, pls review PR #218. I have implemented neg(), neg_() and tanh() function in it.

**Comment by Ujjwal-9** [comment]
hey trask close this issue. I have implemented neg() ,neg_() in #218

**Comment by siarez** [comment]
@Ujjwal-9 It looks like you haven't written the tests for these, Or am I missing something?

**Comment by Ujjwal-9** [comment]
@siarez, yes I haven't yet pushed tests but I will do it once my exams are over.

**Comment by siarez** [comment]
@Ujjwal-9 No worries, Thanks! :)
