### ISSUE TITLE
Can't open Jupyter Notebook after installing PySyft in the same conda environment

### ISSUE THREAD

**Issue by lokeaichirou** [OpenMined/PySyft#7307]
## Description
Can't open Jupyter Notebook after installing PySyft in the same conda environment;  500 Internal Server Error occurs.

## System Information
 - OS: MacOS
 - OS Version: MacOS Ventura 13.2
 - Language Version: Python 3.9
 - Package Manager Version: conda 4.12.0
 - Browser (if applicable): safari
 - Browser Version (if applicable):

**Comment by madhavajay** [comment]
@lokeaichirou that usually happens when theres a conflict with which jupyter gets launched, can you try to deactivate and reactivate your virtualenv?
