### ISSUE TITLE
TypeError: annotate_with_dp_metadata() got an unexpected keyword argument 'data_subjects' 

### ISSUE THREAD

**Issue by qxzhou1010** [OpenMined/PySyft#7426]
## Description
I am leaning the **Uploading Private Data to a Domain Server** note. When I run this cell :

```
# run this cell
data_subjects = sy.DataSubjectArray.from_objs(dataset["ID"])
print(data_subjects)
age_data = sy.Tensor(dataset["Age"]).annotate_with_dp_metadata(
    lower_bound=0, upper_bound=100, data_subjects=data_subjects
) 
```
I encountered this error: 
`TypeError: annotate_with_dp_metadata() got an unexpected keyword argument 'data_subjects'
`
How to fix this problem?
## System Information
 - OS: iOS
 - OS Version: 11.6 
 - Language Version: Python 3.9.16
 - Package Manager Version: conda 4.12.0
 - Browser (if applicable): Google Chrome
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by kennethbruskiewicz** [comment]
Workaround: remove the reference to kwargs and just use the positional arguments.
```python
age_data = sy.Tensor(dataset["Age"]).annotate_with_dp_metadata(
   0, 100, data_subjects
)
```

**Comment by madhavajay** [comment]
@kennethbruskiewicz thank you. Yes @qxzhou1010 the kwarg name was changed at one point.
