### ISSUE TITLE
In syft==0.5.0 TorchHook module error

### ISSUE THREAD

**Issue by Nazmul92** [OpenMined/PySyft#7431]
## Description
I install syft==0.5.0 in anaconda. Installed without any issues and import is ok but when I try to create virtual worker using this command:

hook = sy.TorchHook(torch)

It shows TorchHook module error. Please advice how can fix.

**Comment by ShivaniKolanu** [comment]
Is this issue resolved as I'm also facing the same issue?

**Comment by Nazmul92** [comment]
@ShivaniKolanu not yet. How did you solve? I'm focusing on duet without creating virtual workers.

**Comment by Nazmul92** [comment]
Not yet.

**Comment by ShivaniKolanu** [comment]
I was not able to solve.. Can you please share if something works for you.
And do you know if what was the syft version they used when they created the the tutorial in the below link?
https://github.com/OpenMined/PySyft/blob/c4cba6a47500db5d0d19393b8aa3ad2df6a55d99/examples/tutorials/advanced/Split%20Neural%20Network/Tutorial%201%20-%20SplitNN%20Introduction.ipynb

**Comment by madhavajay** [comment]
`TorchHook` is from `syft~=0.2`.
