### ISSUE TITLE
What privacy enhancing techniques are included in PySyft? 

### ISSUE THREAD

**Issue by qxzhou1010** [OpenMined/PySyft#7437]
## Question
I'm currently learning PySyft. I've done all the courses in tutorials. 
- My question is, what **privacy enhancing techniques** are included in PySyft? In the tutorials, I only saw **differential privacy**. 
- Are there any other privacy-enhancing techniques included in PySyft? For example, Secure Multi-Party Computation(**MPC**) and Homomorphic Encryption(**HE)**.

**Comment by madhavajay** [comment]
@qxzhou1010 We support SMPC in several versions of Syft and now Secure Enclaves. If you are interested in discussing other PET capabilities please join our Slack channel and one of our Input or Output privacy experts will be happy to talk to you.

**Comment by madhavajay** [comment]
Closing as there was no response.
