### ISSUE TITLE
TorchHook not supported in last version of python

### ISSUE THREAD

**Issue by nwadheralblihed** [OpenMined/PySyft#7438]
## Description
Last week I am working with syft==0.2.9 and it was working great!
but this week when I tried to install syft==0.2.9 i have this error "ERROR: Could not find a version that satisfies the requirement torchvision~=0.5.0 (from syft) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1) ERROR: No matching distribution found for torchvision~=0.5.0"

Then when importing the syft library it was "There is no module named 'syft'"

I need to work with TorchHook in federated learning by PyTorch

I use Google Colab. Also I tried my code in Jypter and Kaggle, and all showed the same error

## System Information
 - OS: [iOS, Cloud environment]
 - Language Version: [Python 3.9.16, Torch 1.13.1+cu116]
 - Browser (if applicable): [e.g. Google Chrome]

**Comment by ShivaniKolanu** [comment]
is this issue resolved? I'm also having the same issue. can you please tell me if you solved?

**Comment by nwadheralblihed** [comment]
> not yet

**Comment by nwadheralblihed** [comment]
> 

> not yet

**Comment by madhavajay** [comment]
@nwadheralblihed this will be to do with upstream dependencies not us, we don't control what versions of other libraries are available for upstream dependencies.

If you force install an older torch then it should work or you could fork the `0.2.x` code and change the torch version there yourself. 

Unfortunately `0.2.x` is no longer supported by us.
