### ISSUE TITLE
Failed to connect to network VPN: Can't find network node opengrid_070_beta in the `03-join-network` notebook 

### ISSUE THREAD

**Issue by kennethbruskiewicz** [OpenMined/PySyft#7447]
## Description

I have been having trouble with completing the recommended tutorial notebooks. Right now I am stuck on `03-join-network` notebook. When I try to run `domain_client.apply_to_network(network_client)`, it fails to connect. Furthermore, the network version seems to default to the beta release. This is true if I try both the stable release and previous beta release for PySyft. The API calls also seem to be inconsistent (`/v1/new/metadata` not available locally, `api/v1/` not available on the targeted remote).

## How to Reproduce
1. Have either `syft==0.7.0` or `syft==0.7.0b62` installed with Python 3.9.
2. Run all the steps in the quickstart notebooks up to `03-join-network` successfully (including data upload, create new user, login with new password... not changing the domain name).
3. Attempt to apply the domain to the network.
4. Notice the mismatch between the network version and node version and environment versions, and notice that the api endpoints aren't avaialble. 

## Expected Behavior
The tutorial notebooks can be evaluated completely without errors.

## Screenshots

![debug](https://user-images.githubusercontent.com/955221/226761759-b2714463-4313-47c6-9b16-4c33446f70e0.png)

## System Information
 - OS: NixOS
 - OS Version: 22.05
 - Language Version: Python 3.9
 - Package Manager Version: Conda
 - Browser (if applicable): Chromium

**Comment by madhavajay** [comment]
We will be launching new 0.8+ servers with CD soon so there won't be these manually deployed out of date network servers.
