### ISSUE TITLE
Unable to install syft==0.2.9, and no module torchook found in latest version, there is no dcoumentation regarding how to create virtual workers

### ISSUE THREAD

**Issue by Lagstill** [OpenMined/PySyft#7454]
## Description
Unable to install syft==0.2.9, and no module torchook found in latest version, there is no dcoumentation regarding how to create virtual workers.

## How to Reproduce
1. Did install python==3.8
2. !sudo update-alternatives --config python3
3. !sudo apt-get install python3-pip
4. !pip install syft==0.2.9 -f https://download.pytorch.org/whl/torch_stable.html --user
5. Then got the below error both in colab and in kaggle

## Expected Behavior
1. Torch hook can be used only under version 0.2.9, but it either gives torch/torchvision module not found 
2. For the latest version there is no clear documentation indicating how to create virtual workers.
3. Kernel crashes for version 0.2.9
4. Needed proper installation for each notebook examples and do it locally.

## Screenshots
![image](https://user-images.githubusercontent.com/89288089/227079836-a8ea4c0f-a34e-43a1-bf69-24b9c98d28a2.png)
![image](https://user-images.githubusercontent.com/89288089/227080033-aec556bf-ee05-4fcd-90cc-42612a8a709a.png)

## System Information
 - Colab
 - python 3.8
 - syft 0.2.9

## Additional Context
Please add proper installation or direction guide, there are no proper resources.

**Comment by Lagstill** [comment]
Also in the latest version , following packages are not found:
from syft.core.plan.plan_builder import ROOT_CLIENT
from syft.core.plan.plan_builder import make_plan
from syft.federated.model_centric_fl_client import ModelCentricFLClient
from syft.lib.python.int import Int
from syft.lib.python.list import List
from syft.proto.core.plan.plan_pb2 import Plan as PlanPB
from syft.proto.lib.python.list_pb2 import List as ListPB

**Comment by Lagstill** [comment]
With latest syft version:

![image](https://user-images.githubusercontent.com/89288089/227083859-1c9966f7-9351-4a89-834e-3883ff10abf1.png)

**Comment by madhavajay** [comment]
@Lagstill `0.2.x` is no longer supported.
