### ISSUE TITLE
PATE can only use in version 0.2.9 but require torch=1.4.0

### ISSUE THREAD

**Issue by JadeBYG** [OpenMined/PySyft#7458]
## Description
I also read https://blog.openmined.org/maintaining-privacy-in-medical-data-with-differential-privacy/ and want to have a try. I use google colab and install version 0.2.9 but it told me 'Could not find a version that satisfies the requirement torch~=1.4.0'

## How to Reproduce
1. Go to 'Google colab'
2. Install syft with '!pip install syft==0.2.9'
3. See error
After it ran to Downloading importlib_resources-1.5.0-py2.py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement torch~=1.4.0 (from syft) (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch~=1.4.0

## Expected Behavior
1. how can I use 0.2.9 in google colab
2. is new version of syft can use PATE

## Screenshots
Sorry for that I still don't know how to insert images in GitHub issues.

## System Information
 - Environment: Google Colab
 - Language Version: Python 3.9, PyTorch 1.13.1+cuda11.6
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): Google Chrome

**Comment by madhavajay** [comment]
@JadeBYG `0.2.x` is not supported anymore. We have Federated Learning on the roadmap for current PySyft.
