### ISSUE TITLE
hagrid launch local-node terminal stuck at Pulling Images .....0%

### ISSUE THREAD

**Issue by gelliravi** [OpenMined/PySyft#7459]
## Question
I have followed the steps to install pysyft in Linux at https://openmined.github.io/PySyft/install_tutorials/linux.html##. Everything got installed and able to run docker run hello-world. However, whenever I tried the command hagrid launch local-node, it got stuck at the step of pulling images. Please take a look at the error snapshot I've attached. Can someone help me to resolve it?

## Screenshots
<img width="432" alt="hagrid-launch-pull-images-stuck-Screenshot 2023-03-26 160412" src="https://user-images.githubusercontent.com/320806/227804598-75ccfb90-9999-4a66-a45e-da2b1610060b.png">

## System Information
 - OS: Ubuntu 20.04 and also tried on the latest Ubuntu 22.04
 - Language Version: Python 3.9
 - Package Manager Version: Conda

**Comment by madhavajay** [comment]
@gelliravi please update hagrid
```
$ pip install -U hagrid
```

And then run debug to see your system settings.
```
$ hagrid debug
```

And then run your command with: 
```
$ hagrid ... --verbose
```

If you still have an issue paste the output and the debug output here and ill help.

**Comment by madhavajay** [comment]
This is usually due to a hidden error which you will see if you use `--verbose`. I will close this for now.
