### ISSUE TITLE
Hagrid quickstart error

### ISSUE THREAD

**Issue by KoSpades** [OpenMined/PySyft#7474]
## Description
When running hagrid quickstart, got the error "ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject"

## System Information
 - OS: macOS M1
 - Language Version: Python 3.9.6
 - Package Version: gevent 22.10.2, greenlet 2.0.2

**Comment by madhavajay** [comment]
@KoSpades Can you try `pip install -U hagrid` and update it, or ensure its installed in a virtualenv so that it doesn't conflict with any other packages you have.

**Comment by madhavajay** [comment]
I will close for now as there has been no response, this was fixed by updating the dependencies, please install the latest syft and that should correct the issue.
