### ISSUE TITLE
Hagrid launch and check shows PyGrid api status is ❌

### ISSUE THREAD

**Issue by Dumplingz** [OpenMined/PySyft#7478]
## Question
When running the line `!hagrid launch test_domain domain to docker:8081 --tag=latest` with the install wizard, UI has a ✅  while api has an ❌.

## Further Information
I'm following the Hagrid Install Wizard and when running the lines `!hagrid launch test_domain domain to docker:8081 --tag=latest` and `hagrid.check('localhost:8081',timeout=120)`, the table that is printed out in the end shows api's status is an ❌. Is this intended behavior? I'm not sure if it's really a problem because the subsequent `login` and `land` commands seem to work, and I can access the UI just fine. In fact, uploading private data and create user accounts in the tutorials also seemed to work. 

I'm missing the ssh, jupyter, and host rows in the table as well.

## Screenshots
I assume the correct table should look like this (from tutorial 00-deploy-domain):
<img width="450" alt="Screen Shot 2023-03-30 at 16 19 32" src="https://user-images.githubusercontent.com/19320716/228967198-85280bed-ea36-4be0-b80d-c0a6bb84493a.png">

but I get this:
<img width="1135" alt="Screen Shot 2023-03-30 at 16 16 24" src="https://user-images.githubusercontent.com/19320716/228967309-1e8c6029-be0e-4bc7-b92b-ca676b2b875f.png">

## System Information
 - OS: macOS
 - OS Version: 12.3
 - Language Version: Python 3.9.16
 - Package Manager Version: pip 23.0.1

## Additional Context
Outputs from some previous lines:
✅ hagrid==0.2.134 (latest stable)

✅ macOS
✅ Python 3.9.16
✅ syft==0.7.0 (latest stable)

✅ Git 2.32.1
✅ Docker 20.10.20
✅ Docker Compose 2.12.1

**Comment by dbckz** [comment]
Also getting exactly this. Out of interest, when you login to the domain node do you also find the name of it is 'default_domain_node' rather than 'test_domain'?

**Comment by madhavajay** [comment]
@Dumplingz we have moved to `api/v2` sometimes that check will fail but that doesnt mean the system isnt running. Can you update hagrid with:
```
$ pip install -U hagrid
```

And try running with `--verbose` and see what the output says.

**Comment by madhavajay** [comment]
I will close this for now as the `openapi.json` endpoint is not needed for the frontend or the syft client api.
