### ISSUE TITLE
ConnectionError: Failed to fetch http://localhost:8081/api/v1/new/metadata. Response returned with code 404

### ISSUE THREAD

**Issue by liu-a111** [OpenMined/PySyft#7527]
## Question
My environment configuration is as follows：
hagird==0.2.137
syft==0.8.0b7
I followed the code from Notebook, but there was an error
it's that ConnectionError: Failed to fetch http://localhost:8081/api/v1/new/metadata. Response returned with code 404

**Comment by damilareisaac** [comment]
I got the same error on google Colab. The same code run on my mac machine

**Comment by madhavajay** [comment]
@liu-a111 thats a very old version of syft can you try the latest `0.8.3` or `0.8.4` which will be released in a few days (you can try beta's already).

**Comment by madhavajay** [comment]
Closing for now.
