### ISSUE TITLE
Implement the Add function for IntTensor on the CPU/GPU

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#755]
### User Story: 
As a Data Scientist using PySyft's IntTensor type, I want to leverage a wide range of methods which use our new Unity backend. For this ticket to be complete, the add() should be added to our IntTensor class with the appropriate functionality, returning a new tensor.

Note, it is possible that when you look in the code you'll find that parts of this issue were completed on the backend while implementing another issue. This is par for the course as features do not live in isolation. If this is the case, just take it as a convenience that someone already built that part and press on!

### Every Reference You Might Need for this Issue:

- For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.
- For a reference on how to program in Unity, check out [this basic tutorial](https://unity3d.com/learn/tutorials/projects/roll-ball-tutorial)
- For a reference on how to write HLSL code, check out [this basic tutorial](http://kylehalladay.com/blog/tutorial/2014/06/27/Compute-Shaders-Are-Nifty.html)
- For a complete tutorial on how to add functions to FloatTensor (step by step guide) see [this Google Document](https://docs.google.com/document/d/1WRd7gGLFN0Awtf86AICYIHtg3gfFWLBa5wYTthsB3i0/edit)
- For a reference on how other functions like this have been implemented check out the functions in [this notebook](https://github.com/OpenMined/OpenMined/blob/master/notebooks/Syft%20Tensor%20Example%20Notebook.ipynb) as well as the corresponding files that made it possible ([SyftController](https://github.com/OpenMined/OpenMined/blob/master/Assets/OpenMined/Network/Controllers/SyftController.cs), [FloatTensor.Ops](https://github.com/OpenMined/OpenMined/blob/master/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs), [FloatTensor.ShaderOps](https://github.com/OpenMined/OpenMined/blob/master/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs), [FloatTensorShaders](https://github.com/OpenMined/OpenMined/blob/master/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute), and [FloatTensorTest](https://github.com/OpenMined/OpenMined/blob/master/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs)).
- And of course, please consider our [Contributor Guidelines](https://github.com/OpenMined/Docs/blob/master/contributing/guidelines.md) for all contributions.
### Acceptance Criteria:

- [ ] comment below that you're interested in picking up this issue
- [ ] an example in a notebook in our [tests folder](https://github.com/OpenMined/OpenMined/tree/master/notebooks/tests) showing how to use the functionality from PySyft
- [ ] an integration test in PySyft demonstrating the correct CPU and GPU operation implemented over an IntTensor while connected to a Unity backend
- [ ] a Unit Test in OpenMined/OpenMined demonstrating the correct operation on a FloatTensor
- [ ] [inline](http://pytorch.org/docs/master/tensors.html) documentation in the python code. For inspiration on inline documentation, please check out PyTorch's documentation for this operator.
- [ ] Link your Pull Request back to this Issue so that it gets closed appropriately when the PR is merged.

**Comment by dikshant2210** [comment]
While the title says to implement in the IntTensor class, description says add() should be added to our FloatTensor class! I think it is in IntTensor in both cases. Please correct me if  I am wrong.

**Comment by bharathgs** [comment]
@dikshant2210 you are right! sorry about that. it is intTensor in both the cases.

**Comment by gavinuhma** [comment]
I'll pick this one up

**Comment by gavinuhma** [comment]
Going to start with the PySyft interface and the CPU code

**Comment by iamtrask** [comment]
Sweet! Once you've got the interface setup, I'll add the GPU side. Feel free to just add an if statement that returns "NotImplementException" if dataOnGpu==True and I'll insert my GPU code there.

**Comment by gavinuhma** [comment]
Perfect. Works for me!

**Comment by iamtrask** [comment]
Hey @gavinuhma , what branch are you working on so that I can collaborate with you?

**Comment by gavinuhma** [comment]
Hey @iamtrask I'm working from `int_add`, I started a pull request as a work in progress:
https://github.com/OpenMined/OpenMined/pull/319

**Comment by iamtrask** [comment]
Hey @gavinuhma , in https://github.com/OpenMined/OpenMined/pull/322 I uncovered a potential bug in how our shader is initialized which I will report in another bug issue. This implementation does pass your first unit test with a temporary workaround.

**Comment by gavinuhma** [comment]
Great find @iamtrask ! We're almost done!
