### ISSUE TITLE
Can we get the encrypted parameter data from central server?

### ISSUE THREAD

**Issue by X-Omil** [OpenMined/PySyft#7552]
## Question
Can data onwer get the encrypted parameter data from central server?

## Further Information
Describe your question in greater length here.
When we build a federation learning model with two data ownes(data owner A and data owne B), and a data scientist, can  data onwer obtain the model parameters passed from the data providers to the data scientist after encryption by the central server?

## System Information
- pysyft version: 0.5.0

**Comment by madhavajay** [comment]
@X-Omil sorry can you be a little more explicit in what you are asking? It sounds like a Federated Learning use case?

**Comment by madhavajay** [comment]
Closing for now.
