### ISSUE TITLE
network.domains and network.api.services.network.get_all_peers not working

### ISSUE THREAD

**Issue by KamalGalrani** [OpenMined/PySyft#7565]
## Description
network.domains and network.api.services.network.get_all_peers not working

## How to Reproduce
1. Launch a node using `hagrid launch "network" network to docker:8000 --tag=beta --build-src=dev`
2. Try listing domains with `network.domains` 
3. It fails with the following error
```
<class 'syft.service.response.SyftError'>: Exception calling network.get_all_peers. BaseStash.get_all() missing 1 required positional argument: 'credentials'
```

## Expected Behavior
network.domains must return list of domains

**Comment by rasswanth-s** [comment]
Closing the PR is merged!
