### ISSUE TITLE
User Search: pydantic.networks.EmailStr not in TYPE_BANK

### ISSUE THREAD

**Issue by KamalGalrani** [OpenMined/PySyft#7567]
## Description
![image](https://user-images.githubusercontent.com/2345081/234805035-fd435418-c9bd-4eba-b87c-ad1ed27d5df6.png)

## How to Reproduce
`network_client.api.services.user.search(email=EmailStr('kamal.galrani@tvarit.com'))`

## Expected Behavior
Return user with email address

**Comment by iamtrask** [comment]
Hey @KamalGalrani - thanks for looking into the fix! Is this issue ready to close?
