### ISSUE TITLE
Can not connect to domain node 

### ISSUE THREAD

**Issue by Terror-1** [OpenMined/PySyft#7583]
## Description
I have deployde a domain node on my machine and it seems up by runnung `!hagrid check localhost:8081` but even so I am not able to connect to the domain node 

## How to Reproduce
2. Click on '...'
3. Scroll down to '...'

## Screenshots
![image](https://user-images.githubusercontent.com/73742471/235091867-84b668cd-e64c-4080-939c-3ee79389928e.png)
![image](https://user-images.githubusercontent.com/73742471/235092123-4931acbb-3c2f-41b5-ba1c-c34569b9b0d2.png)

## System Information
 - OS: Windows
 - OS Version: 11
 - Language Version: [e.g. Python 3.9.16, Node 10.18.1]
 - syft version : 0.7.0
 - Docker version 20.10.23
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by godrrrain** [comment]
Same problem, how did you fix this?

**Comment by JieJieNiu** [comment]
I have the same problem with you. Do you solve that?
