### ISSUE TITLE
domain.store

### ISSUE THREAD

**Issue by Terror-1** [OpenMined/PySyft#7588]
![image](https://user-images.githubusercontent.com/73742471/235499064-51f2b6ff-2ca3-4526-bd07-a7d6be433f05.png)

**Comment by iamtrask** [comment]
Hey @Terror-1 - can you post how to reproduce this bug? Please include your operating system and version of python, docker, syft, and hagrid.

**Comment by madhavajay** [comment]
@Terror-1 there isn't a `client.store` in `0.8.x` you interact with Datasets, Code and Jobs to get your results.
