### ISSUE TITLE
UserCode duplicate key error

### ISSUE THREAD

**Issue by jack-chen2022** [OpenMined/PySyft#7626]
##Question Description
My env is Python =3.9.16 , hagrid =0.3.7, syft=0.8.0 ,recently i try api/8.0/01-submit-code.ipynb to request sum_trade_value_mil code again, but found if request the same dataset ps name  'trade_data' will be cause UserCode duplicate key error and domain node response the error message like below , cause from syft.service.code.user_code.UserCode  function.

<img width="819" alt="image" src="https://github.com/OpenMined/PySyft/assets/114645772/b9ae1aaa-690e-468e-bf1b-0d3911fae08e">

### error response 1
<img width="810" alt="image" src="https://github.com/OpenMined/PySyft/assets/114645772/62fa9d79-b30b-4d33-b8b0-e4d6f6a51005">

### error response 2
<img width="803" alt="image" src="https://github.com/OpenMined/PySyft/assets/114645772/4c3ad5db-bd90-4628-bc8b-9bac4417eb5a">

## Expected Behavior
Anyone can teach me how to clean/empty domain node ,or easy way to clean qulite  or mongo database like users duplicate key clean.

## System Information
 - OS: win11
 - OS Version: [e.g. 22]
 - Language Version: Python =3.9.16 , hagrid =0.3.7, syft=0.8.0 ,Docker Desktop 4.19.0 (106363) 
 - Package Manager Version:Conda 23.3.1
 - Browser (if applicable): Google Chrome
 - Browser Version (if applicable): 113.0.5672.93 (正式版本) (64 位元)

**Comment by iamtrask** [comment]
Hey @jack-chen2022 - i've added a new feature request to be able to delete projects from the Python API. (I'm sure we were planning this anyway but now there's a ticket so you can track its progress).

In the mean time if you don't mind clearing the whole domain you can use "hagrid land all; hagrid clean volumes" and it'll empty out everything from your docker container and give you a fresh place to start again. You'll need to run "hagrid launch".

**Comment by iamtrask** [comment]
The error you're getting is basically that the project already exists, and PySyft won't let you create two projects with the same name.

**Comment by jack-chen2022** [comment]
Dear iamtrask and 
koenvanderveen:
I have seen the notebook about  [tutorials](https://github.com/OpenMined/PySyft/tree/dev/notebooks/tutorials)  jupyter. Are we developing JUPYTER based on the system’s original role assignment? like the image.
<img width="856" alt="image" src="https://github.com/OpenMined/PySyft/assets/114645772/66d915ad-edb6-4a03-83d0-21ae417e07d6">

**Comment by madhavajay** [comment]
@jack-chen2022 The UI mentions some roles which have not been implemented yet. We are focused on Data / Model Owner, Data Scientist work flows at the moment.
