### ISSUE TITLE
All documents are related to older versions

### ISSUE THREAD

**Issue by HopeDevote** [OpenMined/PySyft#7653]
When will the API documentation related to pysyft 0.8 and 0.9 be released

**Comment by IrinaMBejan** [comment]
Hi @HopeDevote,

We are hoping to roll in detailed documentation soon for 0.8. Currently, some code examples are provided here: https://github.com/OpenMined/PySyft/tree/dev/notebooks/api/0.8

and over the next few weeks, the API documentation will be available more extensively here: https://github.com/OpenMined/PySyft/tree/dev/notebooks/tutorials/

Thanks a lot for waiting!

**Comment by HopeDevote** [comment]
您好，您的文件我已收到！
