### ISSUE TITLE
Refactor Tox Paths to work with Windows

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#7686]
## Description
Currently, when we use tox, all the paths are ordered by
`/` but in windows we use `\`, 

Modify all the paths in tox.ini such that the all the environments work with Linux, Mac, Windows.

How to reproduce:
Run

`tox -e syft.jupyter` on Windows and it would not work due to the path issue.

**Comment by snehilsanyal** [comment]
Hey @rasswanth-s can I take this issue up?

**Comment by rasswanth-s** [comment]
Closing this , as we added a documentation for the same: https://github.com/OpenMined/PySyft/pull/7701
