### ISSUE TITLE
Square root of encrypted tensor

### ISSUE THREAD

**Issue by HijaziNeveen** [OpenMined/PySyft#7690]
## Question
**Describe your question in ONE SENTENCE.**
I would like to ask if there is a way to find the square root of encrypted tensor?
## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by madhavajay** [comment]
@HijaziNeveen You might be able to use TenSEAL to do HE encrypted computation.
https://github.com/OpenMined/TenSEAL
