### ISSUE TITLE
>=0.8.1b0 PyGrid API Route Error

### ISSUE THREAD

**Issue by chen-z-j** [OpenMined/PySyft#7729]
## Description
I find some error if  update syft and hagrid the api url route path will be error to v2 (http://localhost:8081/api/v2/openapi.json) but the v1(http://localhost:8081/api/v1/openapi.json) is correct, may i gueest over describe suggest.

## Expected Behavior
I am building an device Ubuntu20.04.06 LTS Server on medical lab with Syft ,device package environment  include hagrid=0.3.14 and  >=syft=0.8.1b0  already tested every type. Under notebook 0.8 ~0.9  samples with syft_jupyter can't login even can't find domain server.I used  hagrid chekck was found may be th api route error cause , suggest API Rout error need fix ,and upgrade should be write to  another jupyter notebook, not be necessary in anyother samples to Force Update Syft when some user want test environment or login remote Domain node .

## Screenshots

![PyGrid_API_Test](https://github.com/OpenMined/PySyft/assets/23700469/5dfbb930-503e-4941-b321-856ba487eb53)
![PyGrid_API_Test_error](https://github.com/OpenMined/PySyft/assets/23700469/bebfc44e-be59-4c61-8fc1-b1b2934c215c)
![PyGrid_API_Route_V1](https://github.com/OpenMined/PySyft/assets/23700469/05db0825-d0be-44ea-a603-5e6fea319366)
![PyGrid_API_Route_V2](https://github.com/OpenMined/PySyft/assets/23700469/0aead4f3-a9fa-4c1e-9a52-3c32cf292d78)

**Comment by chen-z-j** [comment]
Ubuntu Device
<img width="1276" alt="Ubuntu Environment" src="https://github.com/OpenMined/PySyft/assets/23700469/e15e27a7-2b34-403b-8326-94e1354feedc">

**Comment by madhavajay** [comment]
@chen-z-j hagrid is probably checking api v2 but you might be deploying api v1. Api v2 is in the latest betas and we will release a stable 0.8.1 this week.

**Comment by madhavajay** [comment]
Closing as there was no response.
