### ISSUE TITLE
May I ask what solution companies generally use now to encrypt AI models?

### ISSUE THREAD

**Issue by nameli0722** [OpenMined/PySyft#7748]
I am working on a project in the company to encrypt the model. I want to research the usage in the industry and apply it to my work. I would be very grateful if I could receive your response as there are no friends around who have done model encryption.

**Comment by iamtrask** [comment]
Hi @nameli0722 - If you mean homomorphic encryption, I believe the leading folks in the space are at https://www.zama.ai/. They have an open source library (concrete), but I believe their fastest one is closed-source/propriteary.
