### ISSUE TITLE
Is PySyft used for large models and are there any examples？

### ISSUE THREAD

**Issue by hwjnihao** [OpenMined/PySyft#7751]
## Question
**Describe your question in ONE SENTENCE.**

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by iamtrask** [comment]
Hi @hwjnihao while there's no strict limit on the size of assets used in PySyft, we don't at present have a tutorial around them. I don't presently have a date for when such a tutorial might come together, but we are actively performing R&D in this area.
