### ISSUE TITLE
Implement Default numel Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#78]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, numel() should return a new tensor. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by baldassarreFe** [comment]
Shouldn't it be possible to compute the number of elements in a tensor even if it is encrypted?
For instance, in [this notebook](https://github.com/OpenMined/PySyft/blob/master/notebooks/Syft%20-%20Paillier%20Encrypted%20Linear%20Classification.ipynb) one can easily count the number of `[e]`s in the encrypted tensors.

Also: [`torch.numel()`](http://pytorch.org/docs/master/torch.html#torch.numel) returns an integer, while the user story says `numel()` should return a tensor. Which one should PySyft implementation follow?

**Comment by iamtrask** [comment]
@baldassarreFe all your points are correct :)

**Comment by alberduris** [comment]
I would like to work on that, cause it seems to be pretty simple. Anyway, I'm not very confident yet, so I'll try but if anyone wants to work on that too, please, feel free to do it :)

**Comment by alberduris** [comment]
Now I have some doubts for @iamtrask, @baldassarreFe or anyone that could help.

If, as @baldassarreFe has suggested, `numel()` will return an integer, and the post is `Returns the total number of elements in the Tensor.` What's the point of implementing `numel` if we already have `nelements`  and `size`?

`size: Size of tensor`
`Returns the total number of elements in the tensor.`

If it's just for having the operation named `numel`, as PyTorch, shouldn't we implement the count for encrypted tensors in `size` and `nelement` too as @baldassarreFe has also suggested?

**Comment by joewie** [comment]
`nelement` is just an alias for `numel` in PyTorch, so I suppose we have both to conform with PyTorch's methods.

Looking at PyTorch's documentation, it seems that their implementation of `size` is supposed to return a `torch.Size` subclass of `tuple`, as in:
```
>>> torch.Tensor(3, 4, 5).size()
torch.Size([3, 4, 5])
```

If we're seeking to mirror PyTorch, it looks like we'll probably need to change our current implementation.

**Comment by baldassarreFe** [comment]
As my personal opinion, I agree that `size()` should give us a tuple of dimensions, just like pytorch [`size()`](http://pytorch.org/docs/master/tensors.html#torch.Tensor.size), while `numel()` and its alias `nelement()` should simply count the elements in the tensor, again like pytorch [implementation](http://pytorch.org/docs/master/torch.html#torch.numel)

Waiting for @iamtrask to give us a last word ;)

**Comment by bharathgs** [comment]
I agree with @baldassarreFe & @joewie, these functions need to be modified.

**Comment by OceanCoding** [comment]
Totally agree with you two, too!

**Comment by iamtrask** [comment]
Agreed
