### ISSUE TITLE
Does version 0.8.1 not support federated learning?

### ISSUE THREAD

**Issue by xswfantasy** [OpenMined/PySyft#7875]
Hello, I just came into contact with the Pysfyt framework, and I want to use it to do research related to federated learning and privacy computing. It is found that Syft 0.2.X version still has some federated learning examples and related APIs, while higher versions such as the latest 0.8.1 version do not have relevant content, including tutorials. 

I would like to ask a few questions: 

1. Does the latest version not support federated learning, or does it support it, but there are no relevant tutorials? 
3. What are the reasons for the major changes in this version?
4. Will you plan to continue to support federated learning and publish some related tutorials in the future?
5. There is no relevant architecture diagram in the document of version 0.8.1. Is the architecture consistent with the description of the document of version 0.7.0?

Looking forward to reply, thank you!

**Comment by madhavajay** [comment]
Hi @xswfantasy `0.2.x` is deprecated however newer Federated Learning capabilities are on our roadmap.

**Comment by ftrier** [comment]
Hi @madhavajay,
as far as I understood, version 0.8.6 does not contain anything specifically for federated learning. Earlier versions did though. This raises the question, how stable is PySyft regarding its API? Do you have any guide/best practices on how create FL using the current PySyft version?

Thank you very much!
