### ISSUE TITLE
Implement Default numpy Functionality for Base Tensor Type

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#79]
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, numpy() should return a new tensor. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

**Comment by sajalsubodh22** [comment]
what exactly we have to do to solve this issue? Actually i am a newbie and really want to help in solving beginner issues.
Please elaborate.

**Comment by iamtrask** [comment]
@sajalsubodh22 Ah! Sorry. that is a bit vague. The functionality is to cast a BaseTensor type to a numpy object. In this case, the internal storage IS a numpy object so it'd be quite easy and a great starting point :)

**Comment by sajalsubodh22** [comment]
@iamtrask thank you so much ! I have gone through the source code of tensor.py , math.py thoroughly and have also read PyTorch's documentation and it seems a bit easy to solve these issues.  
Kindly assign me to this and issue #55 to resolve.
Thanks in advance!

**Comment by iamtrask** [comment]
Excellent! 

Normally we wait until after someone's first PR to add them to the Org (where we can then make assignemnts), but since you asked I went ahead and sent you an invite, and I'll assign you as soon as you accept it! 

Welcome to the OpenMined project!

**Comment by sajalsubodh22** [comment]
thank you so much! Happy to help and get helped! :)
