### ISSUE TITLE
Bump Jaxlib version to 0.4.13 as we have Windows Wheels for Jaxlib

### ISSUE THREAD

**Issue by rasswanth-s** [OpenMined/PySyft#7917]
## Description
Since, we did not have windows wheels, for jaxlib, we used to use the unofficial windows wheels
and install syft by

```python3
pip install syft -U -f https://whls.blob.core.windows.net/unstable/index.html 
```

Since we have the windows wheels, the installation could be reduced to

```python3
pip install syft
```

Task List for the issue:

- [ ] Bump jax and jaxlib to 0.4.13. in setup.cfg
- [ ] Find and remove all the places, where we ask for users install a jaxlib separately in windows
- [ ] Remove in all the places where install jaxlib separately like (pip install jaxlib==0.4.10 -f https://whls.blob.core.windows.net/unstable/index.html)

**Comment by snehilsanyal** [comment]
Hey @rasswanth-s I would like to explore this issue, can you please assign this to me?

**Comment by whsybzz** [comment]
Thank you for providing the Windows download address.
Can you provide a Linux version of jaxlib 0.3.14 for download
```
ERROR: Ignored the following yanked versions: 0.1.63, 0.4.0, 0.4.15
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.14 (from tensorflow-federated) (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20)
ERROR: No matching distribution found for jaxlib==0.3.14
```

when i execute pip install - U jaxlib=0.3.14- f https://storage.googleapis.com/jax-releases/jaxlib_releases.htmlPost error
```
Looking in links: https://storage.googleapis.com/jax-releases/jaxlib_releases.html

Error: Ignored the following yang versions: 0.1.63, 0.4.0, 0.4.15

Error: Could not find a version that satisfies the requirement jaxlib=0.3.14 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20)

Error: No matching distribution found for jaxlib==0.3.14
```

**Comment by rasswanth-s** [comment]
Closing this, as the jaxlib version is updated
