### ISSUE TITLE
Could you add PySyft tutorials?

### ISSUE THREAD

**Issue by bluetail14** [OpenMined/PySyft#7959]
## Question
Hi, 
I saw a link for them in the OpenMined blog but there are no examples in here. 
https://github.com/OpenMined/PySyft/tree/master/examples/tutorials
can you add them?

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by Murat-U-Saglam** [comment]
https://github.com/OpenMined/PySyft/blob/0.8.1/notebooks/api/0.8/00-load-data.ipynb

**Comment by madhavajay** [comment]
@Murat-U-Saglam that is correct thanks. Also @bluetail14 we will be adding some much more high quality tutorials soon.
