### ISSUE TITLE
ModuleNotFoundError when import syft.frameworks.tenseal as ts

### ISSUE THREAD

**Issue by bluetail14** [OpenMined/PySyft#7968]
## Description
When I run 'import syft.frameworks.tenseal as ts' it gives me an error, 'ModuleNotFoundError: No module named 'syft.frameworks'.

## How to Reproduce
1. Run '! pip install -U syft to install PySyft. '
2. Run 'import syft as sy'
3. Run 'import syft.frameworks.tenseal as ts'

## Expected Behavior
It should be able to import tenseal

## System Information
 - OS: AWS SageMaker
 - Python 3.10.8

## Additional Context
I am trying to implement the tutorial here, https://blog.openmined.org/ckks-homomorphic-encryption-pytorch-pysyft-seal/
Do you have a tutorial with the updated code to fix this issue?

**Comment by madhavajay** [comment]
@bluetail14 Tenseal was available in Syft 0.5 if you would prefer to use that.

Alternatively in the latest version of syft 0.8.4 you can install what ever python libraries inside a container and use that in your custom user functions.
