### ISSUE TITLE
sy.orchestra.launch Nodetype is not defined

### ISSUE THREAD

**Issue by JieJieNiu** [OpenMined/PySyft#8043]
## Description
When I run node=sy.orchestra.launch,  the error 'name 'NodeType' is not defined'

I run the !hagrid check localhost 8081, there should be five check mark, but my result is as follow:

## Screenshots
![图片](https://github.com/OpenMined/PySyft/assets/125357499/658d1df2-df12-4cbf-a884-32764fb9a425)

![图片](https://github.com/OpenMined/PySyft/assets/125357499/084b57ce-443e-4c6d-a050-bd44d5af019b)

## System Information
 - OS: [Linux]
 - OS Version: [version 6.2.0-26-generic (buildd@bos03-amd64-042) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0]
 - Language Version: [Python 3.10]
 - Syft version:[0.8.1]
 - Hagrid version: [0.3.70]

**Comment by mamuleanu** [comment]
It may be a compatibility issue between Syft and Hagrid versions. Could you try using Hagrid version 0.3.37 and check if this error is still triggered ?

**Disclaimer:** I'm not a maintainer of PySyft.

**Comment by madhavajay** [comment]
@JieJieNiu sorry, this broke a few times but we just fixed it, can you try installing the latest `hagrid==0.3.108`.
`pip install -U hagrid`

https://pypi.org/project/hagrid/
