### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jokikim** [OpenMined/PySyft#8115]
## Question
Based on PySyft's underlying technology, do you believe that 1) there's a way to allow more robust analytics, perhaps the ability to create dashboards and reporting based on the private data, and 2) a built-in way to run classical ML models, such as through Scikit-Learn API?

## Further Information
I have two questions, for which the contexts are below:

1) Dashboarding: I am not well-versed in Differential Privacy/Federated Learning and other technologies that drive PySyft, but I'm wondering what the full potential of PySyft could look like, beyond simply running DL models. Specifically, I wonder if there's a way, or could ever be a way, to build descriptive analytics around mock/private data, and potentially build Dashboards and Reports around them. I understand that the Data Scientists may not have the actual column names and such, but would there be a way to maintain the underlying relationships between the data so that they could report the relationships between features?

2) Classical ML: I understand that PySyft data is represented as tensors, but does PySyft have any intention on building in Classical ML models, such as Random Forest etc., as well? Is there a reason why Classical ML hasn't been incorporated much to this point?

**Comment by madhavajay** [comment]
@jokikim we do have something that might satisfy your desire for dashboards on the roadmap.

As for doing things like Scikit learn that should be possible in the new `0.8.4` custom container workload APIs. The release will be in the next few days but the latest beta should be just as stable.

https://github.com/OpenMined/PySyft/blob/dev/notebooks/api/0.8/10-container-images.ipynb
