### ISSUE TITLE
Implemented Functions and Security Definition for Differential Privacy

### ISSUE THREAD

**Issue by LoganZeien** [OpenMined/PySyft#8181]
# Questions
1. Is there a list of implemented PyTorch/TensorFlow functions that are compatible with the encrypting tensors?
2. Does the DP implemented in PySyft have a security proof?
3. Followup to 1, where is all the implemented functions/code? 

# Detail
1. I saw in many of the improvement issues, there was a fill called "allowlist.py" located in the Syft source directory (https://github.com/OpenMined/PySyft/blob/syft_0.3.0/src/syft/lib/torch/allowlist.py), but despite my best efforts, I cannot find this file. Was it removed, forgotten, replaced, etc.?
2. In the associated PySyft paper, you mentioned that some differential privacy had theoretical security bounds with a privacy budget. Does the differential privacy implemented in PySyft for ML have a security proof?
3. Where is all the code? Looking through some of the posted issues, I see a lot of implemented code, such as the BFV tensor in Python, but I cannot find it in the current GitHub-dev repository. Even running grep or find on the entire file doesn't return anything regarding, well, anything.

**Comment by madhavajay** [comment]
@LoganZeien 
1. Is there a list of implemented PyTorch/TensorFlow functions that are compatible with the encrypting tensors?
We have a few different Tensor implementations in earlier versions and will be bringing this back in the near future. For now you can do what ever you like server side in a custom container / custom function.

2. Does the DP implemented in PySyft have a security proof?
We are in the process of doing a security audit.

3. Followup to 1, where is all the implemented functions/code?
If you want to see some older DP tensor stuff you can see this:
https://github.com/OpenMined/PySyft/tree/0.7.0/packages/syft/src/syft/core/tensor/autodp
