### ISSUE TITLE
A little question in install_tutorials

### ISSUE THREAD

**Issue by zjlamtt** [OpenMined/PySyft#8223]
## Where?
[Where are you looking to add documentation? Which file? Which feature?](https://openmined.github.io/PySyft/install_tutorials/linux.html##)

## What?
In "Conda and setting up a virtual environment ",there is a little error,： conda remove "conda activate", instead of "source activate".  I know that it's not a big question, but still make the beginner, such as me, a little confuse. Hope you can fix it, thank you.

**Comment by madhavajay** [comment]
Thanks @zjlamtt
