### ISSUE TITLE
Can you provide a Linux version of jaxlib 0.3.14 for download

### ISSUE THREAD

**Issue by whsybzz** [OpenMined/PySyft#8280]
##  jaxlib ==0.3.14 version
** jaxlib ==0.3.14 download.**

https://whls.blob.core.windows.net/unstable/index.html Provided Windows version of jaxlib 0.3.14 for download
Can you provide a Linux version of jaxlib 0.3.14 for download
```
ERROR: Ignored the following yanked versions: 0.1.63, 0.4.0, 0.4.15
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.14 (from tensorflow-federated) (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20)
ERROR: No matching distribution found for jaxlib==0.3.14
```

when i execute pip install - U jaxlib=0.3.14- f https://storage.googleapis.com/jax-releases/jaxlib_releases.htmlPost error
```
Looking in links: https://storage.googleapis.com/jax-releases/jaxlib_releases.html

Error: Ignored the following yang versions: 0.1.63, 0.4.0, 0.4.15

Error: Could not find a version that satisfies the requirement jaxlib=0.3.14 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20)

Error: No matching distribution found for jaxlib==0.3.14
```

**Comment by madhavajay** [comment]
@whsybzz sorry this was the fault of Google not compiling jaxlib for all OSes, we provided some links to alternative versions, good news is its not a problem any more.

We are now using `jaxlib==0.4.20` and google ships binaries for all OSes and CPU architectures to pypi.
