### ISSUE TITLE
pyft0.8.2 remote debugging

### ISSUE THREAD

**Issue by simba-axin** [OpenMined/PySyft#8310]
## Description
After I downloaded the pyft0.8.2 version on the server, when I tried to link my python interpreter through ssh in pycharm, the following error occurred:
## How to Reproduce
1. Go to Pycharm
2. Try to ssh connect 
## Expected Behavior
```
Traceback (most recent call last):
  File "/home/zhouchengxin/anaconda3/envs/PySyft/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhouchengxin/anaconda3/envs/PySyft/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/__main__.py", line 167, in <module>
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/__main__.py", line 163, in run
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/__main__.py", line 16, in run
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/__init__.py", line 28, in cli_run
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/__init__.py", line 46, in session_via_cli
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/__init__.py", line 72, in build_parser
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/plugin/creators.py", line 13, in __init__
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/plugin/creators.py", line 20, in for_interpreter
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/plugin/base.py", line 44, in options
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/plugin/base.py", line 23, in entry_points_for
  File "/home/zhouchengxin/.pycharm_helpers/virtualenv-20.16.7.pyz/virtualenv/run/plugin/base.py", line 23, in <genexpr>
  File "/home/zhouchengxin/anaconda3/envs/PySyft/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 210, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython3macOs
```

## Screenshots
![image](https://github.com/OpenMined/PySyft/assets/63863888/f44f3153-9d90-421e-ada8-efd5fc6131b6)

## System Information
 - OS: Ubuntu
 - OS Version: [e.g. 22]
 - Language Version: python3.9
 - conda list:
# packages in environment at /home/zhouchengxin/anaconda3/envs/PySyft:
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
absl-py                   2.0.0                    pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
ansible                   8.6.1                    pypi_0    pypi
ansible-core              2.15.7                   pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
ascii-magic               2.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bcrypt                    4.0.1                    pypi_0    pypi
boto3                     1.28.65                  pypi_0    pypi
botocore                  1.31.85                  pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0    defaults
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cryptography              41.0.7                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
datasets                  2.14.7                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
distlib                   0.3.7                    pypi_0    pypi
dm-haiku                  0.0.10                   pypi_0    pypi
dnspython                 2.4.2                    pypi_0    pypi
email-validator           2.1.0.post1              pypi_0    pypi
evaluate                  0.4.1                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastapi                   0.103.2                  pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.46.0                   pypi_0    pypi
forbiddenfruit            0.1.4                    pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
gevent                    22.10.2                  pypi_0    pypi
gipc                      1.5.0                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
greenlet                  3.0.1                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hagrid                    0.3.91                   pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
huggingface-hub           0.17.3                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
importlib-metadata        7.0.0                    pypi_0    pypi
importlib-resources       5.0.7                    pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
itables                   1.6.2                    pypi_0    pypi
jax                       0.4.18                   pypi_0    pypi
jaxlib                    0.4.18                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jellyfish                 1.0.3                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jmp                       0.0.4                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
loguru                    0.7.2                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
ml-dtypes                 0.3.1                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
names                     0.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  2.8                      pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.101                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
opendp                    0.8.0                    pypi_0    pypi
openssl                   3.0.12               h7f8727e_0    defaults
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
paramiko                  3.3.1                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1           py39h06a4308_0    defaults
platformdirs              4.1.0                    pypi_0    pypi
prompt-toolkit            3.0.41                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyarrow                   14.0.1                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pycapnp                   1.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.13                  pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pymongo                   4.5.0                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyopenssl                 23.3.0                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.9.18               h955ad1f_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             1.0.0                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
recordlinkage             0.16                     pypi_0    pypi
redis                     4.6.0                    pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
resolvelib                1.0.1                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
restrictedpython          6.2                      pypi_0    pypi
result                    0.10.0                   pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
s3transfer                0.7.0                    pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0    defaults
sherlock                  0.4.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    defaults
stack-data                0.6.3                    pypi_0    pypi
starlette                 0.27.0                   pypi_0    pypi
syft                      0.8.2                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
tokenizers                0.14.1                   pypi_0    pypi
torch                     2.1.0                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.14.0                   pypi_0    pypi
transformers              4.34.0                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18                  pypi_0    pypi
uvicorn                   0.23.2                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
virtualenv                20.25.0                  pypi_0    pypi
virtualenv-api            2.1.18                   pypi_0    pypi
watchfiles                0.21.0                   pypi_0    pypi
wcwidth                   0.2.12                   pypi_0    pypi
websockets                12.0                     pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0    defaults
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    defaults
yarl                      1.9.3                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
zope-event                5.0                      pypi_0    pypi
zope-interface            6.1                      pypi_0    pypi

**Comment by madhavajay** [comment]
@simba-axin you probably need to run the main python backend server with `pdb` inline. @yashgorana is actually adding this to our Kubernetes Dev environment this month. Ill make sure we add documentation on the main README.md.

**Comment by yashgorana** [comment]
@madhavajay  #8481 should address this with docs at https://github.com/OpenMined/PySyft/blob/dev/DEBUGGING.md

**Comment by madhavajay** [comment]
@yashgorana excellent.
@simba-axin I will close this for now but if you want to do remote debugging please checkout the guide above.
