### ISSUE TITLE
An exception occured: maximum recursion depth exceeded. when running install_wizard?

### ISSUE THREAD

**Issue by xwang317** [OpenMined/PySyft#8345]
## Description
An exception occured: maximum recursion depth exceeded. when running install_wizard?

## How to Reproduce
when I tried to run the 01-install-wizard file, it happens when I ran the second cell: 
`wizard.check_hagrid`
There is also a warning at the first cell. 

## Expected Behavior
should not report error?
Thanks in advance. 

## Screenshots
![image](https://github.com/OpenMined/PySyft/assets/77611898/39de9cf5-1c28-439b-86e6-1883cf83e8d9)
![image](https://github.com/OpenMined/PySyft/assets/77611898/00c57384-83ad-4c33-9986-3507eaa3b2cb)
![image](https://github.com/OpenMined/PySyft/assets/77611898/ef48ec36-1541-4c83-b019-7bf5abee7fbd)
![image](https://github.com/OpenMined/PySyft/assets/77611898/e281176b-85b6-4316-8545-4162428f79bc)
![image](https://github.com/OpenMined/PySyft/assets/77611898/3ed5f7b5-fdc2-44bc-98ec-35208b08b9cc)

## System Information
 - OS: WSL ubuntu2204 LTS
 - Language Version: Python 3.10
 - Package Manager Version: anaconda 23.7.4

## Additional Context
Thank you!

**Comment by madhavajay** [comment]
@xwang317 are you able to update hagrid with `pip install -U hagrid` and try again, then run `!hagrid debug` in a cell and copy out the output?

**Comment by madhavajay** [comment]
Closing for now.
