### ISSUE TITLE
Module 'syft' has no attribute 'TorchHook'

### ISSUE THREAD

**Issue by Jaehyung-Lim** [OpenMined/PySyft#8381]
## Question
Are problems related to this resolved?
I saw some same Issue with mine...

## Screenshots
If applicable, add screenshots to help explain your question.
![image](https://github.com/OpenMined/PySyft/assets/76619436/1639f8fd-3aa5-47d3-b04d-4fd9b9183c2d)

## System Information
 - syft version: 0.8.4-beta.12

**Comment by PalexGoneGit** [comment]
It is my understanding that using TorchHook explicitly is no longer necessary in the latest version of PySyst and that step can be skipped. I am still learning myself, so I cannot say for sure.

**Comment by madhavajay** [comment]
@AlexAronikov Correct `TorchHook` was part of `0.2` and is no longer valid in Syft.

**Comment by madhavajay** [comment]
@Jaehyung-Lim check out some of the notebooks here for some examples:
https://github.com/OpenMined/PySyft/tree/dev/notebooks/api/0.8
