### ISSUE TITLE
How to deploy the latest version of pysyft on raspberry pie

### ISSUE THREAD

**Issue by yzmninglang** [OpenMined/PySyft#8518]
## Question

How to deploy the latest version of pysyft on raspberry pie，

## System Information
 - OS: Ubuntu
 - OS Version: 22.04 arm
 - Language Version: Python3.8
 - Package Manager Version: 0.8.4

**Comment by madhavajay** [comment]
@yzmninglang We dropped support for python 3.8 a while back but you should be able to install Python 3.9.

The main thing that will prevent you install syft will be aarch packages for raspberry pi. 

If its a 32-bit raspberry pi it might be a bit harder.
Have you tried to install the current dependencies directly with pip to see which ones are supported currently?

Do you know which model of raspberry pi you have?

https://github.com/OpenMined/PySyft/blob/dev/packages/syft/setup.cfg

```
bcrypt==4.0.1
boto3==1.28.65
forbiddenfruit==0.1.4
gevent==23.9.1
loguru==0.7.2
networkx==2.8
packaging>=23.0
pyarrow==14.0.1
pycapnp==1.3.0
pydantic[email]==1.10.13
pymongo==4.6.1
pynacl==1.5.0
pyzmq>=23.2.1,<=25.1.1
redis==4.6.0
requests==2.31.0
RestrictedPython==7.0
result==0.10.0
tqdm==4.66.1
typeguard==2.13.3
typing_extensions==4.8.0
sherlock[redis,filelock]==0.4.1
uvicorn[standard]==0.24.0.post1
fastapi==0.103.2
psutil==5.9.6
hagrid>=0.3
itables==1.6.2
safetensors==0.4.1
argon2-cffi==23.1.0
matplotlib==3.8.0
jaxlib==0.4.20
jax==0.4.20
numpy>=1.23.5,<=1.24.4
pandas==1.5.3
docker==6.1.3
kr8s==0.13.1
PyYAML==6.0.1
azure-storage-blob==12.19
```

If you have any issues with these libs you can try to create a branch of PySyft in a fork and modify the setup.cfg to get it to use versions that are compatible with your raspberry pi.

**Comment by yzmninglang** [comment]
Thank you very much for your reply. My raspberry pi is the latest version of raspberry pi 5. I also feel that the aarchpython dependency package you mentioned is not compatible. Because some packages only compile x86 architecture, I can't install the dependencies needed by pysyft here.Currently, my raspberry pie 5 is a 64-bit ubuntu system, when I follow your prompts to create an python3.9 environment in conda. Running pip install syft, everything seems to be fine now. Thank you very much for your guidance.

**Comment by madhavajay** [comment]
@yzmninglang glad to hear you got it working! 👏
