### ISSUE TITLE
API Notebook(01-submit-code) doesn't run

### ISSUE THREAD

**Issue by rajaboja** [OpenMined/PySyft#8530]
## Description
```
pointer = sum_trade_value_mil(trade_data=asset)
result = pointer.get()
```
The code above from [this](https://github.com/OpenMined/PySyft/blob/288b559bd764d6425e6db0d9fd2834d83798a819/notebooks/api/0.8/01-submit-code.ipynb)(notebooks/api/0.8/01-submit-code.ipynb) notebook throws following exception:
```
AttributeError                            Traceback (most recent call last)
Cell In[68], line 2
      1 pointer = sum_trade_value_mil(trade_data=asset)
----> 2 result = pointer.get()

AttributeError: 'tuple' object has no attribute 'get'
```

**Comment by H4LL** [comment]
I can confirm that I also get an error running the same code block:

syft version: 0.8.4
python version: 3.11.8

<img width="942" alt="Screenshot 2024-02-27 at 3 51 19 PM" src="https://github.com/OpenMined/PySyft/assets/46713492/c0a521c1-44b1-4aea-a262-462ee2a72e4f">

**Comment by madhavajay** [comment]
@rajaboja and @H4LL Interesting, seems like its having trouble creating the temporary worker. I will ask the team to investigate.

<img width="648" alt="Screenshot 2024-03-04 at 1 13 33 pm" src="https://github.com/OpenMined/PySyft/assets/2882739/cad7c9a2-c94a-4f42-b53f-f2295491a0ba">

**Comment by madhavajay** [comment]
This now creates a pointer where as before it was returning the locally executed data, so I wonder if this is a mismatch between a version and the notebook.

Can you both please print `sy.__version__` to see what version is running and try the `0.8.4` in case you have one of the betas?

**Comment by rajaboja** [comment]
I was running `0.8.3`, upgrading to to `0.8.4` resolves the issue.
Perhaps the `SYFT_VERSION` in the first cell of the notebook can also be updated?

Thanks! @madhavajay @H4LL

**Comment by PalexGoneGit** [comment]
Hi @madhavajay @H4LL  I am running into the same issue in the same notebook. Syft_Version = 0.8.4. Is there a fix for this? Many thanks.


![Screenshot 2024-03-04 at 17 17 46](https://github.com/OpenMined/PySyft/assets/60147284/f6ff772a-7908-4d3a-8c3b-cf13bdf72561)

**Comment by koenvanderveen** [comment]
Hey folks, thanks for raising this. We forgot to mention in the notebook that we now need a manually install the dependency. Also, error handling should definitely be improved here. Please use 
```
pip install opendp
```
and it will work

**Comment by PalexGoneGit** [comment]
Thanks @koenvanderveen ! I tried installing and importing opendp in all notebooks but the error persists. Is there something else which should be done? ![image](https://github.com/OpenMined/PySyft/assets/60147284/9685c2c8-45a8-4588-9825-03b653701e9f)
