### ISSUE TITLE
04-jax-example.ipynb can only be run once without adjustments

### ISSUE THREAD

**Issue by PalexGoneGit** [OpenMined/PySyft#8564]
## Description
04-jax-example.ipynb is working fine, but only is executable once. After the first time of running the notebook, every other run the error "SyftError: The code to be submitted (name and content) already exists" shows up. The error does not disappear after restarting the kernel or landing the node. The only workaround I found is renaming the function every time you run the notebook.

The issue with that is that it discourages (especially newbies like me) from playing around with the notebook. A more elegant solution directly in the notebook making it repeatable without adjustments would improve it.

## Are you interested in working on this improvement yourself?
- No, I am not (as I don't know how it can be improved specifically)

**Comment by koenvanderveen** [comment]
You can add reset=True to sy.orchestra.launch if you want to run it again.
