### ISSUE TITLE
jaxlib AVX instructions error in Conda on Apple Silicon

### ISSUE THREAD

**Issue by petermchale** [OpenMined/PySyft#8705]
## How to Reproduce
On an Apple M1 Pro, create a new conda environment, install pysyft using `pip install -U syft[data_science]`, and then attempt to start a server and a client using the directions in the README. You'll get a runtime error: 

```
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

## Expected Behavior
I expect not to get this error on a machine that is likely quite popular among data scientists. 

## Screenshots
<img width="1714" alt="Screenshot 2024-04-14 at 12 30 04 PM" src="https://github.com/OpenMined/PySyft/assets/19557137/9e4cd4c9-1fcd-4bc4-894e-f7c65fce30b2">
<img width="1722" alt="Screenshot 2024-04-14 at 12 33 41 PM" src="https://github.com/OpenMined/PySyft/assets/19557137/2a89b35b-8f47-423e-9808-83fe612432b0">

## System Information
 - OS: macOS 
 - OS Version: 14.4.1 (Sonoma)
 - Language Version: Python 3.12.2
 - Package Manager Version: conda 22.9.0, pip 23.3.1
 - Browser (if applicable): n/a
 - Browser Version (if applicable): n/a

**Comment by madhavajay** [comment]
Hi @petermchale we use Apple Silicon daily. If I have to guess its because your version of conda might actually be for `x86` not for apple silicon.

This is a common problem.

You can verify by checking with:
```
>>> import platform
>>> platform.platform()
'macOS-13.5.2-arm64-arm-64bit'
```

It should say `arm` but it might say `x86`.

The problem with running python in rosetta emulation mode is that it uses the `jaxlib` x86 libraries which are compiled with `AVX` instructions and rosetta is unable to emulate those special cpu instructions.

Either uninstall and re-install it with the `arm64` version, or use something like `pyenv` to install a different native global python3 version and then use that to install syft.

**Comment by petermchale** [comment]
<img width="730" alt="Screenshot 2024-04-15 at 9 01 01 PM" src="https://github.com/OpenMined/PySyft/assets/19557137/99a2597e-40b7-4bf5-9b2c-1e34b4b492a3">

**Comment by petermchale** [comment]
I've uninstalled my current conda, and will try re-installing the arm64 conda tomorrow.

**Comment by madhavajay** [comment]
@petermchale Yes, you are running python in `x86` emulation mode. You need to install an Apple Silicon native `arm64` version of python.

Unfortunately I can't give you a link as it looks like all of anacondas package downloads are behind a login now.

**Comment by petermchale** [comment]
<img width="813" alt="Screenshot 2024-04-16 at 7 17 51 AM" src="https://github.com/OpenMined/PySyft/assets/19557137/f5791e92-9fe1-4de0-b763-d53c2b846a61">

**Comment by petermchale** [comment]
```pip install -U syft[data_science]``` is now much faster than it was in x86 emulation mode.

**Comment by petermchale** [comment]
<img width="851" alt="Screenshot 2024-04-16 at 7 34 36 AM" src="https://github.com/OpenMined/PySyft/assets/19557137/010e5ae1-39e2-4f71-9c8a-7933a491bd76">
<img width="1272" alt="Screenshot 2024-04-16 at 7 34 11 AM" src="https://github.com/OpenMined/PySyft/assets/19557137/3eb6699e-301e-4062-be6e-e492824bcb97">
<img width="1563" alt="Screenshot 2024-04-16 at 7 33 42 AM" src="https://github.com/OpenMined/PySyft/assets/19557137/3ed02fc9-711a-4707-ab6f-0ba03acc92bb">

**Comment by petermchale** [comment]
Thanks for the prompt help in getting this set up.

**Comment by petermchale** [comment]
May I suggest updating the README to indicate that users should make sure to use the arm64 version of conda, not the x86 version? @madhavajay
