### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Smartappli** [OpenMined/PySyft#8762]
## Question
Is ipv6 supported?

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by madhavajay** [comment]
Hi @Smartappli is there a particular use case that you want IPV6 for?

**Comment by Smartappli** [comment]
Hi @madhavajay  IoMT (Internet of Medical Things) uses abundantly IPv6.  More concretely I'm trying to develop my federated learning platform based on PySyft :) [Artificial Intelligence for Medical Research](https://github.com/Smartappli/AIMER)

**Comment by madhavajay** [comment]
@Smartappli Are you intending to deploy using straight python, a single docker container or kubernetes?

**Comment by madhavajay** [comment]
@Smartappli are you interested in providing a PR for this functionality, otherwise I can add it to our backlog and we can let you know when it comes up in future.

**Comment by Smartappli** [comment]
> @Smartappli are you interested in providing a PR for this functionality, otherwise I can add it to our backlog and we can let you know when it comes up in future.

@madhavajay I'll do a PR but I'm willing to help :) https://github.com/OpenMined/PySyft/pull/8877
