### ISSUE TITLE
01-data-scientist-submit-code.ipynb have some problem

### ISSUE THREAD

**Issue by amostsai** [OpenMined/PySyft#8782]
## Where?
01-data-scientist-submit-code.ipynb

## What?
1. Executing "new_project.create_code_request(obj=mnist_3_linear_layers, client=ds_client)" results in "SyftError: The code to be submitted (name and content) already exists."
2. Executing "project = new_project.start()" results in "Creating default worker image with tag='local-dev' Building default worker image with tag=local-dev Setting up worker poolname=default-pool workers=0 image_uid=e56eaccabde64b5ab89db5c92cb29113 in_memory=True Default worker pool error. Invalid number of workers: 0."

Is there any missing code in this example program?

## Additional Context
Ubuntu 23.10
python 3.11.6
syft 0.8.7b7

**Comment by amostsai** [comment]
![image](https://github.com/OpenMined/PySyft/assets/3417521/78343b9a-0678-4f05-8896-262495d80b55)

**Comment by IrinaMBejan** [comment]
Hi @amostsai, thanks a lot for reporting the issue! Would you mind sharing your notebook so we can replicate the issue?

**Comment by madhavajay** [comment]
@amostsai the Orchestra constructor takes params that allow you to specify additional settings:
```python
node = sy.orchestra.launch(
  ...,
  create_producer=True,
  n_consumers=1
)
```

Are you able to share the code you created so we can understand the issue more?

It looks like its saying you have submitted your code already (which is fine, it just means you need to have it approved and then use it), and the second issue is that if you start a python server without consumers it won't do any of the background work.

**Comment by madhavajay** [comment]
I will close this for now as there has been no response @amostsai if you can supply the steps you took I can re-open the issue and address it.
