### ISSUE TITLE
Unable to login to domain node via UI

### ISSUE THREAD

**Issue by rj3d** [OpenMined/PySyft#8815]
## Description
When I start a domain node with hagrid and go to http://localhost:8081/login, I am presented with a page that does not have a login form. I have the same issue on both Mac and Ubuntu running on an ec2 instance. The issue persists even if I reset the login password via the Python library.

## How to Reproduce
1. Start a domain node with hagrid (e.g. hagrid launch domain)
2. Once the deployment is up, navigate to http://localhost:8081/login in your browser.

## Expected Behavior
I expect to be presented with a page that has a login form.

## Screenshots
<img width="947" alt="Screenshot 2024-05-14 at 11 38 00 AM" src="https://github.com/OpenMined/PySyft/assets/4079100/3c856fef-6764-456c-802c-093ad5df2cf4">

## System Information
 - Packages: hagrid 0.3.121
 - Branch:  0.8.6
 - OS: macOS 14.4.1 and Ubuntu 20.04
 - Language Version: Python 3.12.2
 - Package Manager Version: Conda 24.5.0
 - Browser (if applicable): Chrome 124.0.6367.202 and Firefox 125.0.3

### Linux
`{"datetime": "14/05/2024 19:11:17 UTC", "python_binary": "/home/ubuntu/miniconda3/bin/python", "dependencies": {"docker": "/usr/bin/docker", "git": "/usr/bin/git", "ansible-playbook": "/home/ubuntu/.local/bin/ansible-playbook"}, "environment": {"uname": ["Linux", "ip-10-4-38-69", "5.13.0-1025-aws", "#27~20.04.1-Ubuntu SMP Thu May 19 15:17:13 UTC 2022", "x86_64", "x86_64"], "platform": "linux", "os_version": "5.13.0-1025-aws", "python_version": "3.12.2", "os": "Linux", "apple_silicon": false}, "hagrid": "0.3.121", "hagrid_dev": false, "hagrid_path": "/home/ubuntu/miniconda3/lib/python3.12/site-packages", "hagrid_repo_sha": "b07cbc84bb4898d5710e90d4149b9e890b210392", "docker": "Client:\n Context:    default\n Debug Mode: false\n Plugins:\n  compose: Docker Compose (Docker Inc., v2.27.0)\n\nServer:\n Containers: 132\n  Running: 12\n  Paused: 0\n  Stopped: 120\n Images: 793\n Server Version: 20.10.21\n Storage Driver: overlay2\n  Backing Filesystem: extfs\n  Supports d_type: true\n  Native Overlay Diff: true\n  userxattr: false\n Logging Driver: json-file\n Cgroup Driver: cgroupfs\n Cgroup Version: 1\n Plugins:\n  Volume: local\n  Network: bridge host ipvlan macvlan null overlay\n  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog\n Swarm: inactive\n Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc\n Default Runtime: runc\n Init Binary: docker-init\n containerd version: \n runc version: \n init version: \n Security Options:\n  apparmor\n  seccomp\n   Profile: default\n Kernel Version: 5.13.0-1025-aws\n Operating System: Ubuntu 20.04.5 LTS\n OSType: linux\n Architecture: x86_64\n CPUs: 4\n Total Memory: 15.37GiB\n Name: ip-10-4-38-69\n ID: HIXC:RISR:5KM3:NO5N:JPMU:FKYE:SFUG:T6JO:Z2QP:5OYE:YUWF:MSRD\n Docker Root Dir: /var/lib/docker\n Debug Mode: false\n Registry: https://index.docker.io/v1/\n Labels:\n Experimental: false\n Insecure Registries:\n  127.0.0.0/8\n Live Restore Enabled: false\n\n"}`
### Mac
`{"datetime": "14/05/2024 12:12:14 PDT", "python_binary": "/Users/rschiemann/miniconda3/bin/python", "dependencies": {"docker": "/opt/homebrew/bin/docker", "git": "/opt/homebrew/bin/git", "ansible-playbook": "/Users/rschiemann/miniconda3/bin/ansible-playbook"}, "environment": {"uname": ["Darwin", "GB-RX2FQDYFYC", "23.4.0", "Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000", "arm64", "arm"], "platform": "darwin", "os_version": "23.4.0", "python_version": "3.12.3", "os": "macOS", "apple_silicon": true}, "hagrid": "0.3.121", "hagrid_dev": false, "hagrid_path": "/Users/rschiemann/miniconda3/lib/python3.12/site-packages", "hagrid_repo_sha": "b07cbc84bb4898d5710e90d4149b9e890b210392", "docker": "Client: Docker Engine - Community\n Version:    24.0.5\n Context:    desktop-linux\n Debug Mode: false\n Plugins:\n  buildx: Docker Buildx (Docker Inc.)\n    Version:  v0.12.1-desktop.4\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-buildx\n  compose: Docker Compose (Docker Inc.)\n    Version:  v2.24.6-desktop.1\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-compose\n  debug: Get a shell into any image or container. (Docker Inc.)\n    Version:  0.0.24\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-debug\n  dev: Docker Dev Environments (Docker Inc.)\n    Version:  v0.1.0\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-dev\n  extension: Manages Docker extensions (Docker Inc.)\n    Version:  v0.2.22\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-extension\n  feedback: Provide feedback, right in your terminal! (Docker Inc.)\n    Version:  v1.0.4\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-feedback\n  init: Creates Docker-related starter files for your project (Docker Inc.)\n    Version:  v1.0.1\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-init\n  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)\n    Version:  0.6.0\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-sbom\n  scout: Docker Scout (Docker Inc.)\n    Version:  v1.5.0\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-scout\n\nServer:\n Containers: 6\n  Running: 0\n  Paused: 0\n  Stopped: 6\n Images: 17\n Server Version: 25.0.3\n Storage Driver: overlay2\n  Backing Filesystem: extfs\n  Supports d_type: true\n  Using metacopy: false\n  Native Overlay Diff: true\n  userxattr: false\n Logging Driver: json-file\n Cgroup Driver: cgroupfs\n Cgroup Version: 2\n Plugins:\n  Volume: local\n  Network: bridge host ipvlan macvlan null overlay\n  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog\n Swarm: inactive\n Runtimes: io.containerd.runc.v2 runc\n Default Runtime: runc\n Init Binary: docker-init\n containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb\n runc version: v1.1.12-0-g51d5e94\n init version: de40ad0\n Security Options:\n  seccomp\n   Profile: unconfined\n  cgroupns\n Kernel Version: 6.6.16-linuxkit\n Operating System: Docker Desktop\n OSType: linux\n Architecture: aarch64\n CPUs: 10\n Total Memory: 11.67GiB\n Name: docker-desktop\n ID: 34924f5e-4cb1-425f-b167-a10cbe584a68\n Docker Root Dir: /var/lib/docker\n Debug Mode: false\n HTTP Proxy: http.docker.internal:3128\n HTTPS Proxy: http.docker.internal:3128\n No Proxy: hubproxy.docker.internal\n Experimental: false\n Insecure Registries:\n  hubproxy.docker.internal:5555\n  127.0.0.0/8\n Live Restore Enabled: false\n\n"}`

**Comment by rj3d** [comment]
I am able to see a login page if I use the 0.8.0 version Docker containers launched using `hagrid launch domain  --tag 0.8.0`. The command just hangs if I specify the tag as 0.8.1. Everything from 0.8.2 onward doesn't present me with a login page.

**Comment by madhavajay** [comment]
Hi @rj3d the frontend is currently disabled. The cap'n'proto serialization layer for our JS api is not complete and there are new features in the Python API which aren't yet supported. We are currently focused on providing a richer interface experience within Jupyter first.

**Comment by madhavajay** [comment]
I will close this issue for now.
