### ISSUE TITLE
Check domain health fails in the install wizard Jupyter notebook

### ISSUE THREAD

**Issue by rj3d** [OpenMined/PySyft#8821]
## Description
When running the install wizard Jupyter notebook via `hagrid quickstart`, the notebook fails on `Step 7. Check Domain Health`. `Step 6. Start a Test Domain` appears to successfully create a new node, and I am able to connect to the node with `sy.login()`. However, Step 7 gets stuck with the output `Waiting for Container Creation` and eventually times out. Additionally, if I attempt to navigate to the node in my browser, I am presented with the JSON `{"detail":"Not Found"}`.

## How to Reproduce
1. Run `hagrid quickstart`
2. Open the notebook `00-quickstart.ipynb` and run all of the cells.
3. Open the notebook `01-install-wizard.ipynb` and run all of the cells up to Step 7.
4. Run the cell in Step 7 with the contents `hagrid.check("localhost:8081", timeout=120)`

## Expected Behavior
I expect to be able to complete the install wizard Jupyter notebook without any issues. 

## Screenshots

Successful starting a test domain, but stuck on container creation.

<img width="1150" alt="Screenshot 2024-05-15 at 10 18 44 AM" src="https://github.com/OpenMined/PySyft/assets/4079100/0bd46342-57c3-4c4c-b2b0-f0f83eb29162">

Eventual time out.

<img width="1155" alt="Screenshot 2024-05-15 at 10 28 35 AM" src="https://github.com/OpenMined/PySyft/assets/4079100/e9dcd55a-32a8-4961-8a35-cecbc34e574f">

Browser response.

<img width="267" alt="Screenshot 2024-05-15 at 10 30 48 AM" src="https://github.com/OpenMined/PySyft/assets/4079100/7c1d458d-9fe6-406a-b996-8346d8af65fe">

## System Information
 - Packages: hagrid 0.3.121
 - Branch:  0.8.6
 - OS: macOS 14.4.1
 - Language Version: Python 3.12.3
 - Package Manager Version: Conda 24.5.0
 - Browser (if applicable): Chrome 124.0.6367.202

## Hagrid Debug Output
`{"datetime": "15/05/2024 10:23:37 PDT", "python_binary": "/Users/rschiemann/miniconda3/bin/python", "dependencies": {"docker": "/opt/homebrew/bin/docker", "git": "/opt/homebrew/bin/git", "ansible-playbook": "/Users/rschiemann/miniconda3/bin/ansible-playbook"}, "environment": {"uname": ["Darwin", "GB-RX2FQDYFYC", "23.4.0", "Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000", "arm64", "arm"], "platform": "darwin", "os_version": "23.4.0", "python_version": "3.12.3", "os": "macOS", "apple_silicon": true}, "hagrid": "0.3.121", "hagrid_dev": false, "hagrid_path": "/Users/rschiemann/miniconda3/lib/python3.12/site-packages", "hagrid_repo_sha": "b07cbc84bb4898d5710e90d4149b9e890b210392", "docker": "Client: Docker Engine - Community\n Version:    24.0.5\n Context:    desktop-linux\n Debug Mode: false\n Plugins:\n  buildx: Docker Buildx (Docker Inc.)\n    Version:  v0.13.1-desktop.1\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-buildx\n  compose: Docker Compose (Docker Inc.)\n    Version:  v2.26.1-desktop.1\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-compose\n  debug: Get a shell into any image or container. (Docker Inc.)\n    Version:  0.0.27\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-debug\n  dev: Docker Dev Environments (Docker Inc.)\n    Version:  v0.1.2\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-dev\n  extension: Manages Docker extensions (Docker Inc.)\n    Version:  v0.2.23\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-extension\n  feedback: Provide feedback, right in your terminal! (Docker Inc.)\n    Version:  v1.0.4\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-feedback\n  init: Creates Docker-related starter files for your project (Docker Inc.)\n    Version:  v1.1.0\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-init\n  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)\n    Version:  0.6.0\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-sbom\n  scout: Docker Scout (Docker Inc.)\n    Version:  v1.6.3\n    Path:     /Users/rschiemann/.docker/cli-plugins/docker-scout\n\nServer:\n Containers: 0\n  Running: 0\n  Paused: 0\n  Stopped: 0\n Images: 53\n Server Version: 26.0.0\n Storage Driver: overlay2\n  Backing Filesystem: extfs\n  Supports d_type: true\n  Using metacopy: false\n  Native Overlay Diff: true\n  userxattr: false\n Logging Driver: json-file\n Cgroup Driver: cgroupfs\n Cgroup Version: 2\n Plugins:\n  Volume: local\n  Network: bridge host ipvlan macvlan null overlay\n  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog\n Swarm: inactive\n Runtimes: runc io.containerd.runc.v2\n Default Runtime: runc\n Init Binary: docker-init\n containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb\n runc version: v1.1.12-0-g51d5e94\n init version: de40ad0\n Security Options:\n  seccomp\n   Profile: unconfined\n  cgroupns\n Kernel Version: 6.6.22-linuxkit\n Operating System: Docker Desktop\n OSType: linux\n Architecture: aarch64\n CPUs: 10\n Total Memory: 11.67GiB\n Name: docker-desktop\n ID: 34924f5e-4cb1-425f-b167-a10cbe584a68\n Docker Root Dir: /var/lib/docker\n Debug Mode: false\n HTTP Proxy: http.docker.internal:3128\n HTTPS Proxy: http.docker.internal:3128\n No Proxy: hubproxy.docker.internal\n Labels:\n  com.docker.desktop.address=unix:///Users/rschiemann/Library/Containers/com.docker.docker/Data/docker-cli.sock\n Experimental: false\n Insecure Registries:\n  hubproxy.docker.internal:5555\n  127.0.0.0/8\n Live Restore Enabled: false\n\n"}`

**Comment by rasswanth-s** [comment]
Hello @rj3d 

Hagrid is soon to be deprecated.
We are currently creating a new set of documentation with regarding the new deployment types.

This is being done in the PR: https://github.com/OpenMined/PySyft/pull/8796

This would be soon merged to DEV.

Those set of notebooks, would be our new quickstart notebook.

**Comment by rj3d** [comment]
Thanks for this information @rasswanth-s!

**Comment by rasswanth-s** [comment]
This PR is merged to DEV 
It is available here
https://github.com/OpenMined/PySyft/tree/dev/notebooks/tutorials/deployments

**Comment by madhavajay** [comment]
Closing this issue for now as hagrid is deprecated.
