### ISSUE TITLE
Grammatical Mistake in the About Section

### ISSUE THREAD

**Issue by adityaraute** [OpenMined/PySyft#8907]
## Where?
About section of the repo

## Who?
Viewers of the repo

## What?
Currently the section says
`Perform data science on data that remains in someone else's server`

This is grammatically incorrect. A better phrasing would be
`Perform data science operations on data that remains in someone else's server`

**Comment by Smartappli** [comment]
https://github.com/OpenMined/PySyft/pull/8909

**Comment by adityaraute** [comment]
> #8909

You've made changes in the README but I was talking about the About section. Both should be changed.

**Comment by madhavajay** [comment]
Hi @adityaraute its a tagline and was chosen specifically to be terse, so it doesn't need to be grammatically correct. I will close this issue.
