### ISSUE TITLE
Issue when doing pip install syft 

### ISSUE THREAD

**Issue by msinghal10** [OpenMined/PySyft#9350]
Hello,

I am trying to install pip install syft==0.9.1 on my Mac M3, however, whenever I try to do this I get an issue which I am showing here:
![image](https://github.com/user-attachments/assets/a0ac1ddb-5222-4e32-a23a-99c5dde744b3)

**Comment by madhavajay** [comment]
@msinghal10 can you tell me what version of pyhton you are using, pycapnp uses binary wheels.
https://pypi.org/project/pycapnp/2.0.0/#files

Its likely they haven't released a wheel for your platform tuple, which is python version, os version, hardware version. My guess is you could be using python 3.13 or conda or something.

If you want compilation to work you need a few things like `cmake`
https://github.com/capnproto/pycapnp

**Comment by msinghal10** [comment]
Python version that i have is 3.13. Should I downgrade it to 3.12 for it to work?


—


Mohit Singhal, Ph.D.

________________________________

**Comment by msinghal10** [comment]
Closing the issue, as when i downgraded to 3.12, it worked.

**Comment by madhavajay** [comment]
Yes, we basically can't support the new python when its released until the DL libraries like torch and tensorflow do and they usually don't release a version for all platforms for a little while.
